/**
 * Compacte runtimecatalogus voor Schriftpersonages.
 *
 * De uitgebreide registry in docs/scripture/ blijft de visuele bron van waarheid,
 * maar hoort niet als historische metadata in iedere clientbundle. Deze catalogus
 * bewaart alleen wat renderers, mappings en servervalidatie nodig hebben.
 */
export type CharacterGender = "male" | "female" | "unknown";
export type CharacterAvailability = "A" | "B" | "C" | "D" | "not-proposed";

export interface CharacterAsset {
  readonly id: string;
  readonly name: string;
  readonly gender: CharacterGender;
  readonly role: string;
  readonly availability: CharacterAvailability;
  readonly avatarAllowed: boolean;
  readonly toolsSuitable: boolean;
  readonly bustCompact: string;
  readonly bustDetail: string;
  readonly avatar: string;
  readonly fullBody: string;
  readonly accessibilityLabel: string;
}

export const CHARACTER_ASSETS = {
  "aaron": {
    id: "aaron",
    name: "Aäron",
    gender: "male",
    role: "Zoon van Mosiah; zendeling die Lamoni’s vader onderwijst.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/aaron/portraits/aaron-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/aaron/portraits/aaron-portrait-1024-v1.webp",
    avatar: "/scripture/characters/aaron/portraits/aaron-portrait-256-v1.webp",
    fullBody: "/scripture/characters/aaron/master/aaron-master-v1.webp",
    accessibilityLabel: "Aäron",
  },
  "abinadi": {
    id: "abinadi",
    name: "Abinadi",
    gender: "male",
    role: "Profeet die voor koning Noach getuigt.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/abinadi/portraits/abinadi-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/abinadi/portraits/abinadi-portrait-1024-v1.webp",
    avatar: "/scripture/characters/abinadi/portraits/abinadi-portrait-256-v1.webp",
    fullBody: "/scripture/characters/abinadi/master/abinadi-master-v1.webp",
    accessibilityLabel: "Abinadi",
  },
  "alma-elder": {
    id: "alma-elder",
    name: "Alma de oudere",
    gender: "male",
    role: "Alma de oudere; leert het volk en doopt bij de wateren van Mormon.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/alma-elder/portraits/alma-elder-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/alma-elder/portraits/alma-elder-portrait-1024-v1.webp",
    avatar: "/scripture/characters/alma-elder/portraits/alma-elder-portrait-256-v1.webp",
    fullBody: "/scripture/characters/alma-elder/master/alma-elder-master-v1.webp",
    accessibilityLabel: "Alma de oudere",
  },
  "alma-younger": {
    id: "alma-younger",
    name: "Alma de jonge",
    gender: "male",
    role: "Zoon van Alma; komt tot bekering en onderwijst het volk.",
    availability: "B",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/alma-younger/portraits/alma-younger-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/alma-younger/portraits/alma-younger-portrait-1024-v1.webp",
    avatar: "/scripture/characters/alma-younger/portraits/alma-younger-portrait-256-v1.webp",
    fullBody: "/scripture/characters/alma-younger/master/alma-younger-master-v1.webp",
    accessibilityLabel: "Alma de jonge",
  },
  "amalickiah": {
    id: "amalickiah",
    name: "Amalickiah",
    gender: "male",
    role: "Amalickiah; tegenstander van Moroni en koning van de Lamanieten.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/amalickiah/portraits/amalickiah-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/amalickiah/portraits/amalickiah-portrait-1024-v1.webp",
    avatar: "/scripture/characters/amalickiah/portraits/amalickiah-portrait-256-v1.webp",
    fullBody: "/scripture/characters/amalickiah/master/amalickiah-master-v1.webp",
    accessibilityLabel: "Amalickiah",
  },
  "amlici": {
    id: "amlici",
    name: "Amlici",
    gender: "male",
    role: "Amlici; wil koning worden en leidt een opstand.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/amlici/portraits/amlici-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/amlici/portraits/amlici-portrait-1024-v1.webp",
    avatar: "/scripture/characters/amlici/portraits/amlici-portrait-256-v1.webp",
    fullBody: "/scripture/characters/amlici/master/amlici-master-v1.webp",
    accessibilityLabel: "Amlici",
  },
  "ammaron": {
    id: "ammaron",
    name: "Ammaron",
    gender: "male",
    role: "Bewaarder van de kronieken die Mormon over de platen vertelt.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/ammaron/portraits/ammaron-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/ammaron/portraits/ammaron-portrait-1024-v1.webp",
    avatar: "/scripture/characters/ammaron/portraits/ammaron-portrait-256-v1.webp",
    fullBody: "/scripture/characters/ammaron/master/ammaron-master-v1.webp",
    accessibilityLabel: "Ammaron",
  },
  "ammon-expedition": {
    id: "ammon-expedition",
    name: "Ammon, leider van de expeditie",
    gender: "male",
    role: "Ammon die met een groep het volk van Limhi vindt; andere persoon dan de zoon van Mosiah.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/ammon-expedition/portraits/ammon-expedition-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/ammon-expedition/portraits/ammon-expedition-portrait-1024-v1.webp",
    avatar: "/scripture/characters/ammon-expedition/portraits/ammon-expedition-portrait-256-v1.webp",
    fullBody: "/scripture/characters/ammon-expedition/master/ammon-expedition-master-v1.webp",
    accessibilityLabel: "Ammon, leider van de expeditie",
  },
  "ammon-missionary": {
    id: "ammon-missionary",
    name: "Ammon, zoon van Mosiah",
    gender: "male",
    role: "Zoon van Mosiah; dient koning Lamoni en onderwijst hem.",
    availability: "A",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/ammon-missionary/portraits/ammon-missionary-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/ammon-missionary/portraits/ammon-missionary-portrait-1024-v1.webp",
    avatar: "/scripture/characters/ammon-missionary/portraits/ammon-missionary-portrait-256-v1.webp",
    fullBody: "/scripture/characters/ammon-missionary/master/ammon-missionary-master-v1.webp",
    accessibilityLabel: "Ammon, zoon van Mosiah",
  },
  "amulek": {
    id: "amulek",
    name: "Amulek",
    gender: "male",
    role: "Onderwijst samen met Alma in Ammonihah.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/amulek/portraits/amulek-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/amulek/portraits/amulek-portrait-1024-v1.webp",
    avatar: "/scripture/characters/amulek/portraits/amulek-portrait-256-v1.webp",
    fullBody: "/scripture/characters/amulek/master/amulek-master-v1.webp",
    accessibilityLabel: "Amulek",
  },
  "captain-moroni": {
    id: "captain-moroni",
    name: "Aanvoerder Moroni",
    gender: "male",
    role: "Opperbevelhebber Moroni; voert het vrijheidsvaandel. Andere persoon dan Mormons zoon.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/captain-moroni/portraits/captain-moroni-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/captain-moroni/portraits/captain-moroni-portrait-1024-v1.webp",
    avatar: "/scripture/characters/captain-moroni/portraits/captain-moroni-portrait-256-v1.webp",
    fullBody: "/scripture/characters/captain-moroni/master/captain-moroni-master-v1.webp",
    accessibilityLabel: "Aanvoerder Moroni",
  },
  "corianton": {
    id: "corianton",
    name: "Corianton",
    gender: "male",
    role: "Zoon van Alma; ontvangt raad van zijn vader.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/corianton/portraits/corianton-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/corianton/portraits/corianton-portrait-1024-v1.webp",
    avatar: "/scripture/characters/corianton/portraits/corianton-portrait-256-v1.webp",
    fullBody: "/scripture/characters/corianton/master/corianton-master-v1.webp",
    accessibilityLabel: "Corianton",
  },
  "coriantumr": {
    id: "coriantumr",
    name: "Coriantumr",
    gender: "male",
    role: "Jareditische koning in het slot van Ether.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/coriantumr/portraits/coriantumr-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/coriantumr/portraits/coriantumr-portrait-1024-v1.webp",
    avatar: "/scripture/characters/coriantumr/portraits/coriantumr-portrait-256-v1.webp",
    fullBody: "/scripture/characters/coriantumr/master/coriantumr-master-v1.webp",
    accessibilityLabel: "Coriantumr",
  },
  "enos": {
    id: "enos",
    name: "Enos",
    gender: "male",
    role: "Enos; bidt om vergeving en voor zijn volk.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/enos/portraits/enos-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/enos/portraits/enos-portrait-1024-v1.webp",
    avatar: "/scripture/characters/enos/portraits/enos-portrait-256-v1.webp",
    fullBody: "/scripture/characters/enos/master/enos-master-v1.webp",
    accessibilityLabel: "Enos",
  },
  "ether": {
    id: "ether",
    name: "Ether",
    gender: "male",
    role: "Jareditische profeet en schrijver.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/ether/portraits/ether-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/ether/portraits/ether-portrait-1024-v1.webp",
    avatar: "/scripture/characters/ether/portraits/ether-portrait-256-v1.webp",
    fullBody: "/scripture/characters/ether/master/ether-master-v1.webp",
    accessibilityLabel: "Ether",
  },
  "gideon": {
    id: "gideon",
    name: "Gideon",
    gender: "male",
    role: "Gideon; verzet zich tegen Noach en helpt het volk van Limhi.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/gideon/portraits/gideon-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/gideon/portraits/gideon-portrait-1024-v1.webp",
    avatar: "/scripture/characters/gideon/portraits/gideon-portrait-256-v1.webp",
    fullBody: "/scripture/characters/gideon/master/gideon-master-v1.webp",
    accessibilityLabel: "Gideon",
  },
  "hagoth": {
    id: "hagoth",
    name: "Hagoth",
    gender: "male",
    role: "Hagoth; bouwt schepen.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/hagoth/portraits/hagoth-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/hagoth/portraits/hagoth-portrait-1024-v1.webp",
    avatar: "/scripture/characters/hagoth/portraits/hagoth-portrait-256-v1.webp",
    fullBody: "/scripture/characters/hagoth/master/hagoth-master-v1.webp",
    accessibilityLabel: "Hagoth",
  },
  "heavenly-father": {
    id: "heavenly-father",
    name: "Onze hemelse Vader",
    gender: "male",
    role: "Hemelse Vader in het inleidende verhaal over Joseph Smith; geen menselijke Boek van Mormon-avatar.",
    availability: "not-proposed",
    avatarAllowed: false,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/heavenly-father/portraits/heavenly-father-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/heavenly-father/portraits/heavenly-father-portrait-1024-v1.webp",
    avatar: "/scripture/characters/heavenly-father/portraits/heavenly-father-portrait-256-v1.webp",
    fullBody: "/scripture/characters/heavenly-father/master/heavenly-father-cutout-v1.webp",
    accessibilityLabel: "Onze hemelse Vader",
  },
  "helam": {
    id: "helam",
    name: "Helam",
    gender: "male",
    role: "Wordt door Alma gedoopt in de wateren van Mormon.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/helam/portraits/helam-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/helam/portraits/helam-portrait-1024-v1.webp",
    avatar: "/scripture/characters/helam/portraits/helam-portrait-256-v1.webp",
    fullBody: "/scripture/characters/helam/master/helam-master-v1.webp",
    accessibilityLabel: "Helam",
  },
  "helaman-son-alma": {
    id: "helaman-son-alma",
    name: "Helaman, zoon van Alma",
    gender: "male",
    role: "Zoon van Alma; leidt de tweeduizend jonge strijders.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/helaman-son-alma/portraits/helaman-son-alma-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/helaman-son-alma/portraits/helaman-son-alma-portrait-1024-v1.webp",
    avatar: "/scripture/characters/helaman-son-alma/portraits/helaman-son-alma-portrait-256-v1.webp",
    fullBody: "/scripture/characters/helaman-son-alma/master/helaman-son-alma-master-v1.webp",
    accessibilityLabel: "Helaman, zoon van Alma",
  },
  "helaman-son-helaman": {
    id: "helaman-son-helaman",
    name: "Helaman, zoon van Helaman",
    gender: "male",
    role: "Helaman, zoon van Helaman; vader van Nephi en Lehi.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/helaman-son-helaman/portraits/helaman-son-helaman-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/helaman-son-helaman/portraits/helaman-son-helaman-portrait-1024-v1.webp",
    avatar: "/scripture/characters/helaman-son-helaman/portraits/helaman-son-helaman-portrait-256-v1.webp",
    fullBody: "/scripture/characters/helaman-son-helaman/master/helaman-son-helaman-master-v1.webp",
    accessibilityLabel: "Helaman, zoon van Helaman",
  },
  "himni": {
    id: "himni",
    name: "Himni",
    gender: "male",
    role: "Zoon van Mosiah; zendeling.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/himni/portraits/himni-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/himni/portraits/himni-portrait-1024-v1.webp",
    avatar: "/scripture/characters/himni/portraits/himni-portrait-256-v1.webp",
    fullBody: "/scripture/characters/himni/master/himni-master-v1.webp",
    accessibilityLabel: "Himni",
  },
  "ismael": {
    id: "ismael",
    name: "Ismaël",
    gender: "male",
    role: "Ismaël; reist met zijn familie met Lehi’s gezin mee.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/ismael/portraits/ismael-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/ismael/portraits/ismael-portrait-1024-v1.webp",
    avatar: "/scripture/characters/ismael/portraits/ismael-portrait-256-v1.webp",
    fullBody: "/mysterie-003b-onderzoeker/ismael.png",
    accessibilityLabel: "Ismaël",
  },
  "jacob-son-lehi": {
    id: "jacob-son-lehi",
    name: "Jakob, zoon van Lehi",
    gender: "male",
    role: "Zoon van Lehi; profeet en schrijver van het boek Jakob.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/jacob-son-lehi/portraits/jacob-son-lehi-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/jacob-son-lehi/portraits/jacob-son-lehi-portrait-1024-v1.webp",
    avatar: "/scripture/characters/jacob-son-lehi/portraits/jacob-son-lehi-portrait-256-v1.webp",
    fullBody: "/scripture/characters/jacob-son-lehi/master/jacob-master-v1.webp",
    accessibilityLabel: "Jakob, zoon van Lehi",
  },
  "jared": {
    id: "jared",
    name: "Jared",
    gender: "male",
    role: "Jared; reist met zijn broer, familie en vrienden.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/jared/portraits/jared-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/jared/portraits/jared-portrait-1024-v1.webp",
    avatar: "/scripture/characters/jared/portraits/jared-portrait-256-v1.webp",
    fullBody: "/scripture/characters/jared/master/jared-master-v1.webp",
    accessibilityLabel: "Jared",
  },
  "jesus-christ": {
    id: "jesus-christ",
    name: "Jezus Christus",
    gender: "male",
    role: "Jezus Christus; bezoekt en onderwijst het volk in 3 Nephi.",
    availability: "D",
    avatarAllowed: false,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/jesus-christ/portraits/jesus-christ-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/jesus-christ/portraits/jesus-christ-portrait-1024-v1.webp",
    avatar: "/scripture/characters/jesus-christ/portraits/jesus-christ-portrait-256-v1.webp",
    fullBody: "/scripture/characters/jesus-christ/master/jesus-christ-cutout-v1.webp",
    accessibilityLabel: "Jezus Christus",
  },
  "joseph-smith": {
    id: "joseph-smith",
    name: "Joseph Smith",
    gender: "male",
    role: "Joseph Smith in het inleidende verhaal over de komst van het Boek van Mormon; buiten het tijdvak van de Boek van Mormon-personages.",
    availability: "not-proposed",
    avatarAllowed: false,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/joseph-smith/portraits/joseph-smith-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/joseph-smith/portraits/joseph-smith-portrait-1024-v1.webp",
    avatar: "/scripture/characters/joseph-smith/portraits/joseph-smith-portrait-256-v1.webp",
    fullBody: "/scripture/characters/joseph-smith/master/joseph-smith-cutout-v1.webp",
    accessibilityLabel: "Joseph Smith",
  },
  "king-benjamin": {
    id: "king-benjamin",
    name: "Koning Benjamin",
    gender: "male",
    role: "Koning Benjamin; spreekt zijn volk vanaf een toren toe.",
    availability: "B",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/king-benjamin/portraits/king-benjamin-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/king-benjamin/portraits/king-benjamin-portrait-1024-v1.webp",
    avatar: "/scripture/characters/king-benjamin/portraits/king-benjamin-portrait-256-v1.webp",
    fullBody: "/scripture/characters/king-benjamin/master/king-benjamin-master-v1.webp",
    accessibilityLabel: "Koning Benjamin",
  },
  "king-limhi": {
    id: "king-limhi",
    name: "Koning Limhi",
    gender: "male",
    role: "Koning Limhi; zoon van Noach, leider van het volk dat bevrijd wordt.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/king-limhi/portraits/king-limhi-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/king-limhi/portraits/king-limhi-portrait-1024-v1.webp",
    avatar: "/scripture/characters/king-limhi/portraits/king-limhi-portrait-256-v1.webp",
    fullBody: "/scripture/characters/king-limhi/master/king-limhi-master-v1.webp",
    accessibilityLabel: "Koning Limhi",
  },
  "king-noah": {
    id: "king-noah",
    name: "Koning Noah",
    gender: "male",
    role: "Koning Noach; zoon van Zeniff, koning in het verhaal van Abinadi.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/king-noah/portraits/king-noah-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/king-noah/portraits/king-noah-portrait-1024-v1.webp",
    avatar: "/scripture/characters/king-noah/portraits/king-noah-portrait-256-v1.webp",
    fullBody: "/scripture/characters/king-noah/master/king-noah-adult-master-v1.webp",
    accessibilityLabel: "Koning Noah",
  },
  "korihor": {
    id: "korihor",
    name: "Korihor",
    gender: "male",
    role: "Korihor; ondervraagt Alma en verzet zich tegen diens leer.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/korihor/portraits/korihor-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/korihor/portraits/korihor-portrait-1024-v1.webp",
    avatar: "/scripture/characters/korihor/portraits/korihor-portrait-256-v1.webp",
    fullBody: "/scripture/characters/korihor/master/korihor-master-v1.webp",
    accessibilityLabel: "Korihor",
  },
  "laban": {
    id: "laban",
    name: "Laban",
    gender: "male",
    role: "Laban; bewaart de koperen platen in Jeruzalem.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/laban/portraits/laban-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/laban/portraits/laban-portrait-1024-v1.webp",
    avatar: "/scripture/characters/laban/portraits/laban-portrait-256-v1.webp",
    fullBody: "/mysterie-002b-onderzoeker/laban.png",
    accessibilityLabel: "Laban",
  },
  "laman": {
    id: "laman",
    name: "Laman",
    gender: "male",
    role: "Zoon van Lehi en Sariah; broer van Nephi.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/laman/portraits/laman-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/laman/portraits/laman-portrait-1024-v1.webp",
    avatar: "/scripture/characters/laman/portraits/laman-portrait-256-v1.webp",
    fullBody: "/mysterie-001a-ontdekker/laman.png",
    accessibilityLabel: "Laman",
  },
  "lamoni": {
    id: "lamoni",
    name: "Lamoni",
    gender: "male",
    role: "Lamanitische koning die door Ammon wordt onderwezen.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/lamoni/portraits/lamoni-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/lamoni/portraits/lamoni-portrait-1024-v1.webp",
    avatar: "/scripture/characters/lamoni/portraits/lamoni-portrait-256-v1.webp",
    fullBody: "/scripture/characters/lamoni/master/lamoni-master-v1.webp",
    accessibilityLabel: "Lamoni",
  },
  "lamoni-father": {
    id: "lamoni-father",
    name: "Lamoni’s vader",
    gender: "male",
    role: "Vader van Lamoni; koning die door Aäron wordt onderwezen.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/lamoni-father/portraits/lamoni-father-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/lamoni-father/portraits/lamoni-father-portrait-1024-v1.webp",
    avatar: "/scripture/characters/lamoni-father/portraits/lamoni-father-portrait-256-v1.webp",
    fullBody: "/scripture/characters/lamoni-father/master/lamoni-father-master-v1.webp",
    accessibilityLabel: "Lamoni’s vader",
  },
  "lehi": {
    id: "lehi",
    name: "Lehi",
    gender: "male",
    role: "Lehi; vader van Nephi, leidt zijn gezin uit Jeruzalem.",
    availability: "A",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/lehi/portraits/lehi-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/lehi/portraits/lehi-portrait-1024-v1.webp",
    avatar: "/scripture/characters/lehi/portraits/lehi-portrait-256-v1.webp",
    fullBody: "/mysterie-001a-ontdekker/lehi.png",
    accessibilityLabel: "Lehi",
  },
  "lehi-son-helaman": {
    id: "lehi-son-helaman",
    name: "Lehi, zoon van Helaman",
    gender: "male",
    role: "Lehi, zoon van Helaman; onderwijst samen met zijn broer Nephi.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/lehi-son-helaman/portraits/lehi-son-helaman-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/lehi-son-helaman/portraits/lehi-son-helaman-portrait-1024-v1.webp",
    avatar: "/scripture/characters/lehi-son-helaman/portraits/lehi-son-helaman-portrait-256-v1.webp",
    fullBody: "/scripture/characters/lehi-son-helaman/master/lehi-son-helaman-master-v1.webp",
    accessibilityLabel: "Lehi, zoon van Helaman",
  },
  "lemuel": {
    id: "lemuel",
    name: "Lemuël",
    gender: "male",
    role: "Zoon van Lehi en Sariah; broer van Nephi.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/lemuel/portraits/lemuel-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/lemuel/portraits/lemuel-portrait-1024-v1.webp",
    avatar: "/scripture/characters/lemuel/portraits/lemuel-portrait-256-v1.webp",
    fullBody: "/mysterie-001a-ontdekker/lemuel.png",
    accessibilityLabel: "Lemuël",
  },
  "mormon": {
    id: "mormon",
    name: "Mormon",
    gender: "male",
    role: "Mormon; legerleider en samensteller van de kronieken.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/mormon/portraits/mormon-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/mormon/portraits/mormon-portrait-1024-v1.webp",
    avatar: "/scripture/characters/mormon/portraits/mormon-portrait-256-v1.webp",
    fullBody: "/scripture/characters/mormon/master/mormon-master-v1.webp",
    accessibilityLabel: "Mormon",
  },
  "moroni-son-mormon": {
    id: "moroni-son-mormon",
    name: "Moroni, zoon van Mormon",
    gender: "male",
    role: "Zoon van Mormon; voltooit en bewaart de kronieken. Niet opperbevelhebber Moroni.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/moroni-son-mormon/portraits/moroni-son-mormon-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/moroni-son-mormon/portraits/moroni-son-mormon-portrait-1024-v1.webp",
    avatar: "/scripture/characters/moroni-son-mormon/portraits/moroni-son-mormon-portrait-256-v1.webp",
    fullBody: "/scripture/characters/moroni-son-mormon/master/moroni-son-mormon-master-v1.webp",
    accessibilityLabel: "Moroni, zoon van Mormon",
  },
  "mosiah-son-benjamin": {
    id: "mosiah-son-benjamin",
    name: "Mosiah, zoon van Benjamin",
    gender: "male",
    role: "Mosiah, zoon van Benjamin; koning en vader van de vier zendelingen.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/mosiah-son-benjamin/portraits/mosiah-son-benjamin-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/mosiah-son-benjamin/portraits/mosiah-son-benjamin-portrait-1024-v1.webp",
    avatar: "/scripture/characters/mosiah-son-benjamin/portraits/mosiah-son-benjamin-portrait-256-v1.webp",
    fullBody: "/scripture/characters/mosiah-son-benjamin/master/mosiah-son-benjamin-master-v1.webp",
    accessibilityLabel: "Mosiah, zoon van Benjamin",
  },
  "nehor": {
    id: "nehor",
    name: "Nehor",
    gender: "male",
    role: "Nehor; onderwijst een andere leer en doodt Gideon.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/nehor/portraits/nehor-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/nehor/portraits/nehor-portrait-1024-v1.webp",
    avatar: "/scripture/characters/nehor/portraits/nehor-portrait-256-v1.webp",
    fullBody: "/scripture/characters/nehor/master/nehor-master-v1.webp",
    accessibilityLabel: "Nehor",
  },
  "nephi": {
    id: "nephi",
    name: "Nephi",
    gender: "male",
    role: "Nephi, zoon van Lehi; schrijver en leider van zijn familie.",
    availability: "A",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/nephi/portraits/nephi-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/nephi/portraits/nephi-portrait-1024-v1.webp",
    avatar: "/scripture/characters/nephi/portraits/nephi-portrait-256-v1.webp",
    fullBody: "/mysterie-001c-schriftkenner/nephi.png",
    accessibilityLabel: "Nephi",
  },
  "nephi-son-helaman": {
    id: "nephi-son-helaman",
    name: "Nephi, zoon van Helaman",
    gender: "male",
    role: "Nephi, zoon van Helaman; broer van Lehi en profeet.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/nephi-son-helaman/portraits/nephi-son-helaman-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/nephi-son-helaman/portraits/nephi-son-helaman-portrait-1024-v1.webp",
    avatar: "/scripture/characters/nephi-son-helaman/portraits/nephi-son-helaman-portrait-256-v1.webp",
    fullBody: "/scripture/characters/nephi-son-helaman/master/nephi-son-helaman-master-v1.webp",
    accessibilityLabel: "Nephi, zoon van Helaman",
  },
  "nephi-son-nephi": {
    id: "nephi-son-nephi",
    name: "Nephi, zoon van Nephi",
    gender: "male",
    role: "Nephi, zoon van Nephi; profeet in het verhaal van Christus’ geboorte en komst.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/nephi-son-nephi/portraits/nephi-son-nephi-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/nephi-son-nephi/portraits/nephi-son-nephi-portrait-1024-v1.webp",
    avatar: "/scripture/characters/nephi-son-nephi/portraits/nephi-son-nephi-portrait-256-v1.webp",
    fullBody: "/scripture/characters/nephi-son-nephi/master/nephi-son-nephi-master-v1.webp",
    accessibilityLabel: "Nephi, zoon van Nephi",
  },
  "omner": {
    id: "omner",
    name: "Omner",
    gender: "male",
    role: "Zoon van Mosiah; zendeling.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/omner/portraits/omner-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/omner/portraits/omner-portrait-1024-v1.webp",
    avatar: "/scripture/characters/omner/portraits/omner-portrait-256-v1.webp",
    fullBody: "/scripture/characters/omner/master/omner-master-v1.webp",
    accessibilityLabel: "Omner",
  },
  "pahoran": {
    id: "pahoran",
    name: "Pahoran",
    gender: "male",
    role: "Pahoran; opperrechter met wie Moroni correspondeert.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/pahoran/portraits/pahoran-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/pahoran/portraits/pahoran-portrait-1024-v1.webp",
    avatar: "/scripture/characters/pahoran/portraits/pahoran-portrait-256-v1.webp",
    fullBody: "/scripture/characters/pahoran/master/pahoran-master-v1.webp",
    accessibilityLabel: "Pahoran",
  },
  "sam": {
    id: "sam",
    name: "Sam",
    gender: "male",
    role: "Zoon van Lehi en Sariah; broer van Nephi.",
    availability: "A",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/sam/portraits/sam-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/sam/portraits/sam-portrait-1024-v1.webp",
    avatar: "/scripture/characters/sam/portraits/sam-portrait-256-v1.webp",
    fullBody: "/mysterie-001b-onderzoeker/sam.png",
    accessibilityLabel: "Sam",
  },
  "samuel-lamanite": {
    id: "samuel-lamanite",
    name: "Samuël de Lamaniet",
    gender: "male",
    role: "Samuel de Lamaniet; profeteert vanaf de stadsmuur.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/samuel-lamanite/portraits/samuel-lamanite-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/samuel-lamanite/portraits/samuel-lamanite-portrait-1024-v1.webp",
    avatar: "/scripture/characters/samuel-lamanite/portraits/samuel-lamanite-portrait-256-v1.webp",
    fullBody: "/scripture/characters/samuel-lamanite/master/samuel-lamanite-master-v1.webp",
    accessibilityLabel: "Samuël de Lamaniet",
  },
  "sariah": {
    id: "sariah",
    name: "Sariah",
    gender: "female",
    role: "Sariah; vrouw van Lehi en moeder in zijn gezin.",
    availability: "A",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/sariah/portraits/sariah-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/sariah/portraits/sariah-portrait-1024-v1.webp",
    avatar: "/scripture/characters/sariah/portraits/sariah-portrait-256-v1.webp",
    fullBody: "/mysterie-001a-ontdekker/sariah.png",
    accessibilityLabel: "Sariah",
  },
  "sherem": {
    id: "sherem",
    name: "Sherem",
    gender: "male",
    role: "Sherem; ondervraagt Jakob.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/sherem/portraits/sherem-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/sherem/portraits/sherem-portrait-1024-v1.webp",
    avatar: "/scripture/characters/sherem/portraits/sherem-portrait-256-v1.webp",
    fullBody: "/scripture/characters/sherem/master/sherem-master-v1.webp",
    accessibilityLabel: "Sherem",
  },
  "shiblon": {
    id: "shiblon",
    name: "Shiblon",
    gender: "male",
    role: "Zoon van Alma; ontvangt raad en bewaart later de kronieken.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/shiblon/portraits/shiblon-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/shiblon/portraits/shiblon-portrait-1024-v1.webp",
    avatar: "/scripture/characters/shiblon/portraits/shiblon-portrait-256-v1.webp",
    fullBody: "/scripture/characters/shiblon/master/shiblon-master-v1.webp",
    accessibilityLabel: "Shiblon",
  },
  "shiz": {
    id: "shiz",
    name: "Shiz",
    gender: "male",
    role: "Jareditische legeraanvoerder tegenover Coriantumr.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/shiz/portraits/shiz-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/shiz/portraits/shiz-portrait-1024-v1.webp",
    avatar: "/scripture/characters/shiz/portraits/shiz-portrait-256-v1.webp",
    fullBody: "/scripture/characters/shiz/master/shiz-master-v1.webp",
    accessibilityLabel: "Shiz",
  },
  "zeezrom": {
    id: "zeezrom",
    name: "Zeezrom",
    gender: "male",
    role: "Ondervraagt Amulek; wordt later door Alma genezen en gedoopt.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/zeezrom/portraits/zeezrom-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/zeezrom/portraits/zeezrom-portrait-1024-v1.webp",
    avatar: "/scripture/characters/zeezrom/portraits/zeezrom-portrait-256-v1.webp",
    fullBody: "/scripture/characters/zeezrom/master/zeezrom-master-v1.webp",
    accessibilityLabel: "Zeezrom",
  },
  "zeniff": {
    id: "zeniff",
    name: "Zeniff",
    gender: "male",
    role: "Zeniff; leidt een groep terug naar het land van hun voorouders; vader van Noach.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/zeniff/portraits/zeniff-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/zeniff/portraits/zeniff-portrait-1024-v1.webp",
    avatar: "/scripture/characters/zeniff/portraits/zeniff-portrait-256-v1.webp",
    fullBody: "/scripture/characters/zeniff/master/zeniff-older-master-v1.webp",
    accessibilityLabel: "Zeniff",
  },
  "zerahemnah": {
    id: "zerahemnah",
    name: "Zerahemnah",
    gender: "male",
    role: "Lamanitische legeraanvoerder tegenover Moroni.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/zerahemnah/portraits/zerahemnah-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/zerahemnah/portraits/zerahemnah-portrait-1024-v1.webp",
    avatar: "/scripture/characters/zerahemnah/portraits/zerahemnah-portrait-256-v1.webp",
    fullBody: "/scripture/characters/zerahemnah/master/zerahemnah-master-v1.webp",
    accessibilityLabel: "Zerahemnah",
  },
  "zoram": {
    id: "zoram",
    name: "Zoram",
    gender: "male",
    role: "Zoram; sluit zich aan bij Nephi en zijn familie.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/zoram/portraits/zoram-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/zoram/portraits/zoram-portrait-1024-v1.webp",
    avatar: "/scripture/characters/zoram/portraits/zoram-portrait-256-v1.webp",
    fullBody: "/mysterie-002c-schriftkenner/zoram.png",
    accessibilityLabel: "Zoram",
  },
  "amulon": {
    id: "amulon",
    name: "amulon",
    gender: "male",
    role: "Priester van Noach; onderdrukt later het volk van Alma.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/amulon/portraits/amulon-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/amulon/portraits/amulon-portrait-1024-v1.webp",
    avatar: "/scripture/characters/amulon/portraits/amulon-portrait-256-v1.webp",
    fullBody: "/scripture/characters/amulon/master/amulon-master-v1.webp",
    accessibilityLabel: "amulon",
  },
  "angel-alma": {
    id: "angel-alma",
    name: "Engel die Alma bezocht, rolcanon",
    gender: "male",
    role: "De engel die aan Alma en de zonen van Mosiah verschijnt; geen eigen naam in de tekst.",
    availability: "not-proposed",
    avatarAllowed: false,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/angel-alma/portraits/angel-alma-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/angel-alma/portraits/angel-alma-portrait-1024-v1.webp",
    avatar: "/scripture/characters/angel-alma/portraits/angel-alma-portrait-256-v1.webp",
    fullBody: "/scripture/characters/angel-alma/master/angel-alma-master-v1.webp",
    accessibilityLabel: "Engel die Alma bezocht, rolcanon",
  },
  "brother-of-jared": {
    id: "brother-of-jared",
    name: "De broer van Jared",
    gender: "male",
    role: "Broer van Jared; spreekt met de Heer en leidt samen met Jared zijn familie.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/brother-of-jared/portraits/brother-of-jared-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/brother-of-jared/portraits/brother-of-jared-portrait-1024-v1.webp",
    avatar: "/scripture/characters/brother-of-jared/portraits/brother-of-jared-portrait-256-v1.webp",
    fullBody: "/scripture/characters/brother-of-jared/master/brother-of-jared-master-v1.webp",
    accessibilityLabel: "De broer van Jared",
  },
  "church-disciple": {
    id: "church-disciple",
    name: "Naamloze discipel, rolcanon",
    gender: "male",
    role: "Representatieve leerling uit de verhaalillustraties; geen vastgestelde individuele identiteit.",
    availability: "not-proposed",
    avatarAllowed: false,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/church-disciple/portraits/church-disciple-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/church-disciple/portraits/church-disciple-portrait-1024-v1.webp",
    avatar: "/scripture/characters/church-disciple/portraits/church-disciple-portrait-256-v1.webp",
    fullBody: "/scripture/characters/church-disciple/master/church-disciple-master-v1.webp",
    accessibilityLabel: "Naamloze discipel, rolcanon",
  },
  "jaredite-king-role": {
    id: "jaredite-king-role",
    name: "Naamloze vroege Jaredietische koning, rolcanon",
    gender: "male",
    role: "Representatieve Jareditische koning; niet zonder tekstbewijs aan Coriantumr of een andere naam koppelen.",
    availability: "not-proposed",
    avatarAllowed: false,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/jaredite-king-role/portraits/jaredite-king-role-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/jaredite-king-role/portraits/jaredite-king-role-portrait-1024-v1.webp",
    avatar: "/scripture/characters/jaredite-king-role/portraits/jaredite-king-role-portrait-256-v1.webp",
    fullBody: "/scripture/characters/jaredite-king-role/master/jaredite-king-role-master-v1.webp",
    accessibilityLabel: "Naamloze vroege Jaredietische koning, rolcanon",
  },
  "jaredite-prophet-role": {
    id: "jaredite-prophet-role",
    name: "Naamloze Jaredietische profeet, rolcanon",
    gender: "male",
    role: "Representatieve Jareditische profeet; geen vastgestelde identiteit en niet hetzelfde ontwerp als Ether.",
    availability: "not-proposed",
    avatarAllowed: false,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/jaredite-prophet-role/portraits/jaredite-prophet-role-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/jaredite-prophet-role/portraits/jaredite-prophet-role-portrait-1024-v1.webp",
    avatar: "/scripture/characters/jaredite-prophet-role/portraits/jaredite-prophet-role-portrait-256-v1.webp",
    fullBody: "/scripture/characters/jaredite-prophet-role/master/jaredite-prophet-role-master-v1.webp",
    accessibilityLabel: "Naamloze Jaredietische profeet, rolcanon",
  },
  "joseph-son-lehi": {
    id: "joseph-son-lehi",
    name: "Jozef, zoon van Lehi",
    gender: "male",
    role: "Jozef, zoon van Lehi en Sariah; andere persoon dan Joseph Smith.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/joseph-son-lehi/portraits/joseph-son-lehi-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/joseph-son-lehi/portraits/joseph-son-lehi-portrait-1024-v1.webp",
    avatar: "/scripture/characters/joseph-son-lehi/portraits/joseph-son-lehi-portrait-256-v1.webp",
    fullBody: "/scripture/characters/joseph-son-lehi/master/joseph-son-lehi-master-v1.webp",
    accessibilityLabel: "Jozef, zoon van Lehi",
  },
  "king-laman": {
    id: "king-laman",
    name: "Koning Laman",
    gender: "male",
    role: "Koning Laman in het verhaal van Zeniff; andere persoon dan Lehi’s zoon Laman.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/king-laman/portraits/king-laman-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/king-laman/portraits/king-laman-portrait-1024-v1.webp",
    avatar: "/scripture/characters/king-laman/portraits/king-laman-portrait-256-v1.webp",
    fullBody: "/scripture/characters/king-laman/master/king-laman-master-v1.webp",
    accessibilityLabel: "Koning Laman",
  },
  "lehi-dream-guide": {
    id: "lehi-dream-guide",
    name: "Man in wit gewaad uit Lehi’s droom",
    gender: "male",
    role: "Naamloze man die Lehi in zijn droom begeleidt; niet Jezus Christus.",
    availability: "not-proposed",
    avatarAllowed: false,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/lehi-dream-guide/portraits/lehi-dream-guide-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/lehi-dream-guide/portraits/lehi-dream-guide-portrait-1024-v1.webp",
    avatar: "/scripture/characters/lehi-dream-guide/portraits/lehi-dream-guide-portrait-256-v1.webp",
    fullBody: "/scripture/characters/lehi-dream-guide/master/lehi-dream-guide-cutout-v1.webp",
    accessibilityLabel: "Man in wit gewaad uit Lehi’s droom",
  },
  "nephi-wife": {
    id: "nephi-wife",
    name: "Nephi’s vrouw (naam niet vermeld)",
    gender: "female",
    role: "Naamloze vrouw van Nephi, een dochter van Ismaël; geen verzonnen eigennaam.",
    availability: "A",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/nephi-wife/portraits/nephi-wife-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/nephi-wife/portraits/nephi-wife-portrait-1024-v1.webp",
    avatar: "/scripture/characters/nephi-wife/portraits/nephi-wife-portrait-256-v1.webp",
    fullBody: "/scripture/characters/nephi-wife/master/nephi-wife-cutout-v1.webp",
    accessibilityLabel: "Nephi’s vrouw (naam niet vermeld)",
  },
  "nephihah": {
    id: "nephihah",
    name: "Nephihah",
    gender: "male",
    role: "Nephihah; opperrechter na Alma.",
    availability: "C",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/nephihah/portraits/nephihah-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/nephihah/portraits/nephihah-portrait-1024-v1.webp",
    avatar: "/scripture/characters/nephihah/portraits/nephihah-portrait-256-v1.webp",
    fullBody: "/scripture/characters/nephihah/master/nephihah-master-v1.webp",
    accessibilityLabel: "Nephihah",
  },
  "zoramite-worshipper": {
    id: "zoramite-worshipper",
    name: "Naamloze Zoramietische aanbidder, rolcanon",
    gender: "male",
    role: "Naamloze Zoramitische aanbidder in het verhaal over de Rameumptom; de exacte individuele identiteit is niet vastgesteld.",
    availability: "C",
    avatarAllowed: false,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/zoramite-worshipper/portraits/zoramite-worshipper-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/zoramite-worshipper/portraits/zoramite-worshipper-portrait-1024-v1.webp",
    avatar: "/scripture/characters/zoramite-worshipper/portraits/zoramite-worshipper-portrait-256-v1.webp",
    fullBody: "/scripture/characters/zoramite-worshipper/master/zoramite-worshipper-master-v1.webp",
    accessibilityLabel: "Naamloze Zoramietische aanbidder, rolcanon",
  },
  "abish": {
    id: "abish",
    name: "Abish",
    gender: "female",
    role: "Lamanitische vrouw in dienst van Lamoni’s vrouw; brengt de mensen bijeen en helpt de koningin opstaan.",
    availability: "A",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/abish/portraits/abish-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/abish/portraits/abish-portrait-1024-v1.webp",
    avatar: "/scripture/characters/abish/portraits/abish-portrait-256-v1.webp",
    fullBody: "/scripture/characters/abish/master/abish-master-v1.webp",
    accessibilityLabel: "Abish",
  },
  "lamoni-wife": {
    id: "lamoni-wife",
    name: "Vrouw van koning Lamoni",
    gender: "female",
    role: "Naamloze koningin; spreekt met Ammon en deelt het getuigenis van haar man.",
    availability: "A",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/lamoni-wife/portraits/lamoni-wife-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/lamoni-wife/portraits/lamoni-wife-portrait-1024-v1.webp",
    avatar: "/scripture/characters/lamoni-wife/portraits/lamoni-wife-portrait-256-v1.webp",
    fullBody: "/scripture/characters/lamoni-wife/master/lamoni-wife-master-v1.webp",
    accessibilityLabel: "Vrouw van koning Lamoni",
  },
  "ismael-wife": {
    id: "ismael-wife",
    name: "Vrouw van Ismaël",
    gender: "female",
    role: "Naamloze vrouw van Ismaël; reist met haar gezin en Lehi’s familie.",
    availability: "B",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/ismael-wife/portraits/ismael-wife-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/ismael-wife/portraits/ismael-wife-portrait-1024-v1.webp",
    avatar: "/scripture/characters/ismael-wife/portraits/ismael-wife-portrait-256-v1.webp",
    fullBody: "/scripture/characters/ismael-wife/master/ismael-wife-master-v1.webp",
    accessibilityLabel: "Vrouw van Ismaël",
  },
  "lamoni-father-wife": {
    id: "lamoni-father-wife",
    name: "Vrouw van Lamoni’s vader",
    gender: "female",
    role: "Naamloze koningin in het verhaal waarin Aäron Lamoni’s vader onderwijst.",
    availability: "B",
    avatarAllowed: true,
    toolsSuitable: true,
    bustCompact: "/scripture/characters/lamoni-father-wife/portraits/lamoni-father-wife-portrait-512-v1.webp",
    bustDetail: "/scripture/characters/lamoni-father-wife/portraits/lamoni-father-wife-portrait-1024-v1.webp",
    avatar: "/scripture/characters/lamoni-father-wife/portraits/lamoni-father-wife-portrait-256-v1.webp",
    fullBody: "/scripture/characters/lamoni-father-wife/master/lamoni-father-wife-master-v1.webp",
    accessibilityLabel: "Vrouw van Lamoni’s vader",
  },
} as const satisfies Record<string, CharacterAsset>;

export type CanonicalCharacterId = keyof typeof CHARACTER_ASSETS;

const CHARACTER_ALIASES: Record<string, CanonicalCharacterId> = {
  "brother-jared": "brother-of-jared",
};
export function normalizeCharacterId(id: string | null | undefined): CanonicalCharacterId | null {
  if (!id) return null;
  const normalized = CHARACTER_ALIASES[id] ?? id;
  return normalized in CHARACTER_ASSETS ? normalized as CanonicalCharacterId : null;
}

export function getCharacterAsset(id: string | null | undefined): CharacterAsset | null {
  const normalized = normalizeCharacterId(id);
  return normalized ? CHARACTER_ASSETS[normalized] : null;
}

export function allCharacterAssets(): readonly CharacterAsset[] {
  return Object.values(CHARACTER_ASSETS);
}

export function avatarCharacterAssets(): readonly CharacterAsset[] {
  return allCharacterAssets().filter((character) => character.avatarAllowed);
}

export function isAvatarCharacterId(id: string | null | undefined): id is CanonicalCharacterId {
  const character = getCharacterAsset(id);
  return !!character?.avatarAllowed;
}

export const MYSTERY_BODY_ASSETS: Readonly<Record<string, string>> = {
  lehi: "/mysterie-001a-ontdekker/lehi.png",
  sariah: "/mysterie-001a-ontdekker/sariah.png",
  laman: "/mysterie-001a-ontdekker/laman.png",
  lemuel: "/mysterie-001a-ontdekker/lemuel.png",
  sam: "/mysterie-001b-onderzoeker/sam.png",
  nephi: "/mysterie-001c-schriftkenner/nephi.png",
  laban: "/mysterie-002b-onderzoeker/laban.png",
  zoram: "/mysterie-002c-schriftkenner/zoram.png",
  ismael: "/mysterie-003b-onderzoeker/ismael.png",
};
