import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 1 Nephi. English edition - generated from Dutch master.
export const nephi1: GeneesChapterSeed[] = [
  ch("1-ne", 1,
    q("a", "5-6", "Wat verscheen er voor Lehi op een rotsblok toen hij tot de Heer bad?", "Een vuurkolom", ["Een witte wolk", "Een lichtende ster"], ["vuurkolom"]),
    q("b", "4", "Van welke koning van Juda wordt het eerste regeringsjaar genoemd toen vele profeten verschenen?", "Koning Zedekia", ["Koning Josia", "Koning Jojakim"], ["Zedekia"]),
    q("c", "11", "Wat gaf de eerste van de twaalf die Lehi in zijn visioen zag aan Lehi om te lezen?", "Een boek", ["Een staf", "Een zwaard"], ["boek"]),
  ),
  ch("1-ne", 2,
    q("a", "2", "Wat gebood de Heer Lehi in een droom te doen?", "Met zijn gezin de wildernis in te trekken", ["Met zijn gezin naar Babylon te vluchten", "Met zijn gezin naar het zuiden te varen"], ["wildernis"]),
    q("b", "8", "Welke naam gaf Lehi aan de rivier die in de Rode Zee uitmondde?", "De rivier Laman", ["De rivier Sam", "De rivier Jordaan"], ["rivier Laman"]),
    q("c", "20", "Wat beloofde de Heer aan Nephi als hij de geboden zou onderhouden?", "Dat hij naar een land van belofte zou worden geleid", ["Dat hij binnen drie dagen weer in Jeruzalem zou zijn", "Dat hij met zijn broers een grote stad zou bouwen"], ["land van belofte"]),
  ),
  ch("1-ne", 3,
    q("a", "3", "Waarop waren de kronieken van de Joden die Laban bezat gegraveerd?", "Op platen van koper", ["Op platen van goud", "Op tafelen van steen"], ["platen van koper"]),
    q("b", "11", "Wie ging als eerste het huis van Laban binnen nadat het lot was geworpen?", "Laman", ["Lemuel", "Nephi"], ["Laman"]),
    q("c", "29", "Wie verscheen er toen Laman en Lemuel hun jongere broers met een stok sloegen?", "Een engel van de Heer", ["Een dienstknecht van Laban", "Een profeet uit Jeruzalem"], ["engel van de Heer"]),
  ),
  ch("1-ne", 4,
    q("a", "18", "Waarmee doodde Nephi Laban?", "Met zijn eigen zwaard", ["Met een koperen speer", "Met een zware knuppel"], ["eigen zwaard"]),
    q("b", "35", "Wat was de naam van de dienstknecht van Laban?", "Zoram", ["Zerah", "Zenos"], ["Zoram"]),
    q("c", "7", "Wat was er met Laban aan de hand toen Nephi hem aantrof?", "Hij was dronken van de wijn", ["Hij was door ziekte neergevallen", "Hij was in een gevecht gewond geraakt"], ["dronken van de wijn"]),
  ),
  ch("1-ne", 5,
    q("a", "11", "Wat bevatten de platen van koper onder meer, toen Lehi ze onderzocht?", "De vijf boeken van Mozes", ["De psalmen van koning David", "De wetten van koning Salomo"], ["vijf boeken van Mozes"]),
    q("b", "14", "Van welke zoon van Jakob bleek Lehi een afstammeling te zijn?", "Jozef", ["Ruben", "Simeon"], ["Jozef"]),
    q("c", "2", "Welk verwijt maakte Sariah haar man toen haar zonen niet terugkwamen?", "Dat hij een man van visioenen was", ["Dat hij te weinig voorraad had meegenomen", "Dat hij de verkeerde weg had gekozen"], ["man van visioenen"]),
  ),
  ch("1-ne", 6,
    q("a", "4", "Tot welke God wil Nephi de mensen ertoe bewegen te komen?", "De God van Abraham, Izak en Jakob", ["De God van Adam, Noach en Mozes", "De God van Henoch, David en Salomo"], ["God van Abraham", "Izak", "Jakob"]),
    q("b", "5", "Welke dingen schrijft Nephi niet op zijn platen?", "Dingen die voor de wereld aangenaam zijn", ["Dingen die alleen over zijn oudere broers gaan", "Dingen die alleen over oorlogen en gevechten gaan"], ["voor de wereld aangenaam"]),
    q("c", "1", "Waar staat het geslachtsregister van Nephi's vaderen opgenomen?", "In de kroniek van zijn vader Lehi", ["Op de platen waarop Nephi nu schrijft", "In de kroniek van de profeet Jeremia"], ["kroniek", "vader"]),
  ),
  ch("1-ne", 7,
    q("a", "2", "Wie moesten Nephi en zijn broers uit Jeruzalem meebrengen?", "Ismaël en zijn gezin", ["Jeremia en zijn gezin", "Zedekia en zijn gezin"], ["Ismaël"]),
    q("b", "16", "Wat deden Laman en Lemuel met Nephi nadat hij hen had toegesproken?", "Ze bonden hem met koorden vast", ["Ze sloegen hem met een stok", "Ze sloten hem op in een grot"], ["koorden vast"]),
    q("c", "21", "Wat deed Nephi toen zijn broers hem om vergeving smeekten?", "Hij schonk hun van harte vergeving", ["Hij eiste dat zij hun zwaarden inleverden", "Hij liet hen eerst een dag lang vasten"], ["vergeving"]),
  ),
  ch("1-ne", 8,
    q("a", "19", "Waarvan was de roede die langs de rivier naar de boom voerde?", "Van ijzer", ["Van hout", "Van koper"], ["ijzer"]),
    q("b", "12", "Wat gebeurde er met Lehi toen hij van de vrucht nam?", "Zijn ziel werd met buitengewoon grote vreugde vervuld", ["Zijn lichaam werd van alle vermoeidheid genezen", "Zijn hart werd met grote droefheid om Laman vervuld"], ["grote vreugde"]),
    q("c", "26", "Waar stond het grote en ruime gebouw dat Lehi zag?", "Hoog in de lucht, boven de aarde", ["Diep in een dal naast de rivier", "Op de top van een berg vol bomen"], ["in de lucht"]),
  ),
  ch("1-ne", 9,
    q("a", "3-4", "Waar gaan de platen waarop Nephi nu schrijft voor het grootste deel over?", "Over de bediening onder zijn volk", ["Over de regering van koningen en oorlogen", "Over de reis van zijn gezin over zee"], ["bediening"]),
    q("b", "1", "In welk dal woonde Lehi in een tent toen hij al deze dingen zag?", "In het dal Lemuel", ["In het dal Laman", "In het dal Zoram"], ["dal Lemuel"]),
    q("c", "5", "Waarom gebood de Heer Nephi deze platen te maken?", "Voor een wijs doel dat Nephi niet kende", ["Omdat de andere platen verloren waren gegaan", "Omdat Lehi daar zelf om had gevraagd"], ["wijs doel"]),
  ),
  ch("1-ne", 10,
    q("a", "4", "Hoeveel jaar nadat Lehi Jeruzalem had verlaten, zou volgens zijn profetie de Messias komen?", "Zeshonderd jaar", ["Driehonderd jaar", "Duizend jaar"], ["zeshonderd jaar"]),
    q("b", "9", "Waar zou de profeet die de weg van de Heer bereidt, dopen?", "In Bethabara, aan de overkant van de Jordaan", ["In Jeruzalem, bij de tempel van de Heer", "In Nazareth, aan de oever van de Rode Zee"], ["Bethabara"]),
    q("c", "12", "Waarmee vergeleek Lehi het huis van Israël?", "Met een olijfboom", ["Met een wijnstok", "Met een vijgenboom"], ["olijfboom"]),
  ),
  ch("1-ne", 11,
    q("a", "1", "Waarheen werd Nephi in de Geest van de Heer weggevoerd?", "Naar een zeer hoge berg", ["Naar een brede vlakte aan zee", "Naar een dal vol rijpe bomen"], ["zeer hoge berg"]),
    q("b", "18", "Wie is de maagd die Nephi zag, volgens de engel?", "De moeder van de Zoon van God", ["De zuster van de profeet Jeremia", "De vrouw van de koning van Juda"], ["moeder van de Zoon van God"]),
    q("c", "22", "Waarvan is de boom volgens Nephi een zinnebeeld?", "De liefde van God voor de mensen", ["De wijsheid van de grote wereld", "De macht van een sterk koninkrijk"], ["liefde van God"]),
  ),
  ch("1-ne", 12,
    q("a", "1", "Waarmee wordt het aantal mensen in Nephi's nageslacht vergeleken?", "Met het zand van de zee", ["Met de sterren van de hemel", "Met de blaren van de bomen"], ["zand van de zee"]),
    q("b", "7-8", "Hoeveel discipelen van het Lam werden gekozen om Nephi's nageslacht te dienen?", "Twaalf", ["Zeven", "Zeventig"], ["twaalf"]),
    q("c", "17", "Waarvoor staat de mist van duisternis volgens de engel?", "De verzoekingen van de duivel", ["De moeilijkheden van de reis", "De twijfel van de gelovigen"], ["verzoekingen van de duivel"]),
  ),
  ch("1-ne", 13,
    q("a", "23", "Wat bevat het boek dat uit de mond van een Jood voortkomt, volgens de engel?", "De verbonden van de Heer met het huis van Israël", ["De wetten van alle volken op de aarde", "De geschiedenis van de koningen van Egypte"], ["verbonden van de Heer", "huis van Israël"]),
    q("b", "12", "Waarheen ging de man onder de andere volken die door de Geest van God werd bewogen?", "Over de vele wateren naar het beloofde land", ["Door de woestijn naar de stad Jeruzalem", "Over de bergen naar het land Egypte"], ["vele wateren", "beloofde land"]),
    q("c", "37", "Wat zullen zij hebben die in de laatste dagen trachten Zion voort te brengen?", "De gave en de macht van de Heilige Geest", ["De rijkdom en de eer van de wereld", "De wijsheid en het gezag van de koningen"], ["gave en de macht van de Heilige Geest"]),
  ),
  ch("1-ne", 14,
    q("a", "27", "Wat was de naam van de apostel van het Lam die de dingen zou opschrijven?", "Johannes", ["Petrus", "Mattheüs"], ["Johannes"]),
    q("b", "10", "Hoeveel kerken zijn er volgens de engel?", "Slechts twee", ["Slechts vier", "Slechts zeven"], ["slechts twee"]),
    q("c", "12", "Hoe was het ledental van de kerk van het Lam van God, volgens Nephi's visioen?", "Klein, maar verspreid over de hele aarde", ["Groot, maar beperkt tot één enkel land", "Even groot als dat van de andere kerk"], ["klein"]),
  ),
  ch("1-ne", 15,
    q("a", "24", "Wat betekende de roede van ijzer volgens Nephi?", "Het woord van God", ["De wet van Mozes", "De kracht van een koning"], ["woord van God"]),
    q("b", "8-9", "Wat hadden Laman en Lemuel niet gedaan om de woorden van hun vader te begrijpen?", "Navraag doen bij de Heer", ["Een offer brengen op een altaar", "De platen van koper raadplegen"], ["navraag"]),
    q("c", "18", "Met welke voorvader sloot de Heer het verbond dat in de laatste dagen zal worden vervuld?", "Abraham", ["Henoch", "Salomo"], ["Abraham"]),
  ),
  ch("1-ne", 16,
    q("a", "10", "Waarvan was de bal van vernuftige makelij gemaakt die Lehi bij zijn tent vond?", "Van zuiver koper", ["Van zuiver goud", "Van gehard staal"], ["zuiver koper"]),
    q("b", "13", "Hoe heette de plaats waar het gezin na vier dagen reizen hun tenten opsloeg?", "Shazer", ["Lemuel", "Jershon"], ["Shazer"]),
    q("c", "18", "Wat gebeurde er toen Nephi uitging om voedsel te doden?", "Zijn boog van zuiver staal brak", ["Zijn pijlen waren allemaal op", "Hij verdwaalde in de wildernis"], ["boog", "staal"]),
  ),
  ch("1-ne", 17,
    q("a", "5", "Hoe noemden zij de zee die zij zagen, en wat betekent die naam?", "Irreantum, wat vele wateren betekent", ["Overvloed, wat vele vruchten betekent", "Shazer, wat rode wateren betekent"], ["Irreantum", "vele wateren"]),
    q("b", "4", "Hoeveel jaar verbleef het gezin in de wildernis?", "Acht jaar", ["Vier jaar", "Twaalf jaar"], ["acht jaar"]),
    q("c", "11", "Waarvan maakte Nephi een blaasbalg om het vuur aan te blazen?", "Van dierenhuiden", ["Van schapenwol", "Van boomschors"], ["dierenhuiden"]),
  ),
  ch("1-ne", 18,
    q("a", "7", "Hoe heetten de twee zonen die Lehi in de wildernis verwekte?", "Jakob en Jozef", ["Enos en Jarom", "Zoram en Sam"], ["Jakob", "Jozef"]),
    q("b", "12", "Wat gebeurde er met het kompas nadat Nephi was vastgebonden?", "Het kompas hield op met werken", ["Het wees de verkeerde kant op", "Het werd door de storm verloren"], ["werken"]),
    q("c", "15", "Hoeveel dagen waren zij teruggedreven toen Nephi's broers begonnen in te zien dat de oordelen van God op hen rustten?", "Vier dagen", ["Twee dagen", "Zeven dagen"], ["vier dagen"]),
  ),
  ch("1-ne", 19,
    q("a", "1", "Waaruit maakte Nephi de platen om de kroniek van zijn volk op te graveren?", "Uit erts", ["Uit zilver", "Uit hout"], ["erts"]),
    q("b", "12", "Welke profeet zegt dat de God van de natuur lijdt?", "Zenos", ["Zenock", "Neum"], ["Zenos"]),
    q("c", "23", "Welke profeet las Nephi zijn broers voor om hen te overtuigen in de Heer te geloven?", "Jesaja", ["Jeremia", "Ezechiël"], ["Jesaja"]),
  ),
  ch("1-ne", 20,
    q("a", "4", "Waarvan is het voorhoofd van het volk van Israël volgens de Heer?", "Van koper", ["Van steen", "Van goud"], ["koper"]),
    q("b", "18", "Waaraan zou de gerechtigheid van Israël zijn gelijk geweest als het de geboden had gehoorzaamd?", "Aan de golven van de zee", ["Aan de bergen van Juda", "Aan de sterren aan de hemel"], ["golven van de zee"]),
    q("c", "20", "Waarvandaan moest het volk volgens de Heer uitgaan?", "Uit Babylon", ["Uit Egypte", "Uit Assyrië"], ["Babylon"]),
  ),
  ch("1-ne", 21,
    q("a", "16", "Waarin heeft de Heer het huis van Israël gegraveerd, zo zegt Hij?", "In zijn handpalmen", ["In een tafel van steen", "Op de muren van de tempel"], ["handpalmen"]),
    q("b", "6", "Waartoe stelt de Heer zijn knecht ook, voor de andere volken?", "Tot een licht", ["Tot een rechter", "Tot een koning"], ["licht"]),
    q("c", "14", "Wat zei Zion over de Heer?", "Dat de Heer haar had verlaten", ["Dat de Heer haar nooit zou vergeven", "Dat de Heer haar tot koningin had gemaakt"], ["verlaten"]),
  ),
  ch("1-ne", 22,
    q("a", "20-21", "Wie was volgens Nephi de profeet van wie Mozes sprak?", "De Heilige van Israël", ["Jesaja, de zoon van Amos", "Lehi, de vader van Nephi"], ["Heilige van Israël"]),
    q("b", "25", "Hoeveel kuddes en herders zullen er zijn wanneer de Heer zijn kinderen vergadert?", "Eén kudde en één Herder", ["Twaalf kuddes en twaalf herders", "Zeven kuddes en één herder"], ["één kudde", "één Herder"]),
    q("c", "30", "Waarvan getuigen de dingen op de platen van koper volgens Nephi?", "Dat men gehoorzaam moet zijn aan de geboden van God", ["Dat men zijn bezittingen aan de armen moet geven", "Dat men elke zevende dag in de tempel moet offeren"], ["gehoorzaam", "geboden van God"]),
  ),
  // ===== EINDE =====
];
