import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 1 Nephi. Each fact is bound to the verses in `verses`; `npm run genees:check` verifies this.
export const nephi1: GeneesChapterSeed[] = [
  ch("1-ne", 1,
    q("a", "5-6", "What appeared to Lehi on a rock when he prayed to the Lord?", "A pillar of fire", ["A white cloud", "A shining star"], ["pillar of fire"]),
    q("b", "4", "Which king of Judah is mentioned in whose first year many prophets appeared?", "King Zedekiah", ["King Josiah", "King Jehoiakim"], ["Zedekiah"]),
    q("c", "11", "What did the first of the twelve whom Lehi saw in his vision give to Lehi to read?", "A book", ["A staff", "A sword"], ["book"]),
  ),
  ch("1-ne", 2,
    q("a", "2", "What did the Lord command Lehi to do in a dream?", "To take his family into the wilderness", ["To flee with his family to Babylon", "To sail with his family to the south"], ["wilderness"]),
    q("b", "8", "What name did Lehi give to the river that emptied into the Red Sea?", "The river Laman", ["The river Sam", "The river Jordan"], ["river Laman"]),
    q("c", "20", "What did the Lord promise Nephi if he would keep the commandments?", "That he would prosper and be led to a land of promise", ["That he would return to Jerusalem within three days", "That he would build a great city with his brothers"], ["land of promise"]),
  ),
  ch("1-ne", 3,
    q("a", "3", "Upon what were the records of the Jews that Laban possessed engraved?", "Upon plates of brass", ["Upon plates of gold", "Upon tablets of stone"], ["plates of brass"]),
    q("b", "11", "Who first entered into the house of Laban after the lot had been cast?", "Laman", ["Lemuel", "Nephi"], ["Laman"]),
    q("c", "29", "Who appeared when Laman and Lemuel smote their younger brothers with a rod?", "An angel of the Lord", ["A servant of Laban", "A prophet from Jerusalem"], ["angel of the Lord"]),
  ),
  ch("1-ne", 4,
    q("a", "18", "With what did Nephi slay Laban?", "With his own sword", ["With a brass spear", "With a heavy club"], ["own sword"]),
    q("b", "35", "What was the name of the servant of Laban?", "Zoram", ["Zerah", "Zenos"], ["Zoram"]),
    q("c", "7", "What was the condition of Laban when Nephi found him?", "He was drunken with wine", ["He was smitten by disease", "He was wounded in battle"], ["drunken with wine"]),
  ),
  ch("1-ne", 5,
    q("a", "11", "What did the plates of brass contain when Lehi examined them?", "The five books of Moses", ["The psalms of King David", "The laws of King Solomon"], ["five books of Moses"]),
    q("b", "14", "Of which son of Jacob was Lehi found to be a descendant?", "Joseph", ["Reuben", "Simeon"], ["Joseph"]),
    q("c", "2", "What reproach did Sariah make unto her husband when her sons did not return?", "That he was a visionary man", ["That he had taken too little provisions", "That he had chosen the wrong way"], ["visionary man"]),
  ),
  ch("1-ne", 6,
    q("a", "4", "Unto what God did Nephi persuade his people to come?", "The God of Abraham, Isaac, and Jacob", ["The God of Adam, Noah, and Moses", "The God of Enoch, David, and Solomon"], ["Abraham", "Isaac", "Jacob"]),
    q("b", "5", "What things does Nephi not write upon his plates?", "Things that are pleasant unto the world", ["Things only about his elder brothers", "Things only about wars and contentions"], ["pleasant unto the world"]),
    q("c", "1", "Where are the generations of Nephi's fathers recorded?", "In the record of his father Lehi", ["Upon the plates whereupon Nephi now writes", "In the record of the prophet Jeremiah"], ["record", "Lehi"]),
  ),
  ch("1-ne", 7,
    q("a", "2", "Whom should Nephi and his brothers bring from Jerusalem?", "Ishmael and his family", ["Jeremiah and his family", "Zedekiah and his family"], ["Ishmael"]),
    q("b", "16", "What did Laman and Lemuel do to Nephi after he spake unto them?", "They bound him with cords", ["They smote him with a rod", "They shut him up in a cave"], ["cords"]),
    q("c", "21", "What did Nephi do when his brothers pleaded with him for forgiveness?", "He freely forgave them", ["He required them to surrender their swords", "He made them fast for a day"], ["forgiveness"]),
  ),
  ch("1-ne", 8,
    q("a", "19", "What was the rod that led along the river toward the tree made of?", "Of iron", ["Of wood", "Of brass"], ["iron"]),
    q("b", "12", "What happened to Lehi when he partook of the fruit?", "His soul was filled with exceedingly great joy", ["His body was healed of all weariness", "His heart was filled with great sorrow for Laman"], ["exceedingly great joy"]),
    q("c", "26", "Where was the great and spacious building that Lehi saw?", "High in the air above the earth", ["Deep in a valley beside the river", "On the top of a mountain full of trees"], ["high in the air"]),
  ),
  ch("1-ne", 9,
    q("a", "3-4", "What do the plates whereupon Nephi writes principally contain?", "The ministry among his people", ["The reign of kings and wars", "The journey of his family over sea"], ["ministry"]),
    q("b", "1", "In what valley did Lehi dwell in a tent when he saw all these things?", "In the valley of Lemuel", ["In the valley of Laman", "In the valley of Zoram"], ["valley of Lemuel"]),
    q("c", "5", "Why did the Lord command Nephi to make these plates?", "For a wise purpose which Nephi knew not", ["Because the other plates had been lost", "Because Lehi himself had requested it"], ["wise purpose"]),
  ),
  ch("1-ne", 10,
    q("a", "4", "How many years after Lehi departed from Jerusalem would the Messiah come according to his prophecy?", "Six hundred years", ["Three hundred years", "One thousand years"], ["six hundred years"]),
    q("b", "9", "Where would the prophet who prepareth the way of the Lord baptize?", "In Bethabara beyond the Jordan", ["In Jerusalem at the temple of the Lord", "In Nazareth on the shore of the Red Sea"], ["Bethabara"]),
    q("c", "12", "Whereunto did Lehi liken the house of Israel?", "To an olive tree", ["To a vine", "To a fig tree"], ["olive tree"]),
  ),
  ch("1-ne", 11,
    q("a", "1", "Whither was Nephi carried away in the Spirit of the Lord?", "To an exceedingly high mountain", ["To a broad plain by the sea", "To a valley full of ripe fruit"], ["exceedingly high mountain"]),
    q("b", "18", "Who is the virgin whom Nephi saw according to the angel?", "The mother of the Son of God", ["The sister of the prophet Jeremiah", "The wife of the king of Judah"], ["mother of the Son of God"]),
    q("c", "22", "What is the tree a representation of according to Nephi?", "The love of God for mankind", ["The wisdom of the great world", "The power of a strong kingdom"], ["love of God"]),
  ),
  ch("1-ne", 12,
    q("a", "1", "Whereunto is the number of people in Nephi's seed compared?", "To the sand of the sea", ["To the stars of heaven", "To the leaves of the trees"], ["sand of the sea"]),
    q("b", "7-8", "How many disciples of the Lamb were chosen to minister unto Nephi's seed?", "Twelve", ["Seven", "Seventy"], ["twelve"]),
    q("c", "17", "What does the mist of darkness stand for according to the angel?", "The temptations of the devil", ["The difficulties of the journey", "The doubts of believers"], ["temptations of the devil"]),
  ),
  ch("1-ne", 13,
    q("a", "23", "What does the book which comes forth out of the mouth of a Jew contain according to the angel?", "The covenants of the Lord with the house of Israel", ["The laws of all people upon the earth", "The history of the kings of Egypt"], ["covenants of the Lord", "house of Israel"]),
    q("b", "12", "Whither went the man among the other people who was moved by the Spirit of God?", "Over the many waters to a land which is choice above all other lands", ["Through the wilderness to the city of Jerusalem", "Over the mountains to the land of Egypt"], ["many waters"]),
    q("c", "37", "What shall they have who in the last days seek to bring forth Zion?", "The gift and power of the Holy Ghost", ["The riches and honor of the world", "The wisdom and authority of kings"], ["gift and power of the Holy Ghost"]),
  ),
  ch("1-ne", 14,
    q("a", "27", "What was the name of the apostle of the Lamb who should write these things?", "John", ["Peter", "Matthew"], ["John"]),
    q("b", "10", "How many churches are there according to the angel?", "Only two", ["Only four", "Only seven"], ["two"]),
    q("c", "12", "How was the membership of the church of the Lamb of God according to Nephi's vision?", "Small but gathered out of all the nations", ["Great but confined to one land", "Equal to that of the other church"], ["small"]),
  ),
  ch("1-ne", 15,
    q("a", "24", "What does the rod of iron signify according to Nephi?", "The word of God", ["The law of Moses", "The power of a king"], ["word of God"]),
    q("b", "8-9", "What had Laman and Lemuel not done to understand the words of their father?", "Inquired of the Lord", ["Made an offering on an altar", "Consulted the plates of brass"], ["inquired"]),
    q("c", "18", "With which forefather did the Lord make the covenant that shall be fulfilled in the last days?", "Abraham", ["Enoch", "Solomon"], ["Abraham"]),
  ),
  ch("1-ne", 16,
    q("a", "10", "What was the ball of curious workmanship made of that Lehi found by his tent?", "Of pure brass", ["Of pure gold", "Of hardened steel"], ["pure brass"]),
    q("b", "13", "What was the place called where the family pitched their tents after four days' journey?", "Shazer", ["Lemuel", "Jershon"], ["Shazer"]),
    q("c", "18", "What happened when Nephi went forth to obtain food?", "His bow of fine steel broke", ["All his arrows were spent", "He became lost in the wilderness"], ["bow", "fine steel"]),
  ),
  ch("1-ne", 17,
    q("a", "5", "What was the name of the sea which they saw and what does it mean?", "Irreantum which means many waters", ["Overvloed which means much fruit", "Shazer which means red waters"], ["Irreantum", "many waters"]),
    q("b", "4", "How many years did the family sojourn in the wilderness?", "Eight years", ["Four years", "Twelve years"], ["eight years"]),
    q("c", "11", "What did Nephi make a bellows of to blow the fire?", "Of skins of beasts", ["Of sheep's wool", "Of bark of trees"], ["skins of beasts"]),
  ),
  ch("1-ne", 18,
    q("a", "7", "What were the names of the two sons whom Lehi begat in the wilderness?", "Jacob and Joseph", ["Enos and Jarom", "Zoram and Sam"], ["Jacob", "Joseph"]),
    q("b", "12", "What happened to the compass after Nephi was bound?", "It ceased to work", ["It pointed the wrong way", "It was lost in the storm"], ["work"]),
    q("c", "15", "How many days were they driven back when Nephi's brothers began to see that the judgments of God rested upon them?", "Four days", ["Two days", "Seven days"], ["four days"]),
  ),
  ch("1-ne", 19,
    q("a", "1", "What did Nephi make the plates of to engrave the record of his people?", "Of ore", ["Of silver", "Of wood"], ["ore"]),
    q("b", "12", "Which prophet says that the God of nature suffers?", "Zenos", ["Zenock", "Neum"], ["Zenos"]),
    q("c", "23", "Which prophet did Nephi read unto his brethren to convince them to believe on the Lord?", "Isaiah", ["Jeremiah", "Ezekiel"], ["Isaiah"]),
  ),
  ch("1-ne", 20,
    q("a", "4", "What was the forehead of the people of Israel according to the Lord?", "Brass", ["Stone", "Gold"], ["brass"]),
    q("b", "18", "Whereunto would the righteousness of Israel have been like if it had hearkened to the commandments?", "To the waves of the sea", ["To the mountains of Judah", "To the stars in heaven"], ["waves of the sea"]),
    q("c", "20", "From whence was the people supposed to go forth according to the Lord?", "Out of Babylon", ["Out of Egypt", "Out of Assyria"], ["Babylon"]),
  ),
  ch("1-ne", 21,
    q("a", "16", "Wherein has the Lord graven the house of Israel saith He?", "In the palms of his hands", ["In a tablet of stone", "On the walls of the temple"], ["palms of his hands"]),
    q("b", "6", "Whereunto does the Lord set up his servant for the other nations?", "For a light", ["For a judge", "For a king"], ["light"]),
    q("c", "14", "What did Zion say concerning the Lord?", "That the Lord had forsaken her", ["That the Lord would never forgive her", "That the Lord had made her a queen"], ["forsaken"]),
  ),
  ch("1-ne", 22,
    q("a", "20-21", "Who was the prophet of whom Moses spake according to Nephi?", "The Holy One of Israel", ["Isaiah the son of Amoz", "Lehi the father of Nephi"], ["Holy One of Israel"]),
    q("b", "25", "How many flocks and shepherds shall there be when the Lord gathers his children?", "One flock and one Shepherd", ["Twelve flocks and twelve shepherds", "Seven flocks and one shepherd"], ["one flock", "one Shepherd"]),
    q("c", "30", "Of what do the things on the plates of brass testify according to Nephi?", "That men must obey the commandments of God", ["That men must give their possessions to the poor", "That men must offer in the temple every seventh day"], ["obey", "commandments of God"]),
  ),
];
