import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 1 Nephi (English edition). Each fact is tied to the verses in `verses`; `npm run genees:check` verifies that.
export const nephi1: GeneesChapterSeed[] = [
  ch("1-ne", 1,
    q("a", "5-6", "What appeared on a rock before Lehi when he prayed to the Lord?", "A pillar of fire", ["A white cloud", "A shining star"], ["pillar of fire"]),
    q("b", "4", "In the first year of which king of Judah did many prophets come and warn the people?", "King Zedekiah", ["King Josiah", "King Jehoiakim"], ["Zedekiah"]),
    q("c", "11", "What did the first of the twelve in Lehi's vision give him to read?", "A book", ["A staff", "A sword"], ["book"]),
  ),
  ch("1-ne", 2,
    q("a", "2", "What did the Lord command Lehi in a dream?", "To take his family into the wilderness", ["To flee with his family to Babylon", "To sail with his family to the south"], ["wilderness"]),
    q("b", "8", "What name did Lehi give to the river that emptied into the Red Sea?", "The river Laman", ["The river Sam", "The river Jordan"], ["river Laman"]),
    q("c", "20", "What did the Lord promise Nephi if he kept the commandments?", "That he would be led to a land of promise", ["That he would return to Jerusalem within three days", "That he would build a great city with his brothers"], ["land of promise"]),
  ),
  ch("1-ne", 3,
    q("a", "3", "On what were the records of the Jews that Laban kept engraved?", "On plates of brass", ["On plates of gold", "On tablets of stone"], ["plates of brass"]),
    q("b", "11", "Who was the first to go into Laban's house after the lots were cast?", "Laman", ["Lemuel", "Nephi"], ["Laman"]),
    q("c", "29", "Who appeared when Laman and Lemuel were beating their younger brothers with a rod?", "An angel of the Lord", ["A servant of Laban", "A prophet from Jerusalem"], ["angel of the Lord"]),
  ),
  ch("1-ne", 4,
    q("a", "18", "What weapon did Nephi use to kill Laban?", "His own sword", ["A brass spear", "A heavy club"], ["own sword"]),
    q("b", "35", "What was the name of Laban's servant?", "Zoram", ["Zerah", "Zenos"], ["Zoram"]),
    q("c", "7", "What was Laban's condition when Nephi found him?", "He was drunk with wine", ["He was struck down by illness", "He was wounded in a fight"], ["drunk", "wine"]),
  ),
  ch("1-ne", 5,
    q("a", "11", "What did the plates of brass contain, as Lehi examined them?", "The five books of Moses", ["The psalms of King David", "The laws of King Solomon"], ["five books of Moses"]),
    q("b", "14", "Of which son of Jacob was Lehi found to be a descendant?", "Joseph", ["Reuben", "Simeon"], ["Joseph"]),
    q("c", "2", "What accusation did Sariah make against her husband when her sons did not return?", "That he was a visionary man", ["That he had taken too few provisions", "That he had chosen the wrong way"], ["visionary man"]),
  ),
  ch("1-ne", 6,
    q("a", "4", "Which God did Nephi want to persuade people to come to?", "The God of Abraham, Isaac, and Jacob", ["The God of Adam, Noah, and Moses", "The God of Enoch, David, and Solomon"], ["Abraham", "Isaac", "Jacob"]),
    q("b", "5", "What kind of things does Nephi not write on his plates?", "Things that are pleasing to the world", ["Things only about his older brothers", "Things only about wars and fighting"], ["pleasing", "world"]),
    q("c", "1", "Where is the genealogy of Nephi's fathers recorded?", "In the record kept by his father", ["On the plates Nephi is writing on now", "In the record of the prophet Jeremiah"], ["record", "father"]),
  ),
  ch("1-ne", 7,
    q("a", "2", "Whom were Nephi and his brothers to bring down from Jerusalem?", "Ishmael and his family", ["Jeremiah and his family", "Zedekiah and his family"], ["Ishmael"]),
    q("b", "16", "What did Laman and Lemuel do to Nephi after he spoke to them?", "They bound him with cords", ["They beat him with a rod", "They shut him in a cave"], ["cords"]),
    q("c", "21", "What did Nephi do when his brothers begged him for forgiveness?", "He frankly forgave them all they had done", ["He required them to surrender their swords", "He made them fast for a day"], ["frankly"]),
  ),
  ch("1-ne", 8,
    q("a", "19", "What was the rod made of that led along the river to the tree?", "Iron", ["Wood", "Brass"], ["iron"]),
    q("b", "12", "What happened to Lehi when he ate the fruit?", "His soul was filled with exceedingly great joy", ["His body was healed of all weariness", "His heart was filled with great sorrow for Laman"], ["great joy"]),
    q("c", "26", "Where did the great and spacious building that Lehi saw stand?", "High in the air above the earth", ["Deep in a valley beside the river", "On the top of a mountain full of trees"], ["in the air"]),
  ),
  ch("1-ne", 9,
    q("a", "3-4", "What do the plates Nephi is writing on now mainly contain?", "The ministry among his people", ["The reign of kings and wars", "The journey of his family over the sea"], ["ministry"]),
    q("b", "1", "In which valley did Lehi live in a tent when he saw all these things?", "In the valley of Lemuel", ["In the valley of Laman", "In the valley of Zoram"], ["valley of Lemuel"]),
    q("c", "5", "Why did the Lord command Nephi to make these plates?", "For a wise purpose that Nephi did not know", ["Because the other plates had been lost", "Because Lehi himself had asked for it"], ["wise purpose"]),
  ),
  ch("1-ne", 10,
    q("a", "4", "How many years after Lehi left Jerusalem would the Messiah come, according to his prophecy?", "Six hundred years", ["Three hundred years", "One thousand years"], ["six hundred years"]),
    q("b", "9", "Where would the prophet who prepares the way of the Lord baptize?", "In Bethabara, beyond the river Jordan", ["In Jerusalem, at the temple of the Lord", "In Nazareth, on the shore of the Red Sea"], ["Bethabara"]),
    q("c", "12", "What did Lehi compare the house of Israel to?", "An olive tree", ["A grapevine", "A fig tree"], ["olive tree"]),
  ),
  ch("1-ne", 11,
    q("a", "1", "Where was Nephi carried away in the Spirit of the Lord?", "To an exceedingly high mountain", ["To a broad plain by the sea", "To a valley full of ripe fruit"], ["exceedingly high mountain"]),
    q("b", "18", "According to the angel, who is the virgin Nephi saw?", "The mother of the Son of God", ["The sister of the prophet Jeremiah", "The wife of the king of Judah"], ["mother of the Son of God"]),
    q("c", "22", "According to Nephi, what does the tree represent?", "The love of God for mankind", ["The wisdom of the great world", "The power of a strong kingdom"], ["love of God"]),
  ),
  ch("1-ne", 12,
    q("a", "1", "What is the number of people in Nephi's seed compared to?", "The sand of the sea", ["The stars of heaven", "The leaves of the trees"], ["sand of the sea"]),
    q("b", "7-8", "How many disciples of the Lamb were chosen to minister to Nephi's seed?", "Twelve", ["Seven", "Seventy"], ["twelve"]),
    q("c", "17", "What do the mists of darkness represent, according to the angel?", "The temptations of the devil", ["The hardships of the journey", "The doubts of believers"], ["temptations of the devil"]),
  ),
  ch("1-ne", 13,
    q("a", "23", "According to the angel, what does the book that proceeds out of the mouth of a Jew contain?", "The covenants of the Lord with the house of Israel", ["The laws given to all the nations of the earth", "The history of the kings and priests of Egypt"], ["covenants of the Lord", "house of Israel"]),
    q("b", "12", "Where did the man among the Gentiles go who was moved upon by the Spirit of God?", "Over the many waters to the promised land", ["Through the wilderness to the city of Jerusalem", "Over the mountains to the land of Egypt"], ["many waters", "promised land"]),
    q("c", "37", "What will those have who seek to bring forth Zion in the last days?", "The gift and power of the Holy Ghost", ["The riches and honor of the world", "The wisdom and authority of kings"], ["Holy Ghost"]),
  ),
  ch("1-ne", 14,
    q("a", "27", "What was the name of the apostle of the Lamb who was to write these things?", "John", ["Peter", "James"], ["John"]),
    q("b", "10", "According to the angel, how many churches are there?", "Only two", ["Only four", "Only seven"], ["two"]),
    q("c", "12", "What was the membership of the church of the Lamb of God like in Nephi's vision?", "Small, but spread across the whole earth", ["Large, but limited to a single land", "As large as that of the other church"], ["small"]),
  ),
  ch("1-ne", 15,
    q("a", "24", "What does the rod of iron represent, according to Nephi?", "The word of God", ["The law of Moses", "The power of a king"], ["word of God"]),
    q("b", "8-9", "What had Laman and Lemuel not done to understand their father's words?", "Inquired of the Lord about them", ["Made an offering on an altar", "Consulted the plates of brass"], ["inquired"]),
    q("c", "18", "With which forefather did the Lord make the covenant that would be fulfilled in the latter days?", "Abraham", ["Enoch", "Solomon"], ["Abraham"]),
  ),
  ch("1-ne", 16,
    q("a", "10", "What was the ball of curious workmanship made of that Lehi found outside his tent?", "Fine brass", ["Fine gold", "Hardened steel"], ["fine brass"]),
    q("b", "13", "What was the place called where the family pitched their tents after four days of travel?", "Shazer", ["Lemuel", "Jershon"], ["Shazer"]),
    q("c", "18", "What happened when Nephi went out to slay food?", "His bow of fine steel broke", ["All his arrows were used up", "He got lost in the wilderness"], ["bow", "fine steel"]),
  ),
  ch("1-ne", 17,
    q("a", "5", "What did they call the sea they saw, and what does the name mean?", "Irreantum, which means many waters", ["Bountiful, which means much fruit", "Shazer, which means red waters"], ["Irreantum", "many waters"]),
    q("b", "4", "How many years did the family sojourn in the wilderness?", "Eight years", ["Four years", "Twelve years"], ["eight years"]),
    q("c", "11", "What did Nephi make a bellows out of to blow the fire?", "Skins of beasts", ["Sheep's wool", "Bark of trees"], ["skins of beasts"]),
  ),
  ch("1-ne", 18,
    q("a", "7", "What were the names of the two sons Lehi fathered in the wilderness?", "Jacob and Joseph", ["Enos and Jarom", "Zoram and Sam"], ["Jacob", "Joseph"]),
    q("b", "12", "What happened to the compass after Nephi was bound?", "It ceased to work at all", ["It pointed the wrong way", "It was lost in the storm"], ["cease"]),
    q("c", "15", "For how many days had they been driven back when Nephi's brothers began to see that God's judgments were upon them?", "Four days", ["Two days", "Seven days"], ["four days"]),
  ),
  ch("1-ne", 19,
    q("a", "1", "What did Nephi make the plates of to engrave the record of his people?", "Plates of ore", ["Plates of silver", "Plates of wood"], ["plates of ore"]),
    q("b", "12", "Which prophet says that the God of nature suffers?", "Zenos", ["Zenock", "Neum"], ["Zenos"]),
    q("c", "23", "Which prophet did Nephi read from to persuade his brothers to believe in the Lord?", "Isaiah", ["Jeremiah", "Ezekiel"], ["Isaiah"]),
  ),
  ch("1-ne", 20,
    q("a", "4", "Of what was the brow of the people of Israel made, according to the Lord?", "Brass", ["Stone", "Gold"], ["brass"]),
    q("b", "18", "What would Israel's righteousness have been like if it had hearkened to the commandments?", "The waves of the sea", ["The mountains of Judah", "The stars in heaven"], ["waves of the sea"]),
    q("c", "20", "Out of what place did the Lord say His people must go forth?", "Out of Babylon", ["Out of Egypt", "Out of Assyria"], ["Babylon"]),
  ),
  ch("1-ne", 21,
    q("a", "16", "Where has the Lord engraved the house of Israel, according to His words?", "On the palms of his hands", ["On a tablet of stone", "On the walls of the temple"], ["palms"]),
    q("b", "6", "What will the Lord give his servant to be for the Gentiles?", "A light", ["A judge", "A king"], ["light"]),
    q("c", "14", "What did Zion say about the Lord?", "That the Lord had forsaken her", ["That the Lord would never forgive her", "That the Lord had made her a queen"], ["forsaken"]),
  ),
  ch("1-ne", 22,
    q("a", "20-21", "According to Nephi, who was the prophet of whom Moses spoke?", "The Holy One of Israel", ["Isaiah, the son of Amoz", "Lehi, the father of Nephi"], ["Holy One of Israel"]),
    q("b", "25", "How many folds and shepherds will there be when the Lord gathers his children?", "One fold and one shepherd", ["Twelve folds and twelve shepherds", "Seven folds and one shepherd"], ["one fold", "one shepherd"]),
    q("c", "30", "What do the things written on the plates of brass testify, according to Nephi?", "That men must obey the commandments of God", ["That men must give their possessions to the poor", "That men must offer in the temple every seventh day"], ["commandments of God"]),
  ),
  // ===== EINDE =====
];
