import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 2 Nephi (English edition). Each fact is tied to the verses in `verses`; `npm run genees:check` verifies that.
export const nephi2: GeneesChapterSeed[] = [
  ch("2-ne", 1,
    q("a", "6", "According to Lehi, who can come into the promised land?", "Only those brought by the hand of the Lord", ["Only those who can build a ship of their own", "Only those with the king's permission"], ["hand of the Lord"]),
    q("b", "30", "Who was Laban's servant whom Lehi called a true friend of Nephi?", "Zoram", ["Jacob", "Ishmael"], ["Zoram"]),
    q("c", "13", "What did Lehi say his sons must awake from?", "From a deep sleep", ["From a long journey", "From a severe illness"], ["deep sleep"]),
  ),
  ch("2-ne", 2,
    q("a", "25", "Why are people here, according to Lehi?", "That they might have joy", ["That they might govern the earth", "That they might gain riches"], ["joy"]),
    q("b", "16", "What did the Lord God grant to man?", "That he should act for himself", ["That he should live without law", "That he should found a kingdom of his own"], ["act for himself"]),
    q("c", "19", "Why were Adam and Eve driven out of the garden of Eden?", "To till the earth", ["To found a new city", "To dwell in a desert"], ["till the earth"]),
  ),
  ch("2-ne", 3,
    q("a", "17", "In what would the Lord give power to the Moses He would raise up, according to Joseph's prophecy?", "In a rod", ["In a sword", "In a scroll"], ["rod"]),
    q("b", "6", "What would the Lord raise up for the fruit of Joseph's loins, according to Joseph's prophecy?", "A choice seer", ["A mighty king", "A righteous judge"], ["seer"]),
    q("c", "1", "What place did Joseph, to whom Lehi spoke, have among Lehi's children?", "He was the last-born", ["He was the firstborn", "He was the second son"], ["last-born"]),
  ),
  ch("2-ne", 4,
    q("a", "12", "What happened to Lehi after he had spoken to all his household?", "He died and was buried", ["He fell ill and withdrew", "He was taken up into heaven"], ["died"]),
    q("b", "11", "To which son, as well as to Nephi, did Lehi say the land would be an inheritance?", "To his son Sam", ["To his son Laman", "To his son Joseph"], ["Sam"]),
    q("c", "15", "In what does Nephi's soul delight, as he writes?", "In the scriptures on the plates of brass", ["In the victories over his enemies", "In the riches of the promised land"], ["scriptures"]),
  ),
  ch("2-ne", 5,
    q("a", "28", "How many years had passed since they left Jerusalem?", "Thirty years", ["Twenty years", "Fifty years"], ["thirty years"]),
    q("b", "16", "After the manner of which temple did Nephi build a temple?", "The temple of Solomon", ["The temple of Moses", "The temple of Zedekiah"], ["temple of Solomon"]),
    q("c", "26", "Whom did Nephi consecrate as priests and teachers over his people?", "Jacob and Joseph", ["Sam and Zoram", "Laman and Lemuel"], ["Jacob", "Joseph"]),
  ),
  ch("2-ne", 6,
    q("a", "4", "Whose words did Jacob read to the people?", "Isaiah", ["Jeremiah", "Moses"], ["Isaiah"]),
    q("b", "2", "By whom had Jacob been consecrated?", "By his brother Nephi", ["By his father Lehi", "By the king of Judah"], ["Nephi"]),
    q("c", "14", "According to Jacob, how many times will the Messiah set himself to recover his people?", "The second time", ["The third time", "The seventh time"], ["second time"]),
  ),
  ch("2-ne", 7,
    q("a", "8", "With what will the Lord smite his adversary?", "With the strength of his mouth", ["With a sharp sword of steel", "With fire from heaven"], ["mouth"]),
    q("b", "7", "What has the Lord set his face like, according to Isaiah's words?", "Like a hard flint stone", ["Like a rock in the sea", "Like a shield of steel"], ["flint"]),
    q("c", "3", "In what does the Lord clothe the heavens?", "In blackness", ["In whiteness", "In redness"], ["blackness"]),
  ),
  ch("2-ne", 8,
    q("a", "2", "Which father and mother did Isaiah say the people should look to?", "Abraham and Sarah", ["Isaac and Rebekah", "Jacob and Rachel"], ["Abraham", "Sarah"]),
    q("b", "3", "What will the Lord make the wilderness of Zion like?", "Like Eden", ["Like Bethel", "Like Sinai"], ["Eden"]),
    q("c", "1", "From what are those who follow after righteousness hewn, according to Isaiah?", "From the rock", ["From the river", "From the desert"], ["rock"]),
  ),
  ch("2-ne", 9,
    q("a", "10", "What does Jacob call death and hell?", "An awful monster", ["A mighty fortress", "A bottomless pit"], ["monster"]),
    q("b", "41", "According to Jacob, who is the keeper of the gate of the narrow way?", "The Holy One of Israel", ["The prophet Isaiah", "The angel of the Lord"], ["Holy One of Israel"]),
    q("c", "25", "According to Jacob, what is there where no law is given?", "No punishment", ["No redemption", "No salvation"], ["no punishment"]),
  ),
  ch("2-ne", 10,
    q("a", "3", "According to the angel, what would the name of the Messiah be?", "Christ", ["Immanuel", "Joshua"], ["Christ"]),
    q("b", "11", "Who will not rule in this land of liberty, according to the Lord?", "Kings over the land", ["Priests over the land", "Judges over the land"], ["kings"]),
    q("c", "23", "Between which two ways, according to Jacob, are people free to choose?", "Everlasting death or eternal life", ["Riches or poverty in the promised land", "War or peace with the people of Laman"], ["everlasting death", "eternal life"]),
  ),
  ch("2-ne", 11,
    q("a", "2", "Whose words does Nephi write more of?", "Those of Isaiah", ["Those of Jeremiah", "Those of Zenos"], ["Isaiah"]),
    q("b", "7", "What does Nephi say if there is no Christ?", "Then there is no God", ["Then there is no temple", "Then there is no prophet"], ["no God"]),
    q("c", "4", "For what purpose was the law of Moses given, according to Nephi?", "To prove the coming of Christ", ["To free the people from Egypt", "To build the temple in Jerusalem"], ["coming of Christ"]),
  ),
  ch("2-ne", 12,
    q("a", "4", "Into what, according to Isaiah, will the nations beat their swords?", "Into plowshares", ["Into shields", "Into cooking pots"], ["plow"]),
    q("b", "2", "Where will the mountain of the Lord's house be established in the last days?", "In the top of the mountains", ["In the deepest valley of Judah", "On the shore of the great sea"], ["top of the mountains"]),
    q("c", "7", "With what, according to Isaiah, was the land of Judah full?", "Silver and gold", ["Grain and olive oil", "Sheep and goats"], ["silver and gold"]),
  ),
  ch("2-ne", 13,
    q("a", "16", "Why will the Lord punish the daughters of Zion?", "Because they have become haughty", ["Because they do not keep the Sabbath", "Because they have left the temple"], ["haughty"]),
    q("b", "9", "To which city does Isaiah compare the sin of Judah?", "To Sodom", ["To Babylon", "To Nineveh"], ["Sodom"]),
    q("c", "10", "What will the righteous eat, according to Isaiah?", "The fruit of their doings", ["The bread of the king", "The spoil of the enemy"], ["fruit of their doings"]),
  ),
  ch("2-ne", 14,
    q("a", "1", "How many women will take hold of one man in that day, according to Isaiah?", "Seven women", ["Twelve women", "Ten women"], ["seven"]),
    q("b", "5", "What will the Lord create over mount Zion by night?", "The shining of a flaming fire", ["A great dark cloud of dust", "A rain of silver stars"], ["flaming fire"]),
    q("c", "6", "What will there be for a shadow in the daytime from the heat?", "A tabernacle", ["A high tower", "A wide wall"], ["tabernacle"]),
  ),
  ch("2-ne", 15,
    q("a", "1", "What does Isaiah sing a song about?", "A vineyard on a fruitful hill", ["A sheepfold in a green valley", "A city beside a great river"], ["vineyard"]),
    q("b", "7", "What is the vineyard of the Lord of Hosts?", "The house of Israel", ["The temple of Solomon", "The city of the king"], ["house of Israel"]),
    q("c", "20", "Upon whom does Isaiah pronounce woe in verse 20?", "Those who call evil good", ["Those who rest on the Sabbath", "Those who help the poor"], ["call evil good"]),
  ),
  ch("2-ne", 16,
    q("a", "2", "How many wings did each seraph have?", "Six wings", ["Four wings", "Eight wings"], ["six wings"]),
    q("b", "6-7", "What did the seraph touch Isaiah's lips with?", "A live coal", ["A burning torch", "A hot stone"], ["live coal"]),
    q("c", "8", "What did Isaiah say when the Lord asked whom He should send?", "Here am I; send me", ["I am not worthy", "Send my brother"], ["Here am I"]),
  ),
  ch("2-ne", 17,
    q("a", "14", "What name will the virgin's son be given, according to Isaiah?", "Immanuel", ["Jeremiah", "Jehoram"], ["Immanuel"]),
    q("b", "1", "In the days of which king of Judah did Rezin and Pekah go up against Jerusalem?", "Ahaz, son of Jotham", ["Hezekiah, son of Ahaz", "Manasseh, son of Hezekiah"], ["Ahaz"]),
    q("c", "11", "What was Ahaz allowed to ask of the Lord?", "A sign", ["An army", "A ship"], ["sign"]),
  ),
  ch("2-ne", 18,
    q("a", "3", "What name was Isaiah's son to be given, according to the Lord?", "Maher-shalal-hash-baz", ["Shear-jashub ben Amoz", "Maher-immanuel ben Jesse"], ["Maher-shalal-hash-baz"]),
    q("b", "13", "Whom should we sanctify, according to the Lord?", "The Lord of Hosts", ["The king of Assyria", "The prophet Isaiah"], ["Lord of Hosts"]),
    q("c", "7", "Who is meant by the strong and many waters of the river?", "The king of Assyria", ["The king of Egypt", "The king of Syria"], ["king of Assyria"]),
  ),
  ch("2-ne", 19,
    q("a", "6", "By what names is the child who is born to us called, among others?", "Wonderful, Counselor, The Mighty God", ["Shepherd, Judge, King of all the earth", "Redeemer, Light, Teacher of the people"], ["Wonderful", "Counselor"]),
    q("b", "2", "What have the people who walked in darkness seen?", "A great light", ["A great star", "A great army"], ["great light"]),
    q("c", "15", "According to Isaiah, who is the tail?", "The prophet who teaches lies", ["The priest who serves in the temple", "The warrior who defends the city"], ["lies"]),
  ),
  ch("2-ne", 20,
    q("a", "5", "Whom does the Lord call the rod of his anger?", "The Assyrian", ["The Egyptian", "The Philistine"], ["Assyrian"]),
    q("b", "26", "Which slaughter is mentioned in connection with the rock of Oreb?", "That of Midian", ["That of Amalek", "That of Moab"], ["Midian"]),
    q("c", "21", "What will return to the mighty God, according to Isaiah?", "The remnant of Jacob", ["The armies of the Assyrian", "The city of the king"], ["remnant of Jacob"]),
  ),
  ch("2-ne", 21,
    q("a", "1", "Out of the stem of whom will a branch come forth, according to Isaiah?", "Jesse", ["Joseph", "Judah"], ["Jesse"]),
    q("b", "6", "Who will dwell with the lamb, according to Isaiah?", "The wolf", ["The rooster", "The raven"], ["wolf"]),
    q("c", "9", "What will the earth be full of, according to Isaiah?", "The knowledge of the Lord", ["The riches of the nations", "The cities of the saints"], ["knowledge of the Lord"]),
  ),
  ch("2-ne", 22,
    q("a", "2", "What is the Lord Jehovah, according to this song?", "My strength and my song", ["My fortress and my shield", "My shepherd and my rock"], ["strength", "song"]),
    q("b", "3", "From where will you draw water with joy?", "From the wells of salvation", ["From the river of Jordan", "From the well of Jacob"], ["wells of salvation"]),
    q("c", "6", "Who is great in the midst of the inhabitants of Zion?", "The Holy One of Israel", ["The king who rules Judah", "The prophet Isaiah himself"], ["Holy One of Israel"]),
  ),
  ch("2-ne", 23,
    q("a", "17", "Which people will the Lord stir up against Babylon, according to Isaiah?", "The people of the Medes", ["The people of the Assyrians", "The people of the Philistines"], ["Medes"]),
    q("b", "19", "To which cities is Babylon compared at its downfall?", "Sodom and Gomorrah", ["Nineveh and Tyre", "Jericho and Ai"], ["Sodom and Gomorrah"]),
    q("c", "10", "What will happen to the sun in its going forth, according to Isaiah?", "It will be darkened as it rises", ["It will turn red as blood", "It will shine twice as bright"], ["darkened"]),
  ),
  ch("2-ne", 24,
    q("a", "12", "What title does Lucifer bear in verse 12?", "Son of the morning", ["Son of the noonday sun", "Son of the evening star"], ["son of the morning"]),
    q("b", "14", "What did Lucifer say in his heart he would do?", "Ascend above the heights of the clouds", ["Descend into the depths of the earth", "Found a kingdom in the east"], ["heights of the clouds"]),
    q("c", "23", "What will the Lord make of Babylon?", "A possession for the bittern", ["A city full of merchants", "A pasture for the sheep"], ["bittern"]),
  ),
  ch("2-ne", 25,
    q("a", "19", "How many years after Lehi left Jerusalem does the Messiah come, according to the prophets?", "Six hundred years", ["Four hundred years", "One thousand years"], ["six hundred years"]),
    q("b", "24", "What do Nephi and his people keep, although they believe in Christ?", "The law of Moses", ["The temple of Solomon", "The records of Laban"], ["law of Moses"]),
    q("c", "29", "According to Nephi, who is Christ?", "The Holy One of Israel", ["The prophet Isaiah", "The king of the Jews"], ["Holy One of Israel"]),
  ),
  ch("2-ne", 26,
    q("a", "9", "What is Christ called in verse 9?", "The Son of Righteousness", ["The Son of the Morning", "The Son of Blessing"], ["Son of Righteousness"]),
    q("b", "31", "For what must the laborer in Zion not labor?", "For money", ["For fame", "For power"], ["money"]),
    q("c", "25", "Instead of saying \"Depart from me,\" what does the Lord say?", "Come unto me, all ye ends of the earth", ["Build a temple in the land for my name", "Offer a lamb to me every morning and evening"], ["Come unto me"]),
  ),
  ch("2-ne", 27,
    q("a", "7", "What will the sealed book contain, according to verse 7?", "A revelation from God", ["The laws of the kings", "A list of all the kings"], ["revelation from God"]),
    q("b", "18", "What will the learned say when the book is brought to him?", "I cannot read it", ["I will not buy it", "I read it already"], ["cannot read it"]),
    q("c", "29", "Who will hear the words of the book, according to Isaiah?", "The deaf", ["The rich", "The learned"], ["deaf"]),
  ),
  ch("2-ne", 28,
    q("a", "7", "What will many say in the last days, according to Nephi?", "Eat, drink, and be merry", ["Save, pray, and be careful", "Work, sacrifice, and be thankful"], ["Eat, drink, and be merry"]),
    q("b", "30", "In what way does the Lord God give his word to the children of men?", "Line upon line, precept upon precept", ["Book upon book, chapter upon chapter", "Year upon year, miracle upon miracle"], ["line upon line", "precept upon precept"]),
    q("c", "22", "What does the devil tell some people, according to Nephi?", "That there is no hell and no devil", ["That the Lord will soon return to earth", "That the temple will soon be closed"], ["no hell"]),
  ),
  ch("2-ne", 29,
    q("a", "3", "What will many of the Gentiles say?", "A Bible! A Bible!", ["A temple! A temple!", "A king! A king!"], ["A Bible"]),
    q("b", "4", "From which people does the Bible proceed?", "From the people of the Jews", ["From the people of the Egyptians", "From the people of the Nephites"], ["Jews"]),
    q("c", "8", "How many nations testify that the Lord is God?", "Two nations", ["Three nations", "Seven nations"], ["two nations"]),
  ),
  ch("2-ne", 30,
    q("a", "2", "Who are the covenant people of the Lord, according to Nephi?", "As many Gentiles as will repent", ["Only those who came from Jerusalem", "Only the rich who offer many sacrifices"], ["will repent"]),
    q("b", "7", "In whom will the scattered Jews begin to believe, according to Nephi?", "In Christ", ["In Moses", "In Abraham"], ["Christ"]),
    q("c", "17", "What will happen to everything that is secret, according to Nephi?", "It will be revealed", ["It will be sealed", "It will be forgotten"], ["revealed"]),
  ),
  ch("2-ne", 31,
    q("a", "8", "In what form did the Holy Ghost descend on Christ when he was baptized?", "In the form of a dove", ["In the form of an eagle", "In the form of a cloud"], ["form of a dove"]),
    q("b", "21", "What does Nephi say about the way by which man can be saved?", "There is none other way nor name", ["There are two ways and two names", "There is a way for every nation"], ["none other way"]),
    q("c", "11", "What did the Father say people must do?", "Repent and be baptized", ["Fast and bring an offering", "Pray and keep the law"], ["repent", "baptized"]),
  ),
  ch("2-ne", 32,
    q("a", "2", "With what could they speak once they had received the Holy Ghost?", "With the tongue of angels", ["With the tongue of prophets", "With the tongue of kings"], ["tongue of angels"]),
    q("b", "9", "What must one always do, according to Nephi?", "Pray and not faint", ["Fast and not drink", "Serve and not complain"], ["pray", "faint"]),
    q("c", "6", "Until when will no more doctrine be given, according to Nephi?", "Until he manifests himself in the flesh", ["Until the temple is fully finished", "Until the people have repented"], ["in the flesh"]),
  ),
  ch("2-ne", 33,
    q("a", "6", "In what does Nephi glory, among other things?", "In plainness and truth", ["In his strength and his wisdom", "In his works and his army"], ["plainness", "truth"]),
    q("b", "13", "As whose voice does Nephi speak to all the ends of the earth?", "As the voice of one crying from the dust", ["As the voice of a shepherd in the field", "As the voice of an angel from heaven"], ["crying from the dust"]),
    q("c", "15", "What will be brought against people at the judgment bar, according to Nephi?", "What Nephi has sealed on earth", ["All that people gather on earth", "What the Jews have written on earth"], ["seal"]),
  ),
  // ===== EINDE =====
];
