import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 3 Nephi (English edition). Each fact is tied to the verses in `verses`; `npm run genees:check` verifies that.
export const nephi3: GeneesChapterSeed[] = [
  ch("3-ne", 1,
    q("a", "19", "What happened in the night of the sign?", "There was no darkness, it was light as day", ["A heavy storm lit up the whole night", "An eclipse of the sun lasting many hours"], ["no darkness"]),
    q("b", "21", "What appeared in the heavens according to the word of the prophets?", "A new star", ["A new moon", "A red comet"], ["new star"]),
    q("c", "3", "Who kept the records after his father left the land?", "Nephi, the son of Nephi", ["Lehi, the son of Nephi", "Nephi, the son of Lehi"], ["Nephi"]),
  ),
  ch("3-ne", 2,
    q("a", "8", "From what time did the Nephites begin to reckon their time?", "From the sign of the coming of Christ", ["From the death of King Mosiah", "From the departure of Lehi from Jerusalem"], ["coming of Christ"]),
    q("b", "12", "What did the converted Lamanites do when the robbers threatened?", "They united with the Nephites", ["They moved away to the north", "They built their own kingdom"], ["unite"]),
    q("c", "11", "Through whom did wars and contentions arise in the thirteenth year?", "Through the Gadianton robbers", ["Through the Lamanites from the south", "Through the king of Zarahemla"], ["Gadianton robbers"]),
  ),
  ch("3-ne", 3,
    q("a", "9", "What was the name of the governor of the secret society of Gadianton?", "Giddianhi", ["Gidgiddoni", "Zemnarihah"], ["Giddianhi"]),
    q("b", "18", "Who was appointed chief commander of all the armies of the Nephites?", "Gidgiddoni", ["Lachoneus", "Moronihah"], ["Gidgiddoni"]),
    q("c", "23", "Which land was appointed as the place of gathering?", "The land of Zarahemla", ["The land of Jershon", "The land of Melek"], ["land of Zarahemla"]),
  ),
  ch("3-ne", 4,
    q("a", "28", "What was the name of the robbers' leader who was hanged upon a tree?", "Zemnarihah", ["Giddianhi", "Lachoneus"], ["Zemnarihah"]),
    q("b", "3", "Why could the robbers exist only in the wilderness?", "The Nephites had left their lands desolate", ["The Lamanites had occupied their lands", "The robbers had taken all the cities"], ["left their lands desolate"]),
    q("c", "32", "What did the Nephites cry when they praised God?", "Hosanna to the Most High God", ["Hallelujah to the holy God", "Glory to the king of the land"], ["Hosanna"]),
  ),
  ch("3-ne", 5,
    q("a", "12", "After what land was Mormon named?", "The land of Mormon", ["The land of Helam", "The land of Bountiful"], ["land of Mormon"]),
    q("b", "13", "What is Mormon, according to his own words?", "A disciple of Jesus Christ", ["A high priest of the church", "A commander of the Nephite armies"], ["disciple of Jesus Christ"]),
    q("c", "11", "On what does Mormon make his record?", "On plates made with his own hands", ["On plates his father made", "On brass plates from Jerusalem"], ["own hands"]),
  ),
  ch("3-ne", 6,
    q("a", "6", "Who had established the great peace in the land?", "Gidgiddoni and the judge Lachoneus", ["Zemnarihah and the judge Giddianhi", "Moroni and the judge Pahoran"], ["Gidgiddoni", "Lachoneus"]),
    q("b", "14", "In which year did the church begin to be broken up?", "In the thirtieth year", ["In the twentieth year", "In the fortieth year"], ["thirtieth"]),
    q("c", "8", "What was constructed in the land in the time of peace?", "Many highways and roads", ["Many walls and towers", "Many canals and bridges"], ["highways"]),
  ),
  ch("3-ne", 7,
    q("a", "19", "What did Nephi do in the name of Jesus for his brother?", "He raised his brother from the dead", ["He healed his brother of blindness", "He rescued his brother from prison"], ["from the dead"]),
    q("b", "10", "What did the secret society call the man they appointed as their head?", "They called him their king", ["They called him their judge", "They called him their prophet"], ["king"]),
    q("c", "2", "Into what did the people divide?", "Into tribes", ["Into cities", "Into armies"], ["tribes"]),
  ),
  ch("3-ne", 8,
    q("a", "5", "In which year did a great storm arise?", "In the thirty-fourth year", ["In the thirty-third year", "In the thirty-fifth year"], ["fourth year"]),
    q("b", "8", "What happened to the city of Zarahemla?", "The city did take fire", ["The city was swallowed up", "The city was covered over"], ["take fire"]),
    q("c", "23", "For how long was no light seen?", "Three days", ["Seven days", "Two days"], ["three days"]),
  ),
  ch("3-ne", 9,
    q("a", "3", "What happened to the great city Zarahemla, according to the voice?", "It was burned with fire", ["It was sunk in the sea", "It was covered with earth"], ["burned with fire"]),
    q("b", "18", "How does the Lord call himself in verse 18?", "Alpha and Omega, the beginning and the end", ["The Shepherd and the Rock of the world", "The Judge and the King of the world"], ["Alpha and Omega"]),
    q("c", "20", "What sacrifice does the Lord require instead of bloodshed?", "A broken heart and a contrite spirit", ["A firstling offering from the flock", "A burnt offering of the best grain"], ["broken heart"]),
  ),
  ch("3-ne", 10,
    q("a", "9", "How long did it take before the darkness dispersed from the land?", "Three days", ["Seven days", "Two days"], ["three days"]),
    q("b", "5", "To what does the Lord compare his desire to gather the people?", "To a hen gathering her chickens", ["To a shepherd leading his sheep", "To an eagle carrying its young"], ["chickens"]),
    q("c", "16", "Which prophets testified of these things, according to Mormon?", "Zenos and Zenock", ["Isaiah and Jeremiah", "Moses and Aaron"], ["Zenos", "Zenock"]),
  ),
  ch("3-ne", 11,
    q("a", "1", "Where was the great multitude of the people of Nephi gathered?", "Round about the temple in Bountiful", ["Round about the mountain in Zarahemla", "Round about the palace in Nephi"], ["temple"]),
    q("b", "7", "What did the voice out of heaven say?", "Behold my Beloved Son; hear ye him", ["Behold my servant; follow his words", "Behold the prophet; fear his judgments"], ["Beloved Son", "hear ye him"]),
    q("c", "25", "In whose name must one baptize, according to the Lord?", "In the name of the Father, the Son, and the Holy Ghost", ["In the name of the Father, the prophet, and the king", "In the name of the Lord, the angel, and the Spirit"], ["Father", "Son", "Holy Ghost"]),
  ),
  ch("3-ne", 12,
    q("a", "13", "What does the Lord charge people to be in verse 13?", "The salt of the earth", ["The salt of the sea", "The bread of the earth"], ["salt of the earth"]),
    q("b", "5", "Who shall inherit the earth, according to the Lord?", "Those who are meek in spirit", ["Those who are swift and strong", "Those who are rich and mighty"], ["meek"]),
    q("c", "44", "What does the Lord command regarding our enemies?", "Love your enemies", ["Expel your enemies", "Punish your enemies"], ["love your enemies"]),
  ),
  ch("3-ne", 13,
    q("a", "9", "How does the prayer begin that Jesus teaches the multitude?", "Our Father who art in heaven", ["Our Lord who dwells in heaven", "Our God who reigns on earth"], ["Our Father who art in heaven"]),
    q("b", "33", "What should one seek first, according to Jesus?", "The kingdom of God and his righteousness", ["Riches and a good name among all the people", "Food and clothing for the whole family"], ["kingdom of God"]),
    q("c", "24", "How many masters can no man serve, according to Jesus?", "Two masters", ["Three masters", "Seven masters"], ["two masters"]),
  ),
  ch("3-ne", 14,
    q("a", "7", "What does the Lord promise to those who ask?", "It shall be given unto you", ["It shall be taken from you", "It shall be forgotten by you"], ["given unto you"]),
    q("b", "15", "How do false prophets come to us, according to the Lord?", "In sheep's clothing", ["In kings' clothing", "In priests' garments"], ["sheep's clothing"]),
    q("c", "24", "On what did the wise man build his house, according to Jesus?", "Upon a rock", ["Upon the sand", "Upon a hill"], ["rock"]),
  ),
  ch("3-ne", 15,
    q("a", "17", "What does the Lord say about other sheep?", "That he has other sheep not of this fold", ["That he has no other sheep any more", "That all the sheep are of this one fold"], ["other sheep"]),
    q("b", "4", "What is fulfilled, according to the Lord?", "The law given unto Moses", ["The law given unto Lehi", "The law given unto Abraham"], ["given unto Moses"]),
    q("c", "9", "What is the Lord, according to verse 9?", "The law and the light", ["The gate and the way", "The peace and the rock"], ["law and the light"]),
  ),
  ch("3-ne", 16,
    q("a", "6", "Who are blessed because of their belief in the Lord, according to Him?", "The Gentiles who believe", ["The Nephites alone", "The Jews at Jerusalem"], ["Gentiles"]),
    q("b", "18", "What will the watchmen do, according to the prophet Isaiah?", "Lift up the voice and sing together", ["Gather the people with trumpets", "Leave the city and run away from it"], ["lift up the voice"]),
    q("c", "13", "What does the Father say will happen to the Gentiles if they repent and return to him?", "They shall be numbered among my people", ["They shall be driven out of the land", "They shall be spared without judgment"], ["numbered among my people"]),
  ),
  ch("3-ne", 17,
    q("a", "14", "What did Jesus do when the multitude had knelt upon the ground?", "He groaned within himself", ["He departed from them quietly", "He blessed them with his hands"], ["groaned"]),
    q("b", "7", "Whom did Jesus ask the multitude to bring to him?", "Those who are sick, lame, or blind", ["Those who are rich and powerful", "Those who are strange and unknown"], ["sick"]),
    q("c", "21", "How did Jesus take the little children?", "He took them one by one", ["He sent them back to their parents", "He had them pray in groups"], ["one by one"]),
  ),
  ch("3-ne", 18,
    q("a", "1", "What did Jesus command his disciples to bring to him?", "Bread and wine", ["Water and oil", "Meat and fruit"], ["bread and wine"]),
    q("b", "18", "What must people always do, according to Jesus, so that they do not enter into temptation?", "Watch and pray", ["Fast and sacrifice", "Work and save"], ["watch and pray"]),
    q("c", "7", "In remembrance of what are they to eat the bread, according to Jesus?", "In remembrance of his body, shown to them", ["In remembrance of the law of Moses", "In remembrance of the coming of the robbers"], ["remembrance"]),
  ),
  ch("3-ne", 19,
    q("a", "5", "Into how many groups was the multitude divided?", "Into twelve bodies", ["Into seven bodies", "Into three bodies"], ["twelve bodies"]),
    q("b", "9", "What did the disciples pray for the most?", "That the Holy Ghost should be given them", ["That their people would know war no more", "That their prayer would never end"], ["Holy Ghost"]),
    q("c", "11", "Who went down into the water and was baptized?", "Nephi", ["Mathoni", "Jonas"], ["Nephi"]),
  ),
  ch("3-ne", 20,
    q("a", "3,5", "What did Jesus give the disciples and the multitude to eat and drink?", "Bread and wine", ["Fish and honey", "Grain and milk"], ["bread", "wine"]),
    q("b", "6", "What does verse 6 say about the bread and wine?", "No bread or wine had been brought", ["The disciples had brought it", "The multitude had brought it"], ["brought"]),
    q("c", "14", "What did the Father command Jesus to give them?", "This land for their inheritance", ["The land of Jerusalem for an inheritance", "The southern land for an inheritance"], ["inheritance"]),
  ),
  ch("3-ne", 21,
    q("a", "12", "To what is the remnant of Jacob compared among the Gentiles?", "A lion among the beasts", ["A sheep among the wolves", "An eagle above the mountains"], ["lion"]),
    q("b", "14", "Which instruments of war of the Gentiles does the Lord mention in verse 14?", "Horses and chariots", ["Sheep and flocks", "Towers and gates"], ["horses"]),
    q("c", "16", "What will the Lord cut off out of the land of the Gentiles, according to verse 16?", "Witchcrafts", ["Trade caravans", "Grain fields"], ["witchcrafts"]),
  ),
  ch("3-ne", 22,
    q("a", "9", "To what does the Lord compare his promise in verse 9?", "To the waters of Noah's flood", ["To the waters of the Jordan", "To the waters of the Red Sea"], ["waters of Noah"]),
    q("b", "13", "Who shall be taught of the Lord, according to the Lord?", "All your children", ["All the priests", "Only the rich"], ["children"]),
    q("c", "12", "Of what will the Lord make the windows of restored Zion?", "Of agates", ["Of sapphires", "Of crystal"], ["agates"]),
  ),
  ch("3-ne", 23,
    q("a", "9", "Whom had the Lord commanded to testify to the people about the sign of his death?", "Samuel the Lamanite", ["Nephi son of Helaman", "Lehi the prophet"], ["Samuel"]),
    q("b", "7", "What did Jesus ask Nephi to bring forth?", "The record which he had kept", ["The brass plates from Jerusalem", "Lehi's ball or director"], ["record"]),
    q("c", "13", "What did Jesus command to be done with what had not yet been written?", "That it should be written", ["That it should be kept secret", "That it should be allowed to perish"], ["written"]),
  ),
  ch("3-ne", 24,
    q("a", "1", "Whose words did Jesus command them to write?", "Those of Malachi", ["Those of Isaiah", "Those of Jeremiah"], ["Malachi"]),
    q("b", "8", "In what do the people rob God, according to verse 8?", "In tithes and offerings", ["In sabbath and worship", "In prayers and alms"], ["tithes and offerings"]),
    q("c", "10", "Where must all the tithes be brought, according to the Lord?", "Into the storehouse", ["Into the temple wall", "Into the judgment-seat"], ["storehouse"]),
  ),
  ch("3-ne", 25,
    q("a", "5", "Which prophet will the Lord send before the great and dreadful day?", "Elijah", ["Elisha", "Jonah"], ["Elijah"]),
    q("b", "2", "How is Christ called in verse 2?", "The Son of Righteousness", ["The Son of the Morning", "The Son of Promise"], ["Son of Righteousness"]),
    q("c", "6", "What will Elijah turn, according to the Lord?", "The heart of the fathers to the children", ["The law of the fathers to the children", "The riches of the fathers to the children"], ["heart of the fathers"]),
  ),
  ch("3-ne", 26,
    q("a", "13", "For how long did Jesus teach the people, according to verse 13?", "For three days", ["For seven days", "For forty days"], ["three days"]),
    q("b", "21", "What were those called who were baptized in the name of Jesus?", "The church of Christ", ["The church of the Saints", "The church of Nephi"], ["church of Christ"]),
    q("c", "19", "What did the believers have, according to verse 19?", "All things common among them", ["All things as private property", "All riches with the leaders"], ["all things common"]),
  ),
  ch("3-ne", 27,
    q("a", "5", "By what name should the church be called, according to Jesus?", "By the name of Christ", ["By the name of Moses", "By the name of Nephi"], ["name of Christ"]),
    q("b", "28", "What does Jesus promise to those who ask the Father in his name?", "It shall be given unto them", ["It shall be withheld from them", "It shall be repaid to them"], ["given unto"]),
    q("c", "33", "Through which gate must the disciples enter, according to Jesus?", "Through the strait gate", ["Through the wide gate", "Through the golden gate"], ["strait gate"]),
  ),
  ch("3-ne", 28,
    q("a", "3", "At what age would the disciples come to Jesus in his kingdom, according to him?", "At seventy-two years old", ["At seventy-five years old", "At sixty years old"], ["years old"]),
    q("b", "7", "What would never happen to the three disciples who desired it, according to Jesus?", "They would never taste of death", ["They would never hunger again", "They would never lose their faith"], ["taste of death"]),
    q("c", "22", "What happened when the three were cast into a den of wild beasts?", "They did play with the beasts", ["They were devoured by the beasts", "They were attacked by the beasts"], ["play with the beasts"]),
  ),
  ch("3-ne", 29,
    q("a", "8", "Whom need people no longer hiss at, spurn or make game of, according to Mormon?", "The Jews, the covenant people", ["The Nephites, the chosen people", "The Lamanites, the lost people"], ["Jews"]),
    q("b", "6", "What does he deny who says the Lord no longer works by revelation?", "The revelations of the Lord", ["The covenants of the Lord", "The prophets of the Lord"], ["revelations of the Lord"]),
    q("c", "2", "What may one know about the words of the Lord, according to Mormon?", "That they shall all be fulfilled", ["That they shall all be forgotten", "That they shall never be read again"], ["all be fulfilled"]),
  ),
  ch("3-ne", 30,
    q("a", "1", "To whom does Mormon address himself in chapter 30?", "To the Gentiles", ["To the Nephites", "To the Lamanites"], ["Gentiles"]),
    q("b", "2", "What must the Gentiles do, according to Mormon?", "Turn from their wicked ways", ["Gather in the northern land", "Hurry to build towers"], ["wicked ways"]),
    q("c", "1", "Who is Jesus Christ, according to verse 1?", "The Son of the living God", ["The son of the prophet Mormon", "The son of the king of Judah"], ["Son of the living God"]),
  ),
  // ===== EINDE =====
];
