import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Alma (English edition). Each fact is tied to the verses in `verses`; `npm run genees:check` verifies that.
export const alma: GeneesChapterSeed[] = [
  ch("alma", 1,
    q("a", "15", "What was the name of the man who slew Gideon?", "Nehor", ["Amlici", "Korihor"], ["Nehor"]),
    q("b", "15", "Where was Nehor put to death?", "At the top of the hill Manti", ["On the bank of the river Sidon", "In the marketplace of Zarahemla"], ["hill Manti"]),
    q("c", "12", "What, according to Alma, was introduced among the people for the first time?", "Priestcraft among the people", ["Keeping of slaves among the people", "Building of a temple for worship"], ["priestcraft"]),
  ),
  ch("alma", 2,
    q("a", "1", "What was the name of the man who wanted to become king over the people?", "Amlici", ["Nehor", "Korihor"], ["Amlici"]),
    q("b", "31", "With what did Alma slay the leader of the Amlicites?", "With the sword", ["With a spear", "With an arrow"], ["sword"]),
    q("c", "15", "At which hill, east of the river Sidon, did the Amlicites arrive?", "The hill Amnihu", ["The hill Manti", "The hill Riplah"], ["Amnihu"]),
  ),
  ch("alma", 3,
    q("a", "4", "What had the Amlicites marked on their foreheads?", "A red mark", ["A blue mark", "A black mark"], ["red"]),
    q("b", "26", "How many souls were sent to the eternal world in that one year?", "Thousands and tens of thousands", ["Hundreds and many thousands", "Only a few hundred people"], ["thousands and tens of thousands"]),
    q("c", "22", "Why did Alma not go up to battle himself this time against the Lamanites?", "Because he was afflicted with a wound", ["Because he did not trust the army", "Because he had another plan"], ["wound"]),
  ),
  ch("alma", 4,
    q("a", "5", "About how many souls united themselves with the church in the seventh year?", "About three thousand five hundred", ["About two thousand five hundred", "About five thousand three hundred"], ["three thousand five hundred"]),
    q("b", "17", "Who was appointed chief judge when Alma handed over the judgment-seat?", "Nephihah", ["Helaman", "Gideon"], ["Nephihah"]),
    q("c", "18", "Which office did Alma retain for himself?", "That of high priest", ["That of army commander", "That of chief judge"], ["high priest"]),
  ),
  ch("alma", 5,
    q("a", "38", "Whose name does the good shepherd who calls us bear?", "The name of Christ", ["The name of Mormon", "The name of Abinadi"], ["name of Christ"]),
    q("b", "3", "By whom was Alma consecrated to be a high priest over the church?", "By his father Alma", ["By King Mosiah", "By the prophet Abinadi"], ["father Alma"]),
    q("c", "52", "According to the Spirit, what is laid at the root of the tree?", "The ax", ["The saw", "The spade"], ["ax"]),
  ),
  ch("alma", 6,
    q("a", "8", "In which valley did Alma next begin to declare the word of God?", "The valley of Gideon", ["The valley of Lemuel", "The valley of Helam"], ["valley of Gideon"]),
    q("b", "2", "What happened to those who repented of their sins and did not yet belong to the church?", "They were baptized unto repentance", ["They were sent to Zarahemla", "They had to wait a year first"], ["unto repentance"]),
    q("c", "6", "For what were the children of God commanded to gather together often?", "Fasting and mighty prayer", ["Offerings and burnt sacrifices", "Building temples and altars"], ["fasting and mighty prayer"]),
  ),
  ch("alma", 7,
    q("a", "10", "Where will the Lord be born, according to Alma?", "At Jerusalem", ["At Nazareth", "At Zarahemla"], ["Jerusalem"]),
    q("b", "10", "How does Alma describe the mother of the Lord?", "A virgin, a precious and chosen vessel", ["A princess, a rich and powerful woman", "A queen, a rich and noble vessel"], ["precious and chosen vessel"]),
    q("c", "24", "Which three things must one have, according to Alma?", "Faith, hope, and charity", ["Faith, repentance, and sacrifices", "Knowledge, wisdom, and power"], ["faith, hope, and charity"]),
  ),
  ch("alma", 8,
    q("a", "3", "To which land did Alma journey in the tenth year of the reign of the judges?", "The land of Melek", ["The land of Gideon", "The land of Jershon"], ["land of Melek"]),
    q("b", "6", "What was the name of the city Alma came to after three days' journey north of Melek?", "Ammonihah", ["Zarahemla", "Jershon"], ["Ammonihah"]),
    q("c", "21", "What was the name of the man who received Alma into his house?", "Amulek", ["Amulon", "Amaleki"], ["Amulek"]),
  ),
  ch("alma", 9,
    q("a", "4", "What did the people of Ammonihah say they would not believe if Alma prophesied?", "That the city would be destroyed in one day", ["That the city would perish in a flood", "That the city would be taken by the Lamanites"], ["in one day"]),
    q("b", "26", "What does the angel say about the coming of the Son of God?", "Not many days hence", ["In many hundred years", "In more than a thousand years"], ["not many days hence"]),
    q("c", "34", "Who stepped forward and also began to preach to the people?", "Amulek", ["Zeezrom", "Antionah"], ["Amulek"]),
  ),
  ch("alma", 10,
    q("a", "2", "Who was the father of Amulek?", "Giddonah", ["Aminadi", "Ishmael"], ["Giddonah"]),
    q("b", "7", "Who appeared to Amulek on his journey?", "An angel of the Lord", ["A prophet from Zarahemla", "A servant of Alma"], ["angel of the Lord"]),
    q("c", "31", "What was the name of the foremost lawyer who accused Amulek and Alma?", "Zeezrom", ["Antionah", "Korihor"], ["Zeezrom"]),
  ),
  ch("alma", 11,
    q("a", "3", "What did a judge receive as wages for a day?", "A senine of gold", ["A limnah of gold", "An onti of silver"], ["senine of gold"]),
    q("b", "21", "Who began to question Amulek?", "Zeezrom", ["Antionah", "Gideon"], ["Zeezrom"]),
    q("c", "38-39", "Who, according to Amulek, is truly the Eternal Father of heaven and earth?", "The Son of God", ["The prophet Alma", "The angel of God"], ["Son of God"]),
  ),
  ch("alma", 12,
    q("a", "20", "Who was Antionah?", "A chief ruler among them", ["A lawyer among them", "A captain among them"], ["chief ruler"]),
    q("b", "16", "What does Alma call the second death?", "A spiritual death", ["A temporal death", "A bodily death"], ["spiritual death"]),
    q("c", "21", "What did God place on the east of the garden of Eden, according to the scripture?", "Cherubim and a flaming sword", ["A wall with a gate of gold", "An angel with a golden key"], ["cherubim"]),
  ),
  ch("alma", 13,
    q("a", "15", "To whom did Abraham pay tithes?", "To the king Melchizedek", ["To the prophet Moses", "To the king Solomon"], ["Melchizedek"]),
    q("b", "17", "Over which land was Melchizedek king?", "The land of Salem", ["The land of Moab", "The land of Egypt"], ["land of Salem"]),
    q("c", "9", "How is the Son called in verse 9?", "The Only Begotten of the Father", ["The Firstborn of the Father", "The Anointed of the Father"], ["Only Begotten of the Father"]),
  ),
  ch("alma", 14,
    q("a", "16", "After the order and faith of whom was the chief judge of Ammonihah?", "Nehor", ["Amlici", "Korihor"], ["Nehor"]),
    q("b", "18", "How many days had Alma and Amulek been in prison before the lawyers and judges came?", "Three days", ["Seven days", "Two days"], ["three days"]),
    q("c", "27", "What happened when Alma and Amulek called upon the Lord for deliverance?", "The earth shook mightily", ["A fire broke out", "It began to hail heavily"], ["shook mightily"]),
  ),
  ch("alma", 15,
    q("a", "1", "To which land did Alma and Amulek go after leaving Ammonihah?", "The land of Sidom", ["The land of Melek", "The land of Nephi"], ["land of Sidom"]),
    q("b", "3", "What was Zeezrom suffering from at Sidom?", "A burning fever", ["A serious wound", "Severe blindness"], ["burning fever"]),
    q("c", "12", "What did Alma do with Zeezrom after he was healed?", "He baptized him unto the Lord", ["He sent him back to Ammonihah", "He made him leave the church"], ["baptized"]),
  ),
  ch("alma", 16,
    q("a", "5", "What was the name of the chief captain of the armies of the Nephites?", "Zoram", ["Moroni", "Gideon"], ["Zoram"]),
    q("b", "10", "What happened to the city of Ammonihah according to Alma 16?", "It was left desolate in one day", ["It was gradually occupied by the Lamanites", "It was swallowed up by an earthquake"], ["in one day"]),
    q("c", "19", "What did the priests proclaim about the Son of God?", "His sufferings and death", ["His riches and power", "His marriage and family"], ["sufferings and death"]),
  ),
  ch("alma", 17,
    q("a", "4", "For how many years had the sons of Mosiah been teaching the word among the Lamanites?", "Fourteen years", ["Twenty-four years", "Seventeen years"], ["fourteen years"]),
    q("b", "21", "What was the name of the king of the land of Ishmael?", "Lamoni", ["Limhi", "Laman"], ["Lamoni"]),
    q("c", "38", "How many of the Lamanites fell by Ammon's sling?", "Six men", ["Four men", "Eight men"], ["six"]),
  ),
  ch("alma", 18,
    q("a", "13", "What does the word Rabbanah mean?", "Powerful or great king", ["Wise and mighty lord", "Brave army commander"], ["great king"]),
    q("b", "43", "How long did King Lamoni lie as if dead on his bed?", "Two days and two nights", ["Three days and three nights", "One day and one night"], ["two days and two nights"]),
    q("c", "9", "What was Ammon doing when the king asked for him?", "He was feeding the king's horses", ["He was feasting with the servants", "He was sleeping in the king's tent"], ["horses"]),
  ),
  ch("alma", 19,
    q("a", "8", "What did Ammon say about King Lamoni when he looked at him?", "He is not dead, but sleeps in God", ["He is wounded and must rest by the fire", "He is sick and needs a physician"], ["in God"]),
    q("b", "13", "What did Lamoni say when he rose again?", "That he had seen his Redeemer", ["That he had seen a great army", "That he had seen his father"], ["Redeemer"]),
    q("c", "28", "Who had caused the multitude to be gathered together?", "A Lamanite woman servant", ["A daughter of the king", "A priest of the people"], ["woman servant"]),
  ),
  ch("alma", 20,
    q("a", "3", "In which land were Ammon's brethren in prison?", "The land of Middoni", ["The land of Ishmael", "The land of Sidom"], ["Middoni"]),
    q("b", "10", "What does Lamoni's father call the Nephite Ammon?", "One of the children of a liar", ["One of the sons of a king", "One of the servants of the devil"], ["children of a liar"]),
    q("c", "23", "What did the old king offer Ammon if he would spare him?", "Even half of the kingdom", ["A third of his treasures", "His eldest daughter as a wife"], ["half of the kingdom"]),
  ),
  ch("alma", 21,
    q("a", "2", "What was the great city called that the Lamanites, the Amalekites and the people of Amulon had built?", "The city of Jerusalem", ["The city of Nephi", "The city of Zarahemla"], ["Jerusalem"]),
    q("b", "14", "By whom were Aaron and his brethren delivered from prison?", "By Lamoni and Ammon", ["By Mosiah and Alma", "By Omner and Himni"], ["Lamoni", "Ammon"]),
    q("c", "22", "What did King Lamoni declare to his people about worshiping the Lord?", "That they were free to worship the Lord anywhere", ["That they could worship only in the synagogues", "That they could worship only the king"], ["worship"]),
  ),
  ch("alma", 22,
    q("a", "3", "What did Aaron and his brothers promise the king in exchange for their lives?", "That they would be his servants", ["That they would give him their possessions", "That they would leave the land"], ["servants"]),
    q("b", "7", "What do the Amalekites say about God, according to the king?", "That there is a God", ["That there are two gods", "That there is no God"], ["there is a God"]),
    q("c", "17", "What did the king do when Aaron had spoken these words?", "He knelt and prostrated himself upon the earth", ["He stood up and walked out of the great hall", "He called his bodyguard together at once"], ["upon the earth"]),
  ),
  // ===== EINDE =====
];
