import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Alma (English edition). Each fact is tied to the verses in `verses`; `npm run genees:check` verifies that.
export const alma: GeneesChapterSeed[] = [
  ch("alma", 1,
    q("a", "15", "What was the name of the man who slew Gideon?", "Nehor", ["Amlici", "Korihor"], ["Nehor"]),
    q("b", "15", "Where was Nehor put to death?", "At the top of the hill Manti", ["On the bank of the river Sidon", "In the marketplace of Zarahemla"], ["hill Manti"]),
    q("c", "12", "What, according to Alma, was introduced among the people for the first time?", "Priestcraft among the people", ["Keeping of slaves among the people", "Building of a temple for worship"], ["priestcraft"]),
  ),
  ch("alma", 2,
    q("a", "1", "What was the name of the man who wanted to become king over the people?", "Amlici", ["Nehor", "Korihor"], ["Amlici"]),
    q("b", "31", "With what did Alma slay the leader of the Amlicites?", "With the sword", ["With a spear", "With an arrow"], ["sword"]),
    q("c", "15", "At which hill, east of the river Sidon, did the Amlicites arrive?", "The hill Amnihu", ["The hill Manti", "The hill Riplah"], ["Amnihu"]),
  ),
  ch("alma", 3,
    q("a", "4", "What had the Amlicites marked on their foreheads?", "A red mark", ["A blue mark", "A black mark"], ["red"]),
    q("b", "26", "How many souls were sent to the eternal world in that one year?", "Thousands and tens of thousands", ["Hundreds and many thousands", "Only a few hundred people"], ["thousands and tens of thousands"]),
    q("c", "22", "Why did Alma not go up to battle himself this time against the Lamanites?", "Because he was afflicted with a wound", ["Because he did not trust the army", "Because he had another plan"], ["wound"]),
  ),
  ch("alma", 4,
    q("a", "5", "About how many souls united themselves with the church in the seventh year?", "About three thousand five hundred", ["About two thousand five hundred", "About five thousand three hundred"], ["three thousand five hundred"]),
    q("b", "17", "Who was appointed chief judge when Alma handed over the judgment-seat?", "Nephihah", ["Helaman", "Gideon"], ["Nephihah"]),
    q("c", "18", "Which office did Alma retain for himself?", "That of high priest", ["That of army commander", "That of chief judge"], ["high priest"]),
  ),
  ch("alma", 5,
    q("a", "38", "Whose name does the good shepherd who calls us bear?", "The name of Christ", ["The name of Mormon", "The name of Abinadi"], ["name of Christ"]),
    q("b", "3", "By whom was Alma consecrated to be a high priest over the church?", "By his father Alma", ["By King Mosiah", "By the prophet Abinadi"], ["father Alma"]),
    q("c", "52", "According to the Spirit, what is laid at the root of the tree?", "The ax", ["The saw", "The spade"], ["ax"]),
  ),
  ch("alma", 6,
    q("a", "8", "In which valley did Alma next begin to declare the word of God?", "The valley of Gideon", ["The valley of Lemuel", "The valley of Helam"], ["valley of Gideon"]),
    q("b", "2", "What happened to those who repented of their sins and did not yet belong to the church?", "They were baptized unto repentance", ["They were sent to Zarahemla", "They had to wait a year first"], ["unto repentance"]),
    q("c", "6", "For what were the children of God commanded to gather together often?", "Fasting and mighty prayer", ["Offerings and burnt sacrifices", "Building temples and altars"], ["fasting and mighty prayer"]),
  ),
  ch("alma", 7,
    q("a", "10", "Where will the Lord be born, according to Alma?", "At Jerusalem", ["At Nazareth", "At Zarahemla"], ["Jerusalem"]),
    q("b", "10", "How does Alma describe the mother of the Lord?", "A virgin, a precious and chosen vessel", ["A princess, a rich and powerful woman", "A queen, a rich and noble vessel"], ["precious and chosen vessel"]),
    q("c", "24", "Which three things must one have, according to Alma?", "Faith, hope, and charity", ["Faith, repentance, and sacrifices", "Knowledge, wisdom, and power"], ["faith, hope, and charity"]),
  ),
  ch("alma", 8,
    q("a", "3", "To which land did Alma journey in the tenth year of the reign of the judges?", "The land of Melek", ["The land of Gideon", "The land of Jershon"], ["land of Melek"]),
    q("b", "6", "What was the name of the city Alma came to after three days' journey north of Melek?", "Ammonihah", ["Zarahemla", "Jershon"], ["Ammonihah"]),
    q("c", "21", "What was the name of the man who received Alma into his house?", "Amulek", ["Amulon", "Amaleki"], ["Amulek"]),
  ),
  ch("alma", 9,
    q("a", "4", "What did the people of Ammonihah say they would not believe if Alma prophesied?", "That the city would be destroyed in one day", ["That the city would perish in a flood", "That the city would be taken by the Lamanites"], ["in one day"]),
    q("b", "26", "What does the angel say about the coming of the Son of God?", "Not many days hence", ["In many hundred years", "In more than a thousand years"], ["not many days hence"]),
    q("c", "34", "Who stepped forward and also began to preach to the people?", "Amulek", ["Zeezrom", "Antionah"], ["Amulek"]),
  ),
  ch("alma", 10,
    q("a", "2", "Who was the father of Amulek?", "Giddonah", ["Aminadi", "Ishmael"], ["Giddonah"]),
    q("b", "7", "Who appeared to Amulek on his journey?", "An angel of the Lord", ["A prophet from Zarahemla", "A servant of Alma"], ["angel of the Lord"]),
    q("c", "31", "What was the name of the foremost lawyer who accused Amulek and Alma?", "Zeezrom", ["Antionah", "Korihor"], ["Zeezrom"]),
  ),
  ch("alma", 11,
    q("a", "3", "What did a judge receive as wages for a day?", "A senine of gold", ["A limnah of gold", "An onti of silver"], ["senine of gold"]),
    q("b", "21", "Who began to question Amulek?", "Zeezrom", ["Antionah", "Gideon"], ["Zeezrom"]),
    q("c", "38-39", "Who, according to Amulek, is truly the Eternal Father of heaven and earth?", "The Son of God", ["The prophet Alma", "The angel of God"], ["Son of God"]),
  ),
  ch("alma", 12,
    q("a", "20", "Who was Antionah?", "A chief ruler among them", ["A lawyer among them", "A captain among them"], ["chief ruler"]),
    q("b", "16", "What does Alma call the second death?", "A spiritual death", ["A temporal death", "A bodily death"], ["spiritual death"]),
    q("c", "21", "What did God place on the east of the garden of Eden, according to the scripture?", "Cherubim and a flaming sword", ["A wall with a gate of gold", "An angel with a golden key"], ["cherubim"]),
  ),
  ch("alma", 13,
    q("a", "15", "To whom did Abraham pay tithes?", "To the king Melchizedek", ["To the prophet Moses", "To the king Solomon"], ["Melchizedek"]),
    q("b", "17", "Over which land was Melchizedek king?", "The land of Salem", ["The land of Moab", "The land of Egypt"], ["land of Salem"]),
    q("c", "9", "How is the Son called in verse 9?", "The Only Begotten of the Father", ["The Firstborn of the Father", "The Anointed of the Father"], ["Only Begotten of the Father"]),
  ),
  ch("alma", 14,
    q("a", "16", "After the order and faith of whom was the chief judge of Ammonihah?", "Nehor", ["Amlici", "Korihor"], ["Nehor"]),
    q("b", "18", "How many days had Alma and Amulek been in prison before the lawyers and judges came?", "Three days", ["Seven days", "Two days"], ["three days"]),
    q("c", "27", "What happened when Alma and Amulek called upon the Lord for deliverance?", "The earth shook mightily", ["A fire broke out", "It began to hail heavily"], ["shook mightily"]),
  ),
  ch("alma", 15,
    q("a", "1", "To which land did Alma and Amulek go after leaving Ammonihah?", "The land of Sidom", ["The land of Melek", "The land of Nephi"], ["land of Sidom"]),
    q("b", "3", "What was Zeezrom suffering from at Sidom?", "A burning fever", ["A serious wound", "Severe blindness"], ["burning fever"]),
    q("c", "12", "What did Alma do with Zeezrom after he was healed?", "He baptized him unto the Lord", ["He sent him back to Ammonihah", "He made him leave the church"], ["baptized"]),
  ),
  ch("alma", 16,
    q("a", "5", "What was the name of the chief captain of the armies of the Nephites?", "Zoram", ["Moroni", "Gideon"], ["Zoram"]),
    q("b", "10", "What happened to the city of Ammonihah according to Alma 16?", "It was left desolate in one day", ["It was gradually occupied by the Lamanites", "It was swallowed up by an earthquake"], ["in one day"]),
    q("c", "19", "What did the priests proclaim about the Son of God?", "His sufferings and death", ["His riches and power", "His marriage and family"], ["sufferings and death"]),
  ),
  ch("alma", 17,
    q("a", "4", "For how many years had the sons of Mosiah been teaching the word among the Lamanites?", "Fourteen years", ["Twenty-four years", "Seventeen years"], ["fourteen years"]),
    q("b", "21", "What was the name of the king of the land of Ishmael?", "Lamoni", ["Limhi", "Laman"], ["Lamoni"]),
    q("c", "38", "How many of the Lamanites fell by Ammon's sling?", "Six men", ["Four men", "Eight men"], ["six"]),
  ),
  ch("alma", 18,
    q("a", "13", "What does the word Rabbanah mean?", "Powerful or great king", ["Wise and mighty lord", "Brave army commander"], ["great king"]),
    q("b", "43", "How long did King Lamoni lie as if dead on his bed?", "Two days and two nights", ["Three days and three nights", "One day and one night"], ["two days and two nights"]),
    q("c", "9", "What was Ammon doing when the king asked for him?", "He was feeding the king's horses", ["He was feasting with the servants", "He was sleeping in the king's tent"], ["horses"]),
  ),
  ch("alma", 19,
    q("a", "8", "What did Ammon say about King Lamoni when he looked at him?", "He is not dead, but sleeps in God", ["He is wounded and must rest by the fire", "He is sick and needs a physician"], ["in God"]),
    q("b", "13", "What did Lamoni say when he rose again?", "That he had seen his Redeemer", ["That he had seen a great army", "That he had seen his father"], ["Redeemer"]),
    q("c", "28", "Who had caused the multitude to be gathered together?", "A Lamanite woman servant", ["A daughter of the king", "A priest of the people"], ["woman servant"]),
  ),
  ch("alma", 20,
    q("a", "3", "In which land were Ammon's brethren in prison?", "The land of Middoni", ["The land of Ishmael", "The land of Sidom"], ["Middoni"]),
    q("b", "10", "What does Lamoni's father call the Nephite Ammon?", "One of the children of a liar", ["One of the sons of a king", "One of the servants of the devil"], ["children of a liar"]),
    q("c", "23", "What did the old king offer Ammon if he would spare him?", "Even half of the kingdom", ["A third of his treasures", "His eldest daughter as a wife"], ["half of the kingdom"]),
  ),
  ch("alma", 21,
    q("a", "2", "What was the great city called that the Lamanites, the Amalekites and the people of Amulon had built?", "The city of Jerusalem", ["The city of Nephi", "The city of Zarahemla"], ["Jerusalem"]),
    q("b", "14", "By whom were Aaron and his brethren delivered from prison?", "By Lamoni and Ammon", ["By Mosiah and Alma", "By Omner and Himni"], ["Lamoni", "Ammon"]),
    q("c", "22", "What did King Lamoni declare to his people about worshiping the Lord?", "That they were free to worship the Lord anywhere", ["That they could worship only in the synagogues", "That they could worship only the king"], ["worship"]),
  ),
  ch("alma", 22,
    q("a", "3", "What did Aaron and his brothers promise the king in exchange for their lives?", "That they would be his servants", ["That they would give him their possessions", "That they would leave the land"], ["servants"]),
    q("b", "7", "What do the Amalekites say about God, according to the king?", "That there is a God", ["That there are two gods", "That there is no God"], ["there is a God"]),
    q("c", "17", "What did the king do when Aaron had spoken these words?", "He knelt and prostrated himself upon the earth", ["He stood up and walked out of the great hall", "He called his bodyguard together at once"], ["upon the earth"]),
  ),
  ch("alma", 23,
    q("a", "17", "What did the converted Lamanites call themselves?", "The Anti-Nephi-Lehies", ["The Nephi-Lamanites", "The Lehi-Nephites"], ["Anti-Nephi-Lehies"]),
    q("b", "1", "What did the king of the Lamanites command his people regarding Ammon and his brethren?", "That no one should lay hands on them", ["That they must leave the land", "That they could only preach in Ishmael"], ["hands"]),
    q("c", "14", "Which groups did not convert?", "The Amalekites and the Amulonites", ["The Nephites of Zarahemla", "The people of Ishmael and Middoni"], ["Amalekites", "Amulonites"]),
  ),
  ch("alma", 24,
    q("a", "3", "What name did the king give to his son to whom he conferred the kingdom?", "Anti-Nephi-Lehi", ["Anti-Lehi-Nephi", "Nephi-Anti-Lehi"], ["Anti-Nephi-Lehi"]),
    q("b", "16", "What would they do with their swords if their brethren sought to destroy them?", "Bury them deep in the earth", ["Melt them into tools", "Give them to the Nephites"], ["deep in the earth"]),
    q("c", "22", "How many of them were slain by the Lamanites without resistance?", "A thousand and five", ["A thousand and ten", "Five hundred and five"], ["thousand and five"]),
  ),
  ch("alma", 25,
    q("a", "11", "Who was the first to suffer death by fire because of his belief in God?", "Abinadi", ["Amulek", "Gideon"], ["Abinadi"]),
    q("b", "14", "What did the converted Lamanites do with their weapons of war?", "They did bury their weapons", ["They sold their weapons", "They always carried their weapons"], ["bury their weapons"]),
    q("c", "16", "What purpose did the law of Moses serve for them?", "To strengthen their faith in Christ", ["To separate them from the Nephites", "To keep their riches in the temple"], ["faith in Christ"]),
  ),
  ch("alma", 26,
    q("a", "4", "What does Ammon say about thousands of the Lamanites?", "They have been brought into the fold of God", ["They have gone to serve the Nephites", "They have driven out their king"], ["fold of God"]),
    q("b", "22", "What is given to him who repents, exercises faith, and prays continually?", "To know the mysteries of God", ["A place next to the king", "Riches and power in the land"], ["mysteries of God"]),
    q("c", "12", "In what does Ammon say he will boast?", "In the Lord his God", ["In his own strength", "In his own wisdom"], ["God"]),
  ),
  ch("alma", 27,
    q("a", "22", "Which land did the people of Nephi give up to the people of Ammon?", "The land of Jershon", ["The land of Gideon", "The land of Melek"], ["Jershon"]),
    q("b", "12", "Why did the Lord command Ammon to get the people out of the land?", "So that they would not perish", ["So that they could possess more land", "So that they could attack the Nephites"], ["perish"]),
    q("c", "30", "How are the people of Ammon described in verse 30?", "A zealous and beloved people", ["A warlike and feared people", "A rich and mighty people"], ["zealous and beloved people"]),
  ),
  ch("alma", 28,
    q("a", "7", "Which year of the reign of the judges ended after the terrible battle?", "The fifteenth year", ["The twelfth year", "The twentieth year"], ["fifteenth"]),
    q("b", "6", "How is the day of the terrible battle described?", "A sorrowful day", ["A festive day", "A quiet day"], ["sorrowful day"]),
    q("c", "12", "What do the many thousands who mourn for the loss of their kindred do nonetheless?", "They rejoice and exult in the hope", ["They flee the land and hide", "They gather their armies for revenge"], ["exult in the hope"]),
  ),
  ch("alma", 29,
    q("a", "1", "What would Alma wish to be so that he could speak with the trump of God?", "An angel", ["A king", "A prophet"], ["angel"]),
    q("b", "1", "With what would Alma then like to speak?", "With the trump of God", ["With the harp of David", "With the voice of the king"], ["trump of God"]),
    q("c", "8", "To whom does the Lord grant to teach his word out of their own nation and tongue?", "To all nations on earth", ["To the Nephites alone", "To the Jews alone"], ["all nations"]),
  ),
  ch("alma", 30,
    q("a", "12", "What was the name of the Anti-Christ who preached that there would be no Christ?", "Korihor", ["Nehor", "Amlici"], ["Korihor"]),
    q("b", "50", "What happened to Korihor after Alma had spoken?", "He was struck dumb, unable to speak", ["He was struck blind, unable to see", "He was stoned by the people at once"], ["struck dumb"]),
    q("c", "23", "What was the name of the high priest in the land of Gideon?", "Giddonah", ["Nephihah", "Helaman"], ["Giddonah"]),
  ),
  ch("alma", 31,
    q("a", "21", "What does the name Rameumptom mean?", "The holy stand for prayer", ["The high tower of God", "The place of the chosen"], ["holy stand"]),
    q("b", "3", "What did the Zoramites call the land where they gathered?", "Antionum", ["Gideon", "Jershon"], ["Antionum"]),
    q("c", "7", "Who was Alma's eldest son, whom he did not take along to the Zoramites?", "Helaman", ["Shiblon", "Corianton"], ["Helaman"]),
  ),
  ch("alma", 32,
    q("a", "28", "To what does Alma compare the word?", "To a seed", ["To a river", "To a fire"], ["seed"]),
    q("b", "21", "What is faith not, according to Alma?", "To have a perfect knowledge of things", ["To hope for things which are not seen", "To rely on a seed planted in the heart"], ["perfect knowledge"]),
    q("c", "10", "Where can God be worshiped, according to Alma?", "Anywhere, not only in synagogues", ["Only in the synagogues on the sabbath", "Only in the temple of the king"], ["synagogues"]),
  ),
  ch("alma", 33,
    q("a", "3", "Which prophet of old is quoted concerning prayer or worship?", "Zenos", ["Isaiah", "Neum"], ["Zenos"]),
    q("b", "15", "Which second prophet of old also spoke of the Son of God?", "Zenock", ["Ezias", "Jarom"], ["Zenock"]),
    q("c", "19", "What was raised up in the wilderness so that whoever looked upon it might live?", "A type of Christ", ["An altar of stone", "A great tent"], ["type"]),
  ),
  ch("alma", 34,
    q("a", "10", "What kind of sacrifice must there be, according to Amulek?", "A great and last sacrifice", ["A daily offering of grain", "A yearly offering of sheep"], ["great and last sacrifice"]),
    q("b", "21", "When should one cry to the Lord in one's house, according to Amulek?", "Morning, mid-day, and evening", ["Once a week in the synagogue", "Only when there is need in the land"], ["morning", "evening"]),
    q("c", "32", "What is this life the time for, according to Amulek?", "To prepare to meet God", ["To gain riches and honor", "To build a kingdom on earth"], ["meet God"]),
  ),
  ch("alma", 35,
    q("a", "1", "To which land did Alma and Amulek cross over after their preaching to the Zoramites?", "The land of Jershon", ["The land of Melek", "The land of Gideon"], ["land of Jershon"]),
    q("b", "13", "Where did the people of Ammon go when they left Jershon?", "To the land of Melek", ["To the land of Nephi", "To the land of Sidom"], ["land of Melek"]),
    q("c", "12", "Which year of the reign of the judges ended in this chapter?", "The seventeenth", ["The sixteenth", "The eighteenth"], ["seventeenth"]),
  ),
  ch("alma", 36,
    q("a", "10", "How long could Alma not open his mouth after the angel appeared?", "Three days and three nights", ["Two days and two nights", "Seven days and seven nights"], ["three days and three nights"]),
    q("b", "18", "What words did Alma cry out within his heart?", "O Jesus, Son of God, have mercy on me", ["O Lord, save me from all of my enemies", "O God, take my life away from me now"], ["Son of God"]),
    q("c", "22", "To whose vision does Alma compare what he saw, God sitting on his throne?", "To that of Lehi", ["To that of Nephi", "To that of Mosiah"], ["Lehi"]),
  ),
  ch("alma", 37,
    q("a", "6", "What is brought to pass by small and simple things, according to Alma?", "Great things", ["Small things", "Useless things"], ["great things"]),
    q("b", "21", "About how many plates did Alma tell Helaman to keep?", "Twenty-four plates", ["Twenty-two plates", "Twenty-six plates"], ["twenty"]),
    q("c", "26", "What happened to those who did not repent?", "They have been destroyed", ["They have been banished", "They have been scattered"], ["destroyed"]),
  ),
  ch("alma", 38,
    q("a", "4", "Why was Shiblon stoned, according to Alma?", "For the sake of the word", ["For the sake of his wealth", "For the sake of his army"], ["word"]),
    q("b", "13", "Why do the Zoramites pray, according to Alma?", "To be heard of men and praised", ["To be blessed of God and angels", "To confess their sins before God"], ["heard of men"]),
    q("c", "11", "In what must Shiblon not boast, according to Alma?", "In his own wisdom", ["In the grace of God", "In his brothers' help"], ["own wisdom"]),
  ),
  ch("alma", 39,
    q("a", "10", "With whom was Corianton to counsel in all his undertakings?", "With his elder brothers", ["With the king of the land", "With the teachers of the Zoramites"], ["elder brothers"]),
    q("b", "14", "Why should Corianton not seek after riches?", "Because he cannot carry them with him", ["Because the Lamanites would take them", "Because riches are only for the judges"], ["carry them with"]),
    q("c", "18", "To whom must the plan of redemption be made known, according to Alma?", "To this people and to their children", ["Only to the priests of the church", "Only to the judges of the land"], ["this people"]),
  ),
  ch("alma", 40,
    q("a", "12", "What is the state of happiness of the righteous between death and resurrection called?", "A state called paradise", ["A state called the kingdom", "A state called the garden of Eden"], ["paradise"]),
    q("b", "14", "In what state are the souls of the wicked, according to verse 14?", "In darkness, with a fearful looking for wrath", ["In rest and peace, free of all their troubles", "In sleep until the time of the resurrection"], ["darkness", "fearful"]),
    q("c", "23", "What will happen to the soul at the restoration, according to Alma?", "The soul shall be restored to the body", ["The soul will remain separated forever", "The body will be given to the earth"], ["restored to the body"]),
  ),
  ch("alma", 41,
    q("a", "13", "What does the word restoration mean, according to Alma?", "To bring back evil for evil, carnal for carnal", ["To bring someone from sin to happiness", "To give all things again without judgment"], ["evil for evil"]),
    q("b", "10", "What, according to Alma, has never been happiness?", "Wickedness", ["Hard work", "Obedience"], ["wickedness"]),
    q("c", "14", "What must Corianton do continually, according to Alma?", "Do good continually", ["Take revenge continually", "Seek riches continually"], ["good continually"]),
  ),
  ch("alma", 42,
    q("a", "4", "What was granted to man, according to Alma?", "A probationary time to repent", ["A time of rest without law", "An eternal stay in the garden of Eden"], ["probationary"]),
    q("b", "22-23", "On whom does mercy lay claim, according to Alma?", "The penitent who repent of their sins", ["The mighty who rule the land", "The rich who offer many sacrifices"], ["penitent"]),
    q("c", "27", "Who may come and partake of the waters of life, according to Alma?", "Whosoever will come may come", ["Only the priests of the church", "Only those rich enough"], ["will come"]),
  ),
  ch("alma", 43,
    q("a", "17", "How old was Moroni when he was appointed chief captain?", "Twenty-five years old", ["Thirty-five years old", "Forty-five years old"], ["twenty"]),
    q("b", "19", "With what had Moroni prepared his people?", "Breastplates and arm-shields", ["Chariots and strong warhorses", "Helmets and long iron spears"], ["breastplates", "arm-shields"]),
    q("c", "44", "What was the name of the chief captain of the Lamanites?", "Zerahemnah", ["Amalickiah", "Zemnarihah"], ["Zerahemnah"]),
  ),
  ch("alma", 44,
    q("a", "6", "What did Moroni command Zerahemnah?", "To deliver up his weapons of war", ["To send his whole army home", "To surrender his kingdom to Moroni"], ["weapons of war"]),
    q("b", "20", "What did Moroni do with the Lamanites after he caused the work of death to cease?", "He took their weapons of war", ["He let them keep their weapons", "He gave them food and clothing"], ["weapons of war"]),
    q("c", "24", "Which year of the reign of the judges ended with the record of Alma?", "The eighteenth", ["The seventeenth", "The nineteenth"], ["eighteenth"]),
  ),
  ch("alma", 45,
    q("a", "4", "In whom did Alma ask his son Helaman to believe, who shall come?", "In Jesus Christ, the Messiah", ["In King Benjamin of old", "In the prophet Moses of old"], ["Jesus Christ"]),
    q("b", "10", "How many years after Christ's appearance would the Nephites dwindle in unbelief, according to Alma?", "Four hundred years", ["Two hundred years", "Six hundred years"], ["four hundred years"]),
    q("c", "18", "What happened to Alma after he left the land of Zarahemla?", "He was never heard of again", ["He died soon after in Melek", "He was captured by the Lamanites"], ["never heard of"]),
  ),
  ch("alma", 46,
    q("a", "3", "What was the name of the leader of those who broke away from their brethren?", "Amalickiah", ["Zerahemnah", "Lehonti"], ["Amalickiah"]),
    q("b", "12", "On what did Moroni write the inscription \"In memory of our God\"?", "On a piece of his coat", ["On a plate of brass", "On a wall of the temple"], ["coat"]),
    q("c", "36", "What did Moroni have hoisted on every tower in the land of the Nephites?", "The title of liberty", ["A white flag of peace", "The royal standard"], ["title of liberty"]),
  ),
  ch("alma", 47,
    q("a", "7", "What was the name of the mount on which the Lamanites gathered?", "The mount Antipas", ["The mount Manti", "The mount Onidah"], ["Antipas"]),
    q("b", "11", "What was the name of the leader of those who were on the mount?", "Lehonti", ["Lamoni", "Zerahemnah"], ["Lehonti"]),
    q("c", "18", "What did Amalickiah have done to get Lehonti out of the way?", "Had poison given to him by degrees", ["Had him killed with the sword", "Had him imprisoned in Nephi"], ["poison"]),
  ),
  ch("alma", 48,
    q("a", "5", "From whom did Amalickiah appoint chief captains?", "From the Zoramites", ["From the Amlicites", "From the Nephites"], ["Zoramites"]),
    q("b", "11", "What kind of man was Moroni, according to verse 11?", "A man who did not delight in bloodshed", ["A man who liked to wage war to win", "A man who sought power rather than peace"], ["bloodshed"]),
    q("c", "21", "When were the Nephites compelled to contend against their will?", "Toward the end of the nineteenth year", ["Toward the end of the tenth year", "Toward the start of the twentieth year"], ["nineteenth"]),
  ),
  ch("alma", 49,
    q("a", "3", "Which city had been rebuilt when the Lamanites attacked again?", "Ammonihah", ["Nephihah", "Zarahemla"], ["Ammonihah"]),
    q("b", "4", "With what had the Nephites surrounded themselves?", "A ridge of earth", ["A wall of stone", "A moat full of water"], ["ridge of earth"]),
    q("c", "24", "About how many Nephites were wounded at the entrance?", "About fifty of them", ["About a hundred of them", "About two hundred of them"], ["fifty"]),
  ),
  ch("alma", 50,
    q("a", "13", "What did the Nephites call the city they began to found by the east sea?", "The city of Moroni", ["The city of Lehi", "The city of Aaron"], ["Moroni"]),
    q("b", "2", "What did Moroni have placed on top of the ridges of earth around the cities?", "Timbers as high as a man", ["Brick walls with watchtowers", "A wide moat with sharp stakes"], ["timbers"]),
    q("c", "40", "What was the name of the son of Nephihah who succeeded him as chief judge?", "Pahoran", ["Helaman", "Moronihah"], ["Pahoran"]),
  ),
  ch("alma", 51,
    q("a", "5", "What were those called who wanted Pahoran removed from the judgment-seat?", "The king-men", ["The freemen", "The law-keepers"], ["king-men"]),
    q("b", "34", "Who put a javelin to King Amalickiah's heart?", "Teancum", ["Moroni", "Helaman"], ["Teancum"]),
    q("c", "19", "How many of the dissenters were hewn down by the sword?", "Four thousand", ["Two thousand", "Six thousand"], ["four thousand"]),
  ),
  ch("alma", 52,
    q("a", "3", "What was the name of Amalickiah's brother who became king?", "Ammoron", ["Amulon", "Ammon"], ["Ammoron"]),
    q("b", "16", "Which city did Teancum receive orders to attack and, if possible, retake?", "The city of Mulek", ["The city of Gid", "The city of Nephihah"], ["city of Mulek"]),
    q("c", "33", "Who was the Lamanite leader with an unconquerable spirit?", "Jacob, a Zoramite", ["Lehonti, a Lamanite", "Ammoron, an Amalekite"], ["Jacob"]),
  ),
  ch("alma", 53,
    q("a", "18", "How many of those young men entered into the covenant and took their weapons of war?", "Two thousand", ["One thousand", "Four thousand"], ["two thousand"]),
    q("b", "1", "What did the captured Lamanites have to do?", "Bury their dead", ["Build a temple", "Till the land"], ["bury their dead"]),
    q("c", "21", "What had the young soldiers been taught, according to verse 21?", "To keep the commandments of God", ["To use the weapons of the enemy", "To follow the law of the king"], ["keep the commandments of God"]),
  ),
  ch("alma", 54,
    q("a", "20", "What did Ammoron agree to do with Moroni in this exchange of letters?", "An exchange of prisoners of war", ["A peace treaty without conditions", "The surrender of the city of Gid"], ["prisoners"]),
    q("b", "16", "Whose brother was Ammoron, the king of the Lamanites?", "Amalickiah's", ["Zerahemnah's", "Lehonti's"], ["Amalickiah"]),
    q("c", "23", "Whom did Ammoron say he was a descendant of?", "Zoram", ["Nephi", "Laman"], ["Zoram"]),
  ),
  ch("alma", 55,
    q("a", "5", "What was the name of the man Moroni chose to deceive the guards of the prisoners?", "Laman", ["Lamoni", "Lemuel"], ["Laman"]),
    q("b", "7", "In which city were the captured Nephites guarded?", "In the city of Gid", ["In the city of Mulek", "In the city of Cumeni"], ["city of Gid"]),
    q("c", "13", "With what did Laman and his men put the Lamanite guards to sleep?", "With abundant wine", ["With a heavy meal", "With sweet fruit"], ["wine"]),
  ),
  ch("alma", 56,
    q("a", "10", "Who was the commander of the army to which Helaman joined his young soldiers?", "Antipus", ["Teancum", "Pahoran"], ["Antipus"]),
    q("b", "47", "What did the young soldiers think more upon than upon their lives?", "The liberty of their fathers", ["The riches of their mothers", "The glory of their king"], ["liberty of their fathers"]),
    q("c", "56", "How many of Helaman's young soldiers had fallen to the earth after the battle?", "Not one of them had fallen", ["Two of them had fallen", "Fifty of them had fallen"], ["not one"]),
  ),
  ch("alma", 57,
    q("a", "19", "How many young soldiers made up Helaman's little band?", "Two thousand and sixty", ["Two thousand and seventy", "Two thousand and sixteen"], ["two thousand and sixty"]),
    q("b", "25", "How many of the young soldiers had fainted because of the loss of blood?", "Two hundred", ["Three hundred", "Four hundred"], ["two hundred"]),
    q("c", "29", "Who commanded the band that was appointed to guard the prisoners?", "A man named Gid", ["A man named Antipus", "A man named Lehi"], ["Gid"]),
  ),
  ch("alma", 58,
    q("a", "1", "Which city was the next object of Helaman and his army?", "The city of Manti", ["The city of Gid", "The city of Zeezrom"], ["city of Manti"]),
    q("b", "8", "How many men came to Helaman's assistance with food?", "Two thousand men", ["Six thousand men", "One thousand men"], ["two thousand men"]),
    q("c", "28", "How did Helaman and his army take possession of the city of Manti?", "By a stratagem, without bloodshed", ["By a long siege and starvation", "By a direct assault with weapons"], ["stratagem"]),
  ),
  ch("alma", 59,
    q("a", "3", "To whom did Moroni send an epistle to have men gathered together?", "To Pahoran", ["To Helaman", "To Teancum"], ["Pahoran"]),
    q("b", "8", "Which city was lost to the Lamanites, so that the people had to flee?", "The city of Nephihah", ["The city of Mulek", "The city of Cumeni"], ["Nephihah"]),
    q("c", "13", "With whom was Moroni angry because of their indifference to the freedom of the country?", "With the government", ["With the Lamanites", "With his own army"], ["government"]),
  ),
  ch("alma", 60,
    q("a", "1", "To whom did Moroni write his epistle?", "To the governor Pahoran", ["To the king of the Lamanites", "To Helaman, the high priest"], ["Pahoran"]),
    q("b", "36", "What does Moroni say about what he seeks in his epistle?", "Not power, but to pull it down", ["Power and authority over all the land", "Honor and glory on the battlefield"], ["pull it down"]),
    q("c", "3", "Who suffered exceedingly great sufferings together with Moroni and his men?", "Helaman and his men", ["Teancum and his men", "Pahoran and his men"], ["Helaman"]),
  ),
  ch("alma", 61,
    q("a", "5", "To which land did Pahoran flee when he was driven from the judgment-seat?", "To the land of Gideon", ["To the land of Melek", "To the land of Jershon"], ["land of Gideon"]),
    q("b", "8", "What had the insurgents in Zarahemla done?", "They had appointed a king over them", ["They had set the temple on fire", "They had deposed and banished all judges"], ["appointed a king"]),
    q("c", "9", "What did Pahoran rejoice in, in his reply to Moroni?", "The greatness of Moroni's heart", ["The victory over the Lamanites", "The support of the king-men"], ["greatness"]),
  ),
  ch("alma", 62,
    q("a", "8", "What happened to Pachus and to Pahoran when Zarahemla was retaken?", "Pachus was slain, Pahoran restored", ["Pahoran was slain, Pachus restored", "Moroni was slain, Pahoran stayed away"], ["Pachus", "restored"]),
    q("b", "43", "To whom did Moroni yield up command of his armies?", "To his son Moronihah", ["To his son Helaman", "To Lehi and Teancum"], ["Moronihah"]),
    q("c", "36-37", "Which of Moroni's commanders was slain in the camp of the Lamanites?", "Teancum", ["Pahoran", "Moronihah"], ["Teancum"]),
  ),
  ch("alma", 63,
    q("a", "1", "Who took possession of the sacred things in the thirty-sixth year?", "Shiblon", ["Helaman", "Corianton"], ["Shiblon"]),
    q("b", "5", "What was the name of the man who built an exceedingly large ship?", "Hagoth", ["Morianton", "Teomner"], ["Hagoth"]),
    q("c", "8", "What happened to those who embarked and sailed forth?", "They were never heard of again", ["They settled in the land northward", "They returned home after a year"], ["never heard of"]),
  ),
  // ===== EINDE =====
];
