import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Helaman (English edition). Each fact is tied to the verses in `verses`; `npm run genees:check` verifies that.
export const helaman: GeneesChapterSeed[] = [
  ch("hel", 1,
    q("a", "3", "What were the names of the sons of Pahoran who contended for the judgment-seat?", "Pahoran, Paanchi, and Pacumeni", ["Pahoran, Moronihah, and Pacumeni", "Pahoran, Paanchi, and Pachus"], ["Paanchi", "Pacumeni"]),
    q("b", "10", "What was the name of the man who murdered Pahoran?", "Kishkumen", ["Gadianton", "Coriantumr"], ["Kishkumen"]),
    q("c", "15", "What was the name of the leader of the army that came down against the Nephites, a descendant of Zarahemla?", "Coriantumr", ["Zerahemnah", "Lehonti"], ["Coriantumr"]),
  ),
  ch("hel", 2,
    q("a", "4", "Who was Gadianton, according to Helaman 2?", "A man expert in words and in craft", ["The new chief judge of the people", "A commander of the Nephite armies"], ["craft"]),
    q("b", "6", "Who stopped Kishkumen when he wanted to destroy Helaman?", "A servant of Helaman", ["A guard of the king", "A priest of Gadianton"], ["of Helaman"]),
    q("c", "2", "What was Helaman, the son of Helaman, appointed to do by the voice of the people?", "To fill the judgment-seat", ["To command the Nephite army", "To manage the temple affairs"], ["judgment-seat"]),
  ),
  ch("hel", 3,
    q("a", "21", "What were the names of Helaman's two sons?", "Nephi and Lehi", ["Nephi and Shiblon", "Lehi and Moronihah"], ["Nephi", "Lehi"]),
    q("b", "9", "In what did the people in the land northward dwell?", "In tents and houses of cement", ["In caves and houses of wood", "In cities of stone and mountains"], ["houses of cement"]),
    q("c", "37", "Who took over the judgment-seat when Helaman died?", "His eldest son Nephi", ["His youngest son Lehi", "His brother Moronihah"], ["Nephi"]),
  ),
  ch("hel", 4,
    q("a", "2", "Where did the rebellious ones who were driven out of the land go?", "To the king of the Lamanites", ["To the mountains in the north", "To the land of the Zoramites"], ["king of the Lamanites"]),
    q("b", "10", "How much of their possessions did the Nephites regain?", "Half of all their possessions", ["A third of all their possessions", "A tenth of all their possessions"], ["half of all their possessions"]),
    q("c", "12", "What did the Nephites do in their wickedness, according to verse 12?", "They oppressed the poor", ["They neglected their temples", "They refused to pay taxes"], ["poor"]),
  ),
  ch("hel", 5,
    q("a", "1", "To whom did Nephi deliver the judgment-seat?", "To Cezoram", ["To Pahoran", "To Moronihah"], ["Cezoram"]),
    q("b", "19", "How many Lamanites were convinced by the preaching of Nephi and Lehi?", "Eight thousand", ["Two thousand", "Four thousand"], ["eight thousand"]),
    q("c", "24", "What encircled Nephi and Lehi in the prison without burning them?", "A pillar of fire", ["A white cloud", "A wall of light"], ["pillar of fire"]),
  ),
  ch("hel", 6,
    q("a", "10", "What were the land south and the land north called?", "South Lehi, north Mulek", ["South Mulek, north Lehi", "South Nephi, north Zarahemla"], ["Lehi", "Mulek"]),
    q("b", "15", "Who was murdered by an unknown hand in the sixty-sixth year?", "Cezoram", ["Moronihah", "Helaman"], ["Cezoram"]),
    q("c", "18", "By whom had the band of murderers and plunderers been formed?", "By Kishkumen and Gadianton", ["By Coriantumr and Tubaloth", "By Pacumeni and Paanchi"], ["Kishkumen", "Gadianton"]),
  ),
  ch("hel", 7,
    q("a", "10", "Where was Nephi when he poured out his soul to God?", "On a tower in his garden", ["In the temple of Zarahemla", "On a mountain outside the city"], ["tower"]),
    q("b", "17", "What question did Nephi ask the people in verse 17?", "Why will ye die?", ["Why will ye depart?", "Why will ye flee?"], ["why will ye die"]),
    q("c", "25", "With which band had the people united themselves?", "The secret band of Gadianton", ["The wanderers from the north", "The Lamanites from the wilderness"], ["Gadianton"]),
  ),
  ch("hel", 8,
    q("a", "14", "What did Moses lift up in the wilderness?", "The brazen serpent", ["A great brazen altar", "A great brazen sea"], ["brazen serpent"]),
    q("b", "17", "Who saw Christ's coming and was filled with gladness?", "Abraham", ["Elijah", "Jonah"], ["Abraham"]),
    q("c", "21", "Which of the sons of Zedekiah was not slain?", "Mulek", ["Nephi", "Joseph"], ["Mulek"]),
  ),
  ch("hel", 9,
    q("a", "3", "What did the five men find when they came to the judgment-seat?", "The chief judge had fallen to the earth", ["The judgment-seat was abandoned and empty", "The chief judge was holding a public meeting"], ["fallen to the earth"]),
    q("b", "23", "What was the name of the murdered chief judge?", "Seezoram", ["Moronihah", "Pacumeni"], ["Seezoram"]),
    q("c", "26", "To whose house did Nephi say the men should go?", "To the house of Seantum", ["To the house of Pacumeni", "To the house of Paanchi"], ["Seantum"]),
  ),
  ch("hel", 10,
    q("a", "7", "What will happen in heaven with whatever Nephi seals on earth, according to the Lord?", "It will be sealed in heaven", ["It will be revoked in heaven", "It will be forgotten in heaven"], ["sealed in heaven"]),
    q("b", "8", "What would happen if Nephi said to the temple that it should be rent?", "The temple would be rent in twain", ["The temple would go up in flames", "The temple would sink into the ground"], ["rent in twain"]),
    q("c", "9", "What would happen if Nephi said to the mountain, \"Be thou cast down\"?", "The mountain would become smooth", ["The mountain would go up in fire", "The mountain would split in two"], ["smooth"]),
  ),
  ch("hel", 11,
    q("a", "4", "What did Nephi ask to be in the land instead of the sword?", "A famine in the land", ["An earthquake in the land", "A flood in the land"], ["famine"]),
    q("b", "13", "What did Nephi ask the Lord to send forth upon the face of the earth?", "Rain", ["Fire", "Snow"], ["rain"]),
    q("c", "26", "What did the dissenters become in time?", "A very great band of robbers", ["A mighty and peaceful people", "An army of the Lamanites"], ["band of robbers"]),
  ),
  ch("hel", 12,
    q("a", "7", "Compared to what are the children of men even less, according to verse 7?", "The dust of the earth", ["The sand of the sea", "A stone in the river"], ["dust of the earth"]),
    q("b", "14", "What happens if God says to the earth, \"Thou shalt go back\"?", "The day is lengthened many hours", ["The sun sets and never rises", "The night is lengthened many hours"], ["many hours"]),
    q("c", "23", "Who shall be saved, according to these verses?", "Those who will repent and hearken", ["Those who are rich and offer much", "Those who have never sinned"], ["repent and hearken"]),
  ),
  ch("hel", 13,
    q("a", "2", "What was Samuel by descent?", "A Lamanite", ["A Nephite", "A Zoramite"], ["Lamanite"]),
    q("b", "4", "On what did Samuel climb when they would not let him into the city?", "On the wall of the city", ["On the tower of the temple", "On a hill outside the city"], ["wall"]),
    q("c", "9", "How many years did the Lord say would not pass away before He would cause the Nephites to be smitten?", "Not four hundred years", ["Not two hundred years", "Not a thousand years"], ["four hundred years"]),
  ),
  ch("hel", 14,
    q("a", "2", "In how many years would the Son of God come, according to Samuel?", "In five years", ["In ten years", "In twenty years"], ["five years"]),
    q("b", "5", "What shall arise in heaven as a sign, according to Samuel?", "A new star", ["A new sun", "A new moon"], ["new star"]),
    q("c", "21", "What will there be for many hours when the Lord dies?", "Thunderings and lightnings", ["A hailstorm lasting three days", "A strong wind without lightning"], ["thunderings"]),
  ),
  ch("hel", 15,
    q("a", "9", "What have the converted Lamanites buried, according to Samuel?", "Their weapons of war", ["Their golden idols", "Their silver treasures"], ["weapons of war"]),
    q("b", "1", "What will happen to the people's houses if they do not repent, according to Samuel?", "They will be left desolate", ["They will be set on fire", "They will be given to the Lamanites"], ["desolate"]),
    q("c", "16", "What will the Lord do with the Lamanites, according to verse 16?", "Not utterly destroy them", ["Punish them immediately", "Forget them forever"], ["utterly destroy"]),
  ),
  ch("hel", 16,
    q("a", "7", "What did Samuel do when the people went forth to lay their hands on him?", "He cast himself down from the wall and fled", ["He went to meet the people and spoke", "He hid himself in the temple until night"], ["cast himself down from the wall"]),
    q("b", "4", "What did Nephi do with those who believed Samuel's words?", "He kept baptizing and preaching repentance", ["He sent all of them back to their own homes", "He made them all bring offerings and sacrifices"], ["baptizing"]),
    q("c", "13", "In which year of the reign of the judges were great signs given?", "The ninetieth year", ["The eightieth year", "The hundredth year"], ["ninetieth"]),
  ),
  // ===== EINDE =====
];
