import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Jacob (English edition). Each fact is tied to the verses in `verses`; `npm run genees:check` verifies that.
export const jakob: GeneesChapterSeed[] = [
  ch("jacob", 1,
    q("a", "1", "How many years had passed since Lehi left Jerusalem when Nephi gave Jacob a commandment?", "Fifty-five years", ["Thirty-five years", "Seventy-five years"], ["five years"]),
    q("b", "11", "How were the kings who reigned after Nephi called by the people?", "Second Nephi", ["Nephi the Younger", "Second Lehi"], ["second Nephi"]),
    q("c", "18", "By whose hand were Jacob and Joseph consecrated priests and teachers?", "By the hand of Nephi", ["By the hand of Lehi", "By the hand of Sam"], ["hand of Nephi"]),
  ),
  ch("jacob", 2,
    q("a", "12", "What had many of the people begun to search for, according to Jacob?", "Gold and silver", ["Land and cattle", "Power and fame"], ["gold", "silver"]),
    q("b", "27", "How many wives may a man among this people have, according to the Lord?", "No more than one wife", ["No more than two wives", "No more than seven wives"], ["one wife"]),
    q("c", "18", "What should one seek before seeking riches, according to Jacob?", "The kingdom of God", ["The favor of the king", "A plot of land"], ["kingdom of God"]),
  ),
  ch("jacob", 3,
    q("a", "14", "What are the plates Jacob writes on called?", "The plates of Jacob", ["The plates of Sam", "The plates of Joseph"], ["plates of Jacob"]),
    q("b", "9", "What does Jacob command the people concerning the Lamanites?", "Not to revile them for their skins", ["To drive them out of the land", "To teach them to read and write"], ["revile", "skins"]),
    q("c", "1", "To whom does Jacob first want to speak in this chapter?", "Those who are pure in heart", ["Those who are rich in gold", "Those who have left the law"], ["pure in heart"]),
  ),
  ch("jacob", 4,
    q("a", "5", "Why do Jacob and his people keep the law of Moses?", "Because it points their souls to Christ", ["Because the king requires it of them", "Because otherwise they would lose their land"], ["souls"]),
    q("b", "9", "By what power was the earth created, according to Jacob?", "By the power of his word", ["By the power of his arm", "By the help of the angels"], ["power of his word"]),
    q("c", "16", "What will the stone the Jews reject become, according to the scriptures?", "The only sure foundation", ["An ornament for the king", "The gate of the temple"], ["sure foundation"]),
  ),
  ch("jacob", 5,
    q("a", "3", "To what does the Lord, according to Zenos, liken the house of Israel?", "To a tame olive tree", ["To a wild grapevine", "To a tame fig tree"], ["tame olive tree"]),
    q("b", "41", "What did the Lord of the vineyard ask his servant, weeping?", "What could I have done more?", ["Why did you not warn me?", "Who planted these trees?"], ["done more"]),
    q("c", "50", "What did the servant say when the Lord of the vineyard wanted to cut down the trees?", "Spare it a little longer", ["Call in the new servants", "Then cut them all down"], ["Spare it a little longer"]),
  ),
  ch("jacob", 6,
    q("a", "6", "What question does Jacob ask the people who harden their hearts?", "Why will ye die?", ["Why will ye depart?", "Why will ye fight?"], ["why will ye die"]),
    q("b", "11", "Through which gate must one enter, according to Jacob?", "Through the strait gate", ["Through the golden gate", "Through the eastern gate"], ["strait gate"]),
    q("c", "3", "What will happen to the world, according to Jacob?", "It will be burned with fire", ["It will be flooded with water", "It will be destroyed by storm"], ["burned with fire"]),
  ),
  ch("jacob", 7,
    q("a", "1", "What was the name of the man who preached among the people that there would be no Christ?", "Sherem", ["Korihor", "Zeezrom"], ["Sherem"]),
    q("b", "15", "What happened to Sherem after Jacob had spoken his words?", "He fell to the earth by God's power", ["He fled the land by night", "He was imprisoned by the people"], ["fell to the earth"]),
    q("c", "27", "To whom did Jacob give the plates?", "To his son Enos", ["To his brother Joseph", "To his son Jarom"], ["Enos"]),
  ),
  // ===== EINDE =====
];
