import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Mosiah (English edition). Each fact is tied to the verses in `verses`; `npm run genees:check` verifies that.
export const mosiah: GeneesChapterSeed[] = [
  ch("mosiah", 1,
    q("a", "2", "What were the names of King Benjamin's three sons?", "Mosiah, Helorum, and Helaman", ["Mosiah, Benjamin, and Helaman", "Mosiah, Helorum, and Amaleki"], ["Mosiah", "Helorum", "Helaman"]),
    q("b", "16", "What object, besides the plates, was also entrusted to Mosiah?", "The sword of Laban", ["The crown of Zedekiah", "The ark of the covenant"], ["sword of Laban"]),
    q("c", "12", "What did King Benjamin say would never be blotted out, except through transgression?", "The name he gives them", ["The temple they build", "The law they receive"], ["name"]),
  ),
  ch("mosiah", 2,
    q("a", "7", "What did King Benjamin have built so that the people could hear his words?", "A tower", ["A bridge", "An altar"], ["tower"]),
    q("b", "17", "According to Benjamin, whom are you serving when you serve your fellow beings?", "Only your God", ["Only the king", "Only yourselves"], ["your God"]),
    q("c", "14", "With what did King Benjamin labor to serve his people?", "With his own hands", ["With hired workers", "With his soldiers"], ["own hands"]),
  ),
  ch("mosiah", 3,
    q("a", "8", "What name and which mother does the angel give for the Lord who will come?", "Jesus Christ, and his mother Mary", ["Immanuel, and his mother Sarah", "John, and his mother Elisabeth"], ["Jesus Christ", "Mary"]),
    q("b", "10", "When will He rise from the dead, according to the angel?", "On the third day", ["On the seventh day", "After forty days"], ["third day"]),
    q("c", "19", "According to verse 19, what is the natural man unless he yields to the Holy Spirit?", "An enemy to God", ["A friend to man", "A servant to law"], ["enemy to God"]),
  ),
  ch("mosiah", 4,
    q("a", "1", "How were the people lying when King Benjamin cast his eyes over the multitude?", "They had fallen to the earth", ["They had fled in great panic", "They had all fallen asleep"], ["fallen to the earth"]),
    q("b", "19", "What does Benjamin call us all, in our dependence on God?", "Beggars", ["Rich men", "Rulers"], ["beggars"]),
    q("c", "14", "What will parents not suffer their children to do, according to Benjamin?", "Go hungry or naked", ["Be punished or fall ill", "Go thirsty or cold"], ["hungry", "naked"]),
  ),
  ch("mosiah", 5,
    q("a", "7", "By what name will the people be called because of the covenant, according to Benjamin?", "The children of Christ", ["The servants of the king", "The children of Benjamin"], ["children of Christ"]),
    q("b", "5", "What were the people willing to do in the covenant with God?", "To do his will and keep his commandments", ["To give all their possessions to the king", "To leave the land and live elsewhere"], ["his will", "commandments"]),
    q("c", "14", "Which animal of his neighbor does no one keep for himself, according to Benjamin?", "An ass", ["An ox", "A horse"], ["ass"]),
  ),
  ch("mosiah", 6,
    q("a", "4", "In which year of his age did Mosiah begin to reign?", "His thirtieth", ["His twentieth", "His fortieth"], ["thirtieth"]),
    q("b", "5", "How many years did King Benjamin live after Mosiah became king?", "Three more years", ["Seven more years", "Ten more years"], ["three"]),
    q("c", "7", "How did King Mosiah make sure he was not burdensome to his people?", "He tilled the earth himself", ["He had slaves till his land", "He asked the people for gifts"], ["till"]),
  ),
  ch("mosiah", 7,
    q("a", "3", "Who led the group of strong men who went up to the land of Lehi-Nephi?", "Ammon", ["Limhi", "Zeniff"], ["Ammon"]),
    q("b", "4", "How many days did they wander in the wilderness?", "Forty days", ["Fourteen days", "Seventy days"], ["forty days"]),
    q("c", "9", "Who was the king of the people in the land of Nephi whom Ammon met?", "Limhi, son of Noah", ["Laman, son of Zeniff", "Noah, son of Limhi"], ["Limhi", "Noah"]),
  ),
  ch("mosiah", 8,
    q("a", "9", "What were the twenty-four plates made of?", "Pure gold", ["Pure brass", "Pure silver"], ["pure gold"]),
    q("b", "15", "What is a seer, according to King Limhi?", "Greater than a prophet", ["Equal to a high priest", "Lesser than the king"], ["greater than a prophet"]),
    q("c", "7", "How many men did Limhi send into the wilderness to find the land of Zarahemla?", "Forty-three men", ["Thirty-three men", "Sixty-three men"], ["forty"]),
  ),
  ch("mosiah", 9,
    q("a", "1", "Who is the writer of Mosiah 9?", "Zeniff", ["Ammon", "Limhi"], ["Zeniff"]),
    q("b", "11", "How many years had Zeniff's people lived in the land when King Laman began to grow uneasy?", "Twelve years", ["Six years", "Twenty years"], ["twelve years"]),
    q("c", "18", "How many Lamanites did Zeniff's people slay in one day and a night?", "Three thousand and forty-three", ["Two thousand and forty-three", "Five thousand and forty-seven"], ["three thousand and forty"]),
  ),
  ch("mosiah", 10,
    q("a", "3", "For how many years did Zeniff's people possess the land of their fathers?", "Twenty-two years", ["Thirty-two years", "Forty-two years"], ["twenty"]),
    q("b", "5", "What did Zeniff have the women of his people do?", "Spin, toil, and make fine linen", ["Cook and teach the children", "Forge weapons and make shields"], ["spin", "toil"]),
    q("c", "9", "Where did Zeniff have the women and children of his people hidden?", "In the wilderness", ["In the great tower", "Behind the city walls"], ["wilderness"]),
  ),
  ch("mosiah", 11,
    q("a", "3", "What share of all they possessed did King Noah demand as a tax?", "One fifth", ["One tenth", "One third"], ["fifth"]),
    q("b", "20", "What was the name of the prophet who began to prophesy among King Noah's people?", "Abinadi", ["Amulon", "Gideon"], ["Abinadi"]),
    q("c", "12", "What did King Noah build near the temple?", "A very high tower", ["A large golden altar", "A wide city wall"], ["high tower"]),
  ),
  ch("mosiah", 12,
    q("a", "3", "What does Abinadi compare the life of King Noah to?", "A garment in a hot furnace", ["A flower in an open field", "A stone in a flowing river"], ["garment in a hot furnace"]),
    q("b", "17", "What did King Noah do with Abinadi?", "He had him cast into prison", ["He had him put to death at once", "He had him banished from the land"], ["prison"]),
    q("c", "28", "What did the priests of King Noah say they taught?", "The law of Moses", ["The law of Noah", "The law of the king"], ["law of Moses"]),
  ),
  ch("mosiah", 13,
    q("a", "16", "Which day must one remember and keep holy, according to the commandment?", "The sabbath day", ["The first day", "The harvest day"], ["sabbath day"]),
    q("b", "28", "What does Abinadi say about salvation and the law of Moses?", "Salvation does not come by the law alone", ["Salvation comes only through the law", "Salvation comes through sacrifices alone"], ["law alone"]),
    q("c", "24", "What may one not covet, according to the commandment?", "A neighbor's house", ["The king's field", "The priests' gold"], ["neighbor's house"]),
  ),
  ch("mosiah", 14,
    q("a", "6", "To what does Isaiah liken all of us who have gone astray?", "To sheep", ["To goats", "To oxen"], ["sheep"]),
    q("b", "3", "How is He described in verse 3?", "A man of sorrows", ["A man of war", "A man of wisdom"], ["man of sorrows"]),
    q("c", "7", "What is He compared to when He was oppressed?", "A lamb to the slaughter", ["A lion in the net", "A bull for the offering"], ["lamb to the slaughter"]),
  ),
  ch("mosiah", 15,
    q("a", "14", "What message did the holy prophets bring to Zion, according to Abinadi?", "Thy God reigneth", ["Thy king cometh", "Thy people are saved"], ["God reigneth"]),
    q("b", "25", "What do little children have, according to Abinadi?", "Eternal life as well", ["Their own kingdom", "A heavy punishment"], ["eternal life"]),
    q("c", "21", "What is the resurrection of which Abinadi speaks in verse 21 called?", "The first resurrection", ["The last resurrection", "The third resurrection"], ["first resurrection"]),
  ),
  ch("mosiah", 16,
    q("a", "8", "What is swallowed up in Christ, according to Abinadi?", "The sting of death", ["The power of the devil", "The law of Moses"], ["sting of death"]),
    q("b", "9", "How does Abinadi describe Christ in relation to the world?", "The light and the life of the world", ["The judge and the shepherd of the world", "The king and the guardian of the world"], ["light and the life of the world"]),
    q("c", "14", "Of what is the law of Moses a shadow, according to Abinadi?", "Of things to come", ["Of the former prophets", "Of the first kings"], ["to come"]),
  ),
  ch("mosiah", 17,
    q("a", "2", "What was the name of the young man among the priests who believed Abinadi's words?", "Alma", ["Limhi", "Helam"], ["Alma"]),
    q("b", "20", "How did Abinadi die?", "He died by fire", ["He died by the sword", "He died by stoning"], ["by fire"]),
    q("c", "6", "After how many days did the king have Abinadi brought before him again?", "After three days", ["After seven days", "After two days"], ["three days"]),
  ),
  ch("mosiah", 18,
    q("a", "5", "What was the name of the place with a fountain of pure water where Alma went?", "Mormon", ["Helam", "Shilom"], ["Mormon"]),
    q("b", "16", "About how many souls did Alma baptize in the waters of Mormon?", "About two hundred and four", ["About four hundred and four", "About one hundred and four"], ["two hundred and four"]),
    q("c", "18", "How many priests did Alma ordain in relation to the number of people?", "One priest to every fifty", ["One priest to every hundred", "One priest to every twenty"], ["priest to every fifty"]),
  ),
  ch("mosiah", 19,
    q("a", "4", "Who drew his sword against King Noah?", "Gideon", ["Limhi", "Helam"], ["Gideon"]),
    q("b", "20", "What did the men do with King Noah after he commanded them not to return?", "They made him suffer death by fire", ["They set him free in the wilderness", "They took him back to his palace"], ["by fire"]),
    q("c", "26", "What did Limhi swear to the king of the Lamanites?", "That his people would pay tribute to him", ["That his people would leave the land", "That his people would worship him as a god"], ["pay tribute"]),
  ),
  ch("mosiah", 20,
    q("a", "5", "How many daughters of the Lamanites did the priests of Noah carry off into the wilderness?", "Twenty-four", ["Twenty-six", "Twenty-one"], ["twenty"]),
    q("b", "10", "To what is the fighting of Limhi's people compared?", "To lions fighting for their prey", ["To wolves around their flock", "To bears protecting their young"], ["lions"]),
    q("c", "17", "Who was the king's captain who begged the king not to search Limhi's people?", "Gideon", ["Helam", "Amulon"], ["Gideon"]),
  ),
  ch("mosiah", 21,
    q("a", "26", "With what was the land covered that Limhi's men found?", "With dry bones", ["With thick dust", "With golden idols"], ["dry bones"]),
    q("b", "17", "What did King Limhi command every man to do because of the many widows?", "Contribute to the support of the widows", ["Give a tenth of his harvest to the king", "Marry a widow in his own family"], ["support of the widows"]),
    q("c", "33", "Why could Limhi and his people not be baptized?", "No one had authority from God", ["There was no water in the land", "The king had forbidden it"], ["authority from God"]),
  ),
  ch("mosiah", 22,
    q("a", "6", "By what way did Gideon propose that they escape?", "Through the back wall of the city", ["Through the great gate of the city", "Over the river by boat at night"], ["back wall"]),
    q("b", "10", "What did Limhi send to the Lamanites as tribute and as a present?", "Wine", ["Grain", "Meat"], ["wine"]),
    q("c", "13", "In which land did Limhi's people arrive after many days in the wilderness?", "In the land of Zarahemla", ["In the land of Helam", "In the land of Shilom"], ["Zarahemla"]),
  ),
  ch("mosiah", 23,
    q("a", "3", "How many days' journey did Alma's people flee into the wilderness?", "Eight days' journey", ["Four days' journey", "Twelve days' journey"], ["eight days"]),
    q("b", "19", "What name did Alma's people give the land where they settled?", "Helam", ["Mormon", "Lehi"], ["Helam"]),
    q("c", "6-7", "Whom did the people of Alma want as their king?", "Alma, but he refused", ["Gideon, but he refused", "Helam, but he refused"], ["Alma"]),
  ),
  ch("mosiah", 24,
    q("a", "20", "What did Alma and his people call the valley where they pitched their tents?", "The valley of Alma", ["The valley of Helam", "The valley of Amulon"], ["Alma"]),
    q("b", "19", "What did the Lord do at the time of their escape from the Lamanites?", "He caused a deep sleep to fall on the Lamanites", ["He caused a great storm to arise upon the Lamanites", "He caused the weapons of the Lamanites to vanish"], ["deep sleep"]),
    q("c", "25", "After how many days in the wilderness did Alma's people arrive in Zarahemla?", "After twelve days", ["After six days", "After forty days"], ["twelve days"]),
  ),
  ch("mosiah", 25,
    q("a", "23", "How many churches were there in the land of Zarahemla?", "Seven churches", ["Three churches", "Twelve churches"], ["seven churches"]),
    q("b", "17", "Who was desirous to be baptized after Alma had taught the people?", "King Limhi", ["King Mosiah", "King Noah"], ["Limhi"]),
    q("c", "2", "Of whom were the people of Zarahemla descendants?", "Of Mulek", ["Of Nephi", "Of Laman"], ["Mulek"]),
  ),
  ch("mosiah", 26,
    q("a", "8", "Who had received authority over the church from King Mosiah?", "Alma", ["Limhi", "Helam"], ["Alma"]),
    q("b", "22", "Unto what shall one be baptized, according to the Lord?", "Unto repentance", ["Unto worldly gain", "Unto freedom"], ["unto repentance"]),
    q("c", "30", "How often does the Lord forgive his people who repent?", "As often as they repent", ["At most seven times a year", "Only for the first offense"], ["as often as"]),
  ),
  ch("mosiah", 27,
    q("a", "11", "Who appeared to Alma the younger and the sons of Mosiah?", "The angel of the Lord", ["The prophet Abinadi", "The king of Zarahemla"], ["angel of the Lord"]),
    q("b", "23", "How long did the priests and people fast and pray before Alma's limbs received strength?", "Two days and two nights", ["Three days and three nights", "Seven days and seven nights"], ["two days and two nights"]),
    q("c", "34", "What were the names of the four sons of Mosiah?", "Ammon, Aaron, Omner, and Himni", ["Ammon, Aaron, Helam, and Gideon", "Ammon, Omner, Himni, and Limhi"], ["Ammon", "Aaron", "Omner", "Himni"]),
  ),
  ch("mosiah", 28,
    q("a", "5", "Where did the sons of Mosiah want to go to preach?", "To the land of Nephi", ["To the land of Helam", "To the land of Shilom"], ["land of Nephi"]),
    q("b", "13", "By what means did Mosiah translate the records?", "With two stones fastened in a bow", ["With a pair of silver spectacles", "With a roll of fine parchment"], ["two stones"]),
    q("c", "20", "To whom did Mosiah confer the plates of brass and the other objects?", "To Alma", ["To Ammon", "To Aaron"], ["Alma"]),
  ),
  ch("mosiah", 29,
    q("a", "2", "Whom did the people first want as their king?", "Aaron", ["Ammon", "Himni"], ["Aaron"]),
    q("b", "42", "Who was appointed the first chief judge?", "Alma", ["Aaron", "Limhi"], ["Alma"]),
    q("c", "46", "In which year of his reign did Mosiah die?", "In the thirty-third year", ["In the twenty-third year", "In the forty-third year"], ["thirty"]),
  ),
  // ===== EINDE =====
];
