import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Mosiah. English edition - generated from Dutch master.
export const mosiah: GeneesChapterSeed[] = [
  ch("mosiah", 1,
    q("a", "2", "Hoe heetten de drie zonen van koning Benjamin?", "Mosiah, Helorum en Helaman", ["Mosiah, Benjamin en Helaman", "Mosiah, Helorum en Amaleki"], ["Mosiah", "Helorum", "Helaman"]),
    q("b", "16", "Welk voorwerp kreeg Mosiah, naast de platen, ook in zijn zorg?", "Het zwaard van Laban", ["De kroon van Zedekia", "De ark van het verbond"], ["zwaard van Laban"]),
    q("c", "12", "Wat zal er volgens koning Benjamin nooit worden uitgewist, behalve door overtreding?", "De naam die hij hun geeft", ["De tempel die zij bouwen", "De wet die zij ontvangen"], ["naam"]),
  ),
  ch("mosiah", 2,
    q("a", "7", "Wat liet koning Benjamin bouwen zodat het volk zijn woorden kon horen?", "Een toren", ["Een brug", "Een altaar"], ["toren"]),
    q("b", "17", "Wat zijn de mensen volgens Benjamin wanneer zij hun medemensen dienen?", "Louter in dienst van uw God", ["In dienst van de koning alleen", "In dienst van uzelf"], ["dienst van uw God"]),
    q("c", "14", "Waarmee werkte koning Benjamin om zijn volk te kunnen dienen?", "Met zijn eigen handen", ["Met de hulp van slaven", "Met zijn knechten en soldaten"], ["eigen handen"]),
  ),
  ch("mosiah", 3,
    q("a", "8", "Welke naam en welke moeder noemt de engel voor de Heer die zal komen?", "Jezus Christus, en zijn moeder Maria", ["Immanuel, en zijn moeder Sara", "Johannes, en zijn moeder Elisabet"], ["Jezus Christus", "Maria"]),
    q("b", "10", "Wanneer zal Hij volgens de engel uit de doden opstaan?", "Op de derde dag", ["Op de zevende dag", "Na veertig dagen"], ["derde dag"]),
    q("c", "19", "Wat is de natuurlijke mens volgens vers 19, tenzij hij zich overgeeft aan de Heilige Geest?", "Een vijand van God", ["Een vriend van de wereld", "Een dienaar van de wet"], ["vijand van God"]),
  ),
  ch("mosiah", 4,
    q("a", "1", "Hoe lagen de mensen toen koning Benjamin zijn blik over de menigte wierp?", "Ze waren ter aarde gevallen", ["Ze waren op de vlucht geslagen", "Ze waren in slaap gevallen"], ["ter aarde"]),
    q("b", "19", "Hoe noemt Benjamin ons allen, in onze afhankelijkheid van God?", "Bedelaars", ["Rijken", "Heersers"], ["bedelaars"]),
    q("c", "14", "Wat zult u volgens Benjamin niet dulden dat uw kinderen lijden?", "Honger lijden of naakt gaan", ["Straf lijden of ziek worden", "Dorst lijden of kou lijden"], ["honger lijden", "naakt"]),
  ),
  ch("mosiah", 5,
    q("a", "7", "Hoe zullen de mensen volgens Benjamin wegens het verbond worden genoemd?", "De kinderen van Christus", ["De dienaren van de koning", "De kinderen van Benjamin"], ["kinderen van Christus"]),
    q("b", "5", "Wat waren de mensen bereid te doen in het verbond met God?", "Gods wil te doen en zijn geboden te houden", ["Al hun bezittingen aan de koning te geven", "Het land te verlaten en elders te wonen"], ["wil", "geboden"]),
    q("c", "14", "Welk dier van zijn naaste houdt volgens Benjamin niemand voor zichzelf?", "Een ezel", ["Een rund", "Een paard"], ["ezel"]),
  ),
  ch("mosiah", 6,
    q("a", "4", "In welk levensjaar begon Mosiah te regeren?", "Zijn dertigste", ["Zijn twintigste", "Zijn veertigste"], ["dertigste"]),
    q("b", "5", "Hoeveel jaar leefde koning Benjamin nog nadat Mosiah koning was geworden?", "Nog drie jaar", ["Nog zeven jaar", "Nog tien jaar"], ["drie jaar"]),
    q("c", "7", "Hoe zorgde koning Mosiah ervoor zijn volk niet tot last te zijn?", "Hij bebouwde zelf de aardbodem", ["Hij liet slaven zijn land bewerken", "Hij vroeg het volk om geschenken"], ["bebouwde"]),
  ),
  ch("mosiah", 7,
    q("a", "3", "Wie was de leider van de zestien sterke mannen die naar het land Lehi-Nephi trokken?", "Ammon", ["Limhi", "Zeniff"], ["Ammon"]),
    q("b", "4", "Hoeveel dagen dwaalden zij in de wildernis rond?", "Veertig dagen", ["Veertien dagen", "Zeventig dagen"], ["veertig dagen"]),
    q("c", "9", "Wie was de koning van het volk in het land Nephi die Ammon ontmoette?", "Limhi, de zoon van Noach", ["Laman, de zoon van Zeniff", "Noach, de zoon van Limhi"], ["Limhi", "Noach"]),
  ),
  ch("mosiah", 8,
    q("a", "9", "Waarvan waren de vierentwintig platen die Limhi's mannen meebrachten gemaakt?", "Van zuiver goud", ["Van zuiver koper", "Van zuiver zilver"], ["zuiver goud"]),
    q("b", "15", "Wat is een ziener volgens koning Limhi?", "Groter dan een profeet", ["Gelijk aan een priester", "Kleiner dan een koning"], ["dan een profeet"]),
    q("c", "7", "Hoeveel man liet Limhi de wildernis intrekken om het land Zarahemla te vinden?", "Drieënveertig man", ["Drieëndertig man", "Drieënzestig man"], ["drieënveertig"]),
  ),
  ch("mosiah", 9,
    q("a", "1", "Wie is de schrijver van Mosiah 9?", "Zeniff", ["Ammon", "Limhi"], ["Zeniff"]),
    q("b", "11", "Hoeveel jaar had Zeniffs volk in het land gewoond toen koning Laman ongerust werd?", "Twaalf jaar", ["Zes jaar", "Twintig jaar"], ["twaalf jaar"]),
    q("c", "18", "Hoeveel Lamanieten doodde Zeniffs volk in één dag en één nacht?", "Drieduizend drieënveertig", ["Tweeduizend drieënveertig", "Vijfduizend zevenenveertig"], ["drieduizend drieënveertig"]),
  ),
  ch("mosiah", 10,
    q("a", "3", "Hoeveel jaar bezat Zeniffs volk het land van hun vaderen?", "Tweeëntwintig jaar", ["Tweeëndertig jaar", "Tweeënveertig jaar"], ["tweeëntwintig jaar"]),
    q("b", "5", "Wat liet Zeniff de vrouwen van zijn volk doen?", "Spinnen, zwoegen en weefsel maken", ["Koken en de kinderen onderwijzen", "Wapens smeden en schilden maken"], ["spinnen"]),
    q("c", "9", "Waar liet Zeniff de vrouwen en kinderen van zijn volk verbergen?", "In de wildernis", ["In de grote toren", "Achter de stadsmuren"], ["wildernis"]),
  ),
  ch("mosiah", 11,
    q("a", "3", "Welk deel van alles wat zij bezaten eiste koning Noach als belasting?", "Een vijfde deel", ["Een tiende deel", "Een derde deel"], ["vijfde deel"]),
    q("b", "20", "Hoe heette de profeet die onder het volk van Noach begon te profeteren?", "Abinadi", ["Amulon", "Gideon"], ["Abinadi"]),
    q("c", "12", "Wat bouwde koning Noach bij de tempel?", "Een zeer hoge toren", ["Een groot altaar van goud", "Een brede stadsmuur"], ["hoge toren"]),
  ),
  ch("mosiah", 12,
    q("a", "3", "Waarmee vergelijkt Abinadi het leven van koning Noach?", "Een kleed in een hete oven", ["Een bloem op het veld", "Een steen in de rivier"], ["kleed in een hete oven"]),
    q("b", "17", "Wat deed koning Noach met Abinadi?", "Hij liet hem in de gevangenis werpen", ["Hij liet hem direct ter dood brengen", "Hij liet hem het land uit verbannen"], ["gevangenis"]),
    q("c", "28", "Wat zeiden de priesters van koning Noach dat zij leerden?", "De wet van Mozes", ["De wet van Noach", "De wet van de koning"], ["wet van Mozes"]),
  ),
  ch("mosiah", 13,
    q("a", "16", "Welke dag moet men volgens het gebod gedenken en heiligen?", "De sabbatdag", ["De eerste dag", "De dag van de oogst"], ["sabbatdag"]),
    q("b", "28", "Wat zegt Abinadi over het heil en de wet van Mozes?", "Het heil komt niet door de wet alleen", ["Het heil komt alleen door de wet", "Het heil komt door de offers alleen"], ["door de wet alleen"]),
    q("c", "24", "Wat mag men volgens het gebod niet begeren?", "Het huis van uw naaste", ["De akker van de koning", "Het goud van de priesters"], ["huis van uw naaste"]),
  ),
  ch("mosiah", 14,
    q("a", "6", "Waarmee vergelijkt Jesaja ons allen die zijn afgedwaald?", "Met schapen", ["Met geiten", "Met ossen"], ["schapen"]),
    q("b", "3", "Hoe wordt Hij in vers 3 genoemd?", "Een man van smarten", ["Een man van oorlog", "Een man van wijsheid"], ["man van smarten"]),
    q("c", "7", "Waarmee wordt Hij vergeleken toen Hij werd verdrukt?", "Met een lam ter slachting", ["Met een leeuw in het net", "Met een stier ter offerande"], ["lam ter slachting"]),
  ),
  ch("mosiah", 15,
    q("a", "14", "Welke boodschap hebben de heilige profeten volgens Abinadi tot Zion gebracht?", "Uw God regeert", ["Uw koning komt", "Uw volk is gered"], ["Uw God regeert"]),
    q("b", "25", "Wat hebben kleine kinderen volgens Abinadi?", "Het eeuwige leven", ["Een eigen koninkrijk", "Een zware straf"], ["eeuwige leven"]),
    q("c", "21", "Hoe heet de opstanding waarover Abinadi in vers 21 spreekt?", "De eerste opstanding", ["De laatste opstanding", "De derde opstanding"], ["eerste opstanding"]),
  ),
  ch("mosiah", 16,
    q("a", "8", "Wat is in Christus verzwolgen volgens Abinadi?", "De prikkel van de dood", ["De macht van de duivel", "De wet van Mozes"], ["prikkel van de dood"]),
    q("b", "9", "Wat is Christus volgens Abinadi voor de wereld?", "Het licht en het leven van de wereld", ["De rechter en de herder van de wereld", "De koning en de hoeder van de wereld"], ["licht en het leven van de wereld"]),
    q("c", "14", "Waarvan is de wet van Mozes volgens Abinadi een afschaduwing?", "Van de toekomstige dingen", ["Van de vroegere profeten", "Van de eerste koningen"], ["toekomstige dingen"]),
  ),
  ch("mosiah", 17,
    q("a", "2", "Hoe heette de jonge man onder de priesters die de woorden van Abinadi geloofde?", "Alma", ["Limhi", "Helam"], ["Alma"]),
    q("b", "20", "Hoe stierf Abinadi?", "Door de vuurdood", ["Door het zwaard", "Door steniging"], ["vuurdood"]),
    q("c", "6", "Na hoeveel dagen liet de koning Abinadi wederom voor zich brengen?", "Na drie dagen", ["Na zeven dagen", "Na twee dagen"], ["drie dagen"]),
  ),
  ch("mosiah", 18,
    q("a", "5", "Hoe heette de plaats met een bron van zuiver water waar Alma zich bevond?", "Mormon", ["Helam", "Shilom"], ["Mormon"]),
    q("b", "16", "Hoeveel mensen doopte Alma bij de wateren van Mormon ongeveer?", "Ongeveer tweehonderdvier zielen", ["Ongeveer vierhonderdvier zielen", "Ongeveer honderdvier zielen"], ["tweehonderdvier"]),
    q("c", "18", "Hoeveel priesters ordende Alma ten opzichte van het aantal mensen?", "Eén priester voor iedere vijftig", ["Eén priester voor iedere honderd", "Eén priester voor iedere twintig"], ["één priester voor iedere vijftig"]),
  ),
  ch("mosiah", 19,
    q("a", "4", "Wie trok zijn zwaard tegen koning Noach?", "Gideon", ["Limhi", "Helam"], ["Gideon"]),
    q("b", "20", "Wat deden de mannen met koning Noach nadat hij hun gebood niet terug te keren?", "Ze lieten hem lijden tot de vuurdood", ["Ze lieten hem vrij in de wildernis", "Ze brachten hem terug naar zijn paleis"], ["vuurdood"]),
    q("c", "26", "Wat zwoer Limhi aan de koning van de Lamanieten?", "Dat zijn volk hem schatting zou betalen", ["Dat zijn volk het land zou verlaten", "Dat zijn volk hem als god zou aanbidden"], ["schatting"]),
  ),
  ch("mosiah", 20,
    q("a", "5", "Hoeveel dochters van de Lamanieten werden door de priesters van Noach ontvoerd?", "Vierentwintig", ["Zesentwintig", "Eenentwintig"], ["vierentwintig"]),
    q("b", "10", "Waarmee wordt de strijd van Limhi's volk vergeleken?", "Met leeuwen om hun prooi", ["Met wolven om hun kudde", "Met beren om hun jongen"], ["leeuwen"]),
    q("c", "17", "Wie was de bevelhebber van de koning die Limhi smeekte af te zien van een onderzoek?", "Gideon", ["Helam", "Amulon"], ["Gideon"]),
  ),
  ch("mosiah", 21,
    q("a", "26", "Waarmee was het land bedekt dat de mannen van Limhi vonden?", "Dorre beenderen", ["Dikke stofwolken", "Gouden standbeelden"], ["dorre beenderen"]),
    q("b", "17", "Wat gebood koning Limhi dat iedere man moest doen vanwege de vele weduwen?", "Bijdragen aan het onderhoud van de weduwen", ["Een tiende van zijn oogst aan de koning geven", "Hertrouwen met een weduwe in zijn familie"], ["onderhoud van de weduwen"]),
    q("c", "33", "Waarom konden Limhi en zijn volk zich niet laten dopen?", "Er was niemand met gezag van God", ["Er was geen water in het land", "De koning had het verboden"], ["gezag van God"]),
  ),
  ch("mosiah", 22,
    q("a", "6", "Langs welke weg stelde Gideon voor te ontsnappen?", "Door de achtermuur van de stad", ["Door de grote stadspoort", "Over de rivier met schepen"], ["achtermuur"]),
    q("b", "10", "Wat stuurde Limhi naar de Lamanieten als schatting en als geschenk?", "Wijn", ["Graan", "Vlees"], ["wijn"]),
    q("c", "13", "In welk land kwam het volk van Limhi na vele dagen in de wildernis aan?", "In het land Zarahemla", ["In het land Helam", "In het land Shilom"], ["Zarahemla"]),
  ),
  ch("mosiah", 23,
    q("a", "3", "Hoeveel dagreizen vluchtte het volk van Alma de wildernis in?", "Acht dagreizen", ["Vier dagreizen", "Twaalf dagreizen"], ["acht dagreizen"]),
    q("b", "19", "Welke naam gaf het volk van Alma aan het land waar het zich vestigde?", "Helam", ["Mormon", "Lehi"], ["Helam"]),
    q("c", "6-7", "Wie wilde het volk van Alma als koning hebben?", "Alma, maar hij weigerde", ["Gideon, maar hij weigerde", "Helam, maar hij weigerde"], ["Alma"]),
  ),
  ch("mosiah", 24,
    q("a", "20", "Hoe noemden Alma en zijn volk het dal waarin zij hun tenten opsloegen?", "Het dal Alma", ["Het dal Helam", "Het dal Amulon"], ["dal Alma"]),
    q("b", "19", "Wat deed de Heer ten tijde van hun ontsnapping met de Lamanieten?", "Hij liet een zware slaap op hen vallen", ["Hij liet een grote storm opsteken", "Hij liet hun wapens verdwijnen"], ["zware slaap"]),
    q("c", "25", "Na hoeveel dagen in de wildernis kwam het volk van Alma in Zarahemla aan?", "Na twaalf dagen", ["Na zes dagen", "Na veertig dagen"], ["twaalf dagen"]),
  ),
  ch("mosiah", 25,
    q("a", "23", "Hoeveel kerken waren er in het land Zarahemla?", "Zeven kerken", ["Drie kerken", "Twaalf kerken"], ["zeven kerken"]),
    q("b", "17", "Wie verlangde zich te laten dopen nadat Alma het volk had geleerd?", "Koning Limhi", ["Koning Mosiah", "Koning Noach"], ["Limhi"]),
    q("c", "2", "Van wie was het volk van Zarahemla een afstammeling?", "Van Mulek", ["Van Nephi", "Van Laman"], ["Mulek"]),
  ),
  ch("mosiah", 26,
    q("a", "8", "Wie had van koning Mosiah het gezag over de kerk gekregen?", "Alma", ["Limhi", "Helam"], ["Alma"]),
    q("b", "22", "Tot wat wordt iemand die zich laat dopen volgens de Heer gedoopt?", "Tot bekering", ["Tot rijkdom", "Tot vrijheid"], ["tot bekering"]),
    q("c", "30", "Hoe vaak vergeeft de Heer de overtredingen van zijn volk dat zich bekeert?", "Zo vaak als het zich bekeert", ["Hoogstens zeven keer per jaar", "Alleen bij de eerste overtreding"], ["zo vaak"]),
  ),
  ch("mosiah", 27,
    q("a", "11", "Wie verscheen er aan Alma de jongere en de zonen van Mosiah?", "De engel van de Heer", ["De profeet Abinadi", "De koning van Zarahemla"], ["engel van de Heer"]),
    q("b", "23", "Hoe lang vastten en baden de priesters en het volk voordat Alma's ledematen hun kracht ontvingen?", "Twee dagen en twee nachten", ["Drie dagen en drie nachten", "Zeven dagen en zeven nachten"], ["twee dagen en twee nachten"]),
    q("c", "34", "Wie waren de vier zonen van Mosiah?", "Ammon, Aäron, Omner en Himni", ["Ammon, Aäron, Helam en Gideon", "Ammon, Omner, Himni en Limhi"], ["Ammon", "Aäron", "Omner", "Himni"]),
  ),
  ch("mosiah", 28,
    q("a", "5", "Waarheen wilden de zonen van Mosiah gaan om te prediken?", "Naar het land Nephi", ["Naar het land Helam", "Naar het land Shilom"], ["land Nephi"]),
    q("b", "13", "Waarmee had Mosiah de kronieken van het vernietigde volk vertaald?", "Met twee stenen in een boog", ["Met een gouden bril van zilver", "Met een rol van fijn perkament"], ["twee stenen"]),
    q("c", "20", "Aan wie droeg Mosiah de platen van koper en de voorwerpen over?", "Aan Alma", ["Aan Ammon", "Aan Aäron"], ["Alma"]),
  ),
  ch("mosiah", 29,
    q("a", "2", "Wie wilde het volk eerst als koning hebben?", "Aäron", ["Ammon", "Himni"], ["Aäron"]),
    q("b", "42", "Wie werd als eerste opperrechter aangesteld?", "Alma", ["Aäron", "Limhi"], ["Alma"]),
    q("c", "46", "In welk jaar van zijn regering stierf Mosiah?", "In het drieëndertigste jaar", ["In het drieëntwintigste jaar", "In het drieënveertigste jaar"], ["drieëndertigste"]),
  ),
  // ===== EINDE =====
];
