import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 4 Nephi, Mormon, Ether and Moroni (English edition). Each fact is tied to the verses in `verses`; `npm run genees:check` verifies that.
export const slot: GeneesChapterSeed[] = [
  ch("4-ne", 1,
    q("a", "3", "What did the people have among them after their conversion?", "All things common among them", ["All things as private property", "All things under the judges"], ["things common"]),
    q("b", "17", "What had the people become, according to verse 17?", "One, the children of Christ", ["Divided into many social classes", "Separated into two rival peoples"], ["children of Christ"]),
    q("c", "48", "Who hid up the sacred records unto the Lord?", "Ammaron", ["Mormon", "Moroni"], ["Ammaron"]),
  ),
  ch("morm", 1,
    q("a", "2", "About how old was Mormon when Ammaron came to him?", "About ten years old", ["About fourteen years old", "About seven years old"], ["ten years"]),
    q("b", "3", "When was Mormon to remember what he had observed, according to Ammaron?", "When he was about twenty-four", ["When he was about thirty", "When he was about eighteen"], ["about twenty"]),
    q("c", "15", "How old was Mormon when the Lord visited him?", "Fifteen years old", ["Twelve years old", "Twenty years old"], ["fifteen years"]),
  ),
  ch("morm", 2,
    q("a", "2", "In which year of his life did Mormon go forth at the head of an army?", "In his sixteenth year", ["In his eighteenth year", "In his twentieth year"], ["sixteenth"]),
    q("b", "9", "What was the name of the king of the Lamanites who came against the Nephites with a great army?", "Aaron", ["Lamoni", "Ammoron"], ["Aaron"]),
    q("c", "29", "What did the Lamanites give the Nephites in the treaty?", "The land northward", ["The land southward", "The land of Zarahemla"], ["land northward"]),
  ),
  ch("morm", 3,
    q("a", "11", "What did Mormon refuse to be from that time forth because of their wickedness?", "Their commander and leader", ["Their king and judge", "Their priest and teacher"], ["commander"]),
    q("b", "13", "How often had Mormon delivered his people out of the hands of their enemies?", "He delivered them thrice", ["He delivered them twice", "He delivered them seven times"], ["thrice"]),
    q("c", "17", "To whom does Mormon write, according to verse 17?", "To the Gentiles and the house of Israel", ["Only to the Nephites of his own time", "To the king and his army captains"], ["Gentiles", "house of Israel"]),
  ),
  ch("morm", 4,
    q("a", "2", "To which land were the armies of the Nephites driven back?", "The land of Desolation", ["The land of Jershon", "The land of Zarahemla"], ["land of Desolation"]),
    q("b", "5", "By whom are the wicked punished, according to Mormon?", "By the wicked", ["By the angels", "By the righteous"], ["by the wicked"]),
    q("c", "23", "To which hill did Mormon go when the Lamanites were about to overthrow the land?", "To the hill Shim", ["To the hill Manti", "To the hill Riplah"], ["hill Shim"]),
  ),
  ch("morm", 5,
    q("a", "17", "Whom did the Nephites once have as their shepherd?", "Christ for their shepherd", ["Moses for their shepherd", "Nephi for their shepherd"], ["Christ for their shepherd"]),
    q("b", "18", "To what are the people compared who are led about by Satan?", "To chaff driven before the wind", ["To a sheep straying from the flock", "To dust lying on the mountains"], ["chaff"]),
    q("c", "22", "What does Mormon ask the Gentiles?", "How they can stand before God's power", ["How they can preserve the land", "How they can increase their wealth"], ["stand before"]),
  ),
  ch("morm", 6,
    q("a", "4", "To which land did the Nephites march to gather themselves?", "The land of Cumorah", ["The land of Moroni", "The land of Joshua"], ["Cumorah"]),
    q("b", "11", "How many of Mormon's people remained after the battle?", "Twenty-four of us", ["Twenty-seven of us", "Twenty-one of us"], ["twenty"]),
    q("c", "3", "How did the king of the Lamanites respond to Mormon's request?", "He granted Mormon's request", ["He refused the request", "He had the letter burned"], ["grant"]),
  ),
  ch("morm", 7,
    q("a", "2", "Of which house is the remnant of the people, according to Mormon?", "The house of Israel", ["The house of Judah", "The house of David"], ["house of Israel"]),
    q("b", "4", "What must they lay down, according to Mormon?", "Their weapons of war", ["Their golden idols", "Their silver treasures"], ["weapons of war"]),
    q("c", "8", "In whose name must they be baptized, according to Mormon?", "In the name of Jesus", ["In the name of Mormon", "In the name of Nephi"], ["name of Jesus"]),
  ),
  ch("morm", 8,
    q("a", "1", "Who finishes the record of Mormon?", "Moroni", ["Nephi", "Helaman"], ["Moroni"]),
    q("b", "6", "How many years had passed since the coming of Christ?", "Four hundred years", ["Three hundred years", "Five hundred years"], ["four hundred years"]),
    q("c", "23", "Whose prophecies must one search, according to Moroni?", "Those of Isaiah", ["Those of Jeremiah", "Those of Moses"], ["Isaiah"]),
  ),
  ch("morm", 9,
    q("a", "9", "How is God, according to Mormon?", "The same yesterday, today, and forever", ["Variable, according to times and peoples", "Present only in the temple"], ["yesterday, today, and forever"]),
    q("b", "32", "What characters did Mormon and Moroni use for their record?", "Reformed Egyptian", ["Old Hebrew script", "Aramaic and Syriac"], ["reformed Egyptian"]),
    q("c", "21", "What does Moroni promise to whoever believes in Christ without doubting?", "Whatever he asks the Father in his name", ["An exemption from all trials", "A place in every kingdom of the earth"], ["the Father"]),
  ),
  ch("ether", 1,
    q("a", "2", "From how many plates does Moroni take his account of the ancient inhabitants who were destroyed?", "Twenty-four plates", ["Twelve golden plates", "Forty-eight plates"], ["four plates"]),
    q("b", "34-35", "What happened to the language of Jared and his brother at the great tower?", "It was not confounded", ["It was partly changed", "It was entirely replaced"], ["not confounded"]),
    q("c", "38,42", "What did the Lord promise about the land to which He would lead the brother of Jared?", "That it was choice above all the lands", ["That it was more fertile than Egypt", "That it was close to the tower"], ["choice above all the lands"]),
  ),
  ch("ether", 2,
    q("a", "3", "What does the word \"deseret\", which the Jaredites carried with them, mean?", "A honey bee", ["A field mouse", "A river fish"], ["honey bee"]),
    q("b", "14", "For how long did the Lord talk with the brother of Jared while chastening him?", "For three hours", ["For seven hours", "For two hours"], ["three hours"]),
    q("c", "17", "How tight were the boats of the Jaredites built?", "As tight as a dish", ["As tight as a barrel", "As tight as a jug"], ["dish"]),
  ),
  ch("ether", 3,
    q("a", "1", "How many small stones did the brother of Jared melt out of a rock on mount Shelem?", "Sixteen stones", ["Twelve stones", "Eighteen stones"], ["sixteen"]),
    q("b", "4-6", "How did the Lord make the stones shine when the brother of Jared asked him?", "He touched them with his finger", ["He breathed on them with his breath", "He let a bolt of fire fall on them"], ["finger"]),
    q("c", "21-22", "What was the brother of Jared to do with the things he had seen and heard?", "Write them and seal them up", ["Tell them to the people at once", "Pass them on to his own sons"], ["write them", "seal them up"]),
  ),
  ch("ether", 4,
    q("a", "1", "When were the things the brother of Jared wrote allowed to come to the children of men?", "After he was lifted up upon the cross", ["After the Nephites were destroyed", "After he ascended into heaven"], ["lifted up upon the cross"]),
    q("b", "3,5", "What did the Lord command Moroni to do with the records of the brother of Jared?", "To hide them up again in the earth", ["To give them to the Lamanites", "To burn them before they were found"], ["hide them up again in the earth"]),
    q("c", "6-7", "When would the Lord reveal to the Gentiles what the brother of Jared saw?", "When they repent and exercise faith", ["When they have ended their wars", "When they find the plates themselves"], ["repent", "exercise faith"]),
  ),
  ch("ether", 5,
    q("a", "3", "To how many witnesses would the plates be shown by the power of God?", "To three witnesses", ["To twelve witnesses", "To seven witnesses"], ["three"]),
    q("b", "1", "What was not allowed to be done with the things Moroni had sealed up?", "No one may translate them", ["No one may move them", "No one may look at them"], ["translate"]),
    q("c", "5", "What happens to those who repent and come to the Father in the name of Jesus?", "They will be received into the kingdom of God", ["They will receive power to open the sealed plates", "They will receive the gift of translating the plates"], ["kingdom of God"]),
  ),
  ch("ether", 6,
    q("a", "11", "How many days were the Jaredites driven forth upon the water?", "Three hundred and forty-four days", ["Three hundred and sixty-five days", "One hundred and forty-two days"], ["three hundred and forty"]),
    q("b", "9", "What did the brother of Jared do all day long while they were driven on the waters?", "He sang praises to the Lord", ["He kept watch over the stones", "He read aloud from the record"], ["praises"]),
    q("c", "27", "Which of the sons of Jared was anointed king over the people?", "Orihah, a son of Jared", ["Gilgah, a son of Jared", "Jacom, a son of Jared"], ["Orihah"]),
  ),
  ch("ether", 7,
    q("a", "9", "What did Shule make out of the hill Ephraim for the men he had drawn away with him?", "Swords of steel", ["Brass arrowheads", "Copper shields"], ["swords", "steel"]),
    q("b", "4", "How old was Corihor when he rebelled against his father Kib?", "Thirty-two years old", ["Twenty-one years old", "Forty-five years old"], ["years old"]),
    q("c", "24-25", "What did King Shule do for the prophets who were mocked by the people?", "He gave them power to go wherever they wished", ["He gave them soldiers to protect them everywhere", "He let them live in a city under his protection"], ["power"]),
  ),
  ch("ether", 8,
    q("a", "10-11", "What did the daughter of Jared do to please Akish, the son of Kimnor?", "She danced before him", ["She sang for him", "She poured wine for him"], ["danced"]),
    q("b", "12", "What did Jared demand of Akish in exchange for his daughter?", "The head of his father, the king", ["A large part of his gold and silver", "The keys of the largest city"], ["head", "king"]),
    q("c", "19", "What does Moroni say about the Lord and secret combinations?", "The Lord worketh not in secret combinations", ["The Lord uses them to test his people", "The Lord tolerates them only among his prophets"], ["not in secret combinations"]),
  ),
  ch("ether", 9,
    q("a", "3", "How was Omer warned that he must leave the land?", "The Lord warned him in a dream", ["An angel appeared to him on a mountain", "A prophet spoke to him at the gate"], ["in a dream"]),
    q("b", "22", "Whom did King Emer see, in whose day he rejoiced and gloried?", "The Son of Righteousness", ["An angel of the Lord", "A prophet from the north"], ["Son of Righteousness"]),
    q("c", "35", "What happened when the people had humbled themselves sufficiently before the Lord?", "The Lord sent rain upon the earth", ["The Lord sent manna from heaven", "The Lord removed the poisonous serpents"], ["rain"]),
  ),
  ch("ether", 10,
    q("a", "5", "With what did King Riplakish burden the people?", "With very heavy taxes", ["With forced military service", "With years of forced labor"], ["heavy taxes"]),
    q("b", "20", "Where did the Jaredites build a great city in the days of Lib?", "By the narrow neck of land", ["By the hill Shim in the north", "In the valley of Nimrod"], ["narrow neck of land"]),
    q("c", "23", "Which four metals did the Jaredites dig out of the earth in the days of Lib?", "Gold, silver, iron, and brass", ["Gold, silver, tin, and lead", "Silver, iron, tin, and bronze"], ["gold", "silver", "iron", "brass"]),
  ),
  ch("ether", 11,
    q("a", "5", "What did the brother of Shiblom do with the prophets who prophesied the destruction of the people?", "He had them put to death", ["He banished them to the wilderness", "He imprisoned them in Moron"], ["put to death"]),
    q("b", "2", "To whom did the prophets flee for protection when the people sought to destroy them?", "To King Com", ["To King Omer", "To King Shule"], ["Com"]),
    q("c", "20-21", "What would the Lord God do if the people did not repent in the days of Coriantor?", "Send another people to possess the land", ["Replace their king through a prophet", "Make the land vanish under the sea"], ["another people", "possess the land"]),
  ),
  ch("ether", 12,
    q("a", "6", "What is faith, according to Moroni?", "Things hoped for and not seen", ["Certain knowledge of what is already seen", "Belief only in what one can prove"], ["hoped for and not seen"]),
    q("b", "13", "Whose faith caused the prison to tumble to the earth, according to Moroni?", "That of Alma and Amulek", ["That of Abinadi and Limhi", "That of Ammon and his brethren"], ["Alma and Amulek"]),
    q("c", "30", "What happened when the brother of Jared said to the mountain Zerin, \"Remove\"?", "It was removed", ["It split in two", "It began to tremble"], ["removed"]),
  ),
  ch("ether", 13,
    q("a", "6", "For whom would the New Jerusalem be built upon this land?", "The remnant of the seed of Joseph", ["The remnant of the seed of Judah", "The last followers of the Jaredites"], ["remnant of the seed of Joseph"]),
    q("b", "13", "Where did Ether hide himself by day after the people cast him out?", "In the cavity of a rock", ["In a cave by the sea", "In a pit in the wilderness"], ["cavity of a rock"]),
    q("c", "31", "Where did Shared wound Coriantumr so that he did not go to battle for two years?", "In his thigh", ["In his arm", "In his shoulder"], ["thigh"]),
  ),
  ch("ether", 14,
    q("a", "10", "In what did Lib surpass the other men among the people?", "He was a man of great stature", ["He had the greatest riches", "He had the largest army ever"], ["great stature"]),
    q("b", "17", "Whose brother was Shiz, who overthrew many cities and burned them?", "The brother of Lib", ["The brother of Shared", "The brother of Com"], ["brother of Lib"]),
    q("c", "21-23", "By what were the people troubled day and night when the land was covered with the dead?", "By the scent of the dead", ["By poisonous serpents on the road", "By a shortage of water"], ["scent"]),
  ),
  ch("ether", 15,
    q("a", "2", "How many mighty men had already been slain when Coriantumr began to sorrow?", "Two millions", ["Four millions", "Half a million"], ["two millions"]),
    q("b", "11", "By which hill did the army of Coriantumr pitch its tents, where Mormon had hidden the sacred records?", "The hill Ramah", ["The hill Comnor", "The hill Shim"], ["Ramah"]),
    q("c", "30", "What did Coriantumr do when he had leaned upon his sword to rest a little?", "He smote off the head of Shiz", ["He surrendered to Shiz", "He blew a trumpet for his army"], ["head of Shiz"]),
  ),
  ch("moro", 1,
    q("a", "3", "Why did Moroni wander wherever he could?", "For the safety of his own life", ["To search for the lost plates", "To convert the Lamanites again"], ["safety of"]),
    q("b", "2", "Whom do the Lamanites put to death in their wars, according to Moroni?", "Every Nephite who will not deny the Christ", ["Every Nephite who will not bear arms", "Every Nephite who will not give up the plates"], ["will not deny the Christ"]),
    q("c", "1", "About which people had Moroni just finished abridging the account?", "The people of Jared", ["The people of Limhi", "The people of Ammon"], ["people of Jared"]),
  ),
  ch("moro", 2,
    q("a", "1", "To whom did Christ speak the words in Moroni 2?", "The twelve whom he had chosen", ["The seventy whom he had chosen", "The three whom he had chosen"], ["twelve"]),
    q("b", "2", "What could the disciples give by the laying on of hands?", "The gift of the Holy Ghost", ["The gift of speaking in tongues", "The gift of the spirit of prophecy"], ["Holy Ghost"]),
    q("c", "3", "Who did not hear the words of Christ when he spoke them at his first appearing?", "The multitude who stood by", ["The disciples who were there", "The teachers who were there"], ["multitude"]),
  ),
  ch("moro", 3,
    q("a", "1", "What were the disciples called who ordained priests and teachers?", "The elders of the church", ["The apostles of the church", "The overseers of the church"], ["elders of the church"]),
    q("b", "2", "What did the disciples do before they laid their hands on someone to ordain him?", "They prayed to the Father in the name of Christ", ["They read from the scriptures to the whole church", "They asked the church to give its voice"], ["Father", "name of Christ"]),
    q("c", "3", "What was someone ordained as a priest or teacher to preach?", "Repentance and remission of sins", ["The restoration of the church of Christ", "The covenant of Abraham to all nations"], ["repentance and remission of sins"]),
  ),
  ch("moro", 4,
    q("a", "3", "In remembrance of what did they eat the bread?", "Of the body of thy Son", ["Of the law of Moses", "Of the exodus from Egypt"], ["body of thy Son"]),
    q("b", "2", "What did the elder or priest and the church do before the bread was blessed?", "They did kneel down and pray to the Father", ["They stood up and sang a hymn", "They were silent and read a psalm aloud"], ["pray to the Father"]),
    q("c", "3", "What did they ask God to do with the bread?", "To bless and sanctify it", ["To carry it to the sick", "To divide it among all present"], ["bless and sanctify"]),
  ),
  ch("moro", 5,
    q("a", "2", "In remembrance of what did they drink the wine?", "Of the blood of thy Son", ["Of the covenant with Abraham", "Of the law of Moses"], ["blood of thy Son"]),
    q("b", "1", "What did they take in their hands when the wine was administered?", "The cup", ["The jug", "The bowl"], ["cup"]),
    q("c", "2", "How did they address God in the prayer over the wine?", "O God, the Eternal Father", ["O God, the Lord of Hosts", "O Lord, our Redeemer and King"], ["Eternal Father"]),
  ),
  ch("moro", 6,
    q("a", "2", "With what attitude were people to come to baptism?", "With a broken heart and a contrite spirit", ["With clean hands and a pure heart", "With great faith and a strong testimony"], ["broken heart", "contrite spirit"]),
    q("b", "5", "For what did the church members meet together often, besides speaking about the welfare of their souls?", "To fast and to pray", ["To work and to harvest", "To travel and to trade"], ["fast and to pray"]),
    q("c", "7", "How many witnesses of the church had to condemn someone before the elders?", "Three witnesses", ["Two witnesses", "Seven witnesses"], ["three witnesses"]),
  ),
  ch("moro", 7,
    q("a", "47", "What is charity, according to Mormon?", "The pure love of Christ itself", ["The highest form of sacrifice", "The love one receives from others"], ["pure love of Christ"]),
    q("b", "11", "What image does Mormon use to show that a wicked person can do nothing good?", "A bitter fountain with no good water", ["A dry well that gives no water", "A bad harvest that yields no grain"], ["bitter fountain"]),
    q("c", "16", "What is given to every man that he may know good from evil?", "The Spirit of Christ", ["The gift of prophecy", "The law of Moses"], ["Spirit of Christ"]),
  ),
  ch("moro", 8,
    q("a", "4-5", "Over what had disputations arisen, to Mormon's grief?", "The baptism of little children", ["The ordination of teachers", "The manner of laying on of hands"], ["baptism", "little children"]),
    q("b", "12", "Why do little children not need baptism, according to Mormon?", "They are alive in Christ", ["They are already baptized in spirit", "They are too young to suffer"], ["alive in Christ"]),
    q("c", "25", "What does Mormon call the first fruits of repentance?", "Baptism, which comes by faith", ["The remission of all sins", "The meekness of the heart"], ["baptism"]),
  ),
  ch("moro", 9,
    q("a", "2", "Which men had fallen by the sword in the battle with the Lamanites, according to Mormon?", "Archeantus, Luram, and Emron", ["Amoron, Zenephi, and Archeantus", "Luram, Aaron, and Zenephi"], ["Archeantus", "Luram", "Emron"]),
    q("b", "4", "What do the people do when Mormon speaks the word of God with sharpness?", "They tremble and are angry", ["They fall on their knees and pray", "They fall silent and go home"], ["tremble"]),
    q("c", "22", "What did Mormon pray to God for Moroni?", "That God would spare his life", ["That he would defeat the Lamanites", "That he would soon lead an army"], ["spare"]),
  ),
  ch("moro", 10,
    q("a", "4", "What does Moroni urge readers to ask God?", "If these things are not true", ["If the Lamanites will repent", "If they may translate the plates"], ["are not true"]),
    q("b", "17", "What is the source of all these gifts, according to Moroni?", "The Spirit of Christ", ["The power of the church", "The law of Moses"], ["Spirit of Christ"]),
    q("c", "20-21", "Which three things must one have to be saved in the kingdom of God?", "Faith, hope, and charity", ["Faith, fasting, and simplicity", "Hope, patience, and obedience"], ["faith", "hope", "charity"]),
  ),
  // ===== EINDE =====
];
