import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 4 Nephi, Mormon, Ether and Moroni (English edition). Each fact is tied to the verses in `verses`; `npm run genees:check` verifies that.
export const slot: GeneesChapterSeed[] = [
  ch("4-ne", 1,
    q("a", "3", "What did the people have among them after their conversion?", "All things common among them", ["All things as private property", "All things under the judges"], ["things common"]),
    q("b", "17", "What had the people become, according to verse 17?", "One, the children of Christ", ["Divided into many social classes", "Separated into two rival peoples"], ["children of Christ"]),
    q("c", "48", "Who hid up the sacred records unto the Lord?", "Ammaron", ["Mormon", "Moroni"], ["Ammaron"]),
  ),
  ch("morm", 1,
    q("a", "2", "About how old was Mormon when Ammaron came to him?", "About ten years old", ["About fourteen years old", "About seven years old"], ["ten years"]),
    q("b", "3", "When was Mormon to remember what he had observed, according to Ammaron?", "When he was about twenty-four", ["When he was about thirty", "When he was about eighteen"], ["about twenty"]),
    q("c", "15", "How old was Mormon when the Lord visited him?", "Fifteen years old", ["Twelve years old", "Twenty years old"], ["fifteen years"]),
  ),
  ch("morm", 2,
    q("a", "2", "In which year of his life did Mormon go forth at the head of an army?", "In his sixteenth year", ["In his eighteenth year", "In his twentieth year"], ["sixteenth"]),
    q("b", "9", "What was the name of the king of the Lamanites who came against the Nephites with a great army?", "Aaron", ["Lamoni", "Ammoron"], ["Aaron"]),
    q("c", "29", "What did the Lamanites give the Nephites in the treaty?", "The land northward", ["The land southward", "The land of Zarahemla"], ["land northward"]),
  ),
  ch("morm", 3,
    q("a", "11", "What did Mormon refuse to be from that time forth because of their wickedness?", "Their commander and leader", ["Their king and judge", "Their priest and teacher"], ["commander"]),
    q("b", "13", "How often had Mormon delivered his people out of the hands of their enemies?", "He delivered them thrice", ["He delivered them twice", "He delivered them seven times"], ["thrice"]),
    q("c", "17", "To whom does Mormon write, according to verse 17?", "To the Gentiles and the house of Israel", ["Only to the Nephites of his own time", "To the king and his army captains"], ["Gentiles", "house of Israel"]),
  ),
  ch("morm", 4,
    q("a", "2", "To which land were the armies of the Nephites driven back?", "The land of Desolation", ["The land of Jershon", "The land of Zarahemla"], ["land of Desolation"]),
    q("b", "5", "By whom are the wicked punished, according to Mormon?", "By the wicked", ["By the angels", "By the righteous"], ["by the wicked"]),
    q("c", "23", "To which hill did Mormon go when the Lamanites were about to overthrow the land?", "To the hill Shim", ["To the hill Manti", "To the hill Riplah"], ["hill Shim"]),
  ),
  ch("morm", 5,
    q("a", "17", "Whom did the Nephites once have as their shepherd?", "Christ for their shepherd", ["Moses for their shepherd", "Nephi for their shepherd"], ["Christ for their shepherd"]),
    q("b", "18", "To what are the people compared who are led about by Satan?", "To chaff driven before the wind", ["To a sheep straying from the flock", "To dust lying on the mountains"], ["chaff"]),
    q("c", "22", "What does Mormon ask the Gentiles?", "How they can stand before God's power", ["How they can preserve the land", "How they can increase their wealth"], ["stand before"]),
  ),
  ch("morm", 6,
    q("a", "4", "To which land did the Nephites march to gather themselves?", "The land of Cumorah", ["The land of Moroni", "The land of Joshua"], ["Cumorah"]),
    q("b", "11", "How many of Mormon's people remained after the battle?", "Twenty-four of us", ["Twenty-seven of us", "Twenty-one of us"], ["twenty"]),
    q("c", "3", "How did the king of the Lamanites respond to Mormon's request?", "He granted Mormon's request", ["He refused the request", "He had the letter burned"], ["grant"]),
  ),
  ch("morm", 7,
    q("a", "2", "Of which house is the remnant of the people, according to Mormon?", "The house of Israel", ["The house of Judah", "The house of David"], ["house of Israel"]),
    q("b", "4", "What must they lay down, according to Mormon?", "Their weapons of war", ["Their golden idols", "Their silver treasures"], ["weapons of war"]),
    q("c", "8", "In whose name must they be baptized, according to Mormon?", "In the name of Jesus", ["In the name of Mormon", "In the name of Nephi"], ["name of Jesus"]),
  ),
  ch("morm", 8,
    q("a", "1", "Who finishes the record of Mormon?", "Moroni", ["Nephi", "Helaman"], ["Moroni"]),
    q("b", "6", "How many years had passed since the coming of Christ?", "Four hundred years", ["Three hundred years", "Five hundred years"], ["four hundred years"]),
    q("c", "23", "Whose prophecies must one search, according to Moroni?", "Those of Isaiah", ["Those of Jeremiah", "Those of Moses"], ["Isaiah"]),
  ),
  ch("morm", 9,
    q("a", "9", "How is God, according to Mormon?", "The same yesterday, today, and forever", ["Variable, according to times and peoples", "Present only in the temple"], ["yesterday, today, and forever"]),
    q("b", "32", "What characters did Mormon and Moroni use for their record?", "Reformed Egyptian", ["Old Hebrew script", "Aramaic and Syriac"], ["reformed Egyptian"]),
    q("c", "21", "What does Moroni promise to whoever believes in Christ without doubting?", "Whatever he asks the Father in his name", ["An exemption from all trials", "A place in every kingdom of the earth"], ["the Father"]),
  ),
  // ===== EINDE =====
];
