import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 4 Nephi, Mormon, Ether en Moroni. Elk feit is gebonden aan de verzen in `verses`;
// `npm run genees:check` controleert dat.
export const slot: GeneesChapterSeed[] = [
  ch("4-ne", 1,
    q("a", "3", "Wat hadden de mensen na hun bekering onder zich?", "Alle dingen gemeenschappelijk", ["Alle dingen als privébezit", "Alle dingen onder de rechters"], ["gemeenschappelijk"]),
    q("b", "17", "Hoe waren de mensen volgens vers 17 geworden?", "Eén, kinderen van Christus", ["Verdeeld in vele standen", "Gescheiden in Nephieten en Lamanieten"], ["kinderen van Christus"]),
    q("c", "48", "Wie verborg de kronieken in de hoede van de Heer?", "Ammaron", ["Mormon", "Moroni"], ["Ammaron"]),
  ),
  ch("morm", 1,
    q("a", "2", "Hoe oud was Mormon toen Ammaron tot hem kwam?", "Ongeveer tien jaar", ["Ongeveer veertien jaar", "Ongeveer zeven jaar"], ["tien jaar"]),
    q("b", "3", "Wanneer moest Mormon volgens Ammaron terugdenken aan wat hij had waargenomen?", "Als hij ongeveer vierentwintig was", ["Als hij ongeveer dertig jaar oud was", "Als hij ongeveer achttien was"], ["vierentwintig"]),
    q("c", "15", "Hoe oud was Mormon toen de Heer tot hem kwam?", "Vijftien jaar", ["Twaalf jaar", "Twintig jaar"], ["vijftien jaar"]),
  ),
  ch("morm", 2,
    q("a", "2", "In welk jaar van zijn leven voerde Mormon een leger aan?", "Zestien", ["Achttien", "Twintig"], ["zestien"]),
    q("b", "9", "Hoe heette de koning van de Lamanieten die met een groot leger aanviel?", "Aäron", ["Lamoni", "Ammoron"], ["Aäron"]),
    q("c", "29", "Wat gaven de Lamanieten aan de Nephieten in het verdrag?", "Het noordelijke land", ["Het zuidelijke land", "Het land Zarahemla"], ["noordelijke land"]),
  ),
  ch("morm", 3,
    q("a", "11", "Wat weigerde Mormon omwille van hun goddeloosheid voortaan te zijn?", "Hun commandant en leider", ["Hun koning en rechter", "Hun priester en leraar"], ["commandant"]),
    q("b", "13", "Hoe vaak had Mormon zijn volk uit de handen van hun vijanden bevrijd?", "Driemaal", ["Tweemaal", "Zevenmaal"], ["driemaal"]),
    q("c", "17", "Aan wie schrijft Mormon volgens vers 17?", "Aan de andere volken en het huis van Israël", ["Alleen aan de Nephieten van zijn eigen tijd", "Aan de koning en zijn legeraanvoerders"], ["andere volken", "huis van Israël"]),
  ),
  ch("morm", 4,
    q("a", "2", "Naar welk land werden de legers van de Nephieten teruggedreven?", "Het land Woestenij", ["Het land Jershon", "Het land Zarahemla"], ["Woestenij"]),
    q("b", "5", "Door wie worden de goddelozen volgens Mormon gestraft?", "Door de goddelozen", ["Door de engelen", "Door de rechtvaardigen"], ["goddelozen"]),
    q("c", "23", "Waarheen ging Mormon toen de Lamanieten het land ten val dreigden te brengen?", "Naar de heuvel Shim", ["Naar de heuvel Manti", "Naar de heuvel Riplah"], ["heuvel Shim"]),
  ),
  ch("morm", 5,
    q("a", "17", "Wie hadden de Nephieten eens als hun Herder?", "Christus als hun Herder", ["Mozes als hun Herder", "Nephi als hun Herder"], ["Christus als hun Herder"]),
    q("b", "18", "Waarmee wordt het volk vergeleken dat door Satan wordt geleid?", "Met kaf dat voor de wind wordt gedreven", ["Met een schaap dat van de kudde dwaalt", "Met stof dat op de bergen ligt"], ["kaf"]),
    q("c", "22", "Wat vraagt Mormon aan de andere volken?", "Hoe zij tegenover Gods macht standhouden", ["Hoe zij het land kunnen bewaren", "Hoe zij hun rijkdom kunnen vergroten"], ["standhouden"]),
  ),
  ch("morm", 6,
    q("a", "4", "Naar welk land marcheerden de Nephieten om zich te verzamelen?", "Het land Cumorah", ["Het land Moroni", "Het land Jozua"], ["Cumorah"]),
    q("b", "11", "Hoeveel van Mormons volk bleven er over na de slag?", "Vierentwintig", ["Zevenentwintig", "Eenentwintig"], ["vierentwintig"]),
    q("c", "3", "Hoe reageerde de koning van de Lamanieten op Mormons verzoek?", "Hij stemde in met het verzoek", ["Hij weigerde het verzoek", "Hij liet de brief verbranden"], ["verzoek"]),
  ),
  ch("morm", 7,
    q("a", "2", "Van welk huis is het overblijfsel van het volk volgens Mormon?", "Het huis van Israël", ["Het huis van Juda", "Het huis van David"], ["huis van Israël"]),
    q("b", "4", "Wat moeten zij volgens Mormon neerleggen?", "Hun oorlogswapens", ["Hun gouden afgoden", "Hun zilveren schatten"], ["oorlogswapens"]),
    q("c", "8", "In wiens naam moeten zij zich volgens Mormon laten dopen?", "In de naam van Jezus", ["In de naam van Mormon", "In de naam van Nephi"], ["naam van Jezus"]),
  ),
  ch("morm", 8,
    q("a", "1", "Wie beëindigt de kroniek van Mormon?", "Moroni", ["Nephi", "Helaman"], ["Moroni"]),
    q("b", "6", "Hoeveel jaar was er verstreken sinds de komst van Christus?", "Vierhonderd jaar", ["Driehonderd jaar", "Vijfhonderd jaar"], ["vierhonderd jaar"]),
    q("c", "23", "Welke profetieën moet men volgens Moroni onderzoeken?", "De profetieën van Jesaja", ["De profetieën van Jeremia", "De profetieën van Mozes"], ["Jesaja"]),
  ),
  ch("morm", 9,
    q("a", "9", "Hoe is God volgens Mormon?", "Dezelfde gisteren, heden en voor eeuwig", ["Veranderlijk, naar de tijden en de volken", "Alleen aanwezig in de tempel"], ["gisteren, heden en voor eeuwig"]),
    q("b", "32", "Welke lettertekens gebruikten Mormon en Moroni voor hun kroniek?", "Hervormd-Egyptisch", ["Oud-Hebreeuws", "Aramees-Syrisch"], ["Hervormd-Egyptisch"]),
    q("c", "21", "Wat belooft Moroni aan wie in Christus gelooft zonder te twijfelen?", "Wat hij de Vader ook in Christus' naam vraagt", ["Een vrijstelling van alle beproevingen", "Een plaats in elk koninkrijk van de aarde"], ["Vader"]),
  ),
  ch("ether", 1,
    q("a", "2", "Uit hoeveel platen ontleent Moroni zijn verslag over de oude inwoners die werden vernietigd?", "Vierentwintig platen", ["Twaalf gouden platen", "Achtenveertig platen"], ["vierentwintig"]),
    q("b", "34-35", "Wat gebeurde er met de taal van Jared en zijn broer bij de grote toren?", "Hun taal werd niet verward", ["Hun taal werd gedeeltelijk gewijzigd", "Hun taal werd volledig vervangen"], ["niet verward"]),
    q("c", "38,42", "Wat beloofde de Heer over het land waarheen Hij de broer van Jared zou leiden?", "Dat het verkieslijk was boven alle landen", ["Dat het vruchtbaarder was dan Egypte", "Dat het dicht bij de toren lag"], ["verkieslijk", "alle landen"]),
  ),
  ch("ether", 2,
    q("a", "3", "Wat betekent het woord 'deseret', dat de Jarediëten met zich meevoerden?", "Een honingbij", ["Een veldmuis", "Een zoetwatervis"], ["honingbij"]),
    q("b", "14", "Hoe lang sprak de Heer met de broer van Jared toen Hij hem kastijdde?", "Drie uur lang", ["Zeven uur lang", "Twee uur lang"], ["drie uur"]),
    q("c", "17", "Hoe dicht waren de boten van de Jarediëten gebouwd?", "Zo dicht als een schotel", ["Zo dicht als een ton", "Zo dicht als een kruik"], ["schotel"]),
  ),
  ch("ether", 3,
    q("a", "1", "Hoeveel kleine stenen smolt de broer van Jared uit een rots op de berg Shelem?", "Zestien stenen", ["Twaalf stenen", "Achttien stenen"], ["zestien"]),
    q("b", "4-6", "Hoe maakte de Heer de stenen lichtgevend toen de broer van Jared Hem erom vroeg?", "Hij raakte ze aan met zijn vinger", ["Hij blies erover met zijn adem", "Hij liet er een vuurstraal op neerkomen"], ["vinger"]),
    q("c", "21-22", "Wat moest de broer van Jared doen met de dingen die hij had gezien en gehoord?", "Ze opschrijven en verzegelen", ["Ze meteen aan het volk vertellen", "Ze doorgeven aan zijn eigen zonen"], ["opschrijven", "verzegelen"]),
  ),
  ch("ether", 4,
    q("a", "1", "Wanneer mochten de dingen die de broer van Jared schreef tot de mensenkinderen komen?", "Nadat Hij aan het kruis was verhoogd", ["Nadat de Nephieten waren vernietigd", "Nadat Hij naar de hemel was opgevaren"], ["kruis"]),
    q("b", "3,5", "Wat gebood de Heer Moroni te doen met de verslagen van de broer van Jared?", "Ze weer in de aarde verbergen", ["Ze aan de Lamanieten geven", "Ze verbranden voor ze werden ontdekt"], ["aarde", "verbergen"]),
    q("c", "6-7", "Wanneer zou de Heer aan de andere volken openbaren wat de broer van Jared zag?", "Wanneer zij zich bekeren en geloof oefenen", ["Wanneer zij hun oorlogen hebben beëindigd", "Wanneer zij zelf de platen hebben gevonden"], ["bekeren", "geloof"]),
  ),
  ch("ether", 5,
    q("a", "3", "Aan hoeveel getuigen zouden de platen door de macht van God worden getoond?", "Aan drie getuigen", ["Aan twaalf getuigen", "Aan zeven getuigen"], ["drie"]),
    q("b", "1", "Wat mocht er niet gebeuren met de dingen die Moroni had verzegeld?", "Niemand mocht ze vertalen", ["Niemand mocht ze verplaatsen", "Niemand mocht ze bekijken"], ["vertalen"]),
    q("c", "5", "Wat gebeurt er met wie zich bekeert en tot de Vader komt in de naam van Jezus?", "Hij wordt in het koninkrijk van God ontvangen", ["Hij krijgt de macht om verzegelde platen te openen", "Hij ontvangt de gave om de platen te vertalen"], ["koninkrijk van God"]),
  ),
  ch("ether", 6,
    q("a", "11", "Hoe lang werden de Jarediëten op het water voortgedreven voordat zij het beloofde land bereikten?", "Driehonderdvierenveertig dagen", ["Driehonderdvijfenzestig dagen", "Honderdtweeënveertig dagen"], ["driehonderdvierenveertig"]),
    q("b", "9", "Wat deed de broer van Jared de hele dag terwijl zij op de wateren werden voortgedreven?", "Hij zong de Heer lof toe", ["Hij hield de wacht bij de stenen", "Hij las hardop uit de kroniek"], ["lof toe"]),
    q("c", "27", "Wie van de zonen van Jared werd tot koning over het volk gezalfd?", "Orihah, een zoon van Jared", ["Gilgah, een zoon van Jared", "Jacom, een zoon van Jared"], ["Orihah"]),
  ),
  ch("ether", 7,
    q("a", "9", "Wat maakte Shule uit de heuvel Efraïm voor de mannen die hij met zich had gevoerd?", "Zwaarden van staal", ["Pijlpunten van brons", "Schilden van koper"], ["zwaarden", "staal"]),
    q("b", "4", "Hoe oud was Corihor toen hij tegen zijn vader Kib opstond?", "Tweeëndertig jaar", ["Eenentwintig jaar", "Vijfenveertig jaar"], ["tweeëndertig"]),
    q("c", "24-25", "Wat deed koning Shule voor de profeten die door het volk werden beschimpt?", "Hij gaf hun de bevoegdheid te gaan waarheen zij wilden", ["Hij gaf hun soldaten mee om hen overal te beschermen", "Hij liet hen wonen in een stad onder zijn bescherming"], ["waarheen zij"]),
  ),
  ch("ether", 8,
    q("a", "10-11", "Wat deed de dochter van Jared om Akish, de zoon van Kimnor, te behagen?", "Zij danste voor hem", ["Zij zong voor hem", "Zij schonk wijn voor hem"], ["danste"]),
    q("b", "12", "Wat eiste Jared van Akish in ruil voor zijn dochter?", "Het hoofd van zijn vader, de koning", ["Een groot deel van zijn goud en zilver", "De sleutels van de grootste stad"], ["hoofd", "koning"]),
    q("c", "19", "Wat zegt Moroni over de Heer en geheime verenigingen?", "De Heer werkt niet door geheime verenigingen", ["De Heer gebruikt ze om zijn volk te toetsen", "De Heer duldt ze alleen onder zijn profeten"], ["niet door geheime verenigingen"]),
  ),
  ch("ether", 9,
    q("a", "3", "Hoe werd Omer gewaarschuwd dat hij het land moest verlaten?", "De Heer waarschuwde hem in een droom", ["Een engel verscheen hem op een berg", "Een profeet sprak hem toe bij de poort"], ["droom"]),
    q("b", "22", "Wie zag koning Emer, waarover hij zich verheugde en roemde?", "De Zoon van gerechtigheid", ["Een engel van de Heer", "Een profeet uit het noorden"], ["Zoon van gerechtigheid"]),
    q("c", "35", "Wat gebeurde er nadat het volk zich voldoende voor het aangezicht van de Heer had verootmoedigd?", "De Heer zond regen op het aardoppervlak", ["De Heer zond manna uit de hemel", "De Heer liet de giftige slangen verdwijnen"], ["regen"]),
  ),
  ch("ether", 10,
    q("a", "5", "Waarmee belastte koning Riplakish het volk?", "Met een hoge belasting", ["Met verplichte legerdienst", "Met jarenlange dwangarbeid"], ["hoge belasting"]),
    q("b", "20", "Waar bouwden de Jarediëten in de dagen van Lib een grote stad?", "Bij de landengte", ["Bij de heuvel Shim", "In het dal Nimrod"], ["landengte"]),
    q("c", "23", "Welke vier metalen groeven de Jarediëten in de dagen van Lib uit de aarde?", "Goud, zilver, ijzer en koper", ["Goud, zilver, tin en lood", "Zilver, ijzer, tin en brons"], ["goud", "zilver", "ijzer", "koper"]),
  ),
  ch("ether", 11,
    q("a", "5", "Wat deed de broer van Shiblom met de profeten die de vernietiging van het volk voorspelden?", "Hij liet hen ter dood brengen", ["Hij verbande hen naar de wildernis", "Hij zette hen gevangen in Moron"], ["ter dood"]),
    q("b", "2", "Naar wie vluchtten de profeten voor bescherming toen het volk hen wilde vernietigen?", "Naar koning Com", ["Naar koning Omer", "Naar koning Shule"], ["Com"]),
    q("c", "20-21", "Wat zou de Here God doen als het volk zich in de dagen van Coriantor niet bekeerde?", "Een ander volk zenden om het land te bezitten", ["Hun koning door een profeet vervangen", "Het land onder de zee laten verdwijnen"], ["ander volk", "land te bezitten"]),
  ),
  ch("ether", 12,
    q("a", "6", "Wat is geloof volgens Moroni?", "Hopen op dingen die men niet ziet", ["Zeker weten wat men al heeft gezien", "Geloven wat men zelf kan bewijzen"], ["niet ziet"]),
    q("b", "13", "Door wiens geloof viel volgens Moroni de gevangenis ter aarde?", "Dat van Alma en Amulek", ["Dat van Abinadi en Limhi", "Dat van Ammon en zijn broeders"], ["Alma en Amulek"]),
    q("c", "30", "Wat gebeurde er toen de broer van Jared tot de berg Zerin sprak?", "Hij verplaatste zich", ["Hij spleet in tweeën", "Hij begon te beven"], ["verplaatste"]),
  ),
  ch("ether", 13,
    q("a", "6", "Voor wie zou het Nieuw Jeruzalem op dit land worden gebouwd?", "Voor het overblijfsel van het nageslacht van Jozef", ["Voor het overblijfsel van het nageslacht van Juda", "Voor de laatste volgelingen van de Jarediëten"], ["overblijfsel", "nageslacht van Jozef"]),
    q("b", "13", "Waar verborg Ether zich overdag nadat het volk hem had verworpen?", "In de holte van een rots", ["In een grot bij de zee", "In een put in de wildernis"], ["holte van een rots"]),
    q("c", "31", "Waar had Shared Coriantumr verwond, zodat die twee jaar lang niet ten strijde trok?", "Aan zijn dij", ["Aan zijn arm", "Aan zijn schouder"], ["dij"]),
  ),
  ch("ether", 14,
    q("a", "10", "Waarin overtrof Lib de andere mannen van het volk?", "Hij was zeer groot van gestalte", ["Hij had de meeste rijkdommen", "Hij had de grootste legermacht"], ["groot van gestalte"]),
    q("b", "17", "Wiens broer was Shiz, die vele steden veroverde en in brand stak?", "De broer van Lib", ["De broer van Shared", "De broer van Com"], ["broer van Lib"]),
    q("c", "21-23", "Waardoor werden de mensen dag en nacht geplaagd toen het hele land met lichamen was bedekt?", "Door de stank van de doden", ["Door giftige slangen op de weg", "Door een tekort aan water"], ["stank"]),
  ),
  ch("ether", 15,
    q("a", "2", "Hoeveel sterke mannen waren er al gedood toen Coriantumr zich bedroefd begon te bekeren?", "Twee miljoen mannen", ["Vier miljoen mannen", "Een half miljoen mannen"], ["twee miljoen"]),
    q("b", "11", "Op welke heuvel sloeg het leger van Coriantumr zijn tenten op, waar Mormon de heilige kronieken had verborgen?", "De heuvel Ramah", ["De heuvel Comnor", "De heuvel Shim"], ["Ramah"]),
    q("c", "30", "Wat deed Coriantumr toen hij op zijn zwaard had geleund om wat uit te rusten?", "Hij sloeg Shiz het hoofd af", ["Hij gaf zich over aan Shiz", "Hij blies een bazuin voor zijn leger"], ["het hoofd af"]),
  ),
  ch("moro", 1,
    q("a", "3", "Waarom zwierf Moroni overal rond?", "Voor de veiligheid van zijn leven", ["Om nieuwe platen te gaan zoeken", "Om de Lamanieten te bekeren"], ["veiligheid", "leven"]),
    q("b", "2", "Wie doden de Lamanieten volgens Moroni in hun oorlogen?", "Iedere Nephiet die Christus niet wil verloochenen", ["Iedere Nephiet die geen wapens wil dragen", "Iedere Nephiet die de platen niet wil afstaan"], ["Nephiet", "niet wil verloochenen"]),
    q("c", "1", "Over welk volk had Moroni net de samenvatting van het verslag voltooid?", "Het volk van Jared", ["Het volk van Limhi", "Het volk van Ammon"], ["volk van Jared"]),
  ),
  ch("moro", 2,
    q("a", "1", "Aan wie sprak Christus de woorden die in Moroni 2 staan?", "De twaalf die Hij had gekozen", ["De zeventig die Hij had gekozen", "De drie die Hij had gekozen"], ["twaalf"]),
    q("b", "2", "Wat konden de discipelen door handoplegging geven?", "De Heilige Geest", ["De gave van talen", "De gave van profetie"], ["Heilige Geest"]),
    q("c", "3", "Wie hoorden de woorden van Christus niet toen Hij ze bij zijn eerste verschijning sprak?", "De menigte die erbij stond", ["De discipelen die erbij waren", "De leraren die erbij waren"], ["menigte"]),
  ),
  ch("moro", 3,
    q("a", "1", "Hoe werden de discipelen genoemd die priesters en leraren ordenden?", "Ouderlingen van de kerk", ["Apostelen van de kerk", "Opzieners van de kerk"], ["ouderlingen van de kerk"]),
    q("b", "2", "Wat deden de discipelen eerst voordat zij iemand de handen oplegden om hem te ordenen?", "Zij baden tot de Vader in de naam van Christus", ["Zij lazen uit de schriften voor de hele kerk", "Zij vroegen de kerk om haar stem te geven"], ["Vader", "naam van Christus"]),
    q("c", "3", "Wat moest iemand prediken die tot priester of leraar werd geordend?", "Bekering en vergeving van zonden", ["Het herstel van de kerk van Christus", "Het verbond van Abraham aan alle volken"], ["bekering en vergeving van zonden"]),
  ),
  ch("moro", 4,
    q("a", "3", "Ter gedachtenis waaraan werd het brood gegeten?", "Ter gedachtenis van het lichaam van de Zoon", ["Ter gedachtenis van de wet van Mozes", "Ter gedachtenis van de uittocht uit Egypte"], ["gedachtenis van het lichaam"]),
    q("b", "2", "Wat deden de ouderling of priester en de kerk voordat het brood werd gezegend?", "Zij knielden neer en baden tot de Vader", ["Zij gingen staan en zongen een lofzang", "Zij waren stil en lazen een psalm voor"], ["knielden", "Vader"]),
    q("c", "3", "Wat vroegen zij aan God te doen met het brood?", "Het te zegenen en te heiligen", ["Het te brengen naar de zieken", "Het te delen onder alle aanwezigen"], ["zegenen en te heiligen"]),
  ),
  ch("moro", 5,
    q("a", "2", "Ter gedachtenis waaraan dronken zij de wijn?", "Ter gedachtenis van het bloed van de Zoon", ["Ter gedachtenis van het verbond met Abraham", "Ter gedachtenis van de wet van Mozes"], ["gedachtenis van het bloed"]),
    q("b", "1", "Wat namen zij in handen toen de wijn werd bediend?", "Een beker", ["Een kruik", "Een schaal"], ["beker"]),
    q("c", "2", "Hoe spraken zij God aan in het gebed over de wijn?", "O God, eeuwige Vader", ["O God, Heer der heerscharen", "O Heer, onze Verlosser"], ["eeuwige Vader"]),
  ),
  ch("moro", 6,
    q("a", "2", "Met welke gezindheid moesten mensen tot de doop komen?", "Met een gebroken hart en een verslagen geest", ["Met gereinigde handen en een zuiver hart", "Met een groot geloof en een sterk getuigenis"], ["gebroken hart", "verslagen geest"]),
    q("b", "5", "Waarvoor kwamen de leden van de kerk dikwijls bijeen, naast het spreken over het welzijn van hun ziel?", "Om te vasten en te bidden", ["Om te werken en te oogsten", "Om te reizen en te handelen"], ["vasten en te bidden"]),
    q("c", "7", "Hoeveel getuigen van de kerk moesten iemand schuldig bevinden voor de ouderlingen?", "Drie getuigen", ["Twee getuigen", "Zeven getuigen"], ["drie getuigen"]),
  ),
  ch("moro", 7,
    q("a", "47", "Wat is naastenliefde volgens Mormon?", "De reine liefde van Christus zelf", ["De hoogste vorm van offerbereidheid", "De liefde die men van anderen ontvangt"], ["reine liefde van Christus"]),
    q("b", "11", "Welk beeld gebruikt Mormon om te laten zien dat een slecht mens niets goeds kan doen?", "Een bittere bron die geen goed water geeft", ["Een droge put die geen water geeft", "Een slechte oogst die geen graan geeft"], ["bittere bron"]),
    q("c", "16", "Wat wordt aan ieder mens gegeven om goed van kwaad te kunnen onderscheiden?", "De Geest van Christus", ["De gave van profetie", "De wet van Mozes"], ["Geest van Christus"]),
  ),
  ch("moro", 8,
    q("a", "4-5", "Waarover was er woordenstrijd ontstaan onder de mensen, tot verdriet van Mormon?", "De doop van kleine kinderen", ["De ordening van leraren", "De wijze van handoplegging"], ["doop", "kleine kinderen"]),
    q("b", "12", "Waarom hebben kleine kinderen volgens Mormon geen doop nodig?", "Zij zijn levend in Christus", ["Zij zijn al gedoopt in de geest", "Zij zijn nog te jong om te lijden"], ["levend in Christus"]),
    q("c", "25", "Wat noemt Mormon de eerste vrucht van de bekering?", "De doop, die door geloof komt", ["De vergeving van alle zonden", "De zachtmoedigheid van het hart"], ["doop"]),
  ),
  ch("moro", 9,
    q("a", "2", "Welke mannen waren volgens Mormon door het zwaard gevallen in de strijd met de Lamanieten?", "Archeantus, Luram en Emron", ["Amoron, Zenephi en Archeantus", "Luram, Aäron en Zenephi"], ["Archeantus", "Luram", "Emron"]),
    q("b", "4", "Wat doen de mensen als Mormon het woord van God met scherpte spreekt?", "Zij beven en worden vertoornd", ["Zij vallen op hun knieën en bidden", "Zij zwijgen en gaan naar huis"], ["beven", "vertoornd"]),
    q("c", "22", "Waarvoor bad Mormon voor zijn zoon Moroni?", "Dat God zijn leven zal sparen", ["Dat hij de Lamanieten zal verslaan", "Dat hij snel een leger zal leiden"], ["leven zal sparen"]),
  ),
  ch("moro", 10,
    q("a", "4", "Wat spoort Moroni de lezers aan aan God te vragen?", "Of deze dingen niet waar zijn", ["Of de Lamanieten zich zullen bekeren", "Of zij de platen mogen vertalen"], ["niet waar zijn"]),
    q("b", "17", "Wat is volgens Moroni de bron van al deze gaven?", "De Geest van Christus", ["De kracht van de kerk", "De wet van Mozes"], ["Geest van Christus"]),
    q("c", "20-21", "Welke drie dingen moet iemand hebben om behouden te worden in het koninkrijk van God?", "Geloof, hoop en naastenliefde", ["Geloof, vasten en eenvoud", "Hoop, geduld en gehoorzaamheid"], ["geloof", "hoop", "naastenliefde"]),
  ),
  // ===== EINDE =====
];
