import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 3 Nephi. Elk feit is gebonden aan de verzen in `verses`; `npm run genees:check` controleert dat.
export const nephi3: GeneesChapterSeed[] = [
  ch("3-ne", 1,
    q("a", "19", "Wat gebeurde er in de nacht van het teken?", "Er was geen duisternis, het was licht als op de dag", ["Er was een zware storm die de nacht verlichtte", "Er was een zonsverduistering van vele uren"], ["geen duisternis"]),
    q("b", "21", "Wat verscheen er volgens het woord van de profeten aan de hemel?", "Een nieuwe ster", ["Een nieuwe maan", "Een rode komeet"], ["nieuwe ster"]),
    q("c", "3", "Wie hield de kronieken bij nadat zijn vader het land had verlaten?", "Nephi, de zoon van Nephi", ["Lehi, de zoon van Nephi", "Nephi, de zoon van Lehi"], ["Nephi"]),
  ),
  ch("3-ne", 2,
    q("a", "8", "Vanaf welk tijdstip begonnen de Nephieten hun tijd te rekenen?", "Vanaf het teken van de komst van Christus", ["Vanaf de dood van koning Mosiah", "Vanaf het vertrek van Lehi uit Jeruzalem"], ["komst van Christus"]),
    q("b", "12", "Wat deden de bekeerde Lamanieten toen de rovers dreigden?", "Zij verenigden zich met de Nephieten", ["Zij trokken weg naar het noorden", "Zij bouwden hun eigen koninkrijk"], ["verenigden zich"]),
    q("c", "11", "Door wie ontstonden er in het dertiende jaar oorlogen en twisten?", "Door de rovers van Gadianton", ["Door de Lamanieten uit het zuiden", "Door de koning van Zarahemla"], ["rovers van Gadianton"]),
  ),
  ch("3-ne", 3,
    q("a", "9", "Hoe heette het hoofd van de geheime vereniging van Gadianton?", "Giddianhi", ["Gidgiddoni", "Zemnarihah"], ["Giddianhi"]),
    q("b", "18", "Wie werd aangesteld als hoogste commandant van alle legers van de Nephieten?", "Gidgiddoni", ["Lachoneüs", "Moronihah"], ["Gidgiddoni"]),
    q("c", "23", "Welk land werd aangewezen om zich in te verzamelen?", "Het land Zarahemla", ["Het land Jershon", "Het land Melek"], ["Zarahemla"]),
  ),
  ch("3-ne", 4,
    q("a", "28", "Hoe heette de nieuwe leider van de rovers die aan een boom werd opgehangen?", "Zemnarihah", ["Giddianhi", "Lachoneüs"], ["Zemnarihah"]),
    q("b", "3", "Waarom konden de rovers zich alleen in de wildernis in leven houden?", "De Nephieten hadden hun landen verlaten", ["De Lamanieten hadden hun landen bezet", "De rovers hadden alle steden ingenomen"], ["landen"]),
    q("c", "32", "Wat riepen de Nephieten toen zij God loofden?", "Hosanna de allerhoogste God", ["Halleluja de heilige God", "Eer aan de koning van het land"], ["Hosanna"]),
  ),
  ch("3-ne", 5,
    q("a", "12", "Naar welk land is Mormon genoemd?", "Het land Mormon", ["Het land Helam", "Het land Overvloed"], ["land Mormon"]),
    q("b", "13", "Wat is Mormon volgens zijn eigen woorden?", "Een discipel van Jezus Christus", ["Een hogepriester van de kerk", "Een legeraanvoerder van de Nephieten"], ["discipel van Jezus Christus"]),
    q("c", "11", "Waarop schrijft Mormon zijn kroniek?", "Op platen die hij eigenhandig had gemaakt", ["Op platen die zijn vader had gemaakt", "Op koperen platen uit Jeruzalem"], ["eigenhandig"]),
  ),
  ch("3-ne", 6,
    q("a", "6", "Wie hadden de grote vrede in het land gebracht?", "Gidgiddoni en de rechter Lachoneüs", ["Zemnarihah en de rechter Giddianhi", "Moroni en de rechter Pahoran"], ["Gidgiddoni", "Lachoneüs"]),
    q("b", "14", "In welk jaar begon de kerk uiteen te vallen?", "In het dertigste jaar", ["In het twintigste jaar", "In het veertigste jaar"], ["dertigste"]),
    q("c", "8", "Wat werd er in het land aangelegd in de tijd van vrede?", "Vele wegen en paden", ["Vele muren en torens", "Vele kanalen en bruggen"], ["wegen"]),
  ),
  ch("3-ne", 7,
    q("a", "19", "Wat deed Nephi in de naam van Jezus met zijn broer?", "Hij wekte zijn broer op uit de doden", ["Hij genas zijn broer van blindheid", "Hij redde zijn broer uit de gevangenis"], ["uit de doden"]),
    q("b", "10", "Hoe noemde de geheime vereniging de man die zij als hoofd aanstelden?", "Zij noemden hem hun koning", ["Zij noemden hem hun rechter", "Zij noemden hem hun profeet"], ["koning"]),
    q("c", "2", "In wat verdeelde het volk zich?", "In stammen", ["In steden", "In legers"], ["stammen"]),
  ),
  ch("3-ne", 8,
    q("a", "5", "In welk jaar stak er een grote storm op?", "In het vierendertigste jaar", ["In het drieëndertigste jaar", "In het vijfendertigste jaar"], ["vierendertigste"]),
    q("b", "8", "Wat gebeurde er met de stad Zarahemla?", "Ze vatte vlam", ["Ze zonk weg", "Ze werd bedekt"], ["vlam"]),
    q("c", "23", "Hoe lang werd er geen licht gezien?", "Drie dagen", ["Zeven dagen", "Twee dagen"], ["drie dagen"]),
  ),
  ch("3-ne", 9,
    q("a", "3", "Wat gebeurde er volgens de stem met de grote stad Zarahemla?", "Ze werd met vuur verbrand", ["Ze zonk in de diepten van de zee", "Ze werd met aarde bedekt"], ["met vuur verbrand"]),
    q("b", "18", "Hoe noemt de Heer zichzelf in vers 18?", "De Alfa en de Omega", ["De Eerste en de Laatste", "De Herder en de Rots"], ["Alfa", "Omega"]),
    q("c", "20", "Welk offer vraagt de Heer in plaats van bloedvergieten?", "Een gebroken hart en een verslagen geest", ["Een offer van de eerstelingen van het vee", "Een brandoffer van het beste graan"], ["gebroken hart"]),
  ),
  ch("3-ne", 10,
    q("a", "9", "Hoe lang duurde het voordat de duisternis van het land verdween?", "Drie dagen", ["Zeven dagen", "Twee dagen"], ["drie dagen"]),
    q("b", "5", "Waarmee vergelijkt de Heer zijn verlangen het volk te vergaderen?", "Met een hen die haar kuikens vergadert", ["Met een herder die zijn schapen leidt", "Met een adelaar die zijn jongen draagt"], ["kuikens"]),
    q("c", "16", "Welke profeten hebben volgens Mormon van die dingen getuigd?", "Zenos en Zenock", ["Jesaja en Jeremia", "Mozes en Aäron"], ["Zenos", "Zenock"]),
  ),
  ch("3-ne", 11,
    q("a", "1", "Waar was de grote menigte van het volk van Nephi bijeenvergaderd?", "Rondom de tempel in Overvloed", ["Rondom de berg in Zarahemla", "Rondom het paleis in Nephi"], ["tempel"]),
    q("b", "7", "Wat zei de stem uit de hemel?", "Zie mijn geliefde Zoon; luister naar Hem", ["Zie mijn dienstknecht; volg zijn woorden", "Zie de profeet; vrees zijn oordelen"], ["geliefde Zoon", "luister naar Hem"]),
    q("c", "25", "In wiens naam moet er volgens de Heer worden gedoopt?", "In de naam van de Vader, de Zoon en de Heilige Geest", ["In de naam van de Vader, de profeet en de koning", "In de naam van de Heer, de engel en de Geest"], ["Vader", "Zoon", "Heilige Geest"]),
  ),
  ch("3-ne", 12,
    q("a", "13", "Waartoe draagt de Heer de mensen op in vers 13?", "Het zout van de aarde te zijn", ["Het zout van de zee te zijn", "Het brood van de aarde te zijn"], ["zout van de aarde"]),
    q("b", "5", "Wie zullen volgens de Heer de aarde beërven?", "Zij die zachtmoedig zijn", ["Zij die rijk en machtig zijn", "Zij die snel en sterk zijn"], ["zachtmoedig"]),
    q("c", "44", "Wat gebiedt de Heer ten aanzien van onze vijanden?", "Heb uw vijanden lief", ["Verjaag uw vijanden", "Straf uw vijanden"], ["vijanden lief"]),
  ),
  ch("3-ne", 13,
    q("a", "9", "Hoe begint het gebed dat Jezus de menigte leert?", "Onze Vader die in de hemelen zijt", ["Onze Heer die in de hemel woont", "Onze God die op de aarde regeert"], ["Onze Vader die in de hemelen zijt"]),
    q("b", "33", "Wat moet men volgens Jezus eerst zoeken?", "Het koninkrijk van God en zijn gerechtigheid", ["Rijkdom en een goede naam onder de mensen", "Voedsel en kleding voor het gezin"], ["koninkrijk van God"]),
    q("c", "24", "Hoeveel heren kan niemand volgens Jezus dienen?", "Twee heren", ["Drie heren", "Zeven heren"], ["twee heren"]),
  ),
  ch("3-ne", 14,
    q("a", "7", "Wat belooft de Heer aan wie vraagt?", "Het zal u gegeven worden", ["Het zal u worden afgenomen", "Het zal u worden vergeten"], ["gegeven worden"]),
    q("b", "15", "Hoe komen valse profeten volgens de Heer tot ons?", "In schaapskleren", ["In koningskleren", "In priestergewaden"], ["schaapskleren"]),
    q("c", "24", "Waarop bouwde de verstandige man volgens Jezus zijn huis?", "Op een rots", ["Op het zand", "Op een heuvel"], ["rots"]),
  ),
  ch("3-ne", 15,
    q("a", "17", "Wat zegt de Heer over andere schapen?", "Dat Hij nog andere schapen heeft", ["Dat Hij geen andere schapen meer heeft", "Dat alle schapen van deze kudde zijn"], ["andere schapen"]),
    q("b", "4", "Wat is volgens de Heer vervuld?", "De wet die Mozes werd gegeven", ["De wet die Lehi werd gegeven", "De wet die Abraham werd gegeven"], ["wet die Mozes werd gegeven"]),
    q("c", "9", "Wat is de Heer volgens vers 9?", "De wet en het licht", ["De poort en de weg", "De vrede en de rots"], ["wet en het licht"]),
  ),
  ch("3-ne", 16,
    q("a", "6", "Wie zijn volgens de Heer gezegend wegens hun geloof in Hem?", "De andere volken", ["De Nephieten alleen", "De Joden in Jeruzalem"], ["andere volken"]),
    q("b", "18", "Wat zullen de wachters volgens de profeet Jesaja doen?", "De stem verheffen en met één stem zingen", ["Het volk bijeenroepen met bazuinen", "De stad verlaten en vluchten"], ["stem verheffen"]),
    q("c", "13", "Wat gebeurt er met de andere volken als zij zich bekeren en tot de Heer terugkeren?", "Zij worden onder mijn volk gerekend", ["Zij worden uit het land verdreven", "Zij worden zonder oordeel gespaard"], ["onder mijn volk"]),
  ),
  ch("3-ne", 17,
    q("a", "14", "Wat deed Jezus toen de menigte op de grond was neergeknield?", "Hij zuchtte diep vanbinnen", ["Hij ging heimelijk weg", "Hij zegende hen met de handen"], ["zuchtte"]),
    q("b", "7", "Wie vroeg Jezus de menigte bij Hem te brengen?", "Mensen die ziek, lam of blind zijn", ["Mensen die rijk en machtig zijn", "Mensen die vreemd en onbekend zijn"], ["ziek"]),
    q("c", "21", "Hoe nam Jezus de kleine kinderen bij zich?", "Hij nam hen een voor een bij zich", ["Hij stuurde hen terug naar hun ouders", "Hij liet hen in groepen bidden"], ["een voor een"]),
  ),
  // ===== EINDE =====
];
