import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Alma. Elk feit is gebonden aan de verzen in `verses`; `npm run genees:check` controleert dat.
export const alma: GeneesChapterSeed[] = [
  ch("alma", 1,
    q("a", "15", "Wat was de naam van de man die Gideon doodde?", "Nehor", ["Amlici", "Korihor"], ["Nehor"]),
    q("b", "15", "Waar werd Nehor ter dood gebracht?", "Op de top van de heuvel Manti", ["Aan de oever van de rivier Sidon", "Op de markt van Zarahemla"], ["heuvel Manti"]),
    q("c", "12", "Wat was volgens Alma voor het eerst onder het volk ingevoerd?", "Het priesterbedrog", ["Het houden van slaven", "De bouw van een tempel"], ["priesterbedrog"]),
  ),
  ch("alma", 2,
    q("a", "1", "Hoe heette de man die koning over het volk wilde worden?", "Amlici", ["Nehor", "Korihor"], ["Amlici"]),
    q("b", "31", "Hoe doodde Alma de aanvoerder van de Amlicieten?", "Met het zwaard", ["Met een speer", "Met een pijl"], ["zwaard"]),
    q("c", "15", "Bij welke heuvel kwamen de Amlicieten aan, ten oosten van de Sidon?", "De heuvel Amnihu", ["De heuvel Manti", "De heuvel Riplah"], ["Amnihu"]),
  ),
  ch("alma", 3,
    q("a", "4", "Wat hadden de Amlicieten op hun voorhoofd aangebracht?", "Een rood teken", ["Een blauw teken", "Een zwart teken"], ["rood"]),
    q("b", "26", "Hoeveel zielen werden er in dat ene jaar naar de eeuwige wereld gezonden?", "Duizenden en tienduizenden", ["Honderden en duizenden", "Slechts enkele honderden"], ["duizenden en tienduizenden"]),
    q("c", "22", "Waarom trok Alma deze keer niet zelf ten strijde tegen de Lamanieten?", "Omdat hij letsel had opgelopen", ["Omdat hij het leger niet vertrouwde", "Omdat hij een ander plan had"], ["letsel"]),
  ),
  ch("alma", 4,
    q("a", "5", "Hoeveel zielen sloten zich in het zevende jaar bij de kerk aan?", "Ongeveer drieduizend vijfhonderd", ["Ongeveer tweeduizend vijfhonderd", "Ongeveer vijfduizend driehonderd"], ["drieduizend vijfhonderd"]),
    q("b", "17", "Wie werd aangesteld als opperrechter toen Alma de rechterstoel overdroeg?", "Nephihah", ["Helaman", "Gideon"], ["Nephihah"]),
    q("c", "18", "Welk ambt behield Alma voor zichzelf?", "Dat van hogepriester", ["Dat van legeraanvoerder", "Dat van opperrechter"], ["hogepriester"]),
  ),
  ch("alma", 5,
    q("a", "38", "Welke naam draagt de goede herder die ons roept?", "Die van Christus", ["Die van Mormon", "Die van Abinadi"], ["Christus"]),
    q("b", "3", "Door wie was Alma gewijd tot hogepriester over de kerk?", "Door zijn vader Alma", ["Door koning Mosiah", "Door de profeet Abinadi"], ["vader Alma"]),
    q("c", "52", "Wat ligt volgens de Geest aan de wortel van de boom?", "De bijl", ["De zaag", "De spade"], ["bijl"]),
  ),
  ch("alma", 6,
    q("a", "8", "In welk dal begon Alma daarna het woord van God te verkondigen?", "Het dal Gideon", ["Het dal Lemuel", "Het dal Helam"], ["dal Gideon"]),
    q("b", "2", "Wat gebeurde er met wie zich van zijn zonden bekeerde en nog niet tot de kerk behoorde?", "Ze werden gedoopt tot bekering", ["Ze werden naar Zarahemla gestuurd", "Ze moesten eerst een jaar wachten"], ["tot bekering"]),
    q("c", "6", "Waarvoor werd de kinderen van God geboden dikwijls samen te komen?", "Voor vasten en machtig gebed", ["Voor offers en brandoffers", "Voor het bouwen van tempels"], ["vasten en machtig gebed"]),
  ),
  ch("alma", 7,
    q("a", "10", "Waar zal de Heer volgens Alma worden geboren?", "In Jeruzalem", ["In Nazareth", "In Zarahemla"], ["Jeruzalem"]),
    q("b", "10", "Hoe noemt Alma de moeder van de Heer?", "Een maagd, een kostbaar en uitverkoren vat", ["Een prinses, een rijke en machtige vrouw", "Een koningin, een rijk en edel vat"], ["kostbaar en uitverkoren vat"]),
    q("c", "24", "Welke drie dingen moet men volgens Alma hebben?", "Geloof, hoop en naastenliefde", ["Geloof, bekering en offers", "Kennis, wijsheid en macht"], ["geloof, hoop en naastenliefde"]),
  ),
  ch("alma", 8,
    q("a", "3", "Naar welk land reisde Alma in het tiende regeringsjaar van de rechters?", "Het land Melek", ["Het land Gideon", "Het land Jershon"], ["land Melek"]),
    q("b", "6", "Hoe heette de stad waar Alma na drie dagen reizen ten noorden van Melek aankwam?", "Ammonihah", ["Zarahemla", "Jershon"], ["Ammonihah"]),
    q("c", "21", "Hoe heette de man die Alma in zijn huis ontving?", "Amulek", ["Amulon", "Amaleki"], ["Amulek"]),
  ),
  ch("alma", 9,
    q("a", "4", "Wat zeiden de inwoners van Ammonihah dat Alma kon profeteren zonder dat zij het zouden geloven?", "Dat de stad in één dag zou worden verwoest", ["Dat de stad door een vloed zou vergaan", "Dat de stad door de Lamanieten zou worden ingenomen"], ["in één dag"]),
    q("b", "26", "Wat zegt de engel over de komst van de Zoon van God?", "Over niet vele dagen", ["Over vele honderden jaren", "Over meer dan duizend jaar"], ["niet vele dagen"]),
    q("c", "34", "Wie trad naar voren en begon eveneens tot de mensen te prediken?", "Amulek", ["Zeëzrom", "Antionah"], ["Amulek"]),
  ),
  ch("alma", 10,
    q("a", "2", "Wie was de vader van Amulek?", "Giddonah", ["Aminadi", "Ismaël"], ["Giddonah"]),
    q("b", "7", "Wie verscheen er aan Amulek op zijn reis?", "Een engel van de Heer", ["Een profeet uit Zarahemla", "Een dienstknecht van Alma"], ["engel van de Heer"]),
    q("c", "31", "Hoe heette de belangrijkste wetgeleerde die Amulek en Alma aanklaagde?", "Zeëzrom", ["Antionah", "Korihor"], ["Zeëzrom"]),
  ),
  ch("alma", 11,
    q("a", "3", "Wat ontving een rechter als loon voor een dag?", "Een senine goud", ["Een limna goud", "Een onti zilver"], ["senine goud"]),
    q("b", "21", "Wie begon Amulek te ondervragen?", "Zeëzrom", ["Antionah", "Gideon"], ["Zeëzrom"]),
    q("c", "38-39", "Wie is volgens Amulek waarlijk de eeuwige Vader van de hemel en de aarde?", "De Zoon van God", ["De profeet Alma", "De engel van de Heer"], ["Zoon van God"]),
  ),
  ch("alma", 12,
    q("a", "20", "Wie was Antionah?", "Een hoofdregeerder", ["Een wetgeleerde", "Een legeraanvoerder"], ["hoofdregeerder"]),
    q("b", "16", "Hoe noemt Alma de tweede dood?", "Een geestelijke dood", ["Een tijdelijke dood", "Een lichamelijke dood"], ["geestelijke dood"]),
    q("c", "21", "Wat stelde God volgens het schriftgedeelte ten oosten van de hof van Eden?", "Cherubs met een vlammend zwaard", ["Een muur met een poort van goud", "Een engel met een gouden sleutel"], ["cherubs"]),
  ),
  ch("alma", 13,
    q("a", "15", "Aan wie betaalde Abraham tiende?", "Aan Melchizedek", ["Aan koning Salomo", "Aan de profeet Mozes"], ["Melchizedek"]),
    q("b", "17", "Over welk land was Melchizedek koning?", "Over het land Salem", ["Over het land Moab", "Over het land Egypte"], ["land Salem"]),
    q("c", "9", "Hoe wordt de Zoon in vers 9 genoemd?", "De Eniggeborene van de Vader", ["De Eerstgeborene van de Vader", "De Gezalfde van de Vader"], ["Eniggeborene van de Vader"]),
  ),
  ch("alma", 14,
    q("a", "16", "Naar de orde en het geloof van wie was de opperrechter van Ammonihah?", "Van Nehor", ["Van Amlici", "Van Korihor"], ["Nehor"]),
    q("b", "18", "Hoeveel dagen zaten Alma en Amulek in de gevangenis voordat de wetgeleerden kwamen?", "Drie dagen", ["Zeven dagen", "Twee dagen"], ["drie dagen"]),
    q("c", "27", "Wat gebeurde er toen Alma en Amulek de Heer om bevrijding hadden aangeroepen?", "De aarde beefde hevig", ["Er brak een brand uit", "Het begon hevig te hagelen"], ["aarde beefde hevig"]),
  ),
  ch("alma", 15,
    q("a", "1", "Naar welk land gingen Alma en Amulek nadat zij uit Ammonihah waren vertrokken?", "Het land Sidom", ["Het land Melek", "Het land Nephi"], ["land Sidom"]),
    q("b", "3", "Waaraan leed Zeëzrom in Sidom?", "Een brandende koorts", ["Een zware verwonding", "Een ernstige blindheid"], ["brandende koorts"]),
    q("c", "12", "Wat deed Alma met Zeëzrom nadat hij was genezen?", "Hij doopte hem tot de Heer", ["Hij zond hem terug naar Ammonihah", "Hij liet hem de kerk verlaten"], ["doopte"]),
  ),
  ch("alma", 16,
    q("a", "5", "Hoe heette de opperbevelhebber van de legers van de Nephieten?", "Zoram", ["Moroni", "Gideon"], ["Zoram"]),
    q("b", "10", "Wat gebeurde er volgens Alma 16 met de stad Ammonihah?", "Ze werd in één dag woest achtergelaten", ["Ze werd geleidelijk door de Lamanieten bezet", "Ze werd door een aardbeving verzwolgen"], ["in één dag"]),
    q("c", "19", "Wat verkondigden de priesters over de Zoon van God?", "Zijn lijden en dood", ["Zijn rijkdom en macht", "Zijn huwelijk en gezin"], ["lijden en dood"]),
  ),
  ch("alma", 17,
    q("a", "4", "Hoeveel jaar hadden de zonen van Mosiah het woord onder de Lamanieten geleerd?", "Veertien jaar", ["Veertig jaar", "Zeven jaar"], ["veertien jaar"]),
    q("b", "21", "Hoe heette de koning van het land Ismaël?", "Lamoni", ["Limhi", "Laman"], ["Lamoni"]),
    q("c", "38", "Hoeveel mannen van de Lamanieten werden er met Ammons slinger neergeslagen?", "Zes mannen", ["Vier mannen", "Acht mannen"], ["zes"]),
  ),
  ch("alma", 18,
    q("a", "13", "Wat betekent het woord Rabbanah?", "Machtige of grote koning", ["Wijze en machtige heer", "Dappere legeraanvoerder"], ["grote koning"]),
    q("b", "43", "Hoe lang lag koning Lamoni als dood op zijn bed?", "Twee dagen en twee nachten", ["Drie dagen en drie nachten", "Eén dag en één nacht"], ["twee dagen en twee nachten"]),
    q("c", "9", "Wat deed Ammon toen de koning naar hem vroeg?", "Hij voederde de paarden van de koning", ["Hij vierde feest met de dienstknechten", "Hij sliep in de tent van de koning"], ["paarden"]),
  ),
  ch("alma", 19,
    q("a", "8", "Wat zei Ammon over koning Lamoni toen hij naar hem keek?", "Hij is niet dood, maar slaapt in God", ["Hij is gewond en moet rusten bij het vuur", "Hij is ziek en heeft een arts nodig"], ["slaapt in God"]),
    q("b", "13", "Wat zei Lamoni toen hij weer opstond?", "Dat hij zijn Verlosser had gezien", ["Dat hij een groot leger had gezien", "Dat hij zijn vader had gezien"], ["Verlosser"]),
    q("c", "28", "Wie had de menigte bijeen laten komen?", "Een Lamanitische dienstmaagd", ["Een dochter van de koning", "Een priester van het volk"], ["dienstmaagd"]),
  ),
  ch("alma", 20,
    q("a", "3", "In welk land zaten Ammons broeders in de gevangenis?", "Het land Middoni", ["Het land Ismaël", "Het land Sidom"], ["Middoni"]),
    q("b", "10", "Wat noemt de vader van Lamoni de Nephiet Ammon?", "Een van de kinderen van een leugenaar", ["Een van de zonen van een koning", "Een van de dienaren van de duivel"], ["kinderen van een leugenaar"]),
    q("c", "23", "Wat bood de oude koning Ammon aan als hij hem spaarde?", "De helft van het koninkrijk", ["Een derde van zijn schatten", "Zijn oudste dochter als vrouw"], ["helft van het koninkrijk"]),
  ),
  ch("alma", 21,
    q("a", "2", "Welke stad bouwden de Lamanieten, de Amalekieten en het volk van Amulon?", "Een grote stad die Jeruzalem heette", ["Een grote stad die Nephi heette", "Een grote stad die Zarahemla heette"], ["Jeruzalem"]),
    q("b", "14", "Door wie werden Aäron en zijn broeders uit de gevangenis bevrijd?", "Door Lamoni en Ammon", ["Door Mosiah en Alma", "Door Omner en Himni"], ["Lamoni", "Ammon"]),
    q("c", "22", "Wat verkondigde koning Lamoni zijn volk over het aanbidden van de Heer?", "Dat zij vrij waren de Heer te aanbidden waar zij wilden", ["Dat zij alleen in de synagogen mochten aanbidden", "Dat zij uitsluitend de koning mochten aanbidden"], ["aanbidden"]),
  ),
  ch("alma", 22,
    q("a", "3", "Wat beloofden Aäron en zijn broeders de koning in ruil voor hun leven?", "Dat zij zijn dienstknechten zouden zijn", ["Dat zij hem hun bezittingen zouden geven", "Dat zij het land zouden verlaten"], ["dienstknechten"]),
    q("b", "7", "Wat zeggen de Amalekieten volgens de koning over God?", "Dat er een God is", ["Dat er twee goden zijn", "Dat er geen God is"], ["een God"]),
    q("c", "17", "Wat deed de koning toen Aäron zijn woorden had gesproken?", "Hij knielde en wierp zich ter aarde", ["Hij stond op en verliet de zaal", "Hij riep zijn lijfwacht bijeen"], ["ter aarde"]),
  ),
  ch("alma", 23,
    q("a", "17", "Hoe noemden de bekeerde Lamanieten zich?", "Anti-Nephi-Lehieten", ["Nephi-Lamanieten", "Lehi-Nephieten"], ["Anti-Nephi-Lehieten"]),
    q("b", "1", "Wat gebood de koning van de Lamanieten zijn volk over Ammon en zijn broeders?", "Dat niemand de handen aan hen mocht slaan", ["Dat zij het land moesten verlaten", "Dat zij alleen in Ismaël mochten prediken"], ["handen"]),
    q("c", "14", "Welke groepen bekeerden zich niet?", "De Amalekieten en de Amulonieten", ["De Nephieten van Zarahemla", "Het volk van Ismaël en Middoni"], ["Amalekieten", "Amulonieten"]),
  ),
  ch("alma", 24,
    q("a", "3", "Welke naam gaf de koning aan zijn zoon aan wie hij het koninkrijk overdroeg?", "Anti-Nephi-Lehi", ["Anti-Lehi-Nephi", "Nephi-Anti-Lehi"], ["Anti-Nephi-Lehi"]),
    q("b", "16", "Wat zouden zij volgens de koning met hun zwaarden doen als hun broeders hen wilden vernietigen?", "Ze diep in de grond begraven", ["Ze omsmelten tot gereedschap", "Ze aan de Nephieten schenken"], ["diep in de grond"]),
    q("c", "22", "Hoeveel van hen werden zonder tegenstand door de Lamanieten gedood?", "Duizend en vijf", ["Duizend en tien", "Vijfhonderd en vijf"], ["duizend en vijf"]),
  ),
  // ===== EINDE =====
];
