import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 4 Nephi, Mormon, Ether en Moroni. Elk feit is gebonden aan de verzen in `verses`;
// `npm run genees:check` controleert dat.
export const slot: GeneesChapterSeed[] = [
  ch("4-ne", 1,
    q("a", "3", "Wat hadden de mensen na hun bekering onder zich?", "Alle dingen gemeenschappelijk", ["Alle dingen als privébezit", "Alle dingen onder de rechters"], ["gemeenschappelijk"]),
    q("b", "17", "Hoe waren de mensen volgens vers 17 geworden?", "Eén, kinderen van Christus", ["Verdeeld in vele standen", "Gescheiden in Nephieten en Lamanieten"], ["kinderen van Christus"]),
    q("c", "48", "Wie verborg de kronieken in de hoede van de Heer?", "Ammaron", ["Mormon", "Moroni"], ["Ammaron"]),
  ),
  ch("morm", 1,
    q("a", "2", "Hoe oud was Mormon toen Ammaron tot hem kwam?", "Ongeveer tien jaar", ["Ongeveer veertien jaar", "Ongeveer zeven jaar"], ["tien jaar"]),
    q("b", "3", "Wanneer moest Mormon volgens Ammaron terugdenken aan wat hij had waargenomen?", "Als hij ongeveer vierentwintig was", ["Als hij ongeveer dertig jaar oud was", "Als hij ongeveer achttien was"], ["vierentwintig"]),
    q("c", "15", "Hoe oud was Mormon toen de Heer tot hem kwam?", "Vijftien jaar", ["Twaalf jaar", "Twintig jaar"], ["vijftien jaar"]),
  ),
  ch("morm", 2,
    q("a", "2", "In welk jaar van zijn leven voerde Mormon een leger aan?", "Zestien", ["Achttien", "Twintig"], ["zestien"]),
    q("b", "9", "Hoe heette de koning van de Lamanieten die met een groot leger aanviel?", "Aäron", ["Lamoni", "Ammoron"], ["Aäron"]),
    q("c", "29", "Wat gaven de Lamanieten aan de Nephieten in het verdrag?", "Het noordelijke land", ["Het zuidelijke land", "Het land Zarahemla"], ["noordelijke land"]),
  ),
  ch("morm", 3,
    q("a", "11", "Wat weigerde Mormon omwille van hun goddeloosheid voortaan te zijn?", "Hun commandant en leider", ["Hun koning en rechter", "Hun priester en leraar"], ["commandant"]),
    q("b", "13", "Hoe vaak had Mormon zijn volk uit de handen van hun vijanden bevrijd?", "Driemaal", ["Tweemaal", "Zevenmaal"], ["driemaal"]),
    q("c", "17", "Aan wie schrijft Mormon volgens vers 17?", "Aan de andere volken en het huis van Israël", ["Alleen aan de Nephieten van zijn eigen tijd", "Aan de koning en zijn legeraanvoerders"], ["andere volken", "huis van Israël"]),
  ),
  ch("morm", 4,
    q("a", "2", "Naar welk land werden de legers van de Nephieten teruggedreven?", "Het land Woestenij", ["Het land Jershon", "Het land Zarahemla"], ["Woestenij"]),
    q("b", "5", "Door wie worden de goddelozen volgens Mormon gestraft?", "Door de goddelozen", ["Door de engelen", "Door de rechtvaardigen"], ["goddelozen"]),
    q("c", "23", "Waarheen ging Mormon toen de Lamanieten het land ten val dreigden te brengen?", "Naar de heuvel Shim", ["Naar de heuvel Manti", "Naar de heuvel Riplah"], ["heuvel Shim"]),
  ),
  ch("morm", 5,
    q("a", "17", "Wie hadden de Nephieten eens als hun Herder?", "Christus als hun Herder", ["Mozes als hun Herder", "Nephi als hun Herder"], ["Christus als hun Herder"]),
    q("b", "18", "Waarmee wordt het volk vergeleken dat door Satan wordt geleid?", "Met kaf dat voor de wind wordt gedreven", ["Met een schaap dat van de kudde dwaalt", "Met stof dat op de bergen ligt"], ["kaf"]),
    q("c", "22", "Wat vraagt Mormon aan de andere volken?", "Hoe zij tegenover Gods macht standhouden", ["Hoe zij het land kunnen bewaren", "Hoe zij hun rijkdom kunnen vergroten"], ["standhouden"]),
  ),
  ch("morm", 6,
    q("a", "4", "Naar welk land marcheerden de Nephieten om zich te verzamelen?", "Het land Cumorah", ["Het land Moroni", "Het land Jozua"], ["Cumorah"]),
    q("b", "11", "Hoeveel van Mormons volk bleven er over na de slag?", "Vierentwintig", ["Zevenentwintig", "Eenentwintig"], ["vierentwintig"]),
    q("c", "3", "Hoe reageerde de koning van de Lamanieten op Mormons verzoek?", "Hij stemde in met het verzoek", ["Hij weigerde het verzoek", "Hij liet de brief verbranden"], ["verzoek"]),
  ),
  ch("morm", 7,
    q("a", "2", "Van welk huis is het overblijfsel van het volk volgens Mormon?", "Het huis van Israël", ["Het huis van Juda", "Het huis van David"], ["huis van Israël"]),
    q("b", "4", "Wat moeten zij volgens Mormon neerleggen?", "Hun oorlogswapens", ["Hun gouden afgoden", "Hun zilveren schatten"], ["oorlogswapens"]),
    q("c", "8", "In wiens naam moeten zij zich volgens Mormon laten dopen?", "In de naam van Jezus", ["In de naam van Mormon", "In de naam van Nephi"], ["naam van Jezus"]),
  ),
  ch("morm", 8,
    q("a", "1", "Wie beëindigt de kroniek van Mormon?", "Moroni", ["Nephi", "Helaman"], ["Moroni"]),
    q("b", "6", "Hoeveel jaar was er verstreken sinds de komst van Christus?", "Vierhonderd jaar", ["Driehonderd jaar", "Vijfhonderd jaar"], ["vierhonderd jaar"]),
    q("c", "23", "Welke profetieën moet men volgens Moroni onderzoeken?", "De profetieën van Jesaja", ["De profetieën van Jeremia", "De profetieën van Mozes"], ["Jesaja"]),
  ),
  ch("morm", 9,
    q("a", "9", "Hoe is God volgens Mormon?", "Dezelfde gisteren, heden en voor eeuwig", ["Veranderlijk, naar de tijden en de volken", "Alleen aanwezig in de tempel"], ["gisteren, heden en voor eeuwig"]),
    q("b", "32", "Welke lettertekens gebruikten Mormon en Moroni voor hun kroniek?", "Hervormd-Egyptisch", ["Oud-Hebreeuws", "Aramees-Syrisch"], ["Hervormd-Egyptisch"]),
    q("c", "21", "Wat belooft Moroni aan wie in Christus gelooft zonder te twijfelen?", "Wat hij de Vader ook in Christus' naam vraagt", ["Een vrijstelling van alle beproevingen", "Een plaats in elk koninkrijk van de aarde"], ["Vader"]),
  ),
  // ===== EINDE =====
];
