import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 1 Nefi (edición en español). Cada hecho está ligado a los versículos indicados en `verses`; `npm run genees:check` lo verifica.
export const nephi1: GeneesChapterSeed[] = [
  ch("1-ne", 1,
    q("a", "5-6", "¿Qué apareció ante Lehi, sobre una roca, mientras oraba al Señor?", "Un pilar de fuego", ["Una nube blanca", "Una estrella brillante"], ["pilar de fuego"]),
    q("b", "4", "¿En el primer año del reinado de qué rey de Judá llegaron muchos profetas?", "El rey Sedequías", ["El rey Josías", "El rey Joaquín"], ["Sedequías"]),
    q("c", "11", "¿Qué le dio a Lehi, en su visión, el primero de los doce que vio?", "Un libro", ["Una vara", "Una espada"], ["libro"]),
  ),
  ch("1-ne", 2,
    q("a", "2", "¿Qué le mandó el Señor a Lehi que hiciera, en un sueño?", "Partir para el desierto con su familia", ["Huir a Babilonia con su familia", "Ir en barco al sur con su familia"], ["desierto"]),
    q("b", "8", "¿Qué nombre le dio Lehi al río que desaguaba en el mar Rojo?", "El río Lamán", ["El río Sam", "El río Jordán"], ["Lamán"]),
    q("c", "20", "¿Qué le prometió el Señor a Nefi si guardaba sus mandamientos?", "Que sería conducido a una tierra de promisión", ["Que en tres días volvería a Jerusalén", "Que con sus hermanos edificaría una gran ciudad"], ["tierra de promisión"]),
  ),
  ch("1-ne", 3,
    q("a", "3", "¿Sobre qué estaban grabados los anales de los judíos que tenía Labán?", "Sobre planchas de bronce", ["Sobre planchas de oro", "Sobre tablas de piedra"], ["planchas de bronce"]),
    q("b", "11", "¿Quién fue el primero en entrar en la casa de Labán después de echar suertes?", "Lamán", ["Lemuel", "Nefi"], ["Lamán"]),
    q("c", "29", "¿Quién apareció cuando Lamán y Lemuel golpeaban con una vara a sus hermanos menores?", "Un ángel del Señor", ["Un siervo de Labán", "Un profeta de Jerusalén"], ["ángel del Señor"]),
  ),
  ch("1-ne", 4,
    q("a", "18", "¿Con qué mató Nefi a Labán?", "Con su propia espada", ["Con una lanza de bronce", "Con un pesado garrote"], ["propia espada"]),
    q("b", "35", "¿Cómo se llamaba el siervo de Labán?", "Zoram", ["Zera", "Zenós"], ["Zoram"]),
    q("c", "7", "¿En qué estado encontró Nefi a Labán?", "Estaba ebrio de vino", ["Había caído enfermo", "Estaba herido en una pelea"], ["ebrio de vino"]),
  ),
  ch("1-ne", 5,
    q("a", "11", "¿Qué contenían, entre otras cosas, las planchas de bronce cuando Lehi las examinó?", "Los cinco libros de Moisés", ["Los salmos del rey David", "Las leyes del rey Salomón"], ["cinco libros de Moisés"]),
    q("b", "14", "¿De cuál de los hijos de Jacob descendía Lehi?", "José", ["Rubén", "Leví"], ["José"]),
    q("c", "2", "¿Qué le reprochó Saríah a su esposo cuando sus hijos no regresaban?", "Que era un hombre visionario", ["Que llevó pocas provisiones", "Que tomó el camino equivocado"], ["visionario"]),
  ),
  ch("1-ne", 6,
    q("a", "4", "¿A qué Dios desea Nefi persuadir a los hombres que vengan?", "Al Dios de Abraham, de Isaac y de Jacob", ["Al Dios de Adán, de Noé y de Moisés", "Al Dios de Enoc, de David y de Salomón"], ["Dios de Abraham", "Isaac", "Jacob"]),
    q("b", "5", "¿Qué cosas no escribe Nefi en sus planchas?", "Las cosas que agradan al mundo", ["Las cosas que solo hablan de sus hermanos", "Las cosas que solo hablan de guerras"], ["agradan al mundo"]),
    q("c", "1", "¿Dónde se encuentra la genealogía de los padres de Nefi?", "En los anales que llevó su padre Lehi", ["En las planchas que Nefi está escribiendo ahora", "En los anales del profeta Jeremías"], ["anales", "padre"]),
  ),
  ch("1-ne", 7,
    q("a", "2", "¿A quién debían llevar Nefi y sus hermanos desde Jerusalén?", "A Ismael y su familia", ["A Jeremías y su familia", "A Sedequías y su familia"], ["Ismael"]),
    q("b", "16", "¿Qué hicieron Lamán y Lemuel con Nefi después de que él les habló?", "Lo ataron con cuerdas", ["Lo golpearon con una vara", "Lo encerraron en una cueva"], ["ataron con cuerdas"]),
    q("c", "21", "¿Qué hizo Nefi cuando sus hermanos le pidieron perdón?", "Les perdonó de todo corazón lo hecho", ["Les exigió que entregaran sus espadas", "Les hizo ayunar primero durante un día"], ["perdon"]),
  ),
  ch("1-ne", 8,
    q("a", "19", "¿De qué era la barra que se extendía por la orilla del río hacia el árbol?", "De hierro", ["De madera", "De bronce"], ["hierro"]),
    q("b", "12", "¿Qué le sucedió a Lehi cuando comió del fruto del árbol?", "Su alma se llenó de un gozo inmenso", ["Su cuerpo se curó de todo cansancio", "Su corazón se llenó de gran tristeza por Lamán"], ["gozo inmenso"]),
    q("c", "26", "¿Dónde estaba el edificio grande y espacioso que vio Lehi?", "Muy alto en el aire, sobre la tierra", ["En lo profundo de un valle junto al río", "En la cima de una montaña con árboles"], ["en el aire"]),
  ),
  ch("1-ne", 9,
    q("a", "3-4", "¿De qué tratan principalmente las planchas en las que Nefi escribe ahora?", "Del ministerio entre su propio pueblo", ["Del reinado de los reyes y de las guerras", "Del viaje de su familia a través del mar"], ["ministerio"]),
    q("b", "1", "¿En qué valle vivía Lehi en una tienda cuando vio todas estas cosas?", "En el valle de Lemuel", ["En el valle de Lamán", "En el valle de Zoram"], ["valle de Lemuel"]),
    q("c", "5", "¿Por qué le mandó el Señor a Nefi hacer estas planchas?", "Para un sabio propósito que Nefi desconocía", ["Porque las otras planchas se habían perdido", "Porque Lehi mismo se lo había pedido"], ["sabio propósito"]),
  ),
  ch("1-ne", 10,
    q("a", "4", "¿Cuántos años después de que Lehi saliera de Jerusalén vendría el Mesías según su profecía?", "Seiscientos años", ["Trescientos años", "Novecientos años"], ["seiscientos años"]),
    q("b", "9", "¿Dónde bautizaría el profeta que prepararía el camino del Señor?", "En Betábara, del otro lado del Jordán", ["En Jerusalén, junto al templo del Señor", "En Nazaret, a orillas del mar Rojo"], ["Betábara"]),
    q("c", "12", "¿Con qué comparó Lehi a la casa de Israel?", "Con un olivo", ["Con una vid", "Con una higuera"], ["olivo"]),
  ),
  ch("1-ne", 11,
    q("a", "1", "¿Adónde fue llevado Nefi en el Espíritu del Señor?", "A una montaña extremadamente alta", ["A una llanura extensa junto al mar", "A un valle lleno de árboles maduros"], ["montaña extremadamente alta"]),
    q("b", "18", "¿Quién es la virgen que vio Nefi, según el ángel?", "La madre del Hijo de Dios", ["La hermana del profeta Jeremías", "La esposa del rey de Judá"], ["madre del Hijo de Dios"]),
    q("c", "22", "¿De qué es símbolo el árbol según Nefi?", "Del amor de Dios por los hombres", ["De la sabiduría del gran mundo", "Del poder de un reino fuerte"], ["amor de Dios"]),
  ),
  ch("1-ne", 12,
    q("a", "1", "¿Con qué se compara el número de la descendencia de Nefi?", "Con la arena de la orilla del mar", ["Con las estrellas del cielo", "Con las hojas de los árboles"], ["arena"]),
    q("b", "7-8", "¿Cuántos discípulos del Cordero fueron escogidos para ministrar a la descendencia de Nefi?", "Doce discípulos", ["Siete discípulos", "Setenta discípulos"], ["doce"]),
    q("c", "17", "¿Qué representan los vapores de tinieblas según el ángel?", "Las tentaciones del diablo", ["Las dificultades del viaje", "Las dudas de los creyentes"], ["tentaciones del diablo"]),
  ),
  ch("1-ne", 13,
    q("a", "23", "¿Qué contiene el libro que sale de la boca de un judío, según el ángel?", "Los convenios del Señor con la casa de Israel", ["Las leyes de todos los pueblos de la tierra", "La historia de los reyes de Egipto"], ["convenios", "casa de Israel"]),
    q("b", "12", "¿Adónde fue el hombre entre los gentiles que fue movido por el Espíritu de Dios?", "Sobre las muchas aguas hasta la tierra prometida", ["Por el desierto hasta la ciudad de Jerusalén", "Por las montañas hasta la tierra de Egipto"], ["muchas aguas", "tierra prometida"]),
    q("c", "37", "¿Qué tendrán los que procuren establecer Sion en los últimos días?", "El don y el poder del Espíritu Santo", ["La riqueza y el honor del mundo", "La sabiduría y la autoridad de los reyes"], ["don y el poder del Espíritu Santo"]),
  ),
  ch("1-ne", 14,
    q("a", "27", "¿Cómo se llamaba el apóstol del Cordero que escribiría esas cosas?", "Juan", ["Pedro", "Mateo"], ["Juan"]),
    q("b", "10", "¿Cuántas iglesias hay según el ángel?", "Solamente dos", ["Solamente cuatro", "Solamente siete"], ["dos"]),
    q("c", "12", "¿Cómo era el número de miembros de la iglesia del Cordero de Dios en la visión de Nefi?", "Pocos, pero extendidos por toda la tierra", ["Muchos, pero limitados a un solo país", "Tan grande como el de la otra iglesia"], ["pocos"]),
  ),
  ch("1-ne", 15,
    q("a", "24", "¿Qué significaba la barra de hierro según Nefi?", "La palabra de Dios", ["La ley de Moisés", "El poder de un rey"], ["palabra de Dios"]),
    q("b", "8-9", "¿Qué no habían hecho Lamán y Lemuel para entender las palabras de su padre?", "Preguntar al Señor lo que significaban", ["Ofrecer un sacrificio sobre un altar", "Consultar las planchas de bronce"], ["pregunta"]),
    q("c", "18", "¿Con qué antepasado hizo el Señor el convenio que se cumplirá en los postreros días?", "Con Abraham", ["Con Enoc", "Con Salomón"], ["Abraham"]),
  ),
  ch("1-ne", 16,
    q("a", "10", "¿De qué material era la esfera de hábil factura que Lehi encontró a la entrada de su tienda?", "De bronce fino", ["De oro puro", "De acero templado"], ["bronce fino"]),
    q("b", "13", "¿Qué nombre dio la familia al lugar donde asentó sus tiendas después de cuatro días de camino?", "Shazer", ["Lemuel", "Jershón"], ["Shazer"]),
    q("c", "18", "¿Qué sucedió cuando Nefi salió a cazar alimento?", "Se le quebró su arco de acero fino", ["Se le acabaron todas las flechas", "Se perdió en el desierto"], ["arco", "acero"]),
  ),
  ch("1-ne", 17,
    q("a", "5", "¿Qué nombre dieron al mar que vieron y qué significa?", "Irreántum, que significa muchas aguas", ["Abundancia, que significa muchos frutos", "Shazer, que significa aguas rojas"], ["Irreántum", "muchas aguas"]),
    q("b", "4", "¿Cuántos años permaneció la familia en el desierto?", "Ocho años", ["Cuatro años", "Doce años"], ["ocho años"]),
    q("c", "11", "¿De qué hizo Nefi un fuelle para avivar el fuego?", "De pieles de animales", ["De lana de oveja", "De corteza de árbol"], ["pieles de animales"]),
  ),
  ch("1-ne", 18,
    q("a", "7", "¿Cómo se llamaban los dos hijos que Lehi engendró en el desierto?", "Jacob y José", ["Enós y Jarom", "Zoram y Sam"], ["Jacob", "José"]),
    q("b", "12", "¿Qué le sucedió a la brújula después de que ataron a Nefi?", "Dejó de funcionar por completo", ["Señalaba hacia el lado equivocado", "Se perdió durante la tormenta"], ["funcionar"]),
    q("c", "15", "¿Cuántos días fueron arrojados hacia atrás sobre las aguas cuando los hermanos de Nefi empezaron a ver los juicios de Dios?", "Cuatro días", ["Dos días", "Siete días"], ["cuatro días"]),
  ),
  ch("1-ne", 19,
    q("a", "1", "¿De qué hizo Nefi las planchas en las que grabó la historia de su pueblo?", "De metal", ["De madera", "De piedra"], ["metal"]),
    q("b", "12", "¿Qué profeta dice que el Dios de la naturaleza padece?", "Zenós", ["Zenoc", "Neum"], ["Zenós"]),
    q("c", "23", "¿Qué profeta les leyó Nefi a sus hermanos para convencerlos de que creyeran en el Señor?", "El profeta Isaías", ["El profeta Jeremías", "El profeta Ezequiel"], ["Isaías"]),
  ),
  ch("1-ne", 20,
    q("a", "4", "¿De qué es la frente del pueblo de Israel, según el Señor?", "De bronce", ["De piedra", "De oro"], ["bronce"]),
    q("b", "18", "¿A qué habría sido semejante la rectitud de Israel si hubiera obedecido los mandamientos?", "A las ondas del mar", ["A las montañas de Judá", "A las estrellas del cielo"], ["ondas del mar"]),
    q("c", "20", "¿De dónde debía salir el pueblo según el Señor?", "De la ciudad de Babilonia", ["De la tierra de Egipto", "De la ciudad de Nínive"], ["Babilonia"]),
  ),
  ch("1-ne", 21,
    q("a", "16", "¿Dónde dice el Señor que tiene grabada a la casa de Israel?", "En las palmas de sus manos", ["En una tabla de piedra", "En los muros del templo"], ["palmas"]),
    q("b", "6", "¿Qué papel tendrá el siervo del Señor para los gentiles?", "Será una luz para ellos", ["Será un juez para ellos", "Será un rey para ellos"], ["luz"]),
    q("c", "14", "¿Qué dijo Sion acerca del Señor?", "Que el Señor la había abandonado", ["Que el Señor nunca la perdonaría", "Que el Señor la había hecho reina"], ["abandon"]),
  ),
  ch("1-ne", 22,
    q("a", "20-21", "¿Quién era el profeta de quien habló Moisés, según Nefi?", "El Santo de Israel", ["Isaías, hijo de Amoz", "Lehi, el padre de Nefi"], ["Santo de Israel"]),
    q("b", "25", "¿Cuántos rediles y pastores habrá cuando el Señor reúna a sus hijos?", "Habrá un redil y un pastor", ["Habrá doce rediles y doce pastores", "Habrá siete rediles y un pastor"], ["un redil y un pastor"]),
    q("c", "30", "¿De qué testifican las cosas escritas en las planchas de bronce, según Nefi?", "Que el hombre debe ser obediente a los mandamientos de Dios", ["Que el hombre debe dar sus bienes a los pobres", "Que cada siete días se debe sacrificar en el templo"], ["mandamientos de Dios"]),
  ),
  // ===== EINDE =====
];
