import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 2 Nefi (edición en español). Cada hecho está ligado a los versículos indicados en `verses`; `npm run genees:check` lo verifica.
export const nephi2: GeneesChapterSeed[] = [
  ch("2-ne", 1,
    q("a", "6", "¿Quién puede venir a la tierra de promisión, según Lehi?", "Solo quien sea traído por la mano del Señor", ["Solo quien pueda construir un barco propio", "Solo quien tenga permiso del rey"], ["mano del Señor"]),
    q("b", "30", "¿Quién era el siervo de Labán a quien Lehi llamó amigo fiel de Nefi?", "Zoram", ["Jacob", "Ismael"], ["Zoram"]),
    q("c", "13", "¿De qué debían despertar sus hijos, según Lehi?", "De un profundo sueño", ["De un largo viaje", "De una grave enfermedad"], ["profundo sueño"]),
  ),
  ch("2-ne", 2,
    q("a", "25", "¿Para qué existen los hombres, según Lehi?", "Para que puedan tener gozo", ["Para que gobiernen la tierra", "Para que adquieran riquezas"], ["gozo"]),
    q("b", "16", "¿Qué le concedió el Señor Dios al hombre?", "Obrar por sí mismo", ["Vivir sin ninguna ley", "Fundar su propio reino"], ["por sí mismo"]),
    q("c", "19", "¿Para qué fueron echados Adán y Eva del Jardín de Edén?", "Para cultivar la tierra", ["Para fundar una nueva ciudad", "Para vivir siete años aislados"], ["cultivar la tierra"]),
  ),
  ch("2-ne", 3,
    q("a", "17", "¿En qué dijo el Señor que daría poder al Moisés que levantaría, según la profecía de José?", "En una vara", ["En una espada", "En un rollo"], ["vara"]),
    q("b", "6", "¿Qué levantaría el Señor para los del fruto de los lomos de José, según su testimonio?", "Un vidente escogido", ["Un rey muy poderoso", "Un juez recto y justo"], ["vidente"]),
    q("c", "1", "¿Qué lugar ocupaba José, a quien habló Lehi, entre los hijos de Lehi?", "Era su postrer hijo", ["Era su primer hijo", "Era su segundo hijo"], ["postrer"]),
  ),
  ch("2-ne", 4,
    q("a", "12", "¿Qué le sucedió a Lehi después de hablar a todos los de su casa?", "Murió y fue sepultado", ["Enfermó y se retiró", "Fue llevado al cielo"], ["murió"]),
    q("b", "11", "¿A qué hijo le dio Lehi la tierra por herencia, igual que a Nefi?", "A su hijo Sam", ["A su hijo Lamán", "A su hijo José"], ["Sam"]),
    q("c", "15", "¿En qué se deleita el alma de Nefi, según escribe?", "En las Escrituras de las planchas", ["En las guerras contra sus enemigos", "En las riquezas de toda la tierra"], ["Escrituras"]),
  ),
  ch("2-ne", 5,
    q("a", "28", "¿Cuántos años habían transcurrido desde que salieron de Jerusalén?", "Treinta años", ["Veinte años", "Cincuenta años"], ["treinta años"]),
    q("b", "16", "¿Según el modelo de qué templo edificó Nefi un templo?", "El templo de Salomón", ["El templo de Moisés", "El templo de Sedequías"], ["templo de Salomón"]),
    q("c", "26", "¿A quiénes consagró Nefi para ser sacerdotes y maestros sobre el pueblo?", "A Jacob y a José", ["A Sam y a Zoram", "A Lamán y a Lemuel"], ["Jacob", "José"]),
  ),
  ch("2-ne", 6,
    q("a", "4", "¿Qué profeta les leyó Jacob al pueblo?", "Isaías", ["Jeremías", "Moisés"], ["Isaías"]),
    q("b", "2", "¿Por quién había sido consagrado Jacob?", "Por su hermano Nefi", ["Por su padre Lehi", "Por el rey de Judá"], ["Nefi"]),
    q("c", "14", "¿Cuántas veces se dispondrá el Mesías a recuperar a su pueblo, según Jacob?", "Por segunda vez", ["Por tercera vez", "Por séptima vez"], ["segunda vez"]),
  ),
  ch("2-ne", 7,
    q("a", "8", "¿Con qué herirá el Señor a su adversario?", "Con la fuerza de su boca", ["Con una espada afilada de acero", "Con el fuego del cielo"], ["boca"]),
    q("b", "7", "¿Con qué comparó el Señor su rostro?", "Con un pedernal muy duro", ["Con una roca en el mar", "Con un escudo de acero"], ["pedernal"]),
    q("c", "3", "¿De qué viste el Señor los cielos?", "De obscuridad", ["De luz blanca", "De llamas rojas"], ["obscuridad"]),
  ),
  ch("2-ne", 8,
    q("a", "2", "¿A qué padre y madre debe mirar el pueblo, según Isaías?", "A Abraham y a Sara", ["A Isaac y a Rebeca", "A Jacob y a Raquel"], ["Abraham", "Sara"]),
    q("b", "3", "¿En qué convertirá el Señor el desierto de Sion?", "En un nuevo Edén", ["En una nueva Betel", "En el monte Sinaí"], ["Edén"]),
    q("c", "1", "¿De dónde fue cortado el pueblo que sigue la rectitud, según Isaías?", "De la roca", ["Del río Jordán", "Del desierto"], ["roca"]),
  ),
  ch("2-ne", 9,
    q("a", "10", "¿Cómo llama Jacob a la muerte y al infierno?", "Un terrible monstruo", ["Una muralla invencible", "Un abismo sin fondo ni fin"], ["monstruo"]),
    q("b", "41", "¿Quién es el guardián de la puerta del camino angosto, según Jacob?", "El Santo de Israel", ["El profeta Isaías", "El ángel del Señor"], ["Santo de Israel"]),
    q("c", "25", "¿Qué hay, según Jacob, donde no se ha dado ninguna ley?", "No hay castigo", ["No hay redención", "No hay esperanza"], ["castigo"]),
  ),
  ch("2-ne", 10,
    q("a", "3", "¿Qué nombre tendría el Mesías según el ángel?", "Cristo", ["Emanuel", "Josué"], ["Cristo"]),
    q("b", "11", "¿Quiénes no habrá en esta tierra de libertad, según el Señor?", "Reyes que se levanten sobre los gentiles", ["Sacerdotes que sirvan a diario en el templo", "Labradores que cultiven la tierra con sus manos"], ["reyes"]),
    q("c", "23", "¿Entre qué dos caminos pueden escoger los hombres, según Jacob?", "La muerte interminable o la vida eterna", ["La riqueza o la pobreza en la tierra prometida", "La guerra o la paz con el pueblo de Lamán"], ["muerte interminable", "vida eterna"]),
  ),
  ch("2-ne", 11,
    q("a", "2", "¿De quién escribe Nefi más palabras?", "De Isaías", ["De Jeremías", "De Zenós"], ["Isaías"]),
    q("b", "7", "¿Qué dice Nefi que ocurre si no hay Cristo?", "Que entonces no hay Dios", ["Que entonces no hay templo", "Que entonces no hay profeta"], ["no hay Dios"]),
    q("c", "4", "¿Para qué se ha dado la ley de Moisés, según Nefi?", "Para probar la venida de Cristo", ["Para liberar al pueblo de Egipto", "Para construir el templo de Jerusalén"], ["venida de Cristo"]),
  ),
  ch("2-ne", 12,
    q("a", "4", "¿En qué forjarán sus espadas las naciones, según Isaías?", "En rejas de arado", ["En escudos pesados", "En ollas de cocina"], ["rejas de arado"]),
    q("b", "2", "¿Cómo estará establecido el monte de la casa del Señor en los postreros días?", "Como cabeza de los montes", ["En el valle más profundo de Judá", "A orillas del gran mar"], ["cabeza de los montes"]),
    q("c", "7", "¿De qué estaba llena la tierra de Judá, según Isaías?", "De plata y oro", ["De trigo y aceite", "De ovejas y cabras"], ["plata y oro"]),
  ),
  ch("2-ne", 13,
    q("a", "16", "¿Por qué castigará el Señor a las hijas de Sion?", "Porque se han vuelto altivas", ["Porque no santifican el día de reposo", "Porque han abandonado el templo"], ["altivas"]),
    q("b", "9", "¿Con qué ciudad compara Isaías el pecado de Judá?", "Con Sodoma", ["Con Babilonia", "Con Nínive"], ["Sodoma"]),
    q("c", "10", "¿Qué comerán los justos, según Isaías?", "El fruto de sus obras", ["El pan del rey", "El botín del enemigo"], ["fruto de sus obras"]),
  ),
  ch("2-ne", 14,
    q("a", "1", "¿Cuántas mujeres echarán mano de un hombre en aquel día, según Isaías?", "Siete mujeres", ["Doce mujeres", "Cinco mujeres"], ["siete"]),
    q("b", "5", "¿Qué creará el Señor de noche sobre el monte de Sion?", "Un resplandor de fuego y llamas", ["Una gran nube oscura de polvo", "Una lluvia de estrellas de plata"], ["fuego y llamas"]),
    q("c", "6", "¿Qué habrá para sombra contra el calor del día?", "Un tabernáculo", ["Una alta torre", "Una ancha muralla"], ["tabernáculo"]),
  ),
  ch("2-ne", 15,
    q("a", "1", "¿De qué cantó Isaías el cantar de su amado?", "De una viña en un collado", ["De un redil en el valle", "De una ciudad junto al río"], ["viña"]),
    q("b", "7", "¿Qué es la viña del Señor de los Ejércitos?", "La casa de Israel", ["El templo de Salomón", "La ciudad del rey"], ["casa de Israel"]),
    q("c", "20", "¿Sobre quiénes pronuncia Isaías una advertencia en el versículo 20?", "Los que a lo malo llaman bueno", ["Los que descansan en el día de reposo", "Los que ayudan a los pobres"], ["a lo malo llaman bueno"]),
  ),
  ch("2-ne", 16,
    q("a", "2", "¿Cuántas alas tenía cada serafín?", "Seis alas", ["Cuatro alas", "Ocho alas"], ["seis alas"]),
    q("b", "6-7", "¿Con qué tocó el serafín los labios de Isaías?", "Con un carbón encendido", ["Con una antorcha ardiente", "Con una piedra caliente"], ["carbón encendido"]),
    q("c", "8", "¿Qué dijo Isaías cuando el Señor preguntó a quién enviaría?", "Heme aquí, envíame a mí", ["No soy digno de esa misión", "Envía a mi hermano mayor"], ["Heme aquí"]),
  ),
  ch("2-ne", 17,
    q("a", "14", "¿Qué nombre le pondrá la virgen al hijo, según Isaías?", "Emanuel", ["Jeremías", "Joram"], ["Emanuel"]),
    q("b", "1", "¿En los días de qué rey de Judá subieron Rezín y Peca contra Jerusalén?", "El rey Acaz", ["El rey Josías", "El rey Joás"], ["Acaz"]),
    q("c", "11", "¿Qué le permitió el Señor pedir a Acaz?", "Una señal", ["Un ejército", "Un barco"], ["señal"]),
  ),
  ch("2-ne", 18,
    q("a", "3", "¿Qué nombre debía ponerle Isaías a su hijo, según el Señor?", "Maher-shalal-hash-baz", ["Sear-jasub, hijo de Amoz", "Maher-Emanuel, hijo de Isaí"], ["Maher-shalal-hash-baz"]),
    q("b", "13", "¿A quién debemos santificar, según el Señor?", "Al Señor de los Ejércitos", ["Al rey de Asiria", "Al profeta Isaías mismo"], ["Señor de los Ejércitos"]),
    q("c", "7", "¿A quién se refieren las aguas fuertes y muchas del río?", "Al rey de Asiria", ["Al rey de Egipto", "Al rey de Siria"], ["rey de Asiria"]),
  ),
  ch("2-ne", 19,
    q("a", "6", "¿Cómo se llamará el Niño que nos es nacido, entre otros nombres?", "Admirable, Consejero", ["Pastor, Juez y Rey", "Salvador, Luz y Maestro"], ["Admirable", "Consejero"]),
    q("b", "2", "¿Qué ha visto el pueblo que andaba en tinieblas?", "Una luz muy grande", ["Una gran estrella", "Un gran ejército"], ["luz"]),
    q("c", "15", "¿Quién es la cola, según Isaías?", "El profeta que enseña mentiras", ["El sacerdote que sirve en el templo", "El soldado que defiende la ciudad"], ["enseña mentiras"]),
  ),
  ch("2-ne", 20,
    q("a", "5", "¿Quién es la vara de la ira del Señor?", "El asirio", ["El egipcio", "El filisteo"], ["asirio"]),
    q("b", "26", "¿Qué matanza se menciona en relación con la peña de Horeb?", "La de Madián", ["La de Amalec", "La de Moab"], ["Madián"]),
    q("c", "21", "¿Qué retornará al Dios fuerte, según Isaías?", "El resto de Jacob", ["Los ejércitos del asirio", "La ciudad del rey"], ["resto de Jacob"]),
  ),
  ch("2-ne", 21,
    q("a", "1", "¿Del tronco de quién saldrá una vara, según Isaías?", "De Isaí", ["De José", "De Judá"], ["Isaí"]),
    q("b", "6", "¿Quién morará con el cordero, según Isaías?", "El lobo", ["El gallo", "El cuervo"], ["lobo"]),
    q("c", "9", "¿De qué estará llena la tierra, según Isaías?", "Del conocimiento del Señor", ["De las riquezas de las naciones", "De las ciudades de los santos"], ["conocimiento del Señor"]),
  ),
  ch("2-ne", 22,
    q("a", "2", "¿Qué es el Señor Jehová, según este cántico?", "Mi fortaleza y mi canción", ["Mi castillo y mi escudo", "Mi pastor y mi roca"], ["fortaleza", "canción"]),
    q("b", "3", "¿De dónde sacaréis agua con gozo?", "De las fuentes de la salvación", ["Del río Jordán junto al valle", "Del pozo antiguo de Jacob"], ["fuentes de la salvación"]),
    q("c", "6", "¿Quién es grande en medio de Sion, según el cántico?", "El Santo de Israel", ["El rey de Judá", "El profeta Isaías"], ["Santo de Israel"]),
  ),
  ch("2-ne", 23,
    q("a", "17", "¿Qué pueblo incitará el Señor contra Babilonia, según Isaías?", "A los medos", ["A los asirios", "A los filisteos"], ["medos"]),
    q("b", "19", "¿Con qué ciudades se compara Babilonia en su destrucción?", "Con Sodoma y Gomorra", ["Con Nínive y Tiro", "Con Jericó y Hai"], ["Sodoma", "Gomorra"]),
    q("c", "10", "¿Qué le sucederá al sol al salir, según Isaías?", "Se obscurecerá del todo", ["Se pondrá rojo como la sangre", "Brillará el doble de fuerte"], ["obscurecer"]),
  ),
  ch("2-ne", 24,
    q("a", "12", "¿Qué título lleva Lucifer en el versículo 12?", "Hijo de la mañana", ["Hijo del mediodía", "Hijo de la tarde"], ["hijo de la mañana"]),
    q("b", "14", "¿Qué dijo Lucifer en su corazón que haría?", "Ascender por encima de las nubes", ["Descender a lo más profundo de la tierra", "Fundar un reino en el oriente"], ["las nubes"]),
    q("c", "23", "¿En qué convertirá el Señor a Babilonia?", "En morada de avetoros", ["En una ciudad de mercaderes", "En un prado para ovejas"], ["avetoros"]),
  ),
  ch("2-ne", 25,
    q("a", "19", "¿Cuántos años después de que Lehi saliera de Jerusalén vendría el Mesías, según los profetas?", "Seiscientos años", ["Cuatrocientos años", "Novecientos años"], ["seiscientos años"]),
    q("b", "24", "¿Qué observaban Nefi y su pueblo aunque creían en Cristo?", "La ley de Moisés", ["El templo de Salomón", "Los anales de Labán"], ["ley de Moisés"]),
    q("c", "29", "¿Quién es Cristo, según Nefi?", "El Santo de Israel", ["El profeta Isaías", "El rey de los judíos"], ["Santo de Israel"]),
  ),
  ch("2-ne", 26,
    q("a", "9", "¿Cómo se llama a Cristo en el versículo 9?", "El Hijo de Justicia", ["El Hijo de la mañana", "El Hijo de la bendición"], ["Hijo de Justicia"]),
    q("b", "31", "¿Por qué no debe trabajar el obrero de Sion?", "Por dinero", ["Por fama", "Por poder"], ["dinero"]),
    q("c", "25", "¿Qué dice el Señor en vez de decir: Apártate de mí?", "Venid a mí, extremos de la tierra", ["Edificad un templo para mi nombre", "Ofreced cada día un cordero para mí"], ["Venid a mí"]),
  ),
  ch("2-ne", 27,
    q("a", "7", "¿Qué habrá en el libro sellado, según el versículo 7?", "Una revelación de Dios", ["Las leyes de los reyes", "Una lista de todos los reyes"], ["revelación de Dios"]),
    q("b", "18", "¿Qué dirá el instruido cuando le lleven el libro?", "No puedo leerlo", ["No pienso pagarlo", "Ya lo he leído"], ["no puedo leerlo"]),
    q("c", "29", "¿Quiénes oirán las palabras del libro, según Isaías?", "Los sordos", ["Los ricos", "Los instruidos"], ["sordos"]),
  ),
  ch("2-ne", 28,
    q("a", "7", "¿Qué dirán muchos en los últimos días, según Nefi?", "Comed, bebed y divertíos", ["Ahorrad, orad y sed prudentes", "Trabajad, ofrendad y agradeced"], ["comed, bebed y divertíos"]),
    q("b", "30", "¿De qué manera da el Señor Dios su palabra a los hijos de los hombres?", "Línea por línea, precepto por precepto", ["Libro por libro, capítulo por capítulo", "Año tras año, milagro tras milagro"], ["línea por línea", "precepto por precepto"]),
    q("c", "22", "¿Qué dice el diablo a algunos, según Nefi?", "Que no hay infierno", ["Que el Señor volverá pronto", "Que cerrarán el templo"], ["no hay infierno"]),
  ),
  ch("2-ne", 29,
    q("a", "3", "¿Qué dirán muchos de los gentiles?", "¡Una Biblia! ¡Una Biblia!", ["¡Un templo! ¡Un templo!", "¡Un rey! ¡Un rey!"], ["Una Biblia"]),
    q("b", "4", "¿De qué pueblo procede la Biblia?", "Del pueblo de los judíos", ["Del pueblo de los egipcios", "Del pueblo de los nefitas"], ["judíos"]),
    q("c", "8", "¿Cuántas naciones dan testimonio de que el Señor es Dios?", "Dos naciones", ["Tres naciones", "Siete naciones"], ["dos naciones"]),
  ),
  ch("2-ne", 30,
    q("a", "2", "¿Quiénes son el pueblo del convenio del Señor, según Nefi?", "Todos los gentiles que se arrepienten", ["Solo los que vinieron de Jerusalén", "Solo los ricos que ofrecen muchos sacrificios"], ["se arrepienten"]),
    q("b", "7", "¿En quién empezarán a creer los judíos dispersos, según Nefi?", "En Cristo", ["En Moisés", "En Abraham"], ["Cristo"]),
    q("c", "17", "¿Qué sucederá con todo lo que está oculto, según Nefi?", "Será revelado", ["Será sellado", "Será olvidado"], ["revelado"]),
  ),
  ch("2-ne", 31,
    q("a", "8", "¿En qué forma descendió el Espíritu Santo sobre Cristo cuando fue bautizado?", "En forma de paloma", ["En forma de águila", "En forma de nube"], ["forma de paloma"]),
    q("b", "21", "¿Qué dice Nefi acerca del camino por el cual el hombre puede salvarse?", "No hay otro camino ni otro nombre", ["Hay dos caminos y dos nombres", "Hay un camino para cada nación"], ["no hay otro camino"]),
    q("c", "11", "¿Qué dijo el Padre que debían hacer los hombres?", "Arrepentirse y ser bautizados", ["Ayunar y ofrecer sacrificios", "Orar y guardar la ley"], ["arrepent", "bautizados"]),
  ),
  ch("2-ne", 32,
    q("a", "2", "¿Con qué podrían hablar después de haber recibido el Espíritu Santo?", "Con lengua de ángeles", ["Con lengua de profetas", "Con lengua de reyes"], ["lengua de ángeles"]),
    q("b", "9", "¿Qué debe hacerse siempre, según Nefi?", "Orar y no desmayar", ["Ayunar y no beber", "Ofrendar y no quejarse"], ["no desmayar"]),
    q("c", "6", "¿Hasta cuándo no se dará otra doctrina, según Nefi?", "Hasta que él se manifieste en la carne", ["Hasta que el templo esté terminado", "Hasta que el pueblo se haya arrepentido"], ["en la carne"]),
  ),
  ch("2-ne", 33,
    q("a", "6", "¿En qué se gloría Nefi, entre otras cosas?", "En la claridad y en la verdad", ["En su fuerza y en su sabiduría", "En sus obras y en su ejército"], ["claridad", "verdad"]),
    q("b", "13", "¿Como la voz de quién habla Nefi a todos los extremos de la tierra?", "Como la voz de uno que clama desde el polvo", ["Como la voz de un pastor en el campo", "Como la voz de un ángel del cielo"], ["clama desde el polvo"]),
    q("c", "15", "¿Qué será presentado contra los hombres ante el tribunal del juicio, según Nefi?", "Lo que Nefi sella en la tierra", ["Todo lo que el hombre ha reunido", "Lo que los judíos han escrito"], ["sell"]),
  ),
  // ===== EINDE =====
];
