import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 3 Nefi (edición en español). Cada hecho está ligado a los versículos indicados en `verses`; `npm run genees:check` lo verifica.
export const nephi3: GeneesChapterSeed[] = [
  ch("3-ne", 1,
    q("a", "19", "¿Qué sucedió la noche de la señal?", "No hubo obscuridad en toda la noche", ["Una fuerte tormenta iluminó la noche", "Hubo un eclipse de sol de muchas horas"], ["no hubo obscuridad"]),
    q("b", "21", "¿Qué apareció en el cielo según la palabra de los profetas?", "Una nueva estrella", ["Una nueva luna llena", "Un cometa de color rojo"], ["nueva estrella"]),
    q("c", "3", "¿Quién llevó los anales después de que su padre salió de la tierra?", "Nefi, hijo de Nefi", ["Lehi, hijo de Nefi", "Nefi, hijo de Lehi"], ["Nefi"]),
  ),
  ch("3-ne", 2,
    q("a", "8", "¿Desde cuándo empezaron los nefitas a calcular su tiempo?", "Desde la señal de la venida de Cristo", ["Desde la muerte del rey Mosíah", "Desde la partida de Lehi de Jerusalén"], ["venida de Cristo"]),
    q("b", "12", "¿Qué hicieron los lamanitas convertidos cuando los ladrones amenazaron?", "Se unieron a los nefitas", ["Se fueron a vivir al norte", "Fundaron su propio reino"], ["se unieron"]),
    q("c", "11", "¿Quiénes causaron guerras y contiendas en el año trece?", "Los ladrones de Gadiantón", ["Los lamanitas del sur", "El rey de Zarahemla"], ["ladrones de Gadiantón"]),
  ),
  ch("3-ne", 3,
    q("a", "9", "¿Cómo se llamaba el caudillo de la sociedad secreta de Gadiantón?", "Un hombre llamado Giddiani", ["Un hombre llamado Gidgiddoni", "Un hombre llamado Zemnaríah"], ["Giddiani"]),
    q("b", "18", "¿Quién fue nombrado comandante supremo de todos los ejércitos de los nefitas?", "Un hombre llamado Gidgiddoni", ["Un hombre llamado Laconeo", "Un hombre llamado Moroníah"], ["Gidgiddoni"]),
    q("c", "23", "¿Qué tierra fue señalada como lugar de reunión?", "La tierra de Zarahemla", ["La tierra de Jersón", "La tierra de Melek"], ["Zarahemla"]),
  ),
  ch("3-ne", 4,
    q("a", "28", "¿Cómo se llamaba el nuevo caudillo de los ladrones que fue colgado de un árbol?", "Zemnaríah, su caudillo", ["Giddiani, su caudillo", "Laconeo, su caudillo"], ["Zemnaríah"]),
    q("b", "3", "¿Por qué no podían subsistir los ladrones sino en el desierto?", "Los nefitas habían dejado asoladas sus tierras", ["Los lamanitas habían ocupado sus tierras", "Los ladrones habían tomado todas las ciudades"], ["dejado asoladas"]),
    q("c", "32", "¿Qué clamaron los nefitas al alabar a Dios?", "¡Hosanna al Más Alto Dios!", ["¡Aleluya al Dios santo!", "¡Gloria al rey de la tierra!"], ["Hosanna"]),
  ),
  ch("3-ne", 5,
    q("a", "12", "¿De qué tierra recibe su nombre Mormón?", "De la tierra de Mormón", ["De la tierra de Helam", "De la tierra de Abundancia"], ["tierra de Mormón"]),
    q("b", "13", "¿Qué dice Mormón de sí mismo con sus propias palabras?", "Un discípulo de Jesucristo", ["Un sumo sacerdote de la iglesia", "Un jefe de los ejércitos nefitas"], ["discípulo de Jesucristo"]),
    q("c", "11", "¿Sobre qué escribe Mormón su relato?", "Sobre planchas hechas con sus propias manos", ["Sobre planchas hechas por su propio padre", "Sobre planchas de bronce de Jerusalén"], ["propias manos"]),
  ),
  ch("3-ne", 6,
    q("a", "6", "¿Quiénes habían establecido la gran paz en la tierra?", "Gidgiddoni y el juez Laconeo", ["Zemnaríah y el juez Giddiani", "Moroni y el juez Pahorán"], ["Gidgiddoni", "Laconeo"]),
    q("b", "14", "¿En qué año se deshizo la iglesia en toda la tierra?", "En el año treinta", ["En el año veinte", "En el año cuarenta"], ["año treinta"]),
    q("c", "8", "¿Qué se construyó en la tierra en tiempo de paz?", "Muchas calzadas y caminos", ["Muchos muros y torres", "Muchos canales y puentes"], ["calzadas"]),
  ),
  ch("3-ne", 7,
    q("a", "19", "¿Qué hizo Nefi en el nombre de Jesús con su hermano?", "Lo resucitó de los muertos", ["Lo sanó de su gran ceguera", "Lo libró de la cárcel real"], ["de los muertos"]),
    q("b", "10", "¿Cómo llamó la sociedad secreta al hombre que puso a su cabeza?", "Lo llamaron su rey", ["Lo llamaron su juez", "Lo llamaron su profeta"], ["su rey"]),
    q("c", "2", "¿En qué se dividió el pueblo?", "En tribus por familias", ["En ciudades por regiones", "En ejércitos por reinos"], ["tribus"]),
  ),
  ch("3-ne", 8,
    q("a", "5", "¿En qué año se desató una gran tormenta?", "En el año treinta y cuatro", ["En el año treinta y tres", "En el año treinta y cinco"], ["treinta y cuatro"]),
    q("b", "8", "¿Qué le sucedió a la ciudad de Zarahemla?", "Se incendió por completo", ["Se hundió por completo", "Fue cubierta por completo"], ["incendi"]),
    q("c", "23", "¿Cuánto tiempo no se vio ninguna luz?", "Tres días", ["Siete días", "Dos días"], ["tres días"]),
  ),
  ch("3-ne", 9,
    q("a", "3", "¿Qué dice la voz que sucedió con la gran ciudad de Zarahemla?", "Fue quemada con fuego", ["Fue hundida en el mar", "Fue cubierta de tierra"], ["con fuego"]),
    q("b", "18", "¿Cómo se llama el Señor a sí mismo en el versículo 18?", "El Alfa y la Omega", ["El Primero y el Último", "El Pastor y la Roca"], ["Alfa", "Omega"]),
    q("c", "20", "¿Qué sacrificio pide el Señor en lugar del derramamiento de sangre?", "Un corazón quebrantado y un espíritu contrito", ["Un sacrificio de los primogénitos del ganado", "Un holocausto del mejor grano de la tierra"], ["corazón quebrantado"]),
  ),
  ch("3-ne", 10,
    q("a", "9", "¿Cuánto tiempo pasó antes de que se disipara la obscuridad de la tierra?", "Tres días", ["Siete días", "Dos días"], ["tres días"]),
    q("b", "5", "¿Con qué compara el Señor su deseo de juntar al pueblo?", "Con una gallina que junta sus polluelos", ["Con un pastor que guía sus ovejas", "Con un águila que lleva a sus aguiluchos"], ["gallina"]),
    q("c", "16", "¿Qué profetas testificaron de estas cosas, según Mormón?", "Zenós y Zenoc", ["Isaías y Jeremías", "Moisés y Aarón"], ["Zenós", "Zenoc"]),
  ),
  ch("3-ne", 11,
    q("a", "1", "¿Dónde estaba reunida la gran multitud del pueblo de Nefi?", "Alrededor del templo en Abundancia", ["Alrededor del monte en Zarahemla", "Alrededor del palacio en Nefi"], ["templo"]),
    q("b", "7", "¿Qué dijo la voz del cielo?", "He aquí a mi Hijo Amado; a él oíd", ["He aquí a mi siervo; seguid sus palabras", "He aquí al profeta; temed sus juicios"], ["Hijo Amado", "a él oíd"]),
    q("c", "25", "¿En nombre de quiénes se debe bautizar, según el Señor?", "En el nombre del Padre, del Hijo y del Espíritu Santo", ["En el nombre del Padre, del profeta y del rey", "En el nombre del Señor, del ángel y del Espíritu"], ["Padre", "Hijo", "Espíritu Santo"]),
  ),
  ch("3-ne", 12,
    q("a", "13", "¿A qué exhorta el Señor en el versículo 13?", "A ser la sal de la tierra", ["A ser la sal del mar", "A ser el pan de la tierra"], ["sal de la tierra"]),
    q("b", "5", "¿Quiénes heredarán la tierra, según el Señor?", "Los que son mansos", ["Los que son ricos", "Los que son fuertes"], ["mansos"]),
    q("c", "44", "¿Qué manda el Señor acerca de nuestros enemigos?", "Amad a vuestros enemigos", ["Expulsad a vuestros enemigos", "Castigad a vuestros enemigos"], ["Amad a vuestros enemigos"]),
  ),
  ch("3-ne", 13,
    q("a", "9", "¿Cómo comienza la oración que Jesús enseña a la multitud?", "Padre nuestro que estás en los cielos", ["Señor nuestro que habitas en el cielo", "Dios nuestro que reinas en la tierra"], ["Padre nuestro que estás en los cielos"]),
    q("b", "33", "¿Qué se debe buscar primeramente, según Jesús?", "El reino de Dios y su justicia", ["Riqueza y buen nombre entre los hombres", "Comida y vestido para la familia"], ["reino de Dios"]),
    q("c", "24", "¿A cuántos señores no puede servir nadie, según Jesús?", "A dos señores", ["A tres señores", "A siete señores"], ["dos señores"]),
  ),
  ch("3-ne", 14,
    q("a", "7", "¿Qué promete el Señor a los que piden?", "Se les dará lo que piden", ["Se les quitará lo que tienen", "Se les olvidará por completo"], ["dará"]),
    q("b", "15", "¿Cómo vienen los falsos profetas, según el Señor?", "Con vestidos de ovejas", ["Con vestidos de rey", "Con vestiduras de sacerdote"], ["vestidos de ovejas"]),
    q("c", "24", "¿Sobre qué edificó su casa el hombre prudente, según Jesús?", "Sobre una roca", ["Sobre la arena", "Sobre una colina"], ["roca"]),
  ),
  ch("3-ne", 15,
    q("a", "17", "¿Qué dice el Señor acerca de otras ovejas?", "Que aún tiene otras ovejas", ["Que ya no tiene otras ovejas", "Que todas las ovejas son de este redil"], ["otras ovejas"]),
    q("b", "4", "¿Qué se ha cumplido, según el Señor?", "La ley que fue dada a Moisés", ["La ley que fue dada a Lehi", "La ley que fue dada a Abraham"], ["dada a Moisés"]),
    q("c", "9", "¿Qué es el Señor, según el versículo 9?", "La ley y la luz", ["La puerta y el camino", "La paz y la roca"], ["la ley y la luz"]),
  ),
  ch("3-ne", 16,
    q("a", "6", "¿Quiénes son benditos, según el Señor, por motivo de su creencia en él?", "Los gentiles que creen en él", ["Los nefitas, y solo ellos", "Los judíos que están en Jerusalén"], ["gentiles"]),
    q("b", "18", "¿Qué harán los centinelas, según el profeta Isaías?", "Levantarán la voz y cantarán unánimes", ["Reunirán al pueblo con trompetas", "Abandonarán la ciudad y huirán"], ["levantarán la voz"]),
    q("c", "13", "¿Qué sucederá con los gentiles si se arrepienten y vuelven al Señor?", "Serán contados entre su pueblo", ["Serán expulsados de la tierra", "Serán perdonados sin juicio alguno"], ["serán contados"]),
  ),
  ch("3-ne", 17,
    q("a", "14", "¿Qué hizo Jesús cuando la multitud se hubo arrodillado en el suelo?", "Gimió dentro de sí", ["Se fue en secreto", "Los bendijo con sus manos"], ["gimió"]),
    q("b", "7", "¿A quiénes pidió Jesús a la multitud que le trajeran?", "A los enfermos, cojos y ciegos", ["A los ricos y poderosos", "A los extranjeros y desconocidos"], ["enfermos"]),
    q("c", "21", "¿Cómo tomó Jesús a los niños pequeños?", "Los tomó uno por uno", ["Los devolvió a sus padres", "Les hizo orar en grupos"], ["uno por uno"]),
  ),
  ch("3-ne", 18,
    q("a", "1", "¿Qué mandó Jesús a sus discípulos que le llevaran?", "Pan y vino para todos", ["Agua y aceite para todos", "Carne y fruta para todos"], ["pan y vino"]),
    q("b", "18", "¿Qué deben hacer siempre los hombres, según Jesús, para no entrar en tentación?", "Velar y orar siempre", ["Ayunar y sacrificar", "Trabajar y ahorrar"], ["velar y orar"]),
    q("c", "7", "¿En memoria de qué debían comer el pan, según Jesús?", "En memoria de su cuerpo", ["En memoria de la ley antigua", "En memoria de los antepasados"], ["cuerpo"]),
  ),
  ch("3-ne", 19,
    q("a", "5", "¿En cuántos grupos se dividió la multitud?", "En doce grupos", ["En siete grupos", "En tres grupos"], ["doce grupos"]),
    q("b", "9", "¿Qué fue lo que más pidieron en oración los discípulos?", "Que les fuese dado el Espíritu Santo", ["Que su pueblo no conociera más guerra", "Que su oración durase sin fin"], ["Espíritu Santo"]),
    q("c", "11", "¿Quién entró en el agua para ser bautizado?", "Nefi, hijo de Nefi", ["Matoni, hijo de Nefi", "Jonás, hijo de Nefi"], ["Nefi"]),
  ),
  ch("3-ne", 20,
    q("a", "3,5", "¿Qué dio Jesús de comer y beber a los discípulos y a la multitud?", "Pan y vino a todos", ["Pescado y miel a todos", "Grano y leche a todos"], ["pan", "vino"]),
    q("b", "6", "¿Qué dice el versículo 6 acerca del pan y del vino?", "Nadie había llevado pan ni vino", ["Los discípulos habían llevado pan y vino", "La multitud había llevado pan y vino"], ["llevado pan ni vino"]),
    q("c", "14", "¿Qué mandó el Padre a Jesús que diera al pueblo?", "Esta tierra por herencia", ["La tierra de Judá por herencia", "La tierra del sur por herencia"], ["por herencia"]),
  ),
  ch("3-ne", 21,
    q("a", "12", "¿Con qué se compara al resto de Jacob entre los gentiles?", "Con un león entre los animales", ["Con una oveja entre los lobos", "Con un águila sobre las montañas"], ["león entre los animales"]),
    q("b", "14", "¿Qué hará destruir el Señor de en medio de los gentiles, en el versículo 14?", "Tus caballos y tus carros", ["Tus ovejas y tus rebaños", "Tus torres y tus puertas"], ["caballos"]),
    q("c", "16", "¿Qué práctica exterminará el Señor de su tierra, según el versículo 16?", "Las hechicerías y la adivinación", ["Las caravanas de los mercaderes", "Los campos de trigo y cebada"], ["hechicerías"]),
  ),
  ch("3-ne", 22,
    q("a", "9", "¿Con qué compara el Señor su promesa en el versículo 9?", "Con las aguas de Noé", ["Con las aguas del Jordán", "Con las aguas del mar Rojo"], ["aguas de Noé"]),
    q("b", "13", "¿Quiénes serán instruidos por el Señor, según él?", "Todos tus hijos, por el Señor", ["Todos los sacerdotes, por el rey", "Solo los ricos, por los maestros"], ["hijos"]),
    q("c", "12", "¿De qué hará el Señor las ventanas de la Sion restaurada?", "De ágatas brillantes", ["De zafiros brillantes", "De cristal brillante"], ["ágatas"]),
  ),
  ch("3-ne", 23,
    q("a", "9", "¿A quién había mandado el Señor testificar al pueblo de la señal de su muerte?", "A Samuel el lamanita", ["A Nefi, hijo de Helamán", "A Lehi, el profeta"], ["Samuel el Lamanita"]),
    q("b", "7", "¿Qué pidió Jesús a Nefi que trajera?", "Los anales que habían llevado", ["Las planchas de bronce de Jerusalén", "La esfera o director de Lehi"], ["anales"]),
    q("c", "13", "¿Qué mandó Jesús que se hiciera con lo que aún no estaba escrito?", "Que se escribiera de inmediato", ["Que se guardara en secreto", "Que se dejara perder por completo"], ["se escribiera"]),
  ),
  ch("3-ne", 24,
    q("a", "1", "¿Las palabras de quién mandó Jesús escribir?", "Las de Malaquías", ["Las de Isaías", "Las de Jeremías"], ["Malaquías"]),
    q("b", "8", "¿En qué defrauda el pueblo a Dios, según el versículo 8?", "En los diezmos y las ofrendas", ["En el día de reposo y los cultos", "En las oraciones y las limosnas"], ["diezmos"]),
    q("c", "10", "¿Adónde deben traerse todos los diezmos, según el Señor?", "Al alfolí de la casa del Señor", ["Al muro del templo de Salomón", "Al asiento del juicio del rey"], ["alfolí"]),
  ),
  ch("3-ne", 25,
    q("a", "5", "¿Qué profeta enviará el Señor antes de que venga el día grande y terrible?", "El profeta Elías", ["El profeta Eliseo", "El profeta Jonás"], ["Elías"]),
    q("b", "2", "¿Cómo se llama a Cristo en el versículo 2?", "El Hijo de Justicia", ["El Hijo de la mañana", "El Hijo de la promesa"], ["Hijo de Justicia"]),
    q("c", "6", "¿Qué volverá Elías, según el Señor?", "El corazón de los padres a los hijos", ["La ley de los padres a los hijos", "La riqueza de los padres a los hijos"], ["corazón de los padres"]),
  ),
  ch("3-ne", 26,
    q("a", "13", "¿Cuánto tiempo enseñó Jesús al pueblo, según el versículo 13?", "Por el espacio de tres días", ["Por el espacio de siete días", "Por el espacio de cuarenta días"], ["tres días"]),
    q("b", "21", "¿Cómo fueron llamados los que se bautizaron en el nombre de Jesús?", "La iglesia de Cristo", ["La iglesia de los Santos", "La iglesia de Nefi"], ["iglesia de Cristo"]),
    q("c", "19", "¿Qué tenían los creyentes, según el versículo 19?", "Todas las cosas en común entre ellos", ["Todas las cosas en propiedad privada", "Todas las riquezas en manos de los jefes"], ["en común"]),
  ),
  ch("3-ne", 27,
    q("a", "5", "¿Con qué nombre debe llamarse la iglesia, según Jesús?", "Con el nombre de Cristo", ["Con el nombre de Moisés", "Con el nombre de Nefi"], ["nombre de Cristo"]),
    q("b", "28", "¿Qué promete Jesús a los que piden al Padre en su nombre?", "Cualquier cosa les será concedida", ["Cualquier cosa les será negada", "Cualquier cosa les será devuelta"], ["concedida"]),
    q("c", "33", "¿Por qué puerta deben entrar los discípulos, según Jesús?", "Por la puerta estrecha", ["Por la puerta ancha", "Por la puerta de oro"], ["puerta estrecha"]),
  ),
  ch("3-ne", 28,
    q("a", "3", "¿A qué edad vendrían los discípulos a Jesús en su reino?", "A los setenta y dos años", ["A los setenta y cinco años", "A los sesenta años"], ["setenta y dos"]),
    q("b", "7", "¿Qué nunca les sucedería a los tres discípulos que lo desearon, según Jesús?", "Nunca probarían la muerte", ["Nunca volverían a tener hambre", "Nunca perderían su fe"], ["la muerte"]),
    q("c", "22", "¿Qué sucedió cuando los tres fueron arrojados en un foso de animales feroces?", "Jugaron con las fieras como un niño", ["Fueron devorados por las fieras", "Fueron atacados por las fieras"], ["jugaron con las fieras"]),
  ),
  ch("3-ne", 29,
    q("a", "8", "¿A quién ya no se debe escarnecer ni desdeñar, según Mormón?", "A los judíos", ["A los nefitas", "A los lamanitas"], ["judíos"]),
    q("b", "6", "¿Qué niega el que dice que el Señor ya no obra?", "Las revelaciones del Señor", ["Los convenios del Señor", "Los profetas del Señor"], ["revelaciones"]),
    q("c", "2", "¿Qué se puede saber acerca de las palabras del Señor, según Mormón?", "Que se cumplirán todas", ["Que serán todas olvidadas", "Que nunca más serán leídas"], ["cumplirán todas"]),
  ),
  ch("3-ne", 30,
    q("a", "1", "¿A quiénes se dirige Mormón en este capítulo?", "A los gentiles", ["A los nefitas", "A los lamanitas"], ["gentiles"]),
    q("b", "2", "¿Qué deben hacer los gentiles, según Mormón?", "Tornarse de sus caminos de maldad", ["Reunirse en la tierra del norte", "Apresurarse a construir torres"], ["caminos de maldad"]),
    q("c", "1", "¿Quién es Jesucristo, según el versículo 1?", "El Hijo del Dios viviente", ["El hijo del profeta Mormón", "El hijo del rey de Judá"], ["Hijo del Dios viviente"]),
  ),
  // ===== EINDE =====
];
