import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Alma (edición en español). Cada hecho está ligado a los versículos indicados en `verses`; `npm run genees:check` lo verifica.
export const alma: GeneesChapterSeed[] = [
  ch("alma", 1,
    q("a", "15", "¿Cómo se llamaba el hombre que mató a Gedeón?", "Un hombre llamado Nehor", ["Un hombre llamado Amlici", "Un hombre llamado Korihor"], ["Nehor"]),
    q("b", "15", "¿Dónde fue ejecutado Nehor?", "En la cima del cerro Manti", ["A orillas del río Sidón", "En la plaza de Zarahemla"], ["cerro Manti"]),
    q("c", "12", "¿Qué se había introducido por primera vez entre el pueblo, según Alma?", "La superchería sacerdotal", ["La esclavitud de los hombres", "La construcción de un templo"], ["superchería sacerdotal"]),
  ),
  ch("alma", 2,
    q("a", "1", "¿Cómo se llamaba el hombre que quería ser rey del pueblo?", "Amlici, un hombre astuto", ["Nehor, un hombre astuto", "Korihor, un hombre astuto"], ["Amlici"]),
    q("b", "31", "¿Cómo mató Alma al líder de los amlicitas?", "Con la espada", ["Con una lanza", "Con una flecha"], ["espada"]),
    q("c", "15", "¿A qué cerro llegaron los amlicitas, al este del río Sidón?", "Al cerro Amnihu", ["Al cerro Manti", "Al cerro Riplah"], ["Amnihu"]),
  ),
  ch("alma", 3,
    q("a", "4", "¿Qué se habían marcado los amlicitas en la frente?", "Una marca roja", ["Una marca azul", "Una marca negra"], ["roj"]),
    q("b", "26", "¿Cuántas almas fueron enviadas al mundo eterno en ese año?", "Millares y decenas de millares", ["Solo unas pocas docenas de personas", "Apenas unos cuantos centenares"], ["millares y decenas de millares"]),
    q("c", "22", "¿Por qué no fue Alma esta vez en persona a la batalla contra los lamanitas?", "Porque estaba afligido con una herida", ["Porque no confiaba en el ejército", "Porque tenía otro plan en mente"], ["herida"]),
  ),
  ch("alma", 4,
    q("a", "5", "¿Cuántas almas se unieron a la iglesia en el año séptimo?", "Unas tres mil quinientas", ["Unas dos mil quinientas", "Unas cinco mil trescientas"], ["tres mil quinientas"]),
    q("b", "17", "¿Quién fue nombrado juez superior cuando Alma entregó el asiento judicial?", "Nefíah, un hombre recto", ["Helamán, un hombre recto", "Gedeón, un hombre recto"], ["Nefíah"]),
    q("c", "18", "¿Qué oficio retuvo Alma para sí?", "El de sumo sacerdote", ["El de jefe del ejército", "El de juez superior"], ["sumo sacerdote"]),
  ),
  ch("alma", 5,
    q("a", "38", "¿Cuál es el nombre del buen pastor que nos llama?", "El nombre de Cristo", ["El nombre de Mormón", "El nombre de Abinadí"], ["nombre de Cristo"]),
    q("b", "3", "¿Por quién fue consagrado Alma como sumo sacerdote sobre la iglesia?", "Por su padre Alma", ["Por el rey Mosíah", "Por el profeta Abinadí"], ["padre Alma"]),
    q("c", "52", "¿Qué está puesto a la raíz del árbol, según el Espíritu?", "El hacha", ["La sierra", "La pala"], ["hacha"]),
  ),
  ch("alma", 6,
    q("a", "8", "¿En qué valle empezó Alma a declarar la palabra de Dios?", "En el valle de Gedeón", ["En el valle de Lemuel", "En el valle de Helam"], ["valle de Gedeón"]),
    q("b", "2", "¿Qué sucedía con los que se arrepentían de sus pecados y no pertenecían a la iglesia?", "Se bautizaban para arrepentimiento", ["Debían esperar primero un año entero", "Eran enviados a Zarahemla de inmediato"], ["arrepentimiento"]),
    q("c", "6", "¿Para qué se mandó a los hijos de Dios que se congregaran frecuentemente?", "Para el ayuno y la ferviente oración", ["Para ofrecer sacrificios y holocaustos", "Para construir nuevos templos"], ["ayuno"]),
  ),
  ch("alma", 7,
    q("a", "10", "¿Dónde nacerá el Señor, según Alma?", "En Jerusalén", ["En Nazaret", "En Zarahemla"], ["Jerusalén"]),
    q("b", "10", "¿Cómo llama Alma a la madre del Señor?", "Una virgen, un vaso precioso y escogido", ["Una princesa, una mujer rica y poderosa", "Una reina, un vaso rico y noble"], ["vaso precioso y escogido"]),
    q("c", "24", "¿Qué tres cosas debemos tener, según Alma?", "Fe, esperanza y caridad", ["Fe, arrepentimiento y ofrendas", "Ciencia, sabiduría y poder"], ["fe, esperanza y caridad"]),
  ),
  ch("alma", 8,
    q("a", "3", "¿A qué tierra viajó Alma en el décimo año del gobierno de los jueces?", "A la tierra de Melek", ["A la tierra de Gedeón", "A la tierra de Jershón"], ["tierra de Melek"]),
    q("b", "6", "¿Cómo se llamaba la ciudad a la que llegó Alma tras tres días hacia el norte de Melek?", "Ammoníah", ["Zarahemla", "Jershón"], ["Ammoníah"]),
    q("c", "21", "¿Cómo se llamaba el hombre que recibió a Alma en su casa?", "Amulek", ["Amulón", "Amalekí"], ["Amulek"]),
  ),
  ch("alma", 9,
    q("a", "4", "¿Qué dijeron los habitantes de Ammoníah que no creerían aunque Alma profetizara?", "Que la ciudad sería destruida en un día", ["Que la ciudad perecería por una inundación", "Que los lamanitas conquistarían la ciudad"], ["destruida en un día"]),
    q("b", "26", "¿Qué dice el ángel sobre la venida del Hijo de Dios?", "Que vendrá dentro de pocos días", ["Que vendrá dentro de cientos de años", "Que vendrá dentro de más de mil años"], ["pocos días"]),
    q("c", "34", "¿Quién se adelantó y empezó a predicar también al pueblo?", "Amulek, de Ammoníah", ["Zeezrom, de Ammoníah", "Antiona, de Ammoníah"], ["Amulek"]),
  ),
  ch("alma", 10,
    q("a", "2", "¿Quién era el padre de Amulek?", "Giddona", ["Aminadí", "Ismael"], ["Giddona"]),
    q("b", "7", "¿Quién se apareció a Amulek en su camino?", "Un ángel del Señor", ["Un profeta de Zarahemla", "Un siervo de Alma"], ["ángel del Señor"]),
    q("c", "31", "¿Cómo se llamaba el principal acusador de Amulek y Alma?", "Zeezrom", ["Antiona", "Korihor"], ["Zeezrom"]),
  ),
  ch("alma", 11,
    q("a", "3", "¿Qué recibía un juez como pago por un día?", "Un senine de oro", ["Un limna de oro", "Un onti de plata"], ["senine de oro"]),
    q("b", "21", "¿Quién empezó a interrogar a Amulek?", "Zeezrom", ["Antiona", "Gedeón"], ["Zeezrom"]),
    q("c", "38-39", "¿Quién es verdaderamente el Padre Eterno del cielo y de la tierra, según Amulek?", "El Hijo de Dios", ["El profeta Alma", "El ángel del Señor"], ["Hijo de Dios"]),
  ),
  ch("alma", 12,
    q("a", "20", "¿Quién era Antiona?", "Un gobernante principal", ["Un hombre diestro en la ley", "Un capitán del ejército"], ["gobernante principal"]),
    q("b", "16", "¿Cómo llama Alma a la segunda muerte?", "Una muerte espiritual", ["Una muerte temporal", "Una muerte corporal"], ["muerte espiritual"]),
    q("c", "21", "¿Qué colocó Dios al oriente del Jardín de Edén, según la Escritura?", "Querubines y una espada encendida", ["Un muro con una puerta de oro", "Un ángel con una llave de oro"], ["querubines"]),
  ),
  ch("alma", 13,
    q("a", "15", "¿A quién pagó Abraham los diezmos?", "A Melquisedec", ["Al rey Salomón", "Al profeta Moisés"], ["Melquisedec"]),
    q("b", "17", "¿De qué tierra era rey Melquisedec?", "De la tierra de Salem", ["De la tierra de Moab", "De la tierra de Egipto"], ["tierra de Salem"]),
    q("c", "9", "¿Cómo se llama al Hijo en el versículo 9?", "El Unigénito del Padre", ["El Primogénito del Padre", "El Ungido del Padre"], ["Unigénito del Padre"]),
  ),
  ch("alma", 14,
    q("a", "16", "¿De la orden y la fe de quién era el juez superior de Ammoníah?", "De la orden de Nehor", ["De la orden de Amlici", "De la orden de Korihor"], ["Nehor"]),
    q("b", "18", "¿Cuántos días estuvieron Alma y Amulek en la cárcel antes de que llegaran los abogados?", "Tres días", ["Siete días", "Dos días"], ["tres días"]),
    q("c", "27", "¿Qué sucedió cuando Alma y Amulek clamaron al Señor para ser librados?", "La tierra tembló fuertemente", ["Estalló un gran incendio allí", "Cayó una granizada violenta"], ["fuertemente"]),
  ),
  ch("alma", 15,
    q("a", "1", "¿A qué tierra fueron Alma y Amulek después de salir de Ammoníah?", "A la tierra de Sidom", ["A la tierra de Melek", "A la tierra de Nefi"], ["tierra de Sidom"]),
    q("b", "3", "¿De qué sufría Zeezrom en Sidom?", "De una fiebre ardiente", ["De una herida grave", "De una ceguera severa"], ["fiebre ardiente"]),
    q("c", "12", "¿Qué hizo Alma con Zeezrom después de que fue sanado?", "Lo bautizó en el nombre del Señor", ["Lo envió de regreso a Ammoníah", "Le hizo abandonar la iglesia"], ["bautiz"]),
  ),
  ch("alma", 16,
    q("a", "5", "¿Cómo se llamaba el capitán en jefe de los ejércitos de los nefitas?", "Zoram, con dos hijos", ["Moroni, con dos hijos", "Gedeón, con dos hijos"], ["Zoram"]),
    q("b", "10", "¿Qué sucedió con la ciudad de Ammoníah, según Alma 16?", "Quedó desolada en un solo día", ["Fue ocupada poco a poco por los lamanitas", "Fue tragada por un terremoto"], ["en un solo día"]),
    q("c", "19", "¿Qué proclamaban los sacerdotes acerca del Hijo de Dios?", "Sus padecimientos y muerte", ["Sus riquezas y su poder", "Su matrimonio y su familia"], ["padecimientos y muerte"]),
  ),
  ch("alma", 17,
    q("a", "4", "¿Cuántos años habían enseñado los hijos de Mosíah la palabra de Dios entre los lamanitas?", "Catorce años", ["Cuarenta años", "Siete años"], ["catorce años"]),
    q("b", "21", "¿Cómo se llamaba el rey de la tierra de Ismael?", "El rey Lamoni", ["El rey Limhi", "El rey Lamán"], ["Lamoni"]),
    q("c", "38", "¿Cuántos hombres de los lamanitas cayeron por la honda de Ammón?", "Seis hombres", ["Cuatro hombres", "Ocho hombres"], ["seis"]),
  ),
  ch("alma", 18,
    q("a", "13", "¿Qué significa la palabra Rabbánah?", "Poderoso o gran rey", ["Señor sabio y poderoso", "Valiente jefe del ejército"], ["gran rey"]),
    q("b", "43", "¿Cuánto tiempo estuvo el rey Lamoni como muerto sobre su cama?", "Dos días y dos noches", ["Tres días y tres noches", "Un día y una noche"], ["dos días y dos noches"]),
    q("c", "9", "¿Qué hacía Ammón cuando el rey preguntó por él?", "Daba de comer a los caballos del rey", ["Celebraba una fiesta con los siervos", "Dormía en la tienda del rey"], ["caballos"]),
  ),
  ch("alma", 19,
    q("a", "8", "¿Qué dijo Ammón sobre el rey Lamoni al mirarlo?", "No está muerto, sino que duerme en Dios", ["Está herido y debe descansar junto al fuego", "Está enfermo y necesita un médico"], ["duerme en Dios"]),
    q("b", "13", "¿Qué dijo Lamoni cuando se levantó de nuevo?", "Que había visto a su Redentor", ["Que había visto un gran ejército", "Que había visto a su padre"], ["Redentor"]),
    q("c", "28", "¿Quién había hecho que se reuniera la multitud?", "Una criada lamanita", ["Una hija del rey", "Un sacerdote del pueblo"], ["criada"]),
  ),
  ch("alma", 20,
    q("a", "3", "¿En qué tierra estaban encarcelados los hermanos de Ammón?", "En la tierra de Middoni", ["En la tierra de Ismael", "En la tierra de Sidom"], ["Middoni"]),
    q("b", "10", "¿Cómo llama el padre de Lamoni al nefita Ammón?", "Uno de los hijos de un mentiroso", ["Uno de los hijos de un rey", "Uno de los siervos del diablo"], ["hijos de un mentiroso"]),
    q("c", "23", "¿Qué ofreció el anciano rey a Ammón si le perdonaba la vida?", "Hasta la mitad del reino", ["Un tercio de sus tesoros", "A su hija mayor por esposa"], ["mitad del reino"]),
  ),
  ch("alma", 21,
    q("a", "2", "¿Qué ciudad edificaron los lamanitas, los amalekitas y el pueblo de Amulón?", "Una gran ciudad llamada Jerusalén", ["Una gran ciudad llamada Nefi", "Una gran ciudad llamada Zarahemla"], ["Jerusalén"]),
    q("b", "14", "¿Por intervención de quiénes fueron librados Aarón y sus hermanos de la cárcel?", "Por la de Lamoni y Ammón", ["Por la de Mosíah y Alma", "Por la de Omner e Himni"], ["Lamoni", "Ammón"]),
    q("c", "22", "¿Qué declaró el rey Lamoni a su pueblo acerca de adorar al Señor?", "Que gozarían de libertad para adorar al Señor", ["Que solo podían adorar en las sinagogas del reino", "Que debían adorar únicamente al rey Lamoni"], ["libertad"]),
  ),
  ch("alma", 22,
    q("a", "3", "¿Qué prometieron Aarón y sus hermanos al rey a cambio de sus vidas?", "Que serían sus siervos", ["Que le darían sus posesiones", "Que abandonarían la tierra"], ["siervos"]),
    q("b", "7", "¿Qué dicen los amalekitas acerca de Dios, según el rey?", "Que hay un Dios", ["Que hay dos dioses", "Que no hay Dios"], ["hay un Dios"]),
    q("c", "17", "¿Qué hizo el rey cuando Aarón terminó de hablar?", "Se postró hasta el polvo", ["Se levantó y salió de la sala", "Llamó a su guardia personal"], ["polvo"]),
  ),
  ch("alma", 23,
    q("a", "17", "¿Cómo se llamaron a sí mismos los lamanitas convertidos?", "Los anti-nefi-lehitas", ["Los nefi-lamanitas", "Los lehi-nefitas"], ["anti-nefi-lehitas"]),
    q("b", "1", "¿Qué proclamó el rey de los lamanitas a su pueblo acerca de Ammón y sus hermanos?", "Que no debían echar mano a ellos", ["Que debían salir de la tierra", "Que solo podían predicar en Ismael"], ["echar mano"]),
    q("c", "14", "¿Quiénes no se convirtieron?", "Los amalekitas y los amulonitas", ["Los nefitas de Zarahemla", "El pueblo de Ismael y Middoni"], ["amalekitas", "amulonitas"]),
  ),
  ch("alma", 24,
    q("a", "3", "¿Qué nombre le dio el rey al hijo a quien confirió el reino?", "Anti-Nefi-Lehi", ["Anti-Lehi-Nefi", "Nefi-Anti-Lehi"], ["Anti-Nefi-Lehi"]),
    q("b", "16", "¿Qué harían con sus espadas si sus hermanos intentaban destruirlos, según el rey?", "Enterrarlas en lo profundo de la tierra", ["Fundirlas para hacer herramientas", "Entregarlas a los nefitas para siempre"], ["profundo de la tierra"]),
    q("c", "22", "¿Cuántos de ellos fueron muertos sin resistencia por los lamanitas?", "Mil y cinco", ["Mil y diez", "Quinientos cinco"], ["mil y cinco"]),
  ),
  ch("alma", 25,
    q("a", "11", "¿Quién fue el primero que padeció la muerte por fuego por causa de su fe en Dios?", "Abinadí, el profeta", ["Amulek, de Ammoníah", "Gedeón, el capitán"], ["Abinadí"]),
    q("b", "14", "¿Qué hicieron los lamanitas convertidos con sus armas de guerra?", "Las enterraron en la tierra", ["Las vendieron a los nefitas", "Las llevaban siempre encima"], ["enterraron"]),
    q("c", "16", "¿Para qué les servía la ley de Moisés?", "Para fortalecer su fe en Cristo", ["Para separarse de los nefitas", "Para guardar sus riquezas en el templo"], ["fe en Cristo"]),
  ),
  ch("alma", 26,
    q("a", "4", "¿Qué dice Ammón acerca de miles de los lamanitas?", "Que han sido traídos al redil de Dios", ["Que han empezado a servir a los nefitas", "Que han expulsado a su propio rey"], ["redil de Dios"]),
    q("b", "22", "¿Qué se le concede, según Ammón, al que se arrepiente, ejerce fe y ora continuamente?", "Conocer los misterios de Dios", ["Un lugar junto al rey", "Riquezas y poder en la tierra"], ["misterios de Dios"]),
    q("c", "12", "¿En quién dice Ammón que se gloriará?", "En el Señor, su Dios", ["En su propia fuerza", "En su propia sabiduría"], ["Dios"]),
  ),
  ch("alma", 27,
    q("a", "22", "¿Qué tierra cedió el pueblo de Nefi al pueblo de Ammón?", "La tierra de Jersón", ["La tierra de Gedeón", "La tierra de Melek"], ["Jersón"]),
    q("b", "12", "¿Para qué le mandó el Señor a Ammón sacar a este pueblo de la tierra?", "Para que no perezca el pueblo", ["Para que poseyeran más tierra", "Para que atacaran a los nefitas"], ["no perezca"]),
    q("c", "30", "¿Cómo se describe al pueblo de Ammón en el versículo 30?", "Un pueblo celoso y amado", ["Un pueblo belicoso y temido", "Un pueblo rico y poderoso"], ["celoso y amado"]),
  ),
  ch("alma", 28,
    q("a", "7", "¿Qué año del gobierno de los jueces terminó después de la terrible batalla?", "El año decimoquinto", ["El año duodécimo", "El año vigésimo"], ["decimoquinto"]),
    q("b", "6", "¿Cómo se describe el día de la terrible batalla?", "Un día lúgubre", ["Un día de fiesta", "Un día tranquilo"], ["lúgubre"]),
    q("c", "12", "¿Qué hacen muchos miles que lamentan la pérdida de sus parientes?", "Se regocijan y se alegran en la esperanza", ["Huyen de la tierra y se esconden allí", "Reúnen sus ejércitos para vengarse ya"], ["regocijan"]),
  ),
  ch("alma", 29,
    q("a", "1", "¿Qué desearía ser Alma para hacer sonar la trompeta de Dios?", "Un ángel", ["Un rey", "Un profeta"], ["ángel"]),
    q("b", "1", "¿Con qué quisiera hablar Alma entonces?", "Con la trompeta de Dios", ["Con el arpa de David", "Con la voz del rey"], ["trompeta de Dios"]),
    q("c", "8", "¿A quién concede el Señor que enseñen su palabra en su propia nación y lengua?", "A todas las naciones", ["Solo a los nefitas", "Solo a los judíos"], ["todas las naciones"]),
  ),
  ch("alma", 30,
    q("a", "12", "¿Cómo se llamaba el anticristo que predicaba al pueblo que no habría Cristo?", "Un hombre llamado Korihor", ["Un hombre llamado Nehor", "Un hombre llamado Amlici"], ["Korihor"]),
    q("b", "50", "¿Qué le sucedió a Korihor después de que habló Alma?", "Quedó mudo por completo", ["Quedó ciego por completo", "Fue apedreado por el pueblo"], ["mudo"]),
    q("c", "23", "¿Cómo se llamaba el sumo sacerdote en la tierra de Gedeón?", "Un hombre llamado Giddona", ["Un hombre llamado Nefíah", "Un hombre llamado Helamán"], ["Giddona"]),
  ),
  ch("alma", 31,
    q("a", "21", "¿Qué significa el nombre Rameúmptom?", "El santo púlpito elevado", ["La alta torre de Dios", "El lugar de los escogidos"], ["santo púlpito"]),
    q("b", "3", "¿Cómo llamaron los zoramitas a la tierra donde se reunieron?", "La tierra de Antiónum", ["La tierra de Gedeón", "La tierra de Jersón"], ["Antiónum"]),
    q("c", "7", "¿Quién era el hijo mayor de Alma, a quien no llevó consigo entre los zoramitas?", "Helamán", ["Shiblón", "Coriantón"], ["Helamán"]),
  ),
  ch("alma", 32,
    q("a", "28", "¿Con qué compara Alma la palabra?", "Con una buena semilla", ["Con un río caudaloso", "Con un fuego ardiente"], ["semilla"]),
    q("b", "21", "¿Qué no es la fe, según Alma?", "Un conocimiento perfecto de las cosas", ["Una esperanza en cosas que no se ven", "Una confianza en una buena semilla"], ["conocimiento perfecto"]),
    q("c", "10", "¿Dónde se puede adorar a Dios, según Alma?", "En cualquier lugar, no solo en las sinagogas", ["Solo en las sinagogas en el día de reposo", "Solo en el templo del rey y los jueces"], ["sinagogas"]),
  ),
  ch("alma", 33,
    q("a", "3", "¿Qué antiguo profeta se cita acerca de la oración y la adoración?", "El profeta Zenós", ["El profeta Isaías", "El profeta Jeremías"], ["Zenós"]),
    q("b", "15", "¿Qué segundo profeta antiguo habló también del Hijo de Dios?", "El profeta Zenoc", ["El profeta Ezías", "El profeta Jarom"], ["Zenoc"]),
    q("c", "19", "¿Qué fue levantado en el desierto para que quien mirara a él viviera?", "Un símbolo de Cristo", ["Un altar de piedra", "Una gran carpa blanca"], ["símbolo"]),
  ),
  ch("alma", 34,
    q("a", "10", "¿Qué tipo de sacrificio debe haber, según Amulek?", "Un gran y postrer sacrificio", ["Un sacrificio diario de grano", "Un sacrificio anual de ovejas"], ["gran y postrer sacrificio"]),
    q("b", "21", "¿Cuándo debe clamarse al Señor en casa, según Amulek?", "Por la mañana, al mediodía y al atardecer", ["Una vez por semana en la sinagoga", "Solo cuando hay necesidad en la tierra"], ["mañana", "atardecer"]),
    q("c", "32", "¿Para qué es este tiempo de la vida, según Amulek?", "Para prepararse a comparecer ante Dios", ["Para adquirir riquezas y honores", "Para edificar un reino en la tierra"], ["comparecer ante Dios"]),
  ),
  ch("alma", 35,
    q("a", "1", "¿A qué tierra pasaron Alma y Amulek tras predicar a los zoramitas?", "A la tierra de Jersón", ["A la tierra de Melek", "A la tierra de Gedeón"], ["Jersón"]),
    q("b", "13", "¿Adónde se fue el pueblo de Ammón desde Jersón?", "A la tierra de Melek", ["A la tierra de Nefi", "A la tierra de Sidom"], ["Melek"]),
    q("c", "12", "¿Qué año del gobierno de los jueces terminó en este capítulo?", "El año decimoséptimo", ["El año decimosexto", "El año decimoctavo"], ["decimoséptimo"]),
  ),
  ch("alma", 36,
    q("a", "10", "¿Cuánto tiempo no pudo abrir la boca Alma después de que se le apareció el ángel?", "Tres días y tres noches", ["Dos días y dos noches", "Siete días y siete noches"], ["tres días y tres noches"]),
    q("b", "18", "¿Qué palabras clamó Alma en su corazón?", "Oh Jesús, Hijo de Dios, ten piedad", ["Oh Señor, sálvame de mis enemigos", "Oh Dios, quítame la vida ahora"], ["Jesús, Hijo de Dios"]),
    q("c", "22", "¿Con la visión de quién compara Alma lo que vio, a Dios sentado en su trono?", "Con la de Lehi", ["Con la de Nefi", "Con la de Mosíah"], ["Lehi"]),
  ),
  ch("alma", 37,
    q("a", "6", "¿Qué se realiza por medio de cosas pequeñas y sencillas, según Alma?", "Grandes cosas", ["Cosas pequeñas", "Cosas inútiles"], ["grandes cosas"]),
    q("b", "21", "¿De cuántas planchas habló Alma, que Helamán debía guardar?", "Veinticuatro planchas", ["Veintidós planchas", "Veintiséis planchas"], ["veinticuatro"]),
    q("c", "26", "¿Qué sucedió con los que no se arrepintieron?", "Han sido destruidos", ["Han sido desterrados", "Han sido dispersados"], ["destruidos"]),
  ),
  ch("alma", 38,
    q("a", "4", "¿Por qué fue Shiblón apedreado, según Alma?", "Por motivo de la palabra", ["Por motivo de sus riquezas", "Por motivo de su ejército"], ["por motivo de la palabra"]),
    q("b", "13", "¿Por qué oran los zoramitas, según Alma?", "Para ser oídos de los hombres", ["Para ser bendecidos por Dios", "Para confesar sus pecados ante Dios"], ["oídos de los hombres"]),
    q("c", "11", "¿De qué no debe jactarse Shiblón, según Alma?", "De su propia sabiduría", ["De la gracia de Dios", "Del apoyo de sus hermanos"], ["propia sabiduría"]),
  ),
  ch("alma", 39,
    q("a", "10", "¿Con quién debía consultar Coriantón en todas sus empresas, según Alma?", "Con sus hermanos mayores", ["Con el rey de la tierra", "Con los maestros de los zoramitas"], ["hermanos mayores"]),
    q("b", "14", "¿Por qué no debe Coriantón buscar las riquezas, según Alma?", "Porque no puede llevarlas consigo", ["Porque los lamanitas se las quitarán", "Porque la riqueza es solo para los jueces"], ["llevar"]),
    q("c", "18", "¿A quién debe darse a conocer el plan de redención, según Alma?", "A este pueblo y a sus hijos", ["Solo a los sacerdotes de la iglesia", "Solo a los jueces de la tierra"], ["este pueblo"]),
  ),
  ch("alma", 40,
    q("a", "12", "¿Cómo se llama el estado de felicidad de los justos entre la muerte y la resurrección?", "Un estado llamado paraíso", ["Un estado llamado reino", "Un estado llamado Edén"], ["paraíso"]),
    q("b", "14", "¿En qué se hallan las almas de los malvados, según el versículo 14?", "En tinieblas y en terrible espera", ["En descanso y paz del corazón", "En sueño hasta la resurrección"], ["tinieblas"]),
    q("c", "23", "¿Qué sucederá con el alma en la restauración, según Alma?", "El alma será restaurada al cuerpo", ["El alma quedará separada para siempre", "El cuerpo será entregado a la tierra"], ["restaurada al cuerpo"]),
  ),
  ch("alma", 41,
    q("a", "13", "¿Qué significa la palabra restauración, según Alma?", "Volver de nuevo mal por mal", ["Llevar al pecador a la felicidad", "Devolver todo de nuevo sin juicio"], ["mal por mal"]),
    q("b", "10", "¿Qué cosa nunca ha sido felicidad, según Alma?", "La maldad de los hombres", ["El trabajo duro de cada día", "La obediencia a los mandamientos"], ["maldad"]),
    q("c", "14", "¿Qué debe hacer Coriantón continuamente, según Alma?", "Hacer lo bueno sin cesar", ["Vengarse sin cesar", "Buscar riquezas sin cesar"], ["lo bueno sin cesar"]),
  ),
  ch("alma", 42,
    q("a", "4", "¿Qué le fue concedido al hombre, según Alma?", "Un tiempo para arrepentirse", ["Un tiempo de descanso sin ley", "Una morada eterna en el Edén"], ["arrepentirse"]),
    q("b", "22-23", "¿Sobre quién reclama la misericordia, según Alma?", "Sobre el que de verdad se arrepiente", ["Sobre los poderosos que gobiernan", "Sobre los ricos que ofrecen sacrificios"], ["se arrepiente"]),
    q("c", "27", "¿Quién puede venir y beber de las aguas de la vida, según Alma?", "Cualquiera que quiera venir", ["Solo los sacerdotes de la Iglesia", "Solo quien sea suficientemente rico"], ["quiera venir"]),
  ),
  ch("alma", 43,
    q("a", "17", "¿Qué edad tenía Moroni cuando fue nombrado capitán en jefe?", "Veinticinco años", ["Treinta y cinco años", "Cuarenta y cinco años"], ["veinticinco años"]),
    q("b", "19", "¿Con qué había equipado Moroni a su pueblo?", "Con petos y con broqueles", ["Con carros y caballos de guerra", "Con cascos y largas lanzas"], ["petos", "broqueles"]),
    q("c", "44", "¿Cómo se llamaba el capitán en jefe de los lamanitas?", "Zerahemna, su caudillo", ["Amalickíah, su caudillo", "Zemnarihah, su caudillo"], ["Zerahemna"]),
  ),
  ch("alma", 44,
    q("a", "6", "¿Qué mandó Moroni a Zerahemna?", "Entregar sus armas de guerra", ["Mandar su ejército a casa", "Cederle su reino a Moroni"], ["armas de guerra"]),
    q("b", "20", "¿Qué hizo Moroni con los lamanitas después de detener la matanza?", "Recogió sus armas de guerra", ["Les dejó conservar sus armas", "Les dio comida y vestidos"], ["armas de guerra"]),
    q("c", "24", "¿Qué año del gobierno de los jueces terminó con los anales de Alma?", "El año decimoctavo", ["El año decimoséptimo", "El año decimonoveno"], ["decimoctavo"]),
  ),
  ch("alma", 45,
    q("a", "4", "¿En quién le pidió Alma a su hijo Helamán que creyera, que ha de venir?", "En Jesucristo, el Hijo de Dios", ["En el rey Benjamín, su abuelo", "En el profeta Moisés de Egipto"], ["Jesucristo"]),
    q("b", "10", "¿Cuántos años después de la venida de Cristo degeneraría en incredulidad el pueblo nefita, según Alma?", "Cuatrocientos años", ["Doscientos años", "Seiscientos años"], ["cuatrocientos años"]),
    q("c", "18", "¿Qué sucedió con Alma después de salir de Zarahemla?", "No se volvió a saber de él", ["Murió poco después en Melek", "Fue hecho prisionero por los lamanitas"], ["no se volvió a saber"]),
  ),
  // ===== EINDE =====
];
