import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Helaman. Spanish edition - generated from Dutch master.
export const helaman: GeneesChapterSeed[] = [
  ch("hel", 1,
    q("a", "3", "Hoe heetten de zonen van Pahoran die om de rechterstoel twistten?", "Pahoran, Paänchi en Pacumeni", ["Pahoran, Moronihah en Pacumeni", "Pahoran, Paänchi en Pachus"], ["Paänchi", "Pacumeni"]),
    q("b", "10", "Hoe heette de man die Pahoran vermoordde?", "Kishkumen", ["Gadianton", "Coriantumr"], ["Kishkumen"]),
    q("c", "15", "Hoe heette de Lamanitische leider die de stad Zarahemla innam?", "Coriantumr", ["Zerahemnah", "Lehonti"], ["Coriantumr"]),
  ),
  ch("hel", 2,
    q("a", "4", "Wie was Gadianton volgens Helaman 2?", "Een man met vele woorden en veel listigheid", ["De nieuwe opperrechter van het volk", "Een legeraanvoerder van de Nephieten"], ["listigheid"]),
    q("b", "6", "Wie hield Kishkumen tegen toen hij Helaman wilde vernietigen?", "Een dienstknecht van Helaman", ["Een wacht van de koning", "Een priester van Gadianton"], ["dienstknecht"]),
    q("c", "2", "Wat kreeg Helaman, de zoon van Helaman, door de stem van het volk?", "De rechterstoel te bekleden", ["Het bevel over het leger te voeren", "De tempel te beheren"], ["rechterstoel"]),
  ),
  ch("hel", 3,
    q("a", "21", "Hoe heetten de twee zonen van Helaman?", "Nephi en Lehi", ["Nephi en Shiblon", "Lehi en Moronihah"], ["Nephi", "Lehi"]),
    q("b", "9", "Waarin woonden de mensen in het noordelijke land?", "In tenten en in huizen van cement", ["In grotten en in huizen van hout", "In steden van steen en bergen"], ["cement"]),
    q("c", "37", "Wie nam de rechterstoel over toen Helaman stierf?", "Zijn oudste zoon Nephi", ["Zijn jongste zoon Lehi", "Zijn broer Moronihah"], ["Nephi"]),
  ),
  ch("hel", 4,
    q("a", "2", "Waarheen gingen de weerspannigen die uit het land werden verdreven?", "Naar de koning van de Lamanieten", ["Naar de bergen in het noorden", "Naar het land van de Zoramieten"], ["koning van de Lamanieten"]),
    q("b", "10", "Hoeveel van hun bezittingen verloren de Nephieten aan de Lamanieten?", "De helft van al hun bezittingen", ["Een derde van al hun bezittingen", "Een tiende van al hun bezittingen"], ["helft van al hun bezittingen"]),
    q("c", "12", "Wat deden de Nephieten volgens vers 12 in hun goddeloosheid?", "Zij onderdrukten de armen", ["Zij verwaarloosden hun tempels", "Zij weigerden belasting te betalen"], ["armen"]),
  ),
  ch("hel", 5,
    q("a", "1", "Aan wie droeg Nephi de rechterstoel over?", "Aan Cezoram", ["Aan Pahoran", "Aan Moronihah"], ["Cezoram"]),
    q("b", "19", "Hoeveel Lamanieten werden door de prediking van Nephi en Lehi overtuigd?", "Achtduizend", ["Tweeduizend", "Vierduizend"], ["achtduizend"]),
    q("c", "24", "Wat omringde Nephi en Lehi in de gevangenis zonder hen te verbranden?", "Een vuurkolom", ["Een witte wolk", "Een muur van licht"], ["vuurkolom"]),
  ),
  ch("hel", 6,
    q("a", "10", "Hoe heetten het zuidelijke en het noordelijke land?", "Het zuiden Lehi, het noorden Mulek", ["Het zuiden Mulek, het noorden Lehi", "Het zuiden Nephi, het noorden Zarahemla"], ["Lehi", "Mulek"]),
    q("b", "15", "Wie werd in het zesenzestigste jaar door een onbekende hand vermoord?", "Cezoram", ["Moronihah", "Helaman"], ["Cezoram"]),
    q("c", "18", "Door wie was de bende van moordenaars en plunderaars opgericht?", "Door Kishkumen en Gadianton", ["Door Coriantumr en Tubaloth", "Door Pacumeni en Paänchi"], ["Kishkumen", "Gadianton"]),
  ),
  ch("hel", 7,
    q("a", "10", "Waar bevond Nephi zich toen hij zijn ziel voor God uitstortte?", "Op een toren in zijn tuin", ["In de tempel van Zarahemla", "Op een berg buiten de stad"], ["toren"]),
    q("b", "17", "Welke vraag stelde Nephi aan het volk in vers 17?", "Waarom wilt u sterven?", ["Waarom wilt u vluchten?", "Waarom wilt u rijkdom?"], ["waarom wilt u sterven"]),
    q("c", "25", "Met welke bende hadden de mensen zich verenigd?", "Met de geheime bende van Gadianton", ["Met de zwervers uit het noorden", "Met de Lamanieten uit de wildernis"], ["Gadianton"]),
  ),
  ch("hel", 8,
    q("a", "14", "Wat verhoogde Mozes in de woestijn?", "De koperen slang", ["Een koperen altaar", "Een koperen zee"], ["koperen slang"]),
    q("b", "17", "Wie zag de komst van Christus en was met blijdschap vervuld?", "Abraham", ["Noach", "Henoch"], ["Abraham"]),
    q("c", "21", "Wie van de zonen van Zedekia werd niet gedood?", "Mulek", ["Nephi", "Jozef"], ["Mulek"]),
  ),
  ch("hel", 9,
    q("a", "3", "Wat vonden de vijf mannen toen zij bij de rechterstoel kwamen?", "De opperrechter lag ter aarde gevallen", ["De rechterstoel was verlaten en leeg", "De opperrechter hield een volksvergadering"], ["ter aarde gevallen"]),
    q("b", "23", "Hoe heette de vermoorde opperrechter?", "Seëzoram", ["Moronihah", "Pacumeni"], ["Seëzoram"]),
    q("c", "26", "Naar het huis van wie moesten de mannen volgens Nephi gaan?", "Seantum", ["Pacumeni", "Paänchi"], ["Seantum"]),
  ),
  ch("hel", 10,
    q("a", "7", "Wat zal er volgens de Heer met wat Nephi op aarde verzegelt, in de hemel zijn?", "Het zal in de hemel verzegeld zijn", ["Het zal in de hemel worden herroepen", "Het zal in de hemel vergeten zijn"], ["in de hemel verzegeld"]),
    q("b", "8", "Wat zou er gebeuren als Nephi tot de tempel zei dat hij moest scheuren?", "De tempel zou doormidden scheuren", ["De tempel zou in vlammen opgaan", "De tempel zou in de grond zinken"], ["doormidden"]),
    q("c", "9", "Wat zou er gebeuren als Nephi tot de berg zei: Werp u neer?", "De berg zou vlak worden", ["De berg zou in vuur opgaan", "De berg zou in tweeën splijten"], ["vlak"]),
  ),
  ch("hel", 11,
    q("a", "4", "Wat vroeg Nephi dat er in het land zou heersen in plaats van het zwaard?", "Hongersnood", ["Aardbeving", "Overstroming"], ["hongersnood"]),
    q("b", "13", "Wat vroeg Nephi de Heer op het aardoppervlak te zenden?", "Regen", ["Vuur", "Sneeuw"], ["regen"]),
    q("c", "26", "Wat werden de afgescheidenen mettertijd?", "Een zeer grote bende rovers", ["Een machtig en vreedzaam volk", "Een leger van de Lamanieten"], ["bende rovers"]),
  ),
  ch("hel", 12,
    q("a", "7", "Met wat worden de mensenkinderen in vers 7 vergeleken, waarvan zij zelfs minder zijn?", "Minder dan het stof van de aarde", ["Minder dan het zand van de zee", "Minder dan een steen in de rivier"], ["stof van de aarde"]),
    q("b", "14", "Wat gebeurt er als God tot de aarde zegt: Ga terug?", "De dag wordt met vele uren verlengd", ["De nacht wordt met vele uren verlengd", "De zon gaat voor altijd onder"], ["vele uren"]),
    q("c", "23", "Wie zullen volgens deze verzen behouden worden?", "Zij die zich bekeren en luisteren", ["Zij die rijk zijn en veel offeren", "Zij die nooit hebben gezondigd"], ["bekeren en luisteren"]),
  ),
  ch("hel", 13,
    q("a", "2", "Wat was Samuel van afkomst?", "Een Lamaniet", ["Een Nephiet", "Een Zoramiet"], ["Lamaniet"]),
    q("b", "4", "Waarop klom Samuel toen men hem de stad niet binnen liet?", "Op de muur van de stad", ["Op de toren van de tempel", "Op een heuvel buiten de stad"], ["muur"]),
    q("c", "9", "Hoeveel jaar zouden er volgens de Heer verstrijken voordat Hij de Nephieten zou slaan?", "Geen vierhonderd jaar", ["Geen tweehonderd jaar", "Geen duizend jaar"], ["vierhonderd jaar"]),
  ),
  ch("hel", 14,
    q("a", "2", "Over hoeveel jaar zou de Zoon van God volgens Samuel komen?", "Over vijf jaar", ["Over tien jaar", "Over twintig jaar"], ["vijf jaar"]),
    q("b", "5", "Wat zal er volgens Samuel als teken aan de hemel verrijzen?", "Een nieuwe ster", ["Een nieuwe zon", "Een nieuwe maan"], ["nieuwe ster"]),
    q("c", "21", "Wat zal er volgens Samuel vele uren lang zijn als de Heer sterft?", "Donderslagen en bliksemschichten", ["Een aanhoudende hagelstorm van drie dagen", "Een sterke wind zonder weerlicht"], ["donderslagen"]),
  ),
  ch("hel", 15,
    q("a", "9", "Wat hebben de bekeerde Lamanieten volgens Samuel begraven?", "Hun oorlogswapens", ["Hun gouden afgoden", "Hun zilveren schatten"], ["oorlogswapens"]),
    q("b", "1", "Wat gebeurt er volgens Samuel met hun huis als het volk zich niet bekeert?", "Het wordt leeg achtergelaten", ["Het wordt in brand gestoken", "Het wordt aan de Lamanieten gegeven"], ["leeg"]),
    q("c", "16", "Wat zal de Heer volgens vers 16 met de Lamanieten doen?", "Hen niet volkomen vernietigen", ["Hen onmiddellijk bestraffen", "Hen voor altijd vergeten"], ["niet volkomen vernietigen"]),
  ),
  ch("hel", 16,
    q("a", "7", "Wat deed Samuel toen de mensen hun handen aan hem wilden slaan?", "Hij sprong van de muur af en vluchtte", ["Hij ging het volk tegemoet en sprak", "Hij verborg zich in de tempel"], ["van de muur af"]),
    q("b", "4", "Wat deed Nephi met hen die in Samuels woorden geloofden?", "Hij doopte hen en predikte bekering", ["Hij stuurde hen terug naar huis", "Hij liet hen offers brengen"], ["doopte"]),
    q("c", "13", "In welk regeringsjaar van de rechters werden er grote tekenen gegeven?", "In het negentigste jaar", ["In het tachtigste jaar", "In het honderdste jaar"], ["negentigste"]),
  ),
  // ===== EINDE =====
];
