import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Helamán (edición en español). Cada hecho está ligado a los versículos indicados en `verses`; `npm run genees:check` lo verifica.
export const helaman: GeneesChapterSeed[] = [
  ch("hel", 1,
    q("a", "3", "¿Cómo se llamaban los que se disputaban el asiento judicial?", "Pahorán, Paanqui y Pacumeni", ["Pahorán, Moroníah y Pacumeni", "Pahorán, Paanqui y Pacus"], ["Paanqui", "Pacumeni"]),
    q("b", "10", "¿Cómo se llamaba el hombre que asesinó a Pahorán?", "Kishkumen", ["Gadiantón", "Coriántumr"], ["Kishkumen"]),
    q("c", "15", "¿Cómo se llamaba el caudillo lamanita que tomó la ciudad de Zarahemla?", "Coriántumr, un disidente", ["Zerahemna, un disidente", "Lehonti, un disidente"], ["Coriántumr"]),
  ),
  ch("hel", 2,
    q("a", "4", "¿Quién era Gadiantón?", "Un hombre experto en muchas palabras", ["El nuevo juez superior del pueblo", "Un capitán de los ejércitos nefitas"], ["experto en muchas palabras"]),
    q("b", "6", "¿Quién detuvo a Kishkumen cuando quería destruir a Helamán?", "Un siervo de Helamán", ["Un guardia del rey", "Un sacerdote de Gadiantón"], ["de Helamán"]),
    q("c", "2", "¿Qué le confirió la voz del pueblo a Helamán, hijo de Helamán?", "Ocupar el asiento judicial", ["Dirigir el ejército del pueblo", "Administrar el templo"], ["asiento judicial"]),
  ),
  ch("hel", 3,
    q("a", "21", "¿Cómo se llamaban los dos hijos de Helamán?", "Nefi y Lehi, hermanos", ["Nefi y Shiblón, hermanos", "Lehi y Moroníah, hermanos"], ["Nefi", "Lehi"]),
    q("b", "9", "¿En qué vivían los que estaban en la tierra del norte?", "En tiendas y en casas de cemento", ["En cuevas y en casas de madera", "En ciudades de piedra y montañas"], ["cemento"]),
    q("c", "37", "¿Quién ocupó el asiento judicial cuando murió Helamán?", "Su hijo mayor Nefi", ["Su hijo menor Lehi", "Su hermano Moroníah"], ["Nefi"]),
  ),
  ch("hel", 4,
    q("a", "2", "¿Adónde fueron los rebeldes echados de la tierra?", "Al rey de los lamanitas", ["A las montañas del norte", "A la tierra de los zoramitas"], ["rey de los lamanitas"]),
    q("b", "10", "¿Qué parte de sus posesiones perdieron los nefitas ante los lamanitas?", "La mitad de sus posesiones", ["Un tercio de sus posesiones", "Una décima de sus posesiones"], ["mitad de sus posesiones"]),
    q("c", "12", "¿Qué hacían los nefitas en su maldad, según el versículo 12?", "Oprimían a los pobres", ["Descuidaban sus templos", "Se negaban a pagar impuestos"], ["a los pobres"]),
  ),
  ch("hel", 5,
    q("a", "1", "¿A quién entregó Nefi el asiento judicial?", "A un hombre llamado Cezóram", ["A un hombre llamado Pahorán", "A un hombre llamado Moroníah"], ["Cezóram"]),
    q("b", "19", "¿Cuántos lamanitas fueron convencidos por la predicación de Nefi y Lehi?", "Ocho mil lamanitas", ["Dos mil lamanitas", "Cuatro mil lamanitas"], ["ocho mil"]),
    q("c", "24", "¿Qué rodeaba a Nefi y a Lehi en la cárcel sin quemarlos?", "Un pilar de fuego", ["Una nube blanca", "Un muro de luz"], ["pilar de fuego"]),
  ),
  ch("hel", 6,
    q("a", "10", "¿Cómo se llamaban la tierra del sur y la del norte?", "La del sur Lehi y la del norte Mulek", ["La del sur Mulek y la del norte Lehi", "La del sur Nefi y la del norte Zarahemla"], ["Lehi", "Mulek"]),
    q("b", "15", "¿Quién fue asesinado por mano desconocida en el año sesenta y seis?", "El juez Cezóram", ["El juez Moroníah", "El juez Helamán"], ["Cezóram"]),
    q("c", "18", "¿Por quiénes había sido formada la banda de asesinos y ladrones?", "Por Kishkumen y Gadiantón", ["Por Coriántumr y Tubaloth", "Por Pacumeni y Paanqui"], ["Kishkumen", "Gadiantón"]),
  ),
  ch("hel", 7,
    q("a", "10", "¿Dónde estaba Nefi cuando derramó su alma ante Dios?", "En una torre de su jardín", ["En el templo de Zarahemla", "En una montaña fuera de la ciudad"], ["torre"]),
    q("b", "17", "¿Qué pregunta hizo Nefi al pueblo en el versículo 17?", "¿Por qué deseáis morir?", ["¿Por qué deseáis huir?", "¿Por qué deseáis riquezas?"], ["por qué deseáis morir"]),
    q("c", "25", "¿A qué banda se habían unido las personas?", "A la banda secreta de Gadiantón", ["A los vagabundos del norte", "A los lamanitas del desierto"], ["Gadiantón"]),
  ),
  ch("hel", 8,
    q("a", "14", "¿Qué levantó Moisés en el desierto?", "La serpiente de bronce", ["Un gran altar de bronce", "Un gran mar de bronce"], ["serpiente de bronce"]),
    q("b", "17", "¿Quién vio la venida del Mesías y se llenó de alegría?", "El profeta Abraham", ["El profeta Noé", "El profeta Enoc"], ["Abraham"]),
    q("c", "21", "¿Cuál de los hijos de Sedequías no fue muerto?", "Su hijo Mulek", ["Su hijo Nefi", "Su hijo José"], ["Mulek"]),
  ),
  ch("hel", 9,
    q("a", "3", "¿Qué hallaron los cinco hombres al llegar al asiento judicial?", "El juez superior había caído a tierra", ["El asiento judicial estaba vacío", "El juez superior presidía una asamblea"], ["caído a tierra"]),
    q("b", "23", "¿Cómo se llamaba el juez superior asesinado?", "Seezóram", ["Moroníah", "Pacumeni"], ["Seezóram"]),
    q("c", "26", "¿A casa de quién debían ir los hombres, según Nefi?", "A casa de Seántum", ["A casa de Pacumeni", "A casa de Paanqui"], ["Seántum"]),
  ),
  ch("hel", 10,
    q("a", "7", "¿Qué sucederá en los cielos con lo que Nefi selle en la tierra?", "Será sellado en los cielos", ["Será revocado en los cielos", "Será olvidado en los cielos"], ["sellado en los cielos"]),
    q("b", "8", "¿Qué sucedería si Nefi dijera al templo que se partiera por la mitad?", "El templo se partiría por la mitad", ["El templo se incendiaría", "El templo se hundiría en la tierra"], ["por la mitad"]),
    q("c", "9", "¿Qué sucedería si Nefi dijera a la montaña: Derrúmbate?", "La montaña quedaría llana", ["La montaña se incendiaría", "La montaña se partiría en dos"], ["llana"]),
  ),
  ch("hel", 11,
    q("a", "4", "¿Qué pidió Nefi que hubiera en la tierra en lugar de la espada?", "Hambre sobre toda la tierra", ["Un terremoto sobre la tierra", "Una inundación sobre la tierra"], ["hambre"]),
    q("b", "13", "¿Qué pidió Nefi al Señor que enviara sobre la faz de la tierra?", "Lluvia sobre la tierra", ["Fuego sobre la tierra", "Nieve sobre la tierra"], ["lluvia"]),
    q("c", "26", "¿En qué se convirtieron los disidentes con el tiempo?", "En una gran banda de ladrones", ["En un pueblo poderoso y pacífico", "En un ejército de los lamanitas"], ["banda"]),
  ),
  ch("hel", 12,
    q("a", "7", "¿Con qué se compara la insignificancia de los hijos de los hombres en el versículo 7?", "Son menos que el polvo de la tierra", ["Son menos que la arena del mar", "Son menos que una piedra del río"], ["polvo de la tierra"]),
    q("b", "14", "¿Qué sucede cuando Dios dice a la tierra: Vuélvete atrás?", "El día se alarga muchas horas", ["La noche se alarga muchas horas", "El sol se pone para siempre"], ["muchas horas"]),
    q("c", "23", "¿Quiénes serán salvos, según estos versículos?", "Los que se arrepientan y escuchen", ["Los ricos que hacen muchas ofrendas", "Los que jamás han pecado en su vida"], ["escuch"]),
  ),
  ch("hel", 13,
    q("a", "2", "¿De qué pueblo era Samuel?", "Un lamanita", ["Un nefita", "Un zoramita"], ["lamanita"]),
    q("b", "4", "¿Sobre qué subió Samuel cuando no le permitieron entrar en la ciudad?", "Sobre la muralla de la ciudad", ["Sobre la torre del templo", "Sobre una colina fuera de la ciudad"], ["muralla"]),
    q("c", "9", "¿Cuántos años pasarían antes de que el Señor hiriera a los nefitas?", "Menos de cuatrocientos años", ["Menos de doscientos años", "Menos de ochocientos años"], ["cuatrocientos años"]),
  ),
  ch("hel", 14,
    q("a", "2", "¿Dentro de cuántos años vendría el Hijo de Dios, según Samuel?", "Dentro de cinco años", ["Dentro de diez años", "Dentro de veinte años"], ["cinco años"]),
    q("b", "5", "¿Qué señal aparecerá en el cielo, según Samuel?", "Una estrella nueva", ["Un nuevo sol radiante", "Una nueva luna llena"], ["estrella nueva"]),
    q("c", "21", "¿Qué habrá durante muchas horas cuando el Señor entregue el espíritu?", "Truenos y relámpagos fuertes", ["Una granizada de tres días", "Un viento fuerte sin relámpagos"], ["truenos y relámpagos"]),
  ),
  ch("hel", 15,
    q("a", "9", "¿Qué han enterrado los lamanitas convertidos, según Samuel?", "Sus armas de guerra", ["Sus ídolos de oro", "Sus tesoros de plata"], ["armas de guerra"]),
    q("b", "1", "¿Qué sucederá con las casas del pueblo si no se arrepiente, según Samuel?", "Les quedarán desiertas y vacías", ["Serán incendiadas por el fuego", "Serán entregadas a los lamanitas"], ["desiertas"]),
    q("c", "16", "¿Qué hará el Señor con los lamanitas, según el versículo 16?", "No los destruirá completamente", ["Los castigará de inmediato", "Los olvidará para siempre"], ["completamente"]),
  ),
  ch("hel", 16,
    q("a", "7", "¿Qué hizo Samuel cuando el pueblo quiso echarle mano?", "Se dejó caer desde la muralla y huyó", ["Fue al encuentro del pueblo y habló", "Se escondió en el templo de la ciudad"], ["desde la muralla"]),
    q("b", "4", "¿Qué hizo Nefi con los que creyeron en las palabras de Samuel?", "Los bautizó y predicó arrepentimiento", ["Los envió tranquilamente a sus casas", "Les hizo ofrecer muchos sacrificios"], ["bautiz"]),
    q("c", "13", "¿En qué año del gobierno de los jueces se dieron grandes señales al pueblo?", "En el año noventa", ["En el año ochenta", "En el año cien"], ["año noventa"]),
  ),
  // ===== EINDE =====
];
