import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Jacob (edición en español). Cada hecho está ligado a los versículos indicados en `verses`; `npm run genees:check` lo verifica.
export const jakob: GeneesChapterSeed[] = [
  ch("jacob", 1,
    q("a", "1", "¿Cuántos años habían pasado desde que Lehi salió de Jerusalén cuando Nefi le dio un mandato a Jacob?", "Cincuenta y cinco años", ["Treinta y cinco años", "Setenta y cinco años"], ["cincuenta y cinco años"]),
    q("b", "11", "¿Cómo llamó el pueblo a los reyes que sucedieron a Nefi?", "Nefi segundo", ["Nefi el Menor", "Lehi segundo"], ["Nefi segundo"]),
    q("c", "18", "¿Por mano de quién fueron consagrados Jacob y José como sacerdotes y maestros?", "Por mano de Nefi", ["Por mano de Lehi", "Por mano de Sam"], ["mano de Nefi"]),
  ),
  ch("jacob", 2,
    q("a", "12", "¿Qué habían empezado a buscar muchos del pueblo, según Jacob?", "Oro y plata", ["Tierras y ganado", "Poder y fama"], ["oro", "plata"]),
    q("b", "27", "¿Cuántas esposas puede tener un hombre entre este pueblo, según el Señor?", "No más de una esposa", ["No más de dos esposas", "No más de siete esposas"], ["una esposa"]),
    q("c", "18", "¿Qué debe buscarse antes de buscar riquezas, según Jacob?", "El reino de Dios", ["El favor del rey", "Un terreno propio"], ["reino de Dios"]),
  ),
  ch("jacob", 3,
    q("a", "14", "¿Cómo se llaman las planchas en las que escribe Jacob?", "Las planchas de Jacob", ["Las planchas de Sam", "Las planchas de José"], ["planchas de Jacob"]),
    q("b", "9", "¿Qué manda Jacob al pueblo respecto de los lamanitas?", "No injuriarlos por su color de piel", ["Expulsarlos de la tierra", "Enseñarles a leer y a escribir"], ["injuri"]),
    q("c", "1", "¿A quién quiere dirigirse Jacob primero en este capítulo?", "A los puros de corazón", ["A los ricos en oro", "A los que abandonaron la ley"], ["puros de corazón"]),
  ),
  ch("jacob", 4,
    q("a", "5", "¿Por qué guardan Jacob y su pueblo la ley de Moisés?", "Porque orienta sus almas hacia Cristo", ["Porque el rey se lo exige", "Porque si no perderían su tierra"], ["orienta"]),
    q("b", "9", "¿Por qué poder fue creada la tierra, según Jacob?", "Por el poder de su palabra", ["Por el poder de su brazo", "Por la ayuda de los ángeles"], ["poder de su palabra"]),
    q("c", "16", "¿En qué llegará a convertirse la roca que los judíos rechazan, según las Escrituras?", "En el seguro fundamento", ["En un adorno para el rey", "En la puerta del templo"], ["seguro fundamento"]),
  ),
  ch("jacob", 5,
    q("a", "3", "¿Con qué compara el Señor a la casa de Israel, según Zenós?", "Con un olivo cultivado", ["Con una vid silvestre", "Con una higuera cultivada"], ["olivo cultivado"]),
    q("b", "41", "¿Qué le preguntó llorando el Señor de la viña a su siervo?", "¿Qué más pude haber hecho?", ["¿Por qué no me advertiste?", "¿Quién plantó estos árboles?"], ["qué más pude"]),
    q("c", "50", "¿Qué dijo el siervo cuando el Señor quería cortar los árboles?", "Déjala un poco más de tiempo", ["Llama a los nuevos siervos", "Córtalos todos ahora mismo"], ["déjala un poco más"]),
  ),
  ch("jacob", 6,
    q("a", "6", "¿Qué pregunta les hace Jacob a los que endurecen su corazón?", "¿Por qué queréis morir?", ["¿Por qué queréis partir?", "¿Por qué queréis pelear?"], ["por qué queréis morir"]),
    q("b", "11", "¿Por cuál puerta debe entrarse, según Jacob?", "Por la puerta estrecha", ["Por la puerta de oro", "Por la puerta oriental"], ["puerta estrecha"]),
    q("c", "3", "¿Qué sucederá con el mundo, según Jacob?", "Será quemado con fuego", ["Será inundado por las aguas", "Será destruido por la tempestad"], ["quemado con fuego"]),
  ),
  ch("jacob", 7,
    q("a", "1", "¿Cómo se llamaba el hombre que predicaba entre el pueblo que no habría Cristo?", "Sherem", ["Korihor", "Zeezrom"], ["Sherem"]),
    q("b", "15", "¿Qué le sucedió a Sherem cuando Jacob terminó de hablar?", "Cayó a tierra por el poder divino", ["Huyó de noche de la tierra", "Fue encarcelado por el pueblo"], ["cayó a tierra"]),
    q("c", "27", "¿A quién entregó Jacob las planchas?", "A su hijo Enós", ["A su hermano José", "A su hijo Jarom"], ["Enós"]),
  ),
  // ===== EINDE =====
];
