import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Mosíah (edición en español). Cada hecho está ligado a los versículos indicados en `verses`; `npm run genees:check` lo verifica.
export const mosiah: GeneesChapterSeed[] = [
  ch("mosiah", 1,
    q("a", "2", "¿Cómo se llamaban los tres hijos del rey Benjamín?", "Mosíah, Helorum y Helamán", ["Mosíah, Benjamín y Helamán", "Mosíah, Helorum y Amalekí"], ["Mosíah", "Helorum", "Helamán"]),
    q("b", "16", "¿Qué objeto recibió Mosíah, además de las planchas?", "La espada de Labán", ["La corona de Sedequías", "El arca del convenio"], ["espada de Labán"]),
    q("c", "12", "¿Qué nunca será borrado, sino por causa de transgresión, según el rey Benjamín?", "El nombre que les dará", ["El templo que edificarán", "La ley que recibirán"], ["nombre"]),
  ),
  ch("mosiah", 2,
    q("a", "7", "¿Qué hizo construir el rey Benjamín para que el pueblo oyera sus palabras?", "Una torre", ["Un puente", "Un altar"], ["torre"]),
    q("b", "17", "¿Qué son los hombres, según Benjamín, cuando sirven a sus semejantes?", "Solo están al servicio de Dios", ["Solo están al servicio del rey", "Solo están al servicio de sí mismos"], ["al servicio"]),
    q("c", "14", "¿Con qué trabajó el rey Benjamín para poder servir a su pueblo?", "Con sus propias manos", ["Con la ayuda de esclavos", "Con sus siervos y soldados"], ["propias manos"]),
  ),
  ch("mosiah", 3,
    q("a", "8", "¿Qué nombre y qué madre menciona el ángel para el Señor que vendrá?", "Jesucristo, y su madre María", ["Emanuel, y su madre Sara", "Juan, y su madre Elisabet"], ["Jesucristo", "María"]),
    q("b", "10", "¿Cuándo resucitará de entre los muertos, según el ángel?", "Al tercer día", ["Al séptimo día", "Al décimo día"], ["tercer día"]),
    q("c", "19", "¿Qué es el hombre natural, según el versículo 19, a menos que se someta al Santo Espíritu?", "Enemigo de Dios", ["Amigo del mundo", "Siervo de la ley"], ["enemigo de Dios"]),
  ),
  ch("mosiah", 4,
    q("a", "1", "¿Cómo estaba la gente cuando el rey Benjamín miró a la multitud?", "Habían caído a tierra", ["Habían huido despavoridos", "Se habían quedado dormidos"], ["caído a tierra"]),
    q("b", "19", "¿Cómo nos llama Benjamín en nuestra dependencia de Dios?", "Todos somos mendigos", ["Todos somos ricos", "Todos somos gobernantes"], ["mendigos"]),
    q("c", "14", "¿Qué no consentiréis que padezcan vuestros hijos, según Benjamín?", "Que anden hambrientos ni desnudos", ["Que sufran castigo o enfermedad", "Que pasen sed o sufran frío"], ["hambrientos", "desnudos"]),
  ),
  ch("mosiah", 5,
    q("a", "7", "¿Cómo serán llamados los hombres, según Benjamín, por razón del convenio?", "Progenie de Cristo", ["Siervos del rey Benjamín", "Hijos de Benjamín"], ["progenie de Cristo"]),
    q("b", "5", "¿Qué estaban dispuestos a hacer en el convenio con Dios?", "Hacer su voluntad y obedecerle", ["Dar todos sus bienes al rey", "Dejar la tierra y vivir en otro lugar"], ["voluntad"]),
    q("c", "14", "¿Qué animal que pertenece a su vecino no guardaría nadie para sí, según Benjamín?", "Un asno", ["Un buey", "Un caballo"], ["asno"]),
  ),
  ch("mosiah", 6,
    q("a", "4", "¿En qué año de su vida empezó a reinar Mosíah?", "En el trigésimo", ["En el vigésimo", "En el cuadragésimo"], ["trigésimo"]),
    q("b", "5", "¿Cuántos años más vivió el rey Benjamín después de que Mosíah fue rey?", "Tres años más", ["Siete años más", "Diez años más"], ["tres años"]),
    q("c", "7", "¿Cómo evitó el rey Mosíah ser una carga para su pueblo?", "Él mismo labraba la tierra", ["Hacía que esclavos labraran su tierra", "Pedía regalos al pueblo"], ["labraba la tierra"]),
  ),
  ch("mosiah", 7,
    q("a", "3", "¿Quién era el caudillo de los hombres fuertes que subieron a la tierra de Lehi-Nefi?", "Ammón", ["Limhi", "Zeniff"], ["Ammón"]),
    q("b", "4", "¿Cuántos días anduvieron errantes por el desierto?", "Cuarenta días", ["Catorce días", "Setenta días"], ["cuarenta días"]),
    q("c", "9", "¿Quién era el rey del pueblo en la tierra de Nefi a quien encontró Ammón?", "Limhi, hijo de Noé", ["Lamán, hijo de Zeniff", "Noé, hijo de Limhi"], ["Limhi", "Noé"]),
  ),
  ch("mosiah", 8,
    q("a", "9", "¿De qué eran las veinticuatro planchas que trajeron los hombres de Limhi?", "De oro puro", ["De bronce puro", "De plata pura"], ["oro puro"]),
    q("b", "15", "¿Qué es un vidente, según el rey Limhi?", "Mayor que un profeta", ["Igual que un sacerdote", "Menor que un rey"], ["mayor que un profeta"]),
    q("c", "7", "¿Cuántos hombres envió Limhi al desierto para hallar la tierra de Zarahemla?", "Cuarenta y tres hombres", ["Treinta y tres hombres", "Sesenta y tres hombres"], ["cuarenta y tres"]),
  ),
  ch("mosiah", 9,
    q("a", "1", "¿Quién escribió Mosíah 9?", "Zeniff", ["Ammón", "Mormón"], ["Zeniff"]),
    q("b", "11", "¿Cuántos años habían vivido en la tierra cuando el rey Lamán empezó a inquietarse?", "Doce años", ["Seis años", "Veinte años"], ["doce años"]),
    q("c", "18", "¿A cuántos lamanitas mató el pueblo de Zeniff en un día y una noche?", "Tres mil cuarenta y tres", ["Dos mil cuarenta y tres", "Cinco mil cuarenta y siete"], ["tres mil cuarenta y tres"]),
  ),
  ch("mosiah", 10,
    q("a", "3", "¿Cuántos años poseyó el pueblo de Zeniff la tierra de sus padres?", "Veintidós años", ["Veintiocho años", "Treinta y dos años"], ["veintidós años"]),
    q("b", "5", "¿Qué hizo Zeniff que hicieran las mujeres de su pueblo?", "Hilar, trabajar y tejer telas", ["Cocinar y enseñar a los niños", "Forjar armas y hacer escudos"], ["hilar"]),
    q("c", "9", "¿Dónde hizo Zeniff que se ocultaran las mujeres y los niños de su pueblo?", "En el desierto", ["En la gran torre", "Detrás de los muros"], ["desierto"]),
  ),
  ch("mosiah", 11,
    q("a", "3", "¿Qué parte de todo lo que poseían exigió el rey Noé como tributo?", "La quinta parte", ["La décima parte", "La tercera parte"], ["quinta parte"]),
    q("b", "20", "¿Cómo se llamaba el profeta que empezó a profetizar entre el pueblo del rey Noé?", "Abinadí", ["Amulón", "Gedeón"], ["Abinadí"]),
    q("c", "12", "¿Qué edificó el rey Noé cerca del templo?", "Una torre muy alta", ["Un gran altar de oro", "Una ancha muralla"], ["torre muy alta"]),
  ),
  ch("mosiah", 12,
    q("a", "3", "¿Con qué comparó Abinadí la vida del rey Noé?", "Con un vestido en un horno", ["Con una flor del campo", "Con una piedra en el río"], ["vestido en un horno"]),
    q("b", "17", "¿Qué hizo el rey Noé con Abinadí?", "Mandó que lo encarcelaran", ["Lo hizo matar de inmediato", "Lo hizo desterrar del país"], ["encarcela"]),
    q("c", "28", "¿Qué dijeron los sacerdotes del rey Noé que enseñaban?", "La ley de Moisés", ["La ley de Noé", "La ley del rey"], ["ley de Moisés"]),
  ),
  ch("mosiah", 13,
    q("a", "16", "¿Qué día debe recordarse y santificarse según el mandamiento?", "El día de reposo", ["El primer día", "El día de la cosecha"], ["día de reposo"]),
    q("b", "28", "¿Qué dice Abinadí acerca de la salvación y la ley de Moisés?", "La salvación no viene solo por la ley", ["La salvación viene solo por la ley", "La salvación viene solo por los sacrificios"], ["no viene solo por la ley"]),
    q("c", "24", "¿Qué no se debe codiciar según el mandamiento?", "La casa de tu prójimo", ["El campo del rey", "El oro de los sacerdotes"], ["casa de tu prójimo"]),
  ),
  ch("mosiah", 14,
    q("a", "6", "¿Con qué nos compara Isaías a todos los que nos hemos descarriado?", "Con ovejas", ["Con cabras", "Con bueyes"], ["ovejas"]),
    q("b", "3", "¿Cómo se le llama en el versículo 3?", "Varón de dolores", ["Varón de guerra", "Varón de sabiduría"], ["varón de dolores"]),
    q("c", "7", "¿Con qué se le compara cuando fue oprimido?", "Con un cordero al degolladero", ["Con un león atrapado en la red", "Con un toro para la ofrenda"], ["cordero al degolladero"]),
  ),
  ch("mosiah", 15,
    q("a", "14", "¿Qué mensaje dicen a Sion los profetas santos, según Abinadí?", "¡Tu Dios reina!", ["¡Tu rey viene!", "¡Tu pueblo es salvo!"], ["Tu Dios reina"]),
    q("b", "25", "¿Qué tienen los niños pequeños, según Abinadí?", "La vida eterna", ["Un reino propio", "Un castigo severo"], ["vida eterna"]),
    q("c", "21", "¿Cómo se llama la resurrección de la que habla Abinadí en el versículo 21?", "La primera resurrección", ["La última resurrección", "La tercera resurrección"], ["primera resurrección"]),
  ),
  ch("mosiah", 16,
    q("a", "8", "¿Qué es consumido en Cristo, según Abinadí?", "El aguijón de la muerte", ["El poder de las tinieblas", "La ley de Moisés"], ["aguijón de la muerte"]),
    q("b", "9", "¿Qué es Cristo para el mundo, según Abinadí?", "La luz y la vida del mundo", ["El juez y el pastor del mundo", "El rey y el guardián del mundo"], ["luz y la vida del mundo"]),
    q("c", "14", "¿De qué es símbolo la ley de Moisés, según Abinadí?", "De cosas que están por venir", ["De los profetas del pasado", "De los primeros reyes de Israel"], ["por venir"]),
  ),
  ch("mosiah", 17,
    q("a", "2", "¿Cómo se llamaba el joven entre los sacerdotes que creyó las palabras de Abinadí?", "Alma, descendiente de Nefi", ["Limhi, hijo del rey Noé", "Helam, hijo de un sacerdote"], ["Alma"]),
    q("b", "20", "¿Cómo murió Abinadí?", "Murió por fuego", ["Murió por la espada", "Murió apedreado"], ["por fuego"]),
    q("c", "6", "¿Después de cuántos días mandó el rey que Abinadí fuera llevado otra vez ante él?", "Después de tres días", ["Después de siete días", "Después de dos días"], ["tres días"]),
  ),
  ch("mosiah", 18,
    q("a", "5", "¿Cómo se llamaba el lugar con una fuente de agua pura donde estaba Alma?", "Mormón", ["Helam", "Shilom"], ["Mormón"]),
    q("b", "16", "¿Aproximadamente cuántas almas bautizó Alma en las aguas de Mormón?", "Unas doscientas cuatro almas", ["Unas cuatrocientas cuatro almas", "Unas ciento cuatro almas"], ["doscientas cuatro"]),
    q("c", "18", "¿Cuántos sacerdotes ordenó Alma en relación con el número de personas?", "Un sacerdote por cada cincuenta", ["Un sacerdote por cada cien", "Un sacerdote por cada veinte"], ["por cada cincuenta"]),
  ),
  ch("mosiah", 19,
    q("a", "4", "¿Quién sacó su espada contra el rey Noé?", "Gedeón", ["Limhi", "Helam"], ["Gedeón"]),
    q("b", "20", "¿Qué hicieron los hombres con el rey Noé después de que les mandó que no volvieran?", "Lo hicieron morir por fuego", ["Lo dejaron libre en el desierto", "Lo llevaron de vuelta a su palacio"], ["por fuego"]),
    q("c", "26", "¿Qué juró Limhi al rey de los lamanitas?", "Que su pueblo le pagaría tributo", ["Que su pueblo dejaría la tierra", "Que su pueblo lo adoraría como a un dios"], ["pagaría tributo"]),
  ),
  ch("mosiah", 20,
    q("a", "5", "¿Cuántas hijas de los lamanitas fueron secuestradas por los sacerdotes de Noé?", "Veinticuatro hijas", ["Veintiséis hijas", "Veintiuna hijas"], ["veinticuatro"]),
    q("b", "10", "¿Con qué se compara la lucha del pueblo de Limhi?", "Con leones por su presa", ["Con lobos por su rebaño", "Con osos por sus cachorros"], ["leones"]),
    q("c", "17", "¿Quién era el capitán del rey que le rogó que se refrenara y no investigara al pueblo?", "Gedeón", ["Helam", "Amulón"], ["Gedeón"]),
  ),
  ch("mosiah", 21,
    q("a", "26", "¿De qué estaba cubierta la tierra que hallaron los hombres de Limhi?", "De huesos secos", ["De densa niebla", "De estatuas de oro"], ["huesos secos"]),
    q("b", "17", "¿Qué mandó el rey Limhi que hiciera cada hombre a causa de las muchas viudas?", "Dar para el sostén de las viudas", ["Dar la décima parte de su cosecha al rey", "Casarse con una viuda de su familia"], ["sostén de las viudas"]),
    q("c", "33", "¿Por qué no pudieron bautizarse Limhi y su pueblo?", "Nadie tenía la autoridad de Dios", ["No había agua suficiente en la tierra", "El rey Lamán lo había prohibido a todos"], ["autoridad de Dios"]),
  ),
  ch("mosiah", 22,
    q("a", "6", "¿Por dónde propuso Gedeón escapar?", "Por el muro posterior de la ciudad", ["Por la gran puerta de la ciudad", "Por el río, en barcos grandes"], ["muro posterior"]),
    q("b", "10", "¿Qué envió Limhi a los lamanitas como tributo y regalo?", "Vino en abundancia", ["Grano en abundancia", "Carne en abundancia"], ["vino"]),
    q("c", "13", "¿A qué tierra llegó el pueblo de Limhi después de muchos días en el desierto?", "A la tierra de Zarahemla", ["A la tierra de Helam", "A la tierra de Shilom"], ["Zarahemla"]),
  ),
  ch("mosiah", 23,
    q("a", "3", "¿Cuántos días huyó el pueblo de Alma en el desierto?", "Ocho días", ["Cuatro días", "Doce días"], ["ocho días"]),
    q("b", "19", "¿Qué nombre dio el pueblo de Alma a la tierra donde se estableció?", "La tierra de Helam", ["La tierra de Mormón", "La tierra de Lehi"], ["Helam"]),
    q("c", "6-7", "¿A quién deseaba el pueblo de Alma como rey?", "A Alma, pero se negó", ["A Gedeón, pero se negó", "A Helam, pero se negó"], ["Alma"]),
  ),
  ch("mosiah", 24,
    q("a", "20", "¿Qué nombre dieron Alma y su pueblo al valle donde plantaron sus tiendas?", "El valle de Alma", ["El valle de Helam", "El valle de Amulón"], ["Alma"]),
    q("b", "19", "¿Qué hizo el Señor cuando escaparon de los lamanitas?", "Hizo que cayera un profundo sueño", ["Hizo que se levantara una gran tormenta", "Hizo desaparecer las armas de ellos"], ["profundo sueño"]),
    q("c", "25", "¿Después de cuántos días en el desierto llegó el pueblo de Alma a Zarahemla?", "Después de doce días", ["Después de seis días", "Después de cuarenta días"], ["doce días"]),
  ),
  ch("mosiah", 25,
    q("a", "23", "¿Cuántas iglesias había en la tierra de Zarahemla?", "Siete iglesias", ["Tres iglesias", "Doce iglesias"], ["siete"]),
    q("b", "17", "¿Quién deseó bautizarse después de que Alma enseñó al pueblo?", "El rey Limhi", ["El rey Mosíah", "El rey Noé"], ["Limhi"]),
    q("c", "2", "¿De quién era descendiente el pueblo de Zarahemla?", "De Mulek", ["De Nefi", "De Lamán"], ["Mulek"]),
  ),
  ch("mosiah", 26,
    q("a", "8", "¿Quién había recibido del rey Mosíah la autoridad sobre la iglesia?", "Alma, el sumo sacerdote", ["Limhi, el antiguo rey", "Helam, el primer bautizado"], ["Alma"]),
    q("b", "22", "¿Para qué es bautizado el que se bautiza, según el Señor?", "Para arrepentimiento", ["Para ser rico y poderoso", "Para tener plena libertad"], ["arrepentimiento"]),
    q("c", "30", "¿Cuántas veces perdona el Señor las transgresiones de su pueblo que se arrepiente?", "Cuantas veces se arrepienta", ["Como máximo siete veces al año", "Solo en la primera transgresión"], ["cuantas veces"]),
  ),
  ch("mosiah", 27,
    q("a", "11", "¿Quién se apareció a Alma el joven y a los hijos de Mosíah?", "El ángel del Señor", ["El profeta Abinadí", "El rey de Zarahemla"], ["ángel del Señor"]),
    q("b", "23", "¿Cuánto tiempo ayunaron y oraron los sacerdotes y el pueblo antes de que los miembros de Alma recobraran su fuerza?", "Dos días y dos noches", ["Tres días y tres noches", "Siete días y siete noches"], ["dos días y dos noches"]),
    q("c", "34", "¿Quiénes eran los cuatro hijos de Mosíah?", "Ammón, Aarón, Omner e Himni", ["Ammón, Aarón, Helam y Gedeón", "Ammón, Omner, Himni y Limhi"], ["Ammón", "Aarón", "Omner", "Himni"]),
  ),
  ch("mosiah", 28,
    q("a", "5", "¿Adónde querían ir los hijos de Mosíah para predicar?", "A la tierra de Nefi", ["A la tierra de Helam", "A la tierra de Shilom"], ["tierra de Nefi"]),
    q("b", "13", "¿Con qué tradujo Mosíah los anales del pueblo destruido?", "Con dos piedras en dos aros de un arco", ["Con unos anteojos de oro y plata", "Con un rollo de fino pergamino"], ["dos piedras"]),
    q("c", "20", "¿A quién entregó Mosíah las planchas de bronce y los objetos?", "A Alma, hijo de Alma", ["A Ammón, su hijo mayor", "A Omner, su hijo menor"], ["Alma"]),
  ),
  ch("mosiah", 29,
    q("a", "2", "¿A quién quiso el pueblo primero como rey?", "A Aarón", ["A Ammón", "A Himni"], ["Aarón"]),
    q("b", "42", "¿Quién fue nombrado primer juez superior?", "Alma, hijo de Alma", ["Aarón, hijo de Mosíah", "Limhi, hijo de Noé"], ["Alma"]),
    q("c", "46", "¿En qué año de su reinado murió Mosíah?", "En el trigésimotercer año", ["En el vigésimotercer año", "En el cuadragésimotercer año"], ["trigésimotercer"]),
  ),
  // ===== EINDE =====
];
