import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 4 Nefi, Mormón, Éter y Moroni (edición en español). Cada hecho está ligado a los versículos indicados en `verses`; `npm run genees:check` lo verifica.
export const slot: GeneesChapterSeed[] = [
  ch("4-ne", 1,
    q("a", "3", "¿Qué tenían entre sí las personas después de su conversión?", "Tenían en común todas las cosas", ["Tenían todo como propiedad privada", "Todo pertenecía a los jueces"], ["en común"]),
    q("b", "17", "¿En qué se habían convertido las personas, según el versículo 17?", "En un solo pueblo, hijos de Cristo", ["En una sociedad de muchas clases", "En nefitas y lamanitas separados"], ["hijos de Cristo"]),
    q("c", "48", "¿Quién ocultó los anales sagrados para el Señor?", "Un hombre llamado Ammarón", ["Un hombre llamado Mormón", "Un hombre llamado Moroni"], ["Ammarón"]),
  ),
  ch("morm", 1,
    q("a", "2", "¿Qué edad tenía Mormón cuando Ammarón vino a él?", "Unos diez años", ["Unos catorce años", "Unos siete años"], ["diez años"]),
    q("b", "3", "¿Cuándo debía recordar Mormón lo que había observado, según Ammarón?", "Cuando tuviera unos veinticuatro años", ["Cuando tuviera unos treinta años", "Cuando tuviera unos dieciocho años"], ["veinticuatro años"]),
    q("c", "15", "¿Qué edad tenía Mormón cuando lo visitó el Señor?", "A los quince años", ["A los doce años", "A los veinte años"], ["quince años"]),
  ),
  ch("morm", 2,
    q("a", "2", "¿A qué edad salió Mormón contra los lamanitas a la cabeza de un ejército?", "A los quince años", ["A los dieciocho años", "A los veinte años"], ["quince años"]),
    q("b", "9", "¿Cómo se llamaba el rey de los lamanitas que atacó con un gran ejército?", "El rey Aarón", ["El rey Lamoni", "El rey Ammorón"], ["Aarón"]),
    q("c", "29", "¿Qué dieron los lamanitas a los nefitas en el tratado?", "La región del norte", ["La región del sur", "La tierra de Zarahemla"], ["región del norte"]),
  ),
  ch("morm", 3,
    q("a", "11", "¿Qué se negó a ser Mormón por la iniquidad del pueblo?", "Su comandante y caudillo", ["Su rey y su juez supremo", "Su sacerdote y su maestro"], ["comandante"]),
    q("b", "13", "¿Cuántas veces había librado Mormón a su pueblo de las manos de sus enemigos?", "Tres veces", ["Dos veces", "Siete veces"], ["tres veces"]),
    q("c", "17", "¿A quiénes escribe Mormón, según el versículo 17?", "A los gentiles y a la casa de Israel", ["Solo a los nefitas de su tiempo", "Al rey y a todos sus capitanes de guerra"], ["gentiles", "casa de Israel"]),
  ),
  ch("morm", 4,
    q("a", "2", "¿Hasta qué tierra fueron rechazados los ejércitos nefitas?", "Hasta la tierra de Desolación", ["Hasta la tierra de Jersón", "Hasta la tierra de Zarahemla"], ["Desolación"]),
    q("b", "5", "¿Por quiénes son castigados los inicuos, según Mormón?", "Por los mismos inicuos", ["Por los ángeles del cielo", "Por los justos de la tierra"], ["inicuos"]),
    q("c", "23", "¿Adónde fue Mormón cuando los lamanitas estaban a punto de subyugar la tierra?", "A la colina de Shim", ["A la colina de Manti", "A la colina de Riplah"], ["colina de Shim"]),
  ),
  ch("morm", 5,
    q("a", "17", "¿A quién tuvieron los nefitas en un tiempo por pastor?", "A Cristo por pastor", ["A Moisés por pastor", "A Nefi por pastor"], ["Cristo por pastor"]),
    q("b", "18", "¿A qué se compara al pueblo llevado por Satanás?", "Al tamo que se lleva el viento", ["A una oveja que se aparta del rebaño", "Al polvo que cubre los montes"], ["tamo"]),
    q("c", "22", "¿Qué pregunta Mormón a los gentiles?", "Cómo se hallarán ante el poder de Dios", ["Cómo podrán conservar su tierra", "Cómo podrán aumentar sus riquezas"], ["poder de Dios"]),
  ),
  ch("morm", 6,
    q("a", "4", "¿A qué tierra marcharon los nefitas para reunirse?", "A la tierra de Cumorah", ["A la tierra de Moroni", "A la tierra de Josué"], ["Cumorah"]),
    q("b", "11", "¿Cuántos del pueblo de Mormón quedaron después de la batalla?", "Veinticuatro hombres", ["Veintisiete hombres", "Veintiún hombres"], ["veinticuatro"]),
    q("c", "3", "¿Cómo respondió el rey de los lamanitas a la petición de Mormón?", "Le concedió lo que había solicitado", ["Rechazó rotundamente la petición", "Hizo quemar la carta de Mormón"], ["concedió"]),
  ),
  ch("morm", 7,
    q("a", "2", "¿De qué casa es el resto del pueblo, según Mormón?", "De la casa de Israel", ["De la casa de Judá", "De la casa de David"], ["casa de Israel"]),
    q("b", "4", "¿Qué deben abandonar, según Mormón?", "Sus armas de guerra", ["Sus ídolos de oro", "Sus tesoros de plata"], ["armas de guerra"]),
    q("c", "8", "¿En el nombre de quién deben ser bautizados, según Mormón?", "En el nombre de Jesús", ["En el nombre de Mormón", "En el nombre de Nefi"], ["nombre de Jesús"]),
  ),
  ch("morm", 8,
    q("a", "1", "¿Quién da fin al registro de Mormón?", "Su hijo Moroni", ["Su hijo Nefi", "Su hijo Helamán"], ["Moroni"]),
    q("b", "6", "¿Cuántos años habían pasado desde la venida de Cristo?", "Cuatrocientos años", ["Trescientos años", "Quinientos años"], ["cuatrocientos"]),
    q("c", "23", "¿Qué profecías debe escudriñarse, según Moroni?", "Las profecías de Isaías", ["Las profecías de Jeremías", "Las profecías de Moisés"], ["profecías de Isaías"]),
  ),
  ch("morm", 9,
    q("a", "9", "¿Cómo es Dios, según Mormón?", "El mismo ayer, hoy y para siempre", ["Cambiante según los tiempos y los pueblos", "Presente solo en el templo"], ["ayer, hoy y para siempre"]),
    q("b", "32", "¿En qué caracteres escribieron Mormón y Moroni sus anales?", "En egipcio reformado", ["En hebreo antiguo", "En arameo siríaco"], ["egipcio reformado"]),
    q("c", "21", "¿Qué promete Moroni a quien cree en Cristo sin dudar?", "Todo lo que pida al Padre en nombre de Cristo", ["Que quedará libre de todas las pruebas", "Un lugar en todos los reinos de la tierra"], ["pida al Padre"]),
  ),
  ch("ether", 1,
    q("a", "2", "¿De cuántas planchas toma Moroni su relato sobre los antiguos habitantes destruidos?", "De veinticuatro planchas", ["De doce planchas de oro", "De cuarenta y ocho planchas"], ["veinticuatro planchas"]),
    q("b", "34-35", "¿Qué sucedió con el lenguaje de Jared y su hermano en la gran torre?", "Su lenguaje no fue confundido", ["Su lenguaje fue modificado en parte", "Su lenguaje fue cambiado por completo"], ["confundid"]),
    q("c", "38,42", "¿Qué prometió el Señor acerca de la región adonde guiaría al hermano de Jared?", "Que era favorecida sobre todas", ["Que era más fértil que Egipto", "Que estaba cerca de la torre"], ["favorecida"]),
  ),
  ch("ether", 2,
    q("a", "3", "¿Qué significa deseret, que llevaron consigo los jareditas?", "Una abeja obrera", ["Un topillo de campo", "Un pez de agua dulce"], ["abeja obrera"]),
    q("b", "14", "¿Cuánto tiempo habló el Señor con el hermano de Jared mientras lo reprendía?", "Por espacio de tres horas", ["Por espacio de siete horas", "Por espacio de dos horas"], ["tres horas"]),
    q("c", "17", "¿Cómo estaban construidas las barcas de los jareditas?", "Ajustadas como un vaso", ["Ajustadas como un barril", "Ajustadas como una vasija"], ["como un vaso"]),
  ),
  ch("ether", 3,
    q("a", "1", "¿Cuántas piedras pequeñas fundió el hermano de Jared de una roca en el monte Shelem?", "Dieciséis piedras", ["Doce piedras", "Dieciocho piedras"], ["dieciséis"]),
    q("b", "4-6", "¿Cómo hizo el Señor que brillaran las piedras cuando el hermano de Jared se lo pidió?", "Las tocó con su dedo", ["Sopló sobre ellas", "Les envió un rayo de fuego"], ["dedo"]),
    q("c", "21-22", "¿Qué debía hacer el hermano de Jared con lo que había visto y oído?", "Escribirlo y sellarlo bien", ["Contarlo al pueblo de inmediato", "Dárselo a sus propios hijos"], ["escrib", "sella"]),
  ),
  ch("ether", 4,
    q("a", "1", "¿Cuándo podía llegar a los hijos de los hombres lo que el hermano de Jared escribió?", "Después de que él fuera levantado en la cruz", ["Después de que los nefitas fueran destruidos", "Después de que él ascendiera al cielo"], ["cruz"]),
    q("b", "3,5", "¿Qué mandó el Señor a Moroni respecto a los anales del hermano de Jared?", "Ocultarlos otra vez en la tierra", ["Entregarlos a los lamanitas", "Quemarlos antes de que los hallaran"], ["otra vez en la tierra"]),
    q("c", "6-7", "¿Cuándo manifestaría el Señor a los gentiles lo que vio el hermano de Jared?", "Cuando se arrepientan y ejerzan la fe", ["Cuando terminen sus guerras", "Cuando ellos mismos hallen las planchas"], ["ejerzan la fe"]),
  ),
  ch("ether", 5,
    q("a", "3", "¿A cuántos testigos se mostrarían las planchas por el poder de Dios?", "A tres testigos", ["A doce testigos", "A siete testigos"], ["tres"]),
    q("b", "1", "¿Qué estaba prohibido hacer con lo que Moroni había sellado?", "Estaba prohibido traducirlo", ["Estaba prohibido moverlo", "Estaba prohibido mirarlo"], ["traduc"]),
    q("c", "5", "¿Qué sucede con el que se arrepiente y viene al Padre en el nombre de Jesús?", "Será recibido en el reino de Dios", ["Recibe el poder para abrir las planchas selladas", "Recibe el don de traducir las planchas"], ["reino de Dios"]),
  ),
  ch("ether", 6,
    q("a", "11", "¿Cuánto tiempo fueron impelidos sobre las aguas los jareditas antes de llegar a la tierra prometida?", "Trescientos cuarenta y cuatro días", ["Trescientos sesenta y cinco días", "Ciento cuarenta y dos días"], ["trescientos cuarenta y cuatro"]),
    q("b", "9", "¿Qué hizo el hermano de Jared todo el día mientras eran impelidos sobre las aguas?", "Cantar alabanzas al Señor", ["Vigilar las piedras", "Leer en voz alta los anales"], ["alabanzas"]),
    q("c", "27", "¿Cuál de los hijos de Jared fue ungido para ser rey del pueblo?", "Oríah, un hijo de Jared", ["Gilgá, un hijo de Jared", "Jácom, un hijo de Jared"], ["Oríah"]),
  ),
  ch("ether", 7,
    q("a", "9", "¿Qué hizo Shule con el mineral de la colina de Efraín para los hombres que había llevado consigo?", "Espadas de acero", ["Puntas de flecha de bronce", "Escudos de cobre"], ["espadas de acero"]),
    q("b", "4", "¿Qué edad tenía Corihor cuando se rebeló contra su padre Kib?", "Treinta y dos años", ["Veintiún años", "Cuarenta y cinco años"], ["treinta y dos"]),
    q("c", "24-25", "¿Qué hizo el rey Shule por los profetas injuriados por el pueblo?", "Los facultó mediante una ley para ir a donde quisieran", ["Les dio soldados para protegerlos por todas partes", "Los hizo habitar en una ciudad bajo su protección"], ["ir a donde quisieran"]),
  ),
  ch("ether", 8,
    q("a", "10-11", "¿Qué hizo la hija de Jared para agradar a Akish, hijo de Kimnor?", "Bailó delante de él", ["Cantó delante de él", "Le sirvió vino en la mesa"], ["bailó"]),
    q("b", "12", "¿Qué exigió Jared a Akish a cambio de su hija?", "La cabeza de su padre, el rey", ["Gran parte de su oro y su plata", "Las llaves de la ciudad más grande"], ["cabeza"]),
    q("c", "19", "¿Qué dice Moroni acerca del Señor y las combinaciones secretas?", "El Señor no obra por combinaciones secretas", ["El Señor las usa para probar a su pueblo", "El Señor las tolera solo entre sus profetas"], ["combinaciones secretas"]),
  ),
  ch("ether", 9,
    q("a", "3", "¿Cómo fue avisado Omer de salir de la tierra?", "El Señor lo avisó en un sueño", ["Un ángel se le apareció en una montaña", "Un profeta le habló a la puerta"], ["sueño"]),
    q("b", "22", "¿A quién vio el rey Emer y se regocijó?", "Al Hijo de Justicia", ["A un ángel del Señor", "A un profeta del norte"], ["Hijo de Justicia"]),
    q("c", "35", "¿Qué sucedió después de que el pueblo se humilló suficientemente ante el Señor?", "El Señor envió lluvia sobre la tierra", ["El Señor envió maná del cielo", "El Señor hizo desaparecer las serpientes"], ["lluvia"]),
  ),
  ch("ether", 10,
    q("a", "5", "¿Con qué cargó el rey Riplákish al pueblo?", "Con pesados tributos sobre sus hombros", ["Con servicio militar obligatorio", "Con años de trabajos forzados"], ["pesados tributos"]),
    q("b", "20", "¿Dónde edificaron los jareditas una ciudad grande en los días de Lib?", "Cerca de la estrecha lengua de tierra", ["Cerca de la colina de Shim, al norte", "En el valle de Nimrod junto al río"], ["estrecha lengua de tierra"]),
    q("c", "23", "¿Qué cuatro metales sacaban de la tierra los jareditas en los días de Lib?", "Oro, plata, hierro y bronce", ["Oro, plata, estaño y plomo", "Plata, hierro, estaño y zinc"], ["oro", "plata", "hierro", "bronce"]),
  ),
  ch("ether", 11,
    q("a", "5", "¿Qué hizo el hermano de Shiblom con los profetas que profetizaban la destrucción del pueblo?", "Hizo que los mataran", ["Los desterró al desierto", "Los encarceló en Morón"], ["mataran"]),
    q("b", "2", "¿Hacia quién huyeron los profetas para que los protegiera?", "Hacia el rey Com", ["Hacia el rey Omer", "Hacia el rey Shule"], ["Com"]),
    q("c", "20-21", "¿Qué haría el Señor Dios en los días de Coriantor si el pueblo no se arrepentía?", "Traer a otro pueblo a poseer la tierra", ["Reemplazar a su rey por un profeta", "Hacer desaparecer la tierra bajo el mar"], ["otro pueblo"]),
  ),
  ch("ether", 12,
    q("a", "6", "¿Qué es la fe, según Moroni?", "Las cosas que se esperan y no se ven", ["Saber con certeza lo que ya se ha visto", "Creer lo que uno mismo puede probar"], ["se esperan y no se ven"]),
    q("b", "13", "¿Por la fe de quiénes se derribó la prisión, según Moroni?", "La de Alma y de Amulek", ["La de Abinadí y Limhi", "La de Ammón y sus hermanos"], ["Alma y de Amulek"]),
    q("c", "30", "¿Qué sucedió cuando el hermano de Jared habló al monte de Zerín?", "El monte se apartó de lugar", ["El monte se partió en dos", "El monte empezó a temblar"], ["se apartó"]),
  ),
  ch("ether", 13,
    q("a", "6", "¿Para quiénes se edificaría la Nueva Jerusalén sobre esta tierra?", "Para el resto de la posteridad de José", ["Para el resto de la posteridad de Judá", "Para los últimos seguidores de los jareditas"], ["posteridad de José"]),
    q("b", "13", "¿Dónde se ocultaba Éter de día después de que el pueblo lo echó fuera?", "En el hueco de una roca", ["En una cueva junto al mar", "En un pozo del desierto"], ["hueco de una roca"]),
    q("c", "31", "¿Dónde hirió Shared a Coriántumr, de modo que no salió a la batalla durante dos años?", "En el muslo", ["En el brazo", "En el hombro"], ["muslo"]),
  ),
  ch("ether", 14,
    q("a", "10", "¿En qué superaba Lib a los demás hombres del pueblo?", "Era de gran estatura", ["Poseía las mayores riquezas", "Tenía el mayor ejército"], ["gran estatura"]),
    q("b", "17", "¿De quién era hermano Shiz, que destruyó y quemó muchas ciudades?", "Era hermano de Lib", ["Era hermano de Shared", "Era hermano de Com"], ["hermano de Lib"]),
    q("c", "21-23", "¿Por qué se sintió molesto el pueblo de día y de noche cuando toda la tierra estaba cubierta de cadáveres?", "Por el mal olor de los cadáveres", ["Por las serpientes venenosas del camino", "Por la falta de agua potable en la tierra"], ["mal olor"]),
  ),
  ch("ether", 15,
    q("a", "2", "¿Cuántos hombres valientes habían sido muertos ya cuando Coriántumr empezó a afligirse?", "Dos millones de hombres", ["Cuatro millones de hombres", "Medio millón de hombres"], ["dos millones"]),
    q("b", "11", "¿Junto a qué cerro plantó sus tiendas el ejército de Coriántumr?", "Junto al cerro Rama", ["Junto al cerro Comnor", "Junto al cerro Shim"], ["cerro Rama"]),
    q("c", "30", "¿Qué hizo Coriántumr después de apoyarse sobre su espada para descansar un poco?", "Le cortó la cabeza a Shiz de un golpe", ["Se rindió ante Shiz de inmediato", "Tocó una trompeta para su ejército"], ["cortó la cabeza"]),
  ),
  ch("moro", 1,
    q("a", "3", "¿Por qué andaba errante Moroni por donde podía?", "Para proteger su propia vida", ["Para buscar nuevas planchas", "Para convertir a los lamanitas"], ["propia vida"]),
    q("b", "2", "¿A quién matan los lamanitas en sus guerras, según Moroni?", "A todo nefita que no niegue al Cristo", ["A todo nefita que no lleve armas", "A todo nefita que no entregue las planchas"], ["nefita que no niegue"]),
    q("c", "1", "¿Sobre qué pueblo había acabado Moroni de compendiar los anales?", "El pueblo de Jared", ["El pueblo de Limhi", "El pueblo de Ammón"], ["pueblo de Jared"]),
  ),
  ch("moro", 2,
    q("a", "1", "¿A quiénes habló Cristo las palabras de Moroni 2?", "A los doce que había escogido", ["A los setenta que había escogido", "A los tres que había escogido"], ["doce"]),
    q("b", "2", "¿Qué podían conferir los discípulos al imponer las manos?", "El Espíritu Santo", ["El don de lenguas", "El don de profecía"], ["Espíritu Santo"]),
    q("c", "3", "¿Quiénes no oyeron las palabras de Cristo cuando las habló en su primera aparición?", "La multitud presente", ["Los discípulos presentes", "Los maestros presentes"], ["multitud"]),
  ),
  ch("moro", 3,
    q("a", "1", "¿Cómo eran llamados los discípulos que ordenaban presbíteros y maestros?", "Los élderes de la iglesia", ["Los apóstoles de la iglesia", "Los obispos de la iglesia"], ["élderes de la iglesia"]),
    q("b", "2", "¿Qué hacían primero los discípulos antes de imponer las manos para ordenar a alguien?", "Oraban al Padre en el nombre de Cristo", ["Leían las Escrituras ante toda la iglesia", "Pedían a la iglesia que diera su voto"], ["Padre", "nombre de Cristo"]),
    q("c", "3", "¿Qué debía predicar el ordenado presbítero o maestro?", "El arrepentimiento y la remisión de pecados", ["La restauración de la iglesia de Cristo", "El convenio de Abraham con todos los pueblos"], ["arrepentimiento y la remisión de pecados"]),
  ),
  ch("moro", 4,
    q("a", "3", "¿En memoria de qué se comía el pan?", "En memoria del cuerpo del Hijo", ["En memoria de la ley de Moisés", "En memoria de la salida de Egipto"], ["memoria del cuerpo"]),
    q("b", "2", "¿Qué hacían el élder o el presbítero y la iglesia antes de bendecir el pan?", "Se arrodillaban y oraban al Padre", ["Se ponían de pie y cantaban un himno", "Guardaban silencio y leían un salmo"], ["arrodill", "Padre"]),
    q("c", "3", "¿Qué pedían a Dios que hiciera con el pan?", "Que lo bendijera y lo santificara", ["Que lo llevara a los enfermos", "Que lo repartiera entre los presentes"], ["santifi"]),
  ),
  ch("moro", 5,
    q("a", "2", "¿En memoria de qué se bebía el vino?", "En memoria de la sangre del Hijo", ["En memoria del convenio con Abraham", "En memoria de la ley de Moisés"], ["memoria de la sangre"]),
    q("b", "1", "¿Qué tomaban en la mano cuando se administraba el vino?", "Tomaban una copa", ["Tomaban una jarra", "Tomaban un cuenco"], ["copa"]),
    q("c", "2", "¿Cómo se dirigían a Dios en la oración sobre el vino?", "Oh Dios, Padre Eterno de todos", ["Oh Dios, Señor de los Ejércitos", "Oh Señor, Redentor nuestro"], ["Padre Eterno"]),
  ),
  ch("moro", 6,
    q("a", "2", "¿Con qué disposición debía venirse al bautismo?", "Con corazón quebrantado y espíritu contrito", ["Con las manos limpias y el corazón puro", "Con gran fe y un firme testimonio"], ["corazón quebrantado", "espíritu contrito"]),
    q("b", "5", "¿Para qué se reunía a menudo la iglesia, además de hablar del bienestar de sus almas?", "Para ayunar y para orar", ["Para trabajar y cosechar", "Para viajar y comerciar"], ["ayunar"]),
    q("c", "7", "¿Cuántos testigos de la iglesia debían condenar a alguien ante los élderes?", "Tres testigos", ["Dos testigos", "Siete testigos"], ["tres testigos"]),
  ),
  ch("moro", 7,
    q("a", "47", "¿Qué es la caridad, según Mormón?", "El amor puro de Cristo mismo", ["La más alta forma de entrega", "El amor que se recibe de otros"], ["amor puro de Cristo"]),
    q("b", "11", "¿Qué imagen usa Mormón para mostrar que un hombre malo no puede hacer nada bueno?", "Una fuente amarga que no da agua buena", ["Un pozo seco que no da agua", "Una mala cosecha que no da grano"], ["fuente amarga"]),
    q("c", "16", "¿Qué se da a todo hombre para discernir el bien del mal?", "El Espíritu de Cristo", ["El don de profecía", "La ley de Moisés"], ["Espíritu de Cristo"]),
  ),
  ch("moro", 8,
    q("a", "4-5", "¿Por qué se habían suscitado disputas, para pesar de Mormón?", "Por el bautismo de los niños pequeños", ["Por la ordenación de los maestros", "Por la manera de imponer las manos"], ["bautismo", "niños pequeños"]),
    q("b", "12", "¿Por qué los niños pequeños no necesitan el bautismo, según Mormón?", "Los niños pequeños viven en Cristo", ["Ya fueron bautizados en el espíritu", "Son demasiado jóvenes para sufrir"], ["viven en Cristo"]),
    q("c", "25", "¿Qué llama Mormón las primicias del arrepentimiento?", "El bautismo, que viene por la fe", ["La remisión de todos los pecados", "La mansedumbre del corazón"], ["bautismo"]),
  ),
  ch("moro", 9,
    q("a", "2", "¿Qué hombres habían caído por la espada en el combate contra los lamanitas, según Mormón?", "Arqueanto, Luram y Emrón", ["Amorón, Zenefí y Arqueanto", "Luram, Aarón y Zenefí"], ["Arqueanto", "Luram", "Emrón"]),
    q("b", "4", "¿Qué hace la gente cuando Mormón dice la palabra de Dios con severidad?", "Tiemblan y se enojan", ["Se arrodillan y oran", "Callan y se van a casa"], ["tiemblan"]),
    q("c", "22", "¿Qué pidió Mormón a Dios para su hijo Moroni?", "Que Dios le conserve la vida", ["Que venza a los lamanitas", "Que conduzca pronto un ejército"], ["conserve la vida"]),
  ),
  ch("moro", 10,
    q("a", "4", "¿Qué exhorta Moroni a los lectores a preguntar a Dios?", "Si estas cosas no son verdaderas", ["Si los lamanitas se arrepentirán", "Si pueden traducir las planchas"], ["no son verdaderas"]),
    q("b", "17", "¿Cuál es la fuente de todos estos dones, según Moroni?", "El Espíritu de Cristo", ["El poder de la iglesia", "La ley de Moisés"], ["Espíritu de Cristo"]),
    q("c", "20-21", "¿Qué tres cosas debe tener alguien para ser salvo en el reino de Dios?", "Fe, esperanza y caridad", ["Fe, ayuno y sencillez", "Esperanza, paciencia y obediencia"], ["fe", "esperanza", "caridad"]),
  ),
  // ===== EINDE =====
];
