import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 1 Néphi (édition française). Chaque fait est lié aux versets indiqués dans `verses` ; `npm run genees:check` le vérifie.
export const nephi1: GeneesChapterSeed[] = [
  ch("1-ne", 1,
    q("a", "5-6", "Qu’est-ce qui apparut devant Léhi sur un rocher pendant qu’il priait le Seigneur ?", "Une colonne de feu", ["Un nuage blanc", "Une étoile brillante"], ["colonne de feu"]),
    q("b", "4", "Au début du règne de quel roi de Juda de nombreux prophètes vinrent-ils ?", "Le roi Sédécias", ["Le roi Josias", "Le roi Jojakim"], ["Sédécias"]),
    q("c", "11", "Que le premier des douze vus par Léhi dans sa vision lui donna-t-il à lire ?", "Un livre", ["Un bâton", "Une épée"], ["livre"]),
  ),
  ch("1-ne", 2,
    q("a", "2", "Que le Seigneur commanda-t-il à Léhi de faire en songe ?", "De partir dans le désert avec sa famille", ["De fuir à Babylone avec sa famille", "De naviguer vers le sud avec sa famille"], ["désert"]),
    q("b", "8", "Quel nom Léhi donna-t-il à la rivière qui se déversait dans la mer Rouge ?", "La rivière Laman", ["La rivière Sam", "Le fleuve Jourdain"], ["Laman"]),
    q("c", "20", "Que le Seigneur promit-il à Néphi s’il gardait ses commandements ?", "Qu’il serait conduit vers une terre de promission", ["Qu’il serait de retour à Jérusalem dans trois jours", "Qu’il bâtirait une grande ville avec ses frères"], ["terre de promission"]),
  ),
  ch("1-ne", 3,
    q("a", "3", "Sur quoi étaient gravées les annales des Juifs que Laban possédait ?", "Sur des plaques d’airain", ["Sur des plaques d’or", "Sur des tablettes de pierre"], ["plaques d’airain"]),
    q("b", "11", "Qui entra le premier dans la maison de Laban après le tirage au sort ?", "Laman", ["Lémuel", "Néphi"], ["Laman"]),
    q("c", "29", "Qui apparut quand Laman et Lémuel frappaient leur frère cadet avec un bâton ?", "Un ange du Seigneur", ["Un serviteur de Laban", "Un prophète de Juda"], ["ange du Seigneur"]),
  ),
  ch("1-ne", 4,
    q("a", "18", "Avec quoi Néphi tua-t-il Laban ?", "Avec l’épée même de Laban", ["Avec une lance de cuivre", "Avec un lourd gourdin"], ["épée"]),
    q("b", "35", "Comment s’appelait le serviteur de Laban ?", "Zoram", ["Zérah", "Zénos"], ["Zoram"]),
    q("c", "7", "Dans quel état Néphi trouva-t-il Laban ?", "Il était ivre de vin", ["Il était tombé malade", "Il était blessé au combat"], ["ivre de vin"]),
  ),
  ch("1-ne", 5,
    q("a", "11", "Que contenaient entre autres les plaques d’airain quand Léhi les examina ?", "Les cinq livres de Moïse", ["Les psaumes du roi David", "Les lois du roi Salomon"], ["cinq livres de Moïse"]),
    q("b", "14", "De quel fils de Jacob Léhi se révéla-t-il le descendant ?", "Joseph", ["Ruben", "Siméon"], ["Joseph"]),
    q("c", "2", "Quel reproche Sariah fit-elle à son mari quand ses fils ne revinrent pas ?", "Qu’il n’était qu’un visionnaire", ["Qu’il manquait de provisions", "Qu’il avait pris le mauvais chemin"], ["visionnaire"]),
  ),
  ch("1-ne", 6,
    q("a", "4", "Vers quel Dieu Néphi veut-il persuader les hommes de venir ?", "Le Dieu d’Abraham, d’Isaac et de Jacob", ["Le Dieu d’Adam, de Noé et de Moïse", "Le Dieu d’Hénoc, de David et de Salomon"], ["Dieu d’Abraham", "Isaac", "Jacob"]),
    q("b", "5", "Quelles choses Néphi n’écrit-il pas sur ses plaques ?", "Ce qui plaît au monde", ["Ce qui parle de ses frères", "Ce qui parle des guerres"], ["plaît au monde"]),
    q("c", "1", "Où se trouve la généalogie des pères de Néphi ?", "Dans les annales de son père Léhi", ["Sur les plaques où Néphi écrit maintenant", "Dans les annales du prophète Jérémie"], ["annales", "père"]),
  ),
  ch("1-ne", 7,
    q("a", "2", "Qui Néphi et ses frères devaient-ils amener de Jérusalem ?", "Ismaël et sa famille", ["Jérémie et sa famille", "Sédécias et sa famille"], ["Ismaël"]),
    q("b", "16", "Que firent Laman et Lémuel à Néphi après qu’il leur eut parlé ?", "Ils le lièrent avec des cordes", ["Ils le frappèrent avec un bâton", "Ils l’enfermèrent dans une grotte"], ["lièrent"]),
    q("c", "21", "Que fit Néphi quand ses frères le supplièrent de leur pardonner ?", "Il leur pardonna franchement tout", ["Il exigea qu’ils rendent leurs épées", "Il les fit d’abord jeûner un jour"], ["pardonn"]),
  ),
  ch("1-ne", 8,
    q("a", "19", "Quelle barre longeait la rivière jusqu’à l’arbre ?", "Une barre de fer", ["Une barre de bois", "Une barre de cuivre"], ["barre de fer"]),
    q("b", "12", "Que se passa-t-il quand Léhi mangea du fruit ?", "Son âme fut remplie d’une joie extrêmement grande", ["Son corps fut guéri de toute fatigue", "Son cœur fut rempli de tristesse pour Laman"], ["joie extrêmement grande"]),
    q("c", "26", "Où se trouvait le grand et spacieux édifice que Léhi vit ?", "En l’air, bien haut au-dessus de la terre", ["Au fond d’une vallée près de la rivière", "Au sommet d’une montagne couverte d’arbres"], ["au-dessus de la terre"]),
  ),
  ch("1-ne", 9,
    q("a", "3-4", "De quoi traitent surtout les plaques sur lesquelles Néphi écrit maintenant ?", "Du ministère parmi son peuple", ["Du règne des rois et des guerres", "Du voyage de sa famille sur la mer"], ["ministère"]),
    q("b", "1", "Dans quelle vallée Léhi demeurait-il sous une tente quand il vit toutes ces choses ?", "Dans la vallée de Lémuel", ["Dans la vallée de Laman", "Dans la vallée de Zoram"], ["vallée de Lémuel"]),
    q("c", "5", "Pourquoi le Seigneur commanda-t-il à Néphi de faire ces plaques ?", "Dans un but sage que Néphi ne connaissait pas", ["Parce que les autres plaques avaient été perdues", "Parce que Léhi l’avait lui-même demandé"], ["but sage"]),
  ),
  ch("1-ne", 10,
    q("a", "4", "Combien d’années après le départ de Léhi de Jérusalem le Messie viendrait-il selon sa prophétie ?", "Six cents ans", ["Trois cents ans", "Mille ans"], ["six cents ans"]),
    q("b", "9", "Où le prophète qui préparerait la voie du Seigneur baptiserait-il ?", "À Béthabara, au-delà du Jourdain", ["À Jérusalem, près du temple du Seigneur", "À Nazareth, au bord de la mer Rouge"], ["Béthabara"]),
    q("c", "12", "À quoi Léhi compara-t-il la maison d’Israël ?", "À un olivier", ["À une vigne", "À un figuier"], ["olivier"]),
  ),
  ch("1-ne", 11,
    q("a", "1", "Où Néphi fut-il ravi dans l’Esprit du Seigneur ?", "Sur une montagne extrêmement haute", ["Sur une vaste plaine au bord de la mer", "Dans une vallée pleine d’arbres mûrs"], ["montagne extrêmement haute"]),
    q("b", "18", "Qui est la vierge que Néphi vit, selon l’ange ?", "La mère du Fils de Dieu", ["La sœur du prophète Jérémie", "L’épouse du roi de Juda"], ["mère du Fils de Dieu"]),
    q("c", "22", "De quoi l’arbre est-il le symbole selon Néphi ?", "L’amour de Dieu pour les hommes", ["La sagesse du grand monde", "La puissance d’un royaume fort"], ["amour de Dieu"]),
  ),
  ch("1-ne", 12,
    q("a", "1", "À quoi est comparé le nombre de personnes dans la postérité de Néphi ?", "Au sable de la mer", ["Aux étoiles du ciel", "Aux feuilles des bois"], ["sable de la mer"]),
    q("b", "7-8", "Combien de disciples de l’Agneau furent choisis pour exercer le ministère auprès de la postérité de Néphi ?", "Douze disciples", ["Sept disciples", "Vingt disciples"], ["douze"]),
    q("c", "17", "À quoi correspondent les brouillards de ténèbres selon l’ange ?", "Les tentations du diable", ["Les difficultés du voyage", "Les doutes des croyants"], ["tentations du diable"]),
  ),
  ch("1-ne", 13,
    q("a", "23", "Que contient le livre qui sort de la bouche d’un Juif, selon l’ange ?", "Les alliances avec la maison d’Israël", ["Les lois de tous les peuples de la terre", "L’histoire des rois d’Égypte"], ["alliances", "maison d’Israël"]),
    q("b", "12", "Où alla l’homme parmi les Gentils que l’Esprit de Dieu poussa ?", "Sur les nombreuses eaux, vers la terre promise", ["À travers le désert vers la ville de Jérusalem", "Par-dessus les montagnes vers le pays d’Égypte"], ["nombreuses eaux", "terre promise"]),
    q("c", "37", "Que recevront ceux qui chercheront à faire sortir Sion dans les derniers jours ?", "Le don et le pouvoir du Saint-Esprit", ["La richesse et l’honneur du monde", "La sagesse et l’autorité des rois"], ["don et le pouvoir du Saint-Esprit"]),
  ),
  ch("1-ne", 14,
    q("a", "27", "Quel était le nom de l’apôtre de l’Agneau qui devait écrire ces choses ?", "L’apôtre Jean", ["L’apôtre Pierre", "L’apôtre Paul"], ["Jean"]),
    q("b", "10", "Combien d’Églises y a-t-il selon l’ange ?", "Il n’y en a que deux", ["Il n’y en a que quatre", "Il n’y en a que sept"], ["que deux"]),
    q("c", "12", "Comment étaient les membres de l’Église de l’Agneau de Dieu dans la vision de Néphi ?", "Un petit nombre, mais répandus sur toute la terre", ["Un grand nombre, mais limités à un seul pays", "Aussi nombreux que ceux de l’autre Église"], ["petit nombre"]),
  ),
  ch("1-ne", 15,
    q("a", "24", "Que représentait la barre de fer selon Néphi ?", "La parole de Dieu", ["La loi de Moïse", "Le pouvoir d’un roi"], ["parole de Dieu"]),
    q("b", "8-9", "Que Laman et Lémuel n’avaient-ils pas fait pour comprendre les paroles de leur père ?", "Interroger le Seigneur à ce sujet", ["Offrir un sacrifice sur un autel", "Consulter les plaques d’airain"], ["interrog"]),
    q("c", "18", "Avec quel ancêtre le Seigneur fit-il l’alliance qui s’accomplira dans les derniers jours ?", "Abraham", ["Hénoc", "Salomon"], ["Abraham"]),
  ),
  ch("1-ne", 16,
    q("a", "10", "En quoi était faite la boule d’exécution habile que Léhi trouva près de sa tente ?", "En airain fin", ["En or pur", "En acier trempé"], ["airain fin"]),
    q("b", "13", "Comment s’appelait le lieu où la famille dressa ses tentes après quatre jours de voyage ?", "Shazer", ["Lémuel", "Jershon"], ["Shazer"]),
    q("c", "18", "Que se passa-t-il quand Néphi alla chercher de la nourriture ?", "Son arc d’acier fin se brisa", ["Toutes ses flèches étaient épuisées", "Il se perdit dans le désert"], ["arc", "acier"]),
  ),
  ch("1-ne", 17,
    q("a", "5", "Comment appelèrent-ils la mer qu’ils virent, et que signifie ce nom ?", "Irréantum, ce qui signifie de nombreuses eaux", ["Abondance, ce qui signifie de nombreux fruits", "Shazer, ce qui signifie eaux rouges"], ["Irréantum", "nombreuses eaux"]),
    q("b", "4", "Combien d’années la famille séjourna-t-elle dans le désert ?", "Huit ans", ["Quatre ans", "Douze ans"], ["huit"]),
    q("c", "11", "De quoi Néphi fit-il un soufflet pour attiser le feu ?", "De peaux de bêtes", ["De laine de mouton", "D’écorce d’arbre"], ["peaux de bêtes"]),
  ),
  ch("1-ne", 18,
    q("a", "7", "Comment s’appelaient les deux fils que Léhi engendra dans le désert ?", "Jacob et Joseph", ["Énos et Jarom", "Zoram et Sam"], ["Jacob", "Joseph"]),
    q("b", "12", "Que se passa-t-il avec la boussole après que Néphi fut lié ?", "Elle cessa de fonctionner", ["Elle indiqua le mauvais côté", "Elle fut perdue dans la tempête"], ["cessa de fonctionner"]),
    q("c", "15", "Depuis combien de jours étaient-ils repoussés sur les eaux quand les frères de Néphi commencèrent à voir que les jugements de Dieu étaient sur eux ?", "Quatre jours", ["Deux jours", "Sept jours"], ["quatre jours"]),
  ),
  ch("1-ne", 19,
    q("a", "1", "En quoi Néphi fit-il les plaques pour graver les annales de son peuple ?", "En métal", ["En argent", "En bois"], ["métal"]),
    q("b", "12", "Quel prophète dit que le Dieu de la nature souffre ?", "Zénos", ["Zénock", "Neum"], ["Zénos"]),
    q("c", "23", "Quel prophète Néphi lut-il à ses frères pour les persuader de croire au Seigneur ?", "Le prophète Ésaïe", ["Le prophète Jérémie", "Le prophète Ézéchiel"], ["Ésaïe"]),
  ),
  ch("1-ne", 20,
    q("a", "4", "Comment le Seigneur décrit-il le front du peuple d’Israël ?", "Un front d’airain", ["Un front de pierre", "Un front d’or pur"], ["front d’airain"]),
    q("b", "18", "À quoi le bonheur d’Israël aurait-il ressemblé s’il avait obéi aux commandements du Seigneur ?", "Aux flots de la mer", ["Aux montagnes de Juda", "Aux étoiles du ciel"], ["flots de la mer"]),
    q("c", "20", "D’où le peuple devait-il sortir selon le Seigneur ?", "De Babylone", ["D’Égypte", "De l’Assyrie"], ["Babylone"]),
  ),
  ch("1-ne", 21,
    q("a", "16", "Où le Seigneur dit-il avoir gravé la maison d’Israël ?", "Sur ses mains", ["Sur une pierre", "Sur les murs"], ["mains"]),
    q("b", "6", "Pour quoi le Seigneur établit-il aussi son serviteur à l’égard des nations ?", "Pour être une lumière", ["Pour être leur juge", "Pour être un grand roi"], ["lumière"]),
    q("c", "14", "Qu’a dit Sion au sujet du Seigneur ?", "Que le Seigneur l’avait abandonnée", ["Que le Seigneur ne lui pardonnerait jamais", "Que le Seigneur l’avait faite reine"], ["abandonn"]),
  ),
  ch("1-ne", 22,
    q("a", "20-21", "Qui est le prophète dont Moïse parlait, selon Néphi ?", "Le Saint d’Israël", ["Ésaïe, fils d’Amots", "Léhi, père de Néphi"], ["Saint d’Israël"]),
    q("b", "25", "Combien de troupeaux et de bergers y aura-t-il quand le Seigneur rassemblera ses enfants ?", "Un seul troupeau et un seul berger", ["Douze troupeaux et douze bergers", "Sept troupeaux et un seul berger"], ["seul troupeau", "seul berger"]),
    q("c", "30", "De quoi témoignent les choses écrites sur les plaques d’airain selon Néphi ?", "Que l’homme doit obéir aux commandements de Dieu", ["Que l’homme doit donner ses biens aux pauvres", "Qu’il faut sacrifier au temple tous les sept jours"], ["commandements de Dieu"]),
  ),
  // ===== EINDE =====
];
