import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 2 Néphi (édition française). Chaque fait est lié aux versets indiqués dans `verses` ; `npm run genees:check` le vérifie.
export const nephi2: GeneesChapterSeed[] = [
  ch("2-ne", 1,
    q("a", "6", "Qui peut venir dans cette terre selon Léhi ?", "Seulement celui qui y est amené par la main du Seigneur", ["Seulement celui qui peut construire son propre navire", "Seulement celui qui a la permission du roi"], ["main du Seigneur"]),
    q("b", "30", "Comment s’appelait le serviteur de Laban que Léhi appela un ami fidèle de Néphi ?", "Zoram", ["Jacob", "Ismaël"], ["Zoram"]),
    q("c", "13", "De quoi les fils de Léhi devaient-ils s’éveiller selon lui ?", "D’un profond sommeil", ["D’un long voyage", "D’une grave maladie"], ["profond sommeil"]),
  ),
  ch("2-ne", 2,
    q("a", "25", "Pourquoi les hommes existent-ils selon Léhi ?", "Pour qu’ils puissent avoir la joie", ["Pour qu’ils règnent sur toute la terre", "Pour qu’ils acquièrent des richesses"], ["joie"]),
    q("b", "16", "Que le Seigneur Dieu accorda-t-il à l’homme ?", "La liberté d’agir par lui-même", ["La liberté de vivre sans aucune loi", "Le droit de fonder son propre royaume"], ["agir par lui-même"]),
    q("c", "19", "Pourquoi Adam et Ève furent-ils chassés du jardin d’Éden ?", "Pour aller cultiver la terre", ["Pour fonder une nouvelle ville", "Pour vivre sept ans dans le désert"], ["cultiver la terre"]),
  ),
  ch("2-ne", 3,
    q("a", "17", "Dans quoi le Seigneur donnerait-il du pouvoir au Moïse à venir, selon la prophétie de Joseph ?", "Dans une verge", ["Dans une épée", "Dans un rouleau"], ["verge"]),
    q("b", "6", "Que le Seigneur susciterait-il selon Joseph pour le fruit de ses reins ?", "Un voyant de choix", ["Un roi très puissant", "Un juge très juste"], ["voyant de choix"]),
    q("c", "1", "Quelle place Joseph, à qui Léhi parlait, occupait-il parmi les enfants de Léhi ?", "Il était le dernier-né", ["Il était le premier-né", "Il était le deuxième fils"], ["dernier-né"]),
  ),
  ch("2-ne", 4,
    q("a", "12", "Que se passa-t-il pour Léhi après qu’il eut parlé à toute sa maison ?", "Il mourut et fut enterré", ["Il tomba malade et se retira", "Il fut enlevé au ciel"], ["mourut"]),
    q("b", "11", "À quel fils Léhi dit-il qu’il hériterait le pays comme Néphi ?", "À son fils Sam", ["À son fils Laman", "À son fils Joseph"], ["Sam"]),
    q("c", "15", "Dans quoi l’âme de Néphi trouve-t-elle ses délices, écrit-il ?", "Dans les Écritures des plaques d’airain", ["Dans les guerres contre ses ennemis", "Dans les richesses du pays qu’il habite"], ["Écritures"]),
  ),
  ch("2-ne", 5,
    q("a", "28", "Combien d’années s’étaient écoulées depuis qu’ils avaient quitté Jérusalem ?", "Trente ans", ["Vingt ans", "Quarante ans"], ["trente"]),
    q("b", "16", "Sur le modèle de quel temple Néphi construisit-il un temple ?", "Le temple de Salomon", ["Le temple de Moïse", "Le temple de Sédécias"], ["temple de Salomon"]),
    q("c", "26", "Qui Néphi consacra-t-il prêtres et instructeurs sur son peuple ?", "Jacob et Joseph", ["Sam et Zoram", "Laman et Lémuel"], ["Jacob", "Joseph"]),
  ),
  ch("2-ne", 6,
    q("a", "4", "Quel prophète Jacob lut-il au peuple ?", "Le prophète Ésaïe", ["Le prophète Jérémie", "Le prophète Moïse"], ["Ésaïe"]),
    q("b", "2", "Par qui Jacob avait-il été consacré ?", "Par son frère Néphi", ["Par son père Léhi", "Par le roi de Juda"], ["frère Néphi"]),
    q("c", "14", "Combien de fois le Messie se mettra-t-il en devoir de recouvrer son peuple selon Jacob ?", "Pour la seconde fois", ["Pour la troisième fois", "Pour la septième fois"], ["seconde fois"]),
  ),
  ch("2-ne", 7,
    q("a", "8", "De quoi le Seigneur frappera-t-il son adversaire ?", "De la force de sa propre bouche", ["D’une épée d’acier bien tranchante", "Du feu qui vient du ciel"], ["bouche"]),
    q("b", "7", "À quoi le Seigneur dit-il avoir rendu son visage semblable ?", "À un caillou", ["À un bouclier", "À un mur"], ["caillou"]),
    q("c", "3", "De quoi le Seigneur revêt-il les cieux ?", "D’obscurité", ["De blancheur", "De pourpre"], ["obscurité"]),
  ),
  ch("2-ne", 8,
    q("a", "2", "Sur quel père et quelle mère le peuple doit-il porter les regards selon Ésaïe ?", "Abraham et Sara", ["Isaac et Rebecca", "Jacob et Rachel"], ["Abraham", "Sara"]),
    q("b", "3", "À quoi le Seigneur rendra-t-il le désert de Sion semblable ?", "À un Éden", ["À Béthel", "Au Sinaï"], ["Éden"]),
    q("c", "1", "D’où le peuple qui poursuit la justice a-t-il été taillé selon Ésaïe ?", "Du rocher", ["Du fleuve", "Du désert"], ["rocher"]),
  ),
  ch("2-ne", 9,
    q("a", "10", "Comment Jacob appelle-t-il la mort et l’enfer ?", "Un monstre affreux", ["Un rempart imprenable", "Un abîme sans fond"], ["monstre"]),
    q("b", "41", "Qui est selon Jacob le gardien de la porte du sentier étroit ?", "Le Saint d’Israël", ["Le prophète Ésaïe", "L’ange du Seigneur"], ["Saint d’Israël"]),
    q("c", "25", "Que n’y a-t-il pas selon Jacob là où aucune loi n’est donnée ?", "Pas de châtiment", ["Pas de rédemption", "Pas d’espérance"], ["pas de châtiment"]),
  ),
  ch("2-ne", 10,
    q("a", "3", "Quel nom l’ange dit-il que le Messie porterait ?", "Le nom de Christ", ["Le nom d’Emmanuel", "Le nom de Josué"], ["Christ"]),
    q("b", "11", "Qui n’y aura-t-il pas, selon le Seigneur, dans ce pays de liberté ?", "Des rois qui seront suscités pour les Gentils", ["Des prêtres qui servent chaque jour dans le temple", "Des paysans qui travaillent la terre de leurs mains"], ["rois qui seront suscités"]),
    q("c", "23", "Entre quels deux chemins les hommes sont-ils libres de choisir selon Jacob ?", "Le chemin de la mort éternelle ou celui de la vie éternelle", ["Le chemin de la richesse ou celui de la pauvreté en terre promise", "Le chemin de la guerre ou celui de la paix avec les Lamanites"], ["mort éternelle", "vie éternelle"]),
  ),
  ch("2-ne", 11,
    q("a", "2", "Les paroles de qui Néphi écrit-il encore davantage ?", "Celles d’Ésaïe", ["Celles de Jérémie", "Celles de Zénos"], ["Ésaïe"]),
    q("b", "7", "Que dit Néphi s’il n’y a pas de Christ ?", "Alors il n’y a pas de Dieu", ["Alors il n’y a pas de temple", "Alors il n’y a pas de prophète"], ["pas de Dieu"]),
    q("c", "4", "Pourquoi la loi de Moïse a-t-elle été donnée selon Néphi ?", "Pour prouver la vérité de la venue du Christ", ["Pour libérer le peuple d’Égypte avec l’aide de Dieu", "Pour construire le temple à Jérusalem"], ["venue du Christ"]),
  ),
  ch("2-ne", 12,
    q("a", "4", "En quoi les nations forgeront-elles leurs glaives, selon Ésaïe ?", "Des hoyaux de paysan", ["Des boucliers de guerre", "Des marmites de cuisine"], ["hoyaux"]),
    q("b", "2", "Où se trouvera la maison du Seigneur dans les derniers jours ?", "Sur le sommet des montagnes", ["Au fond d’une vallée de Juda", "Au bord de la grande mer"], ["sommet des montagnes"]),
    q("c", "7", "De quoi le pays de Juda était-il rempli selon Ésaïe ?", "D’argent et d’or en abondance", ["De blé et d’huile en abondance", "De brebis et de chèvres en abondance"], ["argent et d’or"]),
  ),
  ch("2-ne", 13,
    q("a", "16", "Pourquoi le Seigneur punira-t-il les filles de Sion ?", "Parce qu’elles sont devenues orgueilleuses", ["Parce qu’elles ne sanctifient pas le sabbat", "Parce qu’elles ont abandonné le temple"], ["orgueilleuses"]),
    q("b", "9", "À quelle ville Ésaïe compare-t-il le péché de Juda ?", "À Sodome", ["À Babylone", "À Ninive"], ["Sodome"]),
    q("c", "10", "Que mangeront les justes selon Ésaïe ?", "Le fruit de leurs œuvres", ["Le pain du roi lui-même", "Le butin de l’ennemi vaincu"], ["fruit de leurs œuvres"]),
  ),
  ch("2-ne", 14,
    q("a", "1", "Combien de femmes saisiront un seul homme en ce jour, selon Ésaïe ?", "Sept femmes", ["Douze femmes", "Dix femmes"], ["sept femmes"]),
    q("b", "5", "Que le Seigneur établira-t-il pendant la nuit sur la montagne de Sion ?", "Un feu de flammes éclatantes", ["Un grand nuage sombre de poussière", "Une pluie d’étoiles d’argent"], ["feu de flammes éclatantes"]),
    q("c", "6", "Qu’y aura-t-il, selon Ésaïe, pour donner de l’ombre contre la chaleur du jour ?", "Un simple abri", ["Une haute tour", "Un large mur"], ["abri"]),
  ),
  ch("2-ne", 15,
    q("a", "1", "De quoi Ésaïe chante-t-il le cantique ?", "D’une vigne sur un coteau", ["D’une bergerie dans la vallée", "D’une ville au bord du fleuve"], ["vigne"]),
    q("b", "7", "Que représente la vigne du Seigneur des armées ?", "La maison d’Israël", ["Le temple de Salomon", "La ville du roi"], ["maison d’Israël"]),
    q("c", "20", "Sur qui Ésaïe prononce-t-il un « malheur » au verset 20 ?", "Sur ceux qui appellent le mal bien", ["Sur ceux qui se reposent le jour du sabbat", "Sur ceux qui aident les pauvres"], ["appellent le mal bien"]),
  ),
  ch("2-ne", 16,
    q("a", "2", "Combien d’ailes chaque séraphin avait-il ?", "Six ailes chacun", ["Quatre ailes chacun", "Huit ailes chacun"], ["six ailes"]),
    q("b", "6-7", "Avec quoi le séraphin toucha-t-il la bouche d’Ésaïe ?", "Avec une pierre ardente", ["Avec une torche enflammée", "Avec une feuille d’or"], ["pierre ardente"]),
    q("c", "8", "Que dit Ésaïe quand le Seigneur demanda qui il enverrait ?", "Me voici, envoie-moi", ["Je ne suis pas digne", "Envoie plutôt mon frère"], ["Me voici"]),
  ),
  ch("2-ne", 17,
    q("a", "14", "Quel nom le fils de la jeune fille recevra-t-il selon Ésaïe ?", "Emmanuel", ["Jérémie", "Joachim"], ["Emmanuel"]),
    q("b", "1", "Du temps de quel roi de Juda Retsin et Pékach montèrent-ils contre Jérusalem ?", "Achaz", ["Josias", "Joram"], ["Achaz"]),
    q("c", "11", "Que pouvait demander Achaz au Seigneur ?", "Un signe", ["Une armée", "Un navire"], ["signe"]),
  ),
  ch("2-ne", 18,
    q("a", "3", "Quel nom le fils d’Ésaïe devait-il recevoir selon le Seigneur ?", "Maher-Schalal-Chasch-Baz", ["Schear-Jaschub, fils d’Amots", "Maher-Emmanuel, fils d’Isaï"], ["Maher-Schalal-Chasch-Baz"]),
    q("b", "13", "Qui devons-nous sanctifier selon le Seigneur ?", "Le Seigneur des armées", ["Le roi d’Assyrie lui-même", "Le prophète Ésaïe lui-même"], ["Seigneur des armées"]),
    q("c", "7", "Qui désignent les puissantes et grandes eaux du fleuve ?", "Le roi d’Assyrie", ["Le roi d’Égypte", "Le roi de Syrie"], ["roi d’Assyrie"]),
  ),
  ch("2-ne", 19,
    q("a", "6", "Comment l’enfant qui nous est né sera-t-il appelé, entre autres noms ?", "Admirable, Conseiller", ["Berger, Juge et Roi", "Sauveur, Lumière et Maître"], ["Admirable", "Conseiller"]),
    q("b", "2", "Qu’a vu le peuple qui marchait dans les ténèbres ?", "Une grande lumière", ["Une grande étoile", "Une grande armée"], ["grande lumière"]),
    q("c", "15", "Qui est la queue d’Israël selon Ésaïe ?", "Le prophète qui enseigne le mensonge", ["Le prêtre qui sert dans le temple", "Le guerrier qui défend la ville"], ["enseigne le mensonge"]),
  ),
  ch("2-ne", 20,
    q("a", "5", "Qui le Seigneur appelle-t-il la verge de sa colère ?", "L’Assyrien", ["L’Égyptien", "Le Philistin"], ["Assyrien"]),
    q("b", "26", "Quel massacre est mentionné en rapport avec le rocher d’Oreb ?", "Celui de Madian", ["Celui d’Amalek", "Celui de Moab"], ["Madian"]),
    q("c", "21", "Qui reviendra au Dieu puissant selon Ésaïe ?", "Le reste de Jacob", ["Les armées d’Assyrie", "La ville du roi"], ["reste de Jacob"]),
  ),
  ch("2-ne", 21,
    q("a", "1", "De quel tronc un rameau sortira-t-il selon Ésaïe ?", "Du tronc d’Isaï", ["Du tronc de Joseph", "Du tronc de Juda"], ["Isaï"]),
    q("b", "6", "Qui habitera avec l’agneau selon Ésaïe ?", "Le loup", ["Le coq", "Le cerf"], ["loup"]),
    q("c", "9", "De quoi la terre sera-t-elle remplie selon Ésaïe ?", "De la connaissance du Seigneur", ["Des richesses de toutes les nations", "Des villes des saints et des justes"], ["connaissance du Seigneur"]),
  ),
  ch("2-ne", 22,
    q("a", "2", "Qu’est le Seigneur Jéhovah selon ce cantique ?", "Ma force et le sujet de mes louanges", ["Mon refuge, ma forteresse et mon bouclier", "Mon berger, mon guide et mon rocher"], ["force", "louanges"]),
    q("b", "3", "Où puiserez-vous de l’eau avec joie ?", "Aux sources du salut", ["Au fleuve du Jourdain", "Au puits de Jacob"], ["sources du salut"]),
    q("c", "6", "Qui est grand au milieu des habitants de Sion ?", "Le Saint d’Israël", ["Le roi de Juda", "Le prophète Ésaïe"], ["Saint d’Israël"]),
  ),
  ch("2-ne", 23,
    q("a", "17", "Quel peuple le Seigneur excitera-t-il contre Babylone selon Ésaïe ?", "Le peuple des Mèdes", ["Le peuple des Assyriens", "Le peuple d’Édom"], ["Mèdes"]),
    q("b", "19", "À quelles villes Babylone est-elle comparée lors de sa chute ?", "À Sodome et Gomorrhe", ["À Ninive et à Tyr", "À Jéricho et à Aï"], ["Sodome et Gomorrhe"]),
    q("c", "10", "Que devient le soleil à son lever selon Ésaïe ?", "Il s’obscurcira dès son lever", ["Il deviendra rouge comme du sang", "Il brillera deux fois plus fort"], ["obscurcira"]),
  ),
  ch("2-ne", 24,
    q("a", "12", "Quel titre porte Lucifer au verset 12 ?", "Fils de l’aurore", ["Fils de la nuit", "Fils du crépuscule"], ["fils de l’aurore"]),
    q("b", "14", "Que Lucifer dit-il dans son cœur qu’il ferait ?", "Monter sur le sommet des nues", ["Descendre au fond de la terre", "Fonder un royaume à l’est"], ["sommet des nues"]),
    q("c", "23", "Que fera le Seigneur de Babylone ?", "Le gîte du hérisson et un marécage", ["Une ville pleine de marchands riches", "Un pâturage pour les moutons du pays"], ["hérisson"]),
  ),
  ch("2-ne", 25,
    q("a", "19", "Combien d’années après le départ de Léhi de Jérusalem le Messie viendra-t-il selon les prophètes ?", "Six cents ans", ["Quatre cents ans", "Neuf cents ans"], ["six cents ans"]),
    q("b", "24", "Que gardaient Néphi et son peuple bien qu’ils croient au Christ ?", "La loi de Moïse", ["Les lois d’Égypte", "Les rites de Laban"], ["loi de Moïse"]),
    q("c", "29", "Qui est le Christ selon Néphi ?", "Le Saint d’Israël", ["Le prophète Ésaïe", "Le roi des Juifs"], ["Saint d’Israël"]),
  ),
  ch("2-ne", 26,
    q("a", "9", "Comment le Christ est-il appelé au verset 9 ?", "Le Fils de la justice", ["Le Fils de l’aurore", "Le Fils de la bénédiction"], ["Fils de la justice"]),
    q("b", "31", "Pour quoi l’ouvrier en Sion ne doit-il pas travailler ?", "Pour de l’argent", ["Pour la gloire", "Pour le pouvoir"], ["argent"]),
    q("c", "25", "Que dit le Seigneur au lieu de « Éloigne-toi de moi » ?", "Venez toutes à moi, extrémités de la terre", ["Bâtissez un temple en l’honneur de mon nom", "Offrez-moi chaque jour un agneau sans défaut"], ["Venez toutes à moi"]),
  ),
  ch("2-ne", 27,
    q("a", "7", "Que contiendra le livre scellé selon le verset 7 ?", "Une révélation de Dieu", ["Les lois des rois", "Une liste de tous les rois"], ["révélation de Dieu"]),
    q("b", "18", "Que dira le savant quand on lui apportera le livre ?", "Je ne peux pas le lire", ["Je ne veux pas l’acheter", "Je l’ai déjà lu"], ["pas le lire"]),
    q("c", "29", "Qui entendra les paroles du livre selon Ésaïe ?", "Les sourds", ["Les riches", "Les savants"], ["sourds"]),
  ),
  ch("2-ne", 28,
    q("a", "7", "Que diront beaucoup de gens dans les derniers jours selon Néphi ?", "Mangez, buvez et réjouissez-vous", ["Épargnez, priez et soyez prudents", "Travaillez, priez et soyez fidèles"], ["Mangez, buvez, et réjouissez-vous"]),
    q("b", "30", "De quelle manière le Seigneur Dieu donne-t-il sa parole aux enfants des hommes ?", "Ligne sur ligne, précepte sur précepte", ["Livre sur livre, chapitre sur chapitre", "Année après année, miracle après miracle"], ["ligne sur ligne", "précepte sur précepte"]),
    q("c", "22", "Que raconte le diable à certains selon Néphi ?", "Qu’il n’y a pas d’enfer, ni de démon", ["Que le Seigneur reviendra très bientôt", "Que le temple sera fermé par les rois"], ["pas d’enfer"]),
  ),
  ch("2-ne", 29,
    q("a", "3", "Que diront beaucoup de Gentils ?", "Une Bible ! Une Bible !", ["Un temple ! Un temple !", "Un roi ! Un roi !"], ["Une Bible"]),
    q("b", "4", "De quel peuple la Bible vient-elle ?", "Du peuple des Juifs", ["Du peuple des Égyptiens", "Du peuple des Néphites"], ["Juifs"]),
    q("c", "8", "Le témoignage de combien de nations est, selon le Seigneur, la preuve qu’il est Dieu ?", "Deux nations", ["Trois nations", "Sept nations"], ["deux nations"]),
  ),
  ch("2-ne", 30,
    q("a", "2", "Qui est le peuple de l’alliance du Seigneur selon Néphi ?", "Tous les Gentils qui se repentiront", ["Seulement ceux venus de Jérusalem", "Seulement les riches qui font des dons"], ["se repentiront"]),
    q("b", "7", "En qui les Juifs dispersés commenceront-ils à croire selon Néphi ?", "Au Christ", ["À Moïse", "À Abraham"], ["Christ"]),
    q("c", "17", "Qu’arrivera-t-il à tout ce qui est caché selon Néphi ?", "Cela sera révélé", ["Cela sera scellé", "Cela sera oublié"], ["révélé"]),
  ),
  ch("2-ne", 31,
    q("a", "8", "Sous quelle forme le Saint-Esprit descendit-il sur le Christ quand il fut baptisé ?", "Sous la forme d’une colombe", ["Sous la forme d’un aigle", "Sous la forme d’un nuage"], ["forme d’une colombe"]),
    q("b", "21", "Que dit Néphi du chemin par lequel l’homme peut être sauvé ?", "Il n’y a aucun autre chemin ni aucun autre nom", ["Il y a deux chemins et deux noms différents", "Il y a un chemin pour chaque nation"], ["aucun autre chemin"]),
    q("c", "11", "Que dit le Père que les hommes devaient faire ?", "Se repentir et être baptisés", ["Jeûner et offrir un sacrifice", "Prier et observer la loi"], ["repent", "baptisés"]),
  ),
  ch("2-ne", 32,
    q("a", "2", "Avec quoi pourraient-ils parler après avoir reçu le Saint-Esprit ?", "Avec la langue des anges", ["Avec la langue des prophètes", "Avec la langue des rois"], ["langue des anges"]),
    q("b", "9", "Que devons-nous toujours faire selon Néphi ?", "Toujours prier et ne pas se relâcher", ["Toujours jeûner et ne jamais boire", "Toujours sacrifier et ne jamais se plaindre"], ["toujours prier"]),
    q("c", "6", "Jusqu’à quand aucune doctrine supplémentaire ne sera-t-elle donnée selon Néphi ?", "Jusqu’à ce qu’il se manifeste dans la chair", ["Jusqu’à ce que le temple soit entièrement achevé", "Jusqu’à ce que le peuple se soit repenti"], ["dans la chair"]),
  ),
  ch("2-ne", 33,
    q("a", "6", "Dans quoi Néphi met-il entre autres sa gloire ?", "Dans la clarté et dans la vérité", ["Dans sa force et sa sagesse", "Dans ses œuvres et dans son armée"], ["clarté", "vérité"]),
    q("b", "13", "Comme qui Néphi parle-t-il à toutes les extrémités de la terre ?", "Comme quelqu’un qui crie de la poussière", ["Comme la voix d’un berger dans les champs", "Comme la voix d’un ange venu du ciel"], ["crie de la poussière"]),
    q("c", "15", "Qu’est-ce qui sera mis à charge contre les hommes à la barre du jugement selon Néphi ?", "Ce que Néphi scelle sur la terre", ["Tout ce que l’on a amassé sur la terre", "Ce que les Juifs ont écrit sur la terre"], ["scelle sur la terre"]),
  ),
  // ===== EINDE =====
];
