import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 3 Néphi (édition française). Chaque fait est lié aux versets indiqués dans `verses` ; `npm run genees:check` le vérifie.
export const nephi3: GeneesChapterSeed[] = [
  ch("3-ne", 1,
    q("a", "19", "Que se passa-t-il la nuit du signe ?", "Il n’y eut pas de ténèbres de toute la nuit", ["Un violent orage éclaira toute la nuit", "Une éclipse de soleil dura de longues heures"], ["pas de ténèbres"]),
    q("b", "21", "Qu’est-ce qui apparut dans le ciel selon la parole des prophètes ?", "Une nouvelle étoile", ["Une nouvelle lune", "Une comète rouge"], ["nouvelle étoile"]),
    q("c", "3", "Qui tint les annales après que son père eut quitté le pays ?", "Néphi, fils de Néphi", ["Léhi, fils de Néphi", "Néphi, fils de Léhi"], ["Néphi"]),
  ),
  ch("3-ne", 2,
    q("a", "8", "À partir de quand les Néphites commencèrent-ils à compter leur temps ?", "À partir du signe de la venue du Christ", ["À partir de la mort du roi Mosiah", "À partir du départ de Léhi de Jérusalem"], ["venue du Christ"]),
    q("b", "12", "Que firent les Lamanites convertis quand les brigands menacèrent ?", "Ils s’unirent à leurs frères, les Néphites", ["Ils partirent s’installer dans le nord", "Ils fondèrent leur propre royaume"], ["s’unirent"]),
    q("c", "11", "Qui causa des guerres et des querelles dans le pays la treizième année ?", "Les brigands de Gadianton", ["Les Lamanites du pays du sud", "Le roi de la ville de Zarahemla"], ["brigands de Gadianton"]),
  ),
  ch("3-ne", 3,
    q("a", "9", "Comment s’appelait le chef de la société secrète de Gadianton ?", "Giddianhi", ["Gidgiddoni", "Zemnarihah"], ["Giddianhi"]),
    q("b", "18", "Qui fut nommé commandant suprême de toutes les armées néphites ?", "Gidgiddoni", ["Lachonéus", "Moronihah"], ["Gidgiddoni"]),
    q("c", "23", "Quel pays fut désigné comme lieu de rassemblement ?", "Le pays de Zarahemla", ["Le pays de Jershon", "Le pays de Mélek"], ["Zarahemla"]),
  ),
  ch("3-ne", 4,
    q("a", "28", "Comment s’appelait le nouveau chef des brigands pendu à un arbre ?", "Zemnarihah", ["Gidgiddoni", "Giddianhi"], ["Zemnarihah"]),
    q("b", "3", "Pourquoi les brigands ne pouvaient-ils subsister que dans le désert ?", "Les Néphites avaient laissé leurs terres désolées", ["Les Lamanites avaient occupé toutes leurs terres du sud", "Les brigands avaient pris toutes les villes du pays"], ["terres désolées"]),
    q("c", "32", "Que crièrent les Néphites en louant Dieu ?", "Hosanna au Dieu Très-Haut", ["Alléluia au Dieu saint", "Gloire au roi du pays"], ["Hosanna"]),
  ),
  ch("3-ne", 5,
    q("a", "12", "De quel pays Mormon tient-il son nom ?", "Du pays de Mormon", ["Du pays d’Hélam", "Du pays d’Abondance"], ["pays de Mormon"]),
    q("b", "13", "Que dit Mormon de lui-même selon ses propres paroles ?", "Un disciple de Jésus-Christ", ["Un grand prêtre de l’Église", "Un chef des armées néphites"], ["disciple de Jésus-Christ"]),
    q("c", "11", "Sur quoi Mormon écrit-il son récit ?", "Sur des plaques faites de ses mains", ["Sur des plaques faites par son père", "Sur des plaques de cuivre de Jérusalem"], ["mains"]),
  ),
  ch("3-ne", 6,
    q("a", "6", "Qui avait fait régner la grande paix dans le pays ?", "Gidgiddoni et le juge Lachonéus", ["Zemnarihah et le juge Giddianhi", "Moroni et le juge Pahoran"], ["Gidgiddoni", "Lachonéus"]),
    q("b", "14", "En quelle année l’Église se fragmenta-t-elle dans tout le pays ?", "La trentième année", ["La vingtième année", "La quarantième année"], ["trentième année"]),
    q("c", "8", "Qu’est-ce qui fut aménagé dans le pays en temps de paix ?", "De nombreuses grandes routes", ["De nombreux murs et tours", "De nombreux canaux et ponts"], ["routes"]),
  ),
  ch("3-ne", 7,
    q("a", "19", "Que fit Néphi au nom de Jésus pour son frère ?", "Il le ressuscita d’entre les morts", ["Il le guérit de sa grande cécité", "Il le délivra de la prison"], ["d’entre les morts"]),
    q("b", "10", "Comment la société secrète appela-t-elle l’homme qu’elle établit à sa tête ?", "Ils l’appelèrent leur roi", ["Ils l’appelèrent leur juge", "Ils l’appelèrent leur prophète"], ["roi"]),
    q("c", "2", "En quoi le peuple se divisa-t-il ?", "En tribus", ["En villes", "En armées"], ["tribus"]),
  ),
  ch("3-ne", 8,
    q("a", "5", "En quelle année s’éleva un grand orage ?", "La trente-quatrième année", ["La trente-troisième année", "La trente-cinquième année"], ["trente-quatrième année"]),
    q("b", "8", "Que devint la ville de Zarahemla ?", "Elle prit feu et brûla", ["Elle s’enfonça en terre", "Elle fut ensevelie"], ["prit feu"]),
    q("c", "23", "Combien de temps ne vit-on aucune lumière ?", "Trois jours", ["Sept jours", "Deux jours"], ["trois jours"]),
  ),
  ch("3-ne", 9,
    q("a", "3", "Que devint la grande ville de Zarahemla selon la voix ?", "Elle fut brûlée par le feu", ["Elle fut engloutie par la mer", "Elle fut recouverte de terre"], ["brûlée par le feu"]),
    q("b", "18", "Comment le Seigneur se nomme-t-il au verset 18 ?", "L’Alpha et l’Oméga", ["Le Berger et le Roc", "Le Roi et le Juge"], ["Alpha", "Oméga"]),
    q("c", "20", "Quel sacrifice le Seigneur demande-t-il au lieu de l’effusion du sang ?", "Un cœur brisé et un esprit contrit", ["Un sacrifice des premiers-nés du bétail", "Un holocauste du meilleur grain"], ["cœur brisé"]),
  ),
  ch("3-ne", 10,
    q("a", "9", "Combien de temps fallut-il avant que les ténèbres quittent le pays ?", "Trois jours", ["Sept jours", "Deux jours"], ["trois jours"]),
    q("b", "5", "À quoi le Seigneur compare-t-il son désir de rassembler le peuple ?", "À une poule qui rassemble ses poussins", ["À un berger qui conduit ses brebis", "À un aigle qui porte ses petits"], ["poule"]),
    q("c", "16", "Quels prophètes ont témoigné de ces choses selon Mormon ?", "Zénos et Zénock", ["Ésaïe et Jérémie", "Moïse et Aaron"], ["Zénos", "Zénock"]),
  ),
  ch("3-ne", 11,
    q("a", "1", "Où la grande multitude du peuple de Néphi était-elle rassemblée ?", "Autour du temple au pays d’Abondance", ["Autour de la montagne à Zarahemla", "Autour du palais au pays de Néphi"], ["temple"]),
    q("b", "7", "Que dit la voix du ciel ?", "Voici mon Fils bien-aimé ; écoutez-le", ["Voici mon serviteur ; suivez ses paroles", "Voici le prophète ; craignez ses jugements"], ["Fils bien-aimé", "écoutez-le"]),
    q("c", "25", "Au nom de qui faut-il baptiser selon le Seigneur ?", "Au nom du Père, et du Fils, et du Saint-Esprit", ["Au nom du Père, du prophète et du roi", "Au nom du Seigneur, de l’ange et de l’Esprit"], ["Père", "Fils", "Saint-Esprit"]),
  ),
  ch("3-ne", 12,
    q("a", "13", "À quoi le Seigneur exhorte-t-il les hommes au verset 13 ?", "À être le sel de la terre", ["À être le sel de la mer", "À être le pain de la terre"], ["sel de la terre"]),
    q("b", "5", "Qui héritera la terre selon le Seigneur ?", "Ceux qui sont doux", ["Ceux qui sont riches", "Ceux qui sont forts"], ["doux"]),
    q("c", "44", "Que commande le Seigneur au sujet de nos ennemis ?", "Aimez vos ennemis", ["Chassez vos ennemis", "Punissez vos ennemis"], ["Aimez vos ennemis"]),
  ),
  ch("3-ne", 13,
    q("a", "9", "Comment commence la prière que Jésus enseigne à la multitude ?", "Notre Père qui es aux cieux ! Que ton nom soit sanctifié", ["Notre Seigneur qui demeures au ciel ! Que ton nom soit loué", "Notre Dieu qui règnes sur la terre ! Que ton nom soit grand"], ["Notre Père qui es aux cieux"]),
    q("b", "33", "Que faut-il chercher premièrement selon Jésus ?", "Le royaume et la justice de Dieu", ["La richesse et un bon nom", "La nourriture et les vêtements"], ["royaume"]),
    q("c", "24", "Combien de maîtres nul ne peut-il servir selon Jésus ?", "Deux maîtres", ["Trois maîtres", "Sept maîtres"], ["deux maîtres"]),
  ),
  ch("3-ne", 14,
    q("a", "7", "Que promet le Seigneur à ceux qui demandent ?", "On vous donnera", ["On vous retirera", "On vous oubliera"], ["on vous donnera"]),
    q("b", "15", "Comment viennent les faux prophètes selon le Seigneur ?", "En vêtements de brebis", ["En vêtements de roi", "En habits de prêtre"], ["vêtements de brebis"]),
    q("c", "24", "Sur quoi l’homme prudent a-t-il bâti sa maison selon Jésus ?", "Sur un roc solide", ["Sur du sable fin", "Sur une colline"], ["roc"]),
  ),
  ch("3-ne", 15,
    q("a", "17", "Que dit le Seigneur au sujet d’autres brebis ?", "Qu’il a encore d’autres brebis", ["Qu’il n’a plus d’autres brebis", "Que toutes les brebis sont ici"], ["d’autres brebis"]),
    q("b", "4", "Qu’est-ce qui est accompli selon le Seigneur ?", "La loi qui fut donnée à Moïse", ["La loi qui fut donnée à Léhi", "La loi qui fut donnée à Abraham"], ["loi qui fut donnée à Moïse"]),
    q("c", "9", "Qu’est le Seigneur selon le verset 9 ?", "La loi et la lumière", ["La porte et le chemin", "La paix et le roc"], ["loi et la lumière"]),
  ),
  ch("3-ne", 16,
    q("a", "6", "Qui est béni, selon le Seigneur, à cause de sa croyance en lui ?", "Les Gentils", ["Les Néphites", "Les Juifs"], ["Gentils"]),
    q("b", "18", "Que font les sentinelles selon le prophète Ésaïe ?", "Elles élèvent la voix et crient d’allégresse", ["Elles rassemblent le peuple au son des trompettes", "Elles quittent la ville et s’enfuient au loin"], ["élèvent la voix"]),
    q("c", "13", "Que se passe-t-il pour les Gentils s’ils se repentent et reviennent au Seigneur ?", "Ils seront comptés parmi mon peuple", ["Ils seront chassés du pays", "Ils seront épargnés sans jugement"], ["comptés parmi mon peuple"]),
  ),
  ch("3-ne", 17,
    q("a", "14", "Que fit Jésus quand la multitude se fut agenouillée à terre ?", "Il gémit en lui-même", ["Il partit en secret", "Il les bénit de ses mains"], ["gémit"]),
    q("b", "7", "Qui Jésus demanda-t-il à la multitude de lui amener ?", "Les malades, les estropiés et les aveugles", ["Les riches et les puissants du pays", "Les étrangers et les inconnus du pays"], ["malades"]),
    q("c", "21", "Comment Jésus prit-il les petits enfants ?", "Il prit leurs petits enfants un par un", ["Il renvoya les petits enfants à leurs parents", "Il fit prier les enfants par groupes"], ["un par un"]),
  ),
  ch("3-ne", 18,
    q("a", "1", "Qu’est-ce que Jésus commanda à ses disciples de lui apporter ?", "Du pain et du vin", ["De l’eau et du sel", "Du lait et du miel"], ["pain et du vin"]),
    q("b", "18", "Que doivent faire les gens selon Jésus pour ne pas entrer en tentation ?", "Toujours veiller et prier", ["Toujours jeûner et sacrifier", "Toujours travailler et épargner"], ["veiller et prier"]),
    q("c", "7", "En souvenir de quoi doivent-ils manger le pain selon Jésus ?", "En souvenir de son corps", ["En souvenir de la loi de Moïse", "En souvenir de leurs ancêtres"], ["souvenir"]),
  ),
  ch("3-ne", 19,
    q("a", "5", "En combien de groupes la multitude fut-elle divisée ?", "En douze groupes", ["En sept groupes", "En trois groupes"], ["douze groupes"]),
    q("b", "9", "Pour quoi les disciples prièrent-ils le plus ?", "Que le Saint-Esprit leur soit donné", ["Que leur peuple ne connaisse plus la guerre", "Que leur prière dure sans fin"], ["Saint-Esprit"]),
    q("c", "11", "Qui descendit dans l’eau pour être baptisé ?", "Néphi", ["Jonas", "Kumen"], ["Néphi"]),
  ),
  ch("3-ne", 20,
    q("a", "3,5", "Que donna Jésus à manger et à boire aux disciples et à la multitude ?", "Du pain et du vin", ["Du poisson et du miel", "Du grain et du lait"], ["pain", "vin"]),
    q("b", "6", "Que dit le verset 6 au sujet du pain et du vin ?", "Personne n’avait apporté de pain ni de vin", ["Les disciples avaient apporté du pain et du vin", "La multitude avait apporté du pain et du vin"], ["apporté de pain"]),
    q("c", "14", "Que le Père commanda-t-il à Jésus de donner au peuple ?", "Ce pays-ci pour leur héritage", ["Le pays de Juda pour leur héritage", "Le pays du sud pour leur héritage"], ["héritage"]),
  ),
  ch("3-ne", 21,
    q("a", "12", "À quoi le reste de Jacob est-il comparé parmi les Gentils ?", "À un lion parmi les bêtes de la forêt", ["À une brebis parmi les loups", "À un aigle au-dessus des montagnes"], ["lion"]),
    q("b", "14", "Qu’est-ce que le Seigneur exterminera du milieu des Gentils au verset 14 ?", "Tes chevaux et tes chars", ["Tes brebis et tes troupeaux", "Tes tours et tes portes"], ["chevaux", "chars"]),
    q("c", "16", "Quelle pratique le Seigneur retranchera-t-il de leur pays selon le verset 16 ?", "Les enchantements", ["Les caravanes", "Les champs de blé"], ["enchantements"]),
  ),
  ch("3-ne", 22,
    q("a", "9", "À quoi le Seigneur compare-t-il sa promesse au verset 9 ?", "Aux eaux de Noé", ["Aux eaux du Nil", "Aux eaux d’Égypte"], ["eaux de Noé"]),
    q("b", "13", "Qui sera disciple du Seigneur selon lui ?", "Tous tes fils, disciples du Seigneur", ["Tous les prêtres, disciples du roi", "Seulement les riches, disciples des maîtres"], ["fils"]),
    q("c", "12", "De quoi le Seigneur fera-t-il les créneaux de Sion rétablie ?", "De rubis", ["De saphirs", "De cristal"], ["rubis"]),
  ),
  ch("3-ne", 23,
    q("a", "9", "À qui le Seigneur avait-il commandé de témoigner au peuple du signe de sa mort ?", "À Samuel, le Lamanite", ["À Néphi, fils d’Hélaman", "À Léhi, le prophète"], ["Samuel, le Lamanite"]),
    q("b", "7", "Qu’est-ce que Jésus demanda à Néphi d’apporter ?", "Les annales qu’il avait tenues", ["Les plaques de cuivre de Jérusalem", "La boule ou directeur de Léhi"], ["annales"]),
    q("c", "13", "Que commanda Jésus au sujet de ce qui n’était pas encore écrit ?", "Que cela fût écrit", ["Que cela reste secret", "Que cela soit oublié"], ["fût écrit"]),
  ),
  ch("3-ne", 24,
    q("a", "1", "Les paroles de qui Jésus commanda-t-il d’écrire ?", "Celles de Malachie", ["Celles d’Ésaïe", "Celles de Jérémie"], ["Malachie"]),
    q("b", "8", "En quoi le peuple trompe-t-il Dieu selon le verset 8 ?", "Dans la dîme et les offrandes", ["Dans le sabbat et les cultes", "Dans les prières et les aumônes"], ["dîme"]),
    q("c", "10", "Où faut-il apporter toutes les dîmes selon le Seigneur ?", "À la maison du trésor", ["Au mur du temple", "Au siège du jugement"], ["maison du trésor"]),
  ),
  ch("3-ne", 25,
    q("a", "5", "Quel prophète le Seigneur enverra-t-il avant que le jour grand et redoutable arrive ?", "Le prophète Élie", ["Le prophète Élisée", "Le prophète Jonas"], ["Élie"]),
    q("b", "2", "Comment le Christ est-il appelé au verset 2 ?", "Le Fils de la Justice", ["Le Fils de l’aurore", "Le Fils de la promesse"], ["Fils de la Justice"]),
    q("c", "6", "Que ramènera Élie selon le Seigneur ?", "Le cœur des pères à leurs enfants", ["La loi des pères à leurs enfants", "La richesse des pères à leurs enfants"], ["cœur des pères"]),
  ),
  ch("3-ne", 26,
    q("a", "13", "Combien de temps le Seigneur instruisit-il le peuple selon le verset 13 ?", "Pendant trois jours", ["Pendant sept jours", "Pendant quarante jours"], ["trois jours"]),
    q("b", "21", "Comment appelait-on ceux qui furent baptisés au nom de Jésus-Christ ?", "L’Église du Christ", ["L’Église de Néphi", "L’Église de Léhi"], ["Église du Christ"]),
    q("c", "19", "Qu’avaient les croyants selon le verset 19 ?", "Ils avaient tout en commun entre eux", ["Ils avaient tout en propriété privée", "Toutes les richesses étaient aux chefs"], ["en commun"]),
  ),
  ch("3-ne", 27,
    q("a", "5", "De quel nom l’Église doit-elle être appelée selon Jésus ?", "Du nom du Christ", ["Du nom de Moïse", "Du nom de Néphi"], ["nom du Christ"]),
    q("b", "28", "Que promet Jésus à ceux qui demandent au Père en son nom ?", "Cela leur sera donné", ["Cela leur sera refusé", "Cela leur sera rendu"], ["sera donné"]),
    q("c", "33", "Par quelle porte les disciples doivent-ils entrer selon Jésus ?", "Par la porte étroite", ["Par la porte large", "Par la porte d’or"], ["porte étroite"]),
  ),
  ch("3-ne", 28,
    q("a", "3", "À quel âge les disciples viendraient-ils à Jésus dans son royaume ?", "À soixante-douze ans", ["À soixante-quinze ans", "À soixante ans"], ["soixante-douze ans"]),
    q("b", "7", "Que n’arriverait jamais aux trois disciples qui l’avaient désiré selon Jésus ?", "Ils ne goûteraient jamais la mort", ["Ils n’auraient plus jamais faim", "Ils ne perdraient jamais leur foi"], ["jamais la mort"]),
    q("c", "22", "Que se passa-t-il quand les trois furent jetés dans un antre de bêtes sauvages ?", "Ils jouèrent avec les bêtes comme un enfant", ["Ils furent dévorés par les bêtes sauvages", "Ils furent attaqués par les bêtes sauvages"], ["jouèrent avec les bêtes"]),
  ),
  ch("3-ne", 29,
    q("a", "8", "Qui ne faut-il plus siffler ni traiter avec mépris selon Mormon ?", "Le peuple des Juifs", ["Le peuple des Néphites", "Le peuple des Lamanites"], ["Juifs"]),
    q("b", "6", "Que renie celui qui dit que le Seigneur n’agit plus ?", "Les révélations du Seigneur", ["Les alliances du Seigneur", "Les prophètes du Seigneur"], ["révélations du Seigneur"]),
    q("c", "2", "Que peut-on savoir des paroles du Seigneur selon Mormon ?", "Qu’elles s’accompliront toutes", ["Qu’elles seront toutes oubliées", "Qu’elles ne seront plus jamais lues"], ["s’accompliront toutes"]),
  ),
  ch("3-ne", 30,
    q("a", "1", "À qui Mormon s’adresse-t-il dans ce chapitre ?", "Aux Gentils", ["Aux Néphites", "Aux Lamanites"], ["Gentils"]),
    q("b", "2", "Que doivent faire les Gentils selon Mormon ?", "Se détourner de leurs voies mauvaises", ["Se rassembler dans le pays du nord", "Se hâter de bâtir des tours"], ["voies mauvaises"]),
    q("c", "1", "Qui est Jésus-Christ selon le verset 1 ?", "Le Fils du Dieu vivant", ["Le fils du prophète Mormon", "Le fils du roi de Juda"], ["Fils du Dieu vivant"]),
  ),
  // ===== EINDE =====
];
