import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Alma (édition française). Chaque fait est lié aux versets indiqués dans `verses` ; `npm run genees:check` le vérifie.
export const alma: GeneesChapterSeed[] = [
  ch("alma", 1,
    q("a", "15", "Comment s’appelait l’homme qui tua Gédéon ?", "Néhor", ["Amulon", "Zoram"], ["Néhor"]),
    q("b", "15", "Où Néhor fut-il mis à mort ?", "Sur le sommet de la colline de Manti", ["Sur la rive du fleuve Sidon", "Sur la place du marché de Zarahemla"], ["colline de Manti"]),
    q("c", "12", "Qu’est-ce qui fut introduit pour la première fois parmi le peuple selon Alma ?", "Les intrigues de prêtres", ["La possession d’esclaves", "La construction d’un temple"], ["intrigues de prêtres"]),
  ),
  ch("alma", 2,
    q("a", "1", "Comment s’appelait l’homme qui voulait devenir roi sur le peuple ?", "Amlici", ["Néhor", "Korihor"], ["Amlici"]),
    q("b", "31", "Comment Alma tua-t-il le chef des Amlicites ?", "Avec son épée", ["Avec une lance", "Avec une flèche"], ["épée"]),
    q("c", "15", "Sur quelle colline à l’est du Sidon les Amlicites montèrent-ils ?", "La colline Amnihu", ["La colline de Manti", "La colline de Riplah"], ["colline Amnihu"]),
  ),
  ch("alma", 3,
    q("a", "4", "De quoi les Amlicites s’étaient-ils marqué le front ?", "Avec de la peinture rouge", ["Avec de la peinture bleue", "Avec de la peinture blanche"], ["rouge"]),
    q("b", "26", "Combien d’âmes furent envoyées dans le monde éternel en cette seule année ?", "Des milliers et des dizaines de milliers", ["Des centaines et des milliers d’âmes", "Seulement quelques centaines d’âmes"], ["milliers et des dizaines de milliers"]),
    q("c", "22", "Pourquoi Alma ne monta-t-il pas lui-même au combat cette fois-là contre les Lamanites ?", "Parce qu’il était affligé d’une blessure", ["Parce qu’il n’avait pas confiance dans l’armée", "Parce qu’il avait un autre plan"], ["blessure"]),
  ),
  ch("alma", 4,
    q("a", "5", "Combien d’âmes s’unirent à l’Église la septième année ?", "Environ trois mille cinq cents", ["Environ deux mille cinq cents", "Environ cinq mille trois cents"], ["trois mille cinq cents"]),
    q("b", "17", "Qui fut désigné comme grand juge quand Alma remit le siège du jugement ?", "Néphihah", ["Giddonah", "Hélaman"], ["Néphihah"]),
    q("c", "18", "Quel office Alma conserva-t-il pour lui-même ?", "Celui de grand prêtre", ["Celui de chef de l’armée", "Celui de grand juge"], ["grand prêtre"]),
  ),
  ch("alma", 5,
    q("a", "38", "Quel nom porte le bon Berger qui nous appelle ?", "Le nom du Christ", ["Le nom de Mormon", "Le nom d’Abinadi"], ["nom du Christ"]),
    q("b", "3", "Par qui Alma avait-il été consacré grand prêtre de l’Église de Dieu ?", "Par son père Alma", ["Par le roi Mosiah", "Par le roi Limhi"], ["père Alma"]),
    q("c", "52", "Qu’est-ce qui est mis à la racine de l’arbre selon l’Esprit ?", "La cognée", ["La scie", "La bêche"], ["cognée"]),
  ),
  ch("alma", 6,
    q("a", "8", "Dans quelle vallée Alma commença-t-il ensuite à annoncer la parole de Dieu ?", "La vallée de Gédéon", ["La vallée de Lémuel", "La vallée d’Hélam"], ["vallée de Gédéon"]),
    q("b", "2", "Qu’arriva-t-il à ceux qui n’appartenaient pas à l’Église et se repentaient de leurs péchés ?", "Ils furent baptisés au repentir", ["Ils furent envoyés à Zarahemla", "Ils devaient d’abord attendre un an"], ["baptisés au repentir"]),
    q("c", "6", "Pourquoi était-il commandé aux enfants de Dieu de se réunir souvent ?", "Pour jeûner et prier avec ferveur", ["Pour offrir des sacrifices", "Pour bâtir des temples ensemble"], ["jeûn"]),
  ),
  ch("alma", 7,
    q("a", "10", "Où le Seigneur naîtra-t-il selon Alma ?", "À Jérusalem", ["À Nazareth", "À Zarahemla"], ["Jérusalem"]),
    q("b", "10", "Comment Alma appelle-t-il la mère du Seigneur ?", "Une vierge, un vase précieux et élu", ["Une princesse, une femme riche et puissante", "Une reine, un vase riche et noble"], ["vase précieux et élu"]),
    q("c", "24", "Quelles trois choses faut-il avoir selon Alma ?", "La foi, l’espérance et la charité", ["La foi, le repentir et les sacrifices", "La connaissance, la sagesse et le pouvoir"], ["foi, l’espérance et la charité"]),
  ),
  ch("alma", 8,
    q("a", "3", "Dans quel pays Alma se rendit-il au début de la dixième année du règne des juges ?", "Au pays de Mélek", ["Au pays de Gédéon", "Au pays de Jershon"], ["pays de Mélek"]),
    q("b", "6", "Comment s’appelait la ville où Alma arriva après trois jours de voyage au nord de Mélek ?", "Ammonihah", ["Zarahemla", "Jershon"], ["Ammonihah"]),
    q("c", "21", "Comment s’appelait l’homme qui reçut Alma dans sa maison ?", "Amulek", ["Amulon", "Amaléki"], ["Amulek"]),
  ),
  ch("alma", 9,
    q("a", "4", "Que dirent les habitants d’Ammonihah qu’ils ne croiraient pas même si Alma le prophétisait ?", "Que la ville serait détruite en un seul jour", ["Que la ville périrait dans un déluge", "Que la ville serait prise par les Lamanites"], ["un seul jour"]),
    q("b", "26", "Quand le Fils de Dieu viendra-t-il dans sa gloire selon l’ange ?", "Il ne se passera pas beaucoup de jours", ["Dans plusieurs centaines d’années", "Dans bien plus de mille ans"], ["beaucoup de jours"]),
    q("c", "34", "Qui s’avança et commença aussi à prêcher au peuple ?", "Amulek", ["Zeezrom", "Gédéon"], ["Amulek"]),
  ),
  ch("alma", 10,
    q("a", "2", "Qui était le père d’Amulek ?", "Giddonah", ["Aminadi", "Ismaël"], ["Giddonah"]),
    q("b", "7", "Qui apparut à Amulek pendant son voyage ?", "Un ange du Seigneur", ["Un prophète de Mélek", "Un serviteur d’Alma"], ["ange du Seigneur"]),
    q("c", "31", "Comment s’appelait le principal des hommes de loi qui accusa Amulek et Alma ?", "Zeezrom", ["Korihor", "Gédéon"], ["Zeezrom"]),
  ),
  ch("alma", 11,
    q("a", "3", "Que recevait un juge comme salaire pour un jour ?", "Une sénine d’or", ["Un limna d’or", "Un onti d’argent"], ["sénine d’or"]),
    q("b", "21", "Qui commença à interroger Amulek ?", "Zeezrom", ["Gédéon", "Korihor"], ["Zeezrom"]),
    q("c", "38-39", "Qui est selon Amulek le Père éternel même du ciel et de la terre ?", "Le Fils de Dieu", ["Le prophète Alma", "L’ange du Seigneur"], ["Fils de Dieu"]),
  ),
  ch("alma", 12,
    q("a", "20", "Qui était Antionah ?", "Un de leurs principaux dirigeants", ["Un homme de loi très expérimenté", "Un chef de l’armée des Néphites"], ["principaux dirigeants"]),
    q("b", "16", "Comment Alma appelle-t-il la seconde mort ?", "Une mort spirituelle", ["Une mort temporelle", "Une mort corporelle"], ["mort spirituelle"]),
    q("c", "21", "Que plaça Dieu à l’est du jardin d’Éden selon l’Écriture ?", "Des chérubins et une épée flamboyante", ["Un mur avec une grande porte d’or", "Un ange avec une clé en or massif"], ["chérubins"]),
  ),
  ch("alma", 13,
    q("a", "15", "À qui Abraham paya-t-il la dîme ?", "À Melchisédek", ["Au roi Salomon", "Au prophète Élie"], ["Melchisédek"]),
    q("b", "17", "De quel pays Melchisédek était-il roi ?", "Du pays de Salem", ["Du pays de Moab", "Du pays d’Égypte"], ["pays de Salem"]),
    q("c", "9", "Comment le Fils est-il appelé au verset 9 ?", "Le Fils unique du Père", ["Le premier-né du Père", "L’oint du Père"], ["Fils unique du Père"]),
  ),
  ch("alma", 14,
    q("a", "16", "À l’ordre et à la doctrine de qui le grand juge d’Ammonihah appartenait-il ?", "De Néhor", ["D’Amlici", "De Korihor"], ["Néhor"]),
    q("b", "18", "Combien de jours Alma et Amulek restèrent-ils en prison avant que les docteurs de la loi viennent ?", "Trois jours", ["Sept jours", "Deux jours"], ["trois jours"]),
    q("c", "27", "Que se passa-t-il quand Alma et Amulek eurent invoqué le Seigneur pour être délivrés ?", "La terre trembla violemment et les murs s’effondrèrent", ["Un grand incendie éclata et ravagea la ville entière", "Une violente grêle se mit à tomber sur toute la prison"], ["terre trembla violemment"]),
  ),
  ch("alma", 15,
    q("a", "1", "Dans quel pays Alma et Amulek allèrent-ils après avoir quitté Ammonihah ?", "Au pays de Sidom", ["Au pays de Mélek", "Au pays de Néphi"], ["pays de Sidom"]),
    q("b", "3", "De quoi Zeezrom souffrait-il à Sidom ?", "D’une fièvre ardente", ["D’une grave blessure", "D’une cécité sévère"], ["fièvre ardente"]),
    q("c", "12", "Que fit Alma de Zeezrom après sa guérison ?", "Il le baptisa pour le Seigneur", ["Il le renvoya à Ammonihah", "Il lui fit quitter l’Église"], ["baptisa"]),
  ),
  ch("alma", 16,
    q("a", "5", "Comment s’appelait le capitaine en chef des armées des Néphites ?", "Zoram", ["Moroni", "Gédéon"], ["Zoram"]),
    q("b", "10", "Que devint la ville d’Ammonihah ?", "En un seul jour, elle fut laissée désolée", ["Elle fut peu à peu occupée par les Lamanites", "Elle fut engloutie par un tremblement de terre"], ["en un seul jour"]),
    q("c", "19", "Que prêchaient les prêtres au sujet du Fils de Dieu ?", "Ses souffrances et sa mort", ["Ses richesses et sa puissance", "Son mariage et sa famille"], ["souffrances et sa mort"]),
  ),
  ch("alma", 17,
    q("a", "4", "Pendant combien d’années les fils de Mosiah avaient-ils enseigné la parole parmi les Lamanites ?", "Quatorze ans", ["Quarante ans", "Sept ans"], ["quatorze ans"]),
    q("b", "21", "Comment s’appelait le roi du pays d’Ismaël ?", "Lamoni", ["Limhi", "Laman"], ["Lamoni"]),
    q("c", "38", "Combien de Lamanites tombèrent par la fronde d’Ammon ?", "Six Lamanites", ["Quatre Lamanites", "Huit Lamanites"], ["six"]),
  ),
  ch("alma", 18,
    q("a", "13", "Que signifie le mot Rabbanah ?", "Puissant ou grand roi", ["Seigneur sage et puissant", "Brave chef d’armée"], ["grand roi"]),
    q("b", "43", "Combien de temps le roi Lamoni resta-t-il étendu comme mort sur son lit ?", "Deux jours et deux nuits", ["Trois jours et trois nuits", "Un jour et une nuit"], ["deux jours et deux nuits"]),
    q("c", "9", "Que faisait Ammon quand le roi demanda après lui ?", "Il nourrissait les chevaux du roi", ["Il festoyait avec les serviteurs", "Il dormait dans la tente du roi"], ["chevaux"]),
  ),
  ch("alma", 19,
    q("a", "8", "Que dit Ammon du roi Lamoni quand il le regarda ?", "Il n’est pas mort, mais il dort en Dieu", ["Il est blessé et doit se reposer près du feu", "Il est malade et a besoin d’un médecin"], ["dort en Dieu"]),
    q("b", "13", "Que dit Lamoni quand il se releva ?", "Qu’il avait vu son Rédempteur", ["Qu’il avait vu une grande armée", "Qu’il avait vu son père"], ["Rédempteur"]),
    q("c", "28", "Qui avait fait rassembler la multitude ?", "Une servante lamanite", ["Une fille du roi", "Un prêtre du peuple"], ["servante"]),
  ),
  ch("alma", 20,
    q("a", "3", "Dans quel pays les frères d’Ammon étaient-ils en prison ?", "Au pays de Middoni", ["Au pays d’Ismaël", "Au pays de Sidom"], ["Middoni"]),
    q("b", "10", "Comment le père de Lamoni appelle-t-il le Néphite Ammon ?", "Un des enfants d’un menteur", ["Un des fils d’un roi", "Un des serviteurs du diable"], ["enfants d’un menteur"]),
    q("c", "23", "Qu’offrit le vieux roi à Ammon s’il l’épargnait ?", "La moitié du royaume", ["Un tiers de ses trésors", "Sa fille aînée"], ["moitié du royaume"]),
  ),
  ch("alma", 21,
    q("a", "2", "Quelle ville les Lamanites, les Amalékites et le peuple d’Amulon avaient-ils construite ?", "Une grande ville appelée Jérusalem", ["Une grande ville appelée Néphi", "Une grande ville appelée Zarahemla"], ["Jérusalem"]),
    q("b", "14", "Par qui Aaron et ses frères furent-ils délivrés de prison ?", "Par Lamoni et Ammon", ["Par Mosiah et Alma", "Par Omner et Himni"], ["Lamoni", "Ammon"]),
    q("c", "22", "Qu’annonça le roi Lamoni à son peuple au sujet de l’adoration du Seigneur ?", "Qu’ils étaient libres d’adorer le Seigneur partout", ["Qu’ils ne pouvaient adorer que dans les synagogues", "Qu’ils devaient adorer uniquement le roi"], ["adorer le Seigneur"]),
  ),
  ch("alma", 22,
    q("a", "3", "Que promirent Aaron et ses frères au roi en échange de leur vie ?", "Qu’ils seraient ses serviteurs", ["Qu’ils lui donneraient leurs biens", "Qu’ils quitteraient le pays"], ["serviteurs"]),
    q("b", "7", "Que disent les Amalékites au sujet de Dieu selon le roi ?", "Qu’il existe bel et bien un Dieu", ["Qu’il y a deux dieux au ciel", "Qu’il n’y a aucun Dieu"], ["un Dieu"]),
    q("c", "17", "Que fit le roi quand Aaron eut dit ses paroles ?", "Il se prosterna et se jeta sur le sol", ["Il se leva et quitta la grande salle", "Il appela sa garde du corps"], ["sur le sol"]),
  ),
  ch("alma", 23,
    q("a", "17", "Comment les Lamanites convertis s’appelèrent-ils ?", "Anti-Néphi-Léhis", ["Néphi-Lamanites", "Léhi-Néphites"], ["Anti-Néphi-Léhis"]),
    q("b", "1", "Que commanda le roi des Lamanites à son peuple au sujet d’Ammon et de ses frères ?", "De ne pas porter la main sur eux", ["De les chasser hors du pays", "De ne prêcher qu’en Ismaël"], ["porter la main"]),
    q("c", "14", "Quels groupes ne se convertirent pas ?", "Les Amalékites et les Amulonites", ["Les Néphites de Zarahemla", "Le peuple d’Ismaël et de Middoni"], ["Amalékites", "Amulonites"]),
  ),
  ch("alma", 24,
    q("a", "3", "Quel nom le roi donna-t-il à son fils à qui il conféra le royaume ?", "Anti-Néphi-Léhi", ["Anti-Léhi-Néphi", "Néphi-Anti-Léhi"], ["Anti-Néphi-Léhi"]),
    q("b", "16", "Que feraient-ils de leurs épées si leurs frères cherchaient à les détruire selon le roi ?", "Les enterrer profondément dans la terre", ["Les fondre pour en faire des outils", "Les offrir en cadeau aux Néphites"], ["profondément dans la terre"]),
    q("c", "22", "Combien d’entre eux furent tués sans résistance par les Lamanites ?", "Mille cinq personnes", ["Mille dix personnes", "Cinq cent cinq personnes"], ["mille cinq"]),
  ),
  ch("alma", 25,
    q("a", "11", "Qui fut le premier à subir la mort par le feu à cause de sa croyance en Dieu ?", "Abinadi", ["Amulek", "Gédéon"], ["Abinadi"]),
    q("b", "14", "Que firent les Lamanites convertis de leurs armes de guerre ?", "Ils enterrèrent leurs armes de guerre", ["Ils vendirent leurs armes de guerre", "Ils gardaient toujours leurs armes sur eux"], ["enterrèrent"]),
    q("c", "16", "À quoi la loi de Moïse servait-elle pour eux ?", "À fortifier leur foi au Christ", ["À séparer leur peuple des Néphites", "À garder leurs richesses au temple"], ["foi au Christ"]),
  ),
  ch("alma", 26,
    q("a", "4", "Que dit Ammon au sujet de milliers de Lamanites ?", "Qu’ils ont été amenés dans la bergerie de Dieu", ["Qu’ils se sont mis au service des Néphites", "Qu’ils ont chassé leur roi du pays entier"], ["bergerie de Dieu"]),
    q("b", "22", "Que donne-t-on à celui qui se repent, fait preuve de foi et prie continuellement selon Ammon ?", "De connaître les mystères de Dieu", ["Une place à côté du roi", "La richesse et le pouvoir dans le pays"], ["mystères de Dieu"]),
    q("c", "12", "De quoi Ammon dit-il qu’il se vantera ?", "Du Seigneur, son Dieu", ["De sa propre force", "De sa propre sagesse"], ["Dieu"]),
  ),
  ch("alma", 27,
    q("a", "22", "Quel pays le peuple de Néphi céda-t-il au peuple d’Ammon ?", "Le pays de Jershon", ["Le pays de Gédéon", "Le pays de Mélek"], ["Jershon"]),
    q("b", "12", "Pourquoi le Seigneur commanda-t-il à Ammon de faire sortir le peuple du pays ?", "Afin qu’il ne périsse pas", ["Pour posséder plus de terres", "Pour attaquer les Néphites"], ["ne périsse pas"]),
    q("c", "30", "Comment le peuple d’Ammon est-il décrit au verset 30 ?", "Un peuple zélé et bien-aimé", ["Un peuple belliqueux et redouté", "Un peuple riche et puissant"], ["peuple zélé et bien-aimé"]),
  ),
  ch("alma", 28,
    q("a", "7", "Quelle année du règne des juges finit après la terrible bataille ?", "La quinzième année", ["La douzième année", "La vingtième année"], ["quinzième"]),
    q("b", "6", "Comment est décrit le jour de la terrible bataille ?", "Un jour de tristesse", ["Un jour de fête", "Un jour tranquille"], ["jour de tristesse"]),
    q("c", "12", "Que font pourtant de nombreux milliers de personnes qui pleurent la perte des leurs ?", "Elles se réjouissent et exultent dans l’espérance", ["Elles fuient le pays et se cachent", "Elles rassemblent leurs armées pour se venger"], ["exultent dans l’espérance"]),
  ),
  ch("alma", 29,
    q("a", "1", "Que voudrait être Alma pour parler avec la trompette de Dieu ?", "Un ange du ciel", ["Un roi puissant", "Un grand prophète"], ["ange"]),
    q("b", "1", "Avec quoi Alma voudrait-il alors parler ?", "Avec la trompette de Dieu", ["Avec la harpe de David", "Avec la voix du roi"], ["trompette de Dieu"]),
    q("c", "8", "À qui le Seigneur accorde-t-il des gens de leur propre nation et de leur propre langue pour enseigner sa parole ?", "À toutes les nations", ["Aux Néphites seulement", "Aux Juifs seulement"], ["toutes les nations"]),
  ),
  ch("alma", 30,
    q("a", "12", "Comment s’appelait l’antéchrist qui prêchait au peuple qu’il n’y aurait pas de Christ ?", "Korihor", ["Néhor", "Amlici"], ["Korihor"]),
    q("b", "50", "Qu’arriva-t-il à Korihor après qu’Alma eut parlé ?", "Il fut frappé de mutisme", ["Il fut frappé de cécité", "Il fut lapidé par le peuple"], ["mutisme"]),
    q("c", "23", "Comment s’appelait le grand prêtre du pays de Gédéon ?", "Giddonah", ["Néphihah", "Hélaman"], ["Giddonah"]),
  ),
  ch("alma", 31,
    q("a", "21", "Que signifie le nom Raméumptom ?", "La sainte chaire", ["La haute tour", "Le lieu des élus"], ["sainte chaire"]),
    q("b", "3", "Comment les Zoramites appelaient-ils le pays où ils s’étaient rassemblés ?", "Antionum", ["Gédéon", "Jershon"], ["Antionum"]),
    q("c", "7", "Comment s’appelait le fils aîné d’Alma, qu’il ne prit pas avec lui chez les Zoramites ?", "Hélaman", ["Shiblon", "Corianton"], ["Hélaman"]),
  ),
  ch("alma", 32,
    q("a", "28", "À quoi Alma compare-t-il la parole ?", "À une semence", ["À une rivière", "À un feu"], ["semence"]),
    q("b", "21", "Que n’est pas la foi selon Alma ?", "Avoir la connaissance parfaite des choses", ["Espérer en des choses qui ne sont pas vues", "Faire confiance à une bonne semence"], ["connaissance parfaite"]),
    q("c", "10", "Où peut-on adorer Dieu selon Alma ?", "Partout, pas seulement dans les synagogues", ["Seulement dans les synagogues le sabbat", "Seulement dans le temple du roi"], ["synagogues"]),
  ),
  ch("alma", 33,
    q("a", "3", "Quel prophète d’autrefois est cité au sujet de la prière et du culte ?", "Zénos", ["Ésaïe", "Osée"], ["Zénos"]),
    q("b", "15", "Quel second prophète d’autrefois a aussi parlé du Fils de Dieu ?", "Zénock", ["Ésias", "Jarom"], ["Zénock"]),
    q("c", "19", "Qu’est-ce qui fut élevé dans le désert afin que quiconque le regarderait vive ?", "Une figure", ["Un autel", "Une tente"], ["figure"]),
  ),
  ch("alma", 34,
    q("a", "10", "Quelle sorte de sacrifice doit-il y avoir selon Amulek ?", "Un grand et dernier sacrifice", ["Un sacrifice quotidien de grain", "Un sacrifice annuel de moutons"], ["grand et dernier sacrifice"]),
    q("b", "21", "Quand faut-il invoquer le Seigneur dans sa maison selon Amulek ?", "Le matin, à midi et le soir, chaque jour", ["Une fois par semaine à la synagogue", "Seulement en cas de détresse dans le pays"], ["matin", "soir"]),
    q("c", "32", "Pour quoi cette vie est-elle le moment selon Amulek ?", "Se préparer à rencontrer Dieu", ["Acquérir richesse et honneur", "Bâtir un royaume sur la terre"], ["rencontrer Dieu"]),
  ),
  ch("alma", 35,
    q("a", "1", "Dans quel pays Alma et Amulek passèrent-ils après leur prédication chez les Zoramites ?", "Au pays de Jershon", ["Au pays de Mélek", "Au pays de Gédéon"], ["Jershon"]),
    q("b", "13", "Où le peuple d’Ammon alla-t-il en quittant Jershon ?", "Au pays de Mélek", ["Au pays de Néphi", "Au pays de Sidom"], ["pays de Mélek"]),
    q("c", "12", "Quelle année du règne des juges finit dans ce chapitre ?", "La dix-septième année", ["La seizième année", "La dix-huitième année"], ["dix-septième année"]),
  ),
  ch("alma", 36,
    q("a", "10", "Combien de temps Alma ne put-il ouvrir la bouche après l’apparition de l’ange ?", "Trois jours et trois nuits", ["Deux jours et deux nuits", "Sept jours et sept nuits"], ["trois jours et trois nuits"]),
    q("b", "18", "Quelles paroles Alma cria-t-il au-dedans de son cœur ?", "Ô Jésus, Fils de Dieu, sois miséricordieux envers moi", ["Ô Seigneur, délivre-moi de mes ennemis maintenant", "Ô Dieu, reprends ma vie, je t’en prie"], ["Jésus, Fils de Dieu"]),
    q("c", "22", "À la vision de qui Alma compare-t-il ce qu’il vit, Dieu assis sur son trône ?", "À celle de Léhi", ["À celle de Néphi", "À celle de Mosiah"], ["Léhi"]),
  ),
  ch("alma", 37,
    q("a", "6", "Que réalisent des choses petites et simples selon Alma ?", "De grandes choses", ["Des choses petites", "Des choses mauvaises"], ["grandes choses"]),
    q("b", "21", "De combien de plaques Alma parla-t-il à Hélaman, qu’il devait garder ?", "Vingt-quatre plaques", ["Vingt-deux plaques", "Vingt-six plaques"], ["vingt-quatre"]),
    q("c", "26", "Qu’est-il arrivé à ceux qui ne se sont pas repentis ?", "Ils ont été détruits", ["Ils ont été bannis", "Ils ont été dispersés"], ["détruits"]),
  ),
  ch("alma", 38,
    q("a", "4", "Pourquoi Shiblon fut-il lapidé selon Alma ?", "Pour l’amour de la parole", ["À cause de sa richesse", "À cause de son armée"], ["amour de la parole"]),
    q("b", "13", "Pourquoi les Zoramites prient-ils selon Alma ?", "Pour être entendus des hommes", ["Pour être bénis de Dieu", "Pour confesser leurs péchés à Dieu"], ["entendus des hommes"]),
    q("c", "11", "De quoi Shiblon ne doit-il pas se vanter selon Alma ?", "De sa propre sagesse", ["De la grâce de Dieu", "De l’aide de ses frères"], ["sagesse"]),
  ),
  ch("alma", 39,
    q("a", "10", "Avec qui Corianton devait-il tenir conseil dans ses entreprises selon Alma ?", "Avec ses frères aînés", ["Avec le roi du pays", "Avec les maîtres zoramites"], ["frères aînés"]),
    q("b", "14", "Pourquoi Corianton ne doit-il pas rechercher la richesse selon Alma ?", "Parce qu’il ne peut pas l’emporter", ["Parce que les Lamanites la prendraient", "Parce que seuls les juges sont riches"], ["emporter"]),
    q("c", "18", "À qui le plan de rédemption doit-il être révélé selon Alma ?", "À ce peuple et à ses enfants", ["Seulement aux prêtres de l’Église", "Seulement aux juges du pays"], ["ce peuple"]),
  ),
  ch("alma", 40,
    q("a", "12", "Comment s’appelle l’état de bonheur des justes entre la mort et la résurrection ?", "Un état qui s’appelle paradis", ["Un état qui s’appelle royaume", "Un état qui s’appelle jardin d’Éden"], ["paradis"]),
    q("b", "14", "Dans quel état se trouve l’âme des méchants selon le verset 14 ?", "Dans les ténèbres et l’attente affreuse", ["Dans le repos et la paix du cœur", "Dans un sommeil jusqu’à la résurrection"], ["ténèbres"]),
    q("c", "23", "Qu’arrive-t-il à l’âme lors de la restauration selon Alma ?", "L’âme sera restituée au corps", ["L’âme restera à jamais séparée", "Le corps sera donné à la terre"], ["restituée au corps"]),
  ),
  ch("alma", 41,
    q("a", "13", "Que signifie le mot restauration selon Alma ?", "Ramener le mal au mal", ["Passer du péché au bonheur", "Tout rendre sans jugement"], ["mal au mal"]),
    q("b", "10", "Qu’est-ce qui n’a jamais été le bonheur selon Alma ?", "La méchanceté", ["Le travail dur", "L’obéissance"], ["méchanceté"]),
    q("c", "14", "Que doit faire continuellement Corianton selon Alma ?", "Faire continuellement le bien", ["Se venger continuellement", "Chercher continuellement la richesse"], ["continuellement le bien"]),
  ),
  ch("alma", 42,
    q("a", "4", "Que fut-il accordé à l’homme selon Alma ?", "Un temps probatoire pour se repentir", ["Un temps de repos sans loi", "Un séjour éternel au jardin d’Éden"], ["temps probatoire"]),
    q("b", "22-23", "Qui la miséricorde réclame-t-elle selon Alma ?", "Le pénitent, celui qui se repent vraiment", ["Les puissants qui gouvernent le pays", "Les riches qui font beaucoup d’offrandes"], ["pénitent"]),
    q("c", "27", "Qui peut venir prendre des eaux de la vie selon Alma ?", "Quiconque veut venir en prendre gratuitement", ["Seulement les prêtres de l’Église du pays", "Seulement celui qui est assez riche pour payer"], ["veut venir"]),
  ),
  ch("alma", 43,
    q("a", "17", "Quel âge avait Moroni quand il devint capitaine en chef ?", "Vingt-cinq ans", ["Trente-cinq ans", "Quarante-cinq ans"], ["vingt-cinq ans"]),
    q("b", "19", "De quoi Moroni avait-il équipé son peuple ?", "De plastrons et de boucliers pour le bras", ["De chars de guerre et de chevaux rapides", "De casques et de longues lances"], ["plastrons", "boucliers pour le bras"]),
    q("c", "44", "Comment s’appelait le capitaine en chef des Lamanites ?", "Zérahemnah", ["Amalickiah", "Zemnarihah"], ["Zérahemnah"]),
  ),
  ch("alma", 44,
    q("a", "6", "Que commanda Moroni à Zérahemnah ?", "De livrer ses armes de guerre", ["De renvoyer son armée chez elle", "De céder son royaume à Moroni"], ["armes de guerre"]),
    q("b", "20", "Que fit Moroni aux Lamanites après avoir fait cesser l’œuvre de mort ?", "Il leur prit leurs armes de guerre", ["Il leur laissa garder leurs armes", "Il leur donna nourriture et vêtements"], ["armes de guerre"]),
    q("c", "24", "Quelle année du règne des juges finit avec les annales d’Alma ?", "La dix-huitième année", ["La dix-septième année", "La dix-neuvième année"], ["dix-huitième année"]),
  ),
  ch("alma", 45,
    q("a", "4", "En qui Alma demanda-t-il à son fils Hélaman de croire, celui qui viendra ?", "En Jésus-Christ", ["Au roi Benjamin", "Au prophète Moïse"], ["Jésus-Christ"]),
    q("b", "10", "Combien d’années après la manifestation du Christ les Néphites dégénéreraient-ils dans l’incrédulité selon Alma ?", "Quatre cents ans", ["Deux cents ans", "Six cents ans"], ["quatre cents ans"]),
    q("c", "18", "Qu’arriva-t-il à Alma après qu’il eut quitté Zarahemla ?", "On n’entendit plus jamais parler de lui", ["Il mourut peu après à Mélek", "Les Lamanites le firent prisonnier"], ["plus jamais"]),
  ),
  ch("alma", 46,
    q("a", "3", "Comment s’appelait le chef de ceux qui étaient furieux contre leurs frères ?", "Amalickiah", ["Zérahemnah", "Léhonti"], ["Amalickiah"]),
    q("b", "12", "Sur quoi Moroni écrivit-il « En souvenir de notre Dieu » ?", "Sur un morceau de manteau", ["Sur une plaque de cuivre", "Sur un mur du temple"], ["manteau"]),
    q("c", "36", "Que fit hisser Moroni sur toutes les tours du pays des Néphites ?", "L’étendard de la liberté", ["Un drapeau blanc de paix", "L’étendard royal"], ["étendard de la liberté"]),
  ),
  ch("alma", 47,
    q("a", "7", "Comment s’appelait la montagne où les Lamanites s’étaient rassemblés ?", "La montagne Antipas", ["La montagne de Manti", "La montagne Onidah"], ["Antipas"]),
    q("b", "11", "Comment s’appelait le chef de ceux qui se trouvaient sur la montagne ?", "Léhonti", ["Lamoni", "Zoram"], ["Léhonti"]),
    q("c", "18", "Que fit faire Amalickiah pour se débarrasser de Léhonti ?", "Lui faire administrer peu à peu du poison", ["Le faire tuer par l’épée en pleine nuit", "Le faire emprisonner à Néphi pour toujours"], ["poison"]),
  ),
  ch("alma", 48,
    q("a", "5", "Parmi qui Amalickiah nomma-t-il des capitaines en chef ?", "Parmi les Zoramites", ["Parmi les Amlicites", "Parmi les Néphites"], ["Zoramites"]),
    q("b", "11", "Quel genre d’homme était Moroni selon le verset 11 ?", "Un homme qui n’aimait pas verser le sang", ["Un homme qui aimait la guerre pour gagner", "Un homme qui cherchait le pouvoir plus que la paix"], ["sang"]),
    q("c", "21", "Quand les Néphites furent-ils contraints de combattre à contrecœur ?", "Tout à la fin de la dix-neuvième année", ["Tout à la fin de la dixième année", "Au début de la vingtième année"], ["dix-neuvième année"]),
  ),
  ch("alma", 49,
    q("a", "3", "Quelle ville avait été reconstruite quand les Lamanites l’attaquèrent de nouveau ?", "La ville d’Ammonihah", ["La ville de Néphihah", "La ville de Zarahemla"], ["Ammonihah"]),
    q("b", "4", "De quoi les Néphites s’étaient-ils entourés ?", "D’un rempart de terre", ["D’un mur de pierre", "D’un fossé plein d’eau"], ["rempart de terre"]),
    q("c", "24", "Combien de Néphites furent blessés au passage environ ?", "Environ cinquante", ["Environ cent", "Environ deux cents"], ["cinquante"]),
  ),
  ch("alma", 50,
    q("a", "13", "Comment les Néphites appelèrent-ils la ville qu’ils commencèrent à fonder près de la mer de l’est ?", "La ville de Moroni", ["La ville de Léhi", "La ville d’Aaron"], ["Moroni"]),
    q("b", "2", "Que fit mettre Moroni sur le sommet des remparts de terre autour des villes ?", "Des ouvrages en bois jusqu’à hauteur d’homme", ["Des murs de briques avec des tours de guet", "Un large fossé avec des pieux pointus"], ["hauteur d’homme"]),
    q("c", "40", "Comment s’appelait le fils de Néphihah qui succéda à son père comme grand juge ?", "Pahoran", ["Hélaman", "Gédéon"], ["Pahoran"]),
  ),
  ch("alma", 51,
    q("a", "5", "Comment appelait-on ceux qui voulaient que Pahoran soit détrôné du siège du jugement ?", "Les hommes-du-roi", ["Les hommes-du-droit", "Les hommes-du-peuple"], ["hommes-du-roi"]),
    q("b", "34", "Qui enfonça un javelot dans le cœur du roi Amalickiah ?", "Téancum", ["Moroni", "Hélaman"], ["Téancum"]),
    q("c", "19", "Combien de dissidents furent abattus par l’épée ?", "Quatre mille", ["Deux mille", "Six mille"], ["quatre mille"]),
  ),
  ch("alma", 52,
    q("a", "3", "Comment s’appelait le frère d’Amalickiah qui devint roi ?", "Ammoron", ["Amulon", "Ammon"], ["Ammoron"]),
    q("b", "16", "Quelle ville Téancum devait-il attaquer sur ordre de Moroni et reprendre si possible ?", "La ville de Mulek", ["La ville de Gid", "La ville de Néphihah"], ["ville de Mulek"]),
    q("c", "33", "Qui était le chef des Lamanites au caractère indomptable ?", "Jacob, un Zoramite", ["Léhonti, un Lamanite", "Ammoron, un Amalékite"], ["Jacob"]),
  ),
  ch("alma", 53,
    q("a", "18", "Combien de jeunes hommes conclurent l’alliance et prirent leurs armes de guerre ?", "Deux mille", ["Trois mille", "Quatre mille"], ["deux mille"]),
    q("b", "1", "Que durent faire les prisonniers lamanites ?", "Enterrer leurs morts", ["Bâtir un grand temple", "Cultiver tout le pays"], ["enterrer leurs morts"]),
    q("c", "21", "Qu’avait-on enseigné aux jeunes soldats selon le verset 21 ?", "À garder les commandements de Dieu", ["À utiliser les armes de l’ennemi", "À suivre la loi du roi"], ["commandements de Dieu"]),
  ),
  ch("alma", 54,
    q("a", "20", "Sur quoi Moroni voulait-il négocier avec Ammoron selon ces lettres ?", "Un échange de prisonniers", ["Une paix sans conditions", "La reddition de la ville de Gid"], ["prisonniers"]),
    q("b", "16", "De qui Ammoron, roi des Lamanites, était-il le frère ?", "D’Amalickiah", ["De Zérahemnah", "De Léhonti"], ["Amalickiah"]),
    q("c", "23", "De qui Ammoron dit-il être un descendant ?", "De Zoram", ["De Néphi", "De Laman"], ["Zoram"]),
  ),
  ch("alma", 55,
    q("a", "5", "Comment s’appelait l’homme que Moroni choisit pour tromper les gardes des prisonniers ?", "Laman", ["Lamoni", "Lémuel"], ["Laman"]),
    q("b", "7", "Dans quelle ville les Néphites prisonniers étaient-ils gardés ?", "Dans la ville de Gid", ["Dans la ville de Mulek", "Dans la ville de Manti"], ["ville de Gid"]),
    q("c", "13", "Comment Laman et ses hommes plongèrent-ils les gardes lamanites dans le sommeil ?", "Avec du vin en abondance", ["Avec un lourd festin", "Avec des fruits sucrés"], ["vin"]),
  ),
  ch("alma", 56,
    q("a", "10", "Qui était le chef de l’armée à laquelle Hélaman unit ses jeunes soldats ?", "Antipus", ["Téancum", "Pahoran"], ["Antipus"]),
    q("b", "47", "À quoi les jeunes soldats pensaient-ils plus qu’à leur vie ?", "À la liberté de leurs pères", ["À la richesse de leurs mères", "À la gloire de leur roi"], ["liberté de leurs pères"]),
    q("c", "56", "Combien des jeunes soldats d’Hélaman étaient tombés après le combat ?", "Pas une seule âme n’était tombée", ["Deux d’entre eux étaient tombés", "Cinquante d’entre eux étaient tombés"], ["pas une seule âme"]),
  ),
  ch("alma", 57,
    q("a", "19", "Combien de jeunes soldats comptait la petite troupe d’Hélaman ?", "Deux mille soixante", ["Deux mille quarante", "Deux mille seize"], ["deux mille soixante"]),
    q("b", "25", "Combien de jeunes soldats s’étaient évanouis à cause de la perte de sang ?", "Deux cents", ["Trois cents", "Quatre cents"], ["deux cents"]),
    q("c", "29", "Qui était le capitaine en chef de la troupe chargée de garder les prisonniers ?", "Un homme nommé Gid", ["Un homme nommé Antipus", "Un homme nommé Léhi"], ["Gid"]),
  ),
  ch("alma", 58,
    q("a", "1", "Quelle ville était le but suivant d’Hélaman et de son armée ?", "La ville de Manti", ["La ville de Gid", "La ville de Zeezrom"], ["ville de Manti"]),
    q("b", "8", "Combien d’hommes vinrent aider Hélaman avec de la nourriture ?", "Deux mille hommes", ["Six mille hommes", "Mille hommes"], ["deux mille"]),
    q("c", "28", "Comment Hélaman et son armée prirent-ils la ville de Manti ?", "Par un stratagème, sans verser de sang", ["Par un long siège avec la famine", "Par une attaque directe avec des armes"], ["sans verser de sang"]),
  ),
  ch("alma", 59,
    q("a", "3", "À qui Moroni envoya-t-il une épître pour faire rassembler des hommes ?", "À Pahoran", ["À Hélaman", "À Téancum"], ["Pahoran"]),
    q("b", "8", "Quelle ville fut perdue au profit des Lamanites, obligeant le peuple à fuir ?", "La ville de Néphihah", ["La ville de Zarahemla", "La ville d’Ammonihah"], ["Néphihah"]),
    q("c", "13", "Contre qui Moroni fut-il en colère à cause de son indifférence pour la liberté du pays ?", "Contre le gouvernement", ["Contre les Lamanites", "Contre sa propre armée"], ["gouvernement"]),
  ),
  ch("alma", 60,
    q("a", "1", "À qui Moroni écrivit-il sa lettre ?", "Au gouverneur Pahoran", ["Au roi des Lamanites", "À Hélaman, le grand prêtre"], ["Pahoran"]),
    q("b", "36", "Que dit Moroni de son désir dans sa lettre ?", "Il ne cherche pas le pouvoir mais à l’abattre", ["Il cherche le pouvoir et l’autorité dans tout le pays", "Il cherche l’honneur et la gloire sur le champ de bataille"], ["pas le pouvoir"]),
    q("c", "3", "Qui souffrit avec Moroni et ses hommes de très grandes souffrances ?", "Hélaman et ses hommes", ["Téancum et ses hommes", "Pahoran et ses hommes"], ["Hélaman"]),
  ),
  ch("alma", 61,
    q("a", "5", "Dans quel pays Pahoran s’enfuit-il quand il fut chassé du siège du jugement ?", "Au pays de Gédéon", ["Au pays de Mélek", "Au pays de Jershon"], ["pays de Gédéon"]),
    q("b", "8", "Qu’avaient fait les rebelles de Zarahemla ?", "Ils avaient établi un roi sur eux", ["Ils avaient incendié le temple", "Ils avaient destitué tous les juges"], ["établi un roi"]),
    q("c", "9", "De quoi Pahoran se réjouit-il dans sa réponse à Moroni ?", "De la grandeur du cœur de Moroni", ["De la victoire sur les Lamanites", "Du soutien des hommes-du-roi"], ["grandeur"]),
  ),
  ch("alma", 62,
    q("a", "8", "Qu’advint-il de Pachus et de Pahoran quand Zarahemla fut reprise ?", "Pachus fut tué, Pahoran rétabli", ["Pahoran fut tué, Pachus rétabli", "Moroni fut tué, Pahoran resta absent"], ["Pachus fut tué"]),
    q("b", "43", "À qui Moroni remit-il le commandement de ses armées ?", "À son fils Moronihah", ["À son fils Hélaman", "À Léhi et Téancum"], ["Moronihah"]),
    q("c", "36-37", "Lequel des capitaines de Moroni fut tué dans le camp des Lamanites ?", "Téancum", ["Pahoran", "Gédéon"], ["Téancum"]),
  ),
  ch("alma", 63,
    q("a", "1", "Qui prit possession des objets sacrés la trente-sixième année ?", "Shiblon", ["Hélaman", "Moroni"], ["Shiblon"]),
    q("b", "5", "Comment s’appelait l’homme qui construisit un navire extrêmement grand ?", "Hagoth", ["Moroni", "Zoram"], ["Hagoth"]),
    q("c", "8", "Qu’arriva-t-il à ceux qui s’embarquèrent et prirent la mer ?", "On n’entendit plus jamais parler d’eux", ["Ils s’installèrent dans le pays du nord", "Ils revinrent chez eux après un an"], ["plus jamais"]),
  ),
  // ===== EINDE =====
];
