import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Alma. French edition - generated from Dutch master.
export const alma: GeneesChapterSeed[] = [
  ch("alma", 1,
    q("a", "15", "Wat was de naam van de man die Gideon doodde?", "Nehor", ["Amlici", "Korihor"], ["Nehor"]),
    q("b", "15", "Waar werd Nehor ter dood gebracht?", "Op de top van de heuvel Manti", ["Aan de oever van de rivier Sidon", "Op de markt van Zarahemla"], ["heuvel Manti"]),
    q("c", "12", "Wat was volgens Alma voor het eerst onder het volk ingevoerd?", "Het priesterbedrog", ["Het houden van slaven", "De bouw van een tempel"], ["priesterbedrog"]),
  ),
  ch("alma", 2,
    q("a", "1", "Hoe heette de man die koning over het volk wilde worden?", "Amlici", ["Nehor", "Korihor"], ["Amlici"]),
    q("b", "31", "Hoe doodde Alma de aanvoerder van de Amlicieten?", "Met het zwaard", ["Met een speer", "Met een pijl"], ["zwaard"]),
    q("c", "15", "Bij welke heuvel kwamen de Amlicieten aan, ten oosten van de Sidon?", "De heuvel Amnihu", ["De heuvel Manti", "De heuvel Riplah"], ["Amnihu"]),
  ),
  ch("alma", 3,
    q("a", "4", "Wat hadden de Amlicieten op hun voorhoofd aangebracht?", "Een rood teken", ["Een blauw teken", "Een zwart teken"], ["rood"]),
    q("b", "26", "Hoeveel zielen werden er in dat ene jaar naar de eeuwige wereld gezonden?", "Duizenden en tienduizenden", ["Honderden en duizenden", "Slechts enkele honderden"], ["duizenden en tienduizenden"]),
    q("c", "22", "Waarom trok Alma deze keer niet zelf ten strijde tegen de Lamanieten?", "Omdat hij letsel had opgelopen", ["Omdat hij het leger niet vertrouwde", "Omdat hij een ander plan had"], ["letsel"]),
  ),
  ch("alma", 4,
    q("a", "5", "Hoeveel zielen sloten zich in het zevende jaar bij de kerk aan?", "Ongeveer drieduizend vijfhonderd", ["Ongeveer tweeduizend vijfhonderd", "Ongeveer vijfduizend driehonderd"], ["drieduizend vijfhonderd"]),
    q("b", "17", "Wie werd aangesteld als opperrechter toen Alma de rechterstoel overdroeg?", "Nephihah", ["Helaman", "Gideon"], ["Nephihah"]),
    q("c", "18", "Welk ambt behield Alma voor zichzelf?", "Dat van hogepriester", ["Dat van legeraanvoerder", "Dat van opperrechter"], ["hogepriester"]),
  ),
  ch("alma", 5,
    q("a", "38", "Welke naam draagt de goede herder die ons roept?", "Die van Christus", ["Die van Mormon", "Die van Abinadi"], ["Christus"]),
    q("b", "3", "Door wie was Alma gewijd tot hogepriester over de kerk?", "Door zijn vader Alma", ["Door koning Mosiah", "Door de profeet Abinadi"], ["vader Alma"]),
    q("c", "52", "Wat ligt volgens de Geest aan de wortel van de boom?", "De bijl", ["De zaag", "De spade"], ["bijl"]),
  ),
  ch("alma", 6,
    q("a", "8", "In welk dal begon Alma daarna het woord van God te verkondigen?", "Het dal Gideon", ["Het dal Lemuel", "Het dal Helam"], ["dal Gideon"]),
    q("b", "2", "Wat gebeurde er met wie zich van zijn zonden bekeerde en nog niet tot de kerk behoorde?", "Ze werden gedoopt tot bekering", ["Ze werden naar Zarahemla gestuurd", "Ze moesten eerst een jaar wachten"], ["tot bekering"]),
    q("c", "6", "Waarvoor werd de kinderen van God geboden dikwijls samen te komen?", "Voor vasten en machtig gebed", ["Voor offers en brandoffers", "Voor het bouwen van tempels"], ["vasten en machtig gebed"]),
  ),
  ch("alma", 7,
    q("a", "10", "Waar zal de Heer volgens Alma worden geboren?", "In Jeruzalem", ["In Nazareth", "In Zarahemla"], ["Jeruzalem"]),
    q("b", "10", "Hoe noemt Alma de moeder van de Heer?", "Een maagd, een kostbaar en uitverkoren vat", ["Een prinses, een rijke en machtige vrouw", "Een koningin, een rijk en edel vat"], ["kostbaar en uitverkoren vat"]),
    q("c", "24", "Welke drie dingen moet men volgens Alma hebben?", "Geloof, hoop en naastenliefde", ["Geloof, bekering en offers", "Kennis, wijsheid en macht"], ["geloof, hoop en naastenliefde"]),
  ),
  ch("alma", 8,
    q("a", "3", "Naar welk land reisde Alma in het tiende regeringsjaar van de rechters?", "Het land Melek", ["Het land Gideon", "Het land Jershon"], ["land Melek"]),
    q("b", "6", "Hoe heette de stad waar Alma na drie dagen reizen ten noorden van Melek aankwam?", "Ammonihah", ["Zarahemla", "Jershon"], ["Ammonihah"]),
    q("c", "21", "Hoe heette de man die Alma in zijn huis ontving?", "Amulek", ["Amulon", "Amaleki"], ["Amulek"]),
  ),
  ch("alma", 9,
    q("a", "4", "Wat zeiden de inwoners van Ammonihah dat Alma kon profeteren zonder dat zij het zouden geloven?", "Dat de stad in één dag zou worden verwoest", ["Dat de stad door een vloed zou vergaan", "Dat de stad door de Lamanieten zou worden ingenomen"], ["in één dag"]),
    q("b", "26", "Wat zegt de engel over de komst van de Zoon van God?", "Over niet vele dagen", ["Over vele honderden jaren", "Over meer dan duizend jaar"], ["niet vele dagen"]),
    q("c", "34", "Wie trad naar voren en begon eveneens tot de mensen te prediken?", "Amulek", ["Zeëzrom", "Antionah"], ["Amulek"]),
  ),
  ch("alma", 10,
    q("a", "2", "Wie was de vader van Amulek?", "Giddonah", ["Aminadi", "Ismaël"], ["Giddonah"]),
    q("b", "7", "Wie verscheen er aan Amulek op zijn reis?", "Een engel van de Heer", ["Een profeet uit Zarahemla", "Een dienstknecht van Alma"], ["engel van de Heer"]),
    q("c", "31", "Hoe heette de belangrijkste wetgeleerde die Amulek en Alma aanklaagde?", "Zeëzrom", ["Antionah", "Korihor"], ["Zeëzrom"]),
  ),
  ch("alma", 11,
    q("a", "3", "Wat ontving een rechter als loon voor een dag?", "Een senine goud", ["Een limna goud", "Een onti zilver"], ["senine goud"]),
    q("b", "21", "Wie begon Amulek te ondervragen?", "Zeëzrom", ["Antionah", "Gideon"], ["Zeëzrom"]),
    q("c", "38-39", "Wie is volgens Amulek waarlijk de eeuwige Vader van de hemel en de aarde?", "De Zoon van God", ["De profeet Alma", "De engel van de Heer"], ["Zoon van God"]),
  ),
  ch("alma", 12,
    q("a", "20", "Wie was Antionah?", "Een hoofdregeerder", ["Een wetgeleerde", "Een legeraanvoerder"], ["hoofdregeerder"]),
    q("b", "16", "Hoe noemt Alma de tweede dood?", "Een geestelijke dood", ["Een tijdelijke dood", "Een lichamelijke dood"], ["geestelijke dood"]),
    q("c", "21", "Wat stelde God volgens het schriftgedeelte ten oosten van de hof van Eden?", "Cherubs met een vlammend zwaard", ["Een muur met een poort van goud", "Een engel met een gouden sleutel"], ["cherubs"]),
  ),
  ch("alma", 13,
    q("a", "15", "Aan wie betaalde Abraham tiende?", "Aan Melchizedek", ["Aan koning Salomo", "Aan de profeet Mozes"], ["Melchizedek"]),
    q("b", "17", "Over welk land was Melchizedek koning?", "Over het land Salem", ["Over het land Moab", "Over het land Egypte"], ["land Salem"]),
    q("c", "9", "Hoe wordt de Zoon in vers 9 genoemd?", "De Eniggeborene van de Vader", ["De Eerstgeborene van de Vader", "De Gezalfde van de Vader"], ["Eniggeborene van de Vader"]),
  ),
  ch("alma", 14,
    q("a", "16", "Naar de orde en het geloof van wie was de opperrechter van Ammonihah?", "Van Nehor", ["Van Amlici", "Van Korihor"], ["Nehor"]),
    q("b", "18", "Hoeveel dagen zaten Alma en Amulek in de gevangenis voordat de wetgeleerden kwamen?", "Drie dagen", ["Zeven dagen", "Twee dagen"], ["drie dagen"]),
    q("c", "27", "Wat gebeurde er toen Alma en Amulek de Heer om bevrijding hadden aangeroepen?", "De aarde beefde hevig", ["Er brak een brand uit", "Het begon hevig te hagelen"], ["aarde beefde hevig"]),
  ),
  ch("alma", 15,
    q("a", "1", "Naar welk land gingen Alma en Amulek nadat zij uit Ammonihah waren vertrokken?", "Het land Sidom", ["Het land Melek", "Het land Nephi"], ["land Sidom"]),
    q("b", "3", "Waaraan leed Zeëzrom in Sidom?", "Een brandende koorts", ["Een zware verwonding", "Een ernstige blindheid"], ["brandende koorts"]),
    q("c", "12", "Wat deed Alma met Zeëzrom nadat hij was genezen?", "Hij doopte hem tot de Heer", ["Hij zond hem terug naar Ammonihah", "Hij liet hem de kerk verlaten"], ["doopte"]),
  ),
  ch("alma", 16,
    q("a", "5", "Hoe heette de opperbevelhebber van de legers van de Nephieten?", "Zoram", ["Moroni", "Gideon"], ["Zoram"]),
    q("b", "10", "Wat gebeurde er volgens Alma 16 met de stad Ammonihah?", "Ze werd in één dag woest achtergelaten", ["Ze werd geleidelijk door de Lamanieten bezet", "Ze werd door een aardbeving verzwolgen"], ["in één dag"]),
    q("c", "19", "Wat verkondigden de priesters over de Zoon van God?", "Zijn lijden en dood", ["Zijn rijkdom en macht", "Zijn huwelijk en gezin"], ["lijden en dood"]),
  ),
  ch("alma", 17,
    q("a", "4", "Hoeveel jaar hadden de zonen van Mosiah het woord onder de Lamanieten geleerd?", "Veertien jaar", ["Veertig jaar", "Zeven jaar"], ["veertien jaar"]),
    q("b", "21", "Hoe heette de koning van het land Ismaël?", "Lamoni", ["Limhi", "Laman"], ["Lamoni"]),
    q("c", "38", "Hoeveel mannen van de Lamanieten werden er met Ammons slinger neergeslagen?", "Zes mannen", ["Vier mannen", "Acht mannen"], ["zes"]),
  ),
  ch("alma", 18,
    q("a", "13", "Wat betekent het woord Rabbanah?", "Machtige of grote koning", ["Wijze en machtige heer", "Dappere legeraanvoerder"], ["grote koning"]),
    q("b", "43", "Hoe lang lag koning Lamoni als dood op zijn bed?", "Twee dagen en twee nachten", ["Drie dagen en drie nachten", "Eén dag en één nacht"], ["twee dagen en twee nachten"]),
    q("c", "9", "Wat deed Ammon toen de koning naar hem vroeg?", "Hij voederde de paarden van de koning", ["Hij vierde feest met de dienstknechten", "Hij sliep in de tent van de koning"], ["paarden"]),
  ),
  ch("alma", 19,
    q("a", "8", "Wat zei Ammon over koning Lamoni toen hij naar hem keek?", "Hij is niet dood, maar slaapt in God", ["Hij is gewond en moet rusten bij het vuur", "Hij is ziek en heeft een arts nodig"], ["slaapt in God"]),
    q("b", "13", "Wat zei Lamoni toen hij weer opstond?", "Dat hij zijn Verlosser had gezien", ["Dat hij een groot leger had gezien", "Dat hij zijn vader had gezien"], ["Verlosser"]),
    q("c", "28", "Wie had de menigte bijeen laten komen?", "Een Lamanitische dienstmaagd", ["Een dochter van de koning", "Een priester van het volk"], ["dienstmaagd"]),
  ),
  ch("alma", 20,
    q("a", "3", "In welk land zaten Ammons broeders in de gevangenis?", "Het land Middoni", ["Het land Ismaël", "Het land Sidom"], ["Middoni"]),
    q("b", "10", "Wat noemt de vader van Lamoni de Nephiet Ammon?", "Een van de kinderen van een leugenaar", ["Een van de zonen van een koning", "Een van de dienaren van de duivel"], ["kinderen van een leugenaar"]),
    q("c", "23", "Wat bood de oude koning Ammon aan als hij hem spaarde?", "De helft van het koninkrijk", ["Een derde van zijn schatten", "Zijn oudste dochter als vrouw"], ["helft van het koninkrijk"]),
  ),
  ch("alma", 21,
    q("a", "2", "Welke stad bouwden de Lamanieten, de Amalekieten en het volk van Amulon?", "Een grote stad die Jeruzalem heette", ["Een grote stad die Nephi heette", "Een grote stad die Zarahemla heette"], ["Jeruzalem"]),
    q("b", "14", "Door wie werden Aäron en zijn broeders uit de gevangenis bevrijd?", "Door Lamoni en Ammon", ["Door Mosiah en Alma", "Door Omner en Himni"], ["Lamoni", "Ammon"]),
    q("c", "22", "Wat verkondigde koning Lamoni zijn volk over het aanbidden van de Heer?", "Dat zij vrij waren de Heer te aanbidden waar zij wilden", ["Dat zij alleen in de synagogen mochten aanbidden", "Dat zij uitsluitend de koning mochten aanbidden"], ["aanbidden"]),
  ),
  ch("alma", 22,
    q("a", "3", "Wat beloofden Aäron en zijn broeders de koning in ruil voor hun leven?", "Dat zij zijn dienstknechten zouden zijn", ["Dat zij hem hun bezittingen zouden geven", "Dat zij het land zouden verlaten"], ["dienstknechten"]),
    q("b", "7", "Wat zeggen de Amalekieten volgens de koning over God?", "Dat er een God is", ["Dat er twee goden zijn", "Dat er geen God is"], ["een God"]),
    q("c", "17", "Wat deed de koning toen Aäron zijn woorden had gesproken?", "Hij knielde en wierp zich ter aarde", ["Hij stond op en verliet de zaal", "Hij riep zijn lijfwacht bijeen"], ["ter aarde"]),
  ),
  ch("alma", 23,
    q("a", "17", "Hoe noemden de bekeerde Lamanieten zich?", "Anti-Nephi-Lehieten", ["Nephi-Lamanieten", "Lehi-Nephieten"], ["Anti-Nephi-Lehieten"]),
    q("b", "1", "Wat gebood de koning van de Lamanieten zijn volk over Ammon en zijn broeders?", "Dat niemand de handen aan hen mocht slaan", ["Dat zij het land moesten verlaten", "Dat zij alleen in Ismaël mochten prediken"], ["handen"]),
    q("c", "14", "Welke groepen bekeerden zich niet?", "De Amalekieten en de Amulonieten", ["De Nephieten van Zarahemla", "Het volk van Ismaël en Middoni"], ["Amalekieten", "Amulonieten"]),
  ),
  ch("alma", 24,
    q("a", "3", "Welke naam gaf de koning aan zijn zoon aan wie hij het koninkrijk overdroeg?", "Anti-Nephi-Lehi", ["Anti-Lehi-Nephi", "Nephi-Anti-Lehi"], ["Anti-Nephi-Lehi"]),
    q("b", "16", "Wat zouden zij volgens de koning met hun zwaarden doen als hun broeders hen wilden vernietigen?", "Ze diep in de grond begraven", ["Ze omsmelten tot gereedschap", "Ze aan de Nephieten schenken"], ["diep in de grond"]),
    q("c", "22", "Hoeveel van hen werden zonder tegenstand door de Lamanieten gedood?", "Duizend en vijf", ["Duizend en tien", "Vijfhonderd en vijf"], ["duizend en vijf"]),
  ),
  ch("alma", 25,
    q("a", "11", "Wie was de eerste die de vuurdood onderging wegens zijn geloof in God?", "Abinadi", ["Amulek", "Gideon"], ["Abinadi"]),
    q("b", "14", "Wat deden de bekeerde Lamanieten met hun oorlogswapens?", "Ze begroeven hun wapens", ["Ze verkochten hun wapens", "Ze droegen hun wapens altijd bij zich"], ["begroeven"]),
    q("c", "16", "Waartoe diende de wet van Mozes voor hen?", "Om hun geloof in Christus te versterken", ["Om hun volk van de Nephieten te scheiden", "Om hun rijkdom in de tempel te bewaren"], ["geloof in Christus"]),
  ),
  ch("alma", 26,
    q("a", "4", "Wat zegt Ammon over duizenden van de Lamanieten?", "Dat zij in de kudde van God zijn gebracht", ["Dat zij de Nephieten zijn gaan dienen", "Dat zij hun koning hebben verdreven"], ["kudde van God"]),
    q("b", "22", "Wat wordt volgens Ammon gegeven aan wie zich bekeert, geloof oefent en voortdurend bidt?", "De verborgenheden van God", ["Een plaats naast de koning", "Rijkdom en macht in het land"], ["verborgenheden"]),
    q("c", "12", "Waarin zegt Ammon te zullen roemen?", "In de Heer, zijn God", ["In zijn eigen kracht", "In zijn eigen wijsheid"], ["God"]),
  ),
  ch("alma", 27,
    q("a", "22", "Welk land stond het volk van Nephi af aan het volk van Ammon?", "Het land Jershon", ["Het land Gideon", "Het land Melek"], ["Jershon"]),
    q("b", "12", "Waarom gebood de Heer Ammon het volk uit het land te voeren?", "Opdat zij niet zouden omkomen", ["Opdat zij meer land konden bezitten", "Opdat zij de Nephieten konden aanvallen"], ["omkomen"]),
    q("c", "30", "Hoe wordt het volk van Ammon in vers 30 genoemd?", "Een naarstig en geliefd volk", ["Een strijdlustig en gevreesd volk", "Een rijk en machtig volk"], ["naarstig en geliefd volk"]),
  ),
  ch("alma", 28,
    q("a", "7", "Welk regeringsjaar van de rechters eindigde na de verschrikkelijke strijd?", "Het vijftiende regeringsjaar", ["Het twaalfde regeringsjaar", "Het twintigste regeringsjaar"], ["vijftiende"]),
    q("b", "6", "Hoe wordt de dag van de verschrikkelijke strijd beschreven?", "Een droevige dag", ["Een feestelijke dag", "Een rustige dag"], ["droevige dag"]),
    q("c", "12", "Wat doen vele duizenden die rouwen om het verlies van hun verwanten toch?", "Zij verheugen zich en jubelen in de hoop", ["Zij vluchten het land uit en verbergen zich", "Zij verzamelen hun legers voor wraak"], ["jubelen in de hoop"]),
  ),
  ch("alma", 29,
    q("a", "1", "Wat zou Alma willen zijn om de bazuin van God te kunnen laten klinken?", "Een engel", ["Een koning", "Een profeet"], ["engel"]),
    q("b", "1", "Waarmee zou Alma dan willen spreken?", "Met de bazuin van God", ["Met de harp van David", "Met de stem van de koning"], ["bazuin van God"]),
    q("c", "8", "Aan wie geeft de Heer mensen van hun eigen natie en taal om zijn woord te verkondigen?", "Aan alle natiën op aarde", ["Aan de Nephieten alleen", "Aan de Joden alleen"], ["alle natiën"]),
  ),
  ch("alma", 30,
    q("a", "12", "Hoe heette de antichrist die tot het volk predikte dat er geen Christus zou zijn?", "Korihor", ["Nehor", "Amlici"], ["Korihor"]),
    q("b", "50", "Wat gebeurde er met Korihor nadat Alma had gesproken?", "Hij werd met stomheid geslagen", ["Hij werd met blindheid geslagen", "Hij werd door het volk gestenigd"], ["stomheid"]),
    q("c", "23", "Hoe heette de hogepriester in het land Gideon?", "Giddonah", ["Nephihah", "Helaman"], ["Giddonah"]),
  ),
  ch("alma", 31,
    q("a", "21", "Wat betekent de naam Rameümptom?", "De heilige staanplaats", ["De hoge toren van God", "De plaats van de uitverkorenen"], ["heilige staanplaats"]),
    q("b", "3", "Hoe noemden de Zoramieten het land waar zij zich verzamelden?", "Antionum", ["Gideon", "Jershon"], ["Antionum"]),
    q("c", "7", "Wie was de oudste zoon van Alma, die hij niet met zich meenam naar de Zoramieten?", "Helaman", ["Shiblon", "Corianton"], ["Helaman"]),
  ),
  ch("alma", 32,
    q("a", "28", "Waarmee vergelijkt Alma het woord?", "Met een zaadje", ["Met een rivier", "Met een vuur"], ["zaadje"]),
    q("b", "21", "Wat is geloof volgens Alma niet?", "Volmaakte kennis van dingen", ["Hopen op onzichtbare dingen", "Vertrouwen op een goed zaadje"], ["volmaakte kennis"]),
    q("c", "10", "Waar kan men God volgens Alma aanbidden?", "Overal, niet alleen in de synagogen", ["Alleen in de synagogen op sabbat", "Alleen in de tempel van de koning"], ["synagogen"]),
  ),
  ch("alma", 33,
    q("a", "3", "Welke profeet vanouds wordt aangehaald aangaande gebed en aanbidding?", "Zenos", ["Jesaja", "Jeremia"], ["Zenos"]),
    q("b", "15", "Welke tweede profeet vanouds sprak ook over de Zoon van God?", "Zenock", ["Ezias", "Jarom"], ["Zenock"]),
    q("c", "19", "Wat werd er in de wildernis opgeheven, opdat wie ernaar keek zou leven?", "Een zinnebeeld", ["Een altaar van steen", "Een grote tent"], ["zinnebeeld"]),
  ),
  ch("alma", 34,
    q("a", "10", "Wat voor offer moet er volgens Amulek komen?", "Een groot en laatste offer", ["Een dagelijks offer van graan", "Een jaarlijks offer van schapen"], ["groot en laatste offer"]),
    q("b", "21", "Wanneer moet men de Heer volgens Amulek in zijn huis aanroepen?", "'s Ochtends, 's middags en 's avonds", ["Eén keer per week in de synagoge", "Alleen als er nood is in het land"], ["ochtends", "avonds"]),
    q("c", "32", "Waarvoor is dit leven volgens Amulek de tijd?", "Om zich voor te bereiden God te ontmoeten", ["Om rijkdom en eer te verwerven", "Om een koninkrijk op aarde te bouwen"], ["God te ontmoeten"]),
  ),
  ch("alma", 35,
    q("a", "1", "Naar welk land staken Alma en Amulek over na hun prediking bij de Zoramieten?", "Het land Jershon", ["Het land Melek", "Het land Gideon"], ["Jershon"]),
    q("b", "13", "Waarheen vertrok het volk van Ammon uit Jershon?", "Naar het land Melek", ["Naar het land Nephi", "Naar het land Sidom"], ["land Melek"]),
    q("c", "12", "Welk regeringsjaar van de rechters eindigde in dit hoofdstuk?", "Het zeventiende", ["Het zestiende", "Het achttiende"], ["zeventiende"]),
  ),
  ch("alma", 36,
    q("a", "10", "Hoe lang kon Alma zijn mond niet opendoen na de verschijning van de engel?", "Drie dagen en drie nachten", ["Twee dagen en twee nachten", "Zeven dagen en zeven nachten"], ["drie dagen en drie nachten"]),
    q("b", "18", "Welke woorden riep Alma in zijn hart?", "O Jezus, Zoon van God, wees barmhartig", ["O Heer, red mij van mijn vijanden", "O God, neem mijn leven van mij"], ["Jezus, Zoon van God"]),
    q("c", "22", "Met het visioen van wie vergelijkt Alma wat hij zag, God op zijn troon?", "Met dat van Lehi", ["Met dat van Nephi", "Met dat van Mosiah"], ["Lehi"]),
  ),
  ch("alma", 37,
    q("a", "6", "Wat wordt volgens Alma door kleine en eenvoudige dingen teweeggebracht?", "Grote dingen", ["Kleine dingen", "Nutteloze dingen"], ["grote dingen"]),
    q("b", "21", "Over hoeveel platen sprak Alma die Helaman moest bewaren?", "Vierentwintig platen", ["Tweeëntwintig platen", "Zesentwintig platen"], ["vierentwintig"]),
    q("c", "26", "Wat gebeurde er met hen die zich niet bekeerden?", "Ze zijn vernietigd", ["Ze zijn verbannen", "Ze zijn verstrooid"], ["vernietigd"]),
  ),
  ch("alma", 38,
    q("a", "4", "Waarom werd Shiblon volgens Alma gestenigd?", "Omwille van het woord", ["Omwille van zijn rijkdom", "Omwille van zijn leger"], ["omwille van het woord"]),
    q("b", "13", "Waarom bidden de Zoramieten volgens Alma?", "Om door de mensen te worden gehoord", ["Om door God te worden gezegend", "Om hun zonden voor God te belijden"], ["door de mensen te worden gehoord"]),
    q("c", "11", "Waarop moet Shiblon volgens Alma niet roemen?", "Op zijn eigen wijsheid", ["Op de genade van God", "Op de steun van zijn broers"], ["wijsheid"]),
  ),
  ch("alma", 39,
    q("a", "10", "Met wie moest Corianton volgens Alma bij al zijn ondernemingen beraadslagen?", "Met zijn oudere broers", ["Met de koning van het land", "Met de leraren van de Zoramieten"], ["oudere broers"]),
    q("b", "14", "Waarom moet Corianton volgens Alma geen rijkdom nastreven?", "Omdat hij die niet kan meenemen", ["Omdat de Lamanieten hem die ontnemen", "Omdat rijkdom alleen voor de rechters is"], ["meenemen"]),
    q("c", "18", "Aan wie moet het verlossingsplan volgens Alma worden bekendgemaakt?", "Aan dit volk én aan hun kinderen", ["Alleen aan de priesters van de kerk", "Alleen aan de rechters van het land"], ["dit volk"]),
  ),
  ch("alma", 40,
    q("a", "12", "Hoe wordt de staat van geluk van de rechtvaardigen tussen dood en opstanding genoemd?", "De staat van het paradijs", ["De staat van het koninkrijk", "De staat van de hof van Eden"], ["paradijs"]),
    q("b", "14", "Waarin verkeert de ziel van de goddelozen volgens vers 14?", "In duisternis en angstig uitzicht", ["In rust en vrede van het hart", "In slaap tot de opstanding"], ["duisternis", "angstig"]),
    q("c", "23", "Wat zal er volgens Alma bij de herstelling met de ziel gebeuren?", "De ziel wordt tot het lichaam hersteld", ["De ziel blijft voor eeuwig gescheiden", "Het lichaam wordt aan de aarde gegeven"], ["tot het lichaam"]),
  ),
  ch("alma", 41,
    q("a", "13", "Wat betekent het woord herstelling volgens Alma?", "Kwaad wederom voor kwaad terugkrijgen", ["Iemand uit zonde naar geluk brengen", "Alle dingen opnieuw schenken zonder oordeel"], ["kwaad wederom voor kwaad"]),
    q("b", "10", "Wat heeft volgens Alma nooit geluk betekend?", "Goddeloosheid", ["Hardwerken", "Gehoorzaamheid"], ["goddeloosheid"]),
    q("c", "14", "Wat moet Corianton volgens Alma voortdurend doen?", "Voortdurend goed doen", ["Voortdurend wraak nemen", "Voortdurend rijkdom zoeken"], ["voortdurend goed"]),
  ),
  ch("alma", 42,
    q("a", "4", "Wat werd de mens volgens Alma vergund?", "Een proeftijd om zich te bekeren", ["Een tijd van rust zonder wet", "Een eeuwig verblijf in de hof van Eden"], ["proeftijd"]),
    q("b", "22-23", "Op wie maakt de barmhartigheid volgens Alma aanspraak?", "Op de boetvaardigen die zich bekeren", ["Op de machtigen die over het land regeren", "Op de rijken die veel offers brengen"], ["boetvaardigen"]),
    q("c", "27", "Wie mag volgens Alma komen en nemen van de wateren des levens?", "Eenieder die wil komen", ["Alleen de priesters van de kerk", "Alleen wie rijk genoeg is"], ["wil komen"]),
  ),
  ch("alma", 43,
    q("a", "17", "Hoe oud was Moroni toen hij opperbevelhebber werd?", "Vijfentwintig jaar", ["Vijfendertig jaar", "Vijfenveertig jaar"], ["vijfentwintig"]),
    q("b", "19", "Waarmee had Moroni zijn volk uitgerust?", "Met borstplaten en armschilden", ["Met strijdwagens en paarden", "Met helmen en lange speren"], ["borstplaten", "armschilden"]),
    q("c", "44", "Hoe heette de opperbevelhebber van de Lamanieten?", "Zerahemnah", ["Amalickiah", "Zemnarihah"], ["Zerahemnah"]),
  ),
  ch("alma", 44,
    q("a", "6", "Wat gebood Moroni aan Zerahemnah?", "Zijn oorlogswapens over te dragen", ["Zijn leger naar huis te sturen", "Zijn koninkrijk aan Moroni af te staan"], ["oorlogswapens"]),
    q("b", "20", "Wat deed Moroni met de Lamanieten nadat hij het werk van de dood had laten ophouden?", "Hij ontnam hun de oorlogswapens", ["Hij liet hen hun wapens houden", "Hij gaf hun voedsel en kleding"], ["oorlogswapens"]),
    q("c", "24", "Welk regeringsjaar van de rechters eindigde met de kroniek van Alma?", "Het achttiende", ["Het zeventiende", "Het negentiende"], ["achttiende"]),
  ),
  ch("alma", 45,
    q("a", "4", "In wie vroeg Alma zijn zoon Helaman te geloven, die komen zal?", "In Jezus Christus", ["In koning Benjamin", "In de profeet Mozes"], ["Jezus Christus"]),
    q("b", "10", "Hoeveel jaar na de verschijning van Christus zou het volk van Nephi volgens Alma in ongeloof vervallen?", "Vierhonderd jaar", ["Tweehonderd jaar", "Zeshonderd jaar"], ["vierhonderd jaar"]),
    q("c", "18", "Wat gebeurde er met Alma nadat hij Zarahemla had verlaten?", "Men hoorde nooit meer iets van hem", ["Hij stierf kort daarna in Melek", "Hij werd door de Lamanieten gevangen"], ["nooit meer"]),
  ),
  ch("alma", 46,
    q("a", "3", "Hoe heette de leider van hen die zich van de kerk afscheidden?", "Amalickiah", ["Zerahemnah", "Lehonti"], ["Amalickiah"]),
    q("b", "12", "Waarop schreef Moroni het opschrift 'Ter gedachtenis aan onze God'?", "Op een stuk van zijn mantel", ["Op een plaat van koper", "Op een muur van de tempel"], ["mantel"]),
    q("c", "36", "Wat liet Moroni op iedere toren in het land van de Nephieten hijsen?", "Het vrijheidsvaandel", ["Een witte vredesvlag", "De koninklijke standaard"], ["vrijheidsvaandel"]),
  ),
  ch("alma", 47,
    q("a", "7", "Hoe heette de berg waarop de Lamanieten zich verzamelden?", "De berg Antipas", ["De berg Manti", "De berg Onidah"], ["Antipas"]),
    q("b", "11", "Hoe heette de leider van hen die zich op de berg bevonden?", "Lehonti", ["Lamoni", "Zerahemnah"], ["Lehonti"]),
    q("c", "18", "Wat liet Amalickiah doen om Lehonti uit de weg te ruimen?", "Hem geleidelijk vergif laten toedienen", ["Hem door het zwaard laten doden", "Hem gevangen laten zetten in Nephi"], ["vergif"]),
  ),
  ch("alma", 48,
    q("a", "5", "Uit wie stelde Amalickiah opperbevelhebbers aan?", "Uit de Zoramieten", ["Uit de Amlicieten", "Uit de Nephieten"], ["Zoramieten"]),
    q("b", "11", "Wat voor man was Moroni volgens vers 11?", "Een man die geen behagen schepte in bloedvergieten", ["Een man die graag oorlog voerde om te winnen", "Een man die liever macht dan vrede zocht"], ["bloedvergieten"]),
    q("c", "21", "Wanneer werden de Nephieten gedwongen tegen hun zin te strijden?", "Tegen het eind van het negentiende jaar", ["Tegen het eind van het tiende jaar", "Tegen het begin van het twintigste jaar"], ["negentiende"]),
  ),
  ch("alma", 49,
    q("a", "3", "Welke stad was herbouwd toen de Lamanieten daar opnieuw tegenaan liepen?", "Ammonihah", ["Nephihah", "Zarahemla"], ["Ammonihah"]),
    q("b", "4", "Waarmee hadden de Nephieten zich omgeven?", "Een wal van aarde", ["Een muur van steen", "Een gracht vol water"], ["wal van aarde"]),
    q("c", "24", "Hoeveel Nephieten raakten er bij de ingang ongeveer gewond?", "Ongeveer vijftig", ["Ongeveer honderd", "Ongeveer tweehonderd"], ["vijftig"]),
  ),
  ch("alma", 50,
    q("a", "13", "Hoe noemden de Nephieten de stad die zij bij de oostelijke zee begonnen te stichten?", "De stad Moroni", ["De stad Lehi", "De stad Aäron"], ["stad Moroni"]),
    q("b", "2", "Wat liet Moroni bovenop de wallen van aarde om de steden heen zetten?", "Muren van stammen tot op manshoogte", ["Muren van baksteen met wachttorens", "Een brede gracht met scherpe palen"], ["stammen"]),
    q("c", "40", "Hoe heette de zoon van Nephihah die zijn vader opvolgde als opperrechter?", "Pahoran", ["Helaman", "Moronihah"], ["Pahoran"]),
  ),
  ch("alma", 51,
    q("a", "5", "Hoe werden zij genoemd die wilden dat Pahoran van de rechterstoel werd ontheven?", "Koningsgezinden", ["Rechtsgezinden", "Wetsverdedigers"], ["koningsgezinden"]),
    q("b", "34", "Wie stak koning Amalickiah een speer in het hart?", "Teancum", ["Moroni", "Helaman"], ["Teancum"]),
    q("c", "19", "Hoeveel van de afgescheidenen werden er door het zwaard neergehouwen?", "Vierduizend", ["Tweeduizend", "Zesduizend"], ["vierduizend"]),
  ),
  ch("alma", 52,
    q("a", "3", "Hoe heette de broer van Amalickiah die koning werd?", "Ammoron", ["Amulon", "Ammon"], ["Ammoron"]),
    q("b", "16", "Welke stad moest Teancum op bevel van Moroni aanvallen en zo mogelijk heroveren?", "De stad Mulek", ["De stad Gid", "De stad Nephihah"], ["Mulek"]),
    q("c", "33", "Wie was de leider van de Lamanieten met een onoverwinnelijke geest?", "Jakob, een Zoramiet", ["Lehonti, een Lamaniet", "Ammoron, een Amalekiet"], ["Jakob"]),
  ),
  ch("alma", 53,
    q("a", "18", "Hoeveel jongelingen gingen het verbond aan en namen hun oorlogswapens op?", "Tweeduizend", ["Duizend", "Vierduizend"], ["tweeduizend"]),
    q("b", "1", "Wat moesten de gevangen Lamanieten doen?", "Hun doden begraven", ["Een tempel bouwen", "Het land bewerken"], ["doden"]),
    q("c", "21", "Wat was de jonge soldaten volgens vers 21 geleerd?", "De geboden van God te onderhouden", ["De wapens van de vijand te gebruiken", "De wet van de koning te volgen"], ["geboden van God te onderhouden"]),
  ),
  ch("alma", 54,
    q("a", "20", "Waarover wilde Moroni volgens deze brieven met Ammoron onderhandelen?", "Over een uitwisseling van gevangenen", ["Over een vredesverdrag zonder voorwaarden", "Over de overgave van de stad Gid"], ["gevangenen"]),
    q("b", "16", "Wiens broer was Ammoron, de koning van de Lamanieten?", "Die van Amalickiah", ["Die van Zerahemnah", "Die van Lehonti"], ["Amalickiah"]),
    q("c", "23", "Van wie zei Ammoron een afstammeling te zijn?", "Van Zoram", ["Van Nephi", "Van Laman"], ["Zoram"]),
  ),
  ch("alma", 55,
    q("a", "5", "Hoe heette de man die Moroni uitkoos om de wachten van de gevangenen te misleiden?", "Laman", ["Lamoni", "Lemuel"], ["Laman"]),
    q("b", "7", "In welke stad werden de gevangen Nephieten bewaakt?", "In de stad Gid", ["In de stad Mulek", "In de stad Cumeni"], ["stad Gid"]),
    q("c", "13", "Waarmee brachten Laman en zijn mannen de Lamanitische wachten in slaap?", "Met overvloedige wijn", ["Met een zwaar maal", "Met zoete vruchten"], ["wijn"]),
  ),
  ch("alma", 56,
    q("a", "10", "Wie was de aanvoerder van het leger waarbij Helaman zijn jonge soldaten voegde?", "Antipus", ["Teancum", "Pahoran"], ["Antipus"]),
    q("b", "47", "Waaraan hechtten de jonge soldaten meer belang dan aan hun leven?", "De vrijheid van hun vaders", ["De rijkdom van hun moeders", "De roem van hun koning"], ["vrijheid van hun vaders"]),
    q("c", "56", "Hoeveel van Helamans jonge soldaten waren er na het gevecht ter aarde gevallen?", "Er was niet één ziel gevallen", ["Er waren er twee gevallen", "Er waren er vijftig gevallen"], ["niet één ziel"]),
  ),
  ch("alma", 57,
    q("a", "19", "Uit hoeveel jonge soldaten bestond Helamans kleine groep?", "Tweeduizend zestig", ["Tweeduizend zeventig", "Tweeduizend zestien"], ["tweeduizend zestig"]),
    q("b", "25", "Hoeveel van de jonge soldaten waren wegens bloedverlies bezwijmd?", "Tweehonderd", ["Driehonderd", "Vierhonderd"], ["tweehonderd"]),
    q("c", "29", "Wie voerde het bevel over de groep die de gevangenen begeleidde?", "Een man met de naam Gid", ["Een man met de naam Antipus", "Een man met de naam Lehi"], ["Gid"]),
  ),
  ch("alma", 58,
    q("a", "1", "Welke stad was het volgende doel van Helaman en zijn leger?", "De stad Manti", ["De stad Gid", "De stad Zeëzrom"], ["Manti"]),
    q("b", "8", "Hoeveel man kwamen Helaman met voedsel te hulp?", "Tweeduizend man", ["Zesduizend man", "Duizend man"], ["tweeduizend"]),
    q("c", "28", "Hoe namen Helaman en zijn leger de stad Manti in bezit?", "Door een krijgslist, zonder bloedvergieten", ["Door een lange belegering met honger", "Door een directe aanval met wapens"], ["zonder bloedvergieten"]),
  ),
  ch("alma", 59,
    q("a", "3", "Aan wie zond Moroni een brief om manschappen bijeen te laten brengen?", "Aan Pahoran", ["Aan Helaman", "Aan Teancum"], ["Pahoran"]),
    q("b", "8", "Welke stad ging er verloren aan de Lamanieten, waardoor het volk moest vluchten?", "De stad Nephihah", ["De stad Mulek", "De stad Cumeni"], ["Nephihah"]),
    q("c", "13", "Op wie was Moroni vertoornd wegens haar onverschilligheid voor de vrijheid van het land?", "Op de regering", ["Op de Lamanieten", "Op zijn eigen leger"], ["regering"]),
  ),
  ch("alma", 60,
    q("a", "1", "Aan wie schreef Moroni zijn brief?", "Aan de regeerder Pahoran", ["Aan de koning van de Lamanieten", "Aan Helaman, de hogepriester"], ["Pahoran"]),
    q("b", "36", "Wat zegt Moroni over zijn streven in zijn brief?", "Niet naar macht, maar het neerhalen ervan", ["Naar macht en gezag in het hele land", "Naar eer en roem op het slagveld"], ["niet naar macht"]),
    q("c", "3", "Wie leed samen met Moroni en zijn manschappen een buitengewoon groot lijden?", "Helaman en zijn manschappen", ["Teancum en zijn manschappen", "Pahoran en zijn manschappen"], ["Helaman"]),
  ),
  ch("alma", 61,
    q("a", "5", "Naar welk land vluchtte Pahoran toen hij van de rechterstoel werd verdreven?", "Naar het land Gideon", ["Naar het land Melek", "Naar het land Jershon"], ["land Gideon"]),
    q("b", "8", "Wat hadden de opstandelingen in Zarahemla gedaan?", "Ze hadden een koning over zich uitgeroepen", ["Ze hadden de tempel in brand gestoken", "Ze hadden alle rechters afgezet en verbannen"], ["koning over zich uitgeroepen"]),
    q("c", "9", "Waarover verheugde Pahoran zich in zijn antwoord aan Moroni?", "De grootheid van het hart van Moroni", ["De overwinning op de Lamanieten", "De steun van de koningsgezinden"], ["grootheid van"]),
  ),
  ch("alma", 62,
    q("a", "8", "Wat gebeurde er met Pachus en met Pahoran toen Zarahemla was heroverd?", "Pachus werd gedood, Pahoran hersteld", ["Pahoran werd gedood, Pachus hersteld", "Moroni werd gedood, Pahoran bleef weg"], ["Pachus"]),
    q("b", "43", "Aan wie droeg Moroni het bevel over zijn legers over?", "Aan zijn zoon Moronihah", ["Aan zijn zoon Helaman", "Aan Lehi en Teancum"], ["Moronihah"]),
    q("c", "36-37", "Wie van Moroni's bevelhebbers werd in het kamp van de Lamanieten gedood?", "Teancum", ["Pahoran", "Moronihah"], ["Teancum"]),
  ),
  ch("alma", 63,
    q("a", "1", "Wie nam in het zesendertigste jaar bezit van de heilige dingen?", "Shiblon", ["Helaman", "Corianton"], ["Shiblon"]),
    q("b", "5", "Hoe heette de man die een buitengewoon groot schip bouwde?", "Hagoth", ["Morianton", "Teomner"], ["Hagoth"]),
    q("c", "8", "Wat gebeurde er met hen die zich inscheepten en uitvoeren?", "Er werd nooit meer iets van hen gehoord", ["Zij vestigden zich in het noordelijke land", "Zij keerden na een jaar terug naar huis"], ["nooit meer iets van hen"]),
  ),
  // ===== EINDE =====
];
