import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Alma (édition française). Chaque fait est lié aux versets indiqués dans `verses` ; `npm run genees:check` le vérifie.
export const alma: GeneesChapterSeed[] = [
  ch("alma", 1,
    q("a", "15", "Comment s’appelait l’homme qui tua Gédéon ?", "Néhor", ["Amulon", "Zoram"], ["Néhor"]),
    q("b", "15", "Où Néhor fut-il mis à mort ?", "Sur le sommet de la colline de Manti", ["Sur la rive du fleuve Sidon", "Sur la place du marché de Zarahemla"], ["colline de Manti"]),
    q("c", "12", "Qu’est-ce qui fut introduit pour la première fois parmi le peuple selon Alma ?", "Les intrigues de prêtres", ["La possession d’esclaves", "La construction d’un temple"], ["intrigues de prêtres"]),
  ),
  ch("alma", 2,
    q("a", "1", "Comment s’appelait l’homme qui voulait devenir roi sur le peuple ?", "Amlici", ["Néhor", "Korihor"], ["Amlici"]),
    q("b", "31", "Comment Alma tua-t-il le chef des Amlicites ?", "Avec son épée", ["Avec une lance", "Avec une flèche"], ["épée"]),
    q("c", "15", "Sur quelle colline à l’est du Sidon les Amlicites montèrent-ils ?", "La colline Amnihu", ["La colline de Manti", "La colline de Riplah"], ["colline Amnihu"]),
  ),
  ch("alma", 3,
    q("a", "4", "De quoi les Amlicites s’étaient-ils marqué le front ?", "Avec de la peinture rouge", ["Avec de la peinture bleue", "Avec de la peinture blanche"], ["rouge"]),
    q("b", "26", "Combien d’âmes furent envoyées dans le monde éternel en cette seule année ?", "Des milliers et des dizaines de milliers", ["Des centaines et des milliers d’âmes", "Seulement quelques centaines d’âmes"], ["milliers et des dizaines de milliers"]),
    q("c", "22", "Pourquoi Alma ne monta-t-il pas lui-même au combat cette fois-là contre les Lamanites ?", "Parce qu’il était affligé d’une blessure", ["Parce qu’il n’avait pas confiance dans l’armée", "Parce qu’il avait un autre plan"], ["blessure"]),
  ),
  ch("alma", 4,
    q("a", "5", "Combien d’âmes s’unirent à l’Église la septième année ?", "Environ trois mille cinq cents", ["Environ deux mille cinq cents", "Environ cinq mille trois cents"], ["trois mille cinq cents"]),
    q("b", "17", "Qui fut désigné comme grand juge quand Alma remit le siège du jugement ?", "Néphihah", ["Giddonah", "Hélaman"], ["Néphihah"]),
    q("c", "18", "Quel office Alma conserva-t-il pour lui-même ?", "Celui de grand prêtre", ["Celui de chef de l’armée", "Celui de grand juge"], ["grand prêtre"]),
  ),
  ch("alma", 5,
    q("a", "38", "Quel nom porte le bon Berger qui nous appelle ?", "Le nom du Christ", ["Le nom de Mormon", "Le nom d’Abinadi"], ["nom du Christ"]),
    q("b", "3", "Par qui Alma avait-il été consacré grand prêtre de l’Église de Dieu ?", "Par son père Alma", ["Par le roi Mosiah", "Par le roi Limhi"], ["père Alma"]),
    q("c", "52", "Qu’est-ce qui est mis à la racine de l’arbre selon l’Esprit ?", "La cognée", ["La scie", "La bêche"], ["cognée"]),
  ),
  ch("alma", 6,
    q("a", "8", "Dans quelle vallée Alma commença-t-il ensuite à annoncer la parole de Dieu ?", "La vallée de Gédéon", ["La vallée de Lémuel", "La vallée d’Hélam"], ["vallée de Gédéon"]),
    q("b", "2", "Qu’arriva-t-il à ceux qui n’appartenaient pas à l’Église et se repentaient de leurs péchés ?", "Ils furent baptisés au repentir", ["Ils furent envoyés à Zarahemla", "Ils devaient d’abord attendre un an"], ["baptisés au repentir"]),
    q("c", "6", "Pourquoi était-il commandé aux enfants de Dieu de se réunir souvent ?", "Pour jeûner et prier avec ferveur", ["Pour offrir des sacrifices", "Pour bâtir des temples ensemble"], ["jeûn"]),
  ),
  ch("alma", 7,
    q("a", "10", "Où le Seigneur naîtra-t-il selon Alma ?", "À Jérusalem", ["À Nazareth", "À Zarahemla"], ["Jérusalem"]),
    q("b", "10", "Comment Alma appelle-t-il la mère du Seigneur ?", "Une vierge, un vase précieux et élu", ["Une princesse, une femme riche et puissante", "Une reine, un vase riche et noble"], ["vase précieux et élu"]),
    q("c", "24", "Quelles trois choses faut-il avoir selon Alma ?", "La foi, l’espérance et la charité", ["La foi, le repentir et les sacrifices", "La connaissance, la sagesse et le pouvoir"], ["foi, l’espérance et la charité"]),
  ),
  ch("alma", 8,
    q("a", "3", "Dans quel pays Alma se rendit-il au début de la dixième année du règne des juges ?", "Au pays de Mélek", ["Au pays de Gédéon", "Au pays de Jershon"], ["pays de Mélek"]),
    q("b", "6", "Comment s’appelait la ville où Alma arriva après trois jours de voyage au nord de Mélek ?", "Ammonihah", ["Zarahemla", "Jershon"], ["Ammonihah"]),
    q("c", "21", "Comment s’appelait l’homme qui reçut Alma dans sa maison ?", "Amulek", ["Amulon", "Amaléki"], ["Amulek"]),
  ),
  ch("alma", 9,
    q("a", "4", "Que dirent les habitants d’Ammonihah qu’ils ne croiraient pas même si Alma le prophétisait ?", "Que la ville serait détruite en un seul jour", ["Que la ville périrait dans un déluge", "Que la ville serait prise par les Lamanites"], ["un seul jour"]),
    q("b", "26", "Quand le Fils de Dieu viendra-t-il dans sa gloire selon l’ange ?", "Il ne se passera pas beaucoup de jours", ["Dans plusieurs centaines d’années", "Dans bien plus de mille ans"], ["beaucoup de jours"]),
    q("c", "34", "Qui s’avança et commença aussi à prêcher au peuple ?", "Amulek", ["Zeezrom", "Gédéon"], ["Amulek"]),
  ),
  ch("alma", 10,
    q("a", "2", "Qui était le père d’Amulek ?", "Giddonah", ["Aminadi", "Ismaël"], ["Giddonah"]),
    q("b", "7", "Qui apparut à Amulek pendant son voyage ?", "Un ange du Seigneur", ["Un prophète de Mélek", "Un serviteur d’Alma"], ["ange du Seigneur"]),
    q("c", "31", "Comment s’appelait le principal des hommes de loi qui accusa Amulek et Alma ?", "Zeezrom", ["Korihor", "Gédéon"], ["Zeezrom"]),
  ),
  ch("alma", 11,
    q("a", "3", "Que recevait un juge comme salaire pour un jour ?", "Une sénine d’or", ["Un limna d’or", "Un onti d’argent"], ["sénine d’or"]),
    q("b", "21", "Qui commença à interroger Amulek ?", "Zeezrom", ["Gédéon", "Korihor"], ["Zeezrom"]),
    q("c", "38-39", "Qui est selon Amulek le Père éternel même du ciel et de la terre ?", "Le Fils de Dieu", ["Le prophète Alma", "L’ange du Seigneur"], ["Fils de Dieu"]),
  ),
  ch("alma", 12,
    q("a", "20", "Qui était Antionah ?", "Un de leurs principaux dirigeants", ["Un homme de loi très expérimenté", "Un chef de l’armée des Néphites"], ["principaux dirigeants"]),
    q("b", "16", "Comment Alma appelle-t-il la seconde mort ?", "Une mort spirituelle", ["Une mort temporelle", "Une mort corporelle"], ["mort spirituelle"]),
    q("c", "21", "Que plaça Dieu à l’est du jardin d’Éden selon l’Écriture ?", "Des chérubins et une épée flamboyante", ["Un mur avec une grande porte d’or", "Un ange avec une clé en or massif"], ["chérubins"]),
  ),
  ch("alma", 13,
    q("a", "15", "À qui Abraham paya-t-il la dîme ?", "À Melchisédek", ["Au roi Salomon", "Au prophète Élie"], ["Melchisédek"]),
    q("b", "17", "De quel pays Melchisédek était-il roi ?", "Du pays de Salem", ["Du pays de Moab", "Du pays d’Égypte"], ["pays de Salem"]),
    q("c", "9", "Comment le Fils est-il appelé au verset 9 ?", "Le Fils unique du Père", ["Le premier-né du Père", "L’oint du Père"], ["Fils unique du Père"]),
  ),
  ch("alma", 14,
    q("a", "16", "À l’ordre et à la doctrine de qui le grand juge d’Ammonihah appartenait-il ?", "De Néhor", ["D’Amlici", "De Korihor"], ["Néhor"]),
    q("b", "18", "Combien de jours Alma et Amulek restèrent-ils en prison avant que les docteurs de la loi viennent ?", "Trois jours", ["Sept jours", "Deux jours"], ["trois jours"]),
    q("c", "27", "Que se passa-t-il quand Alma et Amulek eurent invoqué le Seigneur pour être délivrés ?", "La terre trembla violemment et les murs s’effondrèrent", ["Un grand incendie éclata et ravagea la ville entière", "Une violente grêle se mit à tomber sur toute la prison"], ["terre trembla violemment"]),
  ),
  ch("alma", 15,
    q("a", "1", "Dans quel pays Alma et Amulek allèrent-ils après avoir quitté Ammonihah ?", "Au pays de Sidom", ["Au pays de Mélek", "Au pays de Néphi"], ["pays de Sidom"]),
    q("b", "3", "De quoi Zeezrom souffrait-il à Sidom ?", "D’une fièvre ardente", ["D’une grave blessure", "D’une cécité sévère"], ["fièvre ardente"]),
    q("c", "12", "Que fit Alma de Zeezrom après sa guérison ?", "Il le baptisa pour le Seigneur", ["Il le renvoya à Ammonihah", "Il lui fit quitter l’Église"], ["baptisa"]),
  ),
  ch("alma", 16,
    q("a", "5", "Comment s’appelait le capitaine en chef des armées des Néphites ?", "Zoram", ["Moroni", "Gédéon"], ["Zoram"]),
    q("b", "10", "Que devint la ville d’Ammonihah ?", "En un seul jour, elle fut laissée désolée", ["Elle fut peu à peu occupée par les Lamanites", "Elle fut engloutie par un tremblement de terre"], ["en un seul jour"]),
    q("c", "19", "Que prêchaient les prêtres au sujet du Fils de Dieu ?", "Ses souffrances et sa mort", ["Ses richesses et sa puissance", "Son mariage et sa famille"], ["souffrances et sa mort"]),
  ),
  ch("alma", 17,
    q("a", "4", "Pendant combien d’années les fils de Mosiah avaient-ils enseigné la parole parmi les Lamanites ?", "Quatorze ans", ["Quarante ans", "Sept ans"], ["quatorze ans"]),
    q("b", "21", "Comment s’appelait le roi du pays d’Ismaël ?", "Lamoni", ["Limhi", "Laman"], ["Lamoni"]),
    q("c", "38", "Combien de Lamanites tombèrent par la fronde d’Ammon ?", "Six Lamanites", ["Quatre Lamanites", "Huit Lamanites"], ["six"]),
  ),
  ch("alma", 18,
    q("a", "13", "Que signifie le mot Rabbanah ?", "Puissant ou grand roi", ["Seigneur sage et puissant", "Brave chef d’armée"], ["grand roi"]),
    q("b", "43", "Combien de temps le roi Lamoni resta-t-il étendu comme mort sur son lit ?", "Deux jours et deux nuits", ["Trois jours et trois nuits", "Un jour et une nuit"], ["deux jours et deux nuits"]),
    q("c", "9", "Que faisait Ammon quand le roi demanda après lui ?", "Il nourrissait les chevaux du roi", ["Il festoyait avec les serviteurs", "Il dormait dans la tente du roi"], ["chevaux"]),
  ),
  ch("alma", 19,
    q("a", "8", "Que dit Ammon du roi Lamoni quand il le regarda ?", "Il n’est pas mort, mais il dort en Dieu", ["Il est blessé et doit se reposer près du feu", "Il est malade et a besoin d’un médecin"], ["dort en Dieu"]),
    q("b", "13", "Que dit Lamoni quand il se releva ?", "Qu’il avait vu son Rédempteur", ["Qu’il avait vu une grande armée", "Qu’il avait vu son père"], ["Rédempteur"]),
    q("c", "28", "Qui avait fait rassembler la multitude ?", "Une servante lamanite", ["Une fille du roi", "Un prêtre du peuple"], ["servante"]),
  ),
  ch("alma", 20,
    q("a", "3", "Dans quel pays les frères d’Ammon étaient-ils en prison ?", "Au pays de Middoni", ["Au pays d’Ismaël", "Au pays de Sidom"], ["Middoni"]),
    q("b", "10", "Comment le père de Lamoni appelle-t-il le Néphite Ammon ?", "Un des enfants d’un menteur", ["Un des fils d’un roi", "Un des serviteurs du diable"], ["enfants d’un menteur"]),
    q("c", "23", "Qu’offrit le vieux roi à Ammon s’il l’épargnait ?", "La moitié du royaume", ["Un tiers de ses trésors", "Sa fille aînée"], ["moitié du royaume"]),
  ),
  ch("alma", 21,
    q("a", "2", "Quelle ville les Lamanites, les Amalékites et le peuple d’Amulon avaient-ils construite ?", "Une grande ville appelée Jérusalem", ["Une grande ville appelée Néphi", "Une grande ville appelée Zarahemla"], ["Jérusalem"]),
    q("b", "14", "Par qui Aaron et ses frères furent-ils délivrés de prison ?", "Par Lamoni et Ammon", ["Par Mosiah et Alma", "Par Omner et Himni"], ["Lamoni", "Ammon"]),
    q("c", "22", "Qu’annonça le roi Lamoni à son peuple au sujet de l’adoration du Seigneur ?", "Qu’ils étaient libres d’adorer le Seigneur partout", ["Qu’ils ne pouvaient adorer que dans les synagogues", "Qu’ils devaient adorer uniquement le roi"], ["adorer le Seigneur"]),
  ),
  ch("alma", 22,
    q("a", "3", "Que promirent Aaron et ses frères au roi en échange de leur vie ?", "Qu’ils seraient ses serviteurs", ["Qu’ils lui donneraient leurs biens", "Qu’ils quitteraient le pays"], ["serviteurs"]),
    q("b", "7", "Que disent les Amalékites au sujet de Dieu selon le roi ?", "Qu’il existe bel et bien un Dieu", ["Qu’il y a deux dieux au ciel", "Qu’il n’y a aucun Dieu"], ["un Dieu"]),
    q("c", "17", "Que fit le roi quand Aaron eut dit ses paroles ?", "Il se prosterna et se jeta sur le sol", ["Il se leva et quitta la grande salle", "Il appela sa garde du corps"], ["sur le sol"]),
  ),
  ch("alma", 23,
    q("a", "17", "Comment les Lamanites convertis s’appelèrent-ils ?", "Anti-Néphi-Léhis", ["Néphi-Lamanites", "Léhi-Néphites"], ["Anti-Néphi-Léhis"]),
    q("b", "1", "Que commanda le roi des Lamanites à son peuple au sujet d’Ammon et de ses frères ?", "De ne pas porter la main sur eux", ["De les chasser hors du pays", "De ne prêcher qu’en Ismaël"], ["porter la main"]),
    q("c", "14", "Quels groupes ne se convertirent pas ?", "Les Amalékites et les Amulonites", ["Les Néphites de Zarahemla", "Le peuple d’Ismaël et de Middoni"], ["Amalékites", "Amulonites"]),
  ),
  ch("alma", 24,
    q("a", "3", "Quel nom le roi donna-t-il à son fils à qui il conféra le royaume ?", "Anti-Néphi-Léhi", ["Anti-Léhi-Néphi", "Néphi-Anti-Léhi"], ["Anti-Néphi-Léhi"]),
    q("b", "16", "Que feraient-ils de leurs épées si leurs frères cherchaient à les détruire selon le roi ?", "Les enterrer profondément dans la terre", ["Les fondre pour en faire des outils", "Les offrir en cadeau aux Néphites"], ["profondément dans la terre"]),
    q("c", "22", "Combien d’entre eux furent tués sans résistance par les Lamanites ?", "Mille cinq personnes", ["Mille dix personnes", "Cinq cent cinq personnes"], ["mille cinq"]),
  ),
  ch("alma", 25,
    q("a", "11", "Qui fut le premier à subir la mort par le feu à cause de sa croyance en Dieu ?", "Abinadi", ["Amulek", "Gédéon"], ["Abinadi"]),
    q("b", "14", "Que firent les Lamanites convertis de leurs armes de guerre ?", "Ils enterrèrent leurs armes de guerre", ["Ils vendirent leurs armes de guerre", "Ils gardaient toujours leurs armes sur eux"], ["enterrèrent"]),
    q("c", "16", "À quoi la loi de Moïse servait-elle pour eux ?", "À fortifier leur foi au Christ", ["À séparer leur peuple des Néphites", "À garder leurs richesses au temple"], ["foi au Christ"]),
  ),
  ch("alma", 26,
    q("a", "4", "Que dit Ammon au sujet de milliers de Lamanites ?", "Qu’ils ont été amenés dans la bergerie de Dieu", ["Qu’ils se sont mis au service des Néphites", "Qu’ils ont chassé leur roi du pays entier"], ["bergerie de Dieu"]),
    q("b", "22", "Que donne-t-on à celui qui se repent, fait preuve de foi et prie continuellement selon Ammon ?", "De connaître les mystères de Dieu", ["Une place à côté du roi", "La richesse et le pouvoir dans le pays"], ["mystères de Dieu"]),
    q("c", "12", "De quoi Ammon dit-il qu’il se vantera ?", "Du Seigneur, son Dieu", ["De sa propre force", "De sa propre sagesse"], ["Dieu"]),
  ),
  // ===== EINDE =====
];
