import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Hélaman (édition française). Chaque fait est lié aux versets indiqués dans `verses` ; `npm run genees:check` le vérifie.
export const helaman: GeneesChapterSeed[] = [
  ch("hel", 1,
    q("a", "3", "Comment s’appelaient les fils de Pahoran qui se querellaient pour le siège du jugement ?", "Pahoran, Paanchi et Pacumeni", ["Pahoran, Moronihah et Pacumeni", "Pahoran, Paanchi et Pachus"], ["Paanchi", "Pacumeni"]),
    q("b", "10", "Comment s’appelait l’homme qui assassina Pahoran ?", "Kishkumen", ["Gadianton", "Coriantumr"], ["Kishkumen"]),
    q("c", "15", "Comment s’appelait le chef lamanite qui s’empara de la ville de Zarahemla ?", "Coriantumr", ["Zérahemnah", "Léhonti"], ["Coriantumr"]),
  ),
  ch("hel", 2,
    q("a", "4", "Qui était Gadianton ?", "Un homme extrêmement expert en paroles", ["Le nouveau grand juge du peuple", "Un capitaine des armées néphites"], ["expert en paroles"]),
    q("b", "6", "Qui eut connaissance du plan visant à faire périr Hélaman grâce à un déguisement ?", "Un serviteur d’Hélaman", ["Un garde du roi", "Un prêtre de Gadianton"], ["serviteur"]),
    q("c", "2", "À quoi Hélaman, fils d’Hélaman, fut-il nommé par la voix du peuple ?", "Occuper le siège du jugement", ["Commander l’armée du peuple", "Diriger l’administration du temple"], ["siège du jugement"]),
  ),
  ch("hel", 3,
    q("a", "21", "Comment s’appelaient les deux fils d’Hélaman ?", "Néphi et Léhi", ["Néphi et Aaron", "Léhi et Laman"], ["Néphi", "Léhi"]),
    q("b", "9", "Où habitait le peuple du pays situé du côté du nord ?", "Dans des tentes et des maisons de ciment", ["Dans des grottes et des maisons de bois", "Dans des villes de pierre et de montagnes"], ["ciment"]),
    q("c", "37", "Qui occupa le siège du jugement à la mort d’Hélaman ?", "Son fils aîné Néphi", ["Son fils cadet Léhi", "Son frère Moronihah"], ["Néphi"]),
  ),
  ch("hel", 4,
    q("a", "2", "Où allèrent les rebelles chassés du pays ?", "Auprès du roi des Lamanites", ["Dans les montagnes du nord", "Au pays des Zoramites"], ["roi des Lamanites"]),
    q("b", "10", "Quelle part de leurs possessions les Néphites perdirent-ils aux mains des Lamanites ?", "La moitié de toutes leurs possessions", ["Un tiers de toutes leurs possessions", "Un dixième de toutes leurs possessions"], ["moitié de toutes leurs possessions"]),
    q("c", "12", "Que faisaient les Néphites dans leur méchanceté selon le verset 12 ?", "Ils opprimaient les pauvres", ["Ils négligeaient leurs temples", "Ils refusaient de payer l’impôt"], ["opprimaient les pauvres"]),
  ),
  ch("hel", 5,
    q("a", "1", "À qui Néphi remit-il le siège du jugement ?", "À Cézoram", ["À Pahoran", "À Moronihah"], ["Cézoram"]),
    q("b", "19", "Combien de Lamanites furent baptisés en vue du repentir par la prédication de Néphi et de Léhi ?", "Huit mille", ["Deux mille", "Quatre mille"], ["huit mille"]),
    q("c", "24", "Qu’est-ce qui entourait Néphi et Léhi dans la prison sans les brûler ?", "Une colonne de feu", ["Un nuage blanc", "Un mur de lumière"], ["colonne de feu"]),
  ),
  ch("hel", 6,
    q("a", "10", "Comment s’appelaient le pays au sud et le pays au nord ?", "Le sud Léhi, le nord Mulek", ["Le sud Mulek, le nord Léhi", "Le sud Néphi, le nord Zarahemla"], ["Léhi", "Mulek"]),
    q("b", "15", "Qui fut assassiné par une main inconnue la soixante-sixième année ?", "Cézoram", ["Hélaman", "Gédéon"], ["Cézoram"]),
    q("c", "18", "Par qui la bande d’assassins et de pillards avait-elle été formée ?", "Par Kishkumen et Gadianton", ["Par Coriantumr et Tubaloth", "Par Pacumeni et Paanchi"], ["Kishkumen", "Gadianton"]),
  ),
  ch("hel", 7,
    q("a", "10", "Où se trouvait Néphi quand il épancha son âme devant Dieu ?", "Sur une tour dans son jardin", ["Dans le temple de Zarahemla", "Sur une montagne hors de la ville"], ["tour"]),
    q("b", "17", "Quelle question Néphi posa-t-il au peuple au verset 17 ?", "Pourquoi voulez-vous mourir ?", ["Pourquoi voulez-vous fuir ?", "Pourquoi voulez-vous la richesse ?"], ["pourquoi voulez-vous mourir"]),
    q("c", "25", "À quelle bande les gens s’étaient-ils unis ?", "À la bande secrète de Gadianton", ["Aux vagabonds venus du nord", "Aux Lamanites du désert"], ["Gadianton"]),
  ),
  ch("hel", 8,
    q("a", "14", "Qu’éleva Moïse dans le désert ?", "Le serpent d’airain", ["Un autel d’airain", "La mer d’airain"], ["serpent d’airain"]),
    q("b", "17", "Qui vit la venue du Christ et fut rempli de joie ?", "Abraham", ["Hénoc", "Joseph"], ["Abraham"]),
    q("c", "21", "Lequel des fils de Sédécias ne fut pas tué ?", "Mulek", ["Néphi", "Joseph"], ["Mulek"]),
  ),
  ch("hel", 9,
    q("a", "3", "Que trouvèrent les cinq hommes en arrivant au siège du jugement ?", "Le grand juge était tombé par terre, dans son sang", ["Le siège du jugement était vide et abandonné", "Le grand juge tenait une assemblée du peuple"], ["tombé par terre"]),
    q("b", "23", "Comment s’appelait le grand juge assassiné ?", "Seezoram", ["Moronihah", "Pacumeni"], ["Seezoram"]),
    q("c", "26", "À la maison de qui les hommes devaient-ils aller selon Néphi ?", "À la maison de Séantum", ["À la maison de Pacumeni", "À la maison de Paanchi"], ["Séantum"]),
  ),
  ch("hel", 10,
    q("a", "7", "Que se passera-t-il, selon le Seigneur, avec ce que Néphi scelle sur la terre ?", "Ce sera scellé au ciel", ["Ce sera révoqué au ciel", "Ce sera oublié au ciel"], ["scellé au ciel"]),
    q("b", "8", "Que se passerait-il si Néphi disait au temple qu’il sera fendu ?", "Le temple serait fendu en deux", ["Le temple prendrait feu", "Le temple s’enfoncerait dans le sol"], ["fendu en deux"]),
    q("c", "9", "Que se passerait-il si Néphi disait à la montagne : Sois abaissée ?", "La montagne serait nivelée", ["La montagne prendrait feu", "La montagne se fendrait en deux"], ["nivel"]),
  ),
  ch("hel", 11,
    q("a", "4", "Que Néphi demanda-t-il pour le pays à la place de l’épée ?", "Une famine", ["Un séisme", "Une crue"], ["famine"]),
    q("b", "13", "Que Néphi demanda-t-il au Seigneur d’envoyer sur la surface de la terre ?", "La pluie", ["Le feu", "La neige"], ["pluie"]),
    q("c", "26", "Que devinrent les dissidents avec le temps ?", "Une bande de brigands extrêmement grande", ["Un peuple puissant et très pacifique", "Une grande armée des Lamanites"], ["bande de brigands"]),
  ),
  ch("hel", 12,
    q("a", "7", "Comment est décrit le néant des enfants des hommes au verset 7 ?", "Moins que la poussière de la terre", ["Moins que le sable de la mer", "Moins qu’une pierre dans le fleuve"], ["poussière de la terre"]),
    q("b", "14", "Que se passe-t-il quand Dieu dit à la terre : Tu reculeras ?", "Le jour est allongé de nombreuses heures", ["La nuit est allongée de nombreuses heures", "Le soleil se couche pour toujours"], ["nombreuses heures"]),
    q("c", "23", "Qui sera sauvé selon ces versets ?", "Ceux qui se repentent et écoutent le Seigneur", ["Ceux qui sont riches et font beaucoup d’offrandes", "Ceux qui n’ont jamais péché de leur vie"], ["se repentent et écoutent"]),
  ),
  ch("hel", 13,
    q("a", "2", "De quel peuple était Samuel ?", "Un Lamanite", ["Un Néphite", "Un Zoramite"], ["Lamanite"]),
    q("b", "4", "Sur quoi Samuel monta-t-il quand on ne le laissa pas entrer dans la ville ?", "Sur la muraille de la ville", ["Sur la tour du temple", "Sur une colline hors de la ville"], ["muraille"]),
    q("c", "9", "Combien d’années passeraient avant que le Seigneur fasse frapper les Néphites ?", "Pas quatre cents ans", ["Pas deux cents ans", "Pas trois mille ans"], ["quatre cents ans"]),
  ),
  ch("hel", 14,
    q("a", "2", "Dans combien d’années le Fils de Dieu viendrait-il selon Samuel ?", "Dans cinq ans", ["Dans dix ans", "Dans vingt ans"], ["cinq"]),
    q("b", "5", "Quel signe se lèvera dans le ciel selon Samuel ?", "Une nouvelle étoile", ["Un nouveau soleil", "Une nouvelle lune"], ["nouvelle étoile"]),
    q("c", "21", "Qu’y aura-t-il pendant de nombreuses heures quand le Seigneur rendra l’esprit ?", "Des tonnerres et des éclairs", ["Une grêle continue de trois jours", "Un vent fort sans éclairs"], ["tonnerres et des éclairs"]),
  ),
  ch("hel", 15,
    q("a", "9", "Qu’ont enterré les Lamanites convertis selon Samuel ?", "Leurs armes de guerre", ["Leurs idoles d’or", "Leurs trésors d’argent"], ["armes de guerre"]),
    q("b", "1", "Que deviendront les maisons du peuple s’il ne se repent pas selon Samuel ?", "Elles seront laissées désertes", ["Elles seront incendiées par le feu", "Elles seront données aux Lamanites"], ["laissées désertes"]),
    q("c", "16", "Que fera le Seigneur aux Lamanites selon le verset 16 ?", "Il ne les détruira pas totalement", ["Il les punira immédiatement", "Il les oubliera pour toujours"], ["pas totalement"]),
  ),
  ch("hel", 16,
    q("a", "7", "Que fit Samuel quand le peuple voulut porter la main sur lui ?", "Il se jeta en bas de la muraille et s’enfuit", ["Il alla à la rencontre du peuple et parla", "Il se cacha dans le temple de la ville"], ["en bas de la muraille"]),
    q("b", "4", "Que fit Néphi de ceux qui crurent aux paroles de Samuel ?", "Il les baptisa et les appela au repentir", ["Il les renvoya tranquillement chez eux", "Il leur fit offrir des sacrifices"], ["baptisa"]),
    q("c", "13", "Quelle année du règne des juges de grands signes furent-ils donnés au peuple ?", "La quatre-vingt-dixième année", ["La quatre-vingtième année", "La cent dixième année"], ["quatre-vingt-dixième année"]),
  ),
  // ===== EINDE =====
];
