import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Jacob (édition française). Chaque fait est lié aux versets indiqués dans `verses` ; `npm run genees:check` le vérifie.
export const jakob: GeneesChapterSeed[] = [
  ch("jacob", 1,
    q("a", "1", "Combien d’années s’étaient écoulées depuis que Léhi avait quitté Jérusalem quand Néphi donna un commandement à Jacob ?", "Cinquante-cinq ans", ["Trente-cinq ans", "Soixante-quinze ans"], ["cinquante-cinq ans"]),
    q("b", "11", "Comment le peuple appelait-il les rois après Néphi ?", "Deuxième Néphi", ["Néphi le Jeune", "Deuxième Léhi"], ["deuxième Néphi"]),
    q("c", "18", "Par la main de qui Jacob et Joseph furent-ils consacrés prêtres et instructeurs ?", "Par la main de Néphi", ["Par la main de Léhi", "Par la main de Sam"], ["main de Néphi"]),
  ),
  ch("jacob", 2,
    q("a", "12", "Que beaucoup du peuple avaient-ils commencé à rechercher selon Jacob ?", "De l’or et de l’argent", ["Des terres et du bétail", "Le pouvoir et la gloire"], ["l’or", "l’argent"]),
    q("b", "27", "Combien d’épouses un homme peut-il avoir parmi ce peuple selon le Seigneur ?", "Pas plus d’une épouse", ["Pas plus de deux épouses", "Pas plus de sept épouses"], ["plus d’une épouse"]),
    q("c", "18", "Que faut-il rechercher avant de rechercher la richesse selon Jacob ?", "Le royaume de Dieu", ["La faveur du roi", "Une terre à soi"], ["royaume de Dieu"]),
  ),
  ch("jacob", 3,
    q("a", "14", "Comment appelle-t-on les plaques sur lesquelles Jacob écrit ?", "Les plaques de Jacob", ["Les plaques de Sam", "Les plaques de Joseph"], ["plaques de Jacob"]),
    q("b", "9", "Que commande Jacob au peuple à propos des Lamanites ?", "De ne plus les insulter à cause de leur peau", ["De les chasser hors du pays où ils vivent", "De leur apprendre à lire et à écrire"], ["insulter"]),
    q("c", "1", "À qui Jacob veut-il d’abord parler dans ce chapitre ?", "À ceux qui ont le cœur pur", ["À ceux qui sont riches en or", "À ceux qui ont abandonné la loi"], ["cœur pur"]),
  ),
  ch("jacob", 4,
    q("a", "5", "Pourquoi Jacob et son peuple gardent-ils la loi de Moïse ?", "Parce qu’elle tourne leur âme vers le Christ", ["Parce que le roi l’exige de tout le peuple", "Parce qu’ils perdraient autrement leur pays"], ["âme vers"]),
    q("b", "9", "Par quoi la terre a-t-elle été créée selon Jacob ?", "Par le pouvoir de sa parole", ["Par le pouvoir de son bras", "Par l’aide des anges"], ["pouvoir de sa parole"]),
    q("c", "16", "Que deviendra la pierre que les Juifs rejettent selon les Écritures ?", "La seule fondation sûre", ["Un ornement pour le roi", "La porte du grand temple"], ["fondation sûre"]),
  ),
  ch("jacob", 5,
    q("a", "3", "À quoi le Seigneur compare-t-il la maison d’Israël selon Zénos ?", "À un olivier franc", ["À une vigne sauvage", "À un figuier franc"], ["olivier franc"]),
    q("b", "41", "Qu’est-ce que le maître de la vigne demanda en pleurant à son serviteur ?", "Qu’aurais-je pu faire de plus ?", ["Pourquoi ne m’as-tu pas averti ?", "Qui a planté tous ces arbres ?"], ["faire de plus"]),
    q("c", "50", "Que dit le serviteur quand le maître voulut abattre les arbres ?", "Épargne-la encore un peu", ["Fais venir d’autres serviteurs", "Coupe-les tous maintenant"], ["Épargne-la"]),
  ),
  ch("jacob", 6,
    q("a", "6", "Quelle question Jacob pose-t-il au peuple qui endurcit son cœur ?", "Pourquoi voulez-vous mourir ?", ["Pourquoi voulez-vous partir ?", "Pourquoi voulez-vous combattre ?"], ["pourquoi voulez-vous mourir"]),
    q("b", "11", "Par quelle porte faut-il entrer selon Jacob ?", "Par la porte étroite", ["Par la porte d’or", "Par la porte de l’est"], ["porte étroite"]),
    q("c", "3", "Que se passera-t-il avec le monde selon Jacob ?", "Il sera brûlé par le feu", ["Il sera submergé par l’eau", "Il sera détruit par la tempête"], ["brûlé par le feu"]),
  ),
  ch("jacob", 7,
    q("a", "1", "Comment s’appelait l’homme qui prêcha parmi le peuple qu’il n’y aurait pas de Christ ?", "Shérem", ["Korihor", "Zeezrom"], ["Shérem"]),
    q("b", "15", "Que se passa-t-il pour Shérem après que Jacob eut dit ces paroles ?", "Il tomba par terre par la puissance de Dieu", ["Il s’enfuit du pays pendant la nuit même", "Il fut jeté en prison par le peuple entier"], ["tomba par terre"]),
    q("c", "27", "À qui Jacob donna-t-il les plaques ?", "À son fils Énos", ["À son frère Joseph", "À son fils Jarom"], ["Énos"]),
  ),
  // ===== EINDE =====
];
