import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Mosiah (édition française). Chaque fait est lié aux versets indiqués dans `verses` ; `npm run genees:check` le vérifie.
export const mosiah: GeneesChapterSeed[] = [
  ch("mosiah", 1,
    q("a", "2", "Comment s’appelaient les trois fils du roi Benjamin ?", "Mosiah, Hélorum et Hélaman", ["Mosiah, Benjamin et Hélaman", "Mosiah, Hélorum et Amaléki"], ["Mosiah", "Hélorum", "Hélaman"]),
    q("b", "16", "Quel objet Mosiah reçut-il aussi en charge, outre les plaques ?", "L’épée de Laban", ["La couronne du roi", "L’arche d’alliance"], ["épée de Laban"]),
    q("c", "12", "Qu’est-ce qui ne sera jamais effacé, sauf par la transgression, selon le roi Benjamin ?", "Le nom qu’il leur donne", ["Le temple qu’ils bâtissent", "La loi qu’ils reçoivent"], ["nom"]),
  ),
  ch("mosiah", 2,
    q("a", "7", "Que fit ériger le roi Benjamin pour que le peuple entende ses paroles ?", "Une tour", ["Un pont", "Un autel"], ["tour"]),
    q("b", "17", "Que sont les hommes lorsqu’ils sont au service de leurs semblables, selon Benjamin ?", "Simplement au service de votre Dieu", ["Au service du seul roi du pays", "Au service de leurs propres intérêts"], ["service de votre Dieu"]),
    q("c", "14", "Avec quoi le roi Benjamin travaillait-il pour servir son peuple ?", "De ses propres mains", ["Avec l’aide d’esclaves", "Avec l’aide de soldats"], ["mains"]),
  ),
  ch("mosiah", 3,
    q("a", "8", "Quel nom et quelle mère l’ange annonce-t-il pour le Seigneur qui viendra ?", "Jésus-Christ, et sa mère Marie", ["Emmanuel, et sa mère Sara", "Jean, et sa mère Élisabeth"], ["Jésus-Christ", "Marie"]),
    q("b", "10", "Quand ressuscitera-t-il d’entre les morts selon l’ange ?", "Le troisième jour", ["Le septième jour", "Après quarante jours"], ["troisième jour"]),
    q("c", "19", "Qu’est-ce que l’homme naturel selon le verset 19 ?", "Un ennemi de Dieu", ["Un ami du monde", "Un fidèle de la loi"], ["ennemi de Dieu"]),
  ),
  ch("mosiah", 4,
    q("a", "1", "Comment les gens se trouvaient-ils quand le roi Benjamin jeta les regards sur la multitude ?", "Ils étaient tombés par terre", ["Ils avaient pris la fuite", "Ils s’étaient endormis"], ["par terre"]),
    q("b", "19", "Comment Benjamin nous appelle-t-il tous dans notre dépendance envers Dieu ?", "Des mendiants", ["Des riches", "Des souverains"], ["mendiants"]),
    q("c", "14", "Que ne souffrirez-vous pas que vos enfants subissent selon Benjamin ?", "Qu’ils soient affamés ou nus", ["Qu’ils soient punis ou malades", "Qu’ils aient soif ou froid"], ["affamés", "nus"]),
  ),
  ch("mosiah", 5,
    q("a", "7", "Comment les hommes seront-ils appelés à cause de l’alliance selon Benjamin ?", "Enfants du Christ", ["Serviteurs du roi", "Enfants de Benjamin"], ["enfants du Christ"]),
    q("b", "5", "À quoi les gens étaient-ils disposés dans l’alliance avec Dieu ?", "À faire sa volonté et à garder ses commandements", ["À donner tous leurs biens au roi et à ses prêtres", "À quitter le pays et à habiter ailleurs"], ["volonté", "commandements"]),
    q("c", "14", "Quel animal de son voisin personne ne garde-t-il pour lui selon Benjamin ?", "Un âne", ["Un bœuf", "Un porc"], ["âne"]),
  ),
  ch("mosiah", 6,
    q("a", "4", "À quel moment de sa vie Mosiah commença-t-il à régner ?", "Dans sa trentième année", ["Dans sa vingtième année", "Dans sa quarantième année"], ["trentième année"]),
    q("b", "5", "Combien d’années le roi Benjamin vécut-il encore après que Mosiah fut devenu roi ?", "Encore trois ans", ["Encore sept ans", "Encore dix ans"], ["trois ans"]),
    q("c", "7", "Comment le roi Mosiah évita-t-il d’être un fardeau pour son peuple ?", "Il cultiva lui-même la terre", ["Il fit travailler des esclaves", "Il demanda des cadeaux au peuple"], ["cultiva"]),
  ),
  ch("mosiah", 7,
    q("a", "3", "Qui était le chef des hommes forts qui montèrent au pays de Léhi-Néphi ?", "Ammon", ["Limhi", "Zénif"], ["Ammon"]),
    q("b", "4", "Pendant combien de jours errèrent-ils dans le désert ?", "Quarante jours", ["Quatorze jours", "Soixante-dix jours"], ["quarante jours"]),
    q("c", "9", "Qui était le roi du peuple du pays de Néphi qui rencontra Ammon ?", "Limhi, fils de Noé", ["Laman, fils de Zénif", "Noé, fils de Limhi"], ["Limhi", "Noé"]),
  ),
  ch("mosiah", 8,
    q("a", "9", "En quoi étaient faites les vingt-quatre plaques que les hommes de Limhi rapportèrent ?", "En or pur, couvertes d’inscriptions", ["En cuivre pur, couvertes d’inscriptions", "En argent pur, couvertes d’inscriptions"], ["or pur"]),
    q("b", "15", "Qu’est-ce qu’un voyant selon le roi Limhi ?", "Plus grand qu’un prophète", ["Égal à un simple prêtre", "Moins grand qu’un roi"], ["plus grand qu’un prophète"]),
    q("c", "7", "Combien d’hommes Limhi envoya-t-il dans le désert pour trouver le pays de Zarahemla ?", "Quarante-trois hommes", ["Trente-trois hommes", "Soixante-trois hommes"], ["quarante-trois"]),
  ),
  ch("mosiah", 9,
    q("a", "1", "Qui est l’auteur du récit au verset 1, envoyé comme espion parmi les Lamanites ?", "Zénif", ["Ammon", "Limhi"], ["Zénif"]),
    q("b", "11", "Depuis combien d’années le peuple de Zénif demeurait-il dans le pays quand le roi Laman commença à se sentir mal à l’aise ?", "Douze ans", ["Six ans", "Vingt ans"], ["douze ans"]),
    q("c", "18", "Combien de Lamanites le peuple de Zénif tua-t-il en un jour et une nuit ?", "Trois mille quarante-trois", ["Deux mille quarante-trois", "Cinq mille quarante-sept"], ["trois mille quarante-trois"]),
  ),
  ch("mosiah", 10,
    q("a", "3", "Pendant combien d’années le peuple de Zénif posséda-t-il le pays de ses pères ?", "Vingt-deux ans", ["Trente-deux ans", "Quarante-deux ans"], ["vingt-deux ans"]),
    q("b", "5", "Quels travaux les femmes devaient-elles accomplir sous Zénif ?", "Filer, peiner et fabriquer du lin", ["Cuisiner et instruire les enfants", "Forger des armes et des boucliers"], ["filer"]),
    q("c", "9", "Où Zénif fit-il cacher les femmes et les enfants de son peuple ?", "Dans le désert", ["Dans la tour", "Derrière les murs"], ["désert"]),
  ),
  ch("mosiah", 11,
    q("a", "3", "Quelle part de tout ce qu’ils possédaient le roi Noé exigea-t-il comme impôt ?", "Un cinquième", ["Un dixième", "Un sixième"], ["cinquième"]),
    q("b", "20", "Comment s’appelait le prophète qui commença à prophétiser parmi le peuple du roi Noé ?", "Abinadi", ["Amulon", "Gédéon"], ["Abinadi"]),
    q("c", "12", "Que construisit le roi Noé près du temple ?", "Une très haute tour", ["Un grand autel d’or", "Un large mur de ville"], ["très haute tour"]),
  ),
  ch("mosiah", 12,
    q("a", "3", "À quoi Abinadi compare-t-il la vie du roi Noé ?", "À un vêtement dans une fournaise ardente", ["À une fleur sur le champ au printemps", "À une pierre dans le fleuve rapide"], ["vêtement dans une fournaise ardente"]),
    q("b", "17", "Que fit le roi Noé d’Abinadi ?", "Il le fit jeter en prison", ["Il le fit exécuter aussitôt", "Il le fit bannir du pays"], ["prison"]),
    q("c", "28", "Que dirent les prêtres du roi Noé qu’ils enseignaient ?", "La loi de Moïse", ["La loi de Noé", "La loi du roi"], ["loi de Moïse"]),
  ),
  ch("mosiah", 13,
    q("a", "16", "Quel jour faut-il se souvenir de sanctifier selon le commandement ?", "Le jour du repos", ["Le premier jour", "Le jour des récoltes"], ["jour du repos"]),
    q("b", "28", "Que dit Abinadi du salut et de la loi de Moïse ?", "Le salut ne vient pas par la loi seule", ["Le salut vient par la loi seule", "Le salut vient par les sacrifices seuls"], ["par la loi seule"]),
    q("c", "24", "Que ne faut-il pas convoiter selon le commandement ?", "La maison de son prochain", ["Le champ du roi du pays", "L’or des prêtres du roi"], ["prochain"]),
  ),
  ch("mosiah", 14,
    q("a", "6", "À quoi Ésaïe nous compare-t-il, nous tous qui nous sommes égarés ?", "À des brebis", ["À des chèvres", "À des bœufs"], ["brebis"]),
    q("b", "3", "Comment est-il appelé au verset 3 ?", "Homme de douleur", ["Homme de guerre", "Homme de sagesse"], ["homme de douleur"]),
    q("c", "7", "À quoi est-il comparé quand il fut opprimé ?", "À un agneau qu’on mène à la boucherie", ["À un lion pris dans le filet", "À un taureau offert en sacrifice"], ["agneau"]),
  ),
  ch("mosiah", 15,
    q("a", "14", "Quel message les saints prophètes ont-ils porté à Sion selon Abinadi ?", "Ton Dieu règne !", ["Ton roi vient !", "Ton peuple vit !"], ["Ton Dieu règne"]),
    q("b", "25", "Que possèdent les petits enfants selon Abinadi ?", "La vie éternelle", ["Un royaume à eux", "Une lourde peine"], ["vie éternelle"]),
    q("c", "21", "Comment s’appelle la résurrection dont Abinadi parle au verset 21 ?", "La première résurrection", ["La dernière résurrection", "La troisième résurrection"], ["première résurrection"]),
  ),
  ch("mosiah", 16,
    q("a", "8", "Qu’est-ce qui est englouti dans le Christ selon Abinadi ?", "L’aiguillon de la mort", ["Le pouvoir du diable", "La loi de Moïse"], ["aiguillon de la mort"]),
    q("b", "9", "Qu’est le Christ pour le monde selon Abinadi ?", "La lumière et la vie du monde", ["Le juge et le berger du monde", "Le roi et le gardien du monde"], ["lumière et la vie du monde"]),
    q("c", "14", "De quoi la loi de Moïse est-elle une ombre selon Abinadi ?", "Des choses qui sont à venir", ["Des prophètes d’autrefois", "Des premiers rois du pays"], ["choses qui sont à venir"]),
  ),
  ch("mosiah", 17,
    q("a", "2", "Comment s’appelait le jeune homme parmi les prêtres qui crut aux paroles d’Abinadi ?", "Alma", ["Limhi", "Hélam"], ["Alma"]),
    q("b", "20", "Comment Abinadi mourut-il ?", "Par le feu", ["Par l’épée", "Par noyade"], ["par le feu"]),
    q("c", "6", "Après combien de jours le roi fit-il de nouveau amener Abinadi devant lui ?", "Après trois jours", ["Après sept jours", "Après deux jours"], ["trois jours"]),
  ),
  ch("mosiah", 18,
    q("a", "5", "Comment s’appelait le lieu où il y avait une source d’eau pure et où Alma se rendit ?", "Mormon", ["Hélam", "Shilom"], ["Mormon"]),
    q("b", "16", "Combien de personnes Alma baptisa-t-il environ aux eaux de Mormon ?", "Environ deux cent quatre âmes", ["Environ quatre cent quatre âmes", "Environ cent quatre âmes"], ["deux cent quatre"]),
    q("c", "18", "Combien de prêtres Alma ordonna-t-il par rapport au nombre de personnes ?", "Un prêtre par cinquante personnes", ["Un prêtre par cent personnes", "Un prêtre par vingt personnes"], ["prêtre par cinquante"]),
  ),
  ch("mosiah", 19,
    q("a", "4", "Qui tira son épée contre le roi Noé ?", "Gédéon", ["Limhi", "Hélam"], ["Gédéon"]),
    q("b", "20", "Que firent les hommes au roi Noé après qu’il leur eut commandé de ne pas retourner ?", "Ils le firent souffrir jusqu’à la mort par le feu", ["Ils le laissèrent libre dans le désert pour toujours", "Ils le ramenèrent dans son palais, sain et sauf"], ["mort par le feu"]),
    q("c", "26", "Que jura Limhi au roi des Lamanites ?", "Que son peuple lui payerait un tribut", ["Que son peuple quitterait le pays", "Que son peuple l’adorerait comme un dieu"], ["tribut"]),
  ),
  ch("mosiah", 20,
    q("a", "5", "Combien de filles des Lamanites les prêtres de Noé enlevèrent-ils ?", "Vingt-quatre", ["Vingt-six", "Vingt et une"], ["vingt-quatre"]),
    q("b", "10", "À quoi est comparé le combat du peuple de Limhi ?", "À des lions pour leurs proies", ["À des loups pour leur troupeau", "À des ours pour leurs petits"], ["lions"]),
    q("c", "17", "Qui était le capitaine du roi qui le pria de renoncer à faire des recherches ?", "Gédéon", ["Hélam", "Amulon"], ["Gédéon"]),
  ),
  ch("mosiah", 21,
    q("a", "26", "De quoi le pays que les hommes de Limhi trouvèrent était-il couvert ?", "D’ossements desséchés", ["De nuages de poussière", "De statues d’or"], ["ossements desséchés"]),
    q("b", "17", "Que commanda le roi Limhi à chaque homme à cause des nombreuses veuves ?", "De donner pour l’entretien des veuves", ["De donner un dixième de sa récolte au roi", "D’épouser une veuve de sa famille"], ["entretien des veuves"]),
    q("c", "33", "Pourquoi Limhi et son peuple ne pouvaient-ils pas être baptisés ?", "Personne n’avait l’autorité de Dieu", ["Il n’y avait pas d’eau dans le pays", "Le roi l’avait interdit"], ["autorité de Dieu"]),
  ),
  ch("mosiah", 22,
    q("a", "6", "Quel chemin d’évasion Gédéon proposa-t-il ?", "Par le mur de derrière de la ville", ["Par la grande porte de la ville", "Sur le fleuve avec des bateaux"], ["mur de derrière"]),
    q("b", "10", "Que Limhi envoya-t-il aux Lamanites comme tribut et comme présent ?", "Du vin", ["Du pain", "Du blé"], ["vin"]),
    q("c", "13", "Dans quel pays le peuple de Limhi arriva-t-il après de nombreux jours dans le désert ?", "Au pays de Zarahemla", ["Au pays d’Hélam", "Au pays de Shilom"], ["Zarahemla"]),
  ),
  ch("mosiah", 23,
    q("a", "3", "Combien de jours le peuple d’Alma s’enfuit-il dans le désert ?", "Huit jours", ["Quatre jours", "Douze jours"], ["huit jours"]),
    q("b", "19", "Comment le peuple d’Alma appela-t-il le pays où il s’établit ?", "Hélam", ["Mormon", "Léhi"], ["Hélam"]),
    q("c", "6-7", "Qui le peuple d’Alma voulait-il avoir pour roi ?", "Alma, mais il refusa", ["Gédéon, mais il refusa", "Hélam, mais il refusa"], ["Alma"]),
  ),
  ch("mosiah", 24,
    q("a", "20", "Comment Alma et son peuple appelèrent-ils la vallée où ils dressèrent leurs tentes ?", "La vallée Alma", ["La vallée Hélam", "La vallée Amulon"], ["vallée Alma"]),
    q("b", "19", "Que fit le Seigneur à l’heure de leur fuite avec les Lamanites ?", "Il envoya un profond sommeil sur eux", ["Il fit se lever une grande tempête", "Il fit disparaître leurs armes"], ["profond sommeil"]),
    q("c", "25", "Après combien de jours dans le désert le peuple d’Alma arriva-t-il à Zarahemla ?", "Après douze jours", ["Après six jours", "Après quarante jours"], ["douze jours"]),
  ),
  ch("mosiah", 25,
    q("a", "23", "Combien d’Églises y avait-il dans le pays de Zarahemla ?", "Sept Églises", ["Trois Églises", "Douze Églises"], ["sept Églises"]),
    q("b", "17", "Qui désira être baptisé après qu’Alma eut enseigné le peuple ?", "Le roi Limhi", ["Le roi Mosiah", "Le roi Noé"], ["Limhi"]),
    q("c", "2", "De qui le peuple de Zarahemla était-il descendant ?", "De Mulek", ["De Néphi", "De Laman"], ["Mulek"]),
  ),
  ch("mosiah", 26,
    q("a", "8", "À qui le roi Mosiah avait-il donné l’autorité sur l’Église ?", "Alma", ["Limhi", "Hélam"], ["Alma"]),
    q("b", "22", "En vue de quoi est baptisé quiconque est baptisé selon le Seigneur ?", "En vue du repentir", ["En vue de la richesse", "En vue de la liberté"], ["repentir"]),
    q("c", "30", "Combien de fois le Seigneur pardonnera-t-il les offenses de son peuple selon le verset 30 ?", "Toutes les fois qu’il se repentira", ["Au plus sept fois chaque année", "Seulement lors de la première faute"], ["toutes les fois"]),
  ),
  ch("mosiah", 27,
    q("a", "11", "Qui apparut à Alma le fils et aux fils de Mosiah ?", "L’ange du Seigneur", ["Le prophète Abinadi", "Le roi de Zarahemla"], ["ange du Seigneur"]),
    q("b", "23", "Combien de temps les prêtres et le peuple jeûnèrent-ils et prièrent-ils avant que les membres d’Alma reçoivent leur force ?", "Deux jours et deux nuits", ["Trois jours et trois nuits", "Sept jours et sept nuits"], ["deux jours et deux nuits"]),
    q("c", "34", "Comment s’appelaient les quatre fils de Mosiah ?", "Ammon, Aaron, Omner et Himni", ["Ammon, Aaron, Hélam et Gédéon", "Ammon, Omner, Himni et Limhi"], ["Ammon", "Aaron", "Omner", "Himni"]),
  ),
  ch("mosiah", 28,
    q("a", "5", "Où les fils de Mosiah voulaient-ils aller prêcher ?", "Au pays de Néphi", ["Au pays d’Hélam", "Au pays de Shilom"], ["pays de Néphi"]),
    q("b", "13", "Avec quoi Mosiah avait-il traduit les annales du peuple détruit ?", "Avec deux pierres fixées dans un arc", ["Avec des lunettes d’or et d’argent", "Avec un rouleau de fin parchemin"], ["deux pierres"]),
    q("c", "20", "À qui Mosiah confia-t-il les plaques d’airain et les objets qu’il avait gardés ?", "À Alma, fils d’Alma", ["À Ammon, son fils", "À Aaron, son fils"], ["Alma"]),
  ),
  ch("mosiah", 29,
    q("a", "2", "Qui le peuple voulut-il d’abord pour roi ?", "Aaron", ["Ammon", "Himni"], ["Aaron"]),
    q("b", "42", "Qui fut désigné pour être le premier grand juge ?", "Alma", ["Aaron", "Limhi"], ["Alma"]),
    q("c", "46", "Dans quelle année de son règne Mosiah mourut-il ?", "Dans la trente-troisième année", ["Dans la vingt-troisième année", "Dans la quarante-troisième année"], ["trente-troisième année"]),
  ),
  // ===== EINDE =====
];
