import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 4 Néphi, Mormon, Éther et Moroni (édition française). Chaque fait est lié aux versets indiqués dans `verses` ; `npm run genees:check` le vérifie.
export const slot: GeneesChapterSeed[] = [
  ch("4-ne", 1,
    q("a", "3", "Qu’avaient les gens entre eux après leur conversion ?", "Ils avaient tout en commun entre eux", ["Ils avaient tout en propriété privée", "Tout appartenait aux juges du pays"], ["en commun"]),
    q("b", "17", "Comment les gens étaient-ils devenus selon le verset 17 ?", "Un seul peuple, enfants du Christ", ["Divisés en de nombreuses classes", "Séparés en Néphites et en Lamanites"], ["enfants du Christ"]),
    q("c", "48", "Qui cacha les annales sacrées pour le Seigneur ?", "Ammaron", ["Mormon", "Moroni"], ["Ammaron"]),
  ),
  ch("morm", 1,
    q("a", "2", "Quel âge avait Mormon quand Ammaron vint à lui ?", "Environ dix ans", ["Environ douze ans", "Environ sept ans"], ["dix ans"]),
    q("b", "3", "Quand Mormon devait-il se souvenir de ce qu’il avait observé selon Ammaron ?", "Vers sa vingt-quatrième année", ["Vers sa trentième année", "Vers sa dix-huitième année"], ["vingt-quatrième année"]),
    q("c", "15", "À quel âge Mormon fut-il visité par le Seigneur ?", "Quinze ans", ["Douze ans", "Vingt ans"], ["quinze ans"]),
  ),
  ch("morm", 2,
    q("a", "2", "Dans quelle année de sa vie Mormon dirigea-t-il une armée ?", "Dans sa seizième année", ["Dans sa dix-huitième année", "Dans sa vingtième année"], ["seizième année"]),
    q("b", "9", "Comment s’appelait le roi des Lamanites qui attaqua avec une grande armée ?", "Aaron", ["Lamoni", "Zoram"], ["Aaron"]),
    q("c", "29", "Que donnèrent les Lamanites aux Néphites dans le traité ?", "Le pays du côté du nord", ["Le pays du côté du sud", "Le pays de Zarahemla"], ["côté du nord"]),
  ),
  ch("morm", 3,
    q("a", "11", "Que refusa Mormon d’être à cause de leur méchanceté ?", "Leur commandant et chef", ["Leur roi et leur juge", "Leur prêtre et leur maître"], ["commandant"]),
    q("b", "13", "Combien de fois Mormon avait-il délivré son peuple des mains de ses ennemis ?", "Trois fois", ["Deux fois", "Sept fois"], ["trois fois"]),
    q("c", "17", "À qui Mormon écrit-il selon le verset 17 ?", "Aux Gentils et à la maison d’Israël", ["Seulement aux Néphites de son temps", "Au roi et à ses capitaines"], ["Gentils", "maison d’Israël"]),
  ),
  ch("morm", 4,
    q("a", "2", "Dans quel pays les armées néphites furent-elles repoussées ?", "Au pays de Désolation", ["Au pays de Jershon", "Au pays de Zarahemla"], ["Désolation"]),
    q("b", "5", "Par qui les méchants sont-ils punis selon Mormon ?", "Par les méchants", ["Par les anges", "Par les justes"], ["méchants"]),
    q("c", "23", "Où Mormon alla-t-il quand les Lamanites étaient sur le point de détruire le pays ?", "À la colline de Shim", ["À la colline de Manti", "À la colline de Riplah"], ["colline de Shim"]),
  ),
  ch("morm", 5,
    q("a", "17", "Qui les Néphites avaient-ils jadis pour berger ?", "Le Christ pour berger", ["Moïse pour leur berger", "Néphi pour leur berger"], ["Christ pour berger"]),
    q("b", "18", "À quoi est comparé le peuple conduit par Satan ?", "À la balle emportée par le vent", ["À une brebis qui s’écarte du troupeau", "À de la poussière sur les montagnes"], ["balle"]),
    q("c", "22", "Que demande Mormon aux Gentils ?", "Comment ils subsisteront devant la puissance de Dieu", ["Comment ils pourront garder leur pays pour toujours", "Comment ils pourront accroître leur richesse"], ["devant la puissance de Dieu"]),
  ),
  ch("morm", 6,
    q("a", "4", "Dans quel pays les Néphites marchèrent-ils pour se rassembler ?", "Au pays de Cumorah", ["Au pays de Moroni", "Au pays de Josué"], ["Cumorah"]),
    q("b", "11", "Combien de gens de Mormon restèrent-ils après la bataille ?", "Vingt-quatre", ["Vingt-sept", "Vingt et un"], ["vingt-quatre"]),
    q("c", "3", "Comment le roi des Lamanites réagit-il à la demande de Mormon ?", "Il lui accorda ce qu’il désirait", ["Il refusa catégoriquement la demande", "Il fit brûler la lettre de Mormon"], ["accorda"]),
  ),
  ch("morm", 7,
    q("a", "2", "De quelle maison le reste du peuple est-il selon Mormon ?", "De la maison d’Israël", ["De la maison de Juda", "De la maison de David"], ["maison d’Israël"]),
    q("b", "4", "Que doivent-ils déposer selon Mormon ?", "Leurs armes de guerre", ["Leurs idoles d’or", "Leurs trésors d’argent"], ["armes de guerre"]),
    q("c", "8", "Au nom de qui doivent-ils être baptisés selon Mormon ?", "Au nom de Jésus", ["Au nom de Mormon", "Au nom de Néphi"], ["nom de Jésus"]),
  ),
  ch("morm", 8,
    q("a", "1", "Qui termine les annales de Mormon ?", "Moroni", ["Néphi", "Hélaman"], ["Moroni"]),
    q("b", "6", "Combien d’années étaient passées depuis la venue du Christ ?", "Quatre cents ans", ["Trois cents ans", "Cinq cents ans"], ["quatre cents"]),
    q("c", "23", "Quelles prophéties faut-il sonder selon Moroni ?", "Les prophéties d’Ésaïe", ["Les prophéties de Jérémie", "Les prophéties de Moïse"], ["prophéties d’Ésaïe"]),
  ),
  ch("morm", 9,
    q("a", "9", "Comment est Dieu selon Mormon ?", "Le même hier, aujourd’hui et à jamais", ["Changeant selon les temps et les peuples", "Présent seulement dans le temple"], ["hier, aujourd’hui et à jamais"]),
    q("b", "32", "Dans quels caractères Mormon et Moroni écrivirent-ils leurs annales ?", "L’égyptien réformé", ["L’ancien hébreu", "L’araméen syriaque"], ["égyptien réformé"]),
    q("c", "21", "Que promet Moroni à quiconque croit au Christ sans douter ?", "Tout ce qu’il demandera au Père, au nom du Christ", ["Une dispense de toutes les épreuves", "Une place dans tous les royaumes de la terre"], ["demandera au Père"]),
  ),
  ch("ether", 1,
    q("a", "2", "De combien de plaques Moroni tire-t-il son récit sur les anciens habitants détruits ?", "De vingt-quatre plaques", ["De douze plaques d’or", "De quarante-huit plaques"], ["vingt-quatre plaques"]),
    q("b", "34-35", "Que se passa-t-il avec la langue de Jared et de son frère à la grande tour ?", "Leur langue ne fut pas confondue", ["Leur langue fut en partie modifiée", "Leur langue fut entièrement remplacée"], ["confondu"]),
    q("c", "38,42", "Que promit le Seigneur au sujet du pays où il mènerait le frère de Jared ?", "Qu’il était préférable à tous les pays", ["Qu’il était plus fertile que l’Égypte", "Qu’il se trouvait près de la tour"], ["préférable"]),
  ),
  ch("ether", 2,
    q("a", "3", "Que signifie le mot déseret, que les Jarédites emportèrent ?", "Une abeille", ["Un campagnol", "Un lézard"], ["abeille"]),
    q("b", "14", "Combien de temps le Seigneur parla-t-il avec le frère de Jared en le réprimandant ?", "Pendant trois heures", ["Pendant sept heures", "Pendant deux heures"], ["trois heures"]),
    q("c", "17", "Comment les bateaux des Jarédites étaient-ils construits ?", "Étanches comme un plat", ["Étanches comme un tonneau", "Étanches comme une cruche"], ["étanches comme un plat"]),
  ),
  ch("ether", 3,
    q("a", "1", "Combien de petites pierres le frère de Jared fondit-il d’un rocher sur le mont Shélem ?", "Seize pierres", ["Douze pierres", "Dix-huit pierres"], ["seize"]),
    q("b", "4-6", "Comment le Seigneur fit-il briller les pierres quand le frère de Jared l’en pria ?", "Il les toucha du doigt", ["Il souffla sur elles", "Il les frappa d’un éclair"], ["doigt"]),
    q("c", "21-22", "Que devait faire le frère de Jared de ce qu’il avait vu et entendu ?", "L’écrire et le sceller", ["Le dire au peuple", "Le léguer à ses fils"], ["écri", "scell"]),
  ),
  ch("ether", 4,
    q("a", "1", "Quand ce que le frère de Jared écrivit pouvait-il parvenir aux enfants des hommes ?", "Après qu’il aurait été élevé sur la croix", ["Après que les Néphites auraient été détruits", "Après qu’il serait monté au ciel"], ["sur la croix"]),
    q("b", "3,5", "Que commanda le Seigneur à Moroni au sujet des annales du frère de Jared ?", "De les cacher de nouveau dans la terre", ["De les remettre aux Lamanites", "De les brûler avant qu’on les trouve"], ["cacher", "terre"]),
    q("c", "6-7", "Quand le Seigneur révélerait-il aux Gentils ce que le frère de Jared vit ?", "Quand ils se repentiront et feront preuve de foi", ["Quand ils auront terminé leurs guerres", "Quand ils auront trouvé eux-mêmes les plaques"], ["repenti", "foi"]),
  ),
  ch("ether", 5,
    q("a", "3", "À combien de témoins les plaques seraient-elles montrées par le pouvoir de Dieu ?", "À trois témoins", ["À douze témoins", "À sept témoins"], ["trois"]),
    q("b", "1", "Qu’était-il interdit de faire avec ce que Moroni avait scellé ?", "Personne ne devait le traduire", ["Personne ne devait le déplacer", "Personne ne devait le regarder"], ["traduire"]),
    q("c", "5", "Qu’arrive-t-il à celui qui se repent et vient au Père au nom de Jésus ?", "Il sera reçu dans le royaume de Dieu", ["Il reçoit le pouvoir d’ouvrir les plaques", "Il reçoit le don de traduire les plaques"], ["royaume de Dieu"]),
  ),
  ch("ether", 6,
    q("a", "11", "Combien de temps les Jarédites furent-ils poussés sur l’eau avant d’atteindre la terre promise ?", "Trois cent quarante-quatre jours", ["Trois cent soixante-cinq jours", "Cent quarante-deux jours"], ["trois cent quarante-quatre jours"]),
    q("b", "9", "Que fit le frère de Jared tout le jour pendant qu’ils étaient poussés sur les eaux ?", "Il chanta des louanges au Seigneur", ["Il monta la garde près des pierres", "Il lut à voix haute les annales"], ["louanges"]),
    q("c", "27", "Lequel des fils de Jared fut oint pour être roi du peuple ?", "Orihah, un fils de Jared", ["Gilgah, un fils de Jared", "Jacom, un fils de Jared"], ["Orihah"]),
  ),
  ch("ether", 7,
    q("a", "9", "Que fit Shule avec le minerai de la colline d’Éphraïm pour les hommes qu’il avait entraînés ?", "Des épées d’acier", ["Des lances de bronze", "Des casques de fer"], ["épées d’acier"]),
    q("b", "4", "Quel âge avait Corihor quand il se rebella contre son père Kib ?", "Trente-deux ans", ["Vingt et un ans", "Quarante-cinq ans"], ["trente-deux ans"]),
    q("c", "24-25", "Que fit le roi Shule pour les prophètes injuriés par le peuple ?", "Il leur donna le pouvoir d’aller où ils voulaient", ["Il leur donna des soldats pour les protéger partout", "Il les fit habiter une ville sous sa protection"], ["aller où ils voulaient"]),
  ),
  ch("ether", 8,
    q("a", "10-11", "Que fit la fille de Jared pour plaire à Akish, fils de Kimnor ?", "Elle dansa devant lui", ["Elle chanta devant lui", "Elle lui versa du vin"], ["dansa"]),
    q("b", "12", "Que demanda Jared à Akish en échange de sa fille ?", "La tête de son père, le roi", ["Une grande part de son or", "Les clés de la plus grande ville"], ["tête", "roi"]),
    q("c", "19", "Que dit Moroni au sujet du Seigneur et des combinaisons secrètes ?", "Le Seigneur n’agit pas par combinaisons secrètes", ["Le Seigneur s’en sert pour éprouver son peuple", "Le Seigneur les tolère seulement chez ses prophètes"], ["pas par combinaisons secrètes"]),
  ),
  ch("ether", 9,
    q("a", "3", "Comment Omer fut-il averti de quitter le pays ?", "Le Seigneur l’avertit en songe", ["Un ange lui apparut sur une montagne", "Un prophète lui parla à la porte"], ["songe"]),
    q("b", "22", "Qui le roi Emer vit-il, et s’en réjouit-il ?", "Le Fils de la justice", ["Un ange du Seigneur", "Un prophète du nord"], ["Fils de la justice"]),
    q("c", "35", "Que se passa-t-il après que le peuple se fut suffisamment humilié devant le Seigneur ?", "Le Seigneur envoya de la pluie sur la terre", ["Le Seigneur envoya la manne du ciel", "Le Seigneur fit disparaître les serpents"], ["pluie"]),
  ),
  ch("ether", 10,
    q("a", "5", "De quoi le roi Riplakish chargea-t-il le peuple ?", "De lourds impôts", ["D’un service armé", "De longues corvées"], ["lourds impôts"]),
    q("b", "20", "Où les Jarédites bâtirent-ils une grande ville du temps de Lib ?", "Près de la langue étroite de terre", ["Près de la colline de Shim", "Dans la vallée de Nimrod au bord du fleuve"], ["langue étroite de terre"]),
    q("c", "23", "Quels quatre métaux les Jarédites tiraient-ils de la terre du temps de Lib ?", "L’or, l’argent, le fer et l’airain", ["L’or, l’argent, l’étain et le plomb", "L’argent, le fer, l’étain et le zinc"], ["argent", "fer", "airain"]),
  ),
  ch("ether", 11,
    q("a", "5", "Que fit le frère de Shiblom des prophètes qui annonçaient la destruction du peuple ?", "Il les fit mettre à mort", ["Il les bannit dans le désert", "Il les fit emprisonner à Moron"], ["mettre à mort"]),
    q("b", "2", "Auprès de qui les prophètes s’enfuirent-ils pour avoir une protection ?", "Auprès du roi Com", ["Auprès du roi Omer", "Auprès du roi Shule"], ["Com"]),
    q("c", "20-21", "Que ferait le Seigneur Dieu du temps de Coriantor si le peuple ne se repentait pas ?", "Envoyer un autre peuple posséder le pays", ["Remplacer leur roi par un prophète", "Faire disparaître le pays sous la mer"], ["autre peuple"]),
  ),
  ch("ether", 12,
    q("a", "6", "Qu’est-ce que la foi selon Moroni ?", "Espérer des choses qu’on ne voit pas", ["Savoir avec certitude ce qu’on a déjà vu", "Croire ce qu’on peut prouver soi-même"], ["ne voit pas"]),
    q("b", "13", "Par la foi de qui la prison s’écroula-t-elle selon Moroni ?", "Celle d’Alma et d’Amulek", ["Celle d’Abinadi et de Limhi", "Celle d’Ammon et de ses frères"], ["Alma et d’Amulek"]),
    q("c", "30", "Que se passa-t-il quand le frère de Jared parla à la montagne Zérin ?", "La montagne fut déplacée", ["La montagne se fendit en deux", "La montagne se mit à trembler"], ["déplacée"]),
  ),
  ch("ether", 13,
    q("a", "6", "Pour qui une nouvelle Jérusalem serait-elle bâtie dans ce pays ?", "Pour le reste de la postérité de Joseph", ["Pour le reste de la postérité de Juda", "Pour les derniers disciples des Jarédites"], ["reste de la postérité", "Joseph"]),
    q("b", "13", "Où Éther se cachait-il le jour après que le peuple l’eut rejeté ?", "Dans la cavité d’un rocher", ["Dans une grotte près de la mer", "Dans un puits du désert"], ["cavité d’un rocher"]),
    q("c", "31", "Où Shared blessa-t-il Coriantumr, de sorte qu’il n’alla plus au combat pendant deux ans ?", "À la cuisse", ["À l’épaule", "Au poignet"], ["cuisse"]),
  ),
  ch("ether", 14,
    q("a", "10", "En quoi Lib surpassait-il les autres hommes du peuple ?", "Il était d’une grande stature", ["Il possédait le plus de richesses", "Il avait la plus grande armée"], ["grande stature"]),
    q("b", "17", "De qui Shiz, qui conquit et brûla beaucoup de villes, était-il le frère ?", "Le frère de Lib", ["Le frère de Shared", "Le frère de Com"], ["frère de Lib"]),
    q("c", "21-23", "Par quoi le peuple fut-il incommodé jour et nuit quand tout le pays était couvert de corps ?", "Par l’odeur des morts", ["Par des serpents venimeux", "Par un manque d’eau"], ["odeur"]),
  ),
  ch("ether", 15,
    q("a", "2", "Combien d’hommes puissants avaient déjà été tués quand Coriantumr commença à s’attrister ?", "Deux millions d’hommes", ["Quatre millions d’hommes", "Un demi-million d’hommes"], ["deux millions"]),
    q("b", "11", "Près de quelle colline l’armée de Coriantumr dressa-t-elle ses tentes ?", "La colline de Ramah", ["La colline de Shim", "La colline de Manti"], ["colline de Ramah"]),
    q("c", "30", "Que fit Coriantumr après s’être appuyé sur son épée pour se reposer ?", "Il coupa la tête de Shiz", ["Il se rendit à Shiz", "Il sonna de la trompette"], ["coupa la tête"]),
  ),
  ch("moro", 1,
    q("a", "3", "Pourquoi Moroni errait-il partout où il le pouvait ?", "Pour la sécurité de sa vie", ["Pour chercher de nouvelles plaques", "Pour convertir les Lamanites"], ["sécurité"]),
    q("b", "2", "Qui les Lamanites mettent-ils à mort dans leurs guerres selon Moroni ?", "Tout Néphite qui ne veut pas nier le Christ", ["Tout Néphite qui ne veut pas porter d’armes", "Tout Néphite qui ne veut pas rendre les plaques"], ["Néphite", "ne veut pas nier"]),
    q("c", "1", "Sur quel peuple Moroni venait-il de finir d’abréger l’histoire ?", "Le peuple de Jared", ["Le peuple de Limhi", "Le peuple d’Ammon"], ["peuple de Jared"]),
  ),
  ch("moro", 2,
    q("a", "1", "À qui le Christ dit-il les paroles qui se trouvent dans Moroni 2 ?", "Aux douze qu’il avait choisis", ["Aux soixante-dix qu’il avait choisis", "Aux trois qu’il avait choisis"], ["douze"]),
    q("b", "2", "Que pouvaient donner les disciples en imposant les mains ?", "Le Saint-Esprit", ["Le don des langues", "Le don de prophétie"], ["Saint-Esprit"]),
    q("c", "3", "Qui n’entendit pas les paroles du Christ lorsqu’il les prononça à sa première apparition ?", "La multitude présente", ["Les disciples présents", "Les instructeurs présents"], ["multitude"]),
  ),
  ch("moro", 3,
    q("a", "1", "Comment appelait-on les disciples qui ordonnaient les prêtres et les instructeurs ?", "Les anciens de l’Église", ["Les apôtres de l’Église", "Les surveillants de l’Église"], ["anciens de l’Église"]),
    q("b", "2", "Que faisaient d’abord les disciples avant d’imposer les mains pour ordonner quelqu’un ?", "Ils priaient le Père au nom du Christ", ["Ils lisaient les Écritures devant toute l’Église", "Ils demandaient à l’Église de donner son vote"], ["Père", "nom du Christ"]),
    q("c", "3", "Que devait prêcher celui qui était ordonné prêtre ou instructeur ?", "Le repentir et le pardon des péchés", ["Le rétablissement de l’Église du Christ", "L’alliance d’Abraham avec tous les peuples"], ["repentir et le pardon des péchés"]),
  ),
  ch("moro", 4,
    q("a", "3", "En souvenir de quoi mangeait-on le pain ?", "En souvenir du corps du Fils", ["En souvenir de la loi de Moïse", "En souvenir de la sortie d’Égypte"], ["souvenir du corps"]),
    q("b", "2", "Que faisaient l’ancien ou le prêtre et l’Église avant que le pain soit béni ?", "Ils s’agenouillaient et priaient le Père", ["Ils se levaient et chantaient un cantique", "Ils se taisaient et lisaient un psaume"], ["agenouill", "Père"]),
    q("c", "3", "Que demandaient-ils à Dieu de faire du pain ?", "Le bénir et le sanctifier", ["L’apporter aux malades", "Le partager entre tous les présents"], ["sanctifier"]),
  ),
  ch("moro", 5,
    q("a", "2", "En souvenir de quoi buvait-on le vin ?", "En souvenir du sang du Fils", ["En souvenir de l’alliance avec Abraham", "En souvenir de la loi de Moïse"], ["souvenir du sang"]),
    q("b", "1", "Qu’est-ce qu’ils prenaient en main lorsque le vin était béni ?", "Une coupe", ["Une cruche", "Une jarre"], ["coupe"]),
    q("c", "2", "Comment s’adressaient-ils à Dieu dans la prière sur le vin ?", "Ô Dieu, Père éternel", ["Ô Dieu, Roi d’Israël", "Ô Seigneur, Rédempteur"], ["Père éternel"]),
  ),
  ch("moro", 6,
    q("a", "2", "Dans quel état d’esprit devait-on venir au baptême ?", "Le cœur brisé et l’esprit contrit", ["Les mains purifiées et le cœur pur", "Une grande foi et un solide témoignage"], ["cœur brisé", "esprit contrit"]),
    q("b", "5", "Pourquoi les membres de l’Église se réunissaient-ils souvent, en plus de parler du bien-être de leur âme ?", "Pour jeûner et pour prier", ["Pour travailler et récolter", "Pour voyager et faire du commerce"], ["jeûner"]),
    q("c", "7", "Combien de témoins de l’Église devaient condamner quelqu’un devant les anciens ?", "Trois témoins", ["Deux témoins", "Sept témoins"], ["trois témoins"]),
  ),
  ch("moro", 7,
    q("a", "47", "Qu’est-ce que la charité selon Mormon ?", "L’amour pur du Christ lui-même", ["Le plus haut degré de dévouement", "L’amour que l’on reçoit des autres"], ["amour pur du Christ"]),
    q("b", "11", "Quelle image Mormon utilise-t-il pour montrer qu’un homme mauvais ne peut rien faire de bon ?", "Une source amère qui ne donne pas de bonne eau", ["Un puits sec qui ne donne pas d’eau", "Une mauvaise récolte qui ne donne pas de blé"], ["source amère"]),
    q("c", "16", "Qu’est-ce qui est donné à tout homme pour discerner le bien du mal ?", "L’Esprit du Christ", ["Le don de prophétie", "La loi de Moïse"], ["Esprit du Christ"]),
  ),
  ch("moro", 8,
    q("a", "4-5", "À propos de quoi des controverses s’étaient-elles élevées, à la peine de Mormon ?", "Le baptême des petits enfants", ["L’ordination des instructeurs", "La manière d’imposer les mains"], ["baptême", "petits enfants"]),
    q("b", "12", "Pourquoi les petits enfants n’ont-ils pas besoin du baptême selon Mormon ?", "Ils sont vivants dans le Christ", ["Ils sont déjà baptisés par l’esprit", "Ils sont trop jeunes pour souffrir"], ["vivants dans le Christ"]),
    q("c", "25", "Que Mormon appelle-t-il les prémices du repentir ?", "Le baptême, qui vient par la foi", ["Le pardon de tous les péchés", "La douceur et l’humilité du cœur"], ["baptême"]),
  ),
  ch("moro", 9,
    q("a", "2", "Quels hommes étaient tombés par l’épée dans le combat contre les Lamanites selon Mormon ?", "Archéantus, Luram et Emron", ["Amoron, Zénéphi et Archéantus", "Luram, Aaron et Zénéphi"], ["Archéantus", "Luram", "Emron"]),
    q("b", "4", "Que font les gens quand Mormon dit la parole de Dieu avec rigueur ?", "Ils tremblent et sont en colère", ["Ils tombent à genoux et prient", "Ils se taisent et rentrent chez eux"], ["tremblent", "colère"]),
    q("c", "22", "Que priait Mormon pour son fils Moroni ?", "Que Dieu lui épargne la vie", ["Qu’il vainque les Lamanites", "Qu’il conduise bientôt une armée"], ["épargne la vie"]),
  ),
  ch("moro", 10,
    q("a", "4", "Qu’est-ce que Moroni exhorte les lecteurs à demander à Dieu ?", "Si ces choses ne sont pas vraies", ["Si les Lamanites se repentiront", "S’ils peuvent traduire les plaques"], ["ne sont pas vraies"]),
    q("b", "17", "Quelle est la source de tous ces dons selon Moroni ?", "L’Esprit du Christ", ["Le pouvoir de l’Église", "La loi de Moïse"], ["Esprit du Christ"]),
    q("c", "20-21", "Quelles trois choses faut-il avoir pour être sauvé dans le royaume de Dieu ?", "La foi, l’espérance et la charité", ["La foi, le jeûne et la simplicité", "L’espérance, la patience et l’obéissance"], ["foi", "espérance", "charité"]),
  ),
  // ===== EINDE =====
];
