import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 1 Nephi (deutsche Ausgabe). Jede Tatsache ist an die Verse in `verses` gebunden; `npm run genees:check` prüft das.
export const nephi1: GeneesChapterSeed[] = [
  ch("1-ne", 1,
    q("a", "5-6", "Was erschien Lehi auf einem Felsen, als er zum Herrn betete?", "Eine Feuersäule", ["Eine weiße Wolke", "Ein leuchtender Stern"], ["Feuersäule"]),
    q("b", "4", "Zu Beginn des ersten Regierungsjahres welches Königs von Juda kamen viele Propheten?", "König Zidkija", ["König Joschija", "König Jojakim"], ["Zidkija"]),
    q("c", "11", "Was gab der Erste der Zwölf in Lehis Vision ihm zu lesen?", "Ein Buch", ["Einen Stab", "Ein Schwert"], ["Buch"]),
  ),
  ch("1-ne", 2,
    q("a", "2", "Was gebot der Herr Lehi in einem Traum?", "Mit seiner Familie in die Wildnis zu ziehen", ["Mit seiner Familie nach Babylon zu fliehen", "Mit seiner Familie nach Süden zu segeln"], ["Wildnis"]),
    q("b", "8", "Welchen Namen gab Lehi dem Fluss, der ins Rote Meer mündete?", "Der Fluss Laman", ["Der Fluss Sam", "Der Fluss Jordan"], ["Laman"]),
    q("c", "20", "Was verhieß der Herr Nephi, wenn er die Gebote hielte?", "Dass er in ein Land der Verheißung geführt würde", ["Dass er binnen drei Tagen wieder in Jerusalem wäre", "Dass er mit seinen Brüdern eine große Stadt bauen würde"], ["Land der Verheißung"]),
  ),
  ch("1-ne", 3,
    q("a", "3", "Worauf waren die Aufzeichnungen der Juden, die Laban besaß, graviert?", "Auf Platten aus Messing", ["Auf Platten aus Gold", "Auf Tafeln aus Stein"], ["Platten aus Messing"]),
    q("b", "11", "Wer ging als Erster in Labans Haus, nachdem das Los geworfen war?", "Laman", ["Lemuel", "Nephi"], ["Laman"]),
    q("c", "29", "Wer erschien, als Laman und Lemuel ihre jüngeren Brüder mit einer Rute schlugen?", "Ein Engel des Herrn", ["Ein Diener Labans", "Ein Prophet aus Juda"], ["Engel des Herrn"]),
  ),
  ch("1-ne", 4,
    q("a", "18", "Womit tötete Nephi Laban?", "Mit seinem eigenen Schwert", ["Mit einem Speer aus Messing", "Mit einer schweren Keule"], ["eigenen Schwert"]),
    q("b", "35", "Wie hieß der Diener Labans?", "Zoram", ["Serach", "Zenos"], ["Zoram"]),
    q("c", "7", "In welchem Zustand befand sich Laban, als Nephi ihn fand?", "Er war zu Boden gefallen, vom Wein trunken", ["Er war von einer Krankheit geschwächt", "Er war in einem Kampf verwundet worden"], ["vom Wein trunken"]),
  ),
  ch("1-ne", 5,
    q("a", "11", "Was enthielten die Platten aus Messing unter anderem, als Lehi sie untersuchte?", "Die fünf Bücher Mose", ["Die Psalmen König Davids", "Die Gesetze König Salomos"], ["fünf Bücher Mose"]),
    q("b", "14", "Von welchem Sohn Jakobs war Lehi ein Nachkomme?", "Josef", ["Ruben", "Simeon"], ["Josef"]),
    q("c", "2", "Welchen Vorwurf machte Sariah ihrem Mann, als ihre Söhne nicht zurückkehrten?", "Er sei ein Mann mit Visionen", ["Er habe zu wenig Vorräte mitgenommen", "Er habe den falschen Weg gewählt"], ["Mann mit Visionen"]),
  ),
  ch("1-ne", 6,
    q("a", "4", "Zu welchem Gott will Nephi die Menschen bewegen zu kommen?", "Zum Gott Abrahams, Isaaks und Jakobs", ["Zum Gott Adams, Noahs und Moses", "Zum Gott Henochs, Davids und Salomos"], ["Abrahams", "Isaaks", "Jakobs"]),
    q("b", "5", "Welche Dinge schreibt Nephi nicht auf seine Platten?", "Dinge, die der Welt gefallen", ["Dinge über seine älteren Brüder", "Dinge über Kriege und Kämpfe"], ["Welt"]),
    q("c", "1", "Wo steht die Stammtafel von Nephis Vätern?", "In dem Bericht, den sein Vater Lehi geführt hat", ["Auf den Platten, auf die Nephi jetzt schreibt", "In dem Bericht des Propheten Jeremia"], ["Bericht", "Vater"]),
  ),
  ch("1-ne", 7,
    q("a", "2", "Wen sollten Nephi und seine Brüder aus Jerusalem herabholen?", "Ischmael und seine Familie", ["Jeremia und seine Familie", "Zidkija und seine Familie"], ["Ischmael"]),
    q("b", "16", "Was taten Laman und Lemuel mit Nephi, nachdem er zu ihnen gesprochen hatte?", "Sie banden ihn mit Stricken", ["Sie schlugen ihn mit einer Rute", "Sie sperrten ihn in eine Höhle"], ["Stricken"]),
    q("c", "21", "Was tat Nephi, als seine Brüder ihn um Vergebung baten?", "Er vergab ihnen freimütig alles, was sie getan hatten", ["Er verlangte, dass sie ihre Schwerter abgaben", "Er ließ sie zuerst einen Tag lang fasten"], ["freimütig"]),
  ),
  ch("1-ne", 8,
    q("a", "19", "Was für eine Stange führte am Ufer des Flusses entlang zum Baum?", "Eine eiserne Stange", ["Eine hölzerne Stange", "Eine messingene Stange"], ["eiserne Stange"]),
    q("b", "12", "Was geschah mit Lehi, als er von der Frucht aß?", "Seine Seele wurde mit überaus großer Freude erfüllt", ["Sein Körper wurde von aller Müdigkeit geheilt", "Sein Herz wurde mit großer Trauer um Laman erfüllt"], ["großer Freude"]),
    q("c", "26", "Wo stand das große und geräumige Gebäude, das Lehi sah?", "Hoch in der Luft über der Erde", ["Tief in einem Tal neben dem Fluss", "Auf dem Gipfel eines bewaldeten Berges"], ["in der Luft"]),
  ),
  ch("1-ne", 9,
    q("a", "3-4", "Wovon handeln die Platten, auf die Nephi jetzt schreibt, hauptsächlich?", "Vom geistlichen Dienst unter seinem Volk", ["Von der Regierung der Könige und von Kriegen", "Von der Reise seiner Familie über das Meer"], ["geistlichen Dienst"]),
    q("b", "1", "In welchem Tal wohnte Lehi in einem Zelt, als er all dies sah?", "Im Tale Lemuel", ["Im Tale Laman", "Im Tale Zoram"], ["Tale Lemuel"]),
    q("c", "5", "Warum gebot der Herr Nephi, diese Platten anzufertigen?", "In seiner weisen Absicht, die Nephi nicht kannte", ["Weil die anderen Platten verloren gegangen waren", "Weil Lehi selbst darum gebeten hatte"], ["weisen Absicht"]),
  ),
  ch("1-ne", 10,
    q("a", "4", "Wie viele Jahre nachdem Lehi Jerusalem verlassen hatte, sollte der Messias kommen?", "Sechshundert Jahre", ["Dreihundert Jahre", "Tausend Jahre"], ["sechshundert Jahre"]),
    q("b", "9", "Wo würde der Prophet taufen, der dem Herrn den Weg bereitet?", "In Betabara, jenseits des Jordans", ["In Jerusalem, beim Tempel des Herrn", "In Nazaret, am Ufer des Roten Meeres"], ["Betabara"]),
    q("c", "12", "Womit verglich Lehi das Haus Israel?", "Mit einem Ölbaum", ["Mit einem Weinstock", "Mit einem Feigenbaum"], ["Ölbaum"]),
  ),
  ch("1-ne", 11,
    q("a", "1", "Wohin wurde Nephi im Geist des Herrn hinweggeführt?", "Auf einen überaus hohen Berg", ["In eine weite Ebene am Meer", "In ein Tal voller reifer Bäume"], ["überaus hohen Berg"]),
    q("b", "18", "Wer ist laut dem Engel die Jungfrau, die Nephi sah?", "Die Mutter des Sohnes Gottes", ["Die Schwester des Propheten Jeremia", "Die Frau des Königs von Juda"], ["Mutter des Sohnes Gottes"]),
    q("c", "22", "Wofür steht der Baum laut Nephi?", "Für die Liebe Gottes zu den Menschenkindern", ["Für die Weisheit der großen Welt", "Für die Macht eines starken Königreichs"], ["Liebe Gottes"]),
  ),
  ch("1-ne", 12,
    q("a", "1", "Womit wird die Zahl der Menschen in Nephis Nachkommenschaft verglichen?", "Mit dem Sand am Meer", ["Mit den Sternen am Himmel", "Mit den Blättern der Bäume"], ["Sand am Meer"]),
    q("b", "7-8", "Wie viele Jünger des Lammes wurden erwählt, Nephis Nachkommen zu dienen?", "Zwölf", ["Sieben", "Siebzig"], ["zwölf"]),
    q("c", "17", "Wofür stehen die Nebel von Finsternis laut dem Engel?", "Für die Versuchungen des Teufels", ["Für die Mühen der Reise", "Für die Zweifel der Gläubigen"], ["Versuchungen des Teufels"]),
  ),
  ch("1-ne", 13,
    q("a", "23", "Was enthält das Buch, das aus dem Mund eines Juden hervorkommt, laut dem Engel?", "Die Bündnisse des Herrn mit dem Haus Israel", ["Die Gesetze aller Völker auf der ganzen Erde", "Die Geschichte der Könige des Landes Ägypten"], ["Bündnisse des Herrn", "Haus Israel"]),
    q("b", "12", "Wohin fuhr der Mann unter den Anderen, auf den der Geist Gottes einwirkte?", "Über die vielen Wasser zum verheißenen Land", ["Durch die Wüste zur Stadt Jerusalem hinauf", "Über die Berge in das Land Ägypten hinab"], ["vielen Wasser", "verheißenen Land"]),
    q("c", "37", "Was werden die haben, die in den Letzten Tagen danach trachten, Zion hervorzubringen?", "Die Gabe und die Macht des Heiligen Geistes", ["Den Reichtum und die Ehre der Welt", "Die Weisheit und die Autorität der Könige"], ["Gabe und die Macht des Heiligen Geistes"]),
  ),
  ch("1-ne", 14,
    q("a", "27", "Wie hieß der Apostel des Lammes, der diese Dinge aufschreiben sollte?", "Johannes", ["Petrus", "Matthäus"], ["Johannes"]),
    q("b", "10", "Wie viele Kirchen gibt es laut dem Engel?", "Nur zwei", ["Nur vier", "Nur sieben"], ["nur zwei"]),
    q("c", "12", "Wie war die Mitgliederzahl der Kirche des Lammes Gottes in Nephis Vision?", "Klein, aber über die ganze Erde verstreut", ["Groß, aber auf ein einziges Land beschränkt", "So groß wie die der anderen Kirche"], ["klein"]),
  ),
  ch("1-ne", 15,
    q("a", "24", "Was bedeutet die eiserne Stange laut Nephi?", "Das Wort Gottes selbst", ["Das Gesetz des Mose", "Die Macht eines Königs"], ["Wort Gottes"]),
    q("b", "8-9", "Was hatten Laman und Lemuel nicht getan, um die Worte ihres Vaters zu verstehen?", "Sie hatten den Herrn nicht darüber befragt", ["Sie hatten kein Opfer auf einem Altar gebracht", "Sie hatten die Messingplatten nicht gelesen"], ["befragt"]),
    q("c", "18", "Mit welchem Vorvater schloss der Herr den Bund, der in den Letzten Tagen erfüllt wird?", "Abraham", ["Henoch", "Salomo"], ["Abraham"]),
  ),
  ch("1-ne", 16,
    q("a", "10", "Woraus bestand die kunstvoll gearbeitete Kugel, die Lehi vor seinem Zelt fand?", "Aus feinem Messing", ["Aus feinem Gold", "Aus gehärtetem Stahl"], ["feinem Messing"]),
    q("b", "13", "Wie hieß der Ort, an dem die Familie nach vier Tagen Wanderung ihre Zelte aufschlug?", "Schazer", ["Lemuel", "Jerschon"], ["Schazer"]),
    q("c", "18", "Was geschah, als Nephi hinausging, um Nahrung zu erjagen?", "Sein Bogen aus feinem Stahl zerbrach", ["Alle seine Pfeile waren aufgebraucht", "Er verirrte sich in der Wildnis"], ["Bogen", "feinem Stahl"]),
  ),
  ch("1-ne", 17,
    q("a", "5", "Wie nannten sie das Meer, das sie erblickten, und was bedeutet der Name?", "Irreantum, was viele Wasser heißt", ["Überfluss, was viele Früchte heißt", "Schazer, was rote Wasser heißt"], ["Irreantum", "viele Wasser"]),
    q("b", "4", "Wie viele Jahre weilte die Familie in der Wildnis?", "Acht Jahre", ["Vier Jahre", "Zwölf Jahre"], ["acht Jahre"]),
    q("c", "11", "Woraus machte Nephi einen Blasebalg, um das Feuer anzublasen?", "Aus Tierhaut", ["Aus Schafwolle", "Aus Baumrinde"], ["Tierhaut"]),
  ),
  ch("1-ne", 18,
    q("a", "7", "Wie hießen die beiden Söhne, die Lehi in der Wildnis gezeugt hatte?", "Jakob und Joseph", ["Enos und Jarom", "Zoram und Sam"], ["Jakob", "Joseph"]),
    q("b", "12", "Was geschah mit dem Kompass, nachdem Nephi gebunden worden war?", "Er hörte auf zu arbeiten", ["Er zeigte in die falsche Richtung", "Er ging im Sturm verloren"], ["arbeiten"]),
    q("c", "15", "Wie viele Tage waren sie zurückgetrieben worden, als Nephis Brüder einzusehen begannen, dass Gottes Strafgerichte über ihnen waren?", "Vier Tage", ["Zwei Tage", "Sieben Tage"], ["vier Tage"]),
  ),
  ch("1-ne", 19,
    q("a", "1", "Woraus machte Nephi die Platten, um den Bericht seines Volkes einzugravieren?", "Aus Erz", ["Aus Silber", "Aus Holz"], ["Erz"]),
    q("b", "12", "Welcher Prophet sagt, dass der Gott der Natur leidet?", "Zenos", ["Zenock", "Neum"], ["Zenos"]),
    q("c", "23", "Welchen Propheten las Nephi seinen Brüdern vor, um sie zum Glauben an den Herrn zu bewegen?", "Jesaja", ["Jeremia", "Ezechiel"], ["Jesaja"]),
  ),
  ch("1-ne", 20,
    q("a", "4", "Woraus ist die Stirn des Volkes Israel laut dem Herrn?", "Sie ist ehern", ["Sie ist steinern", "Sie ist golden"], ["ehern"]),
    q("b", "18", "Wem wäre Israels Rechtschaffenheit gleich gewesen, wenn es die Gebote befolgt hätte?", "Den Wogen des Meeres", ["Den Bergen Judas", "Den Sternen am Himmel"], ["Wogen des Meeres"]),
    q("c", "20", "Woraus sollte das Volk laut dem Herrn ausziehen?", "Aus Babylon", ["Aus Ägypten", "Aus Assyrien"], ["Babylon"]),
  ),
  ch("1-ne", 21,
    q("a", "16", "Worauf hat der Herr das Haus Israel gezeichnet, wie er sagt?", "Auf die Flächen seiner Hände", ["Auf eine Tafel aus Stein", "Auf die Mauern des Tempels"], ["Flächen"]),
    q("b", "6", "Wozu macht der Herr seinen Diener auch für die Anderen?", "Zu einem Licht", ["Zu einem Richter", "Zu einem König"], ["Licht"]),
    q("c", "14", "Was sagte Zion über den Herrn?", "Der Herr habe sie verlassen", ["Der Herr werde ihr nie vergeben", "Der Herr habe sie zur Königin gemacht"], ["verlassen"]),
  ),
  ch("1-ne", 22,
    q("a", "20-21", "Wer war laut Nephi der Prophet, von dem Mose sprach?", "Der Heilige Israels selbst", ["Jesaja, der Sohn des Amoz", "Lehi, der Vater Nephis"], ["Heilige Israels"]),
    q("b", "25", "Wie viele Herden und Hirten wird es geben, wenn der Herr seine Kinder sammelt?", "Eine Herde und einen Hirten", ["Zwölf Herden und zwölf Hirten", "Sieben Herden und einen Hirten"], ["Herde", "Hirte"]),
    q("c", "30", "Wovon zeugen laut Nephi die Dinge auf den Platten aus Messing?", "Dass der Mensch die Gebote Gottes beachten muss", ["Dass der Mensch seinen Besitz den Armen geben muss", "Dass der Mensch jeden siebten Tag im Tempel opfern muss"], ["Gebote Gottes beachten"]),
  ),
  // ===== EINDE =====
];
