import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 2 Nephi (deutsche Ausgabe). Jede Tatsache ist an die Verse in `verses` gebunden; `npm run genees:check` prüft das.
export const nephi2: GeneesChapterSeed[] = [
  ch("2-ne", 1,
    q("a", "6", "Wer wird laut Lehi in dieses Land gelangen?", "Nur wer durch die Hand des Herrn geführt wird", ["Nur wer ein eigenes Schiff selbst bauen kann", "Nur wer eine Erlaubnis des Königs erhalten hat"], ["Hand des Herrn"]),
    q("b", "30", "Wie hieß der Diener Labans, den Lehi einen treuen Freund Nephis nannte?", "Zoram", ["Jakob", "Ischmael"], ["Zoram"]),
    q("c", "13", "Woraus sollten seine Söhne laut Lehi erwachen?", "Aus einem tiefen Schlaf", ["Aus einer langen Reise", "Aus einer schweren Krankheit"], ["tiefen Schlaf"]),
  ),
  ch("2-ne", 2,
    q("a", "25", "Warum gibt es Menschen, laut Lehi?", "Damit sie Freude haben können", ["Damit sie über die Erde herrschen", "Damit sie Reichtum erwerben"], ["Freude"]),
    q("b", "16", "Was hat Gott, der Herr, dem Menschen gewährt?", "Dass er für sich selbst handeln darf", ["Dass er ohne Gesetz leben darf", "Dass er ein eigenes Königreich gründen darf"], ["für sich selbst"]),
    q("c", "19", "Warum wurden Adam und Eva aus dem Garten von Eden vertrieben?", "Um die Erde zu bebauen", ["Um eine Stadt zu gründen", "Um in der Wildnis zu wohnen"], ["Erde zu bebauen"]),
  ),
  ch("2-ne", 3,
    q("a", "17", "Worin würde der Herr dem kommenden Mose Macht geben, laut Josefs Prophezeiung?", "In einem Stab", ["In einem Schwert", "In einem Zepter"], ["Stab"]),
    q("b", "6", "Was würde der Herr laut Josef für die Frucht seiner Lenden erwecken?", "Einen erwählten Seher", ["Einen mächtigen König", "Einen gerechten Richter"], ["Seher"]),
    q("c", "1", "Welchen Platz unter Lehis Kindern hatte Josef, zu dem Lehi sprach?", "Er war der Letztgeborene", ["Er war der Erstgeborene", "Er war der zweite Sohn"], ["Letztgeborene"]),
  ),
  ch("2-ne", 4,
    q("a", "12", "Was geschah mit Lehi, nachdem er zu seinem ganzen Haushalt gesprochen hatte?", "Er starb und wurde begraben", ["Er erkrankte und zog sich zurück", "Er wurde in den Himmel aufgenommen"], ["starb"]),
    q("b", "11", "Welchem Sohn sagte Lehi, dass er das Land ererben werde wie Nephi?", "Seinem Sohn Sam", ["Seinem Sohn Laman", "Seinem Sohn Josef"], ["Sam"]),
    q("c", "15", "Woran erfreut sich Nephis Seele, wie er schreibt?", "An den Schriften auf den Platten aus Messing", ["An den Siegen über seine Feinde im Krieg", "An den Reichtümern des verheißenen Landes"], ["Schriften"]),
  ),
  ch("2-ne", 5,
    q("a", "28", "Wie viele Jahre waren vergangen, seit sie Jerusalem verlassen hatten?", "Dreißig Jahre", ["Zwanzig Jahre", "Fünfzig Jahre"], ["dreißig Jahre"]),
    q("b", "16", "Nach dem Muster welches Tempels baute Nephi einen Tempel?", "Des Tempels Salomos", ["Des Tempels des Mose", "Des Tempels Zidkijas"], ["Tempels Salomos"]),
    q("c", "26", "Wen weihte Nephi zu Priestern und Lehrern über sein Volk?", "Jakob und Joseph", ["Sam und Zoram", "Laman und Lemuel"], ["Jakob", "Joseph"]),
  ),
  ch("2-ne", 6,
    q("a", "4", "Wessen Worte las Jakob dem Volk vor?", "Jesaja", ["Jeremia", "Hosea"], ["Jesaja"]),
    q("b", "2", "Von wem war Jakob geweiht worden?", "Von seinem Bruder Nephi", ["Von seinem Vater Lehi", "Vom König von Juda"], ["Bruder Nephi"]),
    q("c", "14", "Wie oft wird der Messias sich laut Jakob aufmachen, um sein Volk zurückzugewinnen?", "Zum zweiten Mal", ["Zum dritten Mal", "Zum siebten Mal"], ["zweiten Mal"]),
  ),
  ch("2-ne", 7,
    q("a", "8", "Womit wird der Herr seinen Gegner schlagen?", "Mit der Stärke seines Mundes", ["Mit einem scharfen Schwert aus Stahl", "Mit dem Feuer des Himmels"], ["Mundes"]),
    q("b", "7", "Wem hat der Herr sein Angesicht gleich gemacht?", "Einem harten Kieselstein", ["Einem Felsen im Meer", "Einem stählernen Schild"], ["Kieselstein"]),
    q("c", "3", "In welcher Farbe kleidet der Herr die Himmel?", "In Schwärze gehüllt", ["In Weiß gehüllt", "In Purpur gehüllt"], ["Schwärze"]),
  ),
  ch("2-ne", 8,
    q("a", "2", "An welchen Vater und welche Mutter soll das Volk laut Jesaja denken?", "Abraham und Sara", ["Isaak und Rebekka", "Jakob und Rahel"], ["Abraham", "Sara"]),
    q("b", "3", "Wem wird der Herr die Wildnis Zions gleich machen?", "Wie Eden", ["Wie Bethel", "Wie Sinai"], ["Eden"]),
    q("c", "1", "Woraus ist das Volk, das der Rechtschaffenheit nachfolgt, laut Jesaja gehauen?", "Aus dem Fels", ["Aus dem Fluss", "Aus der Wüste"], ["Fels"]),
  ),
  ch("2-ne", 9,
    q("a", "10", "Wie nennt Jakob den Tod und die Hölle?", "Ein furchtbares Ungeheuer", ["Eine hohe Festungsmauer", "Einen tiefen Abgrund"], ["Ungeheuer"]),
    q("b", "41", "Wer ist laut Jakob der Hüter des Tores des schmalen Weges?", "Der Heilige Israels", ["Der Prophet Jesaja", "Der Engel des Herrn"], ["Heilige Israels"]),
    q("c", "25", "Was gibt es laut Jakob, wo kein Gesetz gegeben ist?", "Keine Strafe", ["Keine Erlösung", "Keine Hoffnung"], ["keine Strafe"]),
  ),
  ch("2-ne", 10,
    q("a", "3", "Welcher Name sollte laut dem Engel der Name des Messias sein?", "Christus", ["Immanuel", "Josua"], ["Christus"]),
    q("b", "11", "Wer wird laut dem Herrn in diesem Land der Freiheit nicht sein?", "Könige, die sich über andere erheben", ["Priester, die täglich im Tempel dienen", "Bauern, die das Land mit ihren Händen bestellen"], ["Könige"]),
    q("c", "23", "Zwischen welchen zwei Wegen dürfen die Menschen laut Jakob wählen?", "Der Weg des immerwährenden Todes oder des ewigen Lebens", ["Der Weg des Reichtums oder der Armut im verheißenen Land", "Der Weg des Krieges oder des Friedens mit dem Volk Lamans"], ["immerwährenden Todes", "ewigen Lebens"]),
  ),
  ch("2-ne", 11,
    q("a", "2", "Wessen Worte schreibt Nephi noch mehr auf?", "Die Worte Jesajas", ["Die Worte Jeremias", "Die Worte des Zenos"], ["Jesajas"]),
    q("b", "7", "Was sagt Nephi, wenn es keinen Christus gäbe?", "Dann gäbe es keinen Gott", ["Dann gäbe es keinen Tempel", "Dann gäbe es keinen Propheten"], ["keinen Gott"]),
    q("c", "4", "Wozu ist laut Nephi das Gesetz des Mose gegeben worden?", "Um die Wahrheit des Kommens Christi zu beweisen", ["Um das Volk mit Gottes Hilfe aus Ägypten zu befreien", "Um den Tempel in Jerusalem zu bauen und zu weihen"], ["Kommens Christi"]),
  ),
  ch("2-ne", 12,
    q("a", "4", "Wozu werden die Nationen ihre Schwerter laut Jesaja umschmieden?", "Zu Pflugscharen", ["Zu Schilden", "Zu Kochtöpfen"], ["Pflugscharen"]),
    q("b", "2", "Wo wird das Haus des Herrn in den Letzten Tagen stehen?", "Zu Häupten der Berge", ["Im tiefsten Tal Judas", "Am Ufer des großen Meeres"], ["Häupten der Berge"]),
    q("c", "7", "Wovon war das Land Juda laut Jesaja voll?", "Von Silber und Gold", ["Von Getreide und Olivenöl", "Von Schafen und Ziegen"], ["Silber und Gold"]),
  ),
  ch("2-ne", 13,
    q("a", "16", "Warum wird der Herr die Töchter Zions bestrafen?", "Weil sie hochmütig geworden sind", ["Weil sie den Sabbat nicht heiligen", "Weil sie den Tempel verlassen haben"], ["hochmütig"]),
    q("b", "9", "Mit welcher Stadt vergleicht Jesaja die Sünde Judas?", "Mit Sodom", ["Mit Babylon", "Mit Ninive"], ["Sodom"]),
    q("c", "10", "Was werden die Rechtschaffenen laut Jesaja genießen?", "Die Früchte ihres Tuns", ["Das Brot des Königs", "Die Beute des Feindes"], ["Früchte ihres Tuns"]),
  ),
  ch("2-ne", 14,
    q("a", "1", "Wie viele Frauen werden an jenem Tag einen Mann festhalten, laut Jesaja?", "Sieben Frauen", ["Zwölf Frauen", "Zehn Frauen"], ["sieben Frauen"]),
    q("b", "5", "Was wird der Herr über dem Berg Zion bei Nacht schaffen?", "Einen lichten Feuerschein", ["Eine große dunkle Staubwolke", "Einen Regen aus Silbersternen"], ["Feuerschein"]),
    q("c", "6", "Was wird es als Schatten vor der Hitze bei Tag geben?", "Eine Schirmhütte", ["Einen hohen Turm", "Eine breite Mauer"], ["Schirmhütte"]),
  ),
  ch("2-ne", 15,
    q("a", "1", "Worüber singt Jesaja ein Lied?", "Über einen Weingarten auf einem Hügel", ["Über einen Schafstall im grünen Tal", "Über eine Stadt am großen Fluss"], ["Weingarten"]),
    q("b", "7", "Was ist der Weingarten des Herrn der Heerscharen?", "Das Haus Israel selbst", ["Der Tempel Salomos", "Die Stadt des Königs"], ["Haus Israel"]),
    q("c", "20", "Über wen ruft Jesaja in Vers 20 „Weh“ aus?", "Über die, die Böses gut nennen", ["Über die, die am Sabbat ruhen", "Über die, die den Armen helfen"], ["Böses gut"]),
  ),
  ch("2-ne", 16,
    q("a", "2", "Wie viele Flügel hatte jeder Serafim?", "Sechs Flügel", ["Vier Flügel", "Acht Flügel"], ["sechs Flügel"]),
    q("b", "6-7", "Womit berührte der Serafim Jesajas Lippen?", "Mit einer glühenden Kohle", ["Mit einer brennenden Fackel", "Mit einem heißen Stein"], ["Kohle"]),
    q("c", "8", "Was sagte Jesaja, als der Herr fragte, wen er senden solle?", "Hier bin ich, sende mich", ["Ich bin nicht würdig", "Sende meinen Bruder"], ["Hier bin ich"]),
  ),
  ch("2-ne", 17,
    q("a", "14", "Welchen Namen wird der Sohn der Jungfrau laut Jesaja erhalten?", "Immanuel", ["Jeremia", "Jehoram"], ["Immanuel"]),
    q("b", "1", "In den Tagen welches Königs von Juda zogen Rezin und Pekach gegen Jerusalem?", "Ahas, des Sohnes Jotams", ["Hiskija, des Sohnes Ahas’", "Manasse, des Sohnes Hiskijas"], ["Ahas"]),
    q("c", "11", "Was durfte Ahas vom Herrn fordern?", "Ein Zeichen", ["Ein Heer", "Ein Schiff"], ["Zeichen"]),
  ),
  ch("2-ne", 18,
    q("a", "3", "Welchen Namen sollte der Sohn Jesajas laut dem Herrn erhalten?", "Maher-Schalal-Hasch-Bas", ["Schear-Jaschub Ben Amoz", "Maher-Immanuel Ben Isai"], ["Maher-Schalal-Hasch-Bas"]),
    q("b", "13", "Wen sollen wir laut dem Herrn allein heiligen?", "Den Herrn der Heerscharen", ["Den König von Assyrien", "Den Propheten Jesaja selbst"], ["Heerscharen"]),
    q("c", "7", "Wer ist mit den mächtigen und vielen Wassern des Flusses gemeint?", "Der König von Assyrien", ["Der König von Ägypten", "Der König von Syrien"], ["König von Assyrien"]),
  ),
  ch("2-ne", 19,
    q("a", "6", "Wie wird das Kind, das uns geboren ist, unter anderem genannt?", "Wunderbar und Ratgeber", ["Hirte, Richter und König", "Retter, Licht und Lehrer"], ["Wunderbar", "Ratgeber"]),
    q("b", "2", "Was hat das Volk, das in Finsternis wandelte, gesehen?", "Ein großes Licht", ["Ein großer Stern", "Ein großes Heer"], ["großes Licht"]),
    q("c", "15", "Wer ist laut Jesaja der Schwanz Israels?", "Der Prophet, der Lügen predigt", ["Der Priester, der im Tempel dient", "Der Krieger, der die Stadt verteidigt"], ["Lügen predigt"]),
  ),
  ch("2-ne", 20,
    q("a", "5", "Wer ist laut dem Herrn die Rute seines Zorns?", "Der Assyrer", ["Der Ägypter", "Der Philister"], ["Assyrer"]),
    q("b", "26", "Welches Gemetzel wird im Zusammenhang mit dem Rabenfelsen erwähnt?", "Das gegen Midian", ["Das gegen Amalek", "Das gegen Moab"], ["Midian"]),
    q("c", "21", "Was wird laut Jesaja zum mächtigen Gott zurückkehren?", "Der Überrest Jakobs", ["Die Heere der Assyrer", "Die Stadt des Königs"], ["Überrest Jakobs"]),
  ),
  ch("2-ne", 21,
    q("a", "1", "Aus dem Stamm welches Mannes wird laut Jesaja eine Rute sprießen?", "Isai", ["Josef", "Juda"], ["Isai"]),
    q("b", "6", "Wer wird laut Jesaja beim Lamm wohnen?", "Der Wolf", ["Der Hahn", "Der Rabe"], ["Wolf"]),
    q("c", "9", "Wovon wird die Erde laut Jesaja voll sein?", "Die Erkenntnis des Herrn", ["Die Reichtümer der Nationen", "Die Städte der Heiligen"], ["Erkenntnis des Herrn"]),
  ),
  ch("2-ne", 22,
    q("a", "2", "Was ist der Herr Jehova laut diesem Lied?", "Seine Stärke und sein Lied", ["Seine Burg und sein Schild", "Sein Hirte und sein Fels"], ["Stärke", "Lied"]),
    q("b", "3", "Woraus werdet ihr mit Freuden Wasser schöpfen?", "Aus den Brunnen der Errettung", ["Aus dem Fluss des Jordantals", "Aus dem Brunnen des Vaters Jakob"], ["Brunnen der Errettung"]),
    q("c", "6", "Wer ist groß in der Mitte der Einwohner Zions?", "Der Heilige Israels", ["Der König von Juda", "Der Prophet Jesaja"], ["Heilige Israels"]),
  ),
  ch("2-ne", 23,
    q("a", "17", "Welches Volk wird der Herr laut Jesaja gegen Babylon aufstacheln?", "Die Meder", ["Die Assyrer", "Die Philister"], ["Meder"]),
    q("b", "19", "Mit welchen Städten wird Babylon bei seinem Untergang verglichen?", "Sodom und Gomorra", ["Ninive und Tyrus", "Jericho und Ai"], ["Sodom und Gomorra"]),
    q("c", "10", "Was geschieht laut Jesaja mit der Sonne bei ihrem Aufgang?", "Sie wird verfinstert sein", ["Sie wird rot wie Blut werden", "Sie wird doppelt so hell scheinen"], ["verfinstert"]),
  ),
  ch("2-ne", 24,
    q("a", "12", "Welchen Titel trägt Luzifer in Vers 12?", "Sohn des Morgens", ["Sohn des Mittags", "Sohn des Abends"], ["Sohn des Morgens"]),
    q("b", "14", "Was wollte Luzifer laut Vers 14 in seinem Herzen tun?", "Über die Wolkenhöhen emporsteigen", ["In die Tiefen der Erde hinabsteigen", "Im Osten ein Königreich gründen"], ["Wolkenhöhen"]),
    q("c", "23", "Was wird der Herr aus Babylon machen?", "Zum Besitz für die Reiher", ["Zu einer Stadt voller Kaufleute", "Zu einer Weide für die Schafe"], ["Reiher"]),
  ),
  ch("2-ne", 25,
    q("a", "19", "Wie viele Jahre nach Lehis Aufbruch aus Jerusalem kommt der Messias laut den Propheten?", "Sechshundert Jahre", ["Vierhundert Jahre", "Tausend Jahre"], ["sechshundert Jahre"]),
    q("b", "24", "Was befolgten Nephi und sein Volk, obwohl sie an Christus glaubten?", "Das Gesetz des Mose", ["Die Bräuche der Ägypter", "Die Satzungen Labans"], ["Gesetz des Mose"]),
    q("c", "29", "Wer ist laut Nephi Christus?", "Der Heilige Israels", ["Der Prophet Jesaja", "Der König der Juden"], ["Heilige Israels"]),
  ),
  ch("2-ne", 26,
    q("a", "9", "Wie wird Christus in Vers 9 genannt?", "Der Sohn der Rechtschaffenheit", ["Der Sohn der Gnade und des Segens", "Der Sohn der Kraft und der Ehre"], ["Sohn der Rechtschaffenheit"]),
    q("b", "31", "Wofür darf der Arbeiter in Zion nicht arbeiten?", "Für Geld", ["Für Ruhm", "Für Macht"], ["Geld"]),
    q("c", "25", "Was sagt der Herr laut Vers 25 statt „Geh weg von mir“?", "Kommt her zu mir, all ihr Enden der Erde", ["Baut einen Tempel für meinen Namen", "Opfert mir jeden Tag ein junges Lamm"], ["Kommt her zu mir"]),
  ),
  ch("2-ne", 27,
    q("a", "7", "Was wird laut Vers 7 in dem versiegelten Buch stehen?", "Eine Offenbarung von Gott", ["Die Gesetze der Könige", "Eine Liste aller Könige"], ["Offenbarung von Gott"]),
    q("b", "18", "Was wird der Gelehrte sagen, wenn ihm das Buch gebracht wird?", "Ich kann es nicht lesen", ["Ich will es nicht kaufen", "Ich habe es schon gelesen"], ["nicht lesen"]),
    q("c", "29", "Wer wird laut Jesaja die Worte des Buches hören?", "Die Tauben", ["Die Reichen", "Die Gelehrten"], ["Tauben"]),
  ),
  ch("2-ne", 28,
    q("a", "7", "Was werden viele laut Nephi in den Letzten Tagen sagen?", "Iss, trink und sei lustig", ["Spare, bete und sei vorsichtig", "Arbeite, opfere und sei dankbar"], ["Iss, trink und sei lustig"]),
    q("b", "30", "Auf welche Weise gibt Gott, der Herr, den Menschenkindern sein Wort?", "Zeile um Zeile, Weisung um Weisung", ["Buch um Buch, Kapitel um Kapitel", "Jahr um Jahr, Wunder um Wunder"], ["Zeile um Zeile", "Weisung um Weisung"]),
    q("c", "22", "Was erzählt der Teufel laut Nephi manchen?", "Dass es gar keine Hölle gibt", ["Dass der Herr bald wiederkommt", "Dass der Tempel geschlossen wird"], ["keine Hölle"]),
  ),
  ch("2-ne", 29,
    q("a", "3", "Was werden viele von den Anderen sagen?", "Eine Bibel! Eine Bibel!", ["Ein Tempel! Ein Tempel!", "Ein König! Ein König!"], ["Eine Bibel"]),
    q("b", "4", "Von welchem Volk kommt die Bibel?", "Vom Volk der Juden", ["Vom Volk der Ägypter", "Vom Volk der Nephiten"], ["Juden"]),
    q("c", "8", "Das Zeugnis wie vieler Nationen ist laut dem Herrn ein Beweis, dass er Gott ist?", "Zwei Nationen", ["Drei Nationen", "Sieben Nationen"], ["zwei Nationen"]),
  ),
  ch("2-ne", 30,
    q("a", "2", "Wer ist laut Nephi das Bundesvolk des Herrn?", "Alle von den Anderen, die umkehren", ["Nur die, die aus Jerusalem gekommen sind", "Nur die Reichen, die viele Opfer bringen"], ["umkehren"]),
    q("b", "7", "Woran werden die zerstreuten Juden laut Nephi anfangen zu glauben?", "An Christus", ["An Abraham", "An Jeremia"], ["Christus"]),
    q("c", "17", "Was wird laut Nephi mit allem Verborgenen geschehen?", "Es wird offenbart werden", ["Es wird versiegelt werden", "Es wird vergessen werden"], ["offenbart"]),
  ),
  ch("2-ne", 31,
    q("a", "8", "In welcher Gestalt kam der Heilige Geist auf Christus herab, als er getauft wurde?", "In Gestalt einer Taube", ["In Gestalt eines Adlers", "In Gestalt einer Wolke"], ["Gestalt einer Taube"]),
    q("b", "21", "Was sagt Nephi über den Weg, auf dem der Mensch errettet werden kann?", "Es ist kein anderer Weg noch Name", ["Es gibt zwei Wege und zwei Namen", "Es gibt für jede Nation einen Weg"], ["kein anderer Weg"]),
    q("c", "11", "Was sollten die Menschen laut dem Vater tun?", "Umkehren und sich taufen lassen", ["Fasten und ein Opfer bringen", "Beten und das Gesetz halten"], ["taufen"]),
  ),
  ch("2-ne", 32,
    q("a", "2", "Womit könnten sie reden, nachdem sie den Heiligen Geist empfangen haben?", "Mit der Zunge von Engeln", ["Mit der Zunge von Propheten", "Mit der Zunge von Königen"], ["Zunge von Engeln"]),
    q("b", "9", "Was sollen wir laut Nephi tun?", "Immer beten und nicht ermatten", ["Immer fasten und nie klagen", "Immer opfern und nie ruhen"], ["immer beten"]),
    q("c", "6", "Bis wann wird laut Nephi keine weitere Lehre gegeben werden?", "Bis er sich im Fleische kundtut", ["Bis der Tempel völlig vollendet ist", "Bis das Volk umgekehrt ist"], ["im Fleische"]),
  ),
  ch("2-ne", 33,
    q("a", "6", "Worin frohlockt Nephi unter anderem?", "In Klarheit und in Wahrheit", ["In seiner Kraft und Weisheit", "In seinen Taten und seinem Heer"], ["Klarheit", "Wahrheit"]),
    q("b", "13", "Wie spricht Nephi zu allen Enden der Erde?", "Wie die Stimme eines, der aus dem Staube ruft", ["Wie die Stimme eines Hirten auf dem Feld", "Wie die Stimme eines Engels vom Himmel"], ["aus dem Staube ruft"]),
    q("c", "15", "Was wird laut Nephi vor den Schranken des Gerichts gegen die Menschen vorgebracht werden?", "Das, was Nephi auf Erden gesiegelt hat", ["Alles, was man im Leben gesammelt hat", "Was die Juden damals geschrieben haben"], ["auf Erden"]),
  ),
  // ===== EINDE =====
];
