import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 2 Nephi. German edition - generated from Dutch master.
export const nephi2: GeneesChapterSeed[] = [
  ch("2-ne", 1,
    q("a", "6", "Wie kan volgens Lehi in het land van belofte komen?", "Alleen wie door de hand van de Heer wordt gebracht", ["Alleen wie een schip van eigen makelij kan bouwen", "Alleen wie een vergunning van de koning heeft"], ["hand van de Heer"]),
    q("b", "30", "Wie was de dienstknecht van Laban die Lehi een trouwe vriend van Nephi noemde?", "Zoram", ["Jakob", "Ismaël"], ["Zoram"]),
    q("c", "13", "Waaruit moesten zijn zonen volgens Lehi ontwaken?", "Uit een diepe slaap", ["Uit een lange reis", "Uit een zware ziekte"], ["diepe slaap"]),
  ),
  ch("2-ne", 2,
    q("a", "25", "Waarom zijn de mensen er volgens Lehi?", "Opdat zij vreugde zullen hebben", ["Opdat zij over de aarde zullen heersen", "Opdat zij rijkdom zullen verwerven"], ["vreugde"]),
    q("b", "16", "Wat stond de Here God de mens toe?", "Zelfstandig te handelen", ["Zonder wet te leven", "Zelf een koninkrijk te stichten"], ["zelfstandig te handelen"]),
    q("c", "19", "Waarvoor werden Adam en Eva uit de hof van Eden verdreven?", "Om de aardbodem te bebouwen", ["Om een nieuwe stad te stichten", "Om zeven jaar in de wildernis te leven"], ["aardbodem te bebouwen"]),
  ),
  ch("2-ne", 3,
    q("a", "17", "Waarin zou de Heer de komende Mozes macht geven, volgens de profetie van Jozef?", "In een staf", ["In een zwaard", "In een rolboek"], ["staf"]),
    q("b", "6", "Wat zou de Heer volgens Jozef doen opstaan voor de vrucht van zijn lendenen?", "Een uitgelezen ziener", ["Een machtige koning", "Een rechtvaardige rechter"], ["ziener"]),
    q("c", "1", "Welke plaats had Jozef, tot wie Lehi sprak, onder de kinderen van Lehi?", "Hij was de laatstgeborene", ["Hij was de eerstgeborene", "Hij was de tweede zoon"], ["laatstgeborene"]),
  ),
  ch("2-ne", 4,
    q("a", "12", "Wat gebeurde er met Lehi nadat hij tot zijn gehele huis had gesproken?", "Hij stierf en werd begraven", ["Hij werd ziek en trok zich terug", "Hij werd naar de hemel opgenomen"], ["stierf"]),
    q("b", "11", "Aan welke zoon liet Lehi het land te erven, evenals aan Nephi?", "Aan zijn zoon Sam", ["Aan zijn zoon Laman", "Aan zijn zoon Jozef"], ["Sam"]),
    q("c", "15", "Waarin verheugt Nephi's ziel zich, zo schrijft hij?", "In de Schriften op de platen van koper", ["In de oorlogen met zijn vijanden", "In de rijkdommen van het land"], ["Schriften"]),
  ),
  ch("2-ne", 5,
    q("a", "28", "Hoeveel jaar waren er verstreken sinds zij Jeruzalem hadden verlaten?", "Dertig jaar", ["Twintig jaar", "Vijftig jaar"], ["dertig jaar"]),
    q("b", "16", "Naar het voorbeeld van welke tempel bouwde Nephi een tempel?", "De tempel van Salomo", ["De tempel van Mozes", "De tempel van Zedekia"], ["tempel van Salomo"]),
    q("c", "26", "Wie wijdde Nephi tot priester en leraar over het volk?", "Jakob en Jozef", ["Sam en Zoram", "Laman en Lemuel"], ["Jakob", "Jozef"]),
  ),
  ch("2-ne", 6,
    q("a", "4", "Welke profeet las Jakob het volk voor?", "Jesaja", ["Jeremia", "Mozes"], ["Jesaja"]),
    q("b", "2", "Door wie was Jakob gewijd?", "Door zijn broer Nephi", ["Door zijn vader Lehi", "Door de koning van Juda"], ["Nephi"]),
    q("c", "14", "Hoe vaak zal de Messias zich volgens Jakob opmaken om zijn volk terug te winnen?", "Voor de tweede maal", ["Voor de derde maal", "Voor de zevende maal"], ["tweede maal"]),
  ),
  ch("2-ne", 7,
    q("a", "8", "Waarmee zal de Heer zijn tegenstander slaan?", "Met de kracht van zijn mond", ["Met een scherp zwaard van staal", "Met het vuur van de hemel"], ["mond"]),
    q("b", "7", "Waaraan heeft de Heer zijn gelaat gelijk gemaakt, zo zegt Hij?", "Aan een keisteen", ["Aan een rots in zee", "Aan een stalen schild"], ["keisteen"]),
    q("c", "3", "In welke kleur kleedt de Heer de hemelen?", "In het zwart", ["In het wit", "In het rood"], ["zwart"]),
  ),
  ch("2-ne", 8,
    q("a", "2", "Aan welke vader en moeder moet het volk volgens Jesaja denken?", "Abraham en Sara", ["Izak en Rebekka", "Jakob en Rachel"], ["Abraham", "Sara"]),
    q("b", "3", "Waaraan zal de Heer de wildernis van Zion gelijk maken?", "Aan Eden", ["Aan Bethel", "Aan Sinaï"], ["Eden"]),
    q("c", "1", "Waaruit is het volk dat de gerechtigheid najaagt volgens Jesaja gehouwen?", "Uit de rots", ["Uit de rivier", "Uit de woestijn"], ["rots"]),
  ),
  ch("2-ne", 9,
    q("a", "10", "Hoe noemt Jakob de dood en de hel?", "Een verschrikkelijk monster", ["Een onoverwinnelijke vestingmuur", "Een bodemloze afgrond zonder einde"], ["monster"]),
    q("b", "41", "Wie is volgens Jakob de poortwachter van het smalle pad?", "De Heilige van Israël", ["De profeet Jesaja", "De engel van de Heer"], ["Heilige van Israël"]),
    q("c", "25", "Wat is er volgens Jakob waar geen wet is gegeven?", "Geen straf", ["Geen verlossing", "Geen hoop"], ["geen straf"]),
  ),
  ch("2-ne", 10,
    q("a", "3", "Welke naam zou volgens de engel de naam van de Messias zijn?", "Christus", ["Immanuël", "Jozua"], ["Christus"]),
    q("b", "11", "Wie zullen er volgens de Heer niet zijn in dit land van vrijheid?", "Koningen die zich over anderen verheffen", ["Priesters die dagelijks in de tempel dienen", "Boeren die het land met hun handen bewerken"], ["koningen"]),
    q("c", "23", "Tussen welke twee wegen mogen de mensen volgens Jakob kiezen?", "Eeuwigdurende dood of het eeuwige leven", ["Rijkdom of armoede in het beloofde land", "Oorlog of vrede met het volk van Laman"], ["eeuwigdurende dood", "eeuwige leven"]),
  ),
  ch("2-ne", 11,
    q("a", "2", "Wiens woorden schrijft Nephi nog meer op?", "Die van Jesaja", ["Die van Jeremia", "Die van Zenos"], ["Jesaja"]),
    q("b", "7", "Wat zegt Nephi als er geen Christus is?", "Dan is er geen God", ["Dan is er geen tempel", "Dan is er geen profeet"], ["geen God"]),
    q("c", "4", "Waarvoor is de wet van Mozes volgens Nephi gegeven?", "Als bewijs van de komst van Christus", ["Om het volk van Egypte te bevrijden", "Om de tempel in Jeruzalem te bouwen"], ["komst van Christus"]),
  ),
  ch("2-ne", 12,
    q("a", "4", "Tot wat zullen de volken hun zwaarden omsmeden, volgens Jesaja?", "Tot ploegscharen", ["Tot schilden", "Tot kookpotten"], ["ploegscharen"]),
    q("b", "2", "Waar zal het huis des Heren zich in de laatste dagen bevinden?", "Op de top van de bergen", ["In het diepste dal van Juda", "Aan de oever van de grote zee"], ["top van de bergen"]),
    q("c", "7", "Waarvan was het land van Juda volgens Jesaja vol?", "Van zilver en goud", ["Van graan en olijfolie", "Van schapen en geiten"], ["zilver en goud"]),
  ),
  ch("2-ne", 13,
    q("a", "16", "Waarom zal de Heer de dochters van Zion straffen?", "Omdat zij hoogmoedig zijn geworden", ["Omdat zij de sabbat niet heiligen", "Omdat zij de tempel hebben verlaten"], ["hoogmoedig"]),
    q("b", "9", "Met welke stad vergelijkt Jesaja de zonde van Juda?", "Met Sodom", ["Met Babylon", "Met Ninevé"], ["Sodom"]),
    q("c", "10", "Wat zullen de rechtvaardigen volgens Jesaja eten?", "De vrucht van hun daden", ["Het brood van de koning", "De buit van de vijand"], ["vrucht van hun daden"]),
  ),
  ch("2-ne", 14,
    q("a", "1", "Hoeveel vrouwen zullen volgens Jesaja te dien dage één man aangrijpen?", "Zeven", ["Twaalf", "Tien"], ["zeven"]),
    q("b", "5", "Wat zal de Heer 's nachts boven de berg Zion scheppen?", "Een schijnsel van vlammend vuur", ["Een grote donkere wolk van stof", "Een regen van zilveren sterren"], ["vlammend vuur"]),
    q("c", "6", "Wat zal er zijn tot een schaduw overdag tegen de hitte?", "Een tabernakel", ["Een hoge toren", "Een brede muur"], ["tabernakel"]),
  ),
  ch("2-ne", 15,
    q("a", "1", "Waarover zingt Jesaja een lied?", "Van een wijngaard op een heuvel", ["Van een schaapskooi in het dal", "Van een stad aan de rivier"], ["wijngaard"]),
    q("b", "7", "Wat is de wijngaard van de Heer der heerscharen?", "Het huis van Israël", ["De tempel van Salomo", "De stad van de koning"], ["huis van Israël"]),
    q("c", "20", "Over wie roept Jesaja 'wee' uit in vers 20?", "Zij die het kwade goed noemen", ["Zij die op de sabbat rusten", "Zij die de armen helpen"], ["kwade goed noemen"]),
  ),
  ch("2-ne", 16,
    q("a", "2", "Hoeveel vleugels had elke seraf?", "Zes vleugels", ["Vier vleugels", "Acht vleugels"], ["zes vleugels"]),
    q("b", "6-7", "Waarmee raakte de seraf Jesaja's lippen aan?", "Met een gloeiende kool", ["Met een brandende toorts", "Met een hete steen"], ["gloeiende kool"]),
    q("c", "8", "Wat zei Jesaja toen de Heer vroeg wie Hij zou zenden?", "Hier ben ik; zend mij", ["Ik ben niet waardig", "Zend mijn broer"], ["Hier ben ik"]),
  ),
  ch("2-ne", 17,
    q("a", "14", "Welke naam zal de zoon van de maagd volgens Jesaja krijgen?", "Immanuel", ["Jeremia", "Jehoram"], ["Immanuel"]),
    q("b", "1", "In de dagen van welke koning van Juda trokken Rezin en Pekah tegen Jeruzalem op?", "Achaz", ["Hizkia", "Manasse"], ["Achaz"]),
    q("c", "11", "Wat mocht Achaz van de Heer vragen?", "Een teken", ["Een leger", "Een schip"], ["teken"]),
  ),
  ch("2-ne", 18,
    q("a", "3", "Welke naam moest de zoon van Jesaja volgens de Heer krijgen?", "Maher Sjalal Chasj Baz", ["Sjear-Jasjub Ben Amoz", "Maher Immanuel Ben Isaï"], ["Maher Sjalal Chasj Baz"]),
    q("b", "13", "Wie moeten wij volgens de Heer alleen heilig achten?", "De Heer der heerscharen", ["De koning van Assyrië", "De profeet Jesaja zelf"], ["Heer der heerscharen"]),
    q("c", "7", "Wie wordt met de machtige en vele wateren van de rivier bedoeld?", "De koning van Assyrië", ["De koning van Egypte", "De koning van Syrië"], ["koning van Assyrië"]),
  ),
  ch("2-ne", 19,
    q("a", "6", "Hoe wordt het Kind dat ons is geboren onder meer genoemd?", "Wonderbaar, Raadsman", ["Herder, Rechter en Koning", "Redder, Licht en Leraar"], ["Wonderbaar", "Raadsman"]),
    q("b", "2", "Wat heeft het volk dat in duisternis wandelde gezien?", "Een groot licht", ["Een grote ster", "Een groot leger"], ["groot licht"]),
    q("c", "15", "Wie is volgens Jesaja de staart van Israël?", "De profeet die leugens verkondigt", ["De priester die in de tempel dient", "De krijgsman die de stad verdedigt"], ["leugens verkondigt"]),
  ),
  ch("2-ne", 20,
    q("a", "5", "Wie is volgens de Heer de roede van zijn toorn?", "De Assyriër", ["De Egyptenaar", "De Filistijn"], ["Assyriër"]),
    q("b", "26", "Welke slachting wordt in verband met de rots Oreb genoemd?", "Die van Midian", ["Die van Amalek", "Die van Moab"], ["Midian"]),
    q("c", "21", "Wat zal volgens Jesaja terugkeren tot de sterke God?", "Het overblijfsel van Jakob", ["De legers van de Assyriër", "De stad van de koning"], ["overblijfsel van Jakob"]),
  ),
  ch("2-ne", 21,
    q("a", "1", "Uit de stronk van wie zal volgens Jesaja een twijgje voortkomen?", "Isaï", ["Jozef", "Juda"], ["Isaï"]),
    q("b", "6", "Wie zal volgens Jesaja bij het lam verkeren?", "De wolf", ["De haan", "De raaf"], ["wolf"]),
    q("c", "9", "Waarvan zal de aarde volgens Jesaja vol zijn?", "De kennis van de Heer", ["De rijkdommen van de natiën", "De steden van de heiligen"], ["kennis van de Heer"]),
  ),
  ch("2-ne", 22,
    q("a", "2", "Wat is de Heer Jehova volgens dit lied?", "Zijn sterkte en zijn psalm", ["Zijn burcht en zijn schild", "Zijn herder en zijn rots"], ["sterkte", "psalm"]),
    q("b", "3", "Waaruit zult u met vreugde water scheppen?", "Uit de bronnen van het heil", ["Uit de rivier van Jordaan", "Uit de put van Jakob"], ["bronnen van het heil"]),
    q("c", "6", "Wie is groot in het midden van de inwoners van Zion?", "De Heilige van Israël", ["De koning van Juda", "De profeet Jesaja"], ["Heilige van Israël"]),
  ),
  ch("2-ne", 23,
    q("a", "17", "Welk volk zal de Heer volgens Jesaja tegen Babylon opwekken?", "Het volk van de Meden", ["Het volk van de Assyriërs", "Het volk van de Filistijnen"], ["Meden"]),
    q("b", "19", "Met welke steden wordt Babylon vergeleken bij zijn ondergang?", "Sodom en Gomorra", ["Ninevé en Tyrus", "Jericho en Ai"], ["Sodom en Gomorra"]),
    q("c", "10", "Wat gebeurt er volgens Jesaja met de zon bij haar opgang?", "Ze zal verduisterd zijn", ["Ze zal rood als bloed worden", "Ze zal twee keer zo fel schijnen"], ["verduisterd"]),
  ),
  ch("2-ne", 24,
    q("a", "12", "Welke titel draagt Lucifer in vers 12?", "Zoon van de dageraad", ["Zoon van de middagzon", "Zoon van de avondster"], ["zoon van de dageraad"]),
    q("b", "14", "Wat zei Lucifer in zijn hart te zullen doen?", "Opstijgen boven de wolkenhoogten", ["Neerdalen in het diepste van de aarde", "Een koninkrijk stichten in het oosten"], ["wolkenhoogten"]),
    q("c", "23", "Wat zal de Heer van Babylon maken?", "Een bezit van de roerdomp", ["Een stad vol koopmannen", "Een weide voor de schapen"], ["roerdomp"]),
  ),
  ch("2-ne", 25,
    q("a", "19", "Hoeveel jaar na het vertrek van Lehi uit Jeruzalem komt de Messias volgens de profeten?", "Zeshonderd jaar", ["Vierhonderd jaar", "Duizend jaar"], ["zeshonderd jaar"]),
    q("b", "24", "Wat bewaarden Nephi en zijn volk, hoewel zij in Christus geloofden?", "De wet van Mozes", ["De tempel van Salomo", "De kronieken van Laban"], ["wet van Mozes"]),
    q("c", "29", "Wie is volgens Nephi Christus?", "De Heilige van Israël", ["De profeet Jesaja", "De koning van de Joden"], ["Heilige van Israël"]),
  ),
  ch("2-ne", 26,
    q("a", "9", "Hoe wordt Christus in vers 9 genoemd?", "De Zoon van gerechtigheid", ["De Zoon van de dageraad", "De Zoon van de zegen"], ["Zoon van gerechtigheid"]),
    q("b", "31", "Waarvoor mag de arbeider in Zion niet arbeiden?", "Voor geld", ["Voor roem", "Voor macht"], ["geld"]),
    q("c", "25", "Wat zegt de Heer in plaats van 'Ga van Mij heen'?", "Kom tot Mij, alle einden der aarde", ["Bouw een tempel voor Mijn naam", "Offer elke dag een lam aan Mij"], ["Kom tot Mij"]),
  ),
  ch("2-ne", 27,
    q("a", "7", "Wat zal er in het verzegelde boek staan volgens vers 7?", "Een openbaring van God", ["De wetten van de koningen", "Een lijst van alle koningen"], ["openbaring van God"]),
    q("b", "18", "Wat zal de geleerde zeggen als hem het boek wordt gebracht?", "Ik kan het niet lezen", ["Ik wil het boek niet kopen", "Ik heb het al gelezen"], ["niet lezen"]),
    q("c", "29", "Wie zullen volgens Jesaja de woorden van het boek horen?", "De doven", ["De rijken", "De geleerden"], ["doven"]),
  ),
  ch("2-ne", 28,
    q("a", "7", "Wat zullen velen volgens Nephi in de laatste dagen zeggen?", "Eet, drink en wees vrolijk", ["Spaar, bid en wees voorzichtig", "Werk, offer en wees dankbaar"], ["Eet, drink en wees vrolijk"]),
    q("b", "30", "Op welke wijze geeft de Here God de mensenkinderen zijn woord?", "Regel op regel, voorschrift op voorschrift", ["Boek op boek, hoofdstuk op hoofdstuk", "Jaar op jaar, wonder op wonder"], ["regel op regel", "voorschrift op voorschrift"]),
    q("c", "22", "Wat vertelt de duivel volgens Nephi aan sommigen?", "Dat de hel niet bestaat", ["Dat de Heer binnenkort terugkomt", "Dat de tempel gesloten wordt"], ["hel niet bestaat"]),
  ),
  ch("2-ne", 29,
    q("a", "3", "Wat zullen velen van de andere volken zeggen?", "Een Bijbel! Een Bijbel!", ["Een tempel! Een tempel!", "Een koning! Een koning!"], ["Een Bijbel"]),
    q("b", "4", "Uit welk volk komt de Bijbel voort?", "Uit het volk van de Joden", ["Uit het volk van de Egyptenaren", "Uit het volk van de Nephieten"], ["Joden"]),
    q("c", "8", "Hoeveel natiën getuigen volgens de Heer dat Hij God is?", "Twee natiën", ["Drie natiën", "Zeven natiën"], ["twee natiën"]),
  ),
  ch("2-ne", 30,
    q("a", "2", "Wie zijn volgens Nephi het verbondsvolk van de Heer?", "Allen uit de andere volken die zich bekeren", ["Alleen degenen die uit Jeruzalem zijn gekomen", "Alleen de rijken die veel offers brengen"], ["zich bekeren"]),
    q("b", "7", "Waarin zullen de verstrooide Joden volgens Nephi beginnen te geloven?", "In Christus", ["In Mozes", "In Abraham"], ["Christus"]),
    q("c", "17", "Wat zal er volgens Nephi gebeuren met alles wat verborgen is?", "Het zal worden geopenbaard", ["Het zal worden verzegeld", "Het zal worden vergeten"], ["geopenbaard"]),
  ),
  ch("2-ne", 31,
    q("a", "8", "In welke gedaante daalde de Heilige Geest op Christus neer toen Hij werd gedoopt?", "In de gedaante van een duif", ["In de gedaante van een arend", "In de gedaante van een wolk"], ["gedaante van een duif"]),
    q("b", "21", "Wat zegt Nephi over de weg waardoor de mens kan worden behouden?", "Er is geen andere weg noch naam", ["Er zijn twee wegen en twee namen", "Er is een weg voor elke natie"], ["geen andere weg"]),
    q("c", "11", "Wat zei de Vader dat de mensen moesten doen?", "Zich bekeren en laten dopen", ["Vasten en een offer brengen", "Bidden en de wet houden"], ["bekeer", "dopen"]),
  ),
  ch("2-ne", 32,
    q("a", "2", "Waarmee zouden zij kunnen spreken wanneer zij de Heilige Geest hadden ontvangen?", "Met de taal der engelen", ["Met de taal der profeten", "Met de taal der koningen"], ["taal der engelen"]),
    q("b", "9", "Wat moet men volgens Nephi altijd doen?", "Bidden en niet verslappen", ["Vasten en niet drinken", "Offeren en niet klagen"], ["bidden en niet verslappen"]),
    q("c", "6", "Totdat wanneer zal er volgens Nephi geen verdere leer worden gegeven?", "Totdat Hij Zich in het vlees openbaart", ["Totdat de tempel volledig is voltooid", "Totdat het volk zich heeft bekeerd"], ["in het vlees"]),
  ),
  ch("2-ne", 33,
    q("a", "6", "Waarin roemt Nephi onder meer?", "In duidelijkheid en waarheid", ["In zijn kracht en zijn wijsheid", "In zijn werken en zijn leger"], ["duidelijkheid", "waarheid"]),
    q("b", "13", "Als wie spreekt Nephi tot alle einden der aarde?", "Als de stem van iemand die roept uit het stof", ["Als de stem van een herder in het veld", "Als de stem van een engel uit de hemel"], ["roept uit het stof"]),
    q("c", "15", "Wat zal er volgens Nephi voor het gerecht tegen de mensen worden aangevoerd?", "Wat Nephi op aarde heeft verzegeld", ["Alles wat men op aarde heeft vergaard", "Wat de Joden op aarde hebben geschreven"], ["verzegel"]),
  ),
  // ===== EINDE =====
];
