import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 3 Nephi (deutsche Ausgabe). Jede Tatsache ist an die Verse in `verses` gebunden; `npm run genees:check` prüft das.
export const nephi3: GeneesChapterSeed[] = [
  ch("3-ne", 1,
    q("a", "19", "Was geschah in der Nacht des Zeichens?", "Es gab keine Finsternis, sondern Licht wie am Mittag", ["Es gab einen schweren Sturm, der die Nacht erhellte", "Es gab eine Sonnenfinsternis von vielen Stunden"], ["keine Finsternis"]),
    q("b", "21", "Was erschien laut dem Wort der Propheten am Himmel?", "Ein neuer Stern", ["Ein neuer Mond", "Ein roter Komet"], ["neuer Stern"]),
    q("c", "3", "Wer führte die Aufzeichnungen weiter, nachdem sein Vater das Land verlassen hatte?", "Nephi, der Sohn Nephis", ["Lehi, der Sohn Nephis", "Nephi, der Sohn Lehis"], ["Nephi"]),
  ),
  ch("3-ne", 2,
    q("a", "8", "Von welchem Zeitpunkt an begannen die Nephiten, ihre Zeit zu berechnen?", "Ab dem Zeichen vom Kommen Christi", ["Ab dem Aufbruch Lehis aus Jerusalem", "Ab der Regierung König Mosias"], ["Kommen Christi"]),
    q("b", "12", "Was taten die bekehrten Lamaniten, als die Räuber drohten?", "Sie vereinigten sich mit den Nephiten", ["Sie zogen weit nach Norden hinauf", "Sie gründeten ihr eigenes Königreich"], ["vereinigten sich"]),
    q("c", "11", "Wodurch entstanden im dreizehnten Jahr überall im Land Kriege und Streitigkeiten?", "Die Gadiantonräuber", ["Die Lamaniten im Süden", "Der König von Zarahemla"], ["Gadiantonräuber"]),
  ),
  ch("3-ne", 3,
    q("a", "9", "Wie hieß der Regierende der geheimen Gesellschaft Gadiantons?", "Giddianhi", ["Gidgiddoni", "Zemnarihach"], ["Giddianhi"]),
    q("b", "18", "Wer wurde zum Oberbefehlshaber aller Heere der Nephiten bestimmt?", "Gidgiddoni", ["Lachoneus", "Moronihach"], ["Gidgiddoni"]),
    q("c", "23", "Welches Land war als Sammelplatz bestimmt?", "Das Land Zarahemla", ["Das Land Jerschon", "Das Land Melek"], ["Zarahemla"]),
  ),
  ch("3-ne", 4,
    q("a", "28", "Wie hieß der neue Führer der Räuber, der an einem Baum gehenkt wurde?", "Zemnarihach", ["Gidgiddoni", "Giddianhi"], ["Zemnarihach"]),
    q("b", "3", "Warum konnten die Räuber nur in der Wildnis bestehen?", "Die Nephiten hatten ihre Ländereien verödet zurückgelassen", ["Die Lamaniten hatten alle Ländereien im Süden besetzt", "Die Räuber hatten alle Städte im Land eingenommen"], ["Ländereien"]),
    q("c", "32", "Was riefen die Nephiten, als sie Gott priesen?", "Hosanna dem allerhöchsten Gott", ["Halleluja dem heiligen Gott", "Ehre dem König des Landes"], ["Hosanna"]),
  ),
  ch("3-ne", 5,
    q("a", "12", "Nach welchem Land wurde Mormon benannt?", "Nach dem Land Mormon", ["Nach dem Land Helam", "Nach dem Land Überfluss"], ["Land Mormon"]),
    q("b", "13", "Was ist Mormon laut seinen eigenen Worten?", "Ein Jünger Jesu Christi", ["Ein Hoher Priester", "Ein Heerführer der Nephiten"], ["Jünger Jesu Christi"]),
    q("c", "11", "Worauf schreibt Mormon seinen Bericht?", "Auf Platten, die er mit eigenen Händen anfertigte", ["Auf Platten, die sein Vater angefertigt hatte", "Auf Kupferplatten, die aus Jerusalem stammten"], ["eigenen Händen"]),
  ),
  ch("3-ne", 6,
    q("a", "6", "Wer hatte diesen großen Frieden im Land aufgerichtet?", "Gidgiddoni und der Richter Lachoneus", ["Zemnarihach und der Richter Giddianhi", "Moroni und der Richter Pahoran"], ["Gidgiddoni", "Lachoneus"]),
    q("b", "14", "In welchem Jahr brach die Kirche im ganzen Land auseinander?", "Im dreißigsten Jahr", ["Im zwanzigsten Jahr", "Im vierzigsten Jahr"], ["dreißigsten Jahr"]),
    q("c", "8", "Was wurde in der Zeit des Friedens im Land angelegt?", "Viele Straßen und Wege", ["Viele Mauern und Türme", "Viele Kanäle und Brücken"], ["Straßen"]),
  ),
  ch("3-ne", 7,
    q("a", "19", "Was tat Nephi im Namen Jesu mit seinem Bruder?", "Er erweckte seinen Bruder von den Toten", ["Er heilte seinen Bruder von Blindheit", "Er rettete seinen Bruder aus dem Gefängnis"], ["von den Toten"]),
    q("b", "10", "Wie nannte die geheime Gesellschaft den Mann, den sie als Oberhaupt einsetzte?", "Sie nannten ihn ihren König", ["Sie nannten ihn ihren Richter", "Sie nannten ihn ihren Propheten"], ["König"]),
    q("c", "2", "In was teilte sich das Volk auf?", "In Stämme", ["In Städte", "In Heere"], ["Stämme"]),
  ),
  ch("3-ne", 8,
    q("a", "5", "In welchem Jahr erhob sich ein großer Sturm?", "Im vierunddreißigsten Jahr", ["Im dreiunddreißigsten Jahr", "Im fünfunddreißigsten Jahr"], ["vierunddreißigsten Jahr"]),
    q("b", "8", "Was geschah mit der Stadt Zarahemla?", "Sie fing Feuer", ["Sie versank", "Sie wurde bedeckt"], ["fing Feuer"]),
    q("c", "23", "Wie lange war kein Licht zu sehen?", "Drei Tage", ["Sieben Tage", "Zwei Tage"], ["drei Tage"]),
  ),
  ch("3-ne", 9,
    q("a", "3", "Was geschah laut der Stimme mit der großen Stadt Zarahemla?", "Sie wurde mit Feuer verbrannt", ["Sie versank in den Tiefen des Meeres", "Sie wurde mit Erde bedeckt"], ["mit Feuer verbrannt"]),
    q("b", "18", "Wie nennt sich der Herr in Vers 18?", "Alpha und Omega", ["Erster und Letzter", "Hirte und Fels"], ["Alpha", "Omega"]),
    q("c", "20", "Welches Opfer verlangt der Herr anstelle von Blutvergießen?", "Ein reuiges Herz und zerknirschten Geist", ["Ein Opfer von den Erstlingen des Viehs", "Ein Brandopfer vom besten Getreide"], ["reuiges Herz"]),
  ),
  ch("3-ne", 10,
    q("a", "9", "Wie lange dauerte es, bis die Finsternis aus dem Land wich?", "Drei Tage", ["Sieben Tage", "Zwei Tage"], ["drei Tage"]),
    q("b", "5", "Womit vergleicht der Herr sein Verlangen, das Volk zu sammeln?", "Mit einer Henne, die ihre Küken sammelt", ["Mit einem Hirten, der seine Schafe führt", "Mit einem Adler, der seine Jungen trägt"], ["Henne"]),
    q("c", "16", "Welche Propheten haben laut Mormon davon Zeugnis gegeben?", "Zenos und Zenoch", ["Jesaja und Jeremia", "Mose und Aaron"], ["Zenos", "Zenoch"]),
  ),
  ch("3-ne", 11,
    q("a", "1", "Wo hatte sich die große Menge des Volkes Nephi versammelt?", "Rings um den Tempel in Überfluss", ["Rings um den Berg in Zarahemla", "Rings um den Palast in Nephi"], ["Tempel"]),
    q("b", "7", "Was sagte die Stimme aus dem Himmel?", "Seht meinen geliebten Sohn; ihn höret", ["Seht meinen Diener; folgt seinen Worten", "Seht den Propheten; fürchtet seine Urteile"], ["geliebten Sohn", "ihn höret"]),
    q("c", "25", "In wessen Namen soll laut dem Herrn getauft werden?", "Im Namen des Vaters und des Sohnes und des Heiligen Geistes", ["Im Namen des Vaters, des Propheten und des Königs im Land", "Im Namen des Herrn, des Engels und des Geistes der Wahrheit"], ["Namen des Vaters und des Sohnes und des Heiligen Geistes"]),
  ),
  ch("3-ne", 12,
    q("a", "13", "Wozu fordert der Herr die Menschen in Vers 13 auf?", "Das Salz der Erde zu sein", ["Das Salz des Meeres zu sein", "Das Brot der Erde zu sein"], ["Salz der Erde"]),
    q("b", "5", "Wer wird laut dem Herrn die Erde ererben?", "Die Sanftmütigen", ["Die Reichen im Land", "Die Starken im Land"], ["Sanftmütigen"]),
    q("c", "44", "Was gebietet der Herr in Bezug auf unsere Feinde?", "Liebt eure Feinde", ["Vertreibt eure Feinde", "Bestraft eure Feinde"], ["Liebt eure Feinde"]),
  ),
  ch("3-ne", 13,
    q("a", "9", "Wie beginnt das Gebet, das Jesus der Menge lehrt?", "Unser Vater, der du bist im Himmel", ["Unser Herr, der du wohnst im Himmel", "Unser Gott, der du regierst auf Erden"], ["Unser Vater, der du bist im Himmel"]),
    q("b", "33", "Wonach soll man laut Jesus zuerst trachten?", "Das Reich Gottes und seine Rechtschaffenheit", ["Reichtum und einen guten Namen unter den Menschen", "Nahrung und Kleidung für die Familie"], ["Reich Gottes"]),
    q("c", "24", "Wie vielen Herren kann niemand laut Jesus dienen?", "Zwei Herren", ["Drei Herren", "Sieben Herren"], ["zwei Herren"]),
  ),
  ch("3-ne", 14,
    q("a", "7", "Was verheißt der Herr denen, die bitten?", "Es wird euch gegeben werden", ["Es wird euch genommen werden", "Es wird euch vergessen werden"], ["gegeben werden"]),
    q("b", "15", "Wie kommen falsche Propheten laut dem Herrn zu uns?", "In Schafskleidern", ["In Königskleidern", "In Priestergewändern"], ["Schafskleidern"]),
    q("c", "24", "Worauf baute der weise Mann laut Jesus sein Haus?", "Auf einem Felsen", ["Auf dem Sand", "Auf einem Hügel"], ["Felsen"]),
  ),
  ch("3-ne", 15,
    q("a", "17", "Was sagt der Herr über andere Schafe?", "Dass er noch andere Schafe hat", ["Dass er keine anderen Schafe hat", "Dass alle Schafe hier versammelt sind"], ["andere Schafe"]),
    q("b", "4", "Was ist laut dem Herrn erfüllt?", "Das Gesetz, das Mose gegeben wurde", ["Das Gesetz, das Lehi gegeben wurde", "Das Gesetz, das Abraham gegeben wurde"], ["Gesetz, das Mose gegeben wurde"]),
    q("c", "9", "Was ist der Herr laut Vers 9?", "Das Gesetz und das Licht", ["Die Pforte und der Weg", "Der Friede und der Fels"], ["Gesetz und das Licht"]),
  ),
  ch("3-ne", 16,
    q("a", "6", "Wer ist laut dem Herrn wegen seines Glaubens an ihn gesegnet?", "Die Anderen", ["Nur Juden", "Nur Nephiten"], ["Anderen"]),
    q("b", "18", "Was werden die Wächter laut dem Propheten Jesaja tun?", "Die Stimme erheben und mit vereinter Stimme jauchzen", ["Das Volk mit Posaunen zu einer Versammlung zusammenrufen", "Die Stadt verlassen und in die Wildnis fliehen"], ["Stimme erheben"]),
    q("c", "13", "Was geschieht mit den Anderen, wenn sie umkehren und zum Herrn zurückkommen?", "Sie werden meinem Volk zugezählt werden", ["Sie werden aus dem Land vertrieben werden", "Sie werden ohne Gericht verschont werden"], ["meinem Volk zugezählt"]),
  ),
  ch("3-ne", 17,
    q("a", "14", "Was tat Jesus, als die Menge auf dem Boden niedergekniet war?", "Er stöhnte tief in seinem Inneren", ["Er verließ heimlich den Ort", "Er segnete sie mit seinen Händen"], ["stöhnte"]),
    q("b", "7", "Wen forderte Jesus die Menge auf, zu ihm zu bringen?", "Menschen, die krank, lahm oder blind sind", ["Menschen, die reich und mächtig sind", "Menschen, die fremd und unbekannt sind"], ["krank"]),
    q("c", "21", "Wie nahm Jesus die kleinen Kinder zu sich?", "Er nahm sie eines nach dem anderen", ["Er schickte sie zu ihren Eltern zurück", "Er ließ sie in Gruppen beten"], ["eines nach dem anderen"]),
  ),
  ch("3-ne", 18,
    q("a", "1", "Was gebot Jesus seinen Jüngern, ihm herzubringen?", "Brot und Wein", ["Wasser und Öl", "Fleisch und Obst"], ["Brot und Wein"]),
    q("b", "18", "Was müssen die Menschen laut Jesus immer tun, damit sie nicht in Versuchung geraten?", "Wachen und beten", ["Fasten und opfern", "Arbeiten und sparen"], ["wachen und beten"]),
    q("c", "7", "Wozu sollen sie laut Jesus das Brot essen?", "Zum Gedächtnis seines Leibes", ["Zum Gedächtnis des Gesetzes Moses", "Zum Gedächtnis ihrer Vorfahren"], ["Gedächtnis"]),
  ),
  ch("3-ne", 19,
    q("a", "5", "In wie viele Gruppen wurde die Menge geteilt?", "In zwölf Gruppen", ["In sieben Gruppen", "In drei Gruppen"], ["zwölf Gruppen"]),
    q("b", "9", "Worum beteten die Jünger am meisten?", "Dass ihnen der Heilige Geist gegeben würde", ["Dass ihr Volk keinen Krieg mehr erleben würde", "Dass ihr Gebet nie zu Ende gehen würde"], ["Heilige Geist"]),
    q("c", "11", "Wer stieg ins Wasser hinab, um sich taufen zu lassen?", "Nephi", ["Jonas", "Kumen"], ["Nephi"]),
  ),
  ch("3-ne", 20,
    q("a", "3,5", "Was gab Jesus den Jüngern und der Menge zu essen und zu trinken?", "Brot und Wein", ["Fisch und Honig", "Getreide und Milch"], ["Brot", "Wein"]),
    q("b", "6", "Was sagt Vers 6 über das Brot und den Wein?", "Es war kein Brot und kein Wein gebracht worden", ["Die Jünger hatten Brot und Wein gebracht", "Die Menge hatte Brot und Wein gebracht"], ["kein Brot"]),
    q("c", "14", "Was gebot der Vater Jesus, dem Volk zu geben?", "Dieses Land als ihr Erbteil", ["Das Land Jerusalem als Erbteil", "Das südliche Land als Erbteil"], ["Erbteil"]),
  ),
  ch("3-ne", 21,
    q("a", "12", "Womit wird der Überrest Jakobs unter den Anderen verglichen?", "Mit einem Löwen unter den Tieren", ["Mit einem Schaf unter den Wölfen", "Mit einem Adler über den Bergen"], ["Löwe"]),
    q("b", "14", "Was wird der Herr laut Vers 14 aus der Mitte der Anderen auslöschen und zerstören?", "Pferde und Streitwagen", ["Schafe und Viehherden", "Türme und Stadttore"], ["Pferde"]),
    q("c", "16", "Welche Praxis wird der Herr laut Vers 16 aus ihrem Land ausrotten?", "Die Zauberei", ["Die Karawanen", "Die Kornfelder"], ["Zauberei"]),
  ),
  ch("3-ne", 22,
    q("a", "9", "Womit vergleicht der Herr seine Verheißung in Vers 9?", "Mit den Wassern Noachs", ["Mit den Wassern des Jordan", "Mit den Wassern des Nils"], ["Noachs"]),
    q("b", "13", "Wer wird laut dem Herrn von ihm belehrt werden?", "Alle deine Kinder, vom Herrn", ["Alle Priester, vom König", "Nur die Reichen, von den Lehrern"], ["Kinder"]),
    q("c", "12", "Woraus macht der Herr die Fenster des wiederhergestellten Zion?", "Aus dem Edelstein Achat", ["Aus dem Edelstein Rubin", "Aus dem Edelstein Saphir"], ["Achat"]),
  ),
  ch("3-ne", 23,
    q("a", "9", "Wem hatte der Herr geboten, dem Volk vom Zeichen seines Todes Zeugnis zu geben?", "Samuel dem Lamaniten", ["Nephi, dem Sohn Helamans", "Lehi, dem Propheten"], ["Samuel dem Lamaniten"]),
    q("b", "7", "Was sollte Nephi laut Jesus herbringen?", "Den Bericht, den sie geführt hatten", ["Die Kupferplatten aus Jerusalem", "Die Kugel oder den Wegweiser Lehis"], ["Bericht"]),
    q("c", "13", "Was gebot Jesus in Bezug auf das, was noch nicht aufgeschrieben war?", "Es niederzuschreiben", ["Es geheim zu halten", "Es vergehen zu lassen"], ["niederzuschreiben"]),
  ),
  ch("3-ne", 24,
    q("a", "1", "Wessen Worte gebot Jesus niederzuschreiben?", "Die Worte Maleachis", ["Die Worte Jesajas", "Die Worte Jeremias"], ["Maleachi"]),
    q("b", "8", "Woran beraubt das Volk Gott laut Vers 8?", "Am Zehnten und an Opfergaben", ["Am Sabbat und an Gottesdiensten", "An Gebeten und an Almosen"], ["Zehnten"]),
    q("c", "10", "Wohin soll laut dem Herrn der ganze Zehnte gebracht werden?", "In das Vorratshaus", ["An die Tempelmauer", "Zum Richterstuhl"], ["Vorratshaus"]),
  ),
  ch("3-ne", 25,
    q("a", "5", "Welchen Propheten sendet der Herr, ehe der große und schreckliche Tag kommt?", "Elija", ["Elisa", "Jona"], ["Elija"]),
    q("b", "2", "Wie wird Christus in Vers 2 genannt?", "Der Sohn der Rechtschaffenheit", ["Der Sohn des Lichts und der Gnade", "Der Sohn der Kraft und der Ehre"], ["Sohn der Rechtschaffenheit"]),
    q("c", "6", "Was wird Elija laut dem Herrn zuwenden?", "Das Herz der Väter den Kindern", ["Das Gesetz der Väter den Kindern", "Den Reichtum der Väter den Kindern"], ["Herz der Väter"]),
  ),
  ch("3-ne", 26,
    q("a", "13", "Wie lange hat der Herr das Volk laut Vers 13 belehrt?", "Drei Tage lang", ["Sieben Tage lang", "Vierzig Tage lang"], ["drei Tage"]),
    q("b", "21", "Wie nannte man die, die sich im Namen Jesu taufen ließen?", "Die Kirche Christi", ["Die Kirche Nephis", "Die Kirche Lehis"], ["Kirche Christi"]),
    q("c", "19", "Was hatten die Gläubigen laut Vers 19?", "Sie hatten alles unter sich gemeinsam", ["Sie hatten alles in Privatbesitz", "Alle Reichtümer lagen bei den Führern"], ["gemeinsam"]),
  ),
  ch("3-ne", 27,
    q("a", "5", "Mit welchem Namen soll die Kirche laut Jesus benannt werden?", "Mit dem Namen Christi", ["Mit dem Namen des Mose", "Mit dem Namen Nephis"], ["Namen Christi"]),
    q("b", "28", "Was verheißt Jesus denen, die den Vater in seinem Namen bitten?", "Es wird euch gegeben werden", ["Es wird euch vorenthalten werden", "Es wird euch vergolten werden"], ["gegeben werden"]),
    q("c", "33", "Durch welche Pforte sollen die Jünger laut Jesus eintreten?", "Durch die enge Pforte", ["Durch die breite Pforte", "Durch die goldene Pforte"], ["enge Pforte"]),
  ),
  ch("3-ne", 28,
    q("a", "3", "In welchem Alter würden die Jünger laut Jesus zu ihm kommen?", "Mit zweiundsiebzig Jahren", ["Mit fünfundsiebzig Jahren", "Mit sechzig Jahren"], ["zweiundsiebzig Jahre"]),
    q("b", "7", "Was würde laut Jesus mit den drei Jüngern, die es wünschten, nie geschehen?", "Sie würden nie den Tod schmecken", ["Sie würden nie mehr hungern", "Sie würden nie ihren Glauben verlieren"], ["nie den Tod schmecken"]),
    q("c", "22", "Was geschah, als die drei in eine Grube mit wilden Tieren geworfen wurden?", "Sie spielten mit den Tieren wie ein Kind", ["Sie wurden von den Tieren verschlungen", "Sie wurden von den Tieren angegriffen"], ["spielten mit den Tieren"]),
  ),
  ch("3-ne", 29,
    q("a", "8", "Wen darf man laut Mormon nicht länger verspotten oder verächtlich zurückweisen?", "Das Volk der Juden", ["Das Volk der Nephiten", "Das Volk der Lamaniten"], ["Juden"]),
    q("b", "6", "Was leugnet, wer sagt, der Herr wirke nicht länger?", "Die Offenbarungen des Herrn", ["Die Bündnisse des Herrn", "Die Propheten des Herrn"], ["Offenbarungen des Herrn"]),
    q("c", "2", "Was kann man laut Mormon über die Worte des Herrn wissen?", "Dass sie sich alle erfüllen werden", ["Dass sie alle vergessen werden", "Dass sie nie mehr gelesen werden"], ["sich alle erfüllen werden"]),
  ),
  ch("3-ne", 30,
    q("a", "1", "An wen richtet sich Mormon in diesem Kapitel?", "An die Anderen", ["An die Nephiten", "An die Lamaniten"], ["Anderen"]),
    q("b", "2", "Was sollen die Anderen laut Mormon tun?", "Sich von ihren schlechten Wegen abzuwenden", ["Sich im nördlichen Land zu sammeln", "Sich mit dem Bau von Türmen zu beeilen"], ["schlechten Wegen"]),
    q("c", "1", "Wer ist Jesus Christus laut Vers 1?", "Der Sohn des lebendigen Gottes", ["Der Sohn des Propheten Mormon", "Der Sohn des Königs von Juda"], ["lebendigen Gottes"]),
  ),
  // ===== EINDE =====
];
