import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Alma (deutsche Ausgabe). Jede Tatsache ist an die Verse in `verses` gebunden; `npm run genees:check` prüft das.
export const alma: GeneesChapterSeed[] = [
  ch("alma", 1,
    q("a", "15", "Wie hieß der Mann, der Gideon tötete?", "Nehor", ["Amulon", "Zoram"], ["Nehor"]),
    q("b", "15", "Wo wurde Nehor hingerichtet?", "Auf der Spitze des Hügels Manti", ["Am Ufer des Flusses Sidon", "Auf dem Markt von Zarahemla"], ["Hügels Manti"]),
    q("c", "12", "Was wurde laut Alma zum ersten Mal unter dem Volk eingeführt?", "Die Priesterlist", ["Der Sklavenhandel", "Der Tempelbau"], ["Priesterlist"]),
  ),
  ch("alma", 2,
    q("a", "1", "Wie hieß der Mann, der König über das Volk werden wollte?", "Amlissi", ["Nehor", "Korihor"], ["Amlissi"]),
    q("b", "31", "Wie tötete Alma den Anführer der Amlissiten?", "Mit dem Schwert", ["Mit einem Speer", "Mit einem Pfeil"], ["mit dem Schwert"]),
    q("c", "15", "Auf welchen Hügel östlich des Sidon kamen die Amlissiten?", "Der Hügel Amnihu", ["Der Hügel Manti", "Der Hügel Riplah"], ["Hügel Amnihu"]),
  ),
  ch("alma", 3,
    q("a", "4", "Womit hatten sich die Amlissiten auf der Stirn gekennzeichnet?", "Mit roter Farbe", ["Mit blauer Farbe", "Mit weißer Farbe"], ["rot"]),
    q("b", "26", "Wie viele Seelen wurden in jenem einen Jahr in die ewige Welt gesandt?", "Tausende und Zehntausende", ["Hunderte und Tausende", "Nur wenige Hunderte"], ["Tausende und Zehntausende"]),
    q("c", "22", "Warum zog Alma diesmal nicht selbst in den Kampf gegen die Lamaniten?", "Weil er durch eine Wunde bedrängt war", ["Weil er dem Heer nicht vertraute", "Weil er einen anderen Plan hatte"], ["Wunde"]),
  ),
  ch("alma", 4,
    q("a", "5", "Wie viele Seelen schlossen sich im siebenten Jahr der Kirche an?", "Etwa dreitausendfünfhundert", ["Etwa zweitausendfünfhundert", "Etwa fünftausenddreihundert"], ["dreitausendfünfhundert"]),
    q("b", "17", "Wer wurde zum obersten Richter bestimmt, als Alma den Richterstuhl übergab?", "Nephihach", ["Giddonach", "Helaman"], ["Nephihach"]),
    q("c", "18", "Welches Amt behielt Alma für sich selbst?", "Das Amt des Hohen Priesters", ["Das Amt des Heerführers", "Das Amt des obersten Richters"], ["Hohen Priesters"]),
  ),
  ch("alma", 5,
    q("a", "38", "Welchen Namen trägt der gute Hirte, der uns ruft?", "Den Namen Christi", ["Den Namen Mormons", "Den Namen Abinadis"], ["Christi"]),
    q("b", "3", "Von wem war Alma zum Hohen Priester über die Kirche geweiht worden?", "Von seinem Vater Alma", ["Von König Mosia", "Vom Propheten Abinadi"], ["Vater Alma"]),
    q("c", "52", "Was ist laut dem Geist an die Wurzel des Baumes gelegt?", "Die Axt", ["Die Säge", "Die Hacke"], ["Axt"]),
  ),
  ch("alma", 6,
    q("a", "8", "In welchem Tal fing Alma danach an, das Wort Gottes zu verkünden?", "Das Tal Gideon", ["Das Tal Lemuel", "Das Tal Helam"], ["Tal Gideon"]),
    q("b", "2", "Was geschah mit denen, die nicht zur Kirche gehörten und von ihren Sünden umkehrten?", "Sie wurden zur Umkehr getauft", ["Sie wurden nach Zarahemla gesandt", "Sie mussten zuerst ein Jahr warten"], ["zur Umkehr getauft"]),
    q("c", "6", "Wozu wurde den Kindern Gottes geboten, oft zusammenzukommen?", "Zu Fasten und mächtigem Beten", ["Zu Opfern und Brandopfern", "Zum Bau neuer Tempel im Land"], ["Fasten und mächtigem Beten"]),
  ),
  ch("alma", 7,
    q("a", "10", "Wo wird der Herr laut Alma geboren werden?", "In Jerusalem", ["In Nazaret", "In Zarahemla"], ["Jerusalem"]),
    q("b", "10", "Wie nennt Alma die Mutter des Herrn?", "Eine Jungfrau, ein kostbares und erwähltes Gefäß", ["Eine Prinzessin, eine reiche und mächtige Frau", "Eine Königin, ein reiches und edles Gefäß"], ["kostbares und erwähltes Gefäß"]),
    q("c", "24", "Welche drei Dinge sollen wir laut Alma haben?", "Glauben, Hoffnung und Nächstenliebe", ["Erkenntnis, Weisheit und Macht", "Glauben, Umkehr und Opfergaben"], ["Glauben, Hoffnung und Nächstenliebe"]),
  ),
  ch("alma", 8,
    q("a", "3", "In welches Land reiste Alma zu Beginn des zehnten Jahres der Regierung der Richter?", "Das Land Melek", ["Das Land Gideon", "Das Land Jerschon"], ["Land Melek"]),
    q("b", "6", "Wie hieß die Stadt, in die Alma nach drei Tagereisen nördlich von Melek kam?", "Ammoniha", ["Zarahemla", "Jerschon"], ["Ammoniha"]),
    q("c", "21", "Wie hieß der Mann, der Alma in seinem Haus aufnahm?", "Amulek", ["Amulon", "Amaleki"], ["Amulek"]),
  ),
  ch("alma", 9,
    q("a", "4", "Was würden die Einwohner von Ammoniha Alma selbst dann nicht glauben, wenn er es prophezeite?", "Dass die Stadt an einem einzigen Tag zerstört werde", ["Dass die Stadt von einer Flut vernichtet werde", "Dass die Stadt von den Lamaniten eingenommen werde"], ["einem einzigen Tag"]),
    q("b", "26", "Wann wird der Sohn Gottes laut dem Engel in seiner Herrlichkeit kommen?", "In nicht vielen Tagen", ["In vielen Hundert Jahren", "In mehr als tausend Jahren"], ["nicht vielen Tagen"]),
    q("c", "34", "Wer trat vor und fing ebenfalls an, zum Volk zu predigen?", "Amulek", ["Zeezrom", "Gideon"], ["Amulek"]),
  ),
  ch("alma", 10,
    q("a", "2", "Wer war der Vater Amuleks?", "Giddonach", ["Aminadi", "Ischmael"], ["Giddonach"]),
    q("b", "7", "Wer erschien Amulek auf seiner Reise?", "Ein Engel des Herrn", ["Ein Prophet aus Melek", "Ein Diener Almas"], ["Engel des Herrn"]),
    q("c", "31", "Wie hieß der fachkundigste unter ihnen, der Amulek und Alma anzuklagen begann?", "Zeezrom", ["Korihor", "Gideon"], ["Zeezrom"]),
  ),
  ch("alma", 11,
    q("a", "3", "Was empfing ein Richter als Lohn für einen Tag?", "Eine Senine Gold", ["Ein Limna Gold", "Ein Onti Silber"], ["Senine Gold"]),
    q("b", "21", "Wer fing an, Amulek zu verhören?", "Zeezrom", ["Gideon", "Korihor"], ["Zeezrom"]),
    q("c", "38-39", "Wer ist laut Amulek in Wahrheit der ewige Vater des Himmels und der Erde?", "Der Sohn Gottes", ["Der Prophet Alma", "Der Engel Gottes"], ["Sohn Gottes"]),
  ),
  ch("alma", 12,
    q("a", "20", "Wer war Antionach?", "Einer der obersten Herrscher", ["Ein fachkundiger Gesetzesgelehrter", "Ein Heerführer der Nephiten"], ["obersten Herrscher"]),
    q("b", "16", "Wie nennt Alma den zweiten Tod?", "Ein geistiger Tod", ["Ein zeitlicher Tod", "Ein körperlicher Tod"], ["geistiger Tod"]),
    q("c", "21", "Was stellte Gott laut der Schriftstelle im Osten des Gartens von Eden auf?", "Kerubim mit einem lodernden Schwert", ["Eine Mauer mit einem goldenen Tor", "Einen Engel mit einem goldenen Schlüssel"], ["Kerubim"]),
  ),
  ch("alma", 13,
    q("a", "15", "Wem zahlte Abraham den Zehnten?", "Melchisedek", ["König Salomo", "Prophet Mose"], ["Melchisedek"]),
    q("b", "17", "Über welches Land war Melchisedek König?", "Über das Land Salem", ["Über das Land Moab", "Über das Land Ägypten"], ["Land Salem"]),
    q("c", "9", "Wie wird der Sohn in Vers 9 genannt?", "Der Einziggezeugte des Vaters", ["Der Erstgeborene des Vaters", "Der Gesalbte des Vaters"], ["Einziggezeugte"]),
  ),
  ch("alma", 14,
    q("a", "16", "Welcher Ordnung gehörte der oberste Richter von Ammoniha an?", "Der Ordnung Nehors", ["Der Ordnung Amlissis", "Der Ordnung Korihors"], ["Nehor"]),
    q("b", "18", "Wie viele Tage waren Alma und Amulek im Gefängnis, bevor die Gesetzeskundigen kamen?", "Drei Tage", ["Sieben Tage", "Zwei Tage"], ["drei Tage"]),
    q("c", "27", "Was geschah, als Alma und Amulek den Herrn um Befreiung angerufen hatten?", "Die Erde bebte heftig", ["Ein Feuer brach aus", "Es hagelte heftig"], ["Erde bebte heftig"]),
  ),
  ch("alma", 15,
    q("a", "1", "In welches Land gingen Alma und Amulek, nachdem sie Ammoniha verlassen hatten?", "Das Land Sidom", ["Das Land Melek", "Das Land Nephi"], ["Land Sidom"]),
    q("b", "3", "Woran litt Zeezrom in Sidom?", "An einem brennenden Fieber", ["An einer schweren Verwundung", "An einer ernsten Blindheit"], ["brennenden Fieber"]),
    q("c", "12", "Was tat Alma mit Zeezrom, nachdem dieser genesen war?", "Er taufte ihn in dem Herrn", ["Er schickte ihn nach Ammoniha", "Er ließ ihn die Kirche verlassen"], ["taufte"]),
  ),
  ch("alma", 16,
    q("a", "5", "Wie hieß der oberste Hauptmann über die Heere der Nephiten?", "Zoram", ["Moroni", "Gideon"], ["Zoram"]),
    q("b", "10", "Was geschah mit der Stadt Ammoniha?", "Sie wurde an einem einzigen Tag verwüstet", ["Sie wurde allmählich von den Lamaniten besetzt", "Sie wurde von einem Erdbeben verschlungen"], ["einzigen Tag"]),
    q("c", "19", "Was verkündeten die Priester über den Sohn Gottes?", "Seine Leiden und seinen Tod", ["Seinen Reichtum und seine Macht", "Seine Heirat und seine Familie"], ["Leiden"]),
  ),
  ch("alma", 17,
    q("a", "4", "Wie viele Jahre hatten die Söhne Mosias das Wort unter den Lamaniten gelehrt?", "Vierzehn Jahre", ["Vierzig Jahre", "Sieben Jahre"], ["vierzehn Jahre"]),
    q("b", "21", "Wie hieß der König über das Land Ischmael?", "Lamoni", ["Limhi", "Laman"], ["Lamoni"]),
    q("c", "38", "Wie viele Lamaniten fielen durch Ammons Schleuder?", "Sechs Männer", ["Vier Männer", "Acht Männer"], ["sechs"]),
  ),
  ch("alma", 18,
    q("a", "13", "Was bedeutet das Wort Rabbana?", "Mächtiger oder großer König", ["Weiser und mächtiger Herr", "Tapferer Heerführer"], ["großer König"]),
    q("b", "43", "Wie lange lag König Lamoni wie tot auf seinem Bett?", "Zwei Tage und zwei Nächte", ["Drei Tage und drei Nächte", "Einen Tag und eine Nacht"], ["zwei Tage", "zwei Nächte"]),
    q("c", "9", "Was tat Ammon, als der König nach ihm fragte?", "Er fütterte die Pferde des Königs", ["Er feierte mit den Dienern ein Fest", "Er schlief im Zelt des Königs"], ["Pferde"]),
  ),
  ch("alma", 19,
    q("a", "8", "Was sagte Ammon über König Lamoni, als er ihn ansah?", "Er ist nicht tot, sondern er schläft in Gott", ["Er ist verwundet und muss am Feuer ruhen", "Er ist krank und braucht einen Arzt"], ["schläft in Gott"]),
    q("b", "13", "Was sagte Lamoni, als er wieder aufstand?", "Dass er seinen Erlöser gesehen habe", ["Dass er ein großes Heer gesehen habe", "Dass er seinen Vater gesehen habe"], ["Erlöser"]),
    q("c", "28", "Wer hatte die Menge zusammenkommen lassen?", "Eine lamanitische Magd", ["Eine Tochter des Königs", "Ein Priester des Volkes"], ["Magd"]),
  ),
  ch("alma", 20,
    q("a", "3", "In welchem Land saßen Ammons Brüder im Gefängnis?", "Das Land Middoni", ["Das Land Ischmael", "Das Land Sidom"], ["Middoni"]),
    q("b", "10", "Wie nennt der Vater Lamonis den Nephiten Ammon?", "Eines der Kinder eines Lügners", ["Einen der Söhne eines Königs", "Einen der Diener des Teufels"], ["Kinder eines Lügners"]),
    q("c", "23", "Was bot der alte König Ammon an, falls er ihn verschonte?", "Die Hälfte des Reiches", ["Ein Drittel seiner Schätze", "Seine älteste Tochter"], ["Hälfte des Reiches"]),
  ),
  ch("alma", 21,
    q("a", "2", "Welche Stadt erbauten die Lamaniten, die Amalekiten und das Volk Amulon?", "Eine große Stadt namens Jerusalem", ["Eine große Stadt namens Nephi", "Eine große Stadt namens Zarahemla"], ["Jerusalem"]),
    q("b", "14", "Durch wen wurden Aaron und seine Brüder aus dem Gefängnis befreit?", "Durch Lamoni und Ammon", ["Durch Mosia und Alma", "Durch Omner und Himni"], ["Lamoni", "Ammon"]),
    q("c", "22", "Was verkündete König Lamoni seinem Volk über die Anbetung des Herrn?", "Dass sie frei waren, den Herrn anzubeten, wo sie wollten", ["Dass sie nur in den Synagogen den Herrn anbeten durften", "Dass sie ausschließlich den König anzubeten hatten"], ["anzubeten"]),
  ),
  ch("alma", 22,
    q("a", "3", "Was versprachen Aaron und seine Brüder dem König im Tausch für ihr Leben?", "Dass sie seine Diener sein würden", ["Dass sie ihm ihren Besitz geben würden", "Dass sie das Land verlassen würden"], ["Diener"]),
    q("b", "7", "Was sagen die Amalekiten laut dem König über Gott?", "Dass es einen Gott gibt", ["Dass es zwei Götter gibt", "Dass es keinen Gott gibt"], ["einen Gott"]),
    q("c", "17", "Was tat der König, nachdem Aaron seine Worte gesprochen hatte?", "Er streckte sich auf die Erde nieder", ["Er stand auf und verließ den Saal", "Er rief seine Leibwache zusammen"], ["auf die Erde"]),
  ),
  ch("alma", 23,
    q("a", "17", "Wie nannten sich die bekehrten Lamaniten?", "Anti-Nephi-Lehier", ["Nephi-Lamaniten", "Lehi-Nephiten"], ["Anti-Nephi-Lehier"]),
    q("b", "1", "Was gebot der König der Lamaniten seinem Volk in Bezug auf Ammon und seine Brüder?", "Dass niemand Hand an sie legen durfte", ["Dass sie das Land verlassen mussten", "Dass sie nur in Ischmael predigen durften"], ["Hand an"]),
    q("c", "14", "Welche Gruppen bekehrten sich nicht?", "Die Amalekiten und die Amuloniten", ["Die Nephiten von Zarahemla", "Das Volk von Ischmael und Middoni"], ["Amalekiten", "Amuloniten"]),
  ),
  ch("alma", 24,
    q("a", "3", "Welchen Namen gab der König seinem Sohn, dem er das Königtum übertrug?", "Anti-Nephi-Lehi", ["Anti-Lehi-Nephi", "Nephi-Anti-Lehi"], ["Anti-Nephi-Lehi"]),
    q("b", "16", "Was würden sie laut dem König mit ihren Schwertern tun, wenn ihre Brüder sie vernichten wollten?", "Sie tief in der Erde begraben", ["Sie zu Werkzeugen umschmelzen", "Sie den Nephiten schenken"], ["tief in der Erde"]),
    q("c", "22", "Wie viele von ihnen töteten die Lamaniten ohne Widerstand?", "Eintausendfünf", ["Eintausendzehn", "Fünfhundertfünf"], ["eintausendfünf"]),
  ),
  ch("alma", 25,
    q("a", "11", "Wer war der Erste, der wegen seines Glaubens an Gott den Feuertod erlitt?", "Abinadi", ["Amulek", "Gideon"], ["Abinadi"]),
    q("b", "14", "Was taten die bekehrten Lamaniten mit ihren Kriegswaffen?", "Sie begruben ihre Kriegswaffen in der Erde", ["Sie verkauften ihre Kriegswaffen an die Nephiten", "Sie trugen ihre Kriegswaffen stets bei sich"], ["begruben"]),
    q("c", "16", "Wozu diente das Gesetz des Mose für sie?", "Um ihren Glauben an Christus zu stärken", ["Um ihr Volk von den Nephiten zu trennen", "Um ihren Reichtum im Tempel zu bewahren"], ["Glauben an Christus"]),
  ),
  ch("alma", 26,
    q("a", "4", "Was sagt Ammon über Tausende der Lamaniten?", "Dass sie in die Herde Gottes gebracht wurden", ["Dass sie den Nephiten zu dienen begannen", "Dass sie ihren König vertrieben hätten"], ["Herde Gottes"]),
    q("b", "22", "Was wird laut Ammon dem gegeben, der umkehrt, Glauben ausübt und beständig betet?", "Die Geheimnisse Gottes", ["Ein Platz neben dem König", "Reichtum und Macht im Land"], ["Geheimnisse Gottes"]),
    q("c", "12", "Womit will Ammon prahlen?", "Mit dem Herrn, seinem Gott", ["Mit seiner eigenen Kraft", "Mit seiner eigenen Weisheit"], ["Gott"]),
  ),
  // ===== EINDE =====
];
