import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Helaman (deutsche Ausgabe). Jede Tatsache ist an die Verse in `verses` gebunden; `npm run genees:check` prüft das.
export const helaman: GeneesChapterSeed[] = [
  ch("hel", 1,
    q("a", "3", "Wie hießen die Söhne Pahorans, die um den Richterstuhl stritten?", "Pahoran, Paankhi und Pakumeni", ["Pahoran, Moronihach und Pakumeni", "Pahoran, Paankhi und Pachus"], ["Paankhi", "Pakumeni"]),
    q("b", "10", "Wie hieß der Mann, der Pahoran ermordete?", "Kischkumen", ["Gadianton", "Koriantumr"], ["Kischkumen"]),
    q("c", "15", "Wie hieß der lamanitische Führer, der die Stadt Zarahemla einnahm?", "Koriantumr", ["Zerahemnach", "Lehonti"], ["Koriantumr"]),
  ),
  ch("hel", 2,
    q("a", "4", "Wer war Gadianton?", "Ein Mann, der in vielen Worten gewandt war", ["Der neue oberste Richter des Volkes", "Ein Hauptmann der nephitischen Heere"], ["in vielen Worten"]),
    q("b", "6", "Wer erfuhr in Verkleidung von den Plänen, Helaman zu vernichten?", "Ein Diener Helamans", ["Eine Wache des Königs", "Ein Priester Gadiantons"], ["Diener Helamans"]),
    q("c", "2", "Wozu wurde Helaman, der Sohn Helamans, durch die Stimme des Volkes bestimmt?", "Den Richterstuhl einzunehmen", ["Den Befehl über das Heer zu führen", "Den Tempel zu verwalten"], ["Richterstuhl einzunehmen"]),
  ),
  ch("hel", 3,
    q("a", "21", "Wie hießen die beiden Söhne Helamans?", "Nephi und Lehi", ["Nephi und Aaron", "Lehi und Laman"], ["Nephi", "Lehi"]),
    q("b", "9", "Wo wohnte das Volk im Land nordwärts?", "In Zelten und in Häusern aus Zement", ["In Höhlen und in Häusern aus Holz", "In Städten aus Stein und Bergen"], ["Zement"]),
    q("c", "37", "Wer übernahm den Richterstuhl, als Helaman starb?", "Sein ältester Sohn Nephi", ["Sein jüngster Sohn Lehi", "Sein Bruder Moronihach"], ["Nephi"]),
  ),
  ch("hel", 4,
    q("a", "2", "Wohin gingen die Aufständischen, die aus dem Land gejagt wurden?", "Zum König der Lamaniten", ["In die Berge im Norden", "In das Land der Zoramiten"], ["König der Lamaniten"]),
    q("b", "10", "Welchen Teil ihrer Besitzungen verloren die Nephiten an die Lamaniten?", "Die Hälfte all ihrer Besitzungen", ["Ein Drittel all ihrer Besitzungen", "Ein Zehntel all ihrer Besitzungen"], ["Hälfte all ihrer Besitzungen"]),
    q("c", "12", "Was taten die Nephiten laut Vers 12 in ihrer Schlechtigkeit?", "Sie bedrückten die Armen", ["Sie mieden ihre Tempel", "Sie zahlten keine Steuern"], ["bedrückten"]),
  ),
  ch("hel", 5,
    q("a", "1", "Wem übergab Nephi den Richterstuhl?", "Sezoram", ["Pahoran", "Gideon"], ["Sezoram"]),
    q("b", "19", "Wie viele Lamaniten ließen sich durch die Predigt Nephis und Lehis zur Umkehr taufen?", "Achttausend", ["Zweitausend", "Viertausend"], ["achttausend"]),
    q("c", "24", "Was umschloss Nephi und Lehi im Gefängnis, ohne sie zu verbrennen?", "Eine Feuersäule", ["Eine weiße Wolke", "Eine Lichtmauer"], ["Feuersäule"]),
  ),
  ch("hel", 6,
    q("a", "10", "Wie hießen das südliche und das nördliche Land?", "Der Süden Lehi, der Norden Mulek", ["Der Süden Mulek, der Norden Lehi", "Der Süden Nephi, der Norden Zarahemla"], ["Lehi", "Mulek"]),
    q("b", "15", "Wer wurde im sechsundsechzigsten Jahr von unbekannter Hand ermordet?", "Sezoram", ["Helaman", "Gideon"], ["Sezoram"]),
    q("c", "18", "Von wem war die Bande von Mördern und Räubern gebildet worden?", "Von Kischkumen und Gadianton", ["Von Koriantumr und Tubaloth", "Von Pakumeni und Paankhi"], ["Kischkumen", "Gadianton"]),
  ),
  ch("hel", 7,
    q("a", "10", "Wo befand sich Nephi, als er seine Seele vor Gott ausschüttete?", "Auf einem Turm in seinem Garten", ["Im Tempel von Zarahemla", "Auf einem Berg vor der Stadt"], ["Turm"]),
    q("b", "17", "Welche Frage stellte Nephi dem Volk in Vers 17?", "Warum wollt ihr sterben?", ["Warum wollt ihr fliehen?", "Warum wollt ihr Reichtum?"], ["warum wollt ihr sterben"]),
    q("c", "25", "Mit welcher Bande hatten sich die Menschen vereinigt?", "Mit der geheimen Bande Gadiantons", ["Mit den Wanderern aus dem Norden", "Mit den Lamaniten aus der Wildnis"], ["Gadianton"]),
  ),
  ch("hel", 8,
    q("a", "14", "Was erhob Mose in der Wildnis?", "Die eherne Schlange", ["Einen ehernen Altar", "Das eherne Meer"], ["eherne Schlange"]),
    q("b", "17", "Wer sah das Kommen Christi voraus und war von Frohsinn erfüllt?", "Abraham", ["Henoch", "Elija"], ["Abraham"]),
    q("c", "21", "Welcher der Söhne Zidkijas wurde nicht getötet?", "Mulek", ["Nephi", "Josef"], ["Mulek"]),
  ),
  ch("hel", 9,
    q("a", "3", "Was fanden die fünf Männer vor, als sie zum Richterstuhl kamen?", "Der oberste Richter war zur Erde gefallen", ["Der Richterstuhl war leer und verlassen", "Der oberste Richter hielt eine Volksversammlung"], ["zur Erde gefallen"]),
    q("b", "23", "Wie hieß der ermordete oberste Richter?", "Siezoram", ["Moronihach", "Pakumeni"], ["Siezoram"]),
    q("c", "26", "Zu wessen Haus sollten die Männer laut Nephi gehen?", "Zum Haus Seantums", ["Zum Haus Pakumenis", "Zum Haus Paankhis"], ["Seantum"]),
  ),
  ch("hel", 10,
    q("a", "7", "Was geschieht laut dem Herrn mit dem, was Nephi auf Erden siegelt?", "Es wird im Himmel gesiegelt sein", ["Es wird im Himmel widerrufen werden", "Es wird im Himmel vergessen sein"], ["im Himmel gesiegelt"]),
    q("b", "8", "Was würde geschehen, wenn Nephi zum Tempel sagte, er solle zerbrechen?", "Der Tempel würde entzweibrechen", ["Der Tempel würde in Flammen aufgehen", "Der Tempel würde im Boden versinken"], ["entzweibrechen"]),
    q("c", "9", "Was würde geschehen, wenn Nephi zu diesem Berg sagte: Stürze dich nieder?", "Der Berg würde eben werden", ["Der Berg würde in Flammen stehen", "Der Berg würde entzweigehen"], ["eben"]),
  ),
  ch("hel", 11,
    q("a", "4", "Was erbat Nephi für das Land anstelle des Schwertes?", "Eine Hungersnot", ["Ein Erdbeben", "Eine große Flut"], ["Hungersnot"]),
    q("b", "13", "Was bat Nephi den Herrn auf den Erdboden zu schicken?", "Regen", ["Feuer", "Schnee"], ["Regen"]),
    q("c", "26", "Was wurden die Abtrünnigen im Laufe der Zeit?", "Eine überaus große Räuberbande", ["Ein mächtiges und friedliches Volk", "Ein Heer der Lamaniten"], ["Räuberbande"]),
  ),
  ch("hel", 12,
    q("a", "7", "Als was wird die Nichtigkeit der Menschenkinder in Vers 7 beschrieben?", "Weniger als der Staub der Erde", ["Weniger als der Sand des Meeres", "Weniger als ein Stein im Fluss"], ["Staub der Erde"]),
    q("b", "14", "Was geschieht, wenn Gott zur Erde spricht: Du sollst zurückgehen?", "Der Tag wird um viele Stunden verlängert", ["Die Nacht wird um viele Stunden verlängert", "Die Sonne geht für immer unter"], ["um viele Stunden"]),
    q("c", "23", "Wer wird laut diesen Versen errettet werden?", "Die, die umkehren und auf den Herrn hören", ["Die, die reich sind und viel opfern", "Die, die in ihrem Leben nie gesündigt haben"], ["umkehren"]),
  ),
  ch("hel", 13,
    q("a", "2", "Aus welchem Volk stammte Samuel?", "Aus dem Volk der Lamaniten", ["Aus dem Volk der Nephiten", "Aus dem Volk der Zoramiten"], ["Lamaniten"]),
    q("b", "4", "Worauf stellte sich Samuel, als man ihn nicht in die Stadt ließ?", "Auf die Mauer der Stadt", ["Auf den Turm des Tempels", "Auf einen Hügel vor dem Tor"], ["Mauer"]),
    q("c", "9", "Wie viele Jahre würden laut dem Herrn vergehen, bevor er die Nephiten schlagen lassen würde?", "Keine vierhundert Jahre", ["Keine zweihundert Jahre", "Keine tausend Jahre"], ["keine vierhundert Jahre"]),
  ),
  ch("hel", 14,
    q("a", "2", "In wie vielen Jahren würde der Sohn Gottes laut Samuel kommen?", "Noch fünf Jahre", ["Noch zehn Jahre", "Noch zwanzig Jahre"], ["fünf Jahre"]),
    q("b", "5", "Was wird laut Samuel am Himmel als Zeichen aufgehen?", "Ein neuer Stern", ["Eine neue Sonne", "Ein neuer Mond"], ["neuer Stern"]),
    q("c", "21", "Was wird es laut Samuel viele Stunden lang geben, wenn der Herr den Geist aufgibt?", "Donner und Blitze", ["Ein dreitägiger Hagel", "Ein Sturm ohne Blitz"], ["Donner und Blitze"]),
  ),
  ch("hel", 15,
    q("a", "9", "Was haben die bekehrten Lamaniten laut Samuel begraben?", "Ihre Kriegswaffen", ["Ihre goldenen Götzen", "Ihre Vorräte"], ["Kriegswaffen"]),
    q("b", "1", "Was geschieht laut Samuel mit den Häusern des Volkes, wenn es nicht umkehrt?", "Sie werden verwüstet zurückgelassen", ["Sie werden in Brand gesteckt", "Sie werden den Lamaniten gegeben"], ["verwüstet zurückgelassen"]),
    q("c", "16", "Was wird der Herr laut Vers 16 mit den Lamaniten tun?", "Er wird sie nicht völlig vernichten", ["Er wird sie sofort bestrafen", "Er wird sie für immer vergessen"], ["nicht völlig vernichten"]),
  ),
  ch("hel", 16,
    q("a", "7", "Was tat Samuel, als das Volk Hand an ihn legen wollte?", "Er stürzte sich von der Mauer und floh", ["Er trat dem Volk entgegen und sprach", "Er verbarg sich im Tempel"], ["von der Mauer"]),
    q("b", "4", "Was tat Nephi mit denen, die Samuels Worten glaubten?", "Er taufte sie und rief zur Umkehr", ["Er schickte sie zurück nach Hause", "Er ließ sie Opfer bringen"], ["taufte"]),
    q("c", "13", "In welchem Jahr der Regierung der Richter wurden dem Volk große Zeichen gegeben?", "Im neunzigsten Jahr", ["Im achtzigsten Jahr", "Im hundertsten Jahr"], ["neunzigsten Jahr"]),
  ),
  // ===== EINDE =====
];
