import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Jakob (deutsche Ausgabe). Jede Tatsache ist an die Verse in `verses` gebunden; `npm run genees:check` prüft das.
export const jakob: GeneesChapterSeed[] = [
  ch("jacob", 1,
    q("a", "1", "Wie viele Jahre waren vergangen, seit Lehi Jerusalem verlassen hatte, als Nephi Jakob ein Gebot gab?", "Fünfundfünfzig Jahre", ["Fünfunddreißig Jahre", "Fünfundsiebzig Jahre"], ["Fünfundfünfzig Jahre"]),
    q("b", "11", "Wie wurde der König nach Nephi vom Volk genannt?", "Zweiter Nephi", ["Jüngerer Nephi", "Zweiter Lehi"], ["zweiter Nephi"]),
    q("c", "18", "Durch wessen Hand wurden Jakob und Joseph zu Priestern und Lehrern geweiht?", "Durch die Hand Nephis", ["Durch die Hand Lehis", "Durch die Hand Sams"], ["Hand Nephis"]),
  ),
  ch("jacob", 2,
    q("a", "12", "Wonach begannen viele aus dem Volk laut Jakob zu suchen?", "Gold und Silber", ["Land und Vieh", "Macht und Ruhm"], ["Gold", "Silber"]),
    q("b", "27", "Wie viele Frauen darf ein Mann unter diesem Volk laut dem Herrn haben?", "Nicht mehr als nur eine Frau", ["Nicht mehr als zwei Frauen", "Nicht mehr als sieben Frauen"], ["mehr als nur eine Frau"]),
    q("c", "18", "Wonach soll man laut Jakob trachten, ehe man nach Reichtum trachtet?", "Das Reich Gottes", ["Die Gunst des Königs", "Ein Stück Land"], ["Reich Gottes"]),
  ),
  ch("jacob", 3,
    q("a", "14", "Wie werden die Platten genannt, auf die Jakob schreibt?", "Die Platten Jakobs", ["Die Platten Sams", "Die Platten Josephs"], ["Platten Jakobs"]),
    q("b", "9", "Was gebietet Jakob dem Volk in Bezug auf die Lamaniten?", "Sie wegen ihrer Haut nicht zu schmähen", ["Sie aus dem Land zu vertreiben", "Ihnen Lesen und Schreiben beizubringen"], ["schmähen"]),
    q("c", "1", "Zu wem möchte Jakob in diesem Kapitel zuerst sprechen?", "Zu denen, die im Herzen rein sind", ["Zu denen, die reich an Gold sind", "Zu denen, die das Gesetz verlassen haben"], ["im Herzen rein"]),
  ),
  ch("jacob", 4,
    q("a", "5", "Warum halten Jakob und sein Volk das Gesetz des Mose?", "Weil es ihre Seele auf Christus hinweist", ["Weil der König es von ihnen verlangt", "Weil sie sonst ihr Land verlieren würden"], ["Seele auf"]),
    q("b", "9", "Wodurch ist die Erde laut Jakob erschaffen worden?", "Durch die Macht seines Wortes", ["Durch die Macht seines Armes", "Durch die Hilfe der Engel"], ["Macht seines Wortes"]),
    q("c", "16", "Was wird der Stein, den die Juden verwerfen, laut den Schriften werden?", "Die einzig sichere Grundlage", ["Ein Schmuck für den König", "Das Tor des Tempels in Jerusalem"], ["Grundlage"]),
  ),
  ch("jacob", 5,
    q("a", "3", "Womit vergleicht der Herr laut Zenos das Haus Israel?", "Mit einem edlen Ölbaum", ["Mit einem wilden Weinstock", "Mit einem edlen Feigenbaum"], ["edlen Ölbaum"]),
    q("b", "41", "Was fragte der Herr des Weingartens weinend seinen Diener?", "Was hätte ich sonst noch tun können?", ["Warum hast du mich nicht gewarnt?", "Wer hat diese Bäume gepflanzt?"], ["sonst noch"]),
    q("c", "50", "Was sagte der Diener, als der Herr die Bäume umhauen wollte?", "Verschone ihn noch eine kleine Weile", ["Hole die neuen Diener schnell herbei", "Dann haue sie jetzt alle miteinander um"], ["Verschone ihn"]),
  ),
  ch("jacob", 6,
    q("a", "6", "Welche Frage stellt Jakob dem Volk, das sein Herz verhärtet?", "Warum wollt ihr sterben?", ["Warum wollt ihr fortgehen?", "Warum wollt ihr kämpfen?"], ["warum wollt ihr sterben"]),
    q("b", "11", "Durch welche Pforte soll man laut Jakob eintreten?", "Durch die enge Pforte", ["Durch die goldene Pforte", "Durch die östliche Pforte"], ["enge Pforte"]),
    q("c", "3", "Was wird laut Jakob mit der Welt geschehen?", "Sie wird mit Feuer verbrannt werden", ["Sie wird vom Wasser überflutet werden", "Sie wird vom Sturm verwüstet werden"], ["mit Feuer verbrannt"]),
  ),
  ch("jacob", 7,
    q("a", "1", "Wie hieß der Mann, der unter dem Volk predigte, es werde keinen Christus geben?", "Scherem", ["Korihor", "Nehor"], ["Scherem"]),
    q("b", "15", "Was geschah mit Scherem, nachdem Jakob diese Worte gesprochen hatte?", "Er fiel durch Gottes Macht zur Erde", ["Er floh bei Nacht aus dem Land", "Er wurde vom Volk gefangen gesetzt"], ["zur Erde"]),
    q("c", "27", "Wem gab Jakob die Platten?", "Seinem Sohn Enos", ["Seinem Bruder Joseph", "Seinem Sohn Jarom"], ["Enos"]),
  ),
  // ===== EINDE =====
];
