import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// Mosiah (deutsche Ausgabe). Jede Tatsache ist an die Verse in `verses` gebunden; `npm run genees:check` prüft das.
export const mosiah: GeneesChapterSeed[] = [
  ch("mosiah", 1,
    q("a", "2", "Wie hießen die drei Söhne König Benjamins?", "Mosia, Helorum und Helaman", ["Mosia, Benjamin und Helaman", "Mosia, Helorum und Amaleki"], ["Mosia", "Helorum", "Helaman"]),
    q("b", "16", "Wofür übertrug König Benjamin Mosia neben den Platten ebenfalls die Verantwortung?", "Für das Schwert Labans", ["Für die Krone Zidkijas", "Für die Lade des Bundes"], ["Schwert Labans"]),
    q("c", "12", "Was soll laut König Benjamin nie ausgelöscht werden, außer durch Übertretung?", "Der Name, den er ihnen gibt", ["Der Tempel, den sie bauen", "Das Gesetz, das sie empfangen"], ["Name"]),
  ),
  ch("mosiah", 2,
    q("a", "7", "Was ließ König Benjamin errichten, damit das Volk seine Worte vernehmen konnte?", "Einen Turm", ["Eine Brücke", "Einen Altar"], ["Turm"]),
    q("b", "17", "Was tut ihr laut Benjamin, wenn ihr euren Mitmenschen dient?", "Dann dient ihr eurem Gott", ["Dann dient ihr nur dem König", "Dann dient ihr nur euch selbst"], ["eurem Gott"]),
    q("c", "14", "Womit arbeitete König Benjamin, um seinem Volk zu dienen?", "Mit seinen eigenen Händen", ["Mit Hilfe von Sklaven", "Mit seinen Dienern und Soldaten"], ["eigenen Händen"]),
  ),
  ch("mosiah", 3,
    q("a", "8", "Welchen Namen und welche Mutter nennt der Engel für den Herrn, der kommen wird?", "Jesus Christus und seine Mutter Maria", ["Immanuel und seine Mutter Sara", "Johannes und seine Mutter Elisabeth"], ["Jesus Christus", "Maria"]),
    q("b", "10", "Wann wird er laut dem Engel von den Toten auferstehen?", "Am dritten Tag", ["Am siebten Tag", "Nach vierzig Tagen"], ["dritten Tag"]),
    q("c", "19", "Was ist der natürliche Mensch laut Vers 19, wenn er nicht den Einflüsterungen des Heiligen Geistes nachgibt?", "Ein Feind Gottes", ["Ein Freund der Welt", "Ein Freund der Armen"], ["Feind Gottes"]),
  ),
  ch("mosiah", 4,
    q("a", "1", "Was sah König Benjamin, als er seine Augen über die Menge schweifen ließ?", "Alle waren zur Erde gefallen", ["Alle waren auf der Flucht", "Alle waren eingeschlafen"], ["zur Erde gefallen"]),
    q("b", "19", "Wie nennt Benjamin uns alle in unserer Abhängigkeit von Gott?", "Bettler", ["Reiche", "Fürsten"], ["Bettler"]),
    q("c", "14", "Was werdet ihr laut Benjamin bei euren Kindern nicht zulassen?", "Dass sie hungrig seien oder nackt", ["Dass sie gestraft werden oder krank sind", "Dass sie Durst oder Kälte leiden"], ["hungrig", "nackt"]),
  ),
  ch("mosiah", 5,
    q("a", "7", "Wie werden die Menschen laut Benjamin wegen des Bundes genannt werden?", "Die Kinder Christi", ["Die Diener des Königs", "Die Kinder Benjamins"], ["Kinder Christi"]),
    q("b", "5", "Wozu waren die Menschen bereit, als sie den Bund mit Gott eingingen?", "Gottes Willen zu tun und seine Gebote zu beachten", ["Dem König ihren ganzen Besitz zu geben", "Das Land zu verlassen und anderswo zu wohnen"], ["Willen", "Gebote"]),
    q("c", "14", "Welches Tier seines Nächsten behält laut Benjamin niemand für sich?", "Einen Esel", ["Ein Rind", "Ein Pferd"], ["Esel"]),
  ),
  ch("mosiah", 6,
    q("a", "4", "In welchem Lebensjahr fing Mosia an zu regieren?", "In seinem dreißigsten Lebensjahr", ["In seinem zwanzigsten Lebensjahr", "In seinem vierzigsten Lebensjahr"], ["dreißigsten Lebensjahr"]),
    q("b", "5", "Wie viele Jahre lebte König Benjamin noch, nachdem Mosia König geworden war?", "Noch drei Jahre", ["Noch sieben Jahre", "Noch zehn Jahre"], ["drei Jahre"]),
    q("c", "7", "Wie sorgte König Mosia dafür, seinem Volk nicht zur Last zu fallen?", "Auch er selbst bebaute die Erde", ["Er ließ Sklaven sein Land bestellen", "Er bat das Volk um Geschenke"], ["bebaute die Erde"]),
  ),
  ch("mosiah", 7,
    q("a", "3", "Wer war der Führer der sechzehn starken Männer, die in das Land Lehi-Nephi hinaufzogen?", "Ammon", ["Limhi", "Zeniff"], ["Ammon"]),
    q("b", "4", "Wie viele Tage zogen sie in der Wildnis umher?", "Vierzig Tage", ["Vierzehn Tage", "Siebzig Tage"], ["vierzig Tage"]),
    q("c", "9", "Wer war der König des Volkes im Land Nephi, dem Ammon begegnete?", "Limhi, der Sohn Noas", ["Laman, der Sohn Zeniffs", "Noa, der Sohn Limhis"], ["Limhi", "Noas"]),
  ),
  ch("mosiah", 8,
    q("a", "9", "Woraus waren die vierundzwanzig Platten, die Limhis Männer mitbrachten?", "Aus reinem Gold", ["Aus reinem Kupfer", "Aus reinem Silber"], ["reinem Gold"]),
    q("b", "15", "Was ist ein Seher laut König Limhi?", "Größer als ein Prophet", ["Gleich einem Priester", "Kleiner als ein König"], ["größer als ein Prophet"]),
    q("c", "7", "Wie viele Männer ließ Limhi in die Wildnis ziehen, um das Land Zarahemla zu finden?", "Dreiundvierzig Mann", ["Dreiunddreißig Mann", "Dreiundsechzig Mann"], ["dreiundvierzig"]),
  ),
  ch("mosiah", 9,
    q("a", "1", "Wer ist laut Vers 1 der Erzähler, der als Kundschafter zu den Lamaniten gesandt wurde?", "Zeniff", ["Ammon", "Limhi"], ["Zeniff"]),
    q("b", "11", "Wie viele Jahre hatte Zeniffs Volk im Land gewohnt, als König Laman unruhig wurde?", "Zwölf Jahre", ["Sechs Jahre", "Zwanzig Jahre"], ["zwölf Jahre"]),
    q("c", "18", "Wie viele Lamaniten tötete Zeniffs Volk in einem Tag und einer Nacht?", "Dreitausenddreiundvierzig", ["Zweitausenddreiundvierzig", "Fünftausendsiebenundvierzig"], ["dreitausenddreiundvierzig"]),
  ),
  ch("mosiah", 10,
    q("a", "3", "Wie viele Jahre hatte Zeniffs Volk das Land seiner Väter als Erbteil?", "Zweiundzwanzig Jahre", ["Zweiunddreißig Jahre", "Zweiundvierzig Jahre"], ["zweiundzwanzig Jahre"]),
    q("b", "5", "Welche Arbeiten mussten die Frauen unter Zeniff verrichten?", "Spinnen, arbeiten und feines Leinen herstellen", ["Kochen und die Kinder unterrichten", "Waffen schmieden und Schilde herstellen"], ["spinnen"]),
    q("c", "9", "Wo ließ Zeniff die Frauen und Kinder seines Volkes verbergen?", "In der Wildnis", ["Im hohen Turm", "Hinter den Mauern"], ["Wildnis"]),
  ),
  ch("mosiah", 11,
    q("a", "3", "Welchen Teil von allem, was sie besaßen, forderte König Noa als Steuer?", "Ein Fünftel", ["Ein Zehntel", "Ein Drittel"], ["Fünftel"]),
    q("b", "20", "Wie hieß der Prophet, der unter dem Volk König Noas zu prophezeien begann?", "Abinadi", ["Amulon", "Gideon"], ["Abinadi"]),
    q("c", "12", "Was baute König Noa nahe dem Tempel?", "Einen sehr hohen Turm", ["Einen großen Altar", "Eine breite Stadtmauer"], ["sehr hohen Turm"]),
  ),
  ch("mosiah", 12,
    q("a", "3", "Womit vergleicht Abinadi das Leben König Noas?", "Mit einem Kleid in einem heißen Ofen", ["Mit einer Blume auf dem Feld im Frühling", "Mit einem Stein im reißenden Fluss"], ["Kleid in einem heißen Ofen"]),
    q("b", "17", "Was tat König Noa mit Abinadi?", "Er ließ ihn ins Gefängnis werfen", ["Er ließ ihn sofort hinrichten", "Er ließ ihn aus dem Land verbannen"], ["ins Gefängnis werfen"]),
    q("c", "28", "Was sagten die Priester König Noas, dass sie lehren?", "Das Gesetz des Mose", ["Das Gesetz Noas", "Das Gesetz des Königs"], ["Gesetz des Mose"]),
  ),
  ch("mosiah", 13,
    q("a", "16", "Welchen Tag soll man laut dem Gebot gedenken und heiligen?", "Der Sabbattag", ["Der erste Tag", "Der Erntetag"], ["Sabbattag"]),
    q("b", "28", "Was sagt Abinadi über die Errettung und das Gesetz des Mose?", "Sie kommt nicht durch das Gesetz allein", ["Sie kommt allein durch das Gesetz", "Sie kommt allein durch die Opfer"], ["durch das Gesetz allein"]),
    q("c", "24", "Was darf man laut dem Gebot nicht begehren?", "Das Haus des Nächsten", ["Das Feld des Königs", "Das Gold der Priester"], ["Haus"]),
  ),
  ch("mosiah", 14,
    q("a", "6", "Womit vergleicht Jesaja uns alle, die wir irregegangen sind?", "Mit Schafen", ["Mit Ziegen", "Mit Rindern"], ["Schafe"]),
    q("b", "3", "Wie wird er in Vers 3 genannt?", "Ein Mann der Leiden", ["Ein Mann des Krieges", "Ein Mann der Weisheit"], ["Mann der Leiden"]),
    q("c", "7", "Womit wird er verglichen, als er bedrückt wurde?", "Mit einem Lamm zum Schlachten", ["Mit einem Löwen im Netz", "Mit einem Stier zum Opfer"], ["Lamm zum Schlachten"]),
  ),
  ch("mosiah", 15,
    q("a", "14", "Welche Botschaft haben die heiligen Propheten laut Abinadi zu Zion gesprochen?", "Dein Gott regiert!", ["Dein König kommt!", "Dein Volk ist frei!"], ["Dein Gott regiert"]),
    q("b", "25", "Was haben kleine Kinder laut Abinadi?", "Ewiges Leben", ["Ein Königreich", "Eine Strafe"], ["ewiges Leben"]),
    q("c", "21", "Wie heißt die Auferstehung, von der Abinadi in Vers 21 spricht?", "Die erste Auferstehung", ["Die letzte Auferstehung", "Die dritte Auferstehung"], ["erste Auferstehung"]),
  ),
  ch("mosiah", 16,
    q("a", "8", "Was ist laut Abinadi in Christus verschlungen?", "Der Stachel des Todes", ["Die Macht des Teufels", "Das Gesetz des Mose"], ["Stachel des Todes"]),
    q("b", "9", "Was ist Christus laut Abinadi für die Welt?", "Das Licht und das Leben der Welt", ["Der Richter und der Hirte der Welt", "Der König und der Hüter der Welt"], ["Licht und das Leben der Welt"]),
    q("c", "14", "Wovon ist das Gesetz des Mose laut Abinadi ein Schatten?", "Von dem, was kommen wird", ["Von den früheren Propheten", "Von den ersten Königen"], ["was kommen wird"]),
  ),
  ch("mosiah", 17,
    q("a", "2", "Wie hieß der junge Mann unter den Priestern, der Abinadis Worten glaubte?", "Alma", ["Limhi", "Helam"], ["Alma"]),
    q("b", "20", "Wie starb Abinadi?", "Durch den Feuertod", ["Durch das Schwert", "Durch Steinigung"], ["Feuertod"]),
    q("c", "6", "Nach wie vielen Tagen ließ der König Abinadi wieder vor sich bringen?", "Nach drei Tagen", ["Nach sieben Tagen", "Nach zwei Tagen"], ["nach drei Tagen"]),
  ),
  ch("mosiah", 18,
    q("a", "5", "Wie hieß der Ort mit einer Quelle reinen Wassers, wohin sich Alma begab?", "Mormon", ["Helam", "Schilom"], ["Mormon"]),
    q("b", "16", "Wie viele Menschen taufte Alma bei den Wassern Mormon ungefähr?", "Etwa zweihundertvier Seelen", ["Etwa vierhundertvier Seelen", "Etwa einhundertvier Seelen"], ["zweihundertvier"]),
    q("c", "18", "Wie viele Priester ordinierte Alma im Verhältnis zur Zahl der Menschen?", "Einen Priester für je fünfzig", ["Einen Priester für je hundert", "Einen Priester für je zwanzig"], ["Priester für je fünfzig"]),
  ),
  ch("mosiah", 19,
    q("a", "4", "Wer zog sein Schwert gegen König Noa?", "Gideon", ["Limhi", "Helam"], ["Gideon"]),
    q("b", "20", "Was taten die Männer mit König Noa, nachdem er ihnen geboten hatte, nicht zurückzukehren?", "Sie ließen ihn bis zum Feuertod leiden", ["Sie ließen ihn frei in der Wildnis zurück", "Sie brachten ihn zurück in seinen Palast"], ["Feuertod"]),
    q("c", "26", "Was schwor Limhi dem König der Lamaniten?", "Dass sein Volk ihm Tribut zahlen werde", ["Dass sein Volk das Land verlassen werde", "Dass sein Volk ihn als Gott anbeten werde"], ["Tribut zahlen"]),
  ),
  ch("mosiah", 20,
    q("a", "5", "Wie viele Töchter der Lamaniten wurden von den Priestern Noas entführt?", "Vierundzwanzig", ["Sechsundzwanzig", "Einundzwanzig"], ["vierundzwanzig"]),
    q("b", "10", "Womit wird der Kampf von Limhis Volk verglichen?", "Mit Löwen um ihre Beute", ["Mit Wölfen um ihre Herde", "Mit Bären um ihre Jungen"], ["Löwen"]),
    q("c", "17", "Wer war der Hauptmann des Königs, der den König bat, nicht nachzuforschen?", "Gideon", ["Helam", "Amulon"], ["Gideon"]),
  ),
  ch("mosiah", 21,
    q("a", "26", "Womit war das Land übersät, das Limhis Männer fanden?", "Mit verdorrten Gebeinen", ["Mit dicken Staubwolken", "Mit goldenen Standbildern"], ["verdorrten Gebeinen"]),
    q("b", "17", "Was gebot König Limhi jedem Mann wegen der vielen Witwen?", "Zum Unterhalt der Witwen beizutragen", ["Dem König ein Zehntel seiner Ernte zu geben", "Eine Witwe aus seiner Familie zu heiraten"], ["Unterhalt der Witwen"]),
    q("c", "33", "Warum konnten sich Limhi und sein Volk nicht taufen lassen?", "Es gab niemanden mit Vollmacht von Gott", ["Es gab im ganzen Land kein Wasser dafür", "Der König hatte es streng verboten"], ["Vollmacht von Gott"]),
  ),
  ch("mosiah", 22,
    q("a", "6", "Welchen Fluchtweg schlug Gideon vor?", "Durch die hintere Mauer der Stadt", ["Durch das große Tor der Stadt", "Über den Fluss mit Schiffen"], ["hintere Mauer"]),
    q("b", "10", "Was sandte Limhi den Lamaniten als Tribut und als Geschenk?", "Wein", ["Brot", "Obst"], ["Wein"]),
    q("c", "13", "In welches Land kam Limhis Volk nach vielen Tagen in der Wildnis?", "Das Land Zarahemla", ["Das Land Helam", "Das Land Schilom"], ["Zarahemla"]),
  ),
  ch("mosiah", 23,
    q("a", "3", "Wie weit floh Almas Volk in die Wildnis?", "Acht Tagereisen", ["Vier Tagereisen", "Zwölf Tagereisen"], ["acht Tagereisen"]),
    q("b", "19", "Wie nannte Almas Volk das Land, in dem es sich niederließ?", "Helam", ["Mormon", "Lehi"], ["Helam"]),
    q("c", "6-7", "Wen wollte Almas Volk als König haben?", "Alma, aber er lehnte ab", ["Gideon, aber er lehnte ab", "Helam, aber er lehnte ab"], ["Alma"]),
  ),
  ch("mosiah", 24,
    q("a", "20", "Wie nannten Alma und sein Volk das Tal, in dem sie ihre Zelte aufschlugen?", "Das Tal Alma", ["Das Tal Helam", "Das Tal Amulon"], ["Tal Alma"]),
    q("b", "19", "Was tat der Herr zur Zeit ihrer Flucht mit den Lamaniten?", "Er ließ einen tiefen Schlaf über sie kommen", ["Er ließ einen großen Sturm aufziehen", "Er ließ ihre Waffen verschwinden"], ["tiefen Schlaf"]),
    q("c", "25", "Nach wie vielen Tagen in der Wildnis kam Almas Volk in Zarahemla an?", "Nach zwölf Tagen", ["Nach sechs Tagen", "Nach vierzig Tagen"], ["zwölf Tage"]),
  ),
  ch("mosiah", 25,
    q("a", "23", "Wie viele Gemeinden gab es im Land Zarahemla?", "Sieben Gemeinden", ["Drei Gemeinden", "Zwölf Gemeinden"], ["sieben Gemeinden"]),
    q("b", "17", "Wer wollte sich taufen lassen, nachdem Alma das Volk gelehrt hatte?", "König Limhi", ["König Mosia", "König Noa"], ["Limhi"]),
    q("c", "2", "Wessen Abkömmling war Zarahemla?", "Ein Abkömmling Muleks", ["Ein Abkömmling Nephis", "Ein Abkömmling Lamans"], ["Mulek"]),
  ),
  ch("mosiah", 26,
    q("a", "8", "Wem hatte König Mosia die Vollmacht über die Kirche gegeben?", "Alma", ["Limhi", "Helam"], ["Alma"]),
    q("b", "22", "Wozu wird laut dem Herrn getauft, wer auch immer getauft wird?", "Zur Umkehr", ["Zum Reichtum", "Zur Freiheit"], ["zur Umkehr"]),
    q("c", "30", "Wie oft will der Herr seinem Volk laut Vers 30 seine Verfehlungen vergeben?", "Sooft es zu ihm umkehrt", ["Höchstens siebenmal im Jahr", "Nur bei der ersten Sünde"], ["sooft"]),
  ),
  ch("mosiah", 27,
    q("a", "11", "Wer erschien Alma dem Jüngeren und den Söhnen Mosias?", "Der Engel des Herrn", ["Der Prophet Abinadi", "Der König von Zarahemla"], ["Engel des Herrn"]),
    q("b", "23", "Wie lange fasteten und beteten die Priester und das Volk, bevor Almas Glieder ihre Kraft empfingen?", "Zwei Tage und zwei Nächte", ["Drei Tage und drei Nächte", "Sieben Tage und sieben Nächte"], ["zwei Tage", "zwei Nächte"]),
    q("c", "34", "Wie hießen die vier Söhne Mosias?", "Ammon, Aaron, Omner und Himni", ["Ammon, Aaron, Helam und Gideon", "Ammon, Omner, Himni und Limhi"], ["Ammon", "Aaron", "Omner", "Himni"]),
  ),
  ch("mosiah", 28,
    q("a", "5", "Wohin wollten die Söhne Mosias gehen, um zu predigen?", "In das Land Nephi", ["In das Land Helam", "In das Land Schilom"], ["Land Nephi"]),
    q("b", "13", "Womit hatte Mosia die Aufzeichnungen des vernichteten Volkes übersetzt?", "Mit zwei Steinen in einem Bügel", ["Mit einer goldenen Brille aus Silber", "Mit einer Rolle aus feinem Pergament"], ["zwei Steine"]),
    q("c", "20", "Wem übergab Mosia die Platten aus Messing und die übrigen Gegenstände?", "An Alma", ["An Ammon", "An Aaron"], ["Alma"]),
  ),
  ch("mosiah", 29,
    q("a", "2", "Wen wollte das Volk zuerst als König haben?", "Aaron", ["Ammon", "Himni"], ["Aaron"]),
    q("b", "42", "Wer wurde zum ersten obersten Richter bestimmt?", "Alma", ["Aaron", "Limhi"], ["Alma"]),
    q("c", "46", "In welchem Jahr seiner Regierung starb Mosia?", "Im dreiunddreißigsten Jahr", ["Im dreiundzwanzigsten Jahr", "Im dreiundvierzigsten Jahr"], ["dreiunddreißigsten Jahr"]),
  ),
  // ===== EINDE =====
];
