import type { GeneesChapterSeed } from "../../../src/lib/snelleZendeling/reviveBank";
import { ch, q } from "../helpers";

// 4 Nephi, Mormon, Ether und Moroni (deutsche Ausgabe). Jede Tatsache ist an die Verse in `verses` gebunden; `npm run genees:check` prüft das.
export const slot: GeneesChapterSeed[] = [
  ch("4-ne", 1,
    q("a", "3", "Was hatten die Menschen nach ihrer Bekehrung unter sich?", "Sie hatten alles unter sich gemeinsam", ["Sie hatten alles in Privatbesitz", "Alles gehörte den Richtern des Landes"], ["gemeinsam"]),
    q("b", "17", "Wie waren die Menschen laut Vers 17 geworden?", "Alle waren eins, die Kinder Christi", ["Sie waren in viele Stände geteilt", "Sie waren in Nephiten und Lamaniten geteilt"], ["Kinder Christi"]),
    q("c", "48", "Wer verbarg die heiligen Aufzeichnungen für den Herrn?", "Ammaron", ["Mormon", "Moroni"], ["Ammaron"]),
  ),
  ch("morm", 1,
    q("a", "2", "Wie alt war Mormon, als Ammaron zu ihm kam?", "Ungefähr zehn Jahre", ["Ungefähr vierzehn Jahre", "Ungefähr sieben Jahre"], ["zehn Jahre"]),
    q("b", "3", "Wann sollte sich Mormon laut Ammaron an das erinnern, was er beobachtet hatte?", "Als er ungefähr vierundzwanzig war", ["Als er ungefähr dreißig Jahre alt war", "Als er ungefähr achtzehn war"], ["vierundzwanzig"]),
    q("c", "15", "Wie alt war Mormon, als der Herr ihn besuchte?", "Fünfzehn Jahre", ["Zwölf Jahre", "Zwanzig Jahre"], ["fünfzehn Jahre"]),
  ),
  ch("morm", 2,
    q("a", "2", "In welchem Lebensjahr führte Mormon ein Heer an?", "In seinem sechzehnten Jahr", ["In seinem achtzehnten Jahr", "In seinem zwanzigsten Jahr"], ["sechzehnten Jahr"]),
    q("b", "9", "Wie hieß der König der Lamaniten, der mit einem großen Heer angriff?", "Aaron", ["Lamoni", "Zoram"], ["Aaron"]),
    q("c", "29", "Was gaben die Lamaniten den Nephiten im Vertrag?", "Das Land nordwärts", ["Das Land südwärts", "Das Land Zarahemla"], ["Land nordwärts"]),
  ),
  ch("morm", 3,
    q("a", "11", "Was weigerte sich Mormon wegen ihrer Schlechtigkeit fortan zu sein?", "Ihr Befehlshaber und Führer", ["Ihr König und ihr Richter", "Ihr Priester und ihr Lehrer"], ["Befehlshaber und Führer"]),
    q("b", "13", "Wie oft hatte Mormon sein Volk aus den Händen seiner Feinde befreit?", "Dreimal", ["Zweimal", "Viermal"], ["dreimal"]),
    q("c", "17", "An wen schreibt Mormon laut Vers 17?", "An die Anderen und das Haus Israel", ["Nur an die Nephiten seiner eigenen Zeit", "An den König und seine Heerführer"], ["Anderen", "Haus Israel"]),
  ),
  ch("morm", 4,
    q("a", "2", "In welches Land wurden die Heere der Nephiten zurückgejagt?", "Das Land Verwüstung", ["Das Land Jerschon", "Das Land Zarahemla"], ["Land Verwüstung"]),
    q("b", "5", "Wodurch werden die Schlechten laut Mormon bestraft?", "Durch die Schlechten", ["Durch die Engel", "Durch die Rechtschaffenen"], ["durch die Schlechten"]),
    q("c", "23", "Wohin ging Mormon, als die Lamaniten das Land zu Fall zu bringen drohten?", "Zum Hügel Schim", ["Zum Hügel Manti", "Zum Hügel Riplah"], ["Hügel Schim"]),
  ),
  ch("morm", 5,
    q("a", "17", "Wen hatten die Nephiten einst als ihren Hirten?", "Christus als ihren Hirten", ["Mose als ihren Hirten", "Nephi als ihren Hirten"], ["Christus als ihren Hirten"]),
    q("b", "18", "Womit wird das Volk verglichen, das vom Satan umhergeführt wird?", "Mit Spreu, die vom Wind gejagt wird", ["Mit einem Schaf, das von der Herde irrt", "Mit Staub, der auf den Bergen liegt"], ["Spreu"]),
    q("c", "22", "Was fragt Mormon die Anderen?", "Wie sie vor der Macht Gottes bestehen können", ["Wie sie das Land bewahren können", "Wie sie ihren Reichtum vergrößern können"], ["vor der Macht Gottes bestehen"]),
  ),
  ch("morm", 6,
    q("a", "4", "In welches Land marschierten die Nephiten, um sich zu sammeln?", "Das Land Cumorah", ["Das Land Moroni", "Das Land Josua"], ["Cumorah"]),
    q("b", "11", "Wie viele von Mormons Volk blieben nach der Schlacht übrig?", "Vierundzwanzig", ["Siebenundzwanzig", "Einundzwanzig"], ["vierundzwanzig"]),
    q("c", "3", "Wie reagierte der König der Lamaniten auf Mormons Bitte?", "Er gewährte, was Mormon wünschte", ["Er lehnte Mormons Bitte entschieden ab", "Er ließ den Brief verbrennen und schwieg"], ["gewährte"]),
  ),
  ch("morm", 7,
    q("a", "2", "Von welchem Haus ist der Überrest des Volkes laut Mormon?", "Vom Haus Israel", ["Vom Haus Juda", "Vom Haus David"], ["Haus Israel"]),
    q("b", "4", "Was müssen sie laut Mormon niederlegen?", "Ihre Kriegswaffen", ["Ihre goldenen Götzen", "Ihre Schätze"], ["Kriegswaffen"]),
    q("c", "8", "In wessen Namen sollen sie sich laut Mormon taufen lassen?", "Im Namen Jesu", ["Im Namen Mormons", "Im Namen Nephis"], ["Namen Jesu"]),
  ),
  ch("morm", 8,
    q("a", "1", "Wer führt den Bericht seines Vaters Mormon zu Ende?", "Moroni", ["Nephi", "Helaman"], ["Moroni"]),
    q("b", "6", "Wie viele Jahre waren seit dem Kommen Christi vergangen?", "Vierhundert Jahre", ["Dreihundert Jahre", "Fünfhundert Jahre"], ["vierhundert Jahre"]),
    q("c", "23", "Welche Prophezeiungen soll man laut Moroni erforschen?", "Die Prophezeiungen Jesajas", ["Die Prophezeiungen Jeremias", "Die Prophezeiungen Moses"], ["Prophezeiungen Jesajas"]),
  ),
  ch("morm", 9,
    q("a", "9", "Wie ist Gott laut Mormon?", "Derselbe gestern, heute und immerdar", ["Veränderlich, je nach Zeiten und Völkern", "Nur im Tempel gegenwärtig"], ["gestern, heute und immerdar"]),
    q("b", "32", "In welcher Schrift schrieben Mormon und Moroni ihren Bericht?", "Das sogenannte reformierte Ägyptisch", ["Das alte Hebräisch der Priester", "Das aramäische Syrisch der Händler"], ["reformierte Ägyptisch"]),
    q("c", "21", "Was verheißt Moroni dem, der an Christus glaubt und in nichts zweifelt?", "Alles, was er im Namen Christi vom Vater erbittet", ["Eine Befreiung von allen Prüfungen und Leiden", "Einen Platz in jedem Königreich der Erde"], ["Vater"]),
  ),
  ch("ether", 1,
    q("a", "2", "Aus wie vielen Platten entnimmt Moroni seinen Bericht über die vernichteten früheren Bewohner?", "Aus vierundzwanzig Platten", ["Aus zwölf goldenen Platten", "Aus achtundvierzig Platten"], ["vierundzwanzig Platten"]),
    q("b", "34-35", "Was geschah mit der Sprache Jareds und seines Bruders beim großen Turm?", "Ihre Sprache wurde nicht verwirrt", ["Ihre Sprache wurde teilweise verändert", "Ihre Sprache wurde vollständig ersetzt"], ["nicht verwirrt"]),
    q("c", "38,42", "Was verhieß der Herr über das Land, in das er Jareds Bruder führen würde?", "Dass es vor allen Ländern erwählt war", ["Dass es fruchtbarer war als Ägypten", "Dass es nahe beim Turm lag"], ["erwählt"]),
  ),
  ch("ether", 2,
    q("a", "3", "Was bedeutet das Wort Deseret, das die Jarediten mitnahmen?", "Eine Honigbiene", ["Eine Feldmaus", "Ein Süßwasserfisch"], ["Honigbiene"]),
    q("b", "14", "Wie lange sprach der Herr mit Jareds Bruder, als er ihn züchtigte?", "Drei Stunden lang", ["Sieben Stunden lang", "Zwei Stunden lang"], ["drei Stunden"]),
    q("c", "17", "Wie dicht waren die Boote der Jarediten gebaut?", "So dicht wie eine Schüssel", ["So dicht wie eine Tonne", "So dicht wie ein Wasserkrug"], ["dicht wie eine Schüssel"]),
  ),
  ch("ether", 3,
    q("a", "1", "Wie viele kleine Steine schmolz Jareds Bruder aus einem Felsen auf dem Berg Schelem?", "Sechzehn Steine", ["Zwölf Steine", "Achtzehn Steine"], ["sechzehn"]),
    q("b", "4-6", "Wie machte der Herr die Steine leuchtend, als Jareds Bruder ihn darum bat?", "Er berührte sie mit seinem Finger", ["Er blies mit seinem Atem darüber", "Er ließ einen Feuerstrahl darauf fallen"], ["Finger"]),
    q("c", "21-22", "Was sollte Jareds Bruder mit dem tun, was er gesehen und gehört hatte?", "Es niederschreiben und versiegeln", ["Es sofort dem Volk erzählen", "Es an seine eigenen Söhne weitergeben"], ["niederschreiben", "versiegeln"]),
  ),
  ch("ether", 4,
    q("a", "1", "Wann durfte das, was Jareds Bruder schrieb, zu den Menschenkindern gelangen?", "Nachdem er auf dem Kreuz emporgehoben war", ["Nachdem die Nephiten vernichtet waren", "Nachdem er in den Himmel aufgefahren war"], ["auf dem Kreuz"]),
    q("b", "3,5", "Was gebot der Herr Moroni in Bezug auf die Aufzeichnungen von Jareds Bruder?", "Sie abermals in der Erde zu verbergen", ["Sie vor der Entdeckung zu verbrennen", "Sie den Lamaniten zur Aufbewahrung zu geben"], ["Erde", "verbergen"]),
    q("c", "6-7", "Wann würde der Herr den Anderen offenbaren, was Jareds Bruder gesehen hat?", "Wenn sie umkehren und Glauben ausüben", ["Wenn sie ihre Kriege beendet haben", "Wenn sie die Platten selbst gefunden haben"], ["umkehren", "Glauben"]),
  ),
  ch("ether", 5,
    q("a", "3", "Wie vielen Zeugen würden die Platten durch die Macht Gottes gezeigt werden?", "Drei Zeugen", ["Zwölf Zeugen", "Sieben Zeugen"], ["drei"]),
    q("b", "1", "Was durfte laut Moroni mit dem geschehen, was er versiegelt hatte?", "Niemand durfte es übersetzen", ["Niemand durfte es fortbringen", "Niemand durfte es ansehen"], ["übersetzen"]),
    q("c", "5", "Was geschieht mit dem, der umkehrt und im Namen Jesu zum Vater kommt?", "Er wird in das Reich Gottes aufgenommen", ["Er erhält die Macht, die Platten zu öffnen", "Er empfängt die Gabe, die Platten zu übersetzen"], ["Reich Gottes"]),
  ),
  ch("ether", 6,
    q("a", "11", "Wie lange wurden die Jarediten auf dem Wasser hingetrieben, bis sie das verheißene Land erreichten?", "Dreihundertvierundvierzig Tage", ["Dreihundertfünfundsechzig Tage", "Einhundertzweiundvierzig Tage"], ["dreihundertvierundvierzig"]),
    q("b", "9", "Was tat Jareds Bruder den ganzen Tag, während sie auf dem Wasser getrieben wurden?", "Er lobsang dem Herrn und pries ihn", ["Er hielt bei den Steinen Wache", "Er las laut aus dem Bericht vor"], ["lobsang"]),
    q("c", "27", "Welcher der Söhne Jareds wurde zum König über das Volk gesalbt?", "Orihach, ein Sohn Jareds", ["Gilgach, ein Sohn Jareds", "Jakom, ein Sohn Jareds"], ["Orihach"]),
  ),
  ch("ether", 7,
    q("a", "9", "Was machte Schul aus dem Hügel Efraim für die Männer, die er mit sich geführt hatte?", "Schwerter aus Stahl", ["Pfeilspitzen aus Bronze", "Schilde aus Kupfer"], ["Schwerter aus Stahl"]),
    q("b", "4", "Wie alt war Chorihor, als er sich gegen seinen Vater Kib auflehnte?", "Zweiunddreißig Jahre", ["Einundzwanzig Jahre", "Fünfundvierzig Jahre"], ["zweiunddreißig Jahre"]),
    q("c", "24-25", "Was tat König Schul für die Propheten, die vom Volk geschmäht wurden?", "Er gab ihnen Macht, hinzugehen, wo auch immer sie wollten", ["Er gab ihnen Soldaten mit, die sie überall schützten", "Er ließ sie in einer Stadt unter seinem Schutz wohnen"], ["wo auch immer sie wollten"]),
  ),
  ch("ether", 8,
    q("a", "10-11", "Was tat die Tochter Jareds, um Akisch, dem Sohn Kimnors, zu gefallen?", "Sie tanzte vor ihm", ["Sie sang vor ihm", "Sie schenkte ihm Wein"], ["tanzte"]),
    q("b", "12", "Was verlangte Jared von Akisch im Austausch für seine Tochter?", "Den Kopf seines Vaters, des Königs", ["Einen großen Teil seines Goldes", "Die Schlüssel der größten Stadt"], ["Kopf", "Königs"]),
    q("c", "19", "Was sagt Moroni über den Herrn und geheime Verbindungen?", "Der Herr wirkt nicht in geheimen Verbindungen", ["Der Herr benutzt sie, um sein Volk zu prüfen", "Der Herr duldet sie nur unter seinen Propheten"], ["nicht in geheimen Verbindungen"]),
  ),
  ch("ether", 9,
    q("a", "3", "Wie wurde Omer gewarnt, dass er das Land verlassen musste?", "Der Herr warnte ihn in einem Traum", ["Ein Engel erschien ihm auf einem Berg", "Ein Prophet sprach ihn am Tor an"], ["Traum"]),
    q("b", "22", "Wen sah König Emer, über den er sich freute und frohlockte?", "Den Sohn der Rechtschaffenheit", ["Einen Engel des Herrn im Traum", "Einen Propheten aus dem Norden"], ["Sohn der Rechtschaffenheit"]),
    q("c", "35", "Was geschah, nachdem sich das Volk vor dem Herrn genügend gedemütigt hatte?", "Der Herr sandte Regen auf den Erdboden", ["Der Herr sandte Manna vom Himmel", "Der Herr ließ die Giftschlangen verschwinden"], ["Regen"]),
  ),
  ch("ether", 10,
    q("a", "5", "Womit belastete König Riplakisch das Volk?", "Mit schweren Steuern", ["Mit Pflichtdienst im Heer", "Mit harter Zwangsarbeit"], ["schweren Steuern"]),
    q("b", "20", "Wo bauten die Jarediten in den Tagen Libs eine große Stadt?", "An der schmalen Landenge", ["Beim Hügel Schim im Süden", "Im Tal Nimrod am Fluss"], ["schmalen Landenge"]),
    q("c", "23", "Welche vier Metalle gruben die Jarediten in den Tagen Libs aus der Erde?", "Gold, Silber, Eisen und Kupfer", ["Gold, Silber, Zinn und Blei", "Silber, Eisen, Zinn und Bronze"], ["Gold", "Silber", "Eisen", "Kupfer"]),
  ),
  ch("ether", 11,
    q("a", "5", "Was tat der Bruder Schibloms mit den Propheten, die die Vernichtung des Volkes prophezeiten?", "Er ließ sie alle hinrichten", ["Er verbannte sie in die Wildnis", "Er ließ sie in Moron einsperren"], ["hinrichten"]),
    q("b", "2", "Zu wem flüchteten die Propheten um Schutz, als das Volk sie vernichten wollte?", "Zu König Kom", ["Zu König Omer", "Zu König Schul"], ["Kom"]),
    q("c", "20-21", "Was würde Gott, der Herr, in den Tagen Koriantors tun, wenn das Volk nicht umkehrte?", "Ein anderes Volk senden, das Land zu besitzen", ["Ihren König durch einen Propheten ersetzen", "Das Land unter dem Meer verschwinden lassen"], ["anderes Volk"]),
  ),
  ch("ether", 12,
    q("a", "6", "Was ist Glaube laut Moroni?", "Dass man etwas erhofft und es nicht sieht", ["Dass man sicher weiß, was man schon gesehen hat", "Dass man glaubt, was man selbst beweisen kann"], ["nicht sieht"]),
    q("b", "13", "Durch wessen Glauben stürzte laut Moroni das Gefängnis zur Erde?", "Der Glaube Almas und Amuleks", ["Der Glaube Abinadis und Limhis", "Der Glaube Ammons und seiner Brüder"], ["Almas und Amuleks"]),
    q("c", "30", "Was geschah, als Jareds Bruder zum Berg Zerin sprach?", "Er wurde fortgerückt", ["Er spaltete sich entzwei", "Er begann zu beben"], ["fortgerückt"]),
  ),
  ch("ether", 13,
    q("a", "6", "Für wen sollte das Neue Jerusalem auf diesem Land erbaut werden?", "Für den Überrest der Nachkommen Josefs", ["Für den Überrest der Nachkommen Judas", "Für die letzten Anhänger der Jarediten"], ["Überrest", "Nachkommen Josefs"]),
    q("b", "13", "Wo verbarg sich Ether, nachdem das Volk ihn verworfen hatte?", "In einer Felsenhöhle bei Tag", ["In einer Grotte am Meer bei Tag", "In einem Brunnen in der Wildnis"], ["Felsenhöhle"]),
    q("c", "31", "Wo verwundete Schared Koriantumr, sodass dieser zwei Jahre lang nicht in den Kampf zog?", "Am Schenkel", ["An der Schulter", "Am Oberarm"], ["Schenkel"]),
  ),
  ch("ether", 14,
    q("a", "10", "Worin übertraf Lib die anderen Männer des Volkes?", "Er war von großer Statur", ["Er hatte den größten Reichtum", "Er hatte das größte Heer"], ["großer Statur"]),
    q("b", "17", "Wessen Bruder war Schiz, der viele Städte eroberte und niederbrannte?", "Der Bruder Libs", ["Der Bruder Koms", "Der Bruder Kibs"], ["Libs"]),
    q("c", "21-23", "Wodurch wurde das Volk bei Tag und bei Nacht geplagt, als das ganze Land mit Leichen bedeckt war?", "Durch den Gestank der Toten", ["Durch Giftschlangen auf dem Weg", "Durch einen Mangel an Wasser"], ["Gestank"]),
  ),
  ch("ether", 15,
    q("a", "2", "Wie viele mächtige Männer waren schon getötet, als Koriantumr im Herzen zu trauern begann?", "Zwei Millionen Männer", ["Vier Millionen Männer", "Eine halbe Million Männer"], ["zwei Millionen"]),
    q("b", "11", "An welchem Hügel schlug das Heer Koriantumrs seine Zelte auf, wo Mormon die heiligen Aufzeichnungen verborgen hatte?", "Der Hügel Rama", ["Der Hügel Schim", "Der Hügel Manti"], ["Hügel Rama"]),
    q("c", "30", "Was tat Koriantumr, nachdem er sich auf sein Schwert gelehnt hatte, um sich ein wenig auszuruhen?", "Er schlug Schiz mit dem Schwert den Kopf ab", ["Er ergab sich Schiz und seinem ganzen Heer", "Er blies für sein Heer eine laute Posaune"], ["den Kopf ab"]),
  ),
  // ===== EINDE =====
];
